### ISSUE TITLE
Fix french translation on connect wallet screen

### ISSUE THREAD

**Issue by chxash** [shapeshift/web#1049]
Some i18n texts are not correct in french, see screenshots attached.

![fr1](https://user-images.githubusercontent.com/5720927/154847798-100bbc25-367b-4ad8-b621-1344d4379844.png)
![fr2](https://user-images.githubusercontent.com/5720927/154847800-3ae5f986-11b7-43ff-8700-5f73d3a44126.png)

**Comment by gomesalexandre** [comment]
The not-yet translated entries are expected, have a look at the PR for initial translations: https://github.com/shapeshift/web/pull/924 - it's not exhaustive and more translations are yet to be added!

As for the missing keys, these were added in a later PR. Quoting my earlier discussion with @LPX55:

```
at the moment we're working with engineering to find a solution for a more streamlined and reasonable workflow!
```

I think it would be a great value to have some json diff that adds the missing entries as "TODO" in the meantime.

**Comment by chxash** [comment]
@gomesalexandre ok thank you :) closing this issue !
