### ISSUE TITLE
Fix Dashboard page not loading when refreshing with a KeepKey connected

### ISSUE THREAD

**Issue by cjthompson** [shapeshift/web#1057]
## Any contributor that wishes to be assigned this ticket MUST already own a KeepKey
_Contributors without a KeepKey will not be approved. Please do not ask for a free KeepKey in order to quality for this bounty._

A new feature was recently added that saves information about the paired wallet into LocalStorage. When the app is loaded or refreshed, that information is used to re-create the wallet state so that a user doesn't have to pair a wallet every time.

The feature correctly works correctly for software wallets (ShapeShift, MetaMask, Portis) but does not work correctly for KeepKey.

This feature must work the same for both software and hardware wallets.

### Reference

See #904 and #1034 

### Acceptance Criteria

* Pairing a KeepKey works and the Dashboard, Assets, and Accounts pages load correctly
* Refreshing the page after pairing a KeepKey should restore the previous application state
* After refreshing, the app must show the correct KeepKey device label in the upper-right corner
* After refreshing, the app must load the Dashboard page fully and correctly including showing the correct wallet balance and assets
* After refreshing, the app must correctly load the Assets, Accounts, and Defi pages
* If a KeepKey is currently paired and **CONNECTED** via USB, refreshing the app must show the KeepKey as connected (no "disconnected" error icon)
* If a KeepKey is currently paired and **DISCONNECTED** via USB, refreshing the app must show the KeepKey as disconnected (a warning icon in the wallet menu) and show an error message when the user attempts to take an action that requires the private key (Send, Trade, Defi)

_Note: some of these requirements are already implemented (such as showing the disconnected state) but they are listed here as requirements for this ticket to ensure that they are tested and working as expected._

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

**Comment by cjthompson** [comment]
@0xean - Now that this has been merged into develop, we need to test how it works when deployed to CloudFlare vs Fleek before putting this out as a bounty. It's possible that some of these issues were due to the Fleek deployment.

Please do not bounty this until we can get a few people to test the current code at https://develop.web-29e.pages.dev

**Comment by 0xean** [comment]
as far as I can tell this is all working on the dev deployment.
