### ISSUE TITLE
Update Cosmos (Atom) asset names to be chain specific

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#1153]
Currently, both "Cosmos (Atom)" assets have the same name

<img width="310" alt="Screen Shot 2022-03-08 at 11 48 58 am" src="https://user-images.githubusercontent.com/97164662/157305070-10ee830d-dc43-4d29-afa2-3ebda45e222d.png">

This makes for a confusing UX when searching for the asset - we should include the chain name/identifier in the asset name.

**Comment by 0xdef1cafe** [comment]
closed in https://github.com/shapeshift/lib/pull/477
