### ISSUE TITLE
IPFS: Support Setting Headers

### ISSUE THREAD

**Issue by con5cience** [shapeshift/web#1154]
### Overview

When operating from IPFS, the Shapeshift Web v2 application needs the ability to set request/response headers for an assortment of reasons, including but not limited to:
* Security
* Ensuring browsers and other content consumers are able to properly parse content (i.e. `Content-Type`).

### Reference

Direction:
* Use service worker to set headers.
* Service worker architecture will also be required for Pendo integration in the alpha site.
* Only one service worker allowed, so it needs to do everything.

### Acceptance Criteria

Shapeshift Web v2 can properly set request/response headers.

**Comment by 0xdef1cafe** [comment]
blocked by https://github.com/shapeshift/web/issues/1545
