### ISSUE TITLE
IPFS: Application Redirects

### ISSUE THREAD

**Issue by con5cience** [shapeshift/web#1155]
### Overview

Shapeshift Web v2 needs to handle 404s with an ipfs-404.html that returns the actual index.html + a HTTP 404 response code, or a meta-direct to /index.html.

### Reference

Extra context:

Handle 404s with a `ipfs-404.html` that returns `index.html` with a HTTP 404 response code, or a meta-direct to `/index.html`.

### Acceptance Criteria

Application can handle 302 or meta directs when running on IPFS.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info

**Comment by 0xdef1cafe** [comment]
partially solved by hash routing https://github.com/shapeshift/web/pull/1457

**Comment by 0xdef1cafe** [comment]
outstanding scope of work - add an `ipfs-404.html` page to `/public` and with an html meta redirect back to `index.html`

docs - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
