### ISSUE TITLE
Confirm Trade Modal UI/UX fix

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#1164]
### Overview

Whenever the amount is too long, it breaks the line between the check box and the asset icon and the value shifts ups. (because of the wrapping onto 2 lines)

### Reference

This change will be made in web.

### Acceptance Criteria

A/C: The line in the graphic on the "Confirm Trade" Modal is straight and consistent throughout regardless of the asset, asset amount, etc. 

### Screenshots/Mockups

<img width="433" alt="Screen_Shot_2022-03-10_at_11 42 02_AM" src="https://user-images.githubusercontent.com/57505863/157743820-9d5d9535-6690-4a1b-98ed-a0808a493607.png">

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info

**Comment by naftalimurgor** [comment]
Hi @SS-FOX-McCloud 
I'd like to work on this issue having worked on a similar issue here https://github.com/FraktalNFT/dapp-frontend/pull/235

**Comment by 0xdef1cafe** [comment]
reserved for @NeOMakinG
