### ISSUE TITLE
Add block explorer link to asset pages & send/receive labels

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#1180]
### Overview

It would be nice for exploration and security to be able to click a button to open erc20 tokens and contracts on etherscan.

### Reference

Depending on the designs from product, you'll probably end up implementing here

https://github.com/shapeshift/web/blob/develop/src/components/AssetHeader/AssetHeader.tsx#L58

### Acceptance Criteria

* The button displays as per mockups
* It links out to a valid link for eth addresses of tokens and contracts

### Need By Date

N/A

### Screenshots/Mockups

Product to provide mockups.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by DiggyDiggy2** [comment]
1. Lets make this generic for any asset type.
2. With this ticket lets also bring back "send" "receive" labels on the send receive icons for the web view

**Comment by DiggyDiggy2** [comment]
1. Lets bring back the "send" and "receive" labels to the icons — to better help users find them.
2. Let's add this lovely "view on chain" link next to them
3. (please use existing styles
<img width="569" alt="Screen Shot 2022-03-29 at 4 04 57 PM" src="https://user-images.githubusercontent.com/90058616/160714953-7861e8aa-6335-4b97-bc14-b6a57b3ceccf.png">
)
