### ISSUE TITLE
Gem -  Disable sell assets with balance lower than minimum

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1186]
### Overview

As can be seen on the Gem API responses, there is a minimum supported amount per asset.

https://api.gem.co/institutions/wyre/supported_currencies
https://api.gem.co/institutions/coinify/supported_currencies

As a user, I want to know which assets I can sell depending on my balance, as well as the ones I cannot, so as not be blocked from doing so by Gem later on in the flow.

### References and additional details

N/A

### Acceptance Criteria

- If a user selects an asset they have less than $5 of we'd like display 'Minimum amount to sell $5' above a greyed out 'continue' button.
- Chakra UI's [Alert](https://chakra-ui.com/docs/components/feedback/alert) component is used with error state in the case of minimum sell amount not met.

> Below is an image of the current trade modal with the greyed out continue button for reference. only change from here would be adding the message just above the continue button.
> <img width="570" alt="Screen_Shot_2022-03-28_at_11 35 32_AM" src="https://user-images.githubusercontent.com/97055189/160465405-0079a90d-1864-4bde-9f9b-f50fe726dfc8.png">

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Sponsor / Stakeholder

@gomesalexandre (`gomes` on Discord)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
Gem has minimums like ""minimums":{"USD":5.0}}" so if you have less than 5 dollars you are unable to sell these assets via gem.

**Comment by decentralized-j** [comment]
Gm sers! Spoke with UX master Diggy and beard and agreed upon a path forward.

@gomesalexandre - If a user selects an asset they have less than $5 of we'd like display 'Minimum amount to sell $5' above a greyed out 'continue' button.

Please let me know if mockups are needed or let me know if anything within that description doesn't make sense.

And gomes, a tip from beard - "use the chakra Alert with the status of error"

Below is an image of the current trade modal with the greyed out continue button for reference. only change from here would be adding the message just above the continue button.
<img width="570" alt="Screen_Shot_2022-03-28_at_11 35 32_AM" src="https://user-images.githubusercontent.com/97055189/160465405-0079a90d-1864-4bde-9f9b-f50fe726dfc8.png">

**Comment by 0xean** [comment]
@stackedq - any interest in taking this one?

**Comment by stackedq** [comment]
@0xean absolutely

**Comment by 0xean** [comment]
Awesome thank you!
