### ISSUE TITLE
Web: Change API of `getAddress` in web

### ISSUE THREAD

**Issue by DaoDev44** [shapeshift/web#120]
ChainAdapters inside lib needs to return `addressNList` and `address` from `adapter.getAddress`. This ticket is to change all the places in web to reflect that change: ie
```
const { address, addressNList } = adapter.getAddress({ wallet, path })
```

instead of:

```
const address = adapter.getAddress({ wallet, path })
```

**Comment by 0xdef1cafe** [comment]
not required
