### ISSUE TITLE
Amount for Fox in ETH/FOX LP stake overstated

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#1209]
### Overview

When staking FOX/ETH tokens in liquidity pool from Uniswap contract, the transaction amount showing for Fox in app.shapeshift is coming up as a few billion tokens.

https://discord.com/channels/554694662431178782/954457013688082493

### References and additional details

1) Open Fox Farming - https://fox.shapeshift.com/fox-farming
2) Select ‘Get started’ on ETH-FOX V3 option.
3) Follow prompts to stake the ETH-FOX
4) Once staking complete, check transaction history on https://app.shapeshift.com/
5) Notice the amount sent in Recent Transactions being a few trillion FOX.

![image](https://user-images.githubusercontent.com/100157997/159091521-249fd232-fd9a-434d-9ca5-5a04df2797e0.png)

![image](https://user-images.githubusercontent.com/100157997/159091541-73117523-3cc2-4dfe-bc77-1c975d20ec7b.png)

### Acceptance Criteria

After the transaction is completed, the TX history in app.shapeshift should display the correct amount of FOX-ETH LP tokens.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by stackedq** [comment]
Closing in favor of #1213 and #1214
