### ISSUE TITLE
Remove PUBLIC_URL from build pipelines

### ISSUE THREAD

**Issue by mrnerdhair** [shapeshift/web#1220]
Now that #958 has been resolved, PUBLIC_URL can be removed from all build pipelines. This will make the hash of `index.html` invariant across deployments, allowing development of an automatic deployment verification process.

**Comment by 0xean** [comment]
- Cloudflare
- Fleek

**Comment by 0xean** [comment]
@con5cience - can you updated fleek
@0xdef1cafe - will update cloudflare

**Comment by 0xdef1cafe** [comment]
i've updated both.

prod will be deployed as part of 4/12 release

**Comment by mrnerdhair** [comment]
Deployed to prod and working.
