### ISSUE TITLE
Arrows Unaligned on TX History Page 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#1222]
### Overview

When looking at the transaction history page and filtering for trades, the arrows running down the center column of the page are not aligned properly.

### References and additional details

1. go to app and log in with you wallet.
2. go to the transaction history page by clicking the truncations history tab on the left side of the screen.
3. go to the filter tab towards the center of the page.
4. under categories, click on trade, then apply.
5. notice the arrow going down the center column of the page. they are uneven and dictated by the length of the characters before them in the assets column.

### Acceptance Criteria

Arrows should be aligned and symmetrical running down the center column of the tx history page. 

### Screenshots/Mockups

<img width="926" alt="Screenshot 2022-03-21 083459" src="https://user-images.githubusercontent.com/99363597/159297241-7e324f4d-71e2-4f3d-b68d-7334bd4546ef.png">

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by DiggyDiggy2** [comment]
@reallybeard is redoing the layout on this anyway, so we can close this.
