### ISSUE TITLE
Refactor Cosmos Send modal to use plugins modal

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1234]
Re: https://github.com/shapeshift/web/pull/1211#discussion_r831611467

In #1211, some branching was introduced to either render the existing send modal form or the cosmos send modal form depending on the current assetId (CAIP19):

https://github.com/shapeshift/web/blob/065c951d047be30ebb66471c42b3a889cbbfb03a/src/components/Modals/Send/Send.tsx#L45-L53

Going forward, we want plugins to be able to use their own modals (see discussion https://github.com/shapeshift/web/discussions/1112).

This should be refactored so that there is no assetId branching, and the modal is instead rendered by the cosmos plugin, keeping the existing modal clean of any asset-specific logic.

**Comment by 0xean** [comment]
closed in #1211
