### ISSUE TITLE
Gem - remove feature flag

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#1245]
### Overview

When product deems gem to be stable we should remove the flag from the code.

### References and additional details

Ensure it's removed from

- sample.env
- config.ts
- preferencesSlices.ts
- pr.yml
- both fleek environments
- both cloudflare environments

### Acceptance Criteria

Feature flag is entirely removed from the application code and downstream infra.

### Need By Date

TBD by product.

### Screenshots/Mockups

N/A

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by decentralized-j** [comment]
Gm @0xdef1cafe! Product is good to remove the Gem feature flag! Please let us know if anything is needed on our end
