### ISSUE TITLE
UI -  Create widget that shows current staked positions and their metadata.

### ISSUE THREAD

**Issue by theoboldfrazier** [shapeshift/web#1264]
See mockups in https://projects.invisionapp.com/share/4712GLFPEPKY#/screens/464893193

**Comment by 0xean** [comment]
@SS-FOX-McCloud

**Comment by NeOMakinG** [comment]
Feel free to assign me on this one if needed

**Comment by gomesalexandre** [comment]
@theoboldfrazier looks like we've effectively created the same issue https://github.com/shapeshift/web/issues/1267 - or is this one tackling something different?

**Comment by 0xdef1cafe** [comment]
https://github.com/shapeshift/web/issues/1267
