### ISSUE TITLE
Overview and Tx tab options not showing on ATOM asset page

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#1291]
### Overview

When selecting ATOM from the asset page, there are is no option for the overview or transaction tabs like there is for other ETH/ERC-20 and BTC assets. When selecting it from the accounts menu however, the option for overview or tx tabs is available.

### References and additional details

1) Open app.shapeshift.com and log into Native wallet.
2) Turn on the cosmos testing flag.
3) From the asset page search for Cosmos/ATOM asset and select.
4) Notice under the asset name there is no option to select overview or transactions.
5) Click on the Accounts page and select Cosmos/ATOM.
6) Notice the option to choose overview or transaction tabs.

![image](https://user-images.githubusercontent.com/100157997/160024586-f730b90e-5106-44d8-af8c-b832d6137d54.png)

![image](https://user-images.githubusercontent.com/100157997/160024623-3bbe533d-8b4e-4643-85e5-e402bd3497d1.png)

### Acceptance Criteria

Display could be the same for all assets across ATOM/ETH/ERC-20/BTC on Accounts and Asset Page

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
doesn't require product input - make it the same as ethereum based assets
