### ISSUE TITLE
Tx loading status

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#1295]
### Overview

Now that we have a tx history loading status in the store, we can consume this in a variety of places in the UI to show better messages around transaction history.

### References and additional details

https://github.com/shapeshift/web/blob/develop/src/state/slices/txHistorySlice/selectors.ts#L16

### Acceptance Criteria

- Requires product, but all places that display transaction history can now show a loading state (maybe a skeleton) and a message if transactions have finished loading, but there are zero transactions.

### Need By Date

n/a

### Screenshots/Mockups

TBD by product.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Sponsor / Stakeholder

@0xdef1cafe

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
@reallybeard to find existing components for this
