### ISSUE TITLE
Contract approvals appearing as transactions on Tx history page

### ISSUE THREAD

**Issue by decentralized-j** [shapeshift/web#1336]
### Overview

When looking at the transaction history page, contract approvals appear as 'transactions' instead of as an 'approval' for a specific asset.

### References and additional details

1. Go to app and log in with you wallet
2. Go to the transaction history page by clicking the truncations history tab on the left side of the screen
3. Scroll to find a contract approval conducted with active wallet

Example view from FOX approval - Click [here](https://etherscan.io/tx/0x8320895dcae83be9f3a70b7e0b65b4185d9ddb2638004f7143c9470d9bb51220) for Tx on Etherscan
<img width="1082" alt="Screen Shot 2022-03-27 at 3 56 58 PM" src="https://user-images.githubusercontent.com/97055189/160302745-f2fad0c7-ef3b-4e32-9508-f4918a512464.png">

Example from CVX approval - Click [here](https://etherscan.io/tx/0x6fb26a01e3992b6d06a44763472369210a605cf8c8fdd7372d57b01a2b55547d) for Tx on Etherscan (UX is identical to above)

Example from WETH approval - Click [here](https://etherscan.io/tx/0x68bfdefb322d97af6debe829af61bd5ca6501cc163985f530822b45b64f3cb5f) for Tx on Etherscan (UX is identical to above)

**Desired UX** 
Note 4th Tx history item is 'Approval'
![1](https://user-images.githubusercontent.com/97055189/160467282-28e768c6-c774-4263-a8cf-c3d9fa6a48ae.png)

### Acceptance Criteria

Contract approvals conducted on Uniswap, Cowswap, and other platforms appear as 'approvals' in Tx history rather than 'transactions' with the relevant check mark and gas displayed.

### Screenshots/Mockups

See above

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Sponsor / Stakeholder

@decentralizedj in discord

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
@decentralized-j 

I tried to see what happens and it seems that we have no proper way to detect that these transactions are `Approvals`, the `direction` attribute is not filled, it's not directly linked to the `web` repository, probably related to the `unchained` one

**Comment by decentralized-j** [comment]
@NeOMakinG Understood - Thank you for attempting ser. Will close this issue and revisit in the future if something changes.
