### ISSUE TITLE
Add open issues to ShapeShift Dashboard

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#1349]
### Overview

* put it in web
* cron job - every hour
* manual button - on demand
* pull open issues from web/lib/unchained/hdwallet/docs
* add them to the project
* nothing fancier required with automation (yet)
* https://github.com/orgs/shapeshift/people/shapeshift-ci-bot

### References and additional details

how to fetch open issues and add them to project

note this was buggy, if i ran it multiple times it'd finally complete

```ts
const { graphql } = require('@octokit/graphql')

const projectId = 'PN_kwDOAyeg-84AAiih' // https://github.com/orgs/shapeshift/projects/8/

// requires a personal access token with org:write perms
const personalAccessToken = process.argv.slice(2)[0]

if (!personalAccessToken) {
	console.log('call script with node add-all-issues.js personalAccessToken')
	process.exit(1)
}

const graphqlWithAuth = graphql.defaults({
  headers: {
    authorization: `token ${personalAccessToken}`,
  },
});

const main = async () => {
	const issues = await graphqlWithAuth(`
		query {
		  organization(login: "shapeshift") {
		    web: repository(name: "web") {
		      id
		      issues(
		        first: 100
		        filterBy: {states: OPEN}
		      ) {
		        edges {
		          node {
		            id
		            title
		          }
		        }
		      }
		    }
		    lib: repository(name: "lib") {
		      id
		      issues(
		        first: 100
		        filterBy: {states: OPEN}
		      ) {
		        edges {
		          node {
		            id
		            title
		          }
		        }
		      }
		    }
		    unchained: repository(name: "unchained") {
		      id
		      issues(
		        first: 100
		        filterBy: {states: OPEN}
		      ) {
		        edges {
		          node {
		            id
		            title
		          }
		        }
		      }
		    }
		  }
		}
	`)

	const issueIds = Object.entries(issues.organization).reduce((acc, [_repoId, v]) => {
		acc.push(...v.issues.edges.map(issue => issue.node.id))
		return acc
	}, [])

	console.log(`Found ${issueIds.length} issues`)

	await Promise.all(issueIds.map(contentId => {
		return graphqlWithAuth(`
		  mutation addIssuesToProject($projectId: ID!, $contentId: ID!) {
		    addProjectNextItem(input: {projectId: $projectId, contentId: $contentId }) {
		      projectNextItem {
		        id
					}
				}
			}
		`,
		{ projectId, contentId }
		)
	}))
}

main()
  .then(() => console.log('Added all open issues from web/lib/unchained to project'))
	.catch(e => console.log(e))

```

### Acceptance Criteria

* Open issues are automatically added to the dashboard project

### Need By Date

n/a

**Comment by 0xApotheosis** [comment]
Handy links:

1. https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects
2. https://jasonet.co/posts/scheduled-actions/

**Comment by 0xean** [comment]
1. Run locally with token
1. Create github app for actions environment
https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects#example-workflow-authenticating-with-a-personal-access-token

**Comment by NeOMakinG** [comment]
Some things I know because I worked on a similar project:
- The github app should be added to the organization, not the repository (to use the Project Next API)
- You can subscribe to github web sockets and receive event when issues are created, it should be way better than having a cronjob
- Great resource: https://github.com/PrestaShop/issuebot

Some ideas of automations:
- It would be cool to move the issue to the "Review" column when the PR linked quit the draft mode
- Move the issue to the "Done" column when the application receive the "closed" event, but I guess it can be done directly from github now

**Comment by NeOMakinG** [comment]
> Some things I know because I worked on a similar project:
> 
> * The github app should be added to the organization, not the repository (to use the Project Next API)
> * You can subscribe to github web sockets and receive event when issues are created, it should be way better than having a cronjob
> * Great resource: https://github.com/PrestaShop/issuebot
> 
> Some ideas of automations:
> 
> * It would be cool to move the issue to the "Review" column when the PR linked quit the draft mode
> * Move the issue to the "Done" column when the application receive the "closed" event, but I guess it can be done directly from github now

**Comment by 0xean** [comment]
Okay, so some updates here.

Currently I did the following.

1. Created a new github app that is owned by the SS org 
2.  Created an action that will add any new issue in the web repo to the board

This is working based on my tests, but doesn't quite fulfill the original AC, but does theoretically end up in the same end state where all issues are on the board (for web, can extend to other repos very easily).

**Comment by 0xean** [comment]
Per conversation with @0xdef1cafe is discord,  he is good with this approach.  Will let this run for a day or two to make sure there are no edge cases and propagate to other repos.

**Comment by 0xean** [comment]
This has been propagated to unchained and lib, tested and working in all of them.  closing
