### ISSUE TITLE
Bug - Correct Console Error for HttpRequest to https://raw.githack.com/trustwallet/assets/master/blockchains/ethereum/tokenlist.json'

### ISSUE THREAD

**Issue by Neverwas-dev** [shapeshift/web#1351]
- Brief description 
Access to XMLHttpRequest at 'https://raw.githack.com/trustwallet/assets/master/blockchains/ethereum/tokenlist.json' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Resource is providing a 404 error for the url

- Steps to recreate (detail)
1. Launch app.shapeshift.com
2. Check web console for the error code 

- Screenshots/vids
![image](https://user-images.githubusercontent.com/95000549/160863289-a9483407-038e-468f-be98-33181300d2c8.png)

![image](https://user-images.githubusercontent.com/95000549/160863463-5cb8665b-5173-422b-89f1-7381360f1da2.png)

- AC (acceptance criteria)

Resolve the error for https://raw.githack.com/trustwallet/assets/master/blockchains/ethereum/tokenlist.json

**Comment by 0xean** [comment]
closed as will not  fix
