### ISSUE TITLE
Deposit Modal on the DeFi page in mobile looks a bit messy

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#1381]
### Overview

When staking an asset in the Yearn Vault on mobile, the modal pop out is larger than the screen so you can't see the whole modal in one go. When moving the modal across, the screen behind can be seen in certain parts and it makes it hard to read

### References and additional details

1) Open app.shapeshift in mobile (using PR release https://7b79acc7.web-29e.pages.dev/ )
2) Connect to any wallet
3) Select DeFi page and choose an asset to open the Yearn Vault modal.
4) Select Deposit and notice the bottom part of the modal is too wide for the screen and you cannot see the entire modal
5) Once selecting amount to deposit, select continue and notice the same thing on the following page. When moving the modal across the screen, you can see the information from the previous page behind and it makes It hard to read.
![image](https://user-images.githubusercontent.com/100157997/161635276-5547334f-f6df-484c-8433-972bbd00007c.png)
![image](https://user-images.githubusercontent.com/100157997/161635316-04c553dd-6025-49d1-ae78-f9c306bdfed4.png)

### Acceptance Criteria

Should be able to view modal easily when staking as asset

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
I'll apply on this one when it's out

**Comment by reallybeard** [comment]
> I'll apply on this one when it's out

@NeOMakinG 
I'm gonna pick this up, since its part of the FOXY stuff.. and I borked it. Much appreciated though!
