### ISSUE TITLE
Links ( Shapeshift Validator and Shapeshift DAO) might not be working as intended

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#1393]
### Overview

When going through the steps to stake Cosmos, it looks like Shapeshift Validator should be linked to a page with more info or something but when selecting it, it just open native wallet in another browser page

### References and additional details

1) Access app.shapeshift from development branch https://4cd99f45.web-29e.pages.dev/
2) Log into native wallet. (check CosmosInvestor flag is turned on)
3) Look up Cosmos from the Asset page and select ShapeShift Dao under Validator options
4) In the staking modal select stake
5) Choose amount to stake and select continue
6) On the Atom Staking Page the Validator “Shapeshift Validator” appears to be a hyperlink, but when selecting notice it takes you to new browser page and opens native wallet on the Cosmos asset page
![image](https://user-images.githubusercontent.com/100157997/161879229-3f509242-7e85-4b0d-a92c-56c422ac9b3a.png)

### Acceptance Criteria

Hyperlinks direct users to correct information

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by TaxiStake** [comment]
Can probably just link here https://www.mintscan.io/cosmos/validators/cosmosvaloper199mlc7fr6ll5t54w7tts7f4s0cvnqgc59nmuxf

**Comment by willyogo** [comment]
Agree with @TaxiStake, let's link here for now @gomesalexandre: https://www.mintscan.io/cosmos/validators/cosmosvaloper199mlc7fr6ll5t54w7tts7f4s0cvnqgc59nmuxf
