### ISSUE TITLE
Dark to Light Theme Issue

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#1401]
### Overview

When switching from Dark to Light theme or vice versa, there are elements of the page that flash the opposite color that the page is changing to. For example, if you're going from Dark to Light mode, parts of the page will flash black.

### References and additional details

1. go to app.shapeshift.com
2. go in with your wallet of choice.
3. click on the settings tab in the bottom left hand corner of the page.
4. within the settings widget, toggle the page from dark to light or light to dark.
5. observe the flashes of color when switching themes.

### Acceptance Criteria

The page shouldn't flash colors when switching themes. It should be a smooth dissolve from dark to light theme or vice versa. 

### Screenshots/Mockups

https://user-images.githubusercontent.com/99363597/162019597-bedba4a4-5fcc-46d3-9ca6-53720b0979ff.mp4

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by DiggyDiggy2** [comment]
This is not necessarily a bug. The browser needs to re-render the screen so it will appear to flash.

**Comment by 0xdef1cafe** [comment]
as per product i'm closing this as wont fix
