### ISSUE TITLE
Staking balance includes unbonded stakes and allows user to go through unstake flow on already unstaked balance.

### ISSUE THREAD

**Issue by theoboldfrazier** [shapeshift/web#1404]
### Overview

When a user unstakes cosmos, the coins enter into an unbonded state and remain inaccessible for 21 days. Currently, the app thinks the unbonded balance is part of your staked balance. This allows the user to enter into the unstake flow with the unbonded balance and attempt to unstake them again.

### References and additional details

It might be useful to start in src/components/Delegate/StakingOpportunities.tsx to view the 'Staked Amount' column and how it is calculated. Then in the src/plugins/cosmos/components/modals/Staking/Staking.tsx area, where the modal exists look to remove the ability to unstake already unbonded staking balance.

### Acceptance Criteria

Once a user has unstaked a staked balance, they are not able to enter the unstake flow with the app thinking they can unstake that balance again.

### Need By Date

As soon as possible

### Screenshots/Mockups

<img width="434" alt="Screen Shot 2022-04-06 at 11 25 11" src="https://user-images.githubusercontent.com/88169003/162032841-7490b862-4f0c-4fa2-86f0-584b7fa76d3f.png">
<img width="433" alt="Screen Shot 2022-04-06 at 11 25 24" src="https://user-images.githubusercontent.com/88169003/162032845-768141b9-5c7e-4ca3-96ac-4bf3ed3c2d39.png">

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

2 hours

### Sponsor / Stakeholder

github: theoboldfrazier discord: Theobold Frazier#5808

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by chxash** [comment]
I may be wrong but is this PR already fixing part of this ? (https://github.com/shapeshift/web/pull/1398/files)
In the PR description : 

_"fixes the data shown as "Amount staked" in unstake (the amount that's available to unstake) which currently uses bondings total (staked + unstaked), which is wrong, since you can't unstake an already unstaked amount"_

The remaining question is should we fix what we are displaying in "Staked Amount" column on the `StakingOpportunities.tsx` as well (we are also displaying unbonded balance as part of staked amount)
