### ISSUE TITLE
Cosmos: need to refresh page after staking/unstaking

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#1409]
When staking/unstaking/claiming in Cosmos staking modal, account/staking/unstaking balance doesn't get properly updated.

#### Unstaking
- Open Cosmos Staking modal
- Go to Unstake 
- Unstake some amount of ATOM in a validator
- Undelegations do not get updated

#### Staking

- Open Cosmos Staking modal
- Go to Stake 
- Stake some amount of ATOM in a validator
- Staked amount in overview doesn't get updated
- Account Balance doesn't get updated

#### Rewards

- Open Cosmos Staking modal
- Go to Claim 
- Claim all your pending claims
- Account balance doesn't get updated
- Rewards don't get zero'd out

### A/C

- the `stakingDataSlice` redux state slice gets updated after a stake/unstake/claim Tx
  - the staked amount on a stake Tx gets added to the staking balance, deducted from the account balance (done in #1179)
  - the unstaked amount on an unstake Tx gets added to the unstaking balance / the undelegation entry gets populated / the value gets deducted from the staked amount
  - rewards amount is set to ~0 after a claim Tx
  
  
The account balance update shouldn't need to be updated on this issue as #1179 fixes it from the testing I've done.

**Comment by gomesalexandre** [comment]
Tested locally and #1179 fixes it partially:
- Account balance gets updated after a staking, with the amount you just staked deducted from account balance. This happens when the Tx is picked by unchained (slightly before the Tx is available on Mintscan, which is expected given the optimistic nature of unchained vs. the Tx only being available in Mintscan when complete)
- Account un/staking balances do not get updated after unstaking

**Comment by elmutt** [comment]
Is stakingDataSlice the right place to look?

I would think come through as a normal TX in txHistorySlice like all other transactions but maybe im misunderstanding

**Comment by gomesalexandre** [comment]
> Is stakingDataSlice the right place to look?
> 
> I would think come through as a normal TX in txHistorySlice like all other transactions but maybe im misunderstanding

You're right! Just updated the A/C.
I've spiked this and synced with @NeOMakinG, the solution we will go with is reacting on the Tx messages from WS to re-fire the `stakingDataApi` query. That will trigger a store update, new selector reference and trigger a re-render on all of the UI bits that depend on it.

**Comment by 0xdef1cafe** [comment]
i commented on this yesterday on the wrong issue, so i'll follow up here instead.

i'll approve this to get cosmos out the door, but want to highlight how this stakingData slice is misguided, and needs to be removed entirely.

we now have chain specific logic, calling the same getAccount endpoint, using only a subset of the fetched data, storing it in a separate location, that doesn't describe what it actually is (cosmos specific data) in a transaction provider. 

we really should never have created this stakingData slice in the first place - it's account data that should belong under an optional, discriminated type on the cosmos account.

**Comment by NeOMakinG** [comment]
I guess we can close it, because of #1179

It seems to work fine atm, the only thing we should think about is the slice refactor.
