### ISSUE TITLE
Move KeepKey PIN entry when changing device PIN to settings menu

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#1414]
We initially bootstrapped the existing PIN entry modals, but when changing the PIN via the menu the entry should happen inside the menu itself.

UI: https://www.sketch.com/s/5e6ddd00-6f97-47f5-8daa-6e20a967f4b0/p/7E2E52BC-86BF-42B9-AC2E-8864E8D32111
Spec: https://shapeshift.notion.site/KeepKey-Settings-86cce69e059346c0b14aa0547703465a

**Comment by MBMaria** [comment]
@pastaghost how much did you want to put on this bounty?
