### ISSUE TITLE
Organizing Staked Assets (ETH and ATOM) 

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#1429]
### Overview

Currently how we display transaction history to users isn't quite clear when a user is staking or unstaking assets. I think it would be great to give users more information on these transactions or at least state what these TX's are doing. Possibly add another filter for users on the Transaction History page for when users are doing taxes and make it a little easier to parse through that data.

**Transaction History for using staking into a yearn vault:**
- Depositing into a staking contract you receive the contract token
![YearnInput](https://user-images.githubusercontent.com/94189400/162308204-d83c624d-3239-405b-8514-928a779882e3.jpg)
- Withdrawal from the staking contract you receive the original token back
![YearnWithdraw](https://user-images.githubusercontent.com/94189400/162309314-339e8926-e766-4061-8d69-66ccdde5b49d.jpg)

**Transaction History for staking ATOM (Cosmos):**
- Depositing into a cosmos validator
![ATOMdeposit](https://user-images.githubusercontent.com/94189400/162314696-84b735c8-e995-491a-8aac-ddd305a8d3d3.jpg)
- Withdrawal from cosmos validator
![ATOMwithdrawal](https://user-images.githubusercontent.com/94189400/162318141-45dc569b-e0cf-4bed-87ec-18d8fb256500.jpg)

### References and additional details

Added in overview

### Acceptance Criteria

Transaction History should be labeled correctly for TX's for staking and delegating

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by DiggyDiggy2** [comment]
The solution for stake/unstake on ATOM was done. We should apply the same thing to Yearn. This might need a new ticket @SS-FOX-McCloud

**Comment by SS-FOX-McCloud** [comment]
Created a new ticket just for the Yearn part.
