### ISSUE TITLE
Cosmos integration first impressions - Some suggestions and minor UI bugs

### ISSUE THREAD

**Issue by LPX55** [shapeshift/web#1445]
#1439 may have fixed a few of these issues, but had a blast checking out the Cosmos integration! Major kudos to engineering 🙌

Just some minor bugs that I came across; some may already have been fixed.

![1 fw](https://user-images.githubusercontent.com/16395727/162509845-d598be1d-56ad-401a-b8d2-06386b0c474b.png)

![2 fw](https://user-images.githubusercontent.com/16395727/162509857-0157f4a9-96d5-4e80-b96d-5d33d44fff8a.png)

![3 fw](https://user-images.githubusercontent.com/16395727/162509858-b35d7f19-360f-4699-827a-f4a8ed53400e.png)

![4 fw](https://user-images.githubusercontent.com/16395727/162509859-27ff0306-e8a8-44d0-be6c-ec95678540a1.png)

![5 fw](https://user-images.githubusercontent.com/16395727/162509860-4a4b160f-0c75-427b-885f-a8db9d488b29.png)

![6 fw](https://user-images.githubusercontent.com/16395727/162509855-f1ef9e3c-e358-46dc-881c-e1fb2e09d9c6.png)

**Comment by NeOMakinG** [comment]
- ETH => FOX trade panel: We don't support trades yet
- Asset description: It comes from the `AssetService`, not linked to web, I don't really know if we can do something, maybe @gomesalexandre have an idea!
- Osmosis isn't working yet
- Modal header => Global UI decision, we need to change it everywhere in the application, for consistency (with earn, foxy), I'll not modify it except if the product team decide to change it globally

**Comment by LPX55** [comment]
👍
