### ISSUE TITLE
Determine KeepKey firmware/bootloader update process

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#1453]
`web` currently gets a [JSON file](https://bafybeied24gc2ipvlxdbs4v676dwho2l5aafmngrleic3do2czdvgb546u.ipfs.dweb.link/keepKey.json) hosted on IPFS to determine if the connected KeepKey is up to date.

We need to determine the process for updating this data as KeepKey firmware/bootloader versions change.

One solution might be to put this file under version control and point to a persistent URL in `web`.

**Comment by 0xApotheosis** [comment]
There is a CORS issue accessing the link above from `web` - it's missing appropriate access headers, so we switched to an IPFS link.

**Comment by mrnerdhair** [comment]
Pinged @con5cience to get the CORS config on the bucket updated.
