### ISSUE TITLE
Cosmos: Refactor `stakingDataSlice`

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1454]
### Overview

Currently, the Cosmos staking data (rewards, delegations, undelegations) as well as validators data are living in the `src/state/slices/stakingDataSlice` folder.

We want to get rid of for the staking data that and have all the data related to staking data live on the `portfolioSlice` instead. That includes the slice itself, selectors, and tests. The validators data should be kept there, although as a single-purpose slice. 

The way this should be done is:
- Staking data lives in portfolioSlice, with normalized validator data (as IDs)
- The stakingDataSlice is now a validatorsDataSlice, and contains validator IDs as well as validators info by IDs. We can use the normalized data from portfolioSlice to access/fetch (single) validator data. 

### References and additional details

- [`stakingDataSlice`](https://github.com/shapeshift/web/tree/develop/src/state/slices/stakingDataSlice)
- [`portfolioSlice`](https://github.com/shapeshift/web/tree/develop/src/state/slices/portfolioSlice)

### Acceptance Criteria (TODO, speccing needs to be improved)

- There is no regression on Cosmos staking and delegations
- The `stakingDataSlice` is renamed to a single-concern `validatorsDataSlice`
  - We do not fetch "all validators" anymore (which is lying to us as it's not really all validators) but rather single validators 
- The existing `getAccount` is used to get Cosmos staking data
- Modules consuming this slice now consume the portfolio one in the case of the staking data, or the renamed one in case of validators
- Loading state is removed and achieved by checking for the absence of a validator by ID in validatorsDataSlice.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

5 days

### Sponsor / Stakeholder

@gomesalexandre (`gomes` on Discord)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@theoboldfrazier @0xdef1cafe any thoughts on also moving the validators data and considering them as portfolio accounts?
My vision on that is that from a high-level, they are tied to the portfolio accounts (one Cosmos account has a relation to one/many validators data). The default validator in the case of no active delegation might be the exception to that though, since it doesn't have a relation to any account.

**Comment by 0xdef1cafe** [comment]
reopening as i reverted this out of develop

**Comment by gomesalexandre** [comment]
Closed in https://github.com/shapeshift/web/pull/1700
