### ISSUE TITLE
Cypress sometimes times out waiting on development server

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#1461]
**Reserved for @GMSteuart.**

### Overview

We have an intermittent issue in our Cypress CI pipeline where occasionally the Cypress Run job will fail to start the development server.

An example of this occurring: https://github.com/shapeshift/web/runs/5965520012?check_suite_focus=true

<img width="1075" alt="Screen Shot 2022-04-12 at 7 56 03 am" src="https://user-images.githubusercontent.com/97164662/162840031-b9741731-9ce1-4183-b714-3d630d4f6501.png">

### References and additional details

This could be a number of things, such as:

- A version issue somewhere (Cypress, Node, Ubuntu, Chrome, GitHub Actions etc)
- Under-powered worker failing to execute `yarn dev`
- Something to do with running the tests in parallel across multiple machines
- Maybe we need to use a different browser environment, e.g. Electron over Chrome
- Maybe we just need to bump the timeout to something higher

This issue on the Cypress GitHub seems related: https://github.com/cypress-io/cypress/issues/3310

### Acceptance Criteria

The Cypress Run job runs reliably.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

Probably a couple of days of playing with it

### Sponsor / Stakeholder

GitHub: 0xapotheosis | Discord: 0xApotheosis#2503

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by GMSteuart** [comment]
> This could be a number of things

What an accurate statement. I've ran into many other errors while getting the local emulation going, but so far all fixable by extending the workflow configuration.

**Comment by 0xApotheosis** [comment]
Excellent, appreciate the update - look forward to seeing how you go.

**Comment by GMSteuart** [comment]
@0xApotheosis The main issue with the dev server timeout occurring is that the build times from running `yarn dev` are getting increasingly long. There are two main ways to solve this: one, don't use `yarn dev` and use a split workflow with a build process and testing on the build, and two, increasing the timeout.

Additionally, there is potential that the `msw` package is also affecting timeouts. There is some additional development that could be done with how msw is added to the application; more specifically, there may be benefit in adding msw conditionally based off `env` being `development` and not `production`.

**Comment by GMSteuart** [comment]
@0xApotheosis this is good to go as part of pull #1525
