### ISSUE TITLE
USD value amount not showing on ATOM stake or unstake modal

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#1462]
### Overview

When staking or unstaking ATOM, the value of the asset held in the wallet is stated in ATOM but does not have the corresponding amount in USD

### References and additional details

1) Log into app.shapeshift.com
2) Connect to native wallet and turn on CosmosInvestor flag
3) Select ATOM from asset page and go to staking modal
4) Notice when choosing how much to stake, the value of ATOM is not stated in USD
5) Notice the same when unstaking ATOM, that the USD value does not show in the modal
![image](https://user-images.githubusercontent.com/100157997/162860404-16e93ab4-23da-4886-adf0-68601928b83f.png)
![image](https://user-images.githubusercontent.com/100157997/162860451-a3f78752-cd4c-4d0a-ac7c-5d90b0dec865.png)

### Acceptance Criteria

Staking Modal should display amount of cosmos in ATOM as well as USD

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@NeOMakinG I've just checked the mockups and this wasn't part of it. Since you worked on the design refactor, I think this one should be easy for you!

**Comment by NeOMakinG** [comment]
@gomesalexandre yeah, I'll take it
