### ISSUE TITLE
Update wallet connection modal flow

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#1467]
### Overview

Currently, when connecting a Wallet (any ShapeShift supported wallet) to the shapeshift web app, upon successful pairing of the wallet the user is shown a success modal (pictured below).

Going forwards we want to use this modal only to show error messaging. So if the pairing is successful there should be no modal and the user should be viewing the dashboard.

If there is any issue with the pairing process this modal should pop up and display the appropriate error messaging.

### References and additional details

web code base.  NEED additional info from engineering

### Acceptance Criteria

A/C:
After successfully pairing a wallet to the web app the user should be directed straight to the dashboard. If the user's Wallet has an issue pairing then the error is displayed in the modal.

### Need By Date

n/a

### Screenshots/Mockups

<img width="450" alt="Screen Shot 2022-04-11 at 2 03 44 PM" src="https://user-images.githubusercontent.com/57505863/163015024-7b49a447-957f-4d30-8ff2-c69329072338.png">

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

hours

### Sponsor / Stakeholder

@FOX_McCloud

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
I guess we want to keep success when we are on another action such as KeepKey recovery sentence, native wallet import or creation in order to inform the user everything went well right?

**Comment by SS-FOX-McCloud** [comment]
@NeOMakinG Correct!
