### ISSUE TITLE
Cosmos: Missing Cosmos earn balance in DeFi "Wallet Balance"

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1491]
### Overview

The wrong wallet balance is displayed in DeFi in the case of Cosmos delegations:

The number is not accounting for the Cosmos staking amount, while it is actually accounted for in "Earn Balance".

As such, when we subtract the earn balance from the "Wallet Balance" (that should be `(wallet balance + earn balance) - earn balance`) we get a wrong wallet balance, possibly negative if the total earn balance is greater than the wallet balance.
Issue reference where the subtraction was implemented: https://github.com/shapeshift/web/issues/1272

### Actual

- "Wallet Balance" doesn't contain the Cosmos earn balance
- "Wallet Balance" is negative
- "Net worth" number is different than the one in Dashboard (dashboard amount - Cosmos delegations)

### References and additional details

https://github.com/shapeshift/web/blob/fc329e6efd715bcf586852d53fa2177e1b972683/src/pages/Defi/components/OverviewHeader.tsx#L40-L43

### Acceptance Criteria

- "Wallet Balance" contains Cosmos earn balance
- "Wallet Balance" is positive
- "Net worth" number is matching the Dashboard one

### Screenshots/Mockups

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/17035424/163481099-673070ee-03c6-44f4-9bdf-141d3e8f2e0f.png">

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Sponsor / Stakeholder

@gomesalexandre (`gomes` on Discord)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
I guess it's fixed by https://github.com/shapeshift/web/pull/1501 but the issue missed the `closes` keyword

**Comment by gomesalexandre** [comment]
> I guess it's fixed by #1501 but the issue missed the `closes` keyword

Thanks for the housekeeping @NeOMakinG 🐐 !
