### ISSUE TITLE
Error handling: Login component

### ISSUE THREAD

**Issue by theoboldfrazier** [shapeshift/web#1497]
### Overview

The following errors are expeted from the standalone server:

- Rate Limiting
- Invalid captcha
- Invalid login
- Invalid 2FA (potentially could be merged with invalid logn)

### References and additional details

https://www.notion.so/shapeshift/Legacy-Native-Wallet-Migration-4164af0d0ad641faaee4c32a9aad2d80#3588648cfcd340f1bd39f90b7f64b331

### Acceptance Criteria

* The Error responses from the server are handled properly and display information to the user as to why the login failed.

**Comment by NeOMakinG** [comment]
Provided a draft PR, I would need some specs about how errors will be returned, I guess the rate limit is an HTTP code, but others errors won't
