### ISSUE TITLE
Decrypt wallet into vault.

### ISSUE THREAD

**Issue by theoboldfrazier** [shapeshift/web#1498]
### Overview

Once a successful response happens, we need to create a vault with the decrypted mnemonic.

This needs to happen in a way where the plaintext mnemonic is as protected as much as possible.

Don't need to save the vault at this point, but need to create it to pass through to the name/password screen.

### References and additional details

https://www.notion.so/shapeshift/Legacy-Native-Wallet-Migration-4164af0d0ad641faaee4c32a9aad2d80#3588648cfcd340f1bd39f90b7f64b331

### Acceptance Criteria

* A vault with the user's mnemonic is created to be passed on to the next screens.

**Comment by NeOMakinG** [comment]
I think this one should be done before https://github.com/shapeshift/web/issues/1500

It will be easier if we do it in this order, because we will know how the implementation will work with the TestPhrase screen
