### ISSUE TITLE
Organizing Staked Assets (Yearn)

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#1531]
### Overview

**Overview**
Currently how we display transaction history to users isn't quite clear when a user is staking or unstaking assets. I think it would be great to give users more information on these transactions or at least state what these TX's are doing. Possibly add another filter for users on the Transaction History page for when users are doing taxes and make it a little easier to parse through that data.

Transaction History for using staking into a yearn vault:

Depositing into a staking contract you receive the contract token
![162308204-d83c624d-3239-405b-8514-928a779882e3](https://user-images.githubusercontent.com/57505863/164294327-11259937-3f24-404a-b685-7799c7573e2a.jpeg)

Withdrawal from the staking contract you receive the original token back
![162309314-339e8926-e766-4061-8d69-66ccdde5b49d](https://user-images.githubusercontent.com/57505863/164294348-e5424faf-5dcd-4407-ad7e-75b9788bd095.jpeg)

### References and additional details

Similar to ticket https://github.com/shapeshift/web/issues/1429 but for yearn vaults.

### Acceptance Criteria

A/C: Transaction History should be labeled correctly for TX's for  depositing/withdrawing to/from Yearn vaults.

### Need By Date

n/a

**Comment by 0xean** [comment]
closing as wont fix ( per @0xdef1cafe )
