### ISSUE TITLE
FOXy routing bug

### ISSUE THREAD

**Issue by toshiSat** [shapeshift/web#1547]
### Overview

if you are on overview and hit claim now, and then click deposit or withdraw you are taken to a route that doesn't exist.

Should just route to Withdraw/Deposit

### References and additional details

Need to add a default route for both deposit and withdraw

### Acceptance Criteria

Routes correctly to deposit and withdraw

### Need By Date

N/A

### Estimated effort

2 hrs

**Comment by 0xean** [comment]
closing as stale.
