### ISSUE TITLE
FOX Farm CTA

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#1550]
### Overview

Overview
As a user I want to be aware and be routed to the FOX farm page and all associated opportunities via the DeFi earn tab (https://app.shapeshift.com/defi/earn) on the web app. This should be done via a CTA (call to action) banner.

COPY: "Earn 60%+ APR* by farming your ETH-FOX liquidity pool tokens"

There should also be a button that says "Start Farming FOX" which will link to https://fox.shapeshift.com/fox-farming

This banner/button should live at the top of the earn page. Please see the attached image for additional details/design.

### References and additional details

Web. Need additional detail from engineering.

### Acceptance Criteria

A CTA banner will live at the top of the earn section with a clickable button linking to https://fox.shapeshift.com/fox-farming

### Need By Date

n/a

### Screenshots/Mockups

[_No response_](https://www.sketch.com/s/5dcee031-1213-44a1-a94e-e3439cfb4d17/a/v8nnO9J

![image](https://user-images.githubusercontent.com/57505863/164524300-3c4ec565-6f83-47d6-a050-b0fa40bb63f5.png))

### Estimated effort

2 hours

**Comment by 0xdef1cafe** [comment]
@SS-FOX-McCloud what does this look like on tablet/mobile?

**Comment by 0xdef1cafe** [comment]
nothing required here on an engineering basis, once you can clarify responsive views this can be bountied.

**Comment by SS-FOX-McCloud** [comment]
Hoff working on mobile mockup...will mark ready for bounty once completed.

**Comment by SS-FOX-McCloud** [comment]
Here is the CTA on mobile.  This should be ready for bounty now.  Please let me know if there are any other questions!

![MobileCTA](https://user-images.githubusercontent.com/57505863/165144850-1458fdd0-5cc2-40e4-9331-35312f4d2846.png)

**Comment by brymut** [comment]
Where would the button go for the Button in the CTA on mobile? @SS-FOX-McCloud

**Comment by 0xdef1cafe** [comment]
looks great @brymut but will await @SS-FOX-McCloud input regarding the button

**Comment by brymut** [comment]
> 
> @brymut  The button should still go to the FOX farm page: https://fox.shapeshift.com/fox-farming 
> 
> 
> 
> Is that what you are asking?

There is no CTA button in the mobile mock-up you provided.

**Comment by SS-FOX-McCloud** [comment]
@brymut ah, gotcha! Could the entire banner/CTA be "clickable" on mobile and direct the user to https://fox.shapeshift.com/fox-farming ?

**Comment by NeOMakinG** [comment]
@brymut I would suggest to remove the href from the button but keep it like it is, and apply the href to the whole container even on desktop, so the whole banner is clickable on desktop too

wdyt @SS-FOX-McCloud ?

**Comment by SS-FOX-McCloud** [comment]
> @brymut I would suggest to remove the href from the button but keep it like it is, and apply the href to the whole container even on desktop, so the whole banner is clickable on desktop too
> 
> wdyt @SS-FOX-McCloud ?

Sure!- That would work great! good idea!

**Comment by brymut** [comment]
> @brymut ah, gotcha! Could the entire banner/CTA be "clickable" on mobile and direct the user to https://fox.shapeshift.com/fox-farming ? 
> 
> 

Not sure this would work as there wouldn't be any actual CTA maybe look into the screenshots in the PR and provide feedback on those?

**Comment by NeOMakinG** [comment]
> > @brymut ah, gotcha! Could the entire banner/CTA be "clickable" on mobile and direct the user to https://fox.shapeshift.com/fox-farming ?
> 
> Not sure this would work as there wouldn't be any actual CTA maybe look into the screenshots in the PR and provide feedback on those?

Damn, I still agree with you, having a CTA is a good practice, we shouldn't remove it on mobile, or the user doesn't know that it's clickable :p

**Comment by SS-FOX-McCloud** [comment]
> > > @brymut ah, gotcha! Could the entire banner/CTA be "clickable" on mobile and direct the user to https://fox.shapeshift.com/fox-farming ?
> > 
> > 
> > Not sure this would work as there wouldn't be any actual CTA maybe look into the screenshots in the PR and provide feedback on those?
> 
> Damn, I still agree with you, having a CTA is a good practice, we shouldn't remove it on mobile, or the user doesn't know that it's clickable :p

Thanks for the discussion.  On mobile since there isn't room for the button (and most users will access FOX farm from a desktop anyways, I assume with the wallet connectivity being better on desktop) Can we just update the copy on mobile only to "Click here to Earn 60%+ APR* by farming your ETH-FOX liquidity pool tokens" and then make the entire banner linkable as previously discussed?  Let me know if you dont think this is doable.  Thanks!

**Comment by NeOMakinG** [comment]
> > > > @brymut ah, gotcha! Could the entire banner/CTA be "clickable" on mobile and direct the user to https://fox.shapeshift.com/fox-farming ?
> > > 
> > > 
> > > Not sure this would work as there wouldn't be any actual CTA maybe look into the screenshots in the PR and provide feedback on those?
> > 
> > 
> > Damn, I still agree with you, having a CTA is a good practice, we shouldn't remove it on mobile, or the user doesn't know that it's clickable :p
> 
> Thanks for the discussion. On mobile since there isn't room for the button (and most users will access FOX farm from a desktop anyways, I assume with the wallet connectivity being better on desktop) Can we just update the copy on mobile only to "Click here to Earn 60%+ APR* by farming your ETH-FOX liquidity pool tokens" and then make the entire banner linkable as previously discussed? Let me know if you dont think this is doable. Thanks!

Should be doable and easier if we make the banner fully clickable even on desktop, thanks for your time and feedbacks :+1:

**Comment by gomesalexandre** [comment]
@SS-FOX-McCloud Can we update the issue with the new spec to make it easier for reviewers? 🙏🏽
