### ISSUE TITLE
Your assets bug

### ISSUE THREAD

**Issue by 0xPr0f** [shapeshift/web#1552]
### Overview

When i log in with my wallet, it shows your assets 
and then eth, but i dont have eth ?

### References and additional details

NA

### Acceptance Criteria

i think it should not show any assets there, even if it is as a place holder

### Screenshots/Mockups

<img width="818" alt="Screenshot 2022-04-21 at 8 18 32 PM" src="https://user-images.githubusercontent.com/94965754/164537269-df947833-2f03-4fd6-9f67-3ef749010507.png">

**Comment by 0xdef1cafe** [comment]
we need to at least show the accounts for supported chains
