### ISSUE TITLE
ATOM Staking widget on a stake the third step never updates

### ISSUE THREAD

**Issue by Neverwas-dev** [shapeshift/web#1553]
- Brief description

When staking ATOM the staking widget displays updates during the steps, the last third step (broadcast) never updates with a check when the broadcast is finished. 

- Steps to recreate
1. From the DEFI page choose Shapeshift DAO 
2. Choose Stake
3. input amount and continue
4. Choose gas fee and sign & broadcast

- Screenshots/vids

![image](https://user-images.githubusercontent.com/95000549/164540123-5c8a658c-331a-439f-98af-c08fdd2c3f12.png)

- AC 
Have the user flow continue to conclusion with the same UI (checks) as the process completes

**Comment by DiggyDiggy2** [comment]
It doesn't seem that this needs product review.

**Comment by DiggyDiggy2** [comment]
Can we close this one since its being fixed in another ticket?

**Comment by NeOMakinG** [comment]
@DiggyDiggy2 Which ticket are you talking about? I feel lost now

**Comment by DiggyDiggy2** [comment]
@NeOMakinG i thought https://github.com/shapeshift/web/pull/1562 addresses this?

**Comment by NeOMakinG** [comment]
@DiggyDiggy2 Yes it addresses it but this is a pull request, do we validate the fact that we wants the `Broadcast` step checked like the video of the PR shows?
