### ISSUE TITLE
Replace hardcoded FOXy APR in confirm step with updatable APR

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#1586]
### Overview

A new environment variable has been added for FOXy APR, but the confirm and status step in the FOXy staking flow still display the hardcoded APR of 15%.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/26232238/165328141-55d34c2f-ce81-4e41-bab4-0a0469bd43e0.png">

vs. 

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/26232238/165328367-85385047-d862-46e4-8582-690fb3b4fc22.png">

### References and additional details

Steps to reproduce:
1. Go through FOXy deposit flow
2. On confirm and status steps, Average APR is 15%

### Acceptance Criteria

AC:
1. All instances of the hardcoded FOXy APR are replaced with the environment variable

### Estimated effort

30 minutes

**Comment by 0xean** [comment]
closing as resolved in #1589
