### ISSUE TITLE
KeepKey Settings: Passphrase update success message displayed by default

### ISSUE THREAD

**Issue by mrnerdhair** [shapeshift/web#1592]
### Overview

The passphrase screen in KeepKey Settings shows "Passphrase successfully updated!" before clicking anything.

### References and additional details

(tbd)

### Acceptance Criteria

- The confirmation message should only display on an actual update of the passphrase, not by default.

### Screenshots/Mockups

![image](https://user-images.githubusercontent.com/645226/165403393-05c70432-83d3-4f99-b9e6-a12ec574906c.png)

### Estimated effort

2 hours

**Comment by mrnerdhair** [comment]
... dangit, this was on a feature branch. sorry for the confusion.

**Comment by 0xApotheosis** [comment]
Yes ser, that was a bug that I believe I fixed before the feature was rolled out 👍
