### ISSUE TITLE
Show a toast message if there is an available update to a connected KeepKey

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#1599]
### Overview

We currently alert a KeepKey user of any available updates to their device's firmware or bootloader in the KeepKey settings menu.

We should make this more visible by showing a toast as well.

### References and additional details

Use the same logic as the menu system to determine update status.

We have a `useKeepKeyVersions.ts` hook available that tracks this.

### Acceptance Criteria

A toast displays when a connected KeepKey has an available update.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

One day.

### Sponsor / Stakeholder

GitHub: 0xApotheosis
Discord: 0xApotheosis#2503 

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
@NeOMakinG to pick this up once Product has reviewed.

**Comment by reallybeard** [comment]
![Screen Shot 2022-04-28 at 11 02 00 AM](https://user-images.githubusercontent.com/89934888/165795260-9793d47c-ab08-4bfe-a8b7-58131cc97752.png)

To make the toast clickable we will need to use a custom alert component, see the update app toast in `App.tsx`. We should use the `solid` variant of the alert component.

**Comment by SS-FOX-McCloud** [comment]
@reallybeard @NeOMakinG does this still need product review or can we remove that tag?

**Comment by NeOMakinG** [comment]
> @reallybeard @NeOMakinG does this still need product review or can we remove that tag?

Should we display the toast only one time at the first connection? And then store the fact that it's been dismissed for a couple of days until showing it again?

Or should we display it every time we visit the app?

**Comment by reallybeard** [comment]
> > @reallybeard @NeOMakinG does this still need product review or can we remove that tag?
> 
> Should we display the toast only one time at the first connection? And then store the fact that it's been dismissed for a couple of days until showing it again?
> 
> Or should we display it every time we visit the app?

Its in their best interest to update, so I would every time they connect the wallet but haven't update it yet.

**Comment by NeOMakinG** [comment]
> > > @reallybeard @NeOMakinG does this still need product review or can we remove that tag?
> > 
> > 
> > Should we display the toast only one time at the first connection? And then store the fact that it's been dismissed for a couple of days until showing it again?
> > Or should we display it every time we visit the app?
> 
> Its in their best interest to update, so I would every time they connect the wallet but haven't update it yet.

Thanks for the reply, considering we don't need product input anymore :+1:
