### ISSUE TITLE
Handle factory-new KeepKey connections

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#1609]
### Overview

Upon connecting a factory-new KK -- or one which has been recovered after a failed firmware update -- the user gets dropped to this screen, which could be misleading if the user didn't initiate a wipe.

### References and additional details

Currently, when we receive a `NOTINITIALIZED` event from a KeepKey, we dispatch the `OPEN_KEEPKEY_INITIALIZE` action (assuming the user wiped it).

This even it also emitted when connecting a factory-new KeepKey.
We'll need a way to distinguish between a factory-new KeepKey that has not been initialized, and a KeepKey that has been wiped and needs to be re-initialized.

![165401124-20b3d3ed-632a-41c6-a086-dbdc6bbf3495](https://user-images.githubusercontent.com/97164662/165666467-2f0524e6-d576-4038-9635-d0fbca15bfa3.png)

### Acceptance Criteria

https://github.com/shapeshift/web/issues/1609#issuecomment-1112649156

**Comment by SS-FOX-McCloud** [comment]
Lets update the title of this modal to "Get Started with KeepKey".  Update the rest of the copy to "Your KeepKey is set to factory default settings. Create a new wallet, or restore a wallet using your secret recovery phrase" As this is the first modal in this flow lets also remove the back button. Also, the close button should redirect user back to the connect wallet

recap:
- update title to "Get Started with KeepKey"
- update copy to "Your KeepKey is set to factory default settings. Create a new wallet, or restore a wallet using your secret recovery phrase"
- remove back button
- closing out (x) redirects to connect wallet
