### ISSUE TITLE
Improve PIN modal

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#1613]
### Overview

There are a number of quirks with the PIN modal that we can improve.

![165401810-5e4d9cad-408c-4804-975a-8fbfa2befae6](https://user-images.githubusercontent.com/97164662/165669570-46f1ca3c-c716-424e-8419-b532fa9cbaa7.png)

### References and additional details

From @mrnerdhair:

1. This screen should focus the entry field to allow the PIN to be entered using only the numpad keys, which map to the KK's on-screen PIN layout.
1. Pressing the "Enter" key should have the same effect as pressing the confirm key.
1. Confirming the new PIN on the first screen and loading the second one briefly flashes "Unlock" instead of "Save PIN" on the button
1. If you exit after the first PIN screen, restarting the flow will hang unless you replug your device.
1. Pressing "Confirm" without any numbers entered greys out the button and prevents further progress. The PIN screen is also still displayed on device even after pressing the back button, breaking the previous flows. (Setting a PIN is technically optional during initialization, so trying a blank one could be a valid choice. Still, with my security hat on I'm happy to hide that from users. If we're going to do that, though, we should disable the button if it's blank.)

### Acceptance Criteria

All of the above improvements are implemented.

**Comment by pastaghost** [comment]
@GMSteuart No, this will require a KeepKey to replicate. As of today, this issue along with #1610 and #1607 have been assigned to @brymut via DeWork.

**Comment by fiyanrendiant** [comment]
`PASSWORD`

**Comment by 0xApotheosis** [comment]
> `PASSWORD`

Sir?

**Comment by fiyanrendiant** [comment]
Yes

Pada tanggal Kam, 25 Agu 2022 16.31, Apotheosis ***@***.***>
menulis:

**Comment by fiyanrendiant** [comment]
Thank you!

Pada tanggal Sen, 12 Sep 2022 14.16, Apotheosis ***@***.***>
menulis:
