### ISSUE TITLE
Fix "Cancel" button on "Write down Recovery Sentence" modal

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#1614]
### Overview

Pressing "Cancel" doesn't exit the screen or do anything, though it leaves the device in an uninitialized state.

### References and additional details

- Send a `cancel()` request to the connected device, if it doesn't do this already
- Do something with UX to make this more graceful - product to confirm, as per comment below in acceptance criteria.

### Acceptance Criteria

If a user cancels during this step have them routed back to the connect wallet screen. This is the same activity if they were to cancel during any other steps in the flow. The user would need to start the recovery flow over.

**Comment by SS-FOX-McCloud** [comment]
If a user cancels during this step have them route back to the connect wallet screen.  This is the same activity if they were to cancel during any other steps in the flow. The user would need to start the recover flow over.

**Comment by NeOMakinG** [comment]
@0xApotheosis I would like to take this one, should be quick, change the assign in case you've something against it

**Comment by 0xApotheosis** [comment]
Go for it @NeOMakinG! It should be a simple on - `AwaitKeepKey` accepts an optional `onCancel` prop that can be used here.
