### ISSUE TITLE
Re-pairing a KeepKey after wiping it hangs

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#1616]
### Overview

When a KeepKey is wiped and then immediately reconnected from the splash screen it hangs and never connects.

The only way around this, it seems, is to unplug the KeepKey after wiping it, and plugging it back in.

### References and additional details

This might actually be a bug with `hdwallet` or the KeepKey firmware.

### Acceptance Criteria

Either fix the bug, allowing the KeepKey to reconnect immediately without unplugging it, or the cause is identified as being something in `hdwallet` or the KeepKey firmware.

**Comment by markrypt0** [comment]
I can't reproduce this problem. From app.shapeshift.com I can wipe a keepkey and seamlessly flow to initializing device with both old and current firmware. Probably an obsolete bug.

**Comment by 0xApotheosis** [comment]
Thanks @markrypt0, I'll close this one out.
