### ISSUE TITLE
Add the ability to go back to previous words when restoring a KeepKey from a recovery phrase

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#1617]
### Overview

The KeepKey allows for seed words to be removed by backspacing through the letters.

In the current implementation, this is limited to backspacing through the current word.

### References and additional details

We currently only keep the current word in state as a fixed length array that represents the currently visible inputs.

We'll instead need to remember the entire seed phrase as we go, and have the input fields updated accordingly depending on the word that we are on.

### Acceptance Criteria

We can backspace through all seed words entered during the recovery flow until we leave this flow.

**Comment by MBMaria** [comment]
@pastaghost  am I assigning this as a bounty to @majorhayes in dework? and if so if there an amount you want me to put on it?
