### ISSUE TITLE
Cosmos - Merge `<GetStarted />` into `<Staking />` views

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1624]
### Overview

As a user with no staked positions yet, clicking "Start Staking" on the Cosmos staking modal routes to the "Overview" step of the Cosmos staking modal.
Since I have no staked positions yet, seeing the overview makes no sense and I should be seeing something more intuitive to guide me through the staking process. We actually have that already: the `<GetStarted />` modal, which we could display inside the Staking routes in place of the overview.

We should remove the current Cosmos `<GetStarted />` modal, move its content alongside all other Cosmos staking views, and add some logic to display it instead of the overview in case there are no staking data on any validator.

### References and additional details

- [`src/plugins/cosmos/components/modals/GetStarted/GetStarted.tsx`](https://github.com/shapeshift/web/blob/70d6e45070bf1e663a4869a99dee7c16d70fe03d/src/plugins/cosmos/components/modals/GetStarted/GetStarted.tsx) - the current `<GetStarted />` modal. You can grep for `cosmosGetStarted` to find out every place where we open that modal.
- [`src/plugins/cosmos/components/modals/Staking/Staking.tsx`](https://github.com/shapeshift/web/blob/60ffe3ffaa2e2198c72ad475dabbdcaa88d65819/src/plugins/cosmos/components/modals/Staking/Staking.tsx) - the component that handles the routing of Cosmos staking, we can add a condition there to either show `<Overview />` or `<GetStarted />`

### Acceptance Criteria

- `<GetStarted />` is not a modal anymore
  - it is removed from `<ModalProvider />`
  - the `src/plugins/cosmos/components/modals/GetStarted` folder is removed
  - the `<GetStarted />` and `<LearnMore />` components still exist and live inside `src/plugins/cosmos/components/modals/Staking/views/`, rendered either directly inside the `<Staking />` router, or inside `<Overview />` 
  - the internal routing of the current `<GetStarted />` modal is still working
- "Start Staking" routes to the "Staking" route
- Every place that opens the `<GetStarted />` modal now opens the `<Staking />` router. There should be no references to `cosmosStaking.open` / `cosmosStaking.close` anymore
- There is no regression in the existing `<Staking />` routing
- There is no flash of content i.e a step being rendered for a some amount of ms before going to the specified route

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

4 hours

### Sponsor / Stakeholder

@gomesalexandre (`gomes` on Discord)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
If we go for this, we probably want to be consistent in what we allow and don't allow, and:
- create a second issue to disable the unstake step link if there is no amount staked
  - possibly, disable the overview step if there is both no staked amount and no rewards amount

**Comment by reallybeard** [comment]
It would maybe be easier, and better if we just had a CTA on the overview if the user has no balance and no pending actions (claim, unstake, etc.)

We do this on FOXy

![Screen Shot 2022-05-03 at 11 23 52 AM](https://user-images.githubusercontent.com/89934888/166495095-7f8204a8-75fb-4405-a9de-574e452a661b.png)

**Comment by gomesalexandre** [comment]
> You already have this view, you can just remove that extra modal and make it the overview page.
> 
> ![Screen Shot 2022-05-03 at 11 26 28 AM](https://user-images.githubusercontent.com/89934888/166495817-9359e03d-ac9a-4ea0-adb1-3498889de9c0.png)

Ohh that sounds actually like a better idea and would not require any major logic change, we could just open the get started modal instead of the overview one. @DiggyDiggy2 WDYT?

**Comment by DiggyDiggy2** [comment]
yeah sounds good @gomesalexandre
