### ISSUE TITLE
Demo wallet enhancements

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#1637]
### Overview

* Deep linking functionality - so we can tweet a link that doesn't require clicking the "or view a demo ->" button
* Add a banner indicating that the user is using a demo wallet with a CTA to connect a real wallet
  * Consider where this will be shown on mobile
* Make the "or view a demo ->" button a solid variant/more prominent
* Operations
  * add more FOX to this wallet - probably such that FOX is the largest holding?
  * deposit a bunch of FOX into FOXy
 

### References and additional details

WIP

### Acceptance Criteria

WIP

### Need By Date

n/a

### Screenshots/Mockups

coming from product

### Estimated effort

tbd

**Comment by 0xdef1cafe** [comment]
@tshifty can you please do the following above with the wallet used to generate these demo xpubs?

**Comment by tshifty** [comment]
@0xdef1cafe done

**Comment by DiggyDiggy2** [comment]
mock up for "demo mode banner": https://www.figma.com/file/OHbVrAVaV2xQWUsq0nKzGm/ShapeShift-Library?node-id=548%3A2028

**Comment by DiggyDiggy2** [comment]
here's the image for how the 'demo" button should look. let's bring them side by side when screen width permits. And stack on mobile as needed
<img width="540" alt="Screen Shot 2022-05-02 at 10 58 01 AM" src="https://user-images.githubusercontent.com/90058616/166291436-62d3a863-aeff-4feb-8e32-8abd877b534c.png">
.

**Comment by MBMaria** [comment]
I can assign this to @0xf11nix in Dework. Just need to know estimated hours to complete, please?
