### ISSUE TITLE
Asset page - default to balance chart if non zero balance

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#1639]
### Overview

Currently - on assets, we default to the price chart. On an account page (which is known to have a non-zero balance), we default to the balance chart.

We can enhance this and default to the balance chart on the asset page if a user has a non-zero balance for a given asset.

### References and additional details

WIP.

### Acceptance Criteria

* The behavior works as described above.

### Need By Date

n/a

### Screenshots/Mockups

Read the description.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

30 mins

### Sponsor / Stakeholder

@0xdef1cafe @Diggy

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
closed in #1717
