### ISSUE TITLE
Different Assets displaying an incorrect amount staked in Native and KeepKey wallets

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#1645]
### Overview

Certain assets from the dashboard in either KeepKey or Native wallet are displaying a staked amount incorrectly. The assets are showing a staked amount to the same value as the current balance in the wallet that is staked for ATOM. So far the list of assets identified with the unusual staking balance are: BTC, USD, USDT, CRO, FUN, ICHI, OHM, MARK, COW, UST, CEL, SRM and GALA. Even if there is an amount staked for one of these assets, the asset page shows the amount staked to the value of ATOM staked opposed to the correct value. If the asset does not have any balance, in the wallet, or already staked, it is showing there is a value staked regardless.
Metamask and Portis are not displaying this issue which means it looks like it is only affecting the wallets that currently support Cosmos.

### References and additional details

1) Open app.shapeshift.com and connect to either Native or KK wallet.
2) Select one of these assets from the Dashboard (or asset list) BTC, USD, USDT, CRO, FUN, ICHI, OHM, MARK, COW, UST, CEL, SRM and GALA and notice an amount staked.
3) Select the Defi page and notice the amount staked in the wallet for ATOM.
4) Return to the original asset selected and notice if the amount staked is the same as the amount of ATOM staked.
5) Select BTC and notice the amount staked shows as the same amount of ATOM but with two additional decimal points.

![image](https://user-images.githubusercontent.com/100157997/166075642-533ec084-ac75-4892-8b0d-1d3c1fc7002a.png)

![image](https://user-images.githubusercontent.com/100157997/166075552-07faac7a-a96e-4882-b41f-41f5d6ad2f75.png)
![image](https://user-images.githubusercontent.com/100157997/166075519-01476117-2d9e-428f-8344-fa58bc0841c0.png)
![image](https://user-images.githubusercontent.com/100157997/166075537-0e68f3ad-3ce0-47ae-802a-e33943decf46.png)

### Acceptance Criteria

Assets should display correct staking amount. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
The wrong balance is fixed but now we don't show any staked amount at all except for ATOM. On it.
