### ISSUE TITLE
ShapeShift Native Wallet - Only prompt password entry if necessary

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#1646]
### Overview

Currently on app.shapeshift.com, native wallet users are prompted to enter their password every time they visit or refresh the app. Ideally, users should have to enter their password minimally, like the first time they are signing a transaction per session. Further, if a user has already unlocked their wallet to sign a tx and then refreshes the page, ideally they don't have to unlock their wallet again to sign another tx.

Q for engineering and security:
1. Are the AC below reasonable to implement?
2. Any better ideas for how to improve this UX?

### References and additional details

n/a

### Acceptance Criteria

AC:
1. Users are only prompted to enter their native wallet password when they are connecting their wallet for the first time on a browser or signing a tx
2. Users can see their native wallet's data and interact with the web app while their wallet is 'locked'
3. If a user's native wallet is 'unlocked' and they refresh the page, their native wallet is still unlocked

### Need By Date

I know there are ongoing discussions about native wallet's future, so no rush on this, esp. if it is one of those things that's easier said than done. I defer to engineering on whether it makes sense to prioritize this rn.

### Estimated effort

needs engineering

**Comment by 0xean** [comment]
marking as low priority due to complexity and potential for deprecation of native wallet.

**Comment by twblack88** [comment]
I have to write the spec for this but i have the scope.
