### ISSUE TITLE
FOX staking flow (from DeFi screen)

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#1656]
### Overview

When clicking into FOX token staking (FOXy) from "overview" in the  defi section the FOXy modal opens to the "withdrawal" screen/flow. We want the user to see the "overview" tab first. 

<img width="497" alt="Screen Shot 2022-05-02 at 1 13 57 PM" src="https://user-images.githubusercontent.com/57505863/166310387-de514ae6-a395-4038-a04a-4c16e142a1e6.png">

### References and additional details

this code lives in the FOXy staking modal

### Acceptance Criteria

A/C: When a user access FOX staking (FOXy) from the DeFi overview page (https://app.shapeshift.com/#/defi/)  the modal opens to the FOXy Overview screen. 

### Need By Date

n/a

### Estimated effort

hours

**Comment by chxash** [comment]
@SS-FOX-McCloud I noticed same behaviour was present on fox asset page when clicking on foxy opportunity (the modal was opened in "deposit" tab).
Currently all yearn vaults behave the same so do we really want to fix this to be consistent ?
I raised a PR for it anyway but I was just wondering.

**Comment by gomesalexandre** [comment]
@SS-FOX-McCloud Are we considered this as a fix, or do we want to iterate on the great comments from @chxash about consistency and use this issue to make the modal step consistent on all earn opportunities?
Since the PR didn't close the issue automatically, we will have to manually close it if we consider it fixed.

**Comment by SS-FOX-McCloud** [comment]
closed via https://github.com/shapeshift/web/pull/1706
