### ISSUE TITLE
KeepKey initialize and recovers flows goBacks behavior is wrong

### ISSUE THREAD

**Issue by NeOMakinG** [shapeshift/web#1662]
### Overview

I found a strange behavior/bug, if you enter the wallet name on both flows (recovery and initialize), you'll end to the pin view, then if you go back, you are asked to enter the wallet name again but the view is blocked after submitting it because both wallet.reset and wallet.recover throws an error ActionCancelled without any error code

As these methods throws, we don't receive the PINMATRIXREQUEST message, we end up being blocked on the Label view with the keepkey on the Enter new pin state...

### References and additional details

See the use of `wallet.recover` and `waller.reset` inside `Label.tsx` or the upcoming hook using it

They shouldn't throw at this point but probably accept the new label

### Acceptance Criteria

When you go back right after inserting your label, you should be able to either send the label again or the error should be handled

**Comment by 0xdef1cafe** [comment]
@cjthompson @pastaghost FYI
