### ISSUE TITLE
Pendo - ServiceWorker Fetch Filtering

### ISSUE THREAD

**Issue by mrnerdhair** [shapeshift/web#1672]
### Overview

The new ServiceWorker architecture needs a way to filter fetches at the request of the loaded page.

### References and additional details

- The architecture of the basic page-directed fetch filtering mechanism is described in https://github.com/shapeshift/alpha/issues/1.
- The new ServiceWorker architecture is in #1630.
- Note that `sw.js` doesn't get processed by webpack, so you can't import modules.

### Acceptance Criteria

- The page is able to register a fetch filter which matches outgoing requests by URL regex and communicates over a dedicated MessagePort.
- Upon an outgoing request matching the regex, the service worker calls the page back over the port and gives it a chance to inspect and modify the headers, url, and request body.
- Upon an incoming response matching the regex, the service worker calls the page back over the port and gives it a chance to inspect and modify the response headers and body.
- If either of the above callbacks fail, the service worker must not deliver the fetch response.

**Comment by 0xean** [comment]
closing due to incompatibility of service workers and metamask on ios
