### ISSUE TITLE
Password not working when switching to Native wallet

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#1684]
### Overview

When switching wallets to Native from any other wallet, when you entering the password it states that the password is invalid. If you just cancel out of that modal, the wallet will load as usual. Even if you don't enter any password at all and exit the password modal, the wallet will load.

### References and additional details

1) Log into app.shapeshift.com and connect to native wallet.
2) Switch to any other wallet.
3) Switch back to native wallet.
4) When prompted for password note that when entering the correct password is comes up with the error "invalid password".
5) Note that you can exit the password modal without entering a password (or "invalid password") and the wallet loads as usual.

### Acceptance Criteria

The wallet should not load if the correct password is not entered. Should not be able to by pass the password and have the wallet load. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
I'll take a look at this in the next few days 👍

**Comment by NeOMakinG** [comment]
@MBMaria 

It's because any wallet never gets disconnected if you switch from a wallet to another, meaning that you don't have to enter your password in order to select your native wallet, until it timeout or you click "Disconnect"

We have 2 possibilities:

- Close the modal directly without prompting the password view in case the wallet is already initialized
- Disconnect the current wallet in case you click somewhere (for example, on click on the "Switch wallet" button?)

Could we talk about it and define the specs?

**Comment by DiggyDiggy2** [comment]
> @MBMaria
> 
> It's because any wallet never gets disconnected if you switch from a wallet to another, meaning that you don't have to enter your password in order to select your native wallet, until it timeout or you click "Disconnect"
> 
> We have 2 possibilities:
> 
> * Close the modal directly without prompting the password view in case the wallet is already initialized
> * Disconnect the current wallet in case you click somewhere (for example, on click on the "Switch wallet" button?)
> 
> Could we talk about it and define the specs?

I think that in switching wallet, we should disconnect the current one. isn't this the case for all the other wallets, when switching?

**Comment by NeOMakinG** [comment]
@DiggyDiggy2 
When you switch from one wallet to another, the local state of the past wallet isn't cleared, meaning that you can switch to the past wallet without entering your passphrase again, I don't know if it's intended

Would it be fine if you click on `Switch Wallet`, and you end up on this view with the modal opened? 
![image](https://user-images.githubusercontent.com/14963751/168153029-4e57f4b7-8944-41c2-b1ee-19a5f93ebb36.png)

That would be the simplest way to fix that, the new action of switching wallets would be as simple as `Disconnect everything, remove local state and storage, then open the connect wallet modal`

Overwise, we could keep the local storage, (which would probably be unneeded anymore in case we clear it while switching?), but don't prompt the password modal while connecting to a wallet you previously connected to

**Comment by 0xean** [comment]
@shapeshift/product - can someone take a look @NeOMakinG comment and respond so we can move forward? Ty

**Comment by DiggyDiggy2** [comment]
Since we don't really need the user to enter their password if they have already added a native wallet. We can go ahead and close the modal directly without prompting the password view in case the wallet is already initialized

**Comment by 0xean** [comment]
@shapeshift/operations to take another pass to see if still valid.

**Comment by tshifty** [comment]
This ticket is still valid

**Comment by NeOMakinG** [comment]
I can take it, forget about it 😆

**Comment by Neverwas-dev** [comment]
> 

I can recreate as well still
