### ISSUE TITLE
WalletConnect integration

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#1686]
### Overview

We want to be able to connect *other wallets* into ShapeShift web app via WalletConnect, i.e. a user has another wallet, and we are the dapp.

*Using the ShapeShift native wallet, as a wallet to connect to other dapps, is out of scope.*

### References and additional details

* Spec here https://www.notion.so/shapeshift/WalletConnect-part-1-Integration-in-v2-e56a2b444132497595c201aef3e18500
* Depends on https://github.com/shapeshift/hdwallet/issues/499 and will block completion
* We can probably implement/comment out/put a half baked implementation behind a flag

### Acceptance Criteria

* Feature flag added
* Can connect via WalletConnect

### Estimated effort

1 day

**Comment by 0xdef1cafe** [comment]
@GMSteuart you're welcome to take this one if you want

**Comment by GMSteuart** [comment]
@0xdef1cafe awesome! I'll take it on
