### ISSUE TITLE
handleSubmit event handlers not working on buttons

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1697]
### Overview

https://github.com/shapeshift/web/commit/cd666cfe363fa6073acf2801fabbb7a7089e7eb6 brought some changes to handling submit events e.g:
https://github.com/shapeshift/web/blob/fb388470dfc2813b6b5be03d2e78e81a82a40c9a/src/components/Approval/Approval.tsx#L163-L165
Which produced a regression in events handlers not working anymore

Tried reverting to the previous handler prop, with no results.

Affected flows:

- Cosmos staking  - "Sign and broadcast" button not working
- Cosmos unstaking - "Sign and broadcast" button not working
- Cosmos claim - "Sign and broadcast" button not working
- Trade confirm - "Confirm and Trade" button not working
- Smart contract approval - confirm button not working

### References and additional details

- Grep for all `handleSubmit()` occurences in the aforementioned commit. 
- `console.log()` in `handleSubmit` handlers, no log is outputted in the console

https://github.com/shapeshift/web/commit/cd666cfe363fa6073acf2801fabbb7a7089e7eb6#diff-3298ebbad52758de2508438ba844cd7078ea7c038416f2ad44952a843ddb4096R163-R165

### Acceptance Criteria

- `handleSubmit` event handlers are fired
- All the regressions in the aforementioned flows are fixed, with the buttons working

**Comment by 0xApotheosis** [comment]
Closed by https://github.com/shapeshift/web/pull/1698
