### ISSUE TITLE
Error Page when using browsers that don't support Service workers

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#1743]
### Overview

We are in the process of migrating to an IPFS based front end solution that makes use of Service workers to set headers when loading the web app.  There are certain browsers / settings this fails on and we can serve a more friendly error message when it does. 

To simulate, use firefox private browser and go to this preview https://service-worker-spike.web-29e.pages.dev/#/connect-wallet?returnUrl=/dashboard

### References and additional details

![Screen Shot 2022-05-11 at 11 54 34 AM](https://user-images.githubusercontent.com/15096737/167914984-5438996e-7f27-4747-b4a8-9facbcf9f517.png)

We should also probably explicitly tell people on the error page that if they are using private mode in firefox, the site wont work. 

### Acceptance Criteria

- Implement static error page from product specs this will need to be done in pure HTML/CSS; it will go directly into the page template and can't use any JS at all. (That also means it'll be delivered with every page load, so it would be good to keep it light from a code-size perspective.)

### Estimated effort

4 hours

**Comment by mrnerdhair** [comment]
Just that the error message will need to be done in pure HTML/CSS; it will go directly into the page template and can't use any JS at all. That also means it'll be delivered with every page load, so it would be good to keep it light from a code-size perspective.

**Comment by 0xean** [comment]
> Just that the error message will need to be done in pure HTML/CSS; it will go directly into the page template and can't use any JS at all. That also means it'll be delivered with every page load, so it would be good to keep it light from a code-size perspective.

thanks! added.

**Comment by MBMaria** [comment]
Hi @0xean , are you or @mrnerdhair  taking responsibility for this ticket? Just checking who I need to put the reviewer as in Dework for the bounty.

**Comment by mrnerdhair** [comment]
I'll do the review, since the service worker machinery is pretty specialized. Most of the work here will be on the product side; once there's a spec, implementing it will be trivial.

**Comment by mrnerdhair** [comment]
Per yesterday's meeting, we're dropping this approach for now, so we don't need an error page for it.

**Comment by reallybeard** [comment]
Well if this ever comes up --- something like this would work

https://www.figma.com/proto/OHbVrAVaV2xQWUsq0nKzGm/ShapeShift-Library?node-id=684%3A2305&scaling=min-zoom&page-id=684%3A2290
