### ISSUE TITLE
Display swapper sell assets sorted by balance so that assets with balance are on top

### ISSUE THREAD

**Issue by elmutt** [shapeshift/web#1744]
### Overview

Display swapper sell assets sorted by balance so that assets with balance are on top

### References and additional details

Sort assets by balance before displaying them in swapper sell menu

### Acceptance Criteria

Assets are shown sorted by balance in the sell dropdown menu

**Comment by 0xean** [comment]
@elmutt - to clean up for bounty.

**Comment by elmutt** [comment]
We are going to turn this into a bounty soon

**Comment by elmutt** [comment]
Created bounty
