### ISSUE TITLE
terms of service link in erc-20 staking modal routing to dashboard/terms of service stays in url

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#1745]
### Overview

clicking on the terms of service in ERC-20 staking modal opens up a new window that goes to the dashboard instead of a terms of service page. also after you click the terms of service link the legal/terms-of-service stays in your url. you have to copy past the url back in to get rid of it.

### References and additional details

1. go to https://3202a9af.web-29e.pages.dev/ or app.shapeshift.com and connect with any wallet
2. click on the defi tab
3. click one of your ERC-20 vaults
4. click on the deposit tab on the top of the widget
5. go the the bottom of the widget and click on the terms of service link.
6. notice that it opens a new tab and directs you back to the dashboard.
7. also notice that /legal/terms-of-service# stays in the url as you natigate the app

- happening on all browsers 

### Acceptance Criteria

the terms of service link should take you to a new tab with the terms of service. also the /legal/terms-of-service# should not stay in your url when you navigate off of the page. 

### Screenshots/Mockups

<img width="416" alt="Screenshot 2022-05-11 152910" src="https://user-images.githubusercontent.com/99363597/167936149-90c65c41-85f5-43df-8a04-05e303b30051.png">
<img width="429" alt="Screenshot_2022-05-04_115100" src="https://user-images.githubusercontent.com/99363597/167936151-c0e4fb01-873e-4b08-97f8-18b59169029e.png">

**Comment by NeOMakinG** [comment]
Looking at it right now!
