### ISSUE TITLE
Fox Page - Tabs component - Routing

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1767]
### Overview

After the implementation of the dumb components for the Fox Page tabs, we should wire it up to the routing

### References and additional details

Dumb component implementation: https://github.com/shapeshift/web/issues/1766

### Acceptance Criteria

- Routing for the tabs is implemented (see https://github.com/shapeshift/web/issues/1763 for routing reference)
- The right selected tab is displayed according to the current route

### Screenshots/Mockups

Mockups: https://www.figma.com/proto/WgALgik9YuWzq7VIM0JRdb/FOX-Page-Bounty?node-id=71%3A533&scaling=min-zoom&page-id=71%3A532
<img width="930" alt="image" src="https://user-images.githubusercontent.com/17035424/168136306-ad0b55e8-1557-4bfa-bfd0-18f44ca0456f.png">

### Estimated effort

4 hours

**Comment by 0xean** [comment]
@gomesalexandre - are we able to proceed with this one based on todays meeting?
