### ISSUE TITLE
Fox Page - FOX Market Data

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1771]
### Overview

We should create/integrate a component displaying the market data of FOX/FOXy.

This is very similar to a component we already have, `<AssetMarketData />`:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/17035424/168155407-05c0320a-4726-4795-a855-9f0ab64a1427.png">

It seems that we should be able to reuse it with minor changes, since the only additional fields are Max Available Supply and Total Supply.

### References and additional details

https://github.com/shapeshift/web/blob/8f975ac6f1315f96c6666c9e1721230fdfa9fbff/src/components/AssetHeader/AssetMarketData.tsx#L13-L16

### Acceptance Criteria

- The `<AssetMarketData />` component is reused (if possible), with `<asset symbol>` prefixed before the "Market Data" header (not dynamic, only FOX for now according to the hardcoded FOX asset ID)
- If not possible, a similar component is implemented
- Regardless of the chosen solution, it should support all the fields `<AssetMarketData />` currently supports:
 - Price
 - Market Cap
 - 24 Hrs Volume
 - Day Change
plus 
- Max Available Supply
- Total Supply.
- Note that this might be the exception to being implemented in a *fully* dumb way, in case we reuse `<AssetMarketData />`. Since it is expecting `assetId` and `isLoaded` as props, we should pass them **hardcoded for now**, with FOX.

### Screenshots/Mockups

Mockups: https://www.figma.com/proto/WgALgik9YuWzq7VIM0JRdb/FOX-Page-Bounty?node-id=71%3A533&scaling=min-zoom&page-id=71%3A532

<img width="303" alt="image" src="https://user-images.githubusercontent.com/17035424/168155200-fc4071b2-632a-4250-adc8-3867127037cf.png">

**Comment by gomesalexandre** [comment]
@DiggyDiggy2 This one raises over a few design questions: 
1. Do we want to display these fields in the asset/account pages whenever possible, for consistency?
2. Do we want to display the up/down icon similarly to the asset/account pages, as it isn't present in the mock?
3. Do we want to also prefix `Market Data` in the asset/account page with the asset symbol for consistency?

**Comment by chxash** [comment]
@gomesalexandre maybe a dumb question, but do we already have max supply / available supply available somewhere ? Was not able to find them at first glance

**Comment by DiggyDiggy2** [comment]
> 

1. We'd like the 2 extra fields here for Max Total supply and available supply. If this is something we can also easily grab for the other assets we support as well, that would be a nice addition. However, for now, let's see if we can just add into this page (and we could write up a ticket to add those fields onto the other asset pages).
2. Yes, please add the up/down icon - that was an oversight on the mock up
3. No, we can just remove the word "FOX" from in front of "Market Data", we don't need that. Thanks!

**Comment by gomesalexandre** [comment]
> @gomesalexandre maybe a dumb question, but do we already have max supply / available supply available somewhere ? Was not able to find them at first glance

We already have `maxSupply` coming from Coincap responses, which is the "Max Total Supply", and `supply` which is the "Available Supply" so we can use this.
There's also `totalSupply` on ERC20 contracts (see [EIP-20](https://eips.ethereum.org/EIPS/eip-20)), however that's simply the total token supply, without a notion of "max", so we should probably be using Coincap (effectively, `market-service`) to retrieve these values).

**Comment by 0xdef1cafe** [comment]
@gomesalexandre i'd just have the base component check for the existence of two new optional params and display them if the data exists, use the base component in the plugin where the data is available.

**Comment by chxash** [comment]
@0xdef1cafe @DiggyDiggy2 I am currently integrating the supply fields into lib and I am facing an issue.
For "Max total supply" we have candidate fields `max_supply` and `total_supply` in coingecko api (fox example : https://api.coingecko.com/api/v3/coins/ethereum/contract/0xc770eefad204b5180df6a14ee197d99d808ee52d).
I am not sure which one to use for our case, for example in the previous url, only total_supply is defined to the correct value.
