### ISSUE TITLE
Fox Page - Get FOX - Wire-up

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1778]
### Overview

This wire-up is a follow-up of #1777.

It should implement the buy and receive actions.

It should also remove the hardcoded props.

### References and additional details

See #1777

### Acceptance Criteria

- It is possible to buy FOX and FOXy assets using the CTA
  - For FOX, this uses the Coinbase Pay SDK: https://docs.cloud.coinbase.com/pay-sdk/docs
  - Note: A Coinbase Pay SDK Fiat Ramp issue will be created by @SS-FOX-McCloud but this is not blocked by it. We can just use a regular link to the Coinbase FOX Page (https://www.coinbase.com/price/fox-token) in the meantime
  - For FOXy, we open the FOXy staking modal 
- It is possible to open the receive modal for the current asset
- `assetId` is used as a discriminator. Props that can be gotten from selectors (symbol, description, icon...) should be accessed like so, and the now unused props removed. 
- There is no longer hardcoded props, all data is gotten programmatically from the current route

### Screenshots/Mockups

Mockups: https://www.figma.com/proto/WgALgik9YuWzq7VIM0JRdb/FOX-Page-Bounty?node-id=71%3A533&scaling=min-zoom&page-id=71%3A532

<img width="305" alt="image" src="https://user-images.githubusercontent.com/17035424/168159092-189a4791-12fa-45f1-b35e-9da75681cde3.png">

### Estimated effort

4 hours

**Comment by NeOMakinG** [comment]
@gomesalexandre we don't need any routing, we are using Chakra Tabs which does everything by itself

You will probably want to close this issue as nothing needs to be done for the routing but it will be waiting for the asset logic

**Comment by gomesalexandre** [comment]
> @gomesalexandre we don't need any routing, we are using Chakra Tabs which does everything by itself
> 
> You will probably want to close this issue as nothing needs to be done for the routing but it will be waiting for the asset logic

Just for reference since @chxash started on this one and it might be confusing to anyone looking at this comment: This issue is for wiring the component up, not for routing as initially written, so it is still valid

**Comment by gomesalexandre** [comment]
@SS-FOX-McCloud Do we want a description for FOXy as well? It's missing on the notion, we just have a general-purpose FOX token description that we use both for FOX (the token) and the FOX Page heading. You mentioned that we wanted to consolidate the fox page heading with something that encapsulates both, but we should also have some FOXy copy (that would also be on the asset page, currently missing)

Get FOX: 
<img width="849" alt="image" src="https://user-images.githubusercontent.com/17035424/170228154-82aec7b4-750c-4203-9552-5a469029212e.png">
Get FOXy:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/17035424/170228197-411a9981-af79-4d05-b44e-61348523489a.png">

**Comment by SS-FOX-McCloud** [comment]
> @SS-FOX-McCloud Do we want a description for FOXy as well? It's missing on the notion, we just have a general-purpose FOX token description that we use both for FOX (the token) and the FOX Page heading. You mentioned that we wanted to consolidate the fox page heading with something that encapsulates both, but we should also have some FOXy copy (that would also be on the asset page, currently missing)
> 
> Get FOX: <img alt="image" width="849" src="https://user-images.githubusercontent.com/17035424/170228154-82aec7b4-750c-4203-9552-5a469029212e.png"> Get FOXy: <img alt="image" width="846" src="https://user-images.githubusercontent.com/17035424/170228197-411a9981-af79-4d05-b44e-61348523489a.png">

Thanks @gomesalexandre - Yes, I am meeting with Lindsay later today to go over the copy she has written, so that can be left for now but FOX and FOXy will have different descriptions.  Should have those by end of day. And yes, lets call the page "My FOX" for now.  That may be updated as well.  Thanks!

**Comment by gomesalexandre** [comment]
Closed by https://github.com/shapeshift/web/pull/1865.
