### ISSUE TITLE
Transactions page showing different naming sequence for some assets

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#1781]
### Overview

The word 'Transactions' doesn't show after the / when selecting the asset from the accounts page, but it does for the asset page for ETH, BTC and ATOM. But for ERC-20 assets 'transactions' appears if you select that tab from either assets or account page

### References and additional details

1) Log into app.shapeshift.com and connect to a wallet
2) If choosing MM, select ETH; if choosing Native, select ETH, BTC or ATOM from the accounts page.
3) Select the Transaction history tab and notice the naming sequence at the top of the page. Notice that the word 'Transactions' doesn't appear after the /.
4) Select ETH, BTC or ATOM from the asset page and notice after going to the transaction tab that the word 'Transactions' appears after the /
5) Select any other ERC-20 asset from the accounts page, go to the Transaction Tab and notice that the word 'Transactions' appears as expected.
![image](https://user-images.githubusercontent.com/100157997/168201318-b6727956-993f-423d-82d0-a472fa0e6f31.png)
![image](https://user-images.githubusercontent.com/100157997/168201344-14d6d746-c825-415e-8129-5ab8c5d84f78.png)

### Acceptance Criteria

Naming sequence should be consistent across all assets and across all pages.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

5 hours

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
That one's related to the routing/CAIP parsing:

https://github.com/shapeshift/web/blob/60ffe3ffaa2e2198c72ad475dabbdcaa88d65819/src/Routes/RoutesCommon.tsx#L43-L60

https://github.com/shapeshift/web/commit/1a8f9ec3c is also a commit that can also be read to understand how the nested routing works, in particular:

https://github.com/shapeshift/web/blob/a4b3e1128327236e896bd8c5fb73789673d88587/src/components/Breadcrumbs/Breadcrumbs.tsx#L30-L34

We effectively parse the CAIP from routes to use in breadcrumbs, but historically had some issues from accounts/assets pages. @DaoDev44 IIRC, https://github.com/shapeshift/web/commit/ac0a08128dd27d387a3d446225afe0a8ac9dcae3 tackled something similar?

**Comment by 0xean** [comment]
@gomesalexandre - is this ready for a bounty or what are next steps?

**Comment by gomesalexandre** [comment]
> @gomesalexandre - is this ready for a bounty or what are next steps?

Yeah we can bounty it out, the comment I added provides all the guidance that's needed to start debugging. Estimated effort is 5 hours, probably a bit less if assigned to a contributor who knows the codebase already.

**Comment by 0xApotheosis** [comment]
Assigned to @vividwood on Dework.
