### ISSUE TITLE
Dynamically calculate ETH-FOX APR

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#1788]
### Overview

We currently have an env var to set the ETH-FOX APR in the /defi/earn page

This can be calculated programatically, as per fox.shapeshift.com

### References and additional details

* https://github.com/shapeshift/foxfarm - APR calculation logic is in here somewhere

### Acceptance Criteria

* Don't rely on env var for this APR
* Dynamically calculate APR via web3 call

### Need By Date

n/a

### Screenshots/Mockups

currently hardcoded

<img width="864" alt="image" src="https://user-images.githubusercontent.com/88504456/168361202-105a3cfa-0858-426e-9fcf-bb6c6688813c.png">

dynamically calculated

<img width="935" alt="image" src="https://user-images.githubusercontent.com/88504456/168361590-8a4c7713-e088-4a74-a991-76b491beb023.png">

### Estimated effort

2 hours

**Comment by 0xean** [comment]
@gomesalexandre - can we knock this out with your plugin page as it will be the same code to calc APR?

**Comment by gomesalexandre** [comment]
> @gomesalexandre - can we knock this out with your plugin page as it will be the same code to calc APR?

Will be the exact same info, but IMO we still want to keep this issue to **consume** it since currently it will be plugin-scoped.
