### ISSUE TITLE
Fox Page - Price Chart

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1795]
### Overview

We should create/integrate a component displaying the balance chart of the selected FOX/FOXy opportunity.

This is very similar to a component we already have, `<PriceChart />`:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/17035424/168472655-eafc4885-8ab9-4a00-a39c-2c94e27b4095.png">

### References and additional details

https://github.com/shapeshift/web/blob/ddb2c5af32dfae645c9c67e4e1ff87179b0bff02/src/components/PriceChart/PriceChart.tsx#L25-L30

### Acceptance Criteria

- The `<PriceChart />` component is reused (if possible)
- "Current Price" header is displayed
- The percentage change for the selected timeframe is displayed
- A price chart is shown for that timeframe
- It is possible to pick a timeframe 

### Screenshots/Mockups

Mockups: https://www.figma.com/proto/WgALgik9YuWzq7VIM0JRdb/FOX-Page-Bounty?node-id=71%3A533&scaling=min-zoom&page-id=71%3A532

<img width="409" alt="image" src="https://user-images.githubusercontent.com/17035424/168472535-8f97fa3d-d853-4bf5-a99b-389f2bacdc75.png">

**Comment by NeOMakinG** [comment]
The component is ready but I wont open the PR yet as it can't be developed in a storybook context properly, as we mainly reuse existing components
