### ISSUE TITLE
Fox Page - Trade FOX

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1796]
### Overview

As a user, I want to be able to trade the currently selected asset.

As per design handover discussions, the component used should be the same as the current trade component.

### References and additional details

`src/pages/Dashboard/TradeCard.tsx`:

https://github.com/shapeshift/web/blob/ddb2c5af32dfae645c9c67e4e1ff87179b0bff02/src/pages/Dashboard/TradeCard.tsx#L9-L17

### Acceptance Criteria

- When going from the "Get `<asset>`" to "Trade", the box should resize to accomodate for the bigger trade component
- The current Trade component is reused
- The `defaultBuyAssetId` prop is used with the currently selected asset
- If trading is unavailable for the current asset (for FOXy), a "FOXy is not yet tradeable on ShapeShift" message is shown with a link to an external website (**waiting for full spec**)

### Screenshots/Mockups

Mockups: https://www.figma.com/proto/WgALgik9YuWzq7VIM0JRdb/FOX-Page-Bounty?node-id=71%3A533&scaling=min-zoom&page-id=71%3A532

<img width="407" alt="image" src="https://user-images.githubusercontent.com/17035424/168482420-50016f3d-0416-40db-9080-8c60c838f447.png">

### Estimated effort

2 hours

**Comment by DiggyDiggy2** [comment]
FOXy trade modal:  message: "FOXy is not yet tradeable on ShapeShift. You can trade FOXy on ElasticSwap." shown with a link out to Elastic Swap
