### ISSUE TITLE
Find a way to have swapper specific trade data on a trade

### ISSUE THREAD

**Issue by elmutt** [shapeshift/web#1801]
### Overview

Currently trades have zrx specific trade data on them. We need a way to have swapper specific data on each swapper.

Talk with defi, elmutt & daodev before starting this ticket

### References and additional details

The following 3 fields on trade are zrx specific:

https://github.com/shapeshift/lib/blob/main/packages/swapper/src/api.ts#L83

### Acceptance Criteria

Different swappers can have different trade data

**Comment by 0xean** [comment]
@elmutt - is this completed with the abstraction or still todo?
