### ISSUE TITLE
bug - trade widget builds tx of $1 without inputting any values

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#1803]
### Overview

after logging in, the trade widget will build a tx of $1 without inputting any values

### References and additional details

1. go to app.shapeshift.com or https://31a7d7fe.web-29e.pages.dev/
2. log in with mm, native, or kk
3. go to the trade widget on the right hand side of the screen
4. click on preview trade and then confirm trade
5. notice that a tx is built without putting any values in

### Acceptance Criteria

trade widget should default with $1 in trade modal to load pricing data and notify the user that a trade will go thorough. or if trade modal values equal $0, trade modal should not build a tx 

### Screenshots/Mockups

<img width="313" alt="Screenshot 2022-05-16 135230" src="https://user-images.githubusercontent.com/99363597/168654195-4eee3432-a26f-41c3-9d60-e34fdc36b2c7.png">

see tx build around :57 of this video 

https://user-images.githubusercontent.com/99363597/168654211-078d227a-9472-4cf6-af53-8150406ca77a.mp4

**Comment by 0xean** [comment]
@elmutt to resolve
