### ISSUE TITLE
Fox Page - Other Opportunities

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1805]
### Overview

We should create a component to display the opportunities other than the main for FOX/FOXy, with all their info and CTAs to get started with each opportunity.

Any work on this should be considered presentational for now. https://github.com/shapeshift/web/issues/1834 will wire it up.

### References and additional details

See #1785

### Acceptance Criteria

- A "Other Opportunities" heading is displayed
- "Liquidity Pools", "Farming", and "Borrowing & Lending" accordions are displayed
  - They can be collapsed/expanded, showing the relevant list of opportunities (hardcoded)
- Each item contains the relevant icon/name/APY/"Get Started" CTA for the opportunity

### Screenshots/Mockups

<img width="863" alt="image" src="https://user-images.githubusercontent.com/17035424/168684780-cc3351d0-9d83-4668-8f52-c7ac3d25f801.png">

Mockups: https://www.figma.com/proto/WgALgik9YuWzq7VIM0JRdb/FOX-Page-Bounty?node-id=71%3A533&scaling=min-zoom&page-id=71%3A532

### Estimated effort

4 hours

**Comment by NeOMakinG** [comment]
Already worked on it, the dumbest possible presentational component should be done already

<img width="753" alt="image" src="https://user-images.githubusercontent.com/14963751/168691107-42160801-b16c-49f7-8d58-67d1c1402ddb.png">

**Comment by gomesalexandre** [comment]
Closed by https://github.com/shapeshift/web/pull/1862
