### ISSUE TITLE
drop down wallet menu arrow

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#1807]
### Overview

drop down wallet menu arrow does not go back into default state when you click outside of the window and the menu closes.

### References and additional details

1. go to app.shapeshift.com
2. log in with mm, kk, or native
3. click on the wallet menu button with the arrow symbol pointing to the right (top right hand side of the screen)
4. observe the arrow points down when the menu is open
5. click outside the wallet menu and observer the menu collapses, but the arrow does not switch positions

- happening on all browsers: brave, edge, firefox, and chrome 

### Acceptance Criteria

arrow should move back to the closed position, pointing to the right, when the wallet menu closes when clicking on the page, outside of the menu. 

### Screenshots/Mockups

https://user-images.githubusercontent.com/99363597/168690039-a0c03022-983a-478c-a25d-3c945a8a480f.mp4

![InkedScreenshot 2022-05-16 155725_LI](https://user-images.githubusercontent.com/99363597/168690051-5594f1cb-b2a0-46e2-8e24-b91aa763cabc.jpg)

**Comment by DiggyDiggy2** [comment]
the arrow can just point down at all times, since its not actually collapse-able.
