### ISSUE TITLE
white screen when approving a contract on windows 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#1813]
### Overview

when approving a contract on windows, site crashes to a white screen 

### References and additional details

1. on windows go to https://5fb08634.web-29e.pages.dev/ or app.shapeshift.com
2. log in with mm, kk, or native
3. go to the trade modal and confirm a new contract
4. while waiting for the contact to confirm, site crashes to white screen

- browsers tested: brave, firefox, chrome

### Acceptance Criteria

site should not white screen when approving a contract. after the contract is approved you should be able to continue with your trade.

### Screenshots/Mockups

White screen at :57 in this video

https://user-images.githubusercontent.com/99363597/168877825-6e7d0414-93bd-4648-9fc9-d49d2a28c59d.mp4

**Comment by 0xean** [comment]
@elmutt will take a look at this one.

**Comment by 0xdef1cafe** [comment]
@wesleygravess plz reopen if this isn't fixed

**Comment by wesleygravess** [comment]
confirmed fixed and working in prod
