### ISSUE TITLE
error toast with contract approval

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#1816]
### Overview

when approving a contract in the trade modal, you get a toast error that states, "Insufficient funds for miner fee and amount."

### References and additional details

1. go to app.shapeshift.com
2. log in with mm, kk, or native
3. confirm a new contract in the trade modal
4. notice the toast error that pops up, "Insufficient funds for miner fee and amount."

browsers tested: brave, chrome, firefox

### Acceptance Criteria

you should not get the error, "Insufficient funds for miner fee and amount." when approving a contract and you have sufficient funds 

### Screenshots/Mockups

<img width="439" alt="Screenshot 2022-05-17 125140" src="https://user-images.githubusercontent.com/99363597/168894225-ec60deb7-ab38-4a40-b01d-946c80458ebf.png">

**Comment by 0xean** [comment]
@elmutt to take a look at this one.
