### ISSUE TITLE
Fox Page - Governance

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#1825]
### Overview

We should implement a component that displays the Governance Data.

This is a presentational component only, to be followed by a wire-up.

### References and additional details

See https://github.com/shapeshift/web/issues/1768 for technical spike of this

It should be read before, even though no logic is going to be added, the API of the components is going to be clearer once familiar with Boardroom API and the fields that we need from there/the parsing that will be done.

### Acceptance Criteria

- The "Governance" heading is shown for the component
- It is possible to click "See All Proposal", linking to `https://app.boardroom.info/shapeshift/proposals`
- A mock proposal is shown containing:
  - Proposal Title
  - Choices containing:
    - Choice name
    - Absolute Scores
    - Scores as percentages
- It is possible to click the mock proposal, linking to the relevant proposal (the [latest one](https://app.boardroom.info/shapeshift/proposal/cHJvcG9zYWw6c2hhcGVzaGlmdDpkZWZhdWx0OjB4MjUyOGFmNzc1ZWE3MDJhMTJkYTE2OGI2ZDdmODQzOGJhNGVhZTFjZWJmNDNkNzNiMzZhZDFkZGIzZWRlZjI2MA==) can be used as a mock)

### Screenshots/Mockups

<img width="639" alt="image" src="https://user-images.githubusercontent.com/17035424/168148120-130f04c3-f912-4855-81e7-052e3da20151.png">

### Estimated effort

3 hours

**Comment by NeOMakinG** [comment]
The HTML/CSS is ready for this one but I need to dive into specs in order to add some props and whatever

**Comment by gomesalexandre** [comment]
> The HTML/CSS is ready for this one on the `foxpage-governance` branch but I need to dive into specs in order to add some props and whatever

@NeOMakinG Pushed clean, mergefixed history into `foxpage-governance-clean` (in case you need the original) and PR'd https://github.com/shapeshift/web/pull/1902 with yourself as the author of the component diff.
Also added a `<Skeleton />` component to handle the loading state.
All that will be needed after that's merged is adding it as app code in #1828
