### ISSUE TITLE
Incorrect information about ATOM unstaking time in Learn More on Cosmos (ATOM) Staking Overview page.

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#1853]
### Overview

It states that it takes 14 days to unbond instead of the correct 21 days to unbond in the learn more section on the overview page.

![image](https://user-images.githubusercontent.com/94986227/169564391-1512e9b0-e99c-4379-b267-1ff3f65b9bb3.png)

### References and additional details

Recreation Steps 
1. connect a COSMOS supported wallet to app.shapeshift.com
2. Go to the DeFi tab
3. Click on Earn Tab
4. Go to the Cosmos (ShapeShift DAO Validator)
5. Click Learn More while on the Overview Tab
6. Click Next
7. Observe the incorrect information

### Acceptance Criteria

Please correct the information to 21 days instead of 14 days.

**Comment by gomesalexandre** [comment]
Nice catch. It's a code smell from the original Osmosis implementation, I'll make a PR for that.
Eventually, when we support staking across multiple (IBC/non-IBC) protocols, we should be able to always get the granularity of each protocol right, including info like this one
