### ISSUE TITLE
App.shapeshift.com All time frame chat on dashboard showing incorrectly.

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#1874]
### Overview

When viewing the all-time frame on the dashboard for app.shapeshift.com, it seems like it is off by an order of magnitude.

https://discord.com/channels/554694662431178782/978713734950289438

### References and additional details

repo steps 
1) connect to demo wallet or any wallet
2) wait for the page to load and click all timeframe on the dashboard chart
3) Observe the chart being off significantly from the balance of the wallet

![image](https://user-images.githubusercontent.com/94986227/170098863-ed05c415-1d2e-446c-85a4-326563c85e0f.png)
the 

### Acceptance Criteria

For the all chart on the dashboard to display the proper information.

**Comment by 0xdef1cafe** [comment]
@tolltalcrypto can you still repro as we were having market data issues upstream which are now fixed? ty

**Comment by 0xean** [comment]
@tolltalcrypto please confirm if still happening

**Comment by 0xean** [comment]
confirmed it is still occurring. Low priority.

**Comment by 0xdef1cafe** [comment]
need to pull cosmos staked logic out of `useBalanceChartData`, do it in a selector, that deals with all chains with staked native assets (cosmos & osmosis)

**Comment by 0xdef1cafe** [comment]
blocker to be able to do rainbow charts
