### ISSUE TITLE
Integrate Coinbase Pay as additional fiat on ramp

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#1918]
### Overview

Coinbase Pay is an SDK/UI widget that lets users sign-in to their Coinbase account and use their saved payment methods or crypto balance on self-custody wallets or dapps.

By integrating this we are giving our users another way to on/off board their crypto/fiat!

This wiget will also live on the FOX page so users can buy/sell their FOX direct via Coinbase.

All flows will match the current abstraction similar to Banxa and Gem.

Once work is ready to start on this we can do a further technical breakdown. May want to start with a spike!

### References and additional details

* https://docs.cloud.coinbase.com/pay-sdk/docs
* fiat ramp abstraction here https://github.com/shapeshift/web/blob/develop/src/components/Modals/FiatRamps/config.ts#L26-L27

### Acceptance Criteria

AC:
- Coinbase Pay is added as another on/off ramp provider. 

### Need By Date

n/a

### Screenshots/Mockups

<img width="502" alt="Screen Shot 2022-06-01 at 11 48 24 AM" src="https://user-images.githubusercontent.com/57505863/171470039-93e09ae2-14f6-4e8d-ac2d-0627770ab5b6.png">

### Estimated effort

days

**Comment by SS-FOX-McCloud** [comment]
@0xdef1cafe @DiggyDiggy2 What are your thoughts on Gomes's approach?

**Comment by DiggyDiggy2** [comment]
We will just show 'buy" in the modal that opens next to the Coinbase option.  
Would prefer to use our button

**Comment by theoboldfrazier** [comment]
@gomesalexandre @DiggyDiggy2 @SS-FOX-McCloud 

I was looking at taking this on, have we applied to use the Coinbase Pay SDK?

According to their docs, we need an application ID from them in order for this to work and we'd need to apply to them to get that id.

https://docs.cloud.coinbase.com/pay-sdk/docs/getting-started

See the initOnRampParams here, appId is required: https://docs.cloud.coinbase.com/pay-sdk/docs/integrating-pay

**Comment by gomesalexandre** [comment]
> According to their docs, we need an application ID from them in order for this to work and we'd need to apply to them to get that id.

Yeah that's something we initially noticed when we started spiking it (initially, just to use it in the Fox), IIRC we sent https://www.coinbase.com/cloud/cloud-interest already. @SS-FOX-McCloud can you confirm ? 🙏🏽
