### ISSUE TITLE
Defi page on beta giving IPFS error

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#1932]
### Overview

When attempting to access the earning/defi page on beta, it take you to a new window and displays an error about ipfs resolve.

### References and additional details

1) Log into beta.shapeshift.com
2) Connect to any wallet
3) Select the Earn page in the side menu
4) Select ‘Get started’ and notice it opens a new window and crashes to white screen with an error about ipfs resolve.

Noticed after testing on 6/2/22 after cutting over app.shapeshift.com from CF Pages to Fleek / IPFS

![image](https://user-images.githubusercontent.com/100157997/171779019-60ea510f-e7ff-4a80-9421-8dc57ece670a.png)

### Acceptance Criteria

Should be able access earning/defi page from beta

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
https://github.com/CroixDrinkers/axiom/pull/3619 related PR to resolve the issue.

**Comment by mrnerdhair** [comment]
Caused by #1155.
