### ISSUE TITLE
Analytics Opt-in Modal

### ISSUE THREAD

**Issue by decentralized-j** [shapeshift/web#1964]
### Overview

Gm!

As we near the GTM for Pendo and analytics on the ShapeShift platform, we want to make sure our users are absolutely aware of what is going on behind the scenes to protect their privacy and maintain their autonomy if they so choose.

Once Pendo is ready to roll, we'd like to add the following modal as a default pop up on app.shapeshift.com. Users cannot interact with app.shapeshift.com until they have selected either 'Continue' or 'No thanks...'

<img width="542" alt="Screen Shot 2022-06-06 at 1 22 04 PM" src="https://user-images.githubusercontent.com/97055189/172242200-1f4cec1e-dc04-4b97-940d-0893995453ab.png">

There are a few specific notes with this modal.

- This modal will appear on the app.shapeshift.com splash screen, where users connect their wallet. Users will not be able to connect their wallets until they have selected an option
- This message CANNOT by bypassed or dismissed in any way, except for pressing 'Continue' or 'No thanks...' - This includes escape key, clicking outside of the box, etc
- This message is shown to ALL visitors of app.shapeshift.com, unless they have pressed 'Continue' prior
- As noted above, if a user has already pressed continue, they will not see this modal again and can proceed directly into app.shapeshift.com

### References and additional details

See above

### Acceptance Criteria

- Privacy modal is shown to all users of app.shapeshift.com, unless they have pressed 'Continue' prior
- Modal cannot by bypassed in any way, other than by pressing 'Continue' or 'No thanks...'

Engineering Notes for bounty: 
- Modal does not need to be functional right now.
- Continue or no thanks clicks do nothing more than move forward to the choose wallet screen. Wiring up to user preferences will happen later.
- Because this modal exists on the splash screen it will need to exist as part of the Wallet Modal. This is a single modal that has many different views.

### Screenshots/Mockups

See above
### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

3 hrs

### Sponsor / Stakeholder

@decentralizedj in discord
@theoboldfrazier for engineering

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
ask french fam (@NeOMakinG or @chxash) to do UI component only with dummy data, and stick it in a storybook

@mrnerdhair is dealing with the pendo plugin/wiring up

**Comment by MBMaria** [comment]
GM @decentralized-j , I can get this into a bounty for you, I will just need a sponsor and the estimated number of hours to complete the task. Cheers.
