### ISSUE TITLE
display trade fee in place of shapeshift fee

### ISSUE THREAD

**Issue by elmutt** [shapeshift/web#1988]
### Overview

currently we display a useless row "0 shapeshift fee" We want to display the trade fee (will be returned as 0 for zrx and X for thorchain)

Make it clear in the tooltip that this is not a shapeshift fee

### References and additional details

currently we display a useless row "0 shapeshift fee" We want to display the trade fee (will be returned as 0 for zrx and X for thorchain)

Make it clear in the tooltip that this is not a shapeshift fee

### Acceptance Criteria

currently we display a useless row "0 shapeshift fee" We want to display the trade fee (will be returned as 0 for zrx and X for thorchain)

Make it clear in the tooltip that this is not a shapeshift fee

**Comment by 0xean** [comment]
per product - Make sure the tooltip is explicit that the transaction fee is not charged by SS.
