### ISSUE TITLE
QR Scanner Broken In Prod

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#2006]
### Overview

when scanning a QR code from app.shapeshift.com, it recognizes the QR code but doesn't populate the address that's scanned. 

It broke during the v1.28 release. That Release is linked here. https://github.com/shapeshift/web/pull/1987

Triage Thread here https://discord.com/channels/554694662431178782/984524245658894336

### References and additional details

recreation steps 

1: connect the wallet to app.shapeshift.com
2: go to an asset page and click send
3: in the address send bar, click on the QR scanner
4: Scan a valid QR Code
5: yield no address populated

### Acceptance Criteria

For the QR Scanner to function properly again.

**Comment by GMSteuart** [comment]
This looks fun :)
