### ISSUE TITLE
Fox Page: Use Boardroom API key

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#2009]
### Overview

Boardroom API currently doesn't need an API key but will need one at some point: https://docs.boardroom.info/boardroom-api/boardroom-api/api-keys.
Our requests to the Boardroom API to get Governance data will fail as soon as this is a requirement.
@SS-FOX-McCloud  has requested a Boardroom API key and as soon as we have it, we should add it as a parameter to our requests.

### References and additional details

https://github.com/shapeshift/web/blob/1ed6c6ff4a587cf5a8f5ee2ac8cb5e039ba1ad3c/src/plugins/foxPage/hooks/getGovernanceData.ts#L46-L48

### Acceptance Criteria

- The API key should be added in sample/env config
- Boardroom API requests should use the provided API key

**Comment by DiggyDiggy2** [comment]
Hello,

Thank you for your interest in using the Boardroom API.
Your Boardroom API key is: e98eb1a6fc0902539efed404048623ec

To use the api key include it as a query parameter at the end of your requests.
Example: https://api.boardroom.info/v1/protocols?limit=10&key=your-api-key

If you have any questions you can reach out on discord in our support channel https://discord.com/invite/CEZ8WfuK8s

- The Boardroom Team

**Comment by 0xdef1cafe** [comment]
this has become a wart - we're talking about moving away from boardroom anyway, and the fox page is functioning fine without this
