### ISSUE TITLE
Yearn Vault deposit modal not progressing from Confirm to Status for ERC-20 stakes.

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2012]
### Overview

When depositing into an ERC-20 yearn vault, on the third step of 'Confirm', the modal stays on "Transaction Pending". There is no circling around the arrow between the asset that is getting staked and the wrapped asset. Once the transaction approves, it stays on the Confirm step and doesn't transition to Status.

Noticed from today after release 1.29.0. 
Original release branch: https://github.com/shapeshift/web/pull/2001
The last PR merged was https://github.com/shapeshift/web/pull/2007 to fix a revert of the commit https://github.com/shapeshift/web/commit/09642953f6363266af21c802dbaa2d430c277b8f

### References and additional details

1) Log into app.shapeshift.com and connect to any wallet.
2) Select the defi page and choose one of ERC-20 asset to stake.
3) Deposit amount, approve and broadcast the transaction.
4) Note that the modal stays on the Confirm page even after the TX is confirmed on the block chain. It doesnt progress to Status and the remains saying 'Transaction Pending'

![image](https://user-images.githubusercontent.com/100157997/172979108-66e80587-1d13-4f17-afb9-a9c1dc41f067.png)
![image](https://user-images.githubusercontent.com/100157997/172979168-ac1d27f9-6817-4e81-86ba-b6deb97c22fb.png)

### Acceptance Criteria

Once the stake transaction has been confirmed on the block chain, the modal should update to 'Status' and you should then be able to "View Position". 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
probably related to the websocket issues. @shapeshift/operations can you confirm this is reproducible?

**Comment by MBMaria** [comment]
Can confirm this is still reproducible

**Comment by Neverwas-dev** [comment]
I can confirm as well this is still live in production
