### ISSUE TITLE
Performance: Reduce network calls

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#2028]
### Overview

Currently in the Fox Page, we are making a lot of Infura calls that could be avoiding by having a shared state/singletons instead of hooks, which create a new component-level context every-time they are consumed by a different component.

We should refactor the Fox Page, and the overall app code not to overfetch from Infura.

https://github.com/shapeshift/web/pull/2018 was a first naive go at it to stop the bleed, but more PRs should follow tackling the different components/hooks that consume external APIs.

### References and additional details

These two domains have been spiked to make too many requests
- [`src/plugins/foxPage/hooks`](https://github.com/shapeshift/web/tree/develop/src/plugins/foxPage/hooks)
- [`src/pages/Defi/hooks/useFoxyBalances.tsx`](https://github.com/shapeshift/web/blob/develop/src/pages/Defi/hooks/useFoxyBalances.tsx)

It also seems like the API/consumption of the different investor packages could be improved not to overfetch when consumed.

### Acceptance Criteria

- When opening the Network tab from the browser DevTools, the number of external calls, in particular to Infura, should be reduced

### Estimated effort

3 days

**Comment by 0xdef1cafe** [comment]
@gomesalexandre can this be considered closed? @0xean how are we looking in terms of requests/month for infura now?

**Comment by 0xean** [comment]
Things are stable and we are well within a reasonable plan for the time being.
![Screen Shot 2022-08-03 at 2 23 41 PM](https://user-images.githubusercontent.com/15096737/182704321-66400849-a3a5-421f-b8f1-79808799a28c.png)

**Comment by 0xean** [comment]
I would recommend we close this for now.
