### ISSUE TITLE
select correct utxo account when swapping from utxo asset

### ISSUE THREAD

**Issue by elmutt** [shapeshift/web#2040]
### Overview

When swapping from bitcoin we need a modal to popup for them to choose which account to trade from

### References and additional details

When swapping from bitcoin we need a modal to popup for them to choose which account to trade from

### Acceptance Criteria

When swapping from bitcoin we need a modal to popup for them to choose which account to trade from

**Comment by DiggyDiggy2** [comment]
Does this still product @elmutt?

**Comment by 0xdef1cafe** [comment]
@DiggyDiggy2 yeah - this is still valid. the trade widget/UI only understands assets, not accounts. when a user picks BTC as an asset to swap - there's 3 different addresses we could possible generate, and we'd need UI to select which.

**Comment by reallybeard** [comment]
![Image](https://user-images.githubusercontent.com/89934888/178803766-b13d4ee2-06fd-4627-ba53-028a21319167.png)

Expected behavior: User goes to the bitcoin asset page, we default to whatever account has the highest balance. They will see the account below the asset amount input field. 

When they click on the account row, they are taken to the select account screen.

**Comment by elmutt** [comment]
@reallybeard they will also need to select which account to receive their bitcoin in if bitcoin is the buy asset.

Should it be the same thing for buy asset just like this?

**Comment by reallybeard** [comment]
> @reallybeard they will also need to select which account to receive their bitcoin in if bitcoin is the buy asset.
> 
> Should it be the same thing for buy asset just like this?

Yah, should just get appended to whatever field requires an account to be selected.

**Comment by 0xdef1cafe** [comment]
very closely related to https://github.com/shapeshift/web/issues/2168
