### ISSUE TITLE
Gas warning in trade modal not translating after selecting a different language

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2054]
### Overview

When doing a trade in a different language, the gas warning "Gas fee exceeds XX% of trade amount" does not translate and remains in English

### References and additional details

1) Log into app.shapeshift.com and connect to any wallet
2) Enter details to do a trade in the trade modal
3) In the settings option select a different language.
4) Proceed to Preview Trade and notice the gas warning remaining in English.

![image](https://user-images.githubusercontent.com/100157997/174161962-bf9e348b-a7ef-48c0-bce9-38d9ce31e395.png)

Another non translate:
The date in the historical transactions page remains in English. 
![image](https://user-images.githubusercontent.com/100157997/175404580-9d3a1aba-35d9-4473-9bfc-2291e6989cf2.png)

This particular language does not translate "Transaction History". 
It also doesn't translate the Buy/Sell crypto button. 
Or the "price change" on the dashboard
![image](https://user-images.githubusercontent.com/100157997/175404812-75857abd-d1c5-4948-9f1f-8bd3914cb4f4.png)

![image](https://user-images.githubusercontent.com/100157997/175404878-afbbe546-c899-4afc-8481-2bb80c79f4a2.png)

![image](https://user-images.githubusercontent.com/100157997/175405577-966a1edc-f833-4660-b978-50feeb94a7d8.png)

The asset description ("About XXX") on each asset does not translate. 
![image](https://user-images.githubusercontent.com/100157997/175405174-a01ad339-f05f-4d81-9fee-ca1f0006f0e7.png)

### Acceptance Criteria

All text should translate to the language selected

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by wesleygravess** [comment]
<img width="503" alt="Screenshot 2022-06-16 163441" src="https://user-images.githubusercontent.com/99363597/174162786-8a2bf3fb-4957-4b9a-84b0-400105cfdb00.png">

same issues occurring on the banax off ram text

**Comment by gomesalexandre** [comment]
- "Gas exceeds" translation has been added in https://github.com/shapeshift/web/pull/2076 and is now shown:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/17035424/176201191-1fdbca0b-ef29-46fb-ae51-34547d8c3183.png">

**Comment by gomesalexandre** [comment]
- Transaction history date is still shown in English date format/language and needs to be translated. The component that handles this is `<TransactionDate />`:
https://github.com/shapeshift/web/blob/8a3754fca0b5db5f5a230a9e1809d008ed824a8f/src/components/TransactionHistoryRows/TransactionDate.tsx#L13
This one is obviously going to be a slightly different logic than our usual translations logic since we're dealing with date formats. The dayjs `.locale()` chained method can be used to achieve this, however, note that locales need to be explicitly loaded, as dayjs only comes with English by default.
The naive implementation would be to use `locale(selectedLocale).format('MMMM DD, YYYY')`, however, different languages have different date formats. The following diff will make it work across different locale formats:

```diff
﻿﻿diff --git a/src/components/TransactionHistoryRows/TransactionDate.tsx b/src/components/TransactionHistoryRows/TransactionDate.tsx
index 56cfaf85..d6f9d91d 100644
--- a/src/components/TransactionHistoryRows/TransactionDate.tsx
+++ b/src/components/TransactionHistoryRows/TransactionDate.tsx
@@ -10,6 +10,13 @@ export const TransactionDate = ({ blockTime }: { blockTime: number }) => (
     whiteSpace='nowrap'
     px={4}
   >
-    {dayjs(blockTime * 1000).format('MMMM DD, YYYY')}
+    {(() => {
+      require('dayjs/locale/fr') // change this to a template literal string to explicitly require a specific locale
+      const localizedFormat = require('dayjs/plugin/localizedFormat')
+      dayjs.extend(localizedFormat)
+      return dayjs(blockTime * 1000)
+        .locale('fr') // change this to locale from user settings selector
+        .format('ll')
+    })()}
   </RawText>
 )
```

<img width="123" alt="image" src="https://user-images.githubusercontent.com/17035424/176204967-ed0aa102-bf81-42fd-8f55-f75cfe3721e7.png">

**Comment by gomesalexandre** [comment]
> The asset description ("About XXX") on each asset does not translate.

This will be handled by https://github.com/shapeshift/lib/issues/836. Currently, we do not have the capability to use localized Coingecko descriptions nor to provide overrode localized ones.

**Comment by gomesalexandre** [comment]
> <img alt="Screenshot 2022-06-16 163441" width="503" src="https://user-images.githubusercontent.com/99363597/174162786-8a2bf3fb-4957-4b9a-84b0-400105cfdb00.png">
> 
> same issues occurring on the banax off ram text

- For Indonesian and Chinese, `fiatRamps.banxaMessage` is missing, and the existing `fiatRamps.gemMessage` translation can be leveraged, replacing `Gem` with `Banxa`.
- For Russian, the translations are missing altogether for Banxa and Gem and "Купить или продать на Banxa" / "Купить или продать на Gem" should be added

**Comment by gomesalexandre** [comment]
Agreed to assign @NeOMakinG to it as community contributor - this doesn't need to be bountied out on Dework

**Comment by MBMaria** [comment]
@NeOMakinG if i find other little things that aren't translating, do you want me to post here or make a new ticket?
eg: 
![image](https://user-images.githubusercontent.com/100157997/179128839-d948f51e-bdff-4aa7-afc9-2f06cf46699a.png)
![image](https://user-images.githubusercontent.com/100157997/179128924-1841836f-54fd-4fe8-b46a-14d0ba4a45ab.png)
![image](https://user-images.githubusercontent.com/100157997/179129225-2f4c2089-405c-4db0-aecd-fc9826da46fb.png)
and
![image](https://user-images.githubusercontent.com/100157997/179128880-6d2b74e6-06a6-45de-91fc-1dceadeec7fb.png)
![image](https://user-images.githubusercontent.com/100157997/179128970-76de547d-baa5-4697-b19b-f935eed50edc.png)
and
![image](https://user-images.githubusercontent.com/100157997/179129034-314774f9-e312-4172-b186-09434dcc638f.png)
![image](https://user-images.githubusercontent.com/100157997/179129113-8b8e79df-1f02-4faf-ae27-dba4b5d0c8db.png)
![image](https://user-images.githubusercontent.com/100157997/179129178-ea52d375-014e-40b1-a983-7081b9e7914c.png)
![image](https://user-images.githubusercontent.com/100157997/179129353-5ff96c99-d855-416d-9598-b1f540e0d25a.png)

**Comment by NeOMakinG** [comment]
> @NeOMakinG if i find other little things that aren't translating, do you want me to post here or make a new ticket? eg: ![image](https://user-images.githubusercontent.com/100157997/179128839-d948f51e-bdff-4aa7-afc9-2f06cf46699a.png) ![image](https://user-images.githubusercontent.com/100157997/179128924-1841836f-54fd-4fe8-b46a-14d0ba4a45ab.png) ![image](https://user-images.githubusercontent.com/100157997/179129225-2f4c2089-405c-4db0-aecd-fc9826da46fb.png) and ![image](https://user-images.githubusercontent.com/100157997/179128880-6d2b74e6-06a6-45de-91fc-1dceadeec7fb.png) ![image](https://user-images.githubusercontent.com/100157997/179128970-76de547d-baa5-4697-b19b-f935eed50edc.png) and ![image](https://user-images.githubusercontent.com/100157997/179129034-314774f9-e312-4172-b186-09434dcc638f.png) ![image](https://user-images.githubusercontent.com/100157997/179129113-8b8e79df-1f02-4faf-ae27-dba4b5d0c8db.png) ![image](https://user-images.githubusercontent.com/100157997/179129178-ea52d375-014e-40b1-a983-7081b9e7914c.png) ![image](https://user-images.githubusercontent.com/100157997/179129353-5ff96c99-d855-416d-9598-b1f540e0d25a.png)

@MBMaria I think it's worth creating a new ticket, maybe we should think about inspecting everywhere, creating a big ticket and improving everything at the same time so we ditch the most :)
