### ISSUE TITLE
uncaught error if swapper.buildTrade fails

### ISSUE THREAD

**Issue by elmutt** [shapeshift/web#2057]
### Overview

uncaught error if swapper.buildTrade fails

### References and additional details

uncaught error if swapper.buildTrade fails

### Acceptance Criteria

uncaught error if swapper.buildTrade fails

**Comment by 0xdef1cafe** [comment]
@elmutt is this still valid?

**Comment by 0xdef1cafe** [comment]
closing, ops can reopen once swapper UI changes are made and this is still valid
