### ISSUE TITLE
[Feature Request] Sending modals confirm button update

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#2068]
### Overview

Recommended by Product and Willy

Currently, users sending a TX with anything besides native are given multiple types of messages after clicking confirm. 
![ConfirmonKK](https://user-images.githubusercontent.com/94189400/174893617-7bcdfa89-f17c-4cf7-8283-6ca55416f645.jpg)
After pressing Confirm when sending a TX, you are given a message that says "Broadcasting Transaction" with a spinner. A user with KK would have no idea what to do next (accepting by pressing the button on their keepkey). If a users metamask didn't open up, some new users might not know what to do next.

The suggested fix is that all sending buttons (defi, sending, trading, atom modals) after pressing confirm the button should be pulling data on what wallet the users is using and say "Confirm on [Wallet]" inside the button before moving to the next page. 
![TradeconfirmKK](https://user-images.githubusercontent.com/94189400/174899183-7f1e136f-cc22-45e1-91ea-e8a38d847d3c.jpg)
![DeFiconfirmKK](https://user-images.githubusercontent.com/94189400/174899233-d243b00b-0bb5-4f7a-9c5d-a6214027f7f1.jpg)

### References and additional details

https://discord.com/channels/554694662431178782/988892734133768192/988892737929617488

### Acceptance Criteria

When a user confirms a tx in app.shapeshift.com, if a confirmation on the wallet is required (every wallet besides native) display a pending state in the CTA "Confirm on [wallet]" (ie. "Confirm on KeepKey) until they have confirmed the transaction

**Comment by gomesalexandre** [comment]
Wallet info can be pulled for the current connected wallet by using `useWallet().wallet` / `useWallet().walletInfo`.
Each hdwallet has an helper to keep the checks declarative:
- `isNative`
- `isMetaMask`

From a functional perspective, this means that `<Confirm />` and `<ClaimStatus />` component will need to handle one additional step of showing a confirm state (if not on native), until the confirm actually happened.

**Comment by 0xdef1cafe** [comment]
closing as stale/low priority
