### ISSUE TITLE
webpack broken with nodejs 17: digital envelope routines::unsupported

### ISSUE THREAD

**Issue by jdambron** [shapeshift/web#207]
If upgrading to nodejs 17, the application fails with the following error

`Error: error:0308010C:digital envelope routines::unsupported`

The issue seems to be related to webpack (see https://github.com/webpack/webpack/issues/14532) and is flagged as critical on their side but not yet fixed.

While waiting for a patch, be careful to stay on nodejs version 16.

**Comment by technojak** [comment]
Odd Nodejs version numbers are canary/unstable versions as Nodejs prepare for the next release. We shouldn't ever use it for applications. Package developers should use it to prepare for future releases that wont work on previous versions.

Some info: https://stackoverflow.com/questions/14790017/how-does-node-js-version-numbers-work-and-how-do-i-ensure-compatibility#:~:text=Node%20has%20a%20two%2Dtrack,1%20and%200.8.

**Comment by jdambron** [comment]
@0xdef1cafe done ✅
