### ISSUE TITLE
handle deeplinks without breaking demo wallet

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#2073]
### Overview

When a user visits a url without a wallet connected they are taken to the splash page (connect wallet) once they are connected it redirects them to the dashboard. 

We would like to change this functionality so that if a user goes to `app.shapeshift.com/#/defi`

Once they have connected their wallet it returns them back to that page.

We have this functionality built already, but it seems like its hardcoded to `/dashboard`

### References and additional details

Checkout `PrivateRoute.tsx` inside Routes. This seems to be setup to do this, but not currently functioning.

### Acceptance Criteria

Bring back user to original URL, after connecting wallet on the splash page.

### Need By Date

n/a

### Screenshots/Mockups

n/a

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
Once we have a sponsor for this and the estimated hours I can create a bounty in Dework . Please add the "needs bounty" tag once the info has been provided. Thankyou

**Comment by gomesalexandre** [comment]
@reallybeard This is already implemented, and from testing it out, it seems to be working.
I can't reproduce the redirect to Dashboard. Tried with MM/Native/Demo wallets. Also tried to go from Demo wallet to actual connected wallet with the same result, private routes are working for me and I always get redirected to the right `returnUrl`.

**Comment by 0xdef1cafe** [comment]
`https://app.shapeshift.com/#/demo/assets/bip122:000000000019d6689c085ae165831e93/slip44:0`

note the `/#/demo/` prefixing the rest of the URL handles this automatically
