### ISSUE TITLE
Asset list shows Avalanche assets over eth mainnet assets

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#2101]
### Overview

Currently, with the avalanche flag on, the sorted asset list is showing avalanche assets, e.g. `USDC on Avalanche` as one of the top assets.

From a user's perspective it feels more natural that the eth mainnet version would be displayed.

### References and additional details

This is likely occuring as we use the coingecko market data for avalanche assets which is showing the market cap of USDC on eth mainnet for the avalanche version.

### Acceptance Criteria

May need some product input, but at a minimum IMO it would be nice to at least display both variants - e.g. `USDC` and `USDC on Avalanche`

### Screenshots/Mockups

<img width="928" alt="image" src="https://user-images.githubusercontent.com/88504456/176762933-429835e4-7c92-4076-8ed8-355c4cace6d0.png">

**Comment by DiggyDiggy2** [comment]
We're thinking it would sort by: show the assets a user has a balance of at the top, and then display by market cap (so that USDC for example would show both the ETH and AVAX version together). In the future we'd like to have a filter by chain option, but for now, just want to unblock this.
