### ISSUE TITLE
Multiple USDC assets showing up in asset search

### ISSUE THREAD

**Issue by chxash** [shapeshift/web#2131]
### Overview

When searching for "USDC" in asset search (trade component for example), 2 other flavors of USDC show up first (USDC wormhole token), see screenshot attached.
The real `USDC` should be displayed first to not confuse the user.
And maybe the 2 other tokens should not be called simply `USDC` but something like `USDC (Wormhole)`.

![usdc](https://user-images.githubusercontent.com/5720927/177994088-11cbb1b1-388c-469d-b7a4-39d91f9093e9.png)

### References and additional details

Link to the 2 others tokens on etherscan : 
https://etherscan.io/token/0x7cd167b101d2808cfd2c45d17b2e7ea9f46b74b6
https://etherscan.io/token/0x566957ef80f9fd5526cd2bef8be67035c0b81130

### Acceptance Criteria

At least the real USDC should show up first in the list.
Ideally the assets should have different displayed name.

### Estimated effort

4 hours

**Comment by gomesalexandre** [comment]
Related to https://github.com/shapeshift/web/issues/2101 - same domain, we should tackle these in sequence to make sure we have a maintainable logic that works with both.

Agreed about the tagging part, at the very least we should be able to override these assets.

We already have some asset labeling logic for the specific of `X on Y chain` e.g:
- X on Avalanche: https://github.com/shapeshift/lib/commit/ee13ac8ab46c2bfa07d30be1dceeac13b13cb3b0#diff-b7ef478822cbb04bdaa2867afc02f32c57fdd32f520da5979da8acf5ac5e73aaR45
- X on Osmosis: https://github.com/shapeshift/lib/commit/947e654fb7cbce1f1c2635295737571042357509#diff-092ab88ac8582f8a698f1f1c3c49a8d78ff853a3daa7668fa2813a299569eebbR57

We could iterate on this logic and arbitrarily override asset names, in a similar fashion as how we override descriptions
