### ISSUE TITLE
Add a FOX Farming modal with the new staking UI

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#2143]
### Overview

Fox Farming should be added in a similar fashion as the other DeFi opportunities with the new staking UI (https://github.com/shapeshift/web/pull/2116)

Additionally, a copy should be added for this specific modal:

```
ShapeShift is awarding 6,750,000 FOX until November 30, 2022 to liquidity providers that stake their LP tokens. This is an estimated APR calculated based on the current amount of FOX-ETH-UNIV2 LP tokens staked in the ShapeShift rewards contract. This APR amount is subject to extreme volatility and this amount could drop significantly.
```

### References and additional details

https://www.notion.so/shapeshift/Fox-Farm-LP-Staking-3042a295f4174cdb874d80b5dfb8f002
https://www.figma.com/file/OHbVrAVaV2xQWUsq0nKzGm/ShapeShift-Library?node-id=156%3A3155

### Acceptance Criteria

- Fox Farming works with a similar flow as the other standardized DeFi modals
- The aforementioned copy is added to the FOX Farming modal

### Screenshots/Mockups

![image](https://user-images.githubusercontent.com/17035424/178343698-2193698c-98cf-48c1-9d52-564c98854df9.png)
![image](https://user-images.githubusercontent.com/17035424/178343719-491fb07b-a5b9-4716-9599-097f2d633ce7.png)

**Comment by decentralized-j** [comment]
Synced and closing this to nest under FOX Farming milestone. Ty @gomesalexandre !
