### ISSUE TITLE
app.shapeshift.com is requesting an eth addresses while building the portfolio when first connecting a KeepKey

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#2150]
### Overview

It looks like the app is requesting an eth addresses while building the portfolio, but asking for a confirmation when it should not ask for confirmation. This action is not prompted on screen and blocks balances from showing on the dashboard until the user confirms their ETH address on their device with a button press. 

Issue was first introduced in: https://github.com/shapeshift/web/pull/2107

### References and additional details

Issue reported and recreated here: https://discord.com/channels/554694662431178782/873244924026449940/995015113721516113

### Acceptance Criteria

Connecting the KeepKey to app.shapeshift.com through the normal wallet pair flow without having an ETH address confirmation stop a user from getting to the dashboard. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
Addressed in https://github.com/shapeshift/web/issues/2103

**Comment by purelycrickets** [comment]
Fat fingered wrong issue. This is still an unresolved issue.

**Comment by 0xdef1cafe** [comment]
just needs chain-adapters version bump https://github.com/shapeshift/lib/pull/877

**Comment by brymut** [comment]
Hi @0xdef1cafe , may I please find out why I was unassigned from this on dework? I was still familiarizing myself before it was completed.
