### ISSUE TITLE
Trade modal : display trading fees as cryptoAmount if available

### ISSUE THREAD

**Issue by chxash** [shapeshift/web#2163]
### Overview

Currently we are displaying trading fees only by their fiat values (eg `$3.30`). See screenshot

For CowSwap for example, the trading fees are taken by the platform as a portion of the sold token during a swap.

We want to be able to display this trading fee as a cryptoAmount (eg 50 FOX ≈ $3.30)

Changes are required in lib and web to do this.

### References and additional details

Current implementation 

![178714670-90aa15dd-4ac5-4bc1-bddc-44f274cc85ca](https://user-images.githubusercontent.com/5720927/178936543-f113053c-1e69-45f6-b84a-db2bcc64ef30.png)

### Acceptance Criteria

Trading fee should be displayed as cryptoAmount ≈ fiat value when possible
No regression for swappers not concerned by this change

### Estimated effort

2 hours

**Comment by decentralized-j** [comment]
Gm @chxash ser!

After much discussion on handling Cowswap fees, we're going to go with the implementation outlined in #2265. It doesn't show crypto values but provides the user with a much more detailed breakdown of fees. Let me know if this makes sense and we can close this ticket!
