### ISSUE TITLE
Show order routing protocol in confirm trade modal

### ISSUE THREAD

**Issue by decentralized-j** [shapeshift/web#2174]
### Overview

Gm! We want to display which order routing protocol is being used in the trade modal, on the confirm trade screen.

Please see below for a screenshot of the current view.
![Screen_Shot_2022-07-15_at_9 25 20_AM](https://user-images.githubusercontent.com/97055189/179308482-770da517-939c-4608-93cc-38480dd7be47.png)

Below is a mock of the desired look for the routing information, displayed below the rate.
![Screen_Shot_2022-07-15_at_3 52 51_PM](https://user-images.githubusercontent.com/97055189/179309193-4cb94991-8097-4ec3-806d-021358f75edd.png)

Please direct any questions to me, @decentralizedj on discord.

### References and additional details

See above.

### Acceptance Criteria

Order router is displayed on trade confirm modal in manner shown above.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
We are already using the human-readable `swapper.name`, newly added by @DaoDev44 in https://github.com/shapeshift/lib/pull/867, to display `0x Fee`.
There are no ramifications to this, this will just be about a few JSX modifications to display this variable under the rate vs. `<swapperName> fee` currently

**Comment by MBMaria** [comment]
GM @decentralized-j , do you have an estimated hours for this bounty so i can put a value on it in dework? Cheers.

**Comment by gomesalexandre** [comment]
> GM @decentralized-j , do you have an estimated hours for this bounty so i can put a value on it in dework? Cheers.

We can estimate is as 1 hour @MBMaria

**Comment by SankhaChak** [comment]
GM! Would love to take this up if no one else is working on it.
