### ISSUE TITLE
[Product Suggestion] Error Receiving Trading Quote Toast Update 

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#2179]
### Overview

Currently, users when they attempt a swap to a pair that has no pool listed through 0x they get a toast that says " Something went wrong.  An error occurred getting trade rates."
<img width="429" alt="SomethingWentWrong" src="https://user-images.githubusercontent.com/94189400/179571781-5317d9b1-6474-49fd-8459-1678ddfdef5c.png">

The product team would like this toast to be changed to "We're not able to get a quote for this pair"

### References and additional details

https://discord.com/channels/554694662431178782/998617873587114115/998642803368276039

### Acceptance Criteria

Error " Something went wrong.  An error occurred getting trade rates." when there are no rates available should now read  "We're not able to get a quote for this pair"

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by DiggyDiggy2** [comment]
Just a copy change @gomesalexandre thanks!

**Comment by 0xdef1cafe** [comment]
@gomesalexandre @0xApotheosis plz close if already addressed
