### ISSUE TITLE
Remove winston patch-package

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/web#218]
A temporary fix to unblock web and allow including `unchained-client` for websocket support was adding a patch to the winston/colors package which wasn't playing nicely with webpack: https://github.com/shapeshift/web/blob/e0936a72e432f20441be2ed888ba30bffa0bebd2/patches/winston%2B%2Bcolors%2B1.0.3.patch.

While this does work and allow building and running without warnings or errors from webpack, it is not an ideal long term solution. The version of winston is brought in by the unchained logger and the amqp-ts package. Due to the monorepo nature of unchained and referencing types across packages, the easiest way to get a working `unchained-client` package was to just publish all packages in the monorepo so the `@shapeshiftoss` scope package imports worked both internally via yarn workspace symlinks and externally when imported as a public 3rd party package.

There should be some thought into how we might be able to structure the type exports better in unchained to avoid bringing in the whole monorepo (since we only really care about the types) and also will want to upgrade the logger package to use a more recent version of winston for a more long term fix.

**Comment by 0xean** [comment]
@kaladinlight - can you confirm this is completed?

**Comment by kaladinlight** [comment]
@0xean completed and merged pr linked
