### ISSUE TITLE
Choose a wallet dead click after clicking the back arrow 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2214]
### Overview

On the connect a wallet window, click on a wallet, click the back arrow on the top left, and click on the same wallet again, notice the dead click. 

### References and additional details

1. go to app.shapeshift.com
2. click on connect a wallet 
3. choose a wallet
4. click on the back arrow in the top left portion of the modal
5. click on the same wallet again
6. notice the dead click 

### Acceptance Criteria

After choosing a wallet and clicking the back arrow button, you should be able to click on the same wallet again and proceed with pairing you wallet to the app.shapeshift platform.

### Screenshots/Mockups

https://user-images.githubusercontent.com/99363597/180487348-1e9cfe94-b567-47d7-ab79-d70626862fed.mp4

**Comment by gomesalexandre** [comment]
@wesleygravess That's a bug, from looking at the commit history this was originally fixed in https://github.com/shapeshift/web/commit/32aca3c4a754a62f44afce242d2c09adf2b0d4fd#diff-6235ac98557ec42d729e981a26194b5ea4cdf9907d27649ca94b5b85c94d632dR34-R35
