### ISSUE TITLE
Display approving contract name at swap confirm step

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#2240]
### Overview

Currently as a user, when making a swap and not having allowance for that trade to go through, I'm prompted with a confirm step:

![image](https://user-images.githubusercontent.com/17035424/181080714-d2956380-fc0d-4d3c-a2ce-34319e9b7632.png)

It then opens a wallet prompt to accept an `approve()` Tx. However, there is no information on the contract that's being approved

We should add a new row under the estimated gas fees (**location of the row to be confirmed by product**) to inform the user about the contract that they're approving. We already have this data as `tradeFeeSource`, see references

### References and additional details

- Mock `DisplayFeeData` where the `tradeFeeSource` can be seen:

https://github.com/shapeshift/web/blob/9a7c5095caf25fa2cdb4ef46a30013a42e98566e/src/test/constants.ts#L104

- `<Approval />` component where the `tradeFeeSource` can be gotten from `fees.tradeFeeSource`:

https://github.com/shapeshift/web/blob/222fb5c40ec01e7687254ffdf31e40476efbf8a6/src/components/Approval/Approval.tsx#L51

### Acceptance Criteria

- As a user, I'm able to see the contract that I'm going to approve when clicking "Approve" (0x, Thor, CowSwap, Osmosis)

### Estimated effort

1 hour

**Comment by decentralized-j** [comment]
This is also a great idea ser - Will circle on this tomorrow for UX placement. As a user, you'd want to see a link to the exact contract instead of just saying 'interact with 0x' or something along those lines yeah?

**Comment by gomesalexandre** [comment]
> This is also a great idea ser - Will circle on this tomorrow for UX placement. As a user, you'd want to see a link to the exact contract instead of just saying 'interact with 0x' or something along those lines yeah?

I think having the name instead of the contract, e.g 0x, CowSwap, is a nice abstraction, and follows our vision of abstracting the complexity away by providing the most user-friendly info.
I do believe that we could still show the contract for the most cautious users that want to double check it before the wallet popup, possibly as an explorer link to that contract on said name?

**Comment by reallybeard** [comment]
If we have the source name, can we hyperlink that to the contract? I think I mocked this up at one time.

Allow [0x](http://google.com) to use your USDC?

**Comment by decentralized-j** [comment]
Simple hyperlink sounds good to me - minimal lift but very effective. @reallybeard do you have a mock of this? this should be a very quick bounty

**Comment by decentralized-j** [comment]
closing this in favor of #2268!
