### ISSUE TITLE
Remove "Coinbase pay coming soon" from on/off ramp modal

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#2241]
### Overview

Coinbase has no plans as of now to offer affiliate revs for using their new on-ramp widget. Considering many other providers and potential partners are offering rev share agreements, we have decided not to prioritize the Coinbase on ramp at this time.

### References and additional details

none

### Acceptance Criteria

The "Coming soon" Coinbase pay callout should no longer appear in the fiat on/off ramp modal.

### Screenshots/Mockups

![Screen Shot 2022-07-26 at 12 29 56 PM](https://user-images.githubusercontent.com/90058616/181084337-5c706978-3555-43c5-889f-e46f84ff1dae.png)

### Estimated effort

1 hour

**Comment by gomesalexandre** [comment]
CoinbasePay is defined in the `supportedFiatRamps` here:

https://github.com/shapeshift/web/blob/952632a45b8bce6c14803c630773198b0ac1dc2d/src/components/Modals/FiatRamps/config.ts#L100

As well as in the `FiatRamp` type: https://github.com/shapeshift/web/blob/952632a45b8bce6c14803c630773198b0ac1dc2d/src/components/Modals/FiatRamps/config.ts#L44

Given Coinbase is a specific case of us having a working implementation that we were supposed to unflag in the future and which we might want to keep, I would suggest simply commenting it out (as well as the imports it depends on and removing it from the `FiatRamp` types) for the time being, so we can keep the implementation and uncomment it if we need it in the future.

This can be done in a ☕ time
