### ISSUE TITLE
Allow users to set a non-infinite allowance for swaps

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#2242]
### Overview

Currently as a user, when making a swap and not having allowance for that trade to go through, I'm prompted with a confirm step:

![image](https://user-images.githubusercontent.com/17035424/181080714-d2956380-fc0d-4d3c-a2ce-34319e9b7632.png)

It then opens a wallet prompt to accept an `approve()` Tx. However, this is an infinite allowance, with no way to set some other amount. Since I can't see the crypto amount being swapped.

It should be possible to
- select exact and/or custom allowance (**and/or to be confirmed by product as well as the UX of this**)
- see the crypto amount being swapped to be able to use this displayed number to set up a custom allowance without rejecting the approval and going back to the swap input (**to be confirmed by product**)

### References and additional details

- `<Approval />` component:

https://github.com/shapeshift/web/blob/222fb5c40ec01e7687254ffdf31e40476efbf8a6/src/components/Approval/Approval.tsx

### Acceptance Criteria

- It is possible to set an exact/custom allowance amount that will be used to build the Tx
- The swapped amount (in crypto/fiat) is displayed

**Comment by decentralized-j** [comment]
This is a great suggestion ser, we'll huddle on the product side to come up with UX to reflect this. I like how Connext has integrated this on their initial swap step. Is there any additional functionality you had in mind beyond this?


![Image](https://user-images.githubusercontent.com/97055189/181388444-dc3909f9-fa1c-4461-8225-bd4d67f56202.png)
![Image](https://user-images.githubusercontent.com/97055189/181388443-4519912c-24c2-4946-9f20-2da8614a9b91.png)

**Comment by gomesalexandre** [comment]
> I like how Connext has integrated this on their initial swap step. Is there any additional functionality you had in mind beyond this? User can toggle exact or infinite approval

That's precisely what I had in mind! As a checkbox, but if we think a different toggle UI would look and feel better, we could go for that as well. I don't think we really use toggles across the app except in settings.

**Comment by reallybeard** [comment]
![Screen Shot 2022-07-28 at 10 11 03 AM](https://user-images.githubusercontent.com/89934888/181573288-8153941d-e89e-45a2-8d9f-06d451d3fb1a.png)

**Comment by gomesalexandre** [comment]
> Love this mock beard ser! @gomesalexandre is this feasible from a technical perspective? If so, I'll create a ticket and get it rolling

Definitely @decentralized-j! From a presentational standpoint, it will be trivial.
From a technical perspective, we mostly need to make our lib packages able to handle non-infinite allowances, see below.

For Yearn DeFi modal:

- Make `investor-yearn` accept an optional allowance parameter in [`prepareApprove`](https://github.com/shapeshift/lib/blob/f44bc8fe4a50951207632fdad4106b645d91686d/packages/investor-yearn/src/YearnOpportunity.ts#L287) instead of always using the `MAX_ALLOWANCE` it uses currently
- Add the allowance to form state and consume it with this new parameter in YearnManager's `<Approve />` component:
https://github.com/shapeshift/web/blob/234e5f5740cef064d84f187b9e5eff8e8396f859/src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx#L103

For Foxy DeFi modal:

- Make `investor-foxy` accept an optional allowance option in the `ApproveInput` input of [`approve`](https://github.com/shapeshift/lib/blob/2a3e81641e7fb554e21fbf469ad33c38e63f7ec5/packages/investor-foxy/src/api/api.ts#L404) instead of always using the `MAX_ALLOWANCE` it uses currently
- Add the allowance to form state and consume it with this new parameter in FoxyManager's `<Approve />` component:
https://github.com/shapeshift/web/blob/c515747e2e67764c774f3f8e593121beeeab93d2/src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx#L88

Note that for the two aforementioned DeFi opportunities, the `<Approve />` component exists both for deposit and withdraw so make sure to add it in both.

For swaps:

- Write a new swapper `approve` method similar to the existing [`approveInfinite`](https://github.com/shapeshift/lib/blob/616ea72573dd7a3a91a9233d83f8936b43ca0ed7/packages/swapper/src/swappers/zrx/ZrxSwapper.ts#L73-L75) one that will take an allowance parameter
- Add the allowance to form state and consume `approveInfinite` or `approve` programmatically here (it will need to be added to `useSwapper` as well:

https://github.com/shapeshift/web/blob/222fb5c40ec01e7687254ffdf31e40476efbf8a6/src/components/Approval/Approval.tsx#L69

**Comment by decentralized-j** [comment]
Closing this in favor of #2263 where all information has been aggregated into one spot
