### ISSUE TITLE
In trade confirm step, calculate fiat value for buy asset

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#2245]
### Overview

Currently on the trade confirm step, we display the same fiat value for the sell asset and buy asset rather than calculating the fiat values of each. This gives users the wrong impression that they are losing 0 value to slippage or fees.

![image](https://user-images.githubusercontent.com/26232238/181280207-c61a3890-cb2f-44a7-9b7d-bb5f7a468562.png)

### References and additional details

n/a

### Acceptance Criteria

Currently on the trade confirm step, we display the same fiat value for the sell asset and buy asset rather than calculating the fiat values of each. This gives users the wrong impression that they are losing 0 value to slippage or fees.

![image](https://user-images.githubusercontent.com/26232238/181280207-c61a3890-cb2f-44a7-9b7d-bb5f7a468562.png)

AC:
1. Fiat values are calculated for both the buy asset and sell asset on trade confirm
2. If no fiat value is available for either asset, display "---"

### Estimated effort

30 minutes

**Comment by elmutt** [comment]
@shapeshift/product @willyogo I added the product label and am going to pause on this until the deasigns are more solidified

**Comment by DiggyDiggy2** [comment]
@elmutt do you want us to put the scenarios/layout for all 3 - 0x, cowswap and Thorchain into this ticket?

**Comment by decentralized-j** [comment]
gm all - the talented mr. beard has provided some updated UX to handle this. The CowSwap spec has been updated to reflect this specifically but it's easier to see than explain so please see link below with updated spec info below that.

The big changes involve adding in a 'receive including fees' modal to display the amount received to the user more accurately

https://www.figma.com/proto/OHbVrAVaV2xQWUsq0nKzGm/ShapeShift-Library?node-id=162%3A869&scaling=min-zoom&page-id=134%3A613&starting-point-node-id=134%3A614

https://shapeshift.notion.site/CowSwap-Order-Routing-Selection-in-v2-abc0e99098b449be85b1230d778f4800

**Comment by 0xdef1cafe** [comment]
@chxash FYI closing in favor of https://github.com/shapeshift/web/issues/2265
