### ISSUE TITLE
Add toggle for exact or infinite approvals for swaps on all trades

### ISSUE THREAD

**Issue by decentralized-j** [shapeshift/web#2263]
### Overview

This ticket designed to close #2242

Currently as a user, when making a swap and not having allowance for that trade to go through, you're prompted with a confirm step

![181080714-d2956380-fc0d-4d3c-a2ce-34319e9b7632](https://user-images.githubusercontent.com/97055189/181600219-051f4735-4e0a-43c0-b447-fe5ca34f9bb0.png)

It then opens a wallet prompt to accept an approve() Tx. However, this is an infinite allowance, with no way to set some other amount

It should be possible to
- select exact approval allowance or unlimited allowance

We have a mockup below of a simple toggle switch for doing this
![181573288-8153941d-e89e-45a2-8d9f-06d451d3fb1a](https://user-images.githubusercontent.com/97055189/181600462-1084a2e5-006e-4dcb-8429-b9a4e1ea1ca8.png)

If toggle is set to 'exact' then the exact amount of asset being swapped is passed into the approval. Metamask and other wallets handle this quite well and show it to the user. Example of this below.
![Screen Shot 2022-07-28 at 12 24 15 PM](https://user-images.githubusercontent.com/97055189/181600602-00513088-0bbe-4a8f-a52f-6c6801bcac73.png)

### References and additional details

Technical implementation details from mr @gomesalexandre 

> From a technical perspective, we mostly need to make our lib packages able to handle non-infinite allowances, see below.
> 
> For Yearn DeFi modal:
> 
> * Make `investor-yearn` accept an optional allowance parameter in [`prepareApprove`](https://github.com/shapeshift/lib/blob/f44bc8fe4a50951207632fdad4106b645d91686d/packages/investor-yearn/src/YearnOpportunity.ts#L287) instead of always using the `MAX_ALLOWANCE` it uses currently
> * Add the allowance to form state and consume it with this new parameter in YearnManager's `<Approve />` component:
>   https://github.com/shapeshift/web/blob/234e5f5740cef064d84f187b9e5eff8e8396f859/src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx#L103
> 
> For Foxy DeFi modal:
> 
> * Make `investor-foxy` accept an optional allowance option in the `ApproveInput` input of [`approve`](https://github.com/shapeshift/lib/blob/2a3e81641e7fb554e21fbf469ad33c38e63f7ec5/packages/investor-foxy/src/api/api.ts#L404) instead of always using the `MAX_ALLOWANCE` it uses currently
> * Add the allowance to form state and consume it with this new parameter in FoxyManager's `<Approve />` component:
>   https://github.com/shapeshift/web/blob/c515747e2e67764c774f3f8e593121beeeab93d2/src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx#L88
> 
> Note that for the two aforementioned DeFi opportunities, the `<Approve />` component exists both for deposit and withdraw so make sure to add it in both.
> 
> For swaps:
> 
> * Write a new swapper `approve` method similar to the existing [`approveInfinite`](https://github.com/shapeshift/lib/blob/616ea72573dd7a3a91a9233d83f8936b43ca0ed7/packages/swapper/src/swappers/zrx/ZrxSwapper.ts#L73-L75) one that will take an allowance parameter
> * Add the allowance to form state and consume `approveInfinite` or `approve` programmatically here (it will need to be added to `useSwapper` as well:
> 
> https://github.com/shapeshift/web/blob/222fb5c40ec01e7687254ffdf31e40476efbf8a6/src/components/Approval/Approval.tsx#L69

### Acceptance Criteria

- Approval modal allows users to select exact amount for approval or select unlimited
- Default setting is unlimited approval

### Estimated effort

3 hours

**Comment by elmutt** [comment]
Note that this will also require lib / swapper changes

**Comment by gomesalexandre** [comment]
Estimation: 3 hours @decentralized-j

**Comment by NeOMakinG** [comment]
@decentralized-j what should we use as the allowance tooltip? https://github.com/shapeshift/web/pull/2419/files#diff-17935f9782301023f95f2372d7a5120d72df5f1dff94972e57c8c5a8bd2f6afdR409
