### ISSUE TITLE
Manage and Get FOXy buttons broke on FOX page 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2264]
### Overview

The "Manage" and "Get FOXy" buttons on the FOX Opportunities page are broke. The clicking on them does nothing.

### References and additional details

1. go to app.shapeshift.com
2. log in with your preferred wallet
3. go to the FOX Opportunities page
4. Click on the FOX tab and click the Manage button
5. Notice the click does nothing
6. Then, click on the FOXy tab and click on the Get FOXy button.
7. Notice the click does nothing  

### Acceptance Criteria

When clicking on the manage button on the FOX tab and the Get FOXy button on the FOXy tab, a new window should pop up that allows you to manage your FOX stake
<img width="491" alt="Screenshot 2022-07-28 140101" src="https://user-images.githubusercontent.com/99363597/181606357-a06a1284-96c8-467a-b676-b57c84917e07.png">
. 

### Screenshots/Mockups

<img width="635" alt="Screenshot 2022-07-28 135655" src="https://user-images.githubusercontent.com/99363597/181606382-528d565f-c0e0-4a11-ab71-51732b5ba270.png">
<img width="448" alt="Screenshot 2022-07-28 135708" src="https://user-images.githubusercontent.com/99363597/181606385-02932ea5-27d4-4122-9433-f30102d8ab96.png">

**Comment by gomesalexandre** [comment]
Will tackle this one
