### ISSUE TITLE
Fee display handling in trade modal + displaying slippage amounts in crypto

### ISSUE THREAD

**Issue by decentralized-j** [shapeshift/web#2265]
### Overview

Gm - Was going to combine this ticket with #2266 but it got too long so separated them.

This one is all about fee display handling in the trade modal and displaying slippage amounts. This came to the forefront due to how Cowswap calculates how much the user will receive, based on #2245 and as shown below where we give the impression the user is not losing any value due to slippage.
![181280207-c61a3890-cb2f-44a7-9b7d-bb5f7a468562](https://user-images.githubusercontent.com/97055189/181607704-69238276-b374-4c35-912b-92c0eb341b53.png)

And with Cowswap, the user is shown that they will receive the same amount of $ in their desired asset, but Cowswap removes fees from the 'sell' asset. In screenshot below, user is shown they'll receive $10 DAI. However, after processing the transaction, they receive ~5 DAI because of fees + slippage.

![Whattheusersees1](https://user-images.githubusercontent.com/97055189/181608462-b3fff759-9268-4d95-bf2b-a65805873668.jpg)

The desired handling of this is outlined and shown below. Here is the [Figma link](https://www.figma.com/proto/OHbVrAVaV2xQWUsq0nKzGm/ShapeShift-Library?node-id=162%3A869&scaling=min-zoom&page-id=134%3A613&starting-point-node-id=134%3A614) for additional reference. Ty @reallybeard 

User can enter amount to trade or receive, as normal. Slippage amounts in USD are shown below ($1,000 USDC showing as ~$993.27). Implementation of this closes #2245. User will see the amount they are due to receive, including fees.

Note - These numbers are taken directly from a real Cowswap trade.
![Screen Shot 2022-07-28 at 1 17 50 PM](https://user-images.githubusercontent.com/97055189/181609167-ad2934f5-000e-48e9-acbb-6c9456ff1352.png)

Fee hover modal seen below.
![Screen Shot 2022-07-28 at 1 36 58 PM](https://user-images.githubusercontent.com/97055189/181612894-e0e475bd-f32e-41eb-ae20-933fea3752c7.png)

Review screen below.
![Screen Shot 2022-07-28 at 1 38 05 PM](https://user-images.githubusercontent.com/97055189/181613079-2e50bdc7-0a5b-42e5-8c57-7c3bd3376c79.png)

Pending confirmation screen below.
![Screen Shot 2022-07-28 at 1 38 33 PM](https://user-images.githubusercontent.com/97055189/181613175-d333932d-de0e-4f25-9eb6-83587b079314.png)

Final confirmation screen below.
![Screen Shot 2022-07-28 at 1 38 50 PM](https://user-images.githubusercontent.com/97055189/181613215-dc02739a-aafe-4772-bca9-e21fa20a195d.png)

### References and additional details

Placeholder for technical implementation details.

### Acceptance Criteria

- USD values shown with slippage reflected in trade modal on all steps
- Fee handling in trade modal is in accordance with Figma mockups to show user amounts, in fiat, lost to slippage and fees

**Comment by 0xApotheosis** [comment]
@reallybeard has any code been written to create the interface in those new designs, or shall I start from scratch?

**Comment by 0xApotheosis** [comment]
After checking with product this ticket is now to have the same information available to the user in the buy asset currency, rather than the fiat currency.
