### ISSUE TITLE
Prioritization of user held assets in asset dropdown

### ISSUE THREAD

**Issue by sababa-2019** [shapeshift/web#2266]
### Overview

Gm - As noted in #2265 this was slated to be combined but it got lengthy so they were split.

Currently in the trade modal, when a user selects the asset dropdown, assets they hold in their active wallet are not prioritized.

We want to display to the user the assets that they hold in their active wallet at the top of the list, so the user can more easily select their desired asset to swap.

If there are any questions or mockups required, please tag me and i'll be over in a jiffy to answer anything that comes up.

### References and additional details

Placeholder for technical implementation details.

### Acceptance Criteria

- User assets in active wallet are shown at top of asset dropdown list in trade modal

**Comment by DiggyDiggy2** [comment]
Adding to the ticket - in the Acceptance Criteria - the users balances (that they have assets of) should also display. @reallybeard we're likely going to need a mock up on this one.

**Comment by 0xdef1cafe** [comment]
@shapeshift/product this looks like it should be in v2 to me? can you plz confirm?

**Comment by DiggyDiggy2** [comment]
yes, this can be for V2

**Comment by DiggyDiggy2** [comment]
This would also apply to the search and the "assets" list

**Comment by 0xApotheosis** [comment]
@0xdef1cafe you mentioned some additional requirements on this one - could you please elaborate on what they are?

**Comment by 0xApotheosis** [comment]
From @0xdef1cafe on Discord:

* this asset search component is becoming a core component, it's now used in 3 places - the asset list (top/sidebar of the app), the swapper, and fiat ramps
* it's currently a dumb component and its consumers are managing business logic for what it should render
* i've considered making it a "smarter" component, kind of like the asset dropdown, or at least being able to inject some filter/sort logic into it
* different sort orders - by market cap, by user balance, composite of both, i.e. user balance first, then market cap, then ???
* hide zero balances? ask beard
* if you find a component that takes a god object keyed by asset id, kill it and make sure all take assetId[]
* there's a lot of prop drillin smells - disableUnsupported
