### ISSUE TITLE
Quick Fix - CowSwap Protocol Fee Display

### ISSUE THREAD

**Issue by decentralized-j** [shapeshift/web#2271]
### Overview

Gm!

In order to get CowSwap shipped ASAP, we've added a fix to display the protocol fee to the user on the confirm details screen, as shown below. This will work and accommodate both CowSwap and ThorChain
![unknown](https://user-images.githubusercontent.com/97055189/181642470-d42649c3-430b-44ba-b1d0-52568ccc4381.png)

This fix should allow our users to have all the information they need to make trades using CowSwap, while the revamped trade modal is in the works.

Please ping me if any further information is required to proceed

### References and additional details

Details from @gomesalexandre - ty ser.
> This one will require two changes in the `<TradeConfirm />` component:
> 
> * a simple row addition from a presentational perspective (☕  time)
> * consuming the `feeAmountInSellToken` that's available in the `trade` var:
>   https://github.com/shapeshift/web/blob/8f5c26f403d0829243088a0032179ffbb8f7eeb2/src/components/Trade/TradeConfirm/TradeConfirm.tsx#L49
> 
> This is coming from CowSwapper's `cowBuildTrade()` as parsed response from the Cow.Fi API and is the full 18 digits precision estimated fees in token.
> 
> Estimated time: 1 hour, given we already have the data available

### Acceptance Criteria

- Users can see miner fee & protocol fee when conducting trades

**Comment by gomesalexandre** [comment]
This one will require two changes in the `<TradeConfirm />` component:
- a simple row addition from a presentational perspective (☕  time)
- using the `feeAmountInSellToken` that's available in the `trade` var:
https://github.com/shapeshift/web/blob/8f5c26f403d0829243088a0032179ffbb8f7eeb2/src/components/Trade/TradeConfirm/TradeConfirm.tsx#L49

This is coming from CowSwapper's `cowBuildTrade()` as parsed response from the Cow.Fi API and is the full 18 digits precision estimated fees in token.

Estimated time: 1 hour, given we already have the data available

**Comment by decentralized-j** [comment]
@gomesalexandre Just a heads up, this is now updated to include the change to the Tx history page as well
