### ISSUE TITLE
No back button in the fiat ramp modal

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2273]
### Overview

When selecting the $Buy/Sell Crypto button in app.shapeshift, there is no back back if the user changed their mind on the ramp of choice. They can only exit the modal and start from the beginning again .

### References and additional details

1) Log into app.shapeshift.com 
2) Connect to wallet of choice
3) Select the $Buy/Sell Crypto button
4) Once you choose a ramp, notice there is no back button. If you change your mind on the fiat ramp you chose, you need to X out of the modal and start again . 

### Acceptance Criteria

A back button would allow you to change ramps without exiting all together and having to start again 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
@0xdef1cafe @DiggyDiggy2 do we have estimated hours for this and who shall i put down as the reviewer ? :)

**Comment by gomesalexandre** [comment]
Given we already have routing (the `<FiatRampsRouter />`), this is really just about adding a button and an event firing `history.goBack()` in the `<FiatRamps />` component and styling things according to the product decision for the location of the button. There might be a few gotchas to styling another button next to the `<ModalCloseButton />`, look at other implementations on the codebase on how to achieve this (e.g `src/components/Modals/Receive/ReceiveInfo`:

https://github.com/shapeshift/web/blob/b6b21e628b88e3d32fc85ca29344df00177215cb/src/components/Modals/Receive/ReceiveInfo.tsx#L124-L139

See this diff for a working implementation base implementation (unstyled, without the conditions to hide the icon on other steps where we don't need it)

```diff
diff --git a/src/components/Modals/FiatRamps/FiatRamps.tsx b/src/components/Modals/FiatRamps/FiatRamps.tsx
index 3d60c0030..0688f9dc3 100644
--- a/src/components/Modals/FiatRamps/FiatRamps.tsx
+++ b/src/components/Modals/FiatRamps/FiatRamps.tsx
@@ -1,5 +1,7 @@
+import { ArrowBackIcon } from '@chakra-ui/icons'
 import { Modal, ModalCloseButton, ModalContent, ModalOverlay } from '@chakra-ui/modal'
-import { MemoryRouter } from 'react-router-dom'
+import { IconButton } from '@chakra-ui/react'
+import { MemoryRouter, useHistory } from 'react-router-dom'
 import { useModal } from 'hooks/useModal/useModal'
 
 import { FiatRampsRoutes } from './FiatRampsCommon'
@@ -7,18 +9,35 @@ import { FiatRampsRouter } from './FiatRampsRouter'
 
 const entries = [FiatRampsRoutes.Select, FiatRampsRoutes.Manager]
 
+const FiatRampsContent = () => {
+  const history = useHistory()
+  return (
+    <>
+      <ModalCloseButton />
+      <IconButton
+        isRound
+        size='sm'
+        variant='ghost'
+        aria-label='Back'
+        onClick={history.goBack}
+        icon={<ArrowBackIcon />}
+      />
+
+      <FiatRampsRouter />
+    </>
+  )
+}
 export const FiatRampsModal = () => {
   const { fiatRamps } = useModal()
   const { close, isOpen } = fiatRamps
   return (
-    <Modal isOpen={isOpen} onClose={close} isCentered variant='fluid'>
-      <ModalOverlay />
-      <ModalContent>
-        <ModalCloseButton />
-        <MemoryRouter initialEntries={entries}>
-          <FiatRampsRouter />
-        </MemoryRouter>
-      </ModalContent>
-    </Modal>
+    <MemoryRouter initialEntries={entries}>
+      <Modal isOpen={isOpen} onClose={close} isCentered variant='fluid'>
+        <ModalOverlay />
+        <ModalContent>
+          <FiatRampsContent />
+        </ModalContent>
+      </Modal>
+    </MemoryRouter>
   )
 }
```

**Comment by DiggyDiggy2** [comment]
Yes, it should be  inthe same style as the trade, on the left side of the modal. TY @gomesalexandre 
![Screen Shot 2022-07-29 at 8 32 26 AM](https://user-images.githubusercontent.com/90058616/181782674-6cbb47e2-e009-4b87-96d8-0a567570ccf1.png)
l
