### ISSUE TITLE
Quick Fix 2 - Display CowSwap Fee's in Tx History

### ISSUE THREAD

**Issue by decentralized-j** [shapeshift/web#2279]
### Overview

Gm!

As a follow on to #2271, we want to display the fees that Cowswap (and Thorchain) take out of trades to the user in the Tx history section.

Currently, Tx history looks like this below.
![unknown](https://user-images.githubusercontent.com/97055189/181776542-8743f503-0214-418b-8d47-52f689cade3c.png)

And [here](https://explorer.cow.fi/orders/0x050c369db377387631373eda2690046375e8966e2a4395f84b71c5430c8f6f43b8ff589dbbec0dde6401dc9572f54f8ec779b36462def324) is an example CowSwap transaction that shows the fees taken to execute the trade. Including the information in the 'fees' field is desired. Adding one additional line, preferably just below the 'Transaction Type' line displaying this is requested.

### References and additional details

Placeholder for @gomesalexandre ser!

### Acceptance Criteria

- User can see the fees taken by Cowswap in Tx history

**Comment by 0xdef1cafe** [comment]
this may seem entirely unrelated, but i'm proposed we actually tackle https://github.com/shapeshift/web/pull/2257 first, which exposes more of the parser types from `unchained-client` through `chain-adapters` and gives `web` more relevant tx data.

it will allow us to 

a) close out this long outstanding issue of being able to show `Approve FOX` (including the symbol), and then 
b) have the data to be able to show the cowswap fees in tx history

thoughts @gomesalexandre ? FYI @decentralized-j @DiggyDiggy2

**Comment by decentralized-j** [comment]
If that makes more technical sense to have work flow downhill then fully support it here ser @0xdef1cafe

**Comment by gomesalexandre** [comment]
> this may seem entirely unrelated, but i'm proposed we actually tackle #2257 first, which exposes more of the parser types from `unchained-client` through `chain-adapters` and gives `web` more relevant tx data.

Agreed from an engineering perspective if that's good with product. Everything that brings over the data we need beforehand will just make the user-facing integration easier.
There's a bit of work in the CowSwap parser that will be needed to properly parse Cowswap's `tokenTransfers`, so definitely support this if it allows the Tx data to flow in a better shape

**Comment by gomesalexandre** [comment]
@elmutt Until we parse Thor Txs as trades, will we be able to display the fees here?

**Comment by elmutt** [comment]
Impossible to display the trade fee until we have a thorchain parser (the thorchain parser we have from months ago is not used for anything)

I think this ticket should be for all swappers, if we just do it for one and not the others its just tech debt. I also dont think its a "quick fix" as the title implies, theres quite a bi



> @elmutt Until we parse Thor Txs as trades, will we be able to display the fees here?

**Comment by elmutt** [comment]
Also this definitely relates to the idea of a "blockchain activity" consisting of 1 or more trasactions (we talked about it off and on the last few monnths). It doesnt necessarily make sense to put all of this trade fee data on every single tx related to a trade. @0xdef1cafe might have some thoughts on this too

**Comment by gomesalexandre** [comment]
> Impossible to display the trade fee until we have a thorchain parser (the thorchain parser we have from months ago is not used for anything)
> 
> I think this ticket should be for all swappers, if we just do it for one and not the others its just tech debt
> 
> > @elmutt Until we parse Thor Txs as trades, will we be able to display the fees here?

While I do conceptually agree with you, this is part of the CowSwap milestone and I'd rather we tackle CowSwap then other swappers later on. @decentralized-j I'll split this one into a new issue for other swappers after this is closed and we have more insights.
