### ISSUE TITLE
Warn/clearly display minimum swap values

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#2281]
### Overview

Certain swappers, like cowswap, enforce a minimum swap amount. 

The first screen of the trade widget will allow a user to input any amount, but the second screen (preview trade) will enforce a minimum.

There isn't a clear indication to the user that their manually entered amount that is less than a minimum has been amended.

### References and additional details

See more details where this was originally identified https://github.com/shapeshift/lib/pull/916#pullrequestreview-1055963328

### Acceptance Criteria

Requires @shapeshift/product

**Comment by decentralized-j** [comment]
Will circle on this and get a ticket up tomorrow for alerting users if they've entered an amount sub $20

**Comment by decentralized-j** [comment]
This issue is handled by https://github.com/shapeshift/lib/pull/927 and will be shipped this week.

Closing.
