### ISSUE TITLE
Aggregate UTXO Chains in Accounts

### ISSUE THREAD

**Issue by decentralized-j** [shapeshift/web#2304]
### Overview

Gm!

Now that app.shapeshift.com has BTC, LTC, and BCH, the 'Accounts' page is getting a bit crowded with the different types, as seen below.

![unknown](https://user-images.githubusercontent.com/97055189/182213612-7848f60c-1931-4d26-884c-fc9c9f55dff1.png)

We want to display all the assets a user holds within each account, but consolidate them.

As shown in the screenshot above, the Ethereum account can open a dropdown upon selection of 'Show Tokens' that displays a users token holdings.

We want to mimic this implementation. For example, with Bitcoin types as written below, showing top level with expansion below.

_Bitcoin - 1 BTC - $30,000_
- _Bitcoin - 'Segwit Native' - 0.3 BTC - $10,000_
- _Bitcoin - 'Segwit' - 0.3 BTC - $10,000_
- _Bitcoin - 'Legacy' - 0.3 BTC - $10,000_

In order to view the breakdown of different asset types, the user will click on the top level 'Bitcoin' row or the button below displaying 'Show Accounts' (in place of 'Show Tokens' for Ethereum accounts, but the functionality is the same)

### References and additional details

Placeholder

### Acceptance Criteria

- User is able to see all UTXO holdings aggregated at a top level
- User is able to expand on their UTXO holdings and see individual account level allocations in a collapsable drawer

**Comment by reallybeard** [comment]
Here is the new design for grouping by chain (fee asset). 

https://www.figma.com/proto/OHbVrAVaV2xQWUsq0nKzGm/ShapeShift-Library?node-id=1265%3A4078&scaling=min-zoom&page-id=1265%3A4077

**Comment by 0xdef1cafe** [comment]
closing as duplicate/subset of https://github.com/shapeshift/web/issues/2535
