### ISSUE TITLE
Switching chains returning users to connect wallet screen in MM

### ISSUE THREAD

**Issue by sababa-2019** [shapeshift/web#2320]
### Overview

Gm!

Currently when a user is prompted to switch chains in Metamask on app.shapeshift.com, the app returns them to the 'connect wallet' screen after, as displayed in the video below.

https://user-images.githubusercontent.com/97055189/182446931-d043974a-b8c4-4ddb-88de-c3e4325862da.mov

We'd like for the user to stay on the same screen they were on when they switched chains. If this is not possible, returning them to the 'Dashboard' is an acceptable backup.

### References and additional details

Placeholder

### Acceptance Criteria

- User stays on current screen when switching chains (or for fallback implementation - is directed to 'Dashboard')

**Comment by 0xApotheosis** [comment]
This should already be fixed by the work done to close https://github.com/shapeshift/web/issues/2335.

@shapeshift/operations could you please confirm?

**Comment by 0xdef1cafe** [comment]
closing as fixed
