### ISSUE TITLE
Cosmos UI - Matching claim stepper to vertical deposit and withdraw implementation

### ISSUE THREAD

**Issue by decentralized-j** [shapeshift/web#2329]
### Overview

Gm!

Currently in the Cosmos UI, the deposit and withdraw steppers are vertical (shown below) and are awesome.
<img width="550" alt="Screen Shot 2022-08-03 at 11 51 50 AM" src="https://user-images.githubusercontent.com/97055189/182675878-ba856b33-df05-4768-aaef-53e78b34c526.png">

We want to have the 'Claim' flow (shown below) mimic the same vertical stepper as the deposit and withdraw steppers instead of being horizontal.
<img width="578" alt="Screen Shot 2022-08-03 at 11 51 58 AM" src="https://user-images.githubusercontent.com/97055189/182676033-b624076e-a2e9-40a7-9e51-cb841466ab54.png">

If mocks are needed for this, please let me or @reallybeard know.

### References and additional details

Placeholder

### Acceptance Criteria

- Cosmos claim flow is a vertical stepper matching the deposit and withdraw flows

**Comment by gomesalexandre** [comment]
@reallybeard for design input on this one
