### ISSUE TITLE
UTXO's need to be added for demo wallet LTC + BCH

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#2330]
### Overview

Once I create both UTXO's on the demo wallet they need to be added to the demo wallet to make sure it doesn't break. I will update this ticket once both sends have been done and notify engineering.

### References and additional details

N/A

### Acceptance Criteria

Tshifty sends into demo wallet and notify engineering that UTXO's have been created for LTC and BCH. Engineering pulls the UTXO's from the wallet and adds both into demo infrastructure.

**Comment by tshifty** [comment]
LTC: (LS5M1bLSgYWV27rtv4B2xwrhHS6wXpuPhq) https://live.blockcypher.com/ltc/tx/42e3daf3c1edcbd87ff603451273cb6503fcd1bdd2340d8027f418cd6196301f/
BCH: (bitcoincash:qrnrqru0m7g466esnxpfzxnu5wfedrnaw5pnl7jwvq) https://blockchair.com/bitcoin-cash/transaction/9db907ea1c8c92a615c645c940978ca1584b9a7086799c1b178c1c8bd8e11057

@0xdef1cafe UTXO's created

**Comment by 0xdef1cafe** [comment]
https://iancoleman.io/bip39/ for future reference
