### ISSUE TITLE
Display 0/infinite/value allowances in Tx history

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#2345]
### Overview

Currently, `approve()` Txs are displayed as such:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/17035424/182972587-bcb6e352-fcb3-46f5-b670-72c12d619f49.png">

As a user, I would like to see:

- The `approve()`d amount
-  "Revoke" or a similar copy when approvals are 0
- "Infinite" or a similar copy when approvals are >= totalSupply

### References and additional details

TODO - will be technically specced after the rough edges are tackled in https://github.com/shapeshift/web/pull/2257

### Acceptance Criteria

- The approved amount is shown in the Tx history
- A user-friendly copy is display to show whether the approval is a revoke, an infinite approval, or any approval value in-between

**Comment by gomesalexandre** [comment]
@shapeshift/product This is now unblocked, waiting for product input before technically speccing this

**Comment by reallybeard** [comment]
![Screen Shot 2022-08-12 at 10 39 59 AM](https://user-images.githubusercontent.com/89934888/184391114-76436c9c-d593-4a73-8d77-00c100992092.png)
