### ISSUE TITLE
"insufficient funds" error on ATOM -> OSMO

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#2355]
@shapeshift/product this requires some thought on how we handle this.

I'm not sure if there is a technical way around this, though @elmutt might know.

In the short-term I suggest adding appropriate messaging and blocking the transaction from proceeding if the destination address's balance is too low to complete a swap.

---

Creating a ticket to track the bug noted on https://github.com/shapeshift/web/pull/2351

---

Tested thor swap with Native wallet trading ETH to Cosmos and the TX link generated as expected.

I couldn't test Cosmos to Osmosis, or the reverse as it's all pretty broken, but it's not a regression in this PR, it's broken on `develop` already. The logic change in this PR _seems_ sane though.

When doing `ATOM` -> `OSMO` I get an "insufficient funds" error and the trade appears to fail, though it ultimately goes through:

<img width="1252" alt="Screen Shot 2022-08-07 at 11 55 28 am" src="https://user-images.githubusercontent.com/97164662/183271865-ba628ac8-975c-4b23-837b-cef048184b92.png">

When trying to go `OSMO` -> `ATOM` it says I have no balance:

<img width="812" alt="Screen Shot 2022-08-07 at 11 56 45 am" src="https://user-images.githubusercontent.com/97164662/183271885-30668afa-dcf0-4fbe-b657-df377f3325b8.png">

_Originally posted by @0xApotheosis in https://github.com/shapeshift/web/pull/2351#pullrequestreview-1064362298_

**Comment by toshiSat** [comment]
Seems like the ibc transfer is failing.  @0xApotheosis could I get your Atom/Osmo public address to see what happened?  Also, perhaps, any txid's related to this tx

**Comment by 0xApotheosis** [comment]
Yes ser.

Cosmos receive address: `cosmos1wmcjaxgt42vfc2rwk8ye3qvhdugjmrvu5533dz`
Osmosis receive address: `osmo1wmcjaxgt42vfc2rwk8ye3qvhdugjmrvuu0zpms`

Trade tx: https://www.mintscan.io/osmosis/txs/A97F469CC75EDF6C720A0215A09CE18F7DEAEB5485D505745B9F5DD62C3DAA04

**Comment by elmutt** [comment]
fixed by

https://github.com/shapeshift/web/pull/2375
and
https://github.com/shapeshift/lib/pull/948

**Comment by 0xApotheosis** [comment]
We discovered that this error occurs when the Osmosis receive address has a `0` balance.

@gomesalexandre: `ATOM's basically stuck in the IBC channel as ATOM on Osmosis`

**Comment by 0xApotheosis** [comment]
Note, this will not be fixed by https://github.com/shapeshift/web/pull/2375 or https://github.com/shapeshift/lib/pull/948, and requires a separate PR once a product decision has been made.

**Comment by elmutt** [comment]
You can often get away with 0 fee transactions on osmo so it COULD work for a while to just set it to 0 but I don't think its a good idea to count on that working forever.

IMO the simplest solution is to treat this the same as an EVM swapper that does not have enough eth to swap -- its a very similar situation and we could just display "insufficient osmo funds" or something

**Comment by 0xApotheosis** [comment]
Per @DiggyDiggy2's comment https://github.com/shapeshift/web/issues/2377#issuecomment-1211248692:

> For now, we're planning to default the gas to the slowest "free" fee. This will solve this issue. We'll need to monitor closely and make sure we warn users in the future if this changes/figure out another way to handle.

> ALso, with the new swapper allowing custom gas fees, we'll need to inform the user that Osmo will be required for this trade if they change the gas setting. I'll make a note of this in the spec for advanced trade settings.

**Comment by elmutt** [comment]
fixed by https://github.com/shapeshift/lib/pull/968

**Comment by elmutt** [comment]
closed b
