### ISSUE TITLE
Trade Modal: Stop displaying a ShapeShift fee

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#2362]
### Overview

Sometimes when making a swap, there is a ShapeShift fee when routed through CowSwap.
The ShapeShift fee should always be zero.

### References and additional details

see screenshots for trade pairs where this was occuring

### Acceptance Criteria

The ShapeShift fee on every trade should always be "0"

### Screenshots/Mockups

Here are two examples of trades when there were ShapeShift trade fees being displayed.
<img width="416" alt="Screen Shot 2022-08-08 at 9 57 30 AM" src="https://user-images.githubusercontent.com/90058616/183461139-2eaf9bc3-b24b-48db-851e-bb256950c342.png">
<img width="697" alt="Screen Shot 2022-08-08 at 9 57 14 AM" src="https://user-images.githubusercontent.com/90058616/183461168-1b71d9f2-3a2e-4d48-82ff-81a4f1ca2f04.png">

**Comment by gomesalexandre** [comment]
Assigning myself to spike it since I'm currently in that exact domain
