### ISSUE TITLE
Cant trade into osmosis if no osmo balance

### ISSUE THREAD

**Issue by elmutt** [shapeshift/web#2377]
### Overview

Trading into osmosis requires an osmosis transaction as the second step. This fails if the user does not have any osmo in their wallet

@shapeshift/product how do we want to handle this?

### References and additional details

n/a

### Acceptance Criteria

n/a

**Comment by 0xApotheosis** [comment]
@elmutt I realise https://github.com/shapeshift/web/issues/2355 is probably an appropriate place to track this.

I'll merge this into it.

**Comment by gomesalexandre** [comment]
> @elmutt I realise #2355 is probably an appropriate place to track this.
> 
> I'll merge this into it.

Correct, that's the same error I've been seeing while swapping ATOM -> OSMO without OSMO.

**Comment by DiggyDiggy2** [comment]
For now, we're planning to default the gas to the slowest "free" fee. This will solve this issue. We'll need to monitor closely and make sure we warn users in the future if this changes/figure out another way to handle.

ALso, with the new swapper allowing custom gas fees, we'll need to inform the user that Osmo will be required for this trade if they change the gas setting. I'll make a note of this in the spec for advanced trade settings.
