### ISSUE TITLE
Confirm and Status circles in Fox Claim modal too close to top of the modal box

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2378]
### Overview

When claiming Fox, the confirm and status circles appear too high in the modal. It's inconsistent with positioning of other modals' status progress positions.

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice.
2) Navigate to the Fox Opportunity page and select the Manage option in the FOX Token Staking
3) Select either 'Claim' or 'Claim now' under rewards.
4) Notice the top of the modal and the Confirm and Status circles being too close to the top of the modal

![image](https://user-images.githubusercontent.com/100157997/183790733-a6da40aa-0b12-427e-aa2a-ca0560276cc7.png)

### Acceptance Criteria

Spacing at the top of fox claim modal should be consistent with other modals

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@reallybeard I think this is a non-issue as we want to use the new vertical stepper for this?

**Comment by MBMaria** [comment]
@reallybeard @gomesalexandre this is the broadcast screen of fox claim - same issue with the circles being too high, also the claim amount is kinda running into the text... not sure if this is a non issue as well?
![image](https://user-images.githubusercontent.com/100157997/184019976-dd2d0388-e53f-451f-8014-910d30ba5727.png)

**Comment by DiggyDiggy2** [comment]
Please use the new vertical stepper for this.
