### ISSUE TITLE
KeepKey CowSwap Error

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2392]
### Overview

When trading with CowSwap on KeepKey, the trade fails and a something went wrong error toast pops up. Also, when you go to confirm on the device, the text is random jargon.

### References and additional details

1. go to app.shapeshift.com
2. log in with KeepKey
3. turn on the cowswap flag
4. attempt to make a trade at the trade modal 
5. when you click the confirm and trade button the trade fails
6. a something went wrong error toasts pops up and on the keepkey device, the confirm text is random jargon. 

### Acceptance Criteria

KeepKey trades should broadcasts successfully on cowswap and the confirm text on the device should be legible. 

### Screenshots/Mockups

<img width="397" alt="Screenshot 2022-08-10 163931" src="https://user-images.githubusercontent.com/99363597/184017015-4b101ffc-843c-407e-b723-cd9faeece545.png">
<img width="435" alt="Screenshot 2022-08-10 164027" src="https://user-images.githubusercontent.com/99363597/184017017-65002e1f-e092-45e0-8651-45e14b68357d.png">

**Comment by 0xdef1cafe** [comment]
@pastaghost solution likely here https://discord.com/channels/554694662431178782/989621291399139369/1007326884364828672

**Comment by gomesalexandre** [comment]
Reopening so the web PR can close this
