### ISSUE TITLE
Fox Page: Display "Connect Wallet" instead of  "Get Started" for Demo Wallet

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#2411]
### Overview

As a user with a connected demo wallet (either manually or through deep linking), I am able to connect my wallet in order to start depositing into FOX opportunities.

### References and additional details

https://github.com/shapeshift/web/issues/1805

### Acceptance Criteria

- Fox Farming and LP show "Connect Wallet" instead of "Get Started" in the case of a connected demo wallet
  - Clicking this button opens the wallet connect modal
- There is no regression for these two opportunities in the case of a non-demo wallet
- There is no regression in the main FOX opportunity (FOXy staking) i.e it is still possible to click manage and get started with the staking flow on a demo wallet

**Comment by gomesalexandre** [comment]
Currently blocked by https://github.com/shapeshift/web/issues/2412 - we can't update those buttons before Fox Farming is live in the app.

**Comment by 0xdef1cafe** [comment]
no longer an issue 

![Image](https://user-images.githubusercontent.com/88504456/204683962-0a2061c0-ca75-4160-b96f-0a84963459bf.png)
