### ISSUE TITLE
FOX-ETH LP Icon Fix

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2428]
### Overview

When depositing FOX and ETH in to the FOX-ETH LP, transactions only show the ETH icon when you are depositing and the FOX icon when you are withdrawing. Transactions should show both icons as you are withdrawing and depositing ETH and FOX into the LP simultaneously. 

### References and additional details

1. log into app.shapeshift
2. go the the DeFi earn page
3. click on the FOX-ETH v2 LP 
4. do a deposit and withdraw 
5. go to you transaction history page or the recent transactions on the dashboard
6. notice it only shows the ETH icon for deposits and the FOX iron for withdraws 

### Acceptance Criteria

Transactions should show both icons as you are withdrawing and depositing ETH and FOX into the LP simultaneously. 

### Screenshots/Mockups

Deposit:
<img width="296" alt="Screenshot 2022-08-12 154806" src="https://user-images.githubusercontent.com/99363597/184432496-5a1c97d5-c5cc-4d36-810d-93595bf28f31.png">

Withdraw:
<img width="294" alt="Screenshot 2022-08-12 154823" src="https://user-images.githubusercontent.com/99363597/184432498-e4c6a551-42b2-4ba3-8e99-604e2a495c76.png">

How the icon should look for both deposits and withdraws:
<img width="47" alt="Screenshot 2022-08-12 154912" src="https://user-images.githubusercontent.com/99363597/184432499-d0fe16ce-e31f-49ae-86ae-4afbc9a19f30.png">

**Comment by reallybeard** [comment]
We worked on a mock on how we could do this, and allow this to scale when we allow more than 2 sided pools.
![Screen Shot 2022-08-15 at 10 35 36 AM](https://user-images.githubusercontent.com/89934888/184666736-cdad9c2b-90c2-484e-a204-e4d6b41dbb3a.png)

**Comment by gomesalexandre** [comment]
Related to https://github.com/shapeshift/web/issues/2428
There will be unchained-client Tx Metadata parsing needed here, which is the same thing we need in the aforementioned issue
