### ISSUE TITLE
German lang support

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#2442]
### Overview

We want to add German translations

### References and additional details

Add a `de.json` and associated boilerplate

### Acceptance Criteria

We can switch to german language. Out of scope is the translations themselves - these will be provided later by the globalization team.

### Estimated effort

30 mins

**Comment by hellhound13** [comment]
Hi, D©evil here, I will do the translation, but not the implementation... I think I am wrong here... or?
