### ISSUE TITLE
Hide AVAX & AVAX assets for Native Wallet Users

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#2463]
### Overview

AVAX is currently not supported by Native Wallet. 
Please hide these assets from those users until we have proper support.

### References and additional details

Showing AVAX & Assets on AVAX presents an issue for Native wallet users. As an example, when trying to set up a trade pair with AVAX - the user just gets an endless "searching for rates" spinner.

When viewing an asset details on AVAX - the web app shows "Something went wrong. An error has occured."

### Acceptance Criteria

AVAX assets should not display for Native Wallet users

**Comment by 0xdef1cafe** [comment]
closing as not required.
