### ISSUE TITLE
Mobile Browser App side bar - phones w/smaller screen size 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2465]
### Overview

On the mobile browser version of app, the side bar cuts off some of the options at the bottom and you are unable to scroll to get to them on a phone with a small screen size, EX: iphone se

### References and additional details

1. go to app.shapeshift.com on your mobile device 
2. log in to the dashboard
3. click on the menu button on the top left of the screen, the 3 stacked vertical lines. 
4. the side bar will pop out from the left hand side of the screen
5. notice some of the items are cut off on the bottom of the side bar, settings, join discord, and submit feedback
6. attempt to scroll to the bottom to view the missing items and notice the bar does not scroll down

### Acceptance Criteria

 settings, join discord, and submit feedback should be viewable on smaller screens or you should be able to scroll on the sidebar. 

### Screenshots/Mockups

Wrong View:
<img width="391" alt="Screenshot 2022-08-17 142129" src="https://user-images.githubusercontent.com/99363597/185214325-79bec8df-2a6a-4822-ac6e-678e39a5dcc7.png">

Correct View: 
<img width="290" alt="Screenshot 2022-08-17 142138" src="https://user-images.githubusercontent.com/99363597/185214327-d93adeb3-086f-48f0-af97-44f218a40014.png">

**Comment by 0xdef1cafe** [comment]
![Image](https://user-images.githubusercontent.com/88504456/186811280-8247fb8f-0abd-41a3-8d22-dadd41ed41e2.png)

closing as fixed and scrollable
