### ISSUE TITLE
Spike: Failed to fetch Coingecko FOX historical market data

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#2472]
### Overview

Spotted by @stackedq during work on https://github.com/shapeshift/web/pull/2449

`foxy.js:95 FoxyMarketService(findPriceHistoryByAssetId): Failed to find price history by AssetId`

We intermittently get failed XHRs on Coingecko FOX historical market data, which results in the 1Hr/24Hr price for FOX/y being missing, as well as incorrect price chart lines.

This is happening on both develop and production envs.

### References and additional details

https://github.com/shapeshift/lib/pull/830

### Acceptance Criteria

- We know the root cause of the failed XHRs

**Comment by 0xdef1cafe** [comment]
closing - foxy has it's own market service that relies on archival node data, and this was infura flakiness at the time
