### ISSUE TITLE
German translation 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2479]
### Overview

This ticket encompasses all the missing german translation we have found on app.

### References and additional details

1. go to app.shapeshift.com
2. log in with preferred wallet
3. change the language to german
4. look at the screenshots provided in this ticket and replicate 

### Acceptance Criteria

when changing language to German, all text should translate from English 

### Screenshots/Mockups

<img width="222" alt="Screenshot 2022-08-18 130715" src="https://user-images.githubusercontent.com/99363597/185465693-3610b1ab-7d50-474d-967d-bf265642323d.png">
<img width="947" alt="Screenshot 2022-08-18 130724" src="https://user-images.githubusercontent.com/99363597/185465695-bce5749e-829b-4bf5-bfd9-e90fa4594906.png">
<img width="361" alt="Screenshot 2022-08-18 130736" src="https://user-images.githubusercontent.com/99363597/185465698-c6a3dd96-2fbd-4df9-a220-3974c81647eb.png">
<img width="296" alt="Screenshot 2022-08-18 141223" src="https://user-images.githubusercontent.com/99363597/185465700-87485863-6f96-413f-af4a-a481673dbda3.png">
<img width="537" alt="Screenshot 2022-08-18 141446" src="https://user-images.githubusercontent.com/99363597/185465701-b77b7506-ab83-4da8-a9ed-ab0638376085.png">
<img width="511" alt="Screenshot 2022-08-18 141520" src="https://user-images.githubusercontent.com/99363597/185465702-d75c4260-a917-4cae-b691-7d56d0638b98.png">

**Comment by gomesalexandre** [comment]
@firebomb1 Is this related to the translations you mentioned were still missing?

**Comment by firebomb1** [comment]
As discussed on Discord, Farming/Staking are deliberately not translated in German for lack of better translations/crypto lingo in this language, if there are suggestions for better words that will both be understood by people in crypto and new to crypto we welcome them ;)

The exception in these screenshots are the Proposal titles which come from an external source. Not translatable in the current system, considering that these would be "dynamic" strings (as opposed static ones we currently translate) and that the whole ideation/proposal/governance process happens in English I doubt it's a priority to make these translatable currently.

@wesleygravess If you have time for reviews of German translations before they get merged in the app I think could contact @thesmithdao to get included in the review *loop* (@thesmith on the ShapeShift Discord). Reviewers have the ability to make suggestions on Github and discuss with the translators directly.

**Comment by wesleygravess** [comment]
its already merged into app. that's all we saw during testing so far

**Comment by firebomb1** [comment]
> its already merged into app. that's all we saw during testing so far

I know, I'm talking about the next times if you have German knowledge and time for reviews of course!

**Comment by wesleygravess** [comment]
> > its already merged into app. that's all we saw during testing so far
> 
> I know, I'm talking about the next times if you have German knowledge and time for reviews of course!

I see, will do!

**Comment by thesmithdao** [comment]
Thanks @firebomb1 and @wesleygravess. You guys performed a great job, the Globalization WS appreciates it. 
Yes, review loop is open for community members and aligned with github flow. Feel free to jump in Global's # in Discord or just reach me out. 

~~ @thesmithdao

**Comment by firebomb1** [comment]
Few untranslatable strings which need Engineering work.

"Trade" in the Dashboard:

https://github.com/shapeshift/web/blob/c78f699bc60ce809578bc75488c8c4e1b09f56a3/src/pages/Dashboard/TradeCard.tsx#L19

---

Staking table headers ("Header" keys):

https://github.com/shapeshift/web/blob/c78f699bc60ce809578bc75488c8c4e1b09f56a3/src/components/StakingVaults/StakingTable.tsx#L32-L89

---

The breadcrumb is still also not translatable as mentioned in https://github.com/shapeshift/web/issues/2175 . I think these two issues should be set  as "needs engineering", but I'm not sure to whom to assign them and if I should change the labels myself, any advice @0xdef1cafe ?

---

The rest of the strings are translatable as far as I can see. Some are purposefully not translated (Staking/Farming) if other strings should be fixed/translated it will happen during a review of the German translations, up to @thesmithdao to organize this. Strings can easily be searched on the translation platform to do so.

**Comment by DiggyDiggy2** [comment]
reviewing this– not sure why there's a "needs product" label on it. Can someone clarify for me, what Product needs to weigh in on?

**Comment by wesleygravess** [comment]
> reviewing this– not sure why there's a "needs product" label on it. Can someone clarify for me, what Product needs to weigh in on?

AH I didn't realize there was a needs translation label, I'll change it. Does product get tagged in copy issues unrelated to translation?

**Comment by firebomb1** [comment]
Does "needs translations" tag engineers too? Because as I've stated above we can't do much for most of the cases above (and in the linked issue), it "needs engineering" first, until these strings/elements are translatable we can't translate them 😁

**Comment by wesleygravess** [comment]
> Does "needs translations" tag engineers too? Because as I've stated above we can't do much for most of the cases above (and in the linked issue), it "needs engineering" first (or simultaneously). Until these strings/elements are translatable we can't translate them 😁

got it 👯
