### ISSUE TITLE
Demo Wallet Banner 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2480]
### Overview

After you log in with a demo wallet, you can switch to a real wallet. However, the demo wallet banner stays at the top of the screen after logging in with a real wallet. 

### References and additional details

1. go to app.shapeshift.com 
2. log in to a demo wallet 
3. log in to another wallet on the demo wallet dashboard 
4. once logged in with your wallet, noticed the demo wallet banner stays at the top of the screen 

### Acceptance Criteria

Demo wallet banner should disappear after logging in with a real wallet

### Screenshots/Mockups

<img width="1280" alt="Screenshot 2022-08-18 141236" src="https://user-images.githubusercontent.com/99363597/185467337-69f20cab-35f3-4e85-9565-c3a3ab669ee0.png">

**Comment by gomesalexandre** [comment]
Might have been introduced in https://github.com/shapeshift/web/pull/2410
