### ISSUE TITLE
Thor fees in confirm modal are inaccurate

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#2482]
### Overview

When swapping with Thor there are two issues with the fees shown on the confirm component:

1. The ShapeShift fee is not 0 - it should always be 0.
2. The buy amount is incorrect as it doesn't subtract the fee amount

### References and additional details

<img width="379" alt="Screen Shot 2022-08-18 at 4 40 05 pm" src="https://user-images.githubusercontent.com/97164662/185480534-28d826d3-7e8e-4d8c-a883-3ffb5d92ac1e.png">

### Acceptance Criteria

1. ShapeShift fee is 0
2. Buy amount accurate as to the amount that will actually be received

**Comment by 0xApotheosis** [comment]
@shapeshift/product I'm not sure of the ordering here, is this something we want fixed in the current swapper, or shall we wait until V2?

**Comment by elmutt** [comment]
@0xApotheosis I assumed we were waiting for the v2 swapper modal for this but if product wants it done now its easy enough. Just not sure where the thorchain fee would be displayed so waiting makes more sense to me
