### ISSUE TITLE
"Confirm and Trade" button spins indefinitely after completing a thor trade

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2488]
### Overview

When completing a thor trade, the Confirm and Trade button spins indefinitely. Must go to different page and back again before it stops spinning.

### References and additional details

1) Log into app.shapeshift and connect to native or keepkey
2) Turn on thor flag
3) Select thor trade and preview trade
4) Confirm and Trade and notice the blue button spins indefinitely (Even after tx is showing in recent transactions)
![image](https://user-images.githubusercontent.com/100157997/185566486-e673b436-517a-4bf3-85ad-8569729c7a9e.png)

### Acceptance Criteria

Button should refresh once trade is complete

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
@gomesalexandre isn't that related to the `approveAmount` again?

**Comment by gomesalexandre** [comment]
> @gomesalexandre isn't that related to the `approveAmount` again?

That's very unlikely as:
1. the trade confirm step happens after the approval step
2. there is no approval required for UTXOs as is the case in this screenshot (nor is there for native EVM tokens, in case this happens with ETH sell asset as well)
