### ISSUE TITLE
Trade widget creating minimum thor swap error then reverting

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2504]
### Overview

When doing a thor trade, when you put in a lower amount to trade in the pair, it comes up with an error to say the trade has a minimum amount. After leaving it for a couple seconds, the widget will update and allow the trade to go through. Only noticing it happen when initially using the trade widget. After making a few trades and swapping pairs, it doesn't seem to happen. 

### References and additional details

1) Log into test branch https://bafybeidk3nuxd26ioi7outcmwl6lkhxn3lhewe3skpal6re3seunlggbmu.on.fleek.co/ and connect to kk or native wallet.
2) Turn THOR flag on
3) Select a thor trade pair with a low amount
4) Notice the trade will error with a minimum amount required
5) Leave it for a bit and notice the error will revert and you can continue with trade. 

Testing PR: https://github.com/shapeshift/web/pull/2471
![image](https://user-images.githubusercontent.com/100157997/185713772-b51fca9b-3da3-4cf1-91bd-eb760e795cf5.png)
![image](https://user-images.githubusercontent.com/100157997/185713788-c073deb9-1db4-4985-bb00-24cb2c63e1cd.png)

### Acceptance Criteria

Trade should not error if its allowable. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by DiggyDiggy2** [comment]
@MBMaria can we close this now with the new swapper?

**Comment by DiggyDiggy2** [comment]
@MBMaria can we close this now with the new swapper?

**Comment by MBMaria** [comment]
Closing this as it is no longer an issue with the new swapper
