### ISSUE TITLE
Sent/Received transaction history rows have superfluous (unused) symbol in their label

### ISSUE THREAD

**Issue by firebomb1** [shapeshift/web#2524]
### Overview

Transactions rows currently use a translatable string that is supposed to include a symbol, but the symbol isn't used when displaying this string which causes unexpected capitalization in certain languages. See French for example:

![image](https://user-images.githubusercontent.com/88804546/186046691-69ba8e9d-9b55-470b-bcdb-f57313580d58.png)
(should be either "**E**nvoyé" or "_\<asset symbol\>_ **e**nvoyé"

This should be fixed either by removing the symbol from the translatable string (and the call), or preferably in my opinion by adding the symbol in the call (see below).

### References and additional details

The translatable strings (including the symbol variable):

https://github.com/shapeshift/web/blob/c78f699bc60ce809578bc75488c8c4e1b09f56a3/src/assets/translations/en/main.json#L352-L354

The call, with an empty symbol is passed:

https://github.com/shapeshift/web/blob/c78f699bc60ce809578bc75488c8c4e1b09f56a3/src/components/TransactionHistoryRows/TransactionGenericRow.tsx#L154

The symbol should be available in in the `assets.symbol` variable, but if this was intentionally not passed in order to not display the asset symbol (for any reason?), then the string should be updated accordingly... and the call too.

### Acceptance Criteria

Fixed string/call to displays nicely in all translated languages.

**Comment by gomesalexandre** [comment]
@shapeshift/product Do we actually want to display "Sent assetSymbol" / "Receive assetSymbol", given we already have that information on the next column?

<img width="394" alt="image" src="https://user-images.githubusercontent.com/17035424/186537296-cc6863d3-3d63-4b21-980a-7a75ac026f63.png">

**Comment by DiggyDiggy2** [comment]
@gomesalexandre agreed. We don't want to display the symbol twice.

**Comment by firebomb1** [comment]
Then the issue is that the translatable string suggests that there will be a symbol and in certain languages this expectation creates a weird looking text when the symbol is missing as shown in my screenshot.

The fix is then to remove the non-displayed symbol from the string in English and reset the translations for this string so translators will re-translate it eventually).  I've checked again and the symbol variable isn't used in other calls.
