### ISSUE TITLE
Technical clean-up: remove hard-coding of account #0

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#2536]
### Overview

Replace all hardcoding of account #0 with dynamic usages consumed from #2546

There will be no UI changes - everything should function the same after the corresponding PR is merged. 

### References and additional details

This diff will be helpful: https://github.com/shapeshift/web/compare/account-number-shenanigans

### Acceptance Criteria

All instances of hardcoded account 0 are removed across the web repo. 
Coordinate regression test with operations

Additional tickets will follow for other repo's

**Comment by 0xean** [comment]
Some places to check for hardcoding 

* defi
* send
* receive
* swapping
