### ISSUE TITLE
Create a reusable account selection component UI

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#2537]
### Overview

Create a reusable component that allows the user to select from a list of available accounts.

### References and additional details

https://shapeshift.notion.site/Handle-Multiple-Accounts-a0ac02a4e9704440b08f13a3c619281f

### Acceptance Criteria

This component should support usage on the dashboard, accounts page, asset pages, transaction history, and for specific actions like send, receive, buy/sell and trade.

**Comment by DiggyDiggy2** [comment]
can Beard handle the UI for this, but not wired up? @reallybeard

**Comment by DiggyDiggy2** [comment]
use the UTXO version and apply
