### ISSUE TITLE
Store account meta data in portfolioSliceCommon

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#2546]
### Overview

store BIP44 params associated with accountSpecifier when it's created for reuse across the app
https://github.com/shapeshift/web/blob/develop/src/state/slices/portfolioSlice/portfolioSliceCommon.ts#L89

See [here](https://github.com/shapeshift/web/compare/account-number-shenanigans#diff-3316dabcd3452fc0a6688adad4d102c689cc2d52d71ce1d79196e92054f630b0R26) for one potential strategy and notes

**Comment by asamere** [comment]
https://github.com/shapeshift/lib/pull/992
this lib pr needs to go in ahead of the linked web pr https://github.com/shapeshift/web/pull/2566
