### ISSUE TITLE
Trade Modal on a new approval displaying Trade twice

### ISSUE THREAD

**Issue by Neverwas-dev** [shapeshift/web#2558]
- Brief description
When approving a new asset the Modal is displaying Trade twice on the Confirm or Reject step.

- Steps to recreate
1. Select an asset to that isn't approved yet
2. Enter an amount
3. Click on "Preview Trade"
4. Check the title of the form.

- Screenshots/vids (add or add attachments “to the right”)

![](https://cdn.discordapp.com/attachments/1012312973848612864/1012350299022835782/unknown.png)

- AC
Remove or change one of the Trade headers.

**Comment by Neverwas-dev** [comment]
Adding the needs Product just for review of intended behavior

**Comment by DiggyDiggy2** [comment]
Thanks, Lets make sure this doesn't pop up again in Swapper 2.0. @reallybeard quick fix?
