### ISSUE TITLE
Coinstack failure tolerance - accounts

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#2575]
### Overview

Currently, the unchained coinstacks are entirely decoupled and their health is independent of each other.

However, if any coinstack is unheatlhy, the web dashboard, including account data and tx history, will fail to load as we wait for all responses to succeed to deem that we're in a loaded state.

We want the app to function in a way that is tolerant of one or more failures of coinstacks, and is able to load and show account and transaction data that is available.

### References and additional details

* @reallybeard how do we want to display this to the user? I was thinking a toast requiring manually dismissal along the lines of "Trouble loading data for Foo chain". A second step could be add a retry button in case the failure was transient (network timeout/load related).

### Acceptance Criteria

* The app is functional with one or more failing coinstacks. Misconfigure an endpoint to introduce a failure and observe it's handle gracefully.

### Estimated effort

1 day

**Comment by DiggyDiggy2** [comment]
@reallybeard we already discussed and are good to move forward, yes? Message with Retry button.

**Comment by reallybeard** [comment]
> @reallybeard we already discussed and are good to move forward, yes? Message with Retry button.

yah, thats what I remember. Fire off a toast, with a retry button.
