### ISSUE TITLE
Gracefully handle wallets that are connected, but have an unsupported network selected

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#2581]
### Overview

As a user, when using my wallet with ShapeShift, I want to know if the network I've chosen on my wallet is supported by ShapeShift.

We users have a network selected in their wallet that we don't support, they are not informed of this and it's confusing.

We should prompt them to switch networks in the ShapeShift web app, when this case occurs.

### References and additional details

see overview.

### Acceptance Criteria

when using a wallet, with an active network that's not supported by ShapeShift, the user should see a message to switch networks.

**Comment by DiggyDiggy2** [comment]
Added a needs product label, we'll need to mock up a modal for this scenario

**Comment by firebomb1** [comment]
I'd like to suggest something that I think would be less disrupting than forcing users to switch Network through a modal/error message.

Instead we could display an "Unsupported network" button/option in the current Network Selector (or display the last known network they used in the app).

When the user clicks on it, we display the Networks which we do support, and allow the user to switch at their leisure by clicking on them.

The reasoning is that if a user is connected to a network we don't currently support most of our app is still usable for viewing balances/checking trade quotes/opportunities. And when they do need to interact with the network (e.g. confirm/reject a transaction or sign a message) we already check the Network and offer to switch to the proper one if needed (based on the assets/network they want to use).

**Comment by gomesalexandre** [comment]
> The reasoning is that if a user is connected to a network we don't currently support most of our app is still usable for viewing balances/checking trade quotes/opportunities. And when they do need to interact with the network (e.g. confirm/reject a transaction or sign a message) we already check the Network and offer to switch to the proper one if needed (based on the assets/network they want to use).

That's actually a very good point, the only time we actually need the wallet to be on the right chain is when broadcasting a Tx, and we actually prompt users to switch to the wallet of said transaction before doing so, so that would both be easier to implement and be less disruptive for users.

Other than at Tx broadcast time, the app still works with all the data "read-only" as we're effectively just querying blockchain data from unchained / making JSON-RPC calls with the right chain-adapter for x data.

@shapeshift/product WDYT?

**Comment by DiggyDiggy2** [comment]
Thought about this over the weekend, and I don't see any UX pain points that @firebomb1's solution would bring up. Agreed, it's a better approach. Thank you!
