### ISSUE TITLE
DeFi opportunities - ETH/FOX LP

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#2609]
### Overview

ETH/FOX LP requires account selection - @gomesalexandre you know what to do.

### References and additional details

.

### Acceptance Criteria

.

### Estimated effort

1 day

**Comment by gomesalexandre** [comment]
Partially blocked by https://github.com/shapeshift/web/issues/2598 - we cannot start adding account selection until the API of the multi account dropdown is finalized

**Comment by reallybeard** [comment]
Deposit
https://www.figma.com/proto/OHbVrAVaV2xQWUsq0nKzGm/ShapeShift-Library?node-id=1887%3A7497&scaling=min-zoom&page-id=156%3A3155&starting-point-node-id=1168%3A4238&show-proto-sidebar=1
Note: these accounts will need to be synced -- as you can't deposit from two different accounts.
