### ISSUE TITLE
DeFi opportunites - FOX farming

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#2610]
### Overview

FOX Farming requires account selection - users may have LP tokens on multiple wallets. @gomesalexandre you know what to do.

### References and additional details

.

### Acceptance Criteria

.

### Estimated effort

1 day

**Comment by gomesalexandre** [comment]
Partially blocked by https://github.com/shapeshift/web/issues/2598 - we cannot start adding account selection until the API of the multi account dropdown is finalized

**Comment by reallybeard** [comment]
These should follow the new account pattern we have established.

On the overview screen, the AccountSelector will be used in place of the provider string. To allow the user to change which account they are looking at.
![Screen Shot 2022-09-01 at 9 13 52 AM](https://user-images.githubusercontent.com/89934888/187935955-62537977-a63a-48e0-8639-fbc97d5b38eb.png)

On the deposit/withdraw and anywhere we use the AssetInput it should also have an account dropdown as a child.
![Screen Shot 2022-09-01 at 9 13 57 AM](https://user-images.githubusercontent.com/89934888/187936125-75deac40-484f-4b00-acd8-4cba38f51547.png)
