### ISSUE TITLE
DeFi opportunities - FOXy

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#2611]
### Overview

FOXy implementation of defi opportunities needs to support account selection.

### References and additional details

* https://github.com/shapeshift/web/blob/develop/src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx#L91

### Acceptance Criteria

* We can select an account before depositing or withdrawing
* The overview only shows balances for the selected account
* The selected account defaults to 0

### Screenshots/Mockups

implement account selection in here

<img width="506" alt="image" src="https://user-images.githubusercontent.com/88504456/187556043-9a02f9df-af3c-4cfc-a22b-a01587193216.png">

### Estimated effort

1 day

**Comment by reallybeard** [comment]
Same pattern as other singe sided staking screens
https://www.figma.com/proto/OHbVrAVaV2xQWUsq0nKzGm/ShapeShift-Library?node-id=1810%3A7391&scaling=min-zoom&page-id=156%3A3155&starting-point-node-id=1812%3A8350&show-proto-sidebar=1
