### ISSUE TITLE
Charts and recent transactions not loading in Portis due to litecoin & dogecoin xpub version issues

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2624]
### Overview

When selecting Portis as a wallet, the graphs do not load, neither do the recent transactions. 

### References and additional details

1) Open app.shapeshift.com and connect to Portis wallet
2) Notice Graphs do not load
3) Notice Recent Transactions do not load

*Defi looked at the issue and noticed it was to do with the litecoin & dogecoin xpub versions
![image](https://user-images.githubusercontent.com/100157997/187798787-269d0d1c-9907-49a9-bc47-add8d35d4986.png)
![image](https://user-images.githubusercontent.com/100157997/187799200-8b2510a8-01f2-4546-8a21-03403ff0ac3a.png)

### Acceptance Criteria

Graphs and recent transactions should load when connecting wallet

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
@0xdef1cafe

**Comment by 0xdef1cafe** [comment]
closing as portis is being deprecated
