### ISSUE TITLE
Rainbow chart turns off when navigating to a different page

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2640]
### Overview

After selecting rainbow charts on the dashboard then navigating to a different page and back to dashboard, the chart will default back to Total, opposed to Rainbow. 

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Toggle to rainbow charts on the dashboard
3) Navigate to a different page then back to dashboard
4) Notice the charts have reverted back to Totals

### Acceptance Criteria

When selected rainbow charts, it should remain on rainbows until changed back (or when re-connecting?)

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
closing as won't fix
