### ISSUE TITLE
"Keepkey Update Available" toast does not have a link to the updater app

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2676]
### Overview

When connecting a keepkey that needs an update, the toast has an option to select "Download update". However, if you select this is will take you to a Release link in Github and there is no clear way to get to the update.
Even if you check the version the keepkey is on in the drop down menu, the link takes you to the same Github release.

### References and additional details

1) Log into app.shapeshift and connect to keepkey.
2) Notice the blue toast saying "Keepkey Update Available".
3) Select "Download Update" from the toast and notice it takes you to Github and not the updater app
4) In the drop down menu showing the version the Keepkey is on, also notice the link takes you to Github - https://github.com/keepkey/keepkey-updater/releases/tag/v2.1.4
![image](https://user-images.githubusercontent.com/100157997/189021830-28017647-ba25-4a59-b88f-a9ce91b3b6cf.png)

### Acceptance Criteria

Ideally the toast/update link will take you to the place where you can update the kk easily

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
@pastaghost this is still happening. when selecting "Download Update" from the blue toast, it takes you to github and doesnt link to the updater firmware.

**Comment by wesleygravess** [comment]
Is there a way we can have the link in the toast go to a page that just has a button for windows and mac that downloads the most current updater.

currently it links to this page in github:
<img width="1238" alt="Screenshot 2023-01-23 155839" src="https://user-images.githubusercontent.com/99363597/214149601-92ad5f7d-c0c7-4517-92a7-5fd1dc27164f.png">

Some users are finding it hard to navigate github and it would be a better ux/ui imo as well. 

<img width="638" alt="Screenshot 2023-01-23 160154" src="https://user-images.githubusercontent.com/99363597/214149720-41c9c1c9-8453-45c8-bb64-c7d26467b464.png">

**Comment by wesleygravess** [comment]
@shapeshift/product if this pertains to you

**Comment by 0xdef1cafe** [comment]
closing as stale
