### ISSUE TITLE
Blue "KeepKey Update Available" toast stays on screen even when not connected to KeepKey wallet.

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2677]
### Overview

The blue update available toast for keepkey remains on screen unless you 'x' out of it, even if you are connected to a different wallet.

### References and additional details

1) Log into app.shapeshift and connect to KeepKey
2) Notice the blue toast appear saying "KeepKey Update Available"
3) Disconnect from KeepKey and notice the toast remains on the main landing page.
4) Connect to any other wallet and notice the blue toast remains on screen until you 'x' it.
![image](https://user-images.githubusercontent.com/100157997/189023074-18cb2d74-41f8-46a3-96cd-806c9db36345.png)

![image](https://user-images.githubusercontent.com/100157997/189023415-62014104-e77c-409c-9ef7-47af2214c7ec.png)

### Acceptance Criteria

Keepkey toasts should disappear once disconnected from Keepkey wallet

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by DiggyDiggy2** [comment]
agreed. the Toast should auto-close if the user has not closed it, when they wallet is switched or disconnected.

**Comment by MBMaria** [comment]
Just pinging this one @pastaghost as its still happening. just got it again today when switching from KK to native, the KeepKey Update Available toast remains on screen.
