### ISSUE TITLE
Side menu in Mobile App not retracking after selecting a page to navigate to 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2683]
### Overview

When selecting a page from the side menu in the Mobile App, the page will load in the background but the menu will stay open until you click onto the page behind. Intuitively the menu should retract after selecting a page to navigate to. 

### References and additional details

1) Open ShapeShift Mobile App.
2) Select the menu option at the top left of the screen and notice the menu pop out
3) Select a page to navigate to, ie. Transaction History 
4) Notice the Transaction History load in the background but the menu is still displayed
![image](https://user-images.githubusercontent.com/100157997/189221232-2e39cd0e-05e0-4100-b645-b6282342e941.png)

### Acceptance Criteria

Ideally the menu will retract after selecting a page to navigate to 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
@DiggyDiggy2 - just wanted to make sure you saw this one as well

**Comment by 0xdef1cafe** [comment]
closing as fixed
