### ISSUE TITLE
Add meta mask snap install modal prompt

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#2711]
Add a modal that prompts the user to install the meta mask snap to interact with all the chains. Possibly include a little how-to video on top of this modal so a user can preview it.

Below the video and description a CTA that says "Install Snap"

Allow the user to dismiss the modal, and to not remind them again.

**Comment by reallybeard** [comment]
https://www.figma.com/proto/OHbVrAVaV2xQWUsq0nKzGm/ShapeShift-Library?node-id=2205%3A7602&scaling=min-zoom&page-id=175%3A1479&starting-point-node-id=2205%3A7602&show-proto-sidebar=1

1. Copy may change
2. If you hover over the icons of the chains, you'll see a tooltip with the name of the chain
3. Once the user clicks "add" the button should go into a loading state, and disable all other buttons.
4. Once we've detected the snap is enabled, close the modal and show a success toast.

**Comment by twblack88** [comment]
Shipped 🔥
