### ISSUE TITLE
Add modal to prompt user to re-enable disabled snap

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#2713]
When a user has the SNAP installed, but disabled. We need to prompt them to re-enable it when trying to send or receive the other chains.

Or -- we fire off a toast when we detect that they have the snap installed but disabled.

**Comment by reallybeard** [comment]
https://www.figma.com/proto/OHbVrAVaV2xQWUsq0nKzGm/ShapeShift-Library?node-id=2214%3A7629&scaling=min-zoom&page-id=175%3A1479&starting-point-node-id=178%3A2367&show-proto-sidebar=1

- Learn more link should link out to a help article, that shows how to re-enable in metamask since we can't take them directly to it.

**Comment by twblack88** [comment]
Shipped 🔥
