### ISSUE TITLE
WalletConnect pairing fails from Demo Wallet CTA

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#2714]
### Overview

On a mobile web browser (tested with Chrome on IOS)
- Open app and select demo wallet
- then click connect header, pair with wallet connect and metamask app
- back in app it will show you a toast icon saying an error has occurred.
- if you attempt to go to accounts, its a black screen of death.

Attempting the same flow from the initial pairing prompt works as expected (most of the time)

### References and additional details

NA

### Acceptance Criteria

- pairing flow from Demo Wallet works like any other flow

**Comment by 0xean** [comment]
A refresh seems to solve this

**Comment by 0xdef1cafe** [comment]
@asamere @0xean is this still valid?

**Comment by 0xean** [comment]
i just tried in production and it worked as expected.
