### ISSUE TITLE
asset balance doesn't update on a receive*

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#2716]
1. Android app
2. Sent myself ATOM to native wallet
3. ATOM never appeared even after transaction confirmed 5+ minutes
4. Force quitting and re-launched the app for the ATOM to appear. 
5. I kept trying to pull to refresh...but no such thing in the app.

*Note: Still waiting on ops to recreate this one

**Comment by 0xdef1cafe** [comment]
closing as sporadic websocket issues
