### ISSUE TITLE
Some ATOM staking amounts failing

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2721]
### Overview

When trying to stake certain amounts of ATOM, the transaction is failing. 

### References and additional details

1) Log into app.shapeshift.com
2) Connect to wallet that supports atom staking
3) Navigate to DeFi page and select the ShapeShift Dao Atom staking card
4) Select deposit tab and enter $3 or $4 to deposit.
5) Select Continue and then Sign and Broadcast. 
6) Notice a yellow toast appears saying Transaction Failed as well as the Stake Modal spins indefinitely saying Transaction Pending
![image](https://user-images.githubusercontent.com/100157997/189771285-40807737-02fe-49ea-b076-92524e1a7306.png)
![image](https://user-images.githubusercontent.com/100157997/189771297-79388abb-294d-4f57-bd37-2eed846f271a.png)

### Acceptance Criteria

Should not have transactions failing for certain amounts of atom. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
closing as this has been completely rewritten since then. @MBMaria plz reopen if this is still a valid bug
