### ISSUE TITLE
Flags on Native wallet causing it to crash

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2724]
### Overview

When selecting some of the feature flags on native wallet it causes a black screen to appear, alternatively it just loads the dashboard for ever.
Flags that are causing a black screen: ThorChain and Osmosis. 
Flags causing the dashboard to load indefinitely: Multi-Account, LP and Fox Farming. (Still is also happening on MM for these flags)

Noticed that if you turn the flag on in KK that you can then switch to native and it will stay on and not cause the screen to crash.

### References and additional details

1) Log into release.shapeshift and connect to Native wallet
2) Turn on the feature flag of either Omsosis or ThorChain and notice the screen goes black
3) Refresh and turn on mutli account, LP or Fox Farming flag and notice after applying the flag the dashboard just keeps loading.
4) Switch to KK and turn on any of the flags
5) Switch back to native and notice behavior is as expected.

### Acceptance Criteria

Turning flags on should work as expected and not cause a black screen or have the dashboard load continuously.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
closing as we shouldn't be toggling flags at runtime, especially chain related flags, plz test environments per the built version
