### ISSUE TITLE
Unable to Claim Fox 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2725]
### Overview

Currently unable to claim fox from Fox Yieldy

### References and additional details

1) Log into app.shapeshift and connect to a wallet that has staked fox
2) Navigate to the defi page and select the Fox Staking Token card. 
3) In the Overview Modal select "Claim"
4) Notice the Claim modal pops up but it never allows you to confirm the transaction
![image](https://user-images.githubusercontent.com/100157997/189794183-2abb6aa8-86b1-4d65-99a8-da1a2cec5fc9.png)
 

### Acceptance Criteria

Should be able to claim fox as soon as it is available

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria This should have been solved by https://github.com/shapeshift/web/pull/2720 which went into release - can you confirm?

**Comment by MBMaria** [comment]
@gomesalexandre  i tried post release and it wouldn't let me but I've just jumped on mobile now and it's come up as able to claim on MM browser. I'll be able to check better when I'm on my laptop in the morning tho.

**Comment by MBMaria** [comment]
@gomesalexandre looks like i can claim fox no worries. release did indeed fix it :) sorry about the unnecessary ticket!

**Comment by MBMaria** [comment]
@0xApotheosis  this ticket looks like it captures the foxy not being able to be claimed and is still open

**Comment by 0xdef1cafe** [comment]
@MBMaria still valid?

**Comment by MBMaria** [comment]
Just tried now but it failed. Connectivity with api has been dodgey this avo tho. I can try again tomorrow. 
![image](https://user-images.githubusercontent.com/100157997/217420823-72dceb1b-794d-467b-834f-1a1867facc18.png)
![image](https://user-images.githubusercontent.com/100157997/217420864-30fa28d4-c9ed-4030-badd-919c0a66771b.png)

**Comment by gomesalexandre** [comment]
@MBMaria is this still valid? Can we retest after the bunch of FOXy PRs go in?

**Comment by MBMaria** [comment]
I no longer have fox to claim so im assuming its working again now. will wait until i complete another claim before i close this ticket tho.

**Comment by DiggyDiggy2** [comment]
This works for me with Native wallet. I think that the "Transaction failed" message occurs when there's not enough ETH for gas, in which case, we just need to update the error message.  @gomesalexandre do you want me to create a separate ticket for that and close this one?

**Comment by gomesalexandre** [comment]
> This works for me with Native wallet. I think that the "Transaction failed" message occurs when there's not enough ETH for gas, in which case, we just need to update the error message. @gomesalexandre do you want me to create a separate ticket for that and close this one?

Yeah let's create an issue when we know how to proper repro this, ty! I'll tackle it
