### ISSUE TITLE
DeFi opportunities - Multi-account improvements

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#2730]
### Overview

This issue is for improvements for DeFi opportunities following the work on https://github.com/shapeshift/web/pull/2728 which does multi-account selection with actual multiple accounts, and a full implementation including displaying the information for the currently selected account.

### References and additional details

- https://github.com/shapeshift/web/pull/2728 for a base implementation
- KeepKey can be used to derive multi-accounts for Ethereum accounts

### Acceptance Criteria

Across FOXy, FOX/ETH LP/Farming and Yearn:

- Ensure accountId is passed over from one modal step (overview to deposit/withdraw/claim) to another, as well as internal steps of deposit/confirm/withdraw/claim
- Implement the logic to display the information (available to stake, staked, account balance etc) for each account
- Remove occurrences of `adapter.getBip44Params()` in favor of using selectors

**Comment by 0xdef1cafe** [comment]
closing as too vague/noisy
