### ISSUE TITLE
QR scanner leaves webcam light on and indicator in tab bar after being closed in app

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#2738]
Web Camera indication light being on after scanning a qr code and closing the qr scanner window, but remaining on app.shapeshift.com.

1. connect to app.shapeshift.com with any wallet.
2. go to an asset page and select send asset.
3. click the QR scanner and close out or scan a qr code.
4. notice the web camera light is still on, and the recording notification on the tab at the top is still on as well.

![image](https://user-images.githubusercontent.com/94986227/190023376-3ffe1e7c-2be5-41c6-b1d4-ef7f9306438c.png)

**Comment by gomesalexandre** [comment]
Reference for bounty hunters:

https://github.com/shapeshift/web/blob/47c64e5d7ce4d4702dacac14e61e949aac5415b7/src/components/Modals/Send/views/QrCodeReader.tsx#L66 properly clears the canvas, but we will need to first stop scanning before clearing it.

See `html5-qrcode` documentation for details https://github.com/mebjas/html5-qrcode#stop-scanning, this might be a one-liner.

**Comment by NeOMakinG** [comment]
I'll get a look
