### ISSUE TITLE
QR scanner not populating address in Send Modal

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2739]
### Overview

When trying to scan a QR code for a send on mobile, or on web, in release.shapeshift.com the address does not populate in the send modal. However, if you select next, the transaction will build with the address from the QR code.
Release: https://github.com/shapeshift/web/pull/2733

### References and additional details

1) log into release.shapeshift.com on mobile or web and connect to wallet of choice
2) Select an asset and hit the send button
3) Select the QR scanner option and allow the site to access camera
4) Scan the QR code of an acceptable wallet address
5) Notice the address does not show in the send modal
6) Select Next and notice the transaction build with the address of the QR code

### Acceptance Criteria

Address should populate in send modal after QR code has been scanned

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
https://github.com/shapeshift/web/blob/develop/src/components/Modals/Send/views/Address.tsx#L45

this effect is causing it

the problem is the cosmos send and regular send forms are different

regular send uses the `Input` field and sets `Address` and `VanityAddress` via validation

cosmos just uses `Address`
