### ISSUE TITLE
ATOM claims showing up as 'Transaction' in TX History for additional ATOM accounts

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2759]
### Overview

When viewing Atom Claims for any Account other than Account#0, they appear as a Transaction in the TX history, instead of 'Receive' 

### References and additional details

1) Log into release.shapeshift and connect to native or kk
2) Turn the mutli-account flag on
3) Complete an ATOM claim on an Account other than #0
4) Notice the TX history lists it as a "Transaction" 
5) Select TX history for Account#0 and notice claims are listed as a Receive and not Transaction
![image](https://user-images.githubusercontent.com/100157997/190302907-7be4a302-a150-4758-8864-c83ab7ef68df.png)

### Acceptance Criteria

Atom claims should be listed the same for all accounts in the tx history

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
@MBMaria this can be closed yeah? plz reopen if still an issue
