### ISSUE TITLE
Add error handling and validation to `SwapperV2`

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#2790]
### Overview

Use native react hook form functionality to implement form validation and error handling.

### References and additional details

- Minimum trade amounts
- Insufficient balance
- No receive address

etc

### Acceptance Criteria

Architected using native react hook form, catches all major validation and error states.

**Comment by DiggyDiggy2** [comment]
when the widget is getting rates - the "Preview Trade" button should be faded
