### ISSUE TITLE
Yearn Contract Approvals Failing

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#2807]
### Overview

Currently, users of app.shapeshift.com are unable to approve yearn contract deposits. The error it's spitting out is "logger.ts:52 🚫 error: [App:YearnDeposit:Approve]Error [Kind: undefined] bip44Params required for signAndBroadcast  
Object
error
: 
Error: bip44Params required for signAndBroadcast at e.<anonymous> (https://release.shapeshift.com/static/js/10.f7663aa5.js:1:296861) at f (https://release.shapeshift.com/static/js/3.a6fa026e.js:2:1291959) at Generator._invoke (https://release.shapeshift.com/static/js/3.a6fa026e.js:2:1291712) at Generator.next (https://release.shapeshift.com/static/js/3.a6fa026e.js:2:1292322) at t (https://release.shapeshift.com/static/js/3.a6fa026e.js:2:1283013) at s (https://release.shapeshift.com/static/js/3.a6fa026e.js:2:1283224) at https://release.shapeshift.com/static/js/3.a6fa026e.js:2:1283283 at new Promise (<anonymous>) at e.<anonymous> (https://release.shapeshift.com/static/js/3.a6fa026e.js:2:1283164) at e.<anonymous> (https://release.shapeshift.com/static/js/10.f7663aa5.js:1:297934)
fn
: 
"handleApprove"
message
: 
"Error getting approval gas estimate"
namespace
: 
"App:YearnDeposit:Approve"
status
: 
"error"
timestamp
: 
"2022-09-20T20:05:16.724Z"
[[Prototype]]
: 
Object

### References and additional details

![Screenshot 2022-09-20 140646](https://user-images.githubusercontent.com/94189400/191359582-a5b613ab-e0f6-4bb3-acd3-7961a8475c58.png)

### Acceptance Criteria

Users should be able to approve yearn contracts

**Comment by gomesalexandre** [comment]
@tshifty I've tested this one in latest develop and approval Txs for Yearn deposit get properly built, both with the multi account flag on and off:

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/17035424/191603779-a32fb8f8-2614-43df-913a-f3201ebc89b5.png">

Can you confirm if this is still happening in current release ?

**Comment by tshifty** [comment]
Issue has been fixed
