### ISSUE TITLE
mock metamask in web tests

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#282]
walletprovider is spewing to the console in the tests and shouldn't be doing this.

bonus point if you enforce unhandled promise rejections in the test config and fix those tests too

**Comment by jdambron** [comment]
@0xdef1cafe Mocked metamask and did a little bonus (handle properly console errors in `useNativeSucess` test)
For the  unhandled promise rejections I might have a look if I have spare time, but will do in a distinct PR if that's the case.
