### ISSUE TITLE
FOX Yieldy withdrawal Approval not working on multi account

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2820]
### Overview

When attempting to withdraw a FOX Yielding the Approval is failing on a new account. 

### References and additional details

1) Log into release.shapeshift.com and connect to native.
2) Turn on multi-account flag and add ETH account.
3) From the Defi page, select the FOX token staking card and from the overview modal make sure you have account#1 selected.
4) Select Withdraw and enter amount to withdraw.
5) Select Continue and wait for the Approve screen to appear.
6) Select Confirm to allow the Approval.
7) Notice the Transaction Failed toast appear.
![image](https://user-images.githubusercontent.com/100157997/191628417-c01a8bc2-5e5f-487d-9275-020e42bf09c2.png)
![image](https://user-images.githubusercontent.com/100157997/191628450-a89bf4f2-d3d9-4978-839d-7bb6eb214aca.png)

### Acceptance Criteria

Approval should confirm to allow the withdrawal

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
closing as stale, this has been rewritten since then
