### ISSUE TITLE
Handle factory-new KeepKey Connections

### ISSUE THREAD

**Issue by BitHighlander** [shapeshift/web#2821]
### Overview

Upon connecting a factory-new KeepKey device to the ShapeShift web app, the user encounters the following error:

<img width="1254" alt="Screen Shot 2022-09-21 at 6 16 28 PM" src="https://user-images.githubusercontent.com/4935895/191631860-0541c670-1473-48d8-a08d-1f2cbb2f3ecf.png">

### References and additional details

beta.shapeshift handles this error with the following window:
<img width="1254" alt="Screen Shot 2022-09-21 at 6 18 50 PM" src="https://user-images.githubusercontent.com/4935895/191632004-5023a7aa-99ed-4e89-b91e-df4dc83a3037.png">

auto detected OS

<img width="1254" alt="Screen Shot 2022-09-21 at 6 20 11 PM" src="https://user-images.githubusercontent.com/4935895/191632135-2fca2e39-d69f-495f-9182-161ca93c86ac.png">

updater app download url
https://github.com/keepkey/keepkey-updater/releases/latest

### Acceptance Criteria

Handle an OOB (out of box) KeepKey and display to the user a prompt allowing them to download the KeepKey updater app and prompt for the detected OS.

### Estimated effort

1 day

**Comment by 0xdef1cafe** [comment]
@BitHighlander @pastaghost FYI

**Comment by brymut** [comment]
@0xdef1cafe what went wrong specifically? It was tested out by  @BitHighlander and I and it worked
