### ISSUE TITLE
Protocol fee doesn't always show up in all the places in the trade confirmation widget

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2823]
### Overview

When completing a non 0x trade, the protocol fee doesn't always populate in the "expected amount" drop down list. The protocol fee is shown at the bottom of the widget but not always in the mid section. Sometimes it shows in the drop down menu but more often than not, it is not there.

### References and additional details

1) Log into app.shapeshift and connect to mm/kk/native
2) In the trade widget proceed to create a non 0x trade and 'Preview Trade'
3) Notice the protocol fee at the bottom of the widget.
4) Drop down the menu in the Expected Amount and notice the protocol fee often states it being 0.00 even tho it shows a fee for this at the bottom of the widget. 
![Uploading image.png…]()

### Acceptance Criteria

If there is a protocol fee, the fee amount should be shown in all places it is listed 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
Closed by https://github.com/shapeshift/web/pull/2881.

CowSwap had special logic to show protocol fees, but now we've made this generic and the fee shows up in the receive amounts component.
