### ISSUE TITLE
'Manage' button hidden in some places on Fox Opportunities page on mobile/mobile app

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2834]
### Overview

When viewing the Fox Opportunities page, in both web on mobile and in the mobile app, the 'Manage' button is hidden next to the Farming and Liquidity Pools sections.

### References and additional details

1) Log into app.shapeshift on mobile or open the mobile app and connect to wallet of choice
2) Navigate to the Fox Opportunities page and notice next to the Farming and Liquidity Pools section it lists the opportunities but there is no 'Manage' button along side it.
![image](https://user-images.githubusercontent.com/100157997/191854396-76c7645b-a907-4db9-a9bf-3cf043b20395.png)

### Acceptance Criteria

Should be able to access these opportunities from this page

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by reallybeard** [comment]
Looks like we need don't have the entire row as a button to launch the opportunity.

On mobile the manage buttons will be hidden, so the entire row should be a button.
