### ISSUE TITLE
New wallet on mobile app importing transactions from other wallets after switching between wallets

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2839]
### Overview

After creating a new wallet on the Mobile App, if you switch to a different wallet that has a balance and transaction history, once switching back to the fresh wallet, it will bring across a small balance, which will go down to zero after a couple seconds, and will also bring across and keep previous transaction history. If you do a transaction in the new wallet, then disconnect and reconnect, the old transactions will disappear and only the relevant one(s) to the new wallet will remain. 
Release: https://github.com/shapeshift/web/pull/2837

### References and additional details

1) Open Mobile App and create new wallet
2) Notice on initial load there is a zero balance and no transaction history
3) Switch to a wallet that has a balance and recent transactions
4) Switch back to the new wallet and notice a small balance (which will decrease to 0) and transaction history.
5) Complete a transaction in the new wallet
6) Disconnect wallet and reconnect
7) Notice the correct balance and correct transaction history.

### Acceptance Criteria

New wallet should not have balance or tx history from other wallets after switch between wallets.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
@MBMaria plz reopen if this is still valid, but i think we'd be hearing about this a lot if it were

**Comment by MBMaria** [comment]
yup this is no longer an issue. tx's not importing across new wallets
