### ISSUE TITLE
Add a tooltip when there's no rate available

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#2851]
### Overview

When there’s no rate available on a trade pair, add a tooltip on “no rate available”.

The tooltip will copy is: "This is often due to very limited or no liquidity on the trade pair."

### References and additional details

You can see this error when picking some really unknown erc-20 and trying to trade to a more popular asset.

### Acceptance Criteria

User sees a tooltip option whenever they see the "no rate available" trade error.

**Comment by 0xApotheosis** [comment]
Closed by https://github.com/shapeshift/web/pull/2789/commits/359a459e80927dfbbaf4e46ae0d73cb1d43e0434
