### ISSUE TITLE
Error handling when an asset in the trade is not supported in the wallet

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#2852]
### Overview

In the case that a user sets up a trade with an asset not supported by their wallet, we still want to fetch the rate.
In this case, fetch the rate, but update the button copy to "[SYMBOL] not supported by wallet".

This way the user will understand why they cannot make the trade.

### References and additional details

You can see this occur now, if you try to set up a trade BTC > ETH with Metamask connected. It doesnt fetch the rate and the error on the button is not clear.

### Acceptance Criteria

1. No matter what assets a wallet supports, users should be able to explore rates across trade pairs.

2 .The button should be faded out with "[SYMBOL] not supported by wallet"

**Comment by 0xApotheosis** [comment]
Part 2 of this will be completed in https://github.com/shapeshift/web/pull/2789.

For part 1, quote requests require send and receive addresses, so we need to think through how we handle that - maybe we provide a dummy address for the corresponding chain.
