### ISSUE TITLE
USDT (Wormhole assets) not properly labeled

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#2853]
### Overview

When selecting USDT - the first two assets that appear do not seem to be properly labeled. Its likely they are Tether USD Wormhole assets (Solana and Binance)
https://cdn.discordapp.com/attachments/915663891005067294/1022920533723062272/unknown.png

### References and additional details

This is worrying, as a user might accidentally trade for the wrong "USDT" since their symbols are almost identical to the original and the labels do not reflect differences.

* override the name to include "Wormhole" or similar here https://github.com/shapeshift/lib/blob/main/packages/asset-service/src/generateAssetData/overrides.json#L2

### Acceptance Criteria

Define a format for wormhole assets, which will probably need to include the wormhole chain, and the text "wormhole" for clarity on these asset types

### Screenshots/Mockups

note the third USDT is the asset we really want to be swapping to, the first and second assets should be labelled accordingly

<img width="390" alt="image" src="https://user-images.githubusercontent.com/88504456/194163851-dd5e259c-603d-4e9f-909a-5aa436301b05.png">

### Estimated effort

2 hours

**Comment by MBMaria** [comment]
@0xdef1cafe do we have an amount and expected hours for this bounty?

**Comment by crowicked** [comment]
Hello, first time looking at Shapeshift code so be gentle :) A bit confused with the suggested solution to override...

I did some code spelunking, seems like WH assets from Coingecko should be excluded from the list anyways, but the exclusion is based on token name only, hence `USDTso` & `USDTbs` showing up: [see](https://github.com/shapeshift/lib/blob/1f5af2acabb9dfc04cd203d98a33f6c9c051514c/packages/asset-service/src/generateAssetData/coingecko.ts#L51)

Maybe we can use some other data/endpoint from CG to properly identify wormhole assets, as opposed to manually adding overrides?
![image](https://user-images.githubusercontent.com/48219654/195220099-a17e4532-6112-4500-b9b0-691e9804dfee.png)

**Comment by crowicked** [comment]
Seems this endpoint returns something usable for this case?
![image](https://user-images.githubusercontent.com/48219654/195221984-1285da97-7a88-4fec-8d4b-21e30d649b53.png)

**Comment by crowicked** [comment]
PR created in `shapshift/lib`: https://github.com/shapeshift/lib/pull/1067
