### ISSUE TITLE
Trying to trade but a different network is selected

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#2854]
### Overview

1. I've got Avalanche as the active network 
2. I try to trade ETH to FOX (or whatever)
3. the button error shows "Insufficient funds" _ which is true because those funds are on another network. However, its a confusing user experience. 
4. Please have the button say "Switch Network To Trade"?

### References and additional details

This is easy to replicate using Metamask and the steps outlined above.

### Acceptance Criteria

When the user sets up a trade, but has the wrong network selected, the button should inform them to "Switch Network To Trade"

**Comment by 0xApotheosis** [comment]
No longer an issue, resolved in recent updates.

When selecting "Confirm and Trade" whilst on a different network MetaMask will ask the user to switch networks.
