### ISSUE TITLE
User unable to send DOGE on KK

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2870]
### Overview

User is trying to send Doge in app.shapeshift.com and encountered error while doing so. Last doge transaction user had was last August 22. Already provided basic TS steps and nothing worked.

### References and additional details

1. Connect KeepKey to app.shapeshift.com
2. Send DOGE

Discord conversation: https://discord.com/channels/554694662431178782/1024143911784038430

Have asked for console errors and will comment below when provided. 

Was unable to recreate on Chrome or Brave. 

### Acceptance Criteria

Doge sends should work across wallets and browsers

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
Update from user: 
"issue persists even when importing 12 words on app.ss"
![image](https://user-images.githubusercontent.com/100157997/192615274-4d036dad-e267-4889-a0fa-70a09b29e91a.png)

**Comment by wesleygravess** [comment]
I was unable to recreate. I was able to make a DOGE send from my kk

**Comment by MBMaria** [comment]
@pastaghost the user is still experiencing issues with a doge send on linus. any ideas what might the issue. I believe, the user said he doesnt have any issues with any other coins.

**Comment by 0xdef1cafe** [comment]
closing as stale
