### ISSUE TITLE
Coinstack failure tolerance - persistent notification

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#2883]
### Overview

If we're dealing with a persistent failure, e.g. a coinstack is completely down, we want a way to display a persistent notification, e.g. a banner, to inform the user that the app is likely to be in a degraded state and things may not work as expected.

Requires

https://github.com/shapeshift/web/issues/2575
https://github.com/shapeshift/web/issues/2882

### References and additional details

Up to @shapeshift/product - but we can either have a single persistent notification (e.g. a banner), or small discrete notifications where things may be affected (most features - charts, asset/account pages, swapping, defi, send).

### Acceptance Criteria

It looks/feels however product decides.

### Estimated effort

1 day

**Comment by DiggyDiggy2** [comment]
https://cdn.discordapp.com/attachments/964289350013681725/1024389402836873276/Screen_Shot_2022-09-27_at_1.37.41_PM.png
