### ISSUE TITLE
"Not enough ETH for gas" error NOT showing for trades with multi account and thorswap flags on

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2894]
### Overview

When doing a trade on Swapper V2 with thorswap and multi account flags on, sometimes it will allow you to confirm and broadcast a transaction even if there isnt enough ETH to cover gas. Instead of giving the Not enough eth to cover gas error, it will act as if the trade is going to confirm, then the widget resets and you get a 'Something went wrong error' .

### References and additional details

1) Log into release.shapeshift.com and connect to native wallet
2) Turn on flags for thorswap and multi account. (At this stage of testing, cowswap was turned off and V2 swapper was turned on) ( Release: https://github.com/shapeshift/web/pull/2877)
3) In the trade widget create a 0x trade
4) Notice that you can enter an amount of eth that when you add the gas fee, will be greater than the balance on eth available
5) Select Confirm and Trade
6) Notice the tx appears as if it will complete but the modal wil then reset to $0.00 and a "Something went wrong" error appears.
![image](https://user-images.githubusercontent.com/100157997/192658278-64a83759-eaa2-48eb-b436-4f51f929f9f9.png)
![image](https://user-images.githubusercontent.com/100157997/192658283-361a413d-d6ac-46fc-8ae7-1fa90f0c6eb1.png)

### Acceptance Criteria

Not enough gas for eth error should appear and stop a trade from 'being confirmed' if there is not enough ETH

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
i'm going to remove this from the mobile migration milestone/label, as we're not shipping multi accounts as part of the mobile migration
