### ISSUE TITLE
Move unchained url to be a constant or env variable

### ISSUE THREAD

**Issue by bootsboogie** [shapeshift/web#29]
Do this ticket first https://github.com/shapeshift/web/issues/48

Also we should have it point at the production endpoint so people can just get it up and running with out the back end dependencies.

**Comment by 0xdef1cafe** [comment]
should this be a more general issue first - create configuration management strategy?

i've previously used this https://github.com/af/envalid#api

and typed it strongly - so you can import config and get a strongly typed object, and write custom regex validators etc.

**Comment by bootsboogie** [comment]
> should this be a more general issue first - create configuration management strategy?
> 
> i've previously used this https://github.com/af/envalid#api
> 
> and typed it strongly - so you can import config and get a strongly typed object, and write custom regex validators etc.

Yea I think that is a good idea we should figure out our strategy and then move the `unchainedUrl` into it. I have never used `envalid` but it sounds cool I like that it is strongly typed.

**Comment by 0xdef1cafe** [comment]
> > should this be a more general issue first - create configuration management strategy?
> > i've previously used this https://github.com/af/envalid#api
> > and typed it strongly - so you can import config and get a strongly typed object, and write custom regex validators etc.
> 
> Yea I think that is a good idea we should figure out our strategy and then move the `unchainedUrl` into it. I have never used `envalid` but it sounds cool I like that it is strongly typed.

Cool, I'm going to mark this as blocked and created this https://github.com/shapeshift/web/issues/48
