### ISSUE TITLE
Expected Amounts changing for Rune Thorswap trades 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2904]
### Overview

When executing a Rune Thorswap trade the estimated amount changes as you go through the flow of the trade. After selecting "Confirm and Trade" the Send amount and Expected amount roughly 10x.

### References and additional details

1) Log into app.shapeshift and connect to native
2) Turn Thorswap flag on
3) In the trade widget set up a trade into Rune.
4) Notice the estimated amount, then Preview Trade
5) Notice the estimated amount has changed, then select Confirm and Trade
6) Notice the estimated amount changes and the send amount has also changed (or the USD value of them)
![image](https://user-images.githubusercontent.com/100157997/192921711-3ede0bb0-eeaf-4866-acd9-f84f59024126.png)
![image](https://user-images.githubusercontent.com/100157997/192921721-44a51ab6-8747-40dc-9aca-0fc3903acecc.png)
![image](https://user-images.githubusercontent.com/100157997/192921732-dd143092-a16b-4238-b292-6871e82a3e3c.png)

### Acceptance Criteria

Estimated amount should be consistent and the usd value after broadcasting trade should not change

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Reopening as fees are still borked in RUNE swaps and the logic has tight coupling with this issue

**Comment by gomesalexandre** [comment]
Closed by #2881
