### ISSUE TITLE
Remove ETH.HEIGIC from THORChain trading

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2907]
### Overview

https://github.com/shapeshift/lib/blob/main/packages/caip/src/adapters/thortrading/index.ts#L13

ETH.HEIGIC is listed as one of the supported assets on our list for thorchain trading. However, it is not listed as a pool on the thorchain website: https://app.thoryield.com/pools

defi mentioned it should be removed form our list

### References and additional details

1. Go to: https://github.com/shapeshift/lib/blob/main/packages/caip/src/adapters/thortrading/index.ts#L13
2. notice the HEIGIC asset
3. Go to https://app.thoryield.com/pools
4. notice there is no HEIGIC pool

### Acceptance Criteria

ETH.HEIGIC should be removed from our list per defis request
Discord conversation:
https://discord.com/channels/554694662431178782/1022165573347577996/1025136455951056897

**Comment by 0xdef1cafe** [comment]
requires caip package bump with https://github.com/shapeshift/lib/pull/1044
