### ISSUE TITLE
THORChain halt flags

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#2925]
### Overview

If THORChain is halted upstream, we want to respect that and disable THORChain trading at runtime.

### References and additional details

* Check the `HALT*` flags here https://daemon.thorchain.shapeshift.com/lcd/thorchain/mimir
* Use an RTK query subscription with 60s check to retrieve this data
* Expose it via a hook, mapped to our assets (might need a CAIP adapter for this)

### Acceptance Criteria

* Disable THORChain trading if `HALTTRADING` is `1`
* Disable specific assets from trading based on the respective key/value pairs

### Estimated effort

1 day

**Comment by 0xApotheosis** [comment]
The second part of this AC was addressed in https://github.com/shapeshift/lib/pull/1080 in that we now won't return TX data or a quote if the `halted` flag is set on the inbound (receiving assets) address:

https://github.com/shapeshift/lib/blob/a4d6d6f36e1ad803a5328c0536701f142e2f97f2/packages/swapper/src/swappers/thorchain/utils/getInboundAddressDataForChain.ts#L16

**Comment by 0xdef1cafe** [comment]
closed by https://github.com/shapeshift/web/pull/3597
