### ISSUE TITLE
Trade source switching from 0x to Thorchain in trade confirmation screen

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2959]
### Overview

When completing a trade on MM or Tallyho, the trade builds as a 0x trade but after the trade is broadcast and confirmed, the screen switches to say the protocol used was Thorchain. It also jacks the Before Fee to much higher than displayed in the preview trade amount.

### References and additional details

1) Log into release.shapeshift.com and connect to MM or TallyHo! (For this testing, Thorswap flag is enabled by default. Release: https://github.com/shapeshift/web/pull/2954)
2) In the trade widget or on the trade page set up a trade
3) Notice the Before Fees look normal, as expected and the protocol states 0x
4) Confirm and Trade and notice the Protocol switches to Thorchain and the Before fees are much much higher. 
![image](https://user-images.githubusercontent.com/100157997/193723588-cc533cd6-3fbb-4eab-a454-3a87da71dd4e.png)
![image](https://user-images.githubusercontent.com/100157997/193723605-05f74a6b-c406-4671-934a-d3c443b6b3ff.png)

### Acceptance Criteria

Protocol should remain as 0x on MM and TallyHo, and the before fees should not change after the trade is broadcasted

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Might be a similar issue as https://github.com/shapeshift/web/pull/2921
