### ISSUE TITLE
Update swap expected amount to match the buy amount

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#2973]
### Overview

Right now the expected amount is pulling from the min amount expected with slippage. We would like it to match the amount in the buy field.

### References and additional details

For example
![Screen_Shot_2022-10-04_at_1 19 46_PM](https://user-images.githubusercontent.com/89934888/193896091-0ef8b528-c418-4f8d-9692-5c8f8b7ba384.png)

IN this screenshot the expected amount says `199.6 FOX` it should say `200 FOX` to match the amount in the buy field.

### Acceptance Criteria

The expected amount matches the buy amount field

**Comment by 0xApotheosis** [comment]
Already done 👌 

<img width="402" alt="Screen Shot 2022-10-14 at 12 06 31 pm" src="https://user-images.githubusercontent.com/97164662/195739064-eeb7771e-b176-4108-b4c1-be88c900d7ad.png">
