### ISSUE TITLE
Reprioritize swappers

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#2984]
### Overview

In lieu of `getBestSwapper` actually doing what it's name suggests, we rely on the order of the swappers instantiated in the swapper manager to get quotes.

We should order these in terms of the typically most favorable rates. THORChain is not ideal for most ERC20 swaps, as two fees are effectively paid, and should be deprioritized.

This is likely 0x, CoWSwap, THORChain.

### References and additional details

* https://github.com/shapeshift/web/blob/release/src/components/Trade/hooks/useSwapper/swapperManager.ts#L34

### Acceptance Criteria

We decide on the ideal order of swappers.

**Comment by willyogo** [comment]
noice.

does cowswap being off screw with stuff?
if not, i'd say 
1. cowswap 2. 0x 3. thorchain
if so, LGTM :metal:
