### ISSUE TITLE
Default state on trade should show placeholder text

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#3032]
### Overview

When the trade widget/page is first loaded it currently shows `0` it should instead show placeholder text `0.00` or `$0.00` if in fiat.

### References and additional details

This is for the trade component

### Acceptance Criteria

Show the placeholder value until the user has input a value or hit max button.

### Screenshots/Mockups

![Screen Shot 2022-10-11 at 10 17 29 AM](https://user-images.githubusercontent.com/89934888/195131951-cd5cbc2c-9ca3-4813-a69b-fb23b821446b.png)
![Screen Shot 2022-10-11 at 10 17 36 AM](https://user-images.githubusercontent.com/89934888/195131956-97290522-1aad-429b-b8d7-40bafebbef08.png)

**Comment by DiggyDiggy2** [comment]
We've had no complaints about this and the UX is fine when testing. Closing
