### ISSUE TITLE
Transaction History filter button not clearing search bar

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3038]
### Overview

When searching in the transaction history, the 'x' next to the filters only clears filters that are selected, it doesn't clear the search bar.

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to the Transaction History page 
3) In the search bar, type in something to search
4) Try select the 'x' next to the filter and notice you cannot select it.
![image](https://user-images.githubusercontent.com/100157997/195196923-936ab933-95e3-4a9d-a72c-6637822786d6.png)

### Acceptance Criteria

'x' could clear the filters as well as the search bar

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by DiggyDiggy2** [comment]
I'm assigning to @reallybeard to see if he can tackle this one
