### ISSUE TITLE
Add the "get the app" banners to our mobile website

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3045]
### Overview

We want to add the banners for android and iOS mobile website users that prompt to get the mobile application.

### References and additional details

how to for iOS:
https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners

how to for Android:
https://developer.chrome.com/blog/app-install-banners-native/

### Acceptance Criteria

mobile website users see the banner to get the app

**Comment by DiggyDiggy2** [comment]
@reallybeard - Defi thinks you can probably tackle this one. LMK

**Comment by 0xdef1cafe** [comment]
closing as stale
