### ISSUE TITLE
Improve error message on defi protocols, when the user doesn't have enough ETH

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3059]
### Overview

1. If a user is depositing into a Defi position, and they don't have enough ETH to cover gas, the error message is not very helpful
2. Instead of showing "transaction failed" - we should show "Not enough ETH to cover gas"

### References and additional details

1. Go to stake FOX (into FOXy) on an account with only FOX and very little or no Ethereum
2. Notice that on the approval step, the transaction simply fails but as a user, its not clear why.
3. We need to change the error message

![Screen Shot 2022-10-13 at 1 46 12 PM](https://user-images.githubusercontent.com/90058616/195696198-33c36ecb-444a-46bb-9ab5-e7bbc61169bb.png)

### Acceptance Criteria

As a user, when i'm depositing into a protocol/staking etc, and I don't have enough ETH to cover gas, I should see an error message that says "Not enough ETH to cover gas"

**Comment by 0xdef1cafe** [comment]
closing as stale
