### ISSUE TITLE
Unable to get rates on trades when Native Rune is the sell asset

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3066]
### Overview

Able to get rates going into native Rune, but unable to get rates when attempting to trade out of native Rune.

This issue is on prod and release

### References and additional details

1. Set up a trade with Native Rune as the sell asset
2. Notice that no rate is available

### Acceptance Criteria

User should be able to get rates when swapping out of Native Rune

**Comment by 0xApotheosis** [comment]
Useful context: https://github.com/shapeshift/web/pull/3111#pullrequestreview-1149392066
