### ISSUE TITLE
Increase slippage on Thorchain swaps to avoid failures

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3069]
### Overview

From Orion at 9R:
The 0.2% slip is too tight of a tolerance for swaps with USDC - example of refunded tx: https://viewblock.io/thorchain/tx/35EBE5089D3090BB0068534CF493091658A25A95B4A5CF998C6DB854F8B79E85

Other integrations use much higher tolerance like 2-5%. We can consider allowing this to be higher, until we have trade settings.

Slip on TC is not static and is dependent on pool depths at the given point in time.

### References and additional details

n/a

### Acceptance Criteria

Swaps on Thorchain have slightly higher default slippage, to avoid failures

**Comment by 0xdef1cafe** [comment]
@asamere can you let us know an ideal % here for default slippage plz?

**Comment by 0xApotheosis** [comment]
We currently use 3% (the 0.2% shown in the UI visual-only): https://github.com/shapeshift/lib/blob/a643be3c74183d0c67100e6f288fc957db0cba45/packages/swapper/src/swappers/utils/constants.ts#L2

I've DMed Adam for a better percentage.

**Comment by asamere** [comment]
> We currently use 3% (the 0.2% shown in the UI visual-only): https://github.com/shapeshift/lib/blob/a643be3c74183d0c67100e6f288fc957db0cba45/packages/swapper/src/swappers/utils/constants.ts#L2
> 
> I've DMed Adam for a better percentage.

It's tough to say a specific percent to offset. if the input asset has a significant outbound fee for refunds I'd reduce the limit on the output asset to the equivalent cost of the refund (no point losing more money to get your funds back vs the trade completing). If the refund is cost is cheap (from rune for sure) you can run a much tighter limit as if it refunds you can just try again. Maybe pairing up for a bit would be a good idea.
