### ISSUE TITLE
Frame wallet users aren't able to access app (to even see its not supported)

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#3076]
### Overview

This was reported to me kind of tangentially so I don't have all the details, but a user who has Frame wallet, ended up in a state where the site opens mulitple metamask tabs.

### References and additional details

I don't have a ton of detail on how to reproduce besides this video.  

This also may be kind of an odd edge case to handle based on some reading on Frame. 

![Screen Shot 2022-10-17 at 6 40 56 AM](https://user-images.githubusercontent.com/15096737/196179471-f13fa980-eb1b-43bf-b34c-6c66ca603981.png)

Maybe we are blocking this interaction for security reasons, which may be good and we just need a better error message, IE another extension is attempting to act as metamask. 

### Acceptance Criteria

Wallets that are not support correctly tell the user in an error message vs opening multiple MM tabs 

https://user-images.githubusercontent.com/15096737/196179123-9093d0a4-3568-44d3-b853-d6e62c35b3e9.mov

**Comment by 0xean** [comment]
Injecting Frame as Metamask seems to solve this in the browser extension. 
![Screenshot 2022-11-29 at 6 26 06 AM](https://user-images.githubusercontent.com/15096737/204540854-11dc1383-4588-4988-ab68-bdbd90459f66.png)

**Comment by 0xdef1cafe** [comment]
closing as workaround, can confirm frame works via injecting as metamask
