### ISSUE TITLE
Foxy Vault Pending Withdraw Text 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#3100]
### Overview

After completing a withdraw of the foxy vault, the pending withdraw text in the modal doesn't load unless you refresh the page.

### References and additional details

1. go to app.shapeshift.com
2. log in with a wallet 
3. go to the defi page 
4. click on the foxy vault and complete a withdraw 
5. notice the pending withdraw in the modal doesn't show up without a refresh

### Acceptance Criteria

The pending withdraw should show up in the modal after you broadcast the tx

### Screenshots/Mockups

After a refresh:
<img width="461" alt="Screen Shot 2022-10-19 at 2 10 37 PM" src="https://user-images.githubusercontent.com/99363597/196771310-e683ebe8-1f17-47de-9fd3-808c0d678f03.png">

**Comment by 0xdef1cafe** [comment]
closing as stale/low pri
