### ISSUE TITLE
Account selection for Fox Farming and LPs glitchy when more than two accounts

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3103]
### Overview

If there are more than two Eth accounts, when trying to select a different account in the Fox Farming or ETH/FOX LP, the drop down menu goes glitchy and makes it hard to select an account. 

### References and additional details

1) Log into release.shapeshift.com and connect to wallet that supports multi account (testing on Release 1.117.0, PR: https://github.com/shapeshift/web/pull/2481)
2) In the Accounts page, add 2x ETH accounts
3) Navigate to Defi page and select the Fox Farming or LP card
4) Select deposit or withdraw and try to select a different account. 
5) Notice the drop down menu moves around and makes it hard to select a different account.

https://user-images.githubusercontent.com/100157997/196812110-5d77b8ef-5523-4b78-ac24-f6c7576e7b86.mp4

### Acceptance Criteria

Accounts should be easy to select from drop down menu

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
@MBMaria this still valid?

**Comment by MBMaria** [comment]
This has been fixed now @0xdef1cafe . no longer glitching
