### ISSUE TITLE
KeepKey Passphrase button copy change

### ISSUE THREAD

**Issue by notatooyou** [shapeshift/web#311]
To repro:
1. connect a KeepKey with a passphrase
2. enter the correct pin
3. see the below pop-up 
 
Screen shot attached. The blue button says "Set Passphrase". In this flow, I am only entering the passphrase to connect my wallet. So, this button would more appropriately say "Submit Passphrase" or something like that. Yes?

<img width="433" alt="Screen Shot 2021-11-08 at 2 45 28 PM" src="https://user-images.githubusercontent.com/89656210/140823796-a34180fb-a3da-43cc-8853-3b1ab942b94f.png">

**Comment by notatooyou** [comment]
<img width="433" alt="Screen Shot 2021-11-08 at 2 45 28 PM" src="https://user-images.githubusercontent.com/89656210/140823722-3640bfac-0969-4de3-ad98-0e102a591c92.png">

**Comment by cjthompson** [comment]
I put that language in because it's setting the passphrase on the device for that session. Passphrases aren't persisted between sessions (device plug/unplug) so it must be set each time.

Axiom says "Continue".

The text for the button is in `messages-en.json` and can easily be changed.
