### ISSUE TITLE
Cowswap Trades not working on TallyHo!

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3131]
### Overview

When trying to complete a TallyHo! trade, the transaction fails when using Cowswap. When turning flag off, initial trade looks like its trying to use Cowswap but after selecting Preview Trade it shows correct figures and trade completes on 0x as expected.

### References and additional details

1) Log into app.shapeshift.com and connect to TallyHo!
2) Populate trade, select preview trade and then confirm and trade
3) Notice the trade fails with a Something went wrong error
4) Turn Cowswap flag off and replicate trade
5) Notice when initially populating trade, the fees look off
6) Preview trade and notice the fees look accurate
7) Confirm and Trade and note the trade executes as expected
![image](https://user-images.githubusercontent.com/100157997/197309677-6718c197-a34e-40b2-afcd-f71dd8521c4b.png)
![image](https://user-images.githubusercontent.com/100157997/197309685-b78a35f0-176c-4486-ba95-53beb824ed66.png)
![image](https://user-images.githubusercontent.com/100157997/197309691-7f4f7841-1e30-4936-88cf-d6b55f5df9a1.png)

### Acceptance Criteria

Trades should work without having to turn flags off

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
closed as tallyho has some green dream
