### ISSUE TITLE
Switching from Xdefi to TallyHo! doesnt always work

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3132]
### Overview

When trying to connect to TallyHo from Xdefi, it doesnt always connect

### References and additional details

1) Log into app.shapeshift.com and connect to xdefi
2) Make sure TallyHo is selected as default, refresh then switch to TallyHo.
3) Notice that the wallet gives an error about needing to be installed or selected as default. However, the wallet will load in the background.
4) Switch back to xdefi and back again to TallyHo
5) Notice that the wallet will now not connect. Need to disconnect, reselect TallyHo as default wallet and refresh and then it will connect.
![image](https://user-images.githubusercontent.com/100157997/197310020-24b8f1af-960c-4ceb-9a9b-bf6e5783aeba.png)
![image](https://user-images.githubusercontent.com/100157997/197310029-20035ce8-da64-447b-a924-cc3b5d9010f9.png)

### Acceptance Criteria

Switching between wallets should be unhindered

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
we euthanized tallyho, closing
