### ISSUE TITLE
Show underlying tokens on FOX Farming

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3144]
### Overview

We want to give users, who are FARMING FOX/ETH, the ability to see how much FOX/ETH make up their LP tokens on the overview. 

### References and additional details

Currently the overview on FOX Farming looks like this:
<img width="482" alt="Screen Shot 2022-10-24 at 3 48 42 PM" src="https://user-images.githubusercontent.com/90058616/197636228-3d87b853-9b0d-411f-b780-1c3e7eae29fc.png">

We'd like it to have an expansion ability on the LP token, like this:
<img width="431" alt="Screen Shot 2022-10-24 at 3 49 32 PM" src="https://user-images.githubusercontent.com/90058616/197636342-852f1fe0-1912-494a-9281-584676530aca.png">

### Acceptance Criteria

Users who are Farming can see the breakdown of the tokens in the liquidity pool (that make up their LP tokens)

**Comment by gomesalexandre** [comment]
As soon as the DeFi opportunities slice (https://github.com/shapeshift/web/pull/3136) will be fully implemented, we will be able to have the information about an arbitrary LP opportunity underlying tokens
