### ISSUE TITLE
FOXy manage button not loading on fox opportunities page 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#3158]
### Overview

The FOXy manage button on the fox opportunities page isn't loading.

### References and additional details

1. go to app.shapeshift.com
2. log in with native, mm, or kk
3. click on the fox opportunities tab
4. on the fox page click on the foxy tab 
5. notice the foxy manage button isn't loading under the liquidity pools section 

### Acceptance Criteria

the foxy manage button should load and you should be able to access the vault 

### Screenshots/Mockups

See button not loading here:
<img width="596" alt="Screenshot 2022-10-26 112603" src="https://user-images.githubusercontent.com/99363597/198072284-fd79b7d2-771a-480c-8921-fcec1367d4e5.png">

**Comment by gomesalexandre** [comment]
@wesleygravess added a sneaky fix for this in https://github.com/shapeshift/web/pull/3802
