### ISSUE TITLE
Asset Atari (ATRI) balance not loading and affecting users ability to use funds in that asset

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3167]
### Overview

When trading into/with Atari in app.shapeshift the balance is not showing/loading. 

### References and additional details

1) Log into app.shapeshift.com and connect to wallet of choice
2) Select ATRI from the search bar or asset page
3) Trade into ATRI and notice that the tx shows in recent transactions but the balance does not update.
https://etherscan.io/tx/0x0125246f2ad512711009a2ddcc59f527a6fb2fdfe672b81806dc81df3f49fe89
![image](https://user-images.githubusercontent.com/100157997/198159789-a9337a6f-9aa2-4c6b-bc1d-83f6bd452ce5.png)

Possible issue: app.shapeshift if pulling the wrong contract address?
When selecting "View on chain", Etherscan takes you to the address page, rather than the token page.
Takes you to: https://etherscan.io/address/0xdacd69347de42babfaecd09dc88958378780fb62  but potentially should be: https://etherscan.io/token/0xdacD69347dE42baBfAEcD09dC88958378780FB62

*This affects users ability to use their funds currently in ATRI. 

### Acceptance Criteria

Should be able to view asset balance and interact with asset monies.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@kaladinlight Looks like unchained (both on dev and prod) is not parsing ATRI tokens, this is the response from the [`GetAccount`](https://dev-api.ethereum.shapeshift.com/docs/#/v1/GetAccount) endpoint for a pubkey with ATRI tokens:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/17035424/198269118-7aa9fbb6-d8a0-4eae-83c9-05face1d04eb.png">

As can be seen on the screenshot, ATRI entry (`0x5daf465a9ccf64deb146eeae9e7bd40d6761c986`) is missing in `tokens`

**Comment by 0xdef1cafe** [comment]
closing as low pri

**Comment by MBMaria** [comment]
User is reporting this as an issue here: https://discord.com/channels/554694662431178782/1072384289246818314

**Comment by kaladinlight** [comment]
@MBMaria fix in place if you want to notify user
