### ISSUE TITLE
Add "Aggregator" label to OnRamper

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3194]
### Overview

1. We want to add "aggregator" to the Onramper link on the "buy/sell" crypto widget
2. Can we also move them to the #2 position, under JunoPay

### References and additional details

see above

### Acceptance Criteria

as a user I should see that Onramper is a fiat ramp aggregator and in the 2nd position.

**Comment by 0xApotheosis** [comment]
Looks like this was closed by https://github.com/shapeshift/web/pull/3198
