### ISSUE TITLE
Refreshing while having the fox/eth pool overview modal open yields a black screen

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#3206]
### Overview

Refreshing while having the fox/eth pool overview modal open yields a black screen

1) Connect Wallet with Fox/eth pool balance
2) Go to defi page
3) click on fox/eth pool and bring up the overview modal
4) hit refresh and observe a black screen

Might be related to the URL, I know we had that issue before when we got black screens more often. 

example url - https://release.shapeshift.com/#/fox?provider=UNI%20V2&chainId=eip155%3A1&contractAddress=0x470e8de2ebaef52014a47cb5e6af86884947f08c&assetReference=0x470e8de2ebaef52014a47cb5e6af86884947f08c&highestBalanceAccountAddress=0x8bedab5f8ddcac46013a15f9cd015ee2174e3e2a&rewardId=&modal=overview 

![image](https://user-images.githubusercontent.com/94986227/199343885-9e52f33d-cebe-4d81-92c7-0e53dc144349.png)

### References and additional details

see above. 

Triage link: https://discord.com/channels/554694662431178782/1037112617099079771

### Acceptance Criteria

A refresh with modal open would bring you back to the defi/fox page/asset page/ account page instead of black screening. 

### Need By Date

n/a

### Screenshots/Mockups

n/a

**Comment by gomesalexandre** [comment]
Note, this one will eventually be fixed by proper AccountId carrying through DeFi route props vs. the way we do it currently (drilling props)

**Comment by 0xApotheosis** [comment]
<img width="917" alt="Screenshot 2022-12-01 at 9 26 43 am" src="https://user-images.githubusercontent.com/97164662/204921632-2881434e-c2a3-4a95-8ac4-a3cbb16894da.png">
