### ISSUE TITLE
Native wallet UTXO default asset edge case

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#3208]
### Overview

Default asset selection is currently broken for the below edge case.

### References and additional details

From gomes: 

Probably edge case enough not to block this PR and be tackled as a follow-up, but I have noticed that for native wallet UTXO assets, going to an UTXO, navigating to a non-asset page e.g dashboard, then back to the same UTXO breaks the default account selection.

https://user-images.githubusercontent.com/17035424/199194357-7fdacdcf-33c9-400c-afa0-b0eed8e8d6c1.mov

This happens consistently and requires selecting the same asset again, either from the assets dropdown, or by navigating to a different asset and back to the rugged one

### Acceptance Criteria

Default assets are correctly selected.

**Comment by 0xApotheosis** [comment]
@MBMaria please bounty, 4 hours.

**Comment by 0xApotheosis** [comment]
Assigned to @crowicked as a bounty.

**Comment by 0xApotheosis** [comment]
@crowicked this will be inadvertently fixed by a PR today: https://github.com/shapeshift/web/pull/3214/files#diff-0f315d183697744fb9d565e7d8f222eb50a96ee74a2ba513081de2fe5295f54bR200-R224

**Comment by crowicked** [comment]
> @crowicked this will be inadvertently fixed by a PR today: https://github.com/shapeshift/web/pull/3214/files#diff-0f315d183697744fb9d565e7d8f222eb50a96ee74a2ba513081de2fe5295f54bR200-R224

Was just typing a reply with that question 😄 

Also, noticed that right now, while on dashboard, typing in an asset name and selecting it, doesn't take you to the assets page at all (aka couldn't replicate the UI behavior from the video), tried both locally & current app.shapeshift.com

**Comment by 0xApotheosis** [comment]
@crowicked hmm, I couldn't replicate that.

Wanna post a screen recording of it, and note any console errors you're getting?
