### ISSUE TITLE
Portis cannot connect

### ISSUE THREAD

**Issue by notatooyou** [shapeshift/web#321]
repro:
1. go to connect wallet
2. select portis
3. see this window and click the button

<img width="447" alt="Screen Shot 2021-11-09 at 3 48 30 PM" src="https://user-images.githubusercontent.com/89656210/141018137-a5bb2dde-04af-46de-a99b-073b864bc8cd.png">

4. see this message spin forever, and never connect
<img width="493" alt="Screen Shot 2021-11-09 at 3 49 02 PM" src="https://user-images.githubusercontent.com/89656210/141018171-26276c91-3000-4e3b-a383-37163ba52d05.png">

(also "Conected" is spelled wrong. Should be "Connected")

**Comment by cjthompson** [comment]
This is fixed.
