### ISSUE TITLE
Multiple Accounts Broken

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#3216]
### Overview

Multiple accounts for everything but THORChain and Cosmos is broken after adding a new account. From the accounts page expanding or clicking on any account does not work and refreshes the page. ETH does work if you click without expanding but expanding and clicking on any ETH token refreshes the page. 

### References and additional details

N/A

### Acceptance Criteria

After adding new accounts for any asset, you should be able to click on those assets and be brough to the correct corresponding page.

**Comment by 0xApotheosis** [comment]
Closing in favour of a pre-existing ticket: https://github.com/shapeshift/web/issues/3207
