### ISSUE TITLE
Fox Farming v4 txs should appear as stake/unstake 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#3240]
### Overview

Fox Farming v4 txs are appearing as send and receives when they should be appearing as stake/unstake transactions. 

### References and additional details

1. go to app.shapeshift.com
2. log in with mm, native, or kk
3. arrive on dashboard and click on the defi tab
4. click on the fox farming v4 staking position 
5. complete a deposit or withdraw transaction 
6. after the transaction has confirmed go to the dashboard or tx history page 
7. notice the deposit or withdraw shows up as a send or receive instead of a stake/unstake 

### Acceptance Criteria

a deposit into the fox farming v4 position should show up as a stake transaction. a withdraw from the fox farming v4 position should show up as an unstake transaction. 

### Screenshots/Mockups

<img width="308" alt="Screenshot 2022-11-07 144319" src="https://user-images.githubusercontent.com/99363597/200401066-a608a6f7-3909-4c13-ae0f-c6798ef0ca76.png">

**Comment by DiggyDiggy2** [comment]
we definitely would like to make this improvement. adding to clean up.

**Comment by 0xdef1cafe** [comment]
closing as low pri
