### ISSUE TITLE
Remove $50 minimum for Thorchain Swaps into ETH mainnet

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3242]
### Overview

We previously made trades into ETH mainnet have a $50 minimum to avoid failures on Thorchain, but now that we've completed https://github.com/shapeshift/lib/issues/1050, we should be able to remove the hard-coded minimum, in favor of proper estimations.

### References and additional details

The minimum trade amount is at least the outbound_fee that the node/midgard reports

### Acceptance Criteria

As a user I should be able to swap via Thorchain without a hard coded $50 minimum

**Comment by 0xApotheosis** [comment]
@DiggyDiggy2 turns out I already did this in https://github.com/shapeshift/lib/pull/1080

We are good here 👌 

<img width="378" alt="Screenshot 2022-11-08 at 4 10 25 pm" src="https://user-images.githubusercontent.com/97164662/200480328-aaa8fe97-849a-42c8-8d6b-c371368e94a8.png">
