### ISSUE TITLE
Refreshing on Fox Farming V4 overview page causes screen to black out

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3256]
### Overview

Whilst on the Fox Farming overview page when you refresh, it causes the screen to go black.

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to the Defi page and select the Fox Farming Card
3) On the overview page, refresh and notice that the page goes black.

### Acceptance Criteria

Page should not crash on a refresh

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
Relates to https://github.com/shapeshift/web/issues/3206

**Comment by 0xdef1cafe** [comment]
closing as stale this has been completely rewritten
