### ISSUE TITLE
Depositing into FOX/ETH LP when no fox in wallets that do not support mutli-account populates a miniscule amount

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3257]
### Overview

When depositing into a FOX/ETH LP in a wallet that has no fox and does not support multi accounts results in a tiny amount being entered to deposit. It only happens when there used to be fox and then it was sent/trades elsewhere. New accounts with no previous balance of fox do not have this error.
Noticed in Xdefi, MM, and Portis

### References and additional details

1) Log into app.shapeshift and connect to xdefi, MM or Portis
2) If a balance of fox is available transfer to a different account.
3) If there is already a zero balance of fox make sure there is previous history with fox tx in wallet.
4) Navigate to Defi page and select the FOX/ETH LP card. 
5) Enter an amount to deposit and notice a small amount populated despite being no fox in the wallet. 

![image](https://user-images.githubusercontent.com/100157997/200716578-96a17f38-a8c0-4bd0-9fb4-12082b5e3475.png)

### Acceptance Criteria

There should be no amount to deposit when zero balance of fox

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@DiggyDiggy2 I wasn't able to reproduce on a fresh account following the repro steps

![image](https://user-images.githubusercontent.com/17035424/200816429-3512418d-564c-48dd-99a4-4b9a6bec7fc3.png)
![image](https://user-images.githubusercontent.com/17035424/200816495-28298141-eec1-42d5-af94-7a0c9bf16bc7.png)

Following up in DM so I can reproduce with the same seed

**Comment by DiggyDiggy2** [comment]
@MBMaria can you FOXCrypt a seedphrase for this test wallet to Gomes? We've been unable to replicate.

**Comment by 0xdef1cafe** [comment]
closing as stale while searching for portis - this code has changed so much since then the ticket is almost certainly invalid
