### ISSUE TITLE
Transaction History: Scroll to show more

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/web#327]
Currently a set amount of transactions are shown, but we would like to show more transactions if bottom of the transaction history is hit until there are no more to show.

**Comment by 0xean** [comment]
Needs product guidance on the correct way to show all transactions.  @SS-FOX-McCloud to follow up with product folks to see what next steps are.

**Comment by 0xean** [comment]
pagination vs infinite scroll, etc.

**Comment by 0xdef1cafe** [comment]
closing in favor of https://github.com/shapeshift/web/issues/1006
