### ISSUE TITLE
Send/receive asset selection should handle unsupported assets

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#3311]
### Overview

Currently when in an asset page and opening up send/receive then clicking the back arrow, the full list of supported assets is displayed:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/17035424/201659989-3dc55fb0-5e14-4dae-82c1-964840a57808.png">

This includes assets the wallet does not support, meaning it is possible to intent sending/receiving assets which can't be:

<img width="994" alt="image" src="https://user-images.githubusercontent.com/17035424/201659047-15754b90-ea55-4254-87a6-0add0f862c13.png">
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/17035424/201659123-8f50457c-9f6d-493f-b9a3-8023a6ab9e7a.png">

We should bring the notion of supported chainIds to those modals, which https://github.com/shapeshift/web/pull/3308 will simplify now that we have unified asset selection components

### References and additional details

- https://github.com/shapeshift/web/blob/ed2a2056c5a124034eb76e5c884abc3e5affd1e4/src/hooks/useWalletSupportsChain/useWalletSupportsChain.ts#L55

- https://github.com/shapeshift/web/blob/f05d69c551c8fe5e586cd0811bb0f35b675d3ed9/src/state/slices/portfolioSlice/utils.ts#L324-L344

### Acceptance Criteria

- When selecting an asset to send, the list is filtered to the assets the connected wallet supports, using chain support
- When selecting an asset to send, the list is filtered to the assets the connected wallet supports, using chain support

**Comment by DiggyDiggy2** [comment]
to fix this, we can remove the back arrow on the pop-up when the user is on a specific asset page.

**Comment by twblack88** [comment]
confirmed with ops this works now. looks like we need to tag ticktes to close on PR merging too.
