### ISSUE TITLE
Cosmos deposit/withdraw type in dollar amount tx fails 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#3322]
### Overview

if you go to the cosmos defi modal, click to deposit/withdraw, switch the amount to USD and input a number, the tx fails. However, clicking on the % buttons works and typing in a number for the asset amount works.

### References and additional details

1. go to app.shapeshift.com
2. click on the defi tab
3. click on your cosmos staking position
4. click on deposit/withdraw 
5. switch the input to USD
6. type in a number and click continue 
7. click sign and broadcast and notice the transaction failed toast 

### Acceptance Criteria

The tx should not fail if you type a fiat amount when interacting with the cosmos staking modal 

### Screenshots/Mockups

<img width="436" alt="Screenshot 2022-11-14 143811" src="https://user-images.githubusercontent.com/99363597/201753066-1dfd9a8e-891c-4019-9f71-7eaee96e56be.png">
<img width="877" alt="Screenshot 2022-11-14 145141" src="https://user-images.githubusercontent.com/99363597/201753070-0109a393-17d6-437d-980f-12cdac32e5c1.png">

https://user-images.githubusercontent.com/99363597/201753083-df8bfd1f-094c-422b-a1d9-0ad909d5d170.mp4

**Comment by 0xdef1cafe** [comment]
closing as stale this has been entirely rewritten since then
