### ISSUE TITLE
Update title of trade modal when trade is pending and completed

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#3329]
### Overview

Currently, the trade modal continues displaying 'Confirm Details' as the title after a user has confirmed a trade.

As a user, I want the trade modal to clearly reflect when my trade is in progress as well as when it is complete.

### References and additional details

Steps to repro:
1. Confirm a trade
2. Notice that the title of the modal is still "Confirm details"

### Acceptance Criteria

AC:
1. When a users' trade transaction is successfully broadcasted, update the title of the trade modal to 'Trade Pending'
2. When a users' trade transaction is successfully completed, update the title of the trade modal to 'Trade Completed'

### Screenshots/Mockups

![image](https://user-images.githubusercontent.com/26232238/201785391-491150b3-7f75-4ef9-975a-db8c3188fbcb.png)

**Comment by ef3n9r98** [comment]
Hi @willyogo, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by woodenfurniture** [comment]
This one's mostly resolved however there's some outstanding work for thorswapper trades as noted by @0xApotheosis:
https://github.com/shapeshift/web/pull/3808#pullrequestreview-1294660546

I recommend we leave this issue open until myself or someone can loop back and handle undefined status for thorswapper trades.

**Comment by twblack88** [comment]
just tested, with the tx drawer we should cover all the bases
