### ISSUE TITLE
Can't enter password on saved native wallet after clicking back button 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#3347]
### Overview

If you click the back arrow on the native wallet password modal, you are unable to click on your saved wallet to get to the password modal again. You have to either close to wallet modal or navigate back to the wallet menu and choose the native wallet again. 

### References and additional details

1) click on connect wallet on the app landing page or switch wallets from inside the app
2) click on native wallet
3) click saved wallets 
4) click on saved wallet
5) arrive on the password modal and click the back arrow 
6) trying click on a saved wallet again and notice it doesnt proceed to the password modal 

### Acceptance Criteria

You should be able to click on your saved wallet and get to the password modal after clicking the back arrow from the password modal.

**Comment by 0xdef1cafe** [comment]
closing as low priority
