### ISSUE TITLE
Hanging FOX/ETH staking opportunities cards/rows balances on account switch

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#3356]
### Overview

Currently when switching accounts in MM, the previous staking data is left hanging:

- If you do have a staking opportunities in both, the balance shown in cards is the one of the originally connected account
- If you have a balance in the originally staked account but not the new one, the balance is left hanging and clicking it will open the Get Started flow
- Earn balance shows your originally connected account balance as a positive offset
- Wallet balance shows your originally connected account balance as a negative offset

### References and additional details

- https://github.com/shapeshift/web/blob/7535f441b203ffda83198bf565bf32eab1c28841/src/pages/Defi/hooks/useEarnBalances.tsx#L44

We select aggregated balances and keep the old ones in the store, which is expected, however, we should filter out by the wallet's current AccountIds - https://github.com/shapeshift/web/pull/3330/ will make this a lot more easier and reliable

### Acceptance Criteria

- When switching wallets, staking balances aren't left hanging
- The originally connected account balance isn't accounted for in totals

### Screenshots/Mockups

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/17035424/202447019-3babda63-463d-4eba-b9fa-c79c11eee327.png">
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/17035424/202447047-47c00cee-9116-4151-8191-e40a440c1e4c.png">

**Comment by 0xdef1cafe** [comment]
@shapeshift/operations can we get a retest/close plz?

**Comment by gomesalexandre** [comment]
@wesleygravess Closing this since I wasn't able to repro it either, blazingly fast and opportunities slice refactor fixed this
