### ISSUE TITLE
(Wallet Connect / Android / MetaMask) Hit or Miss prompts on Metamask

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#3362]
### Overview

Diggy noticed that after doing a send through wallet connect w Metamask, when trying another one you won't get a second prompt to do another send. 

1, Do a send through Wallet Connect w Metamask on android.
2. Try to do another send / trade after that.
3.  Notice that you won't get a prompt to confirm that send on MetaMask

### References and additional details

https://discord.com/channels/554694662431178782/1042892249031262208/1042930799302938684

### Acceptance Criteria

A user should get the prompt on MetaMask for every send that they prompt it to do.

*bonus points if you get SS to move over to MetaMask when making a send.

**Comment by 0xdef1cafe** [comment]
low priority as walletconnect v2 sdk is coming mid 23 and users aren't complaining about this

**Comment by twblack88** [comment]
with our focus on metamask and new walletconnect v2 coming i think we can close this
