### ISSUE TITLE
(Mobile / MetaMask) Shown a doubled Miner Fee when making a send with MetaMask on Mobile

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#3363]
### Overview

When sending with ShapeShift mobile and MetaMask, on the signing page inside the MetaMask app you are given a doubled miner fee. The max fee is the exact same but the estimation seems to be screwing up inside the MetaMask app. Possibly because we may not be using MetaMask Mobiles Estimation when sending a transaction. I'm unable to recreate this using a browser on PC.

Recreation Steps:
1. Make a send with MetaMask on Mobile
2. Notice the fee that you agree to on ShapeShift.
3. Notice the estimation fee is doubled but the max fee stays the same

### References and additional details
![Screenshot_20221130-125947_MetaMask](https://user-images.githubusercontent.com/94189400/204901095-e514ef2d-32af-4c96-9f6f-318d91bd694b.jpg)
![Screenshot_20221130-130003_MetaMask](https://user-images.githubusercontent.com/94189400/204901107-ee7a5135-2ea9-4a50-8338-e39a56357c28.jpg)
![Screenshot_20221130-130148_Chrome](https://user-images.githubusercontent.com/94189400/204901123-fca66775-9458-4ae2-a7be-8154031cc89c.jpg)

### Acceptance Criteria

Users should see the same estimation and max like you do using MetaMask on PC

**Comment by MBMaria** [comment]
Finding the same issue connecting to MM from app.shapeshift on mobile. (not wallet connect via the app)
I am unable to make a send or do a trade as it wont calculate a gas estimation. Tested on i0S.

**Comment by firebomb1** [comment]
Just to provide more data, as it might be related. I'm on Android too and it does pick up the estimation from app.shapeshift.com, but apparently it almost doubles it, I have no idea why.

Split-screen screenshot on the top is ShapeShift mobile app and bottom is MetaMask on the Accept/Reject screen:

![image](https://user-images.githubusercontent.com/88804546/202872774-afe4b5bb-f008-451b-8190-85966a91176f.png)

It does mention a "Max fee" below, which seems to match what ShapeShift estimated, but it still suggests a much higher fee than that under "app.shapeshift.com suggested gas fee". And if I was to accept the transaction it would pick the "suggested" one judging by the total line at the bottom 😕

**Comment by tshifty** [comment]
@firebomb1 Can you try that again? The issue may have been on MetaMasks side as my issue seems to be fixed and the correct miner fee amount is being transferred over to MetaMask.

**Comment by firebomb1** [comment]
@tshifty Unfortunately it still seems to somewhat double the fee suggested on Mobile (Android) using WalletConnect and MetaMask... again in the last line ("Max amount") on MetaMask it does mention the fee we can see on ShapeShift UI... but it doesn't seem to use it, if I was to confirm this transaction it would most likely use the bold value I've circled in red would be used :(

![image](https://user-images.githubusercontent.com/88804546/204883571-821ce378-6b27-4110-81b6-4e629057d79e.png)

On PC, also using WalletConnect with MetaMask, the fee suggestion seems to work correctly:

![image](https://user-images.githubusercontent.com/88804546/204884063-3ea20773-d108-428b-ac9d-feddf5d0928a.png)

Clicking on the fee (blue link) on MetaMask Mobile gives us a bit of info on what might be going on (the fee amount is not exactly the same as I had to re-create the transaction and the estimation changed):
![image](https://user-images.githubusercontent.com/88804546/204886042-7e0e5aed-942c-4994-a17f-2991b5aa35cf.png)

I don't know enough about MetaMask and the API/RPC we use to say if it's really the issue, but it's a potential source of the discrepancy... it still wouldn't explain why on PC it seems to use the correct value.

**Comment by tshifty** [comment]
@firebomb1 I'm still unable to recreate this. Moving this over to a discord thread for further testing

![Screenshot_20221130-122003_ShapeShift](https://user-images.githubusercontent.com/94189400/204889738-706a7a11-d071-4cf3-81fa-8e19d34e3ab2.jpg)
![Screenshot_20221130-122026_MetaMask](https://user-images.githubusercontent.com/94189400/204889754-aae14422-5db7-42f0-af97-10326ee9fabb.jpg)

**Comment by tshifty** [comment]
@firebomb1 I'm able to recreate that visual issue but it seems that once you make the send the max fee that is set on chain is the one matching the SS app. I'll open up a discord thread so we can discuss

**Comment by purelycrickets** [comment]
@MBMaria another one

**Comment by MBMaria** [comment]
![image](https://github.com/shapeshift/web/assets/100157997/95ece275-f066-4032-9efe-90eebe77c647)
![image](https://github.com/shapeshift/web/assets/100157997/9cd47394-9410-410e-8739-469e765b2e50)

Fees are looking good. closing this one.
