### ISSUE TITLE
Wallet Connect iOS mobile tx confirm prompts

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#3364]
### Overview

When making a send or trade on metamask via wallet connect on the mobile app, the user is brought to metamask. Sometimes the confirm prompt on the wallet doesn't come up when making sends. Also, when clicking confirm on the metamask prompt, the confirm button stays in the pending state indefinitely and the tx never confirms, this happens for trades and sends. 

### References and additional details

1. open shapeshift mobile app 
2. connect with mm through wallet connect
3. go to the eth asset page and click send
4. scan an address, click next
5. choose amount to send, click next, and click confirm
6. the mm app opens up, sometimes the confirm doesn't show up, when it does click confirm.
7. notice the confirm button spins indefinitely
8. when you go back to the app an error appears that the user rejected the transaction  

### Acceptance Criteria

the mm confirm prompt should show up every time and the confirm button on the mm app should broadcast the tx. 

### Screenshots/Mockups

![IMG_4050](https://user-images.githubusercontent.com/99363597/202581566-07b8aa3c-710f-4fc5-a746-d29ae17c116c.png)

**Comment by MBMaria** [comment]
Finding the same issue connecting to MM from app.shapeshift on mobile. (not wallet connect via the app)
I am unable to make a send or do a trade as it wont calculate a gas estimation. Tested on i0S.

**Comment by purelycrickets** [comment]
@MBMaria another one

**Comment by MBMaria** [comment]
Able to send on mm connected via wallet connect now. Closing ticket  ![image](https://github.com/shapeshift/web/assets/100157997/a1937cfb-bbaa-43bf-afa6-30ddb7a6480f)
