### ISSUE TITLE
Fox staking and opportunity balances populating in Defi page when switching to Keplr

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3366]
### Overview

When switching to Keplr from the DeFi page in a wallet with balances in fox staking/opportunities, they show up in the keplr DeFi page. They disappear after a while but on initial switch makes the wallet balance incorrect.

### References and additional details

1) Log into app.shapeshift and connect to wallet with fox staked or deposited in fox opportunities
2) Navigate to DeFi page
3) Switch to Keplr wallet
4) Notice any fox staking or opportunity cards showing in the Keplr wallet
![image](https://user-images.githubusercontent.com/100157997/202612777-2581c62f-96cb-4e8f-99e4-dcfd4d62abfe.png)

*can also occur when switching to Keplr when not on the Defi page
### Acceptance Criteria

Fox staking and depositing opportunities shouldn't display in Keplr. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
closing as cannot repro
