### ISSUE TITLE
Not Collecting Market Data for Idle Assets STETH and AGEUR

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#3378]
### Overview

App is not collecting market data for Idle Assets STETH and AGEUR.

### References and additional details

1. go to app.shapeshift.com 
2. log in with mm, kk, or native
3. turn on the idle flag
4. go to the search bar and type in Euler AGEUR or Lido STETH
5. look at the market data for the junior and senior Tranche for both assets 
6. Notice the note on the chart, "Market data for this asset isn't available yet. We're working on it, hang tight!"

### Acceptance Criteria

app should collect market data for these idle assets 

### Screenshots/Mockups

<img width="302" alt="Screenshot 2022-11-21 122943" src="https://user-images.githubusercontent.com/99363597/203121647-91807a07-9a70-4a8b-8d4a-4dee993aa14a.png">

**Comment by gomesalexandre** [comment]
Closed by https://github.com/shapeshift/lib/pull/1097
