### ISSUE TITLE
Fox Opportunities not appearing on MM mobile when staked in V5

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3379]
### Overview

If there is fox staked in the V5 contract, the fox farming and ETH/FOX LP balances/opportunities do not show up in MetaMask on the mobile app (connected via wallet connect) or web on mobile. 

### References and additional details

1) Log into app.shapeshift.com on MOBILE and connect to Metamask (via wallet connect)
2) Navigate to defi page and deposit into V5 contract.
3) Refresh and notice that the fox farming and eth/fox LP balances/cards are no longer visible.
4) Navigate to the Fox Opportunity page and notice they do not appear there either. 
![image](https://user-images.githubusercontent.com/100157997/203162933-b1b45f8c-0b39-4bc1-b1f5-e069c3016283.png)

### Acceptance Criteria

Fox Farming and ETH/FOX LPs should be visible at all times

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
If you disconnect the wallet, refresh and then reconnect the fox opportunities will re appear.

**Comment by 0xdef1cafe** [comment]
closing as this has been rewritten and we're now on v6
