### ISSUE TITLE
Idle finance DeFi card/balance only showing after a refresh

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3387]
### Overview

When depositing into Idle finance, the card on the DeFi page only shows up after a refresh

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to Defi page and select the Earn tab
3) Find an Idle asset to deposit into that doesn't have a balance
4) Complete a deposit into the asset and then navigate to the Defi home page
5) Notice the new asset doesn't appear in the list
6) Refresh page and note the asset card will appear

*behaviour noticed on native wallet and MM

### Acceptance Criteria

Asset should appear in the list automatically once tx completed on the block chain, a refresh shouldn't be needed.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
After completing a withdraw, the balance only updates after a refresh.

**Comment by 0xdef1cafe** [comment]
@MBMaria retest and close plz?

**Comment by MBMaria** [comment]
Trying to deposit into one of these but its failing. 
![image](https://user-images.githubusercontent.com/100157997/217419078-ca7c0e24-08fd-44ed-a172-65701072973e.png)
![image](https://user-images.githubusercontent.com/100157997/217419198-4011e84d-40f5-46f8-af3f-e27c8c1486c2.png)
![image](https://user-images.githubusercontent.com/100157997/217419257-7093bfca-ef3d-40d4-946a-1fb43bcd864e.png)

**Comment by gomesalexandre** [comment]
@MBMaria the deposit issue has been fixed upstream and in https://github.com/shapeshift/lib/pull/1188 - refetch is still valid
