### ISSUE TITLE
Unable to trade out of PAXG - protocol trying to use Cowswap when token is unsupported

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3397]
### Overview

When trying to trade out of PAXG, app.shapeshift is trying to use Cowswap as the protocol but PAXG is an unsupported token on Cowsawp. It will trade ETH into PAXG using 0x, but not for a trade the other way round. 

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Use the trade modal or navigate to the trade page
3) Enter PAXG as the top asset and enter an amount
4) Note the protocol being used is Cowswap
5) Notice that you can select Preview Trade but it doesn't take you to a preview of the trade
![image](https://user-images.githubusercontent.com/100157997/203642985-a5b78725-c3fb-44b0-b182-40f302f6af05.png)
![image](https://user-images.githubusercontent.com/100157997/203643004-830a756a-9120-4c4c-b194-859f304c4dff.png)
![image](https://user-images.githubusercontent.com/100157997/203643042-379f6ce7-384c-403f-a134-7e45278628b9.png)

### Acceptance Criteria

app.shapeshift should use the most appropriate protocol to ensure a trade is executed. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
![image](https://user-images.githubusercontent.com/88504456/216854076-e498470c-b1d4-48c5-903c-7acc66d44cc5.png)

closing as this now routes correctly via 0x
