### ISSUE TITLE
Switching wallets on accounts page triggers error boundary

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#3404]
### Overview

Currently on the accounts page, when switching from Native to MM, an error boundary is triggered

It stays even when switching back to MetaMask, and is resolved by clicking "Try Again"

### References and additional details

N/A

### Acceptance Criteria

- Wallet switching from accounts page works

### Screenshots/Mockups

<img width="456" alt="Screenshot 2022-11-25 at 18 28 05" src="https://user-images.githubusercontent.com/17035424/204033547-72e33f43-5e0b-4115-b52a-5406efe24c78.png">

**Comment by tshifty** [comment]
Fixed.
