### ISSUE TITLE
Incorrect receive address in THORSwap memo

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#3417]
### Overview

TX https://viewblock.io/thorchain/tx/4CD279A312D59189169D97E203C3BAB26063B62EA4ACEDF5837FE51F69A8A00E has an invalid (BTC) address when it should have had the user's Ethereum address.

### References and additional details

Possibly a caching issue with a `TradeState` value.

### Acceptance Criteria

Reproduce, and then fix.

**Comment by 0xApotheosis** [comment]
Possibly another occurrence: https://discord.com/channels/554694662431178782/1050824938371694612

Trade link: https://viewblock.io/thorchain/tx/67D348A5917BAA39EF0DCEA185C07FC4016D9623E7F9C3E512ABE09A11F69C9E

Sent to `bc1qeua35yy4q8qjwefn7v4hrqjrttj2zh56c3ltpd`, which doesn't seem to belong to `zpub6qqo2sKd2Ninjp9o34DSzm3RAvvJCqQxBnVdCmPh5tZXSgM2boyRYzSTWhyG85uKqEKMATgPULd6cQw35FrMV2eSpZLDv4bVtgopPpvMBfn`.

**Comment by 0xdef1cafe** [comment]
Closed by release 1.180.0
