### ISSUE TITLE
Allowing inbound swap amount lower than min swap

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#3418]
### Overview

We are sometimes allowing transactions below the minimum swap amount for THORSwap to be built.

### References and additional details

An example is https://viewblock.io/thorchain/tx/C20A6BDCFD060A6A61E4A799CF856F1DBA3518F86F06BF9AD691DC88C3E97EC3

### Acceptance Criteria

These should be caught at the trade quote screen - we should never reach the trade preview step for these type of trades.

**Comment by 0xdef1cafe** [comment]
@0xApotheosis is this still valid? believe this should be fixed with swapper robustness lately

**Comment by 0xApotheosis** [comment]
Yep, this guy is fixed.
