### ISSUE TITLE
ThorSwap "View Transaction" should link to viewblock

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#3426]
### Overview

Currently, our logic for the "View Transaction" link is to route to the inbound Tx explorer i.e the explorer of the sell asset, or to CowSwap/Osmosis explorer if the swap is from one of these sources

We should also handle ThorSwap Txs to consistently link to viewblock - currently, we only route to it in case of RUNE as a sell asset, since viewblock is defined as a RUNE explorer

### References and additional details

https://github.com/shapeshift/web/blob/b5e649395c8a4fa057f9d57c48981d99aa64cfc9/src/components/Trade/TradeConfirm/TradeConfirm.tsx#L147-L156

In the case of Thor swaps, `thorchain` is the source so we can simply add a case for it:

<img width="168" alt="image" src="https://user-images.githubusercontent.com/17035424/204654248-855fa1b8-f10b-4df7-a139-e57c3a55dd12.png">

### Acceptance Criteria

- All ThorSwaps "View Transaction" links in trade confirm link to viewblock.io

**Comment by 0xApotheosis** [comment]
We should make `TradeSourceName` an enum whilst we're here.
