### ISSUE TITLE
Unable to deposit in Fox Yieldy on MM (gets stuck on approval)

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3428]
### Overview

When trying to deposit into Fox Yieldy on MM in a wallet that hasn't approved fox, it is getting stuck on the approval, and not allowing the deposit to go through

### References and additional details

1) Log into app.shapeshift and connect to a MM wallet that doesn't have fox already staked
2) Navigate to DeFi page and select earn
3) Select Fox and go to Deposit Fox now
4) Select a % or 'max' amount to deposit
5) Go to approval and select continue and confirm
6) Note an error comes up saying 'Transaction Failed'

*if fox already staked, the error does not occur
**can have a work around by approving directly on etherscan
*** if you select a whole number of fox to deposit, ie 10 then the approval goes through

https://user-images.githubusercontent.com/100157997/204659100-c4ad7835-d1f5-447c-a9ec-700bf9193c8d.mov

### Acceptance Criteria

Should be able to use % and max button of fox and approval will be accepted

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
@gomesalexandre is this something you would typically work on? Just wondering if there would be a timeline when this might get fixed as marketing are about to do a push/promo for foxy and asked if it will be fixed before hand?

**Comment by MBMaria** [comment]
Experiencing this on KK with account 1 that hasn't been deposited into previously.
![image](https://user-images.githubusercontent.com/100157997/204932252-ff6c0891-789d-452b-a4e2-4e8ba44181fc.png)

**Comment by gomesalexandre** [comment]
https://github.com/shapeshift/web/pull/3414 will pave the way for things to be more sane here, we're passing a precision amount to Foxy API while it expects a base unit float.

By itself, the aforementinoed PR won't fix it nor make us able to spot the issue, so we'll need another level of safety in
1. naming
2. ensuring we are blazingly safe, checking the stringified BN is an integer (not fail-proof by itself as e.g 1 ETH would be an integer, but safe in combination with the right vernacular)

**Comment by MBMaria** [comment]
i just experienced this again @gomesalexandre . it gets stuck on the approval if i choose a $ amount of fox deposit or it i choose a percent of fox to deposit . this is on MM where no fox has been deposited previously
![image](https://user-images.githubusercontent.com/100157997/205754872-c5dd8263-6d4a-4249-ba2e-2da1445290d7.png)
