### ISSUE TITLE
UTXO trades defaulting to account 0 even if account 1 is selected

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3430]
### Overview

When trying to complete a UTXO trade from an account other than 0, the trade will automatically use account 0, even if account 1 is selected. It will not allow the trade to preview.

### References and additional details

1) Log into app.shapeshift and connect to native wallet
2) Navigate to accounts page and make sure you have a UTXO with a higher balance in account 1 than account 0
3) Select asset from account 1
4) In the trade widget populate a trade out of the asset (move it to the top box in the widget)
5) Make sure the amount to trade is within the balance tradeable from account 1 but is more than the balance of account 0
6) Select preview trade and note that it spins but does not progress. 
Console error: 
![image](https://user-images.githubusercontent.com/100157997/204669612-73039d3f-6778-4d67-a7c4-0929eb352c19.png)
![image](https://user-images.githubusercontent.com/100157997/204670382-a79b72d1-1451-4372-a238-3953a99f76a7.png)
![image](https://user-images.githubusercontent.com/100157997/204670509-abd55089-0f23-4e97-8afd-a2d2b92f6f31.png)

### Acceptance Criteria

Trade widget should use the account selected, not defaulting to account 0 . 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
Closed by https://github.com/shapeshift/web/pull/3516
