### ISSUE TITLE
Recent TXID pulling from different location than when broadcasting thorswap trade

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3446]
### Overview

When broadcasting a trade on thorswap, the view transaction link is different to the txid in the recent transactions

### References and additional details

1) Log into app.shapeshift and connect to wallet that supports thor trades
2) Navigate to trade page and create a trade using thorswap
3) Broadcast tx and select the link to 'view transaction'
4) In the recent tx's select the txid. Note it takes you to different links.
![image](https://user-images.githubusercontent.com/100157997/204936718-295d81fb-5022-4ac8-80d2-326d154f6a07.png)

### Acceptance Criteria

Link to tx should be the same location

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
It looks like we don't apply any of the conditional TX link logic in transaction history, this applies to special CowSwap and Osmosis logic, too.

**Comment by 0xApotheosis** [comment]
Incorrectly closed by https://github.com/shapeshift/lib/pull/1110.

**Comment by purelycrickets** [comment]
@MBMaria another one

**Comment by MBMaria** [comment]
Still an issue. 
tx from "view transaction": (missinf 0x) https://viewblock.io/thorchain/tx/1effb442501248fc6e07eb8682776b8385f645420d36a258a733ed97c9a91d2c
tx from recent transactions: https://etherscan.io/tx/0x1effb442501248fc6e07eb8682776b8385f645420d36a258a733ed97c9a91d2c

**Comment by kaladinlight** [comment]
If we did want to provide the same explorer link, we could detect if we are on the trade page and change how we display recent transactions on that page only as a possibility. Otherwise it would probably fall more into the "activity/action" (not sure what name we have been referring to it) view that links multiple transactions together for a specific action (ex. eth tx + usdc tx as a single "swap" transaction view)

@twblack88 @0xean
