### ISSUE TITLE
Add default sell asset to the trade component

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#3487]
### Overview

We would like to be able to set the sell asset in addition to the buy asset on trade by default.

### References and additional details

I believe we would need to add support for this to `useDefaultAssets` 

### Acceptance Criteria

When a user clicks on the trade button from the asset actions they are taken to trade with that asset pre-selected as the sell asset. 

We would also need to run validation on this pre-selected asset, if they have no balance of that specific asset. 

### Estimated effort

half a day

**Comment by 0xdef1cafe** [comment]
closing as discussed
