### ISSUE TITLE
User unable to withdraw from v4 FOX Farming 

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#3589]
### Overview

We have a user (@hatch22) that is a bit late on trying to withdraw their FOX/ETH from the v4 FOX Farming contract. I'm unable to test this since I no longer have anything inside that contract but the user provided their console errors,

"This is what I get when I try to do a Withdraw & Claim on the ETH/FOX contract: 

Error: Asset not found for AssetId undefined
    at P (ExpiredWithdraw.tsx:53:21)
    at Cl (react-dom.production.min.js:167:137)
    at Du (react-dom.production.min.js:290:337)
    at bs (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at os (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at w (scheduler.production.min.js:13:203)
    at MessagePort.C (scheduler.production.min.js:14:128)
    pi    @    react-dom.production.min.js:189
o.componentDidCatch.n.callback    @    react-dom.production.min.js:190
Yo    @    react-dom.production.min.js:144
wu    @    react-dom.production.min.js:261
bu    @    react-dom.production.min.js:260
gu    @    react-dom.production.min.js:259
(anonymous)    @    react-dom.production.min.js:283
ks    @    react-dom.production.min.js:281
as    @    react-dom.production.min.js:270
w    @    scheduler.production.min.js:13
C    @    scheduler.production.min.js:14

### References and additional details

https://discord.com/channels/554694662431178782/1061157276901183529/1061158578284658770

### Acceptance Criteria

This user should be able to withdraw his FOX/ETH from our v4 FOX Farming contract

**Comment by gomesalexandre** [comment]
@tshifty I've just tried to repro this and while I've experienced the same error, the removal Tx actually went through.

Could you confirm?

**Comment by MBMaria** [comment]
Unable to claim V4 - giving an error of "insufficient funds" even though there are more than enough funds to cover gas
![image](https://user-images.githubusercontent.com/100157997/214957198-96f03f0b-1d7a-4ff3-aff2-a574ec1a6de3.png)

**Comment by DiggyDiggy2** [comment]
have we had any further complaints on this? Can we confirm that they have enough gas in Account #0?

**Comment by MBMaria** [comment]
this was a selecting account issue. believe it is fixed as i successfully withdrew from v4 the other day. closing this one now.
