### ISSUE TITLE
Add estimated time to break even on savers vaults deposits

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3590]
### Overview

As a user, when depositing into a Savers vault, I want to see the estimated time that it would take to break even on my deposit after fees.

### References and additional details

This information is available, and we'd just need to implement it.

@reallybeard to determine where this line item appears in the UI
<img width="400" alt="Screen Shot 2023-01-09 at 11 40 00 AM" src="https://user-images.githubusercontent.com/90058616/211383250-91ff160a-85ea-4966-b765-ded19588a26a.png">

### Acceptance Criteria

when depositing into a Savers vault, user should see the estimated time that it would take to break even on their deposit after fees.

**Comment by gomesalexandre** [comment]
Closed by https://github.com/shapeshift/web/pull/3723
