### ISSUE TITLE
Allow us to embed youtube videos on the app

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#3605]
### Overview

We would like to embed youtube videos on the site in guides.

### References and additional details

I believe we need to add youtube to the CSP

### Acceptance Criteria

Videos from youtube will be loaded and not blocked

**Comment by 0xdef1cafe** [comment]
closing as stale - add `media-src` to the CSP at your discretion https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/media-src
