### ISSUE TITLE
Withdraw from FOX Yieldy not working (7-14 days) 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3622]
### Overview

Gets stuck at Pending when withdrawing from FOX yieldy on the 7-14 day option. Instant withdrawal works.

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Naviate to Defi Page and select Fox token staking card
3) Withdraw from Fox yeildy
4) Enter amount to withdraw and select Continue
5) Sign and Broadcast
6) Notice an error comes up about 'something went wrong', the circle spins continuously on Transaction Pending 
![image](https://user-images.githubusercontent.com/100157997/211948520-aad29ddb-400a-4f62-be16-5a285a26a2af.png)
![image](https://user-images.githubusercontent.com/100157997/211948528-d4e65f02-c414-4190-80a5-0ad4e8c5f060.png)

### Acceptance Criteria

Should be able to withdraw from Fox yieldy either instantly or the 7-14 day option 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by wesleygravess** [comment]
I was just able to complete a foxy 7-14 day withdraw on native and kk.

**Comment by wesleygravess** [comment]
i was just able to do a foxy 7-14 day withdraw on kk and native.

https://etherscan.io/tx/0x26f70eb7a48798bde0bad7c1b1f8f4176df1e2b580439fb99aab3f921636a2e5
<img width="474" alt="Screenshot 2023-01-12 111618" src="https://user-images.githubusercontent.com/99363597/212123562-dfec4fe1-0532-4489-afd1-86cf0f89a835.png">

**Comment by MBMaria** [comment]
I was also able to withdraw foxy just now on MM
![image](https://user-images.githubusercontent.com/100157997/213303209-ad5565e8-3bad-4dc2-9a65-653b443b3dc9.png)

**Comment by gomesalexandre** [comment]
@MBMaria Can we close this after retesting after the stack of FOXy PRs go in?

**Comment by MBMaria** [comment]
Confirming foxy withdrawal is working.
