### ISSUE TITLE
Entering USD amount for staking cosmos sdk coins causes the transaction to fail

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3623]
### Overview

When selecting a USD value amount to deposit in atom or osmosis staking it causes the transaction to fail. If you select a % to deposit, the transaction will complete

### References and additional details

1) Log into app.shapeshift.com and connect to wallet that supports atom
2) Navigate to the Defi page and select the atom (or osmosis) card
3) Select Deposit and type in a USD value, ie $2 and select Continue
4) Sign and Broadcast
5) Notice the "transaction failed" toast appears, and the transaction will stay on pending until exited
![image](https://user-images.githubusercontent.com/100157997/211950445-ecbace4e-09af-41f8-b424-4709e8f04bf7.png)
![image](https://user-images.githubusercontent.com/100157997/211950490-02c55f3a-95a5-482a-a2d1-49dd0ca58df3.png)
![image](https://user-images.githubusercontent.com/100157997/212414493-79b0d27a-11dc-4c49-860c-b6db9d569be8.png)

### Acceptance Criteria

Should be able to type a USD amount in to stake atom/osmosis

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by wesleygravess** [comment]
original ticket for this issue if needed: https://github.com/shapeshift/web/issues/3322

**Comment by gomesalexandre** [comment]
@MBMaria this has been fixed in https://github.com/shapeshift/web/pull/3844 - please close after confirming fixed for both Cosmos and Osmosis

**Comment by MBMaria** [comment]
Fixed and merged in todays release 1.217.0
