### ISSUE TITLE
Defi page not loading all vaults/cards until a transaction is completed 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3637]
### Overview

When viewing the DeFi page, only Fox Token Staking and ShapeShift Dao validator for Atom are showing up until a transaction is done in the defi section.

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to DeFi page and notice only Foxy and Atom staking are available
3) Complete a TX  such as a deposit or stake
4) Navigate back to DeFi page and note that the other cards/vaults appear. (only idle and LP pools currently, not yearn)
![image](https://user-images.githubusercontent.com/100157997/212785629-c73d7011-f0ac-4460-bbd8-e8300ba70c48.png)

### Acceptance Criteria

All vaults/cards should be displayed on DeFi page. A tx should not be required for the assets to show.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by wesleygravess** [comment]
this ticket is fix, defi position loading properly now.
