### ISSUE TITLE
Thorchain Send TXID invalid url 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#3639]
### Overview

The thorchain block explorer link in to txid provides and invalid url: https://v2.viewblock.io/thorchain/tx/C45F63E1E84BF561930B0BE70ECC5000021DD0C36064AF4E887345EEFDD59BF2

The v2 in the url is the issue. If you delete that, the link works and it takes you to the correct page for your tx:
https://viewblock.io/thorchain/tx/C45F63E1E84BF561930B0BE70ECC5000021DD0C36064AF4E887345EEFDD59BF2

### References and additional details

1. go to app.shapeshift.com
2. log in with shapeshift or kk
3. go to the thorchain asset page
4. make a send tx
5. click on the link in the green toast or the tx in the trade history 
6. notice it takes you to a 404: NOT FOUND page 
7. delete the v2 at the beginning of the url 
8. notice the url now takes you to the correct page for you tx

### Acceptance Criteria

link should take you to the correct page for your tx by deleting v2 at the beginning of the url 

### Screenshots/Mockups

With v2 in url:

<img width="1276" alt="Screenshot 2023-01-17 135555" src="https://user-images.githubusercontent.com/99363597/213016976-3d0a9e37-fb2c-46cc-b809-8ff4a3a85a5f.png">

Without v2 in url:

<img width="1276" alt="Screenshot 2023-01-17 163416" src="https://user-images.githubusercontent.com/99363597/213017085-fb64d919-d2f4-47e2-b848-451f2e29c747.png">

**Comment by gomesalexandre** [comment]
@wesleygravess This has been fixed in https://github.com/shapeshift/web/pull/3650, please close after confirming this has been fixed
