### ISSUE TITLE
FOX token staking button causing oops error

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#3654]
### Overview

When clicking the manage button under fox token staking section on the fox opportunities page, it causes an oops error. 

Also happening when clicking the get foxy button on the foxy tab on the fox opportunities page
Elastic swap info never loads on the foxy tab on the fox opportunities page

### References and additional details

1. go to app.shapeshift.com
2. log in with mm, native, or kk
3. navigate to the fox opportunities page 
4. click on the manage button under the fox token staking section
5. notice the oops error 

### Acceptance Criteria

the fox token staking manage button should open up the defi window to manage your position 

### Screenshots/Mockups

<img width="1268" alt="Screenshot 2023-01-19 102442" src="https://user-images.githubusercontent.com/99363597/213483386-0bd27b90-d3f9-4948-a9d6-73241af9906c.png">
<img width="563" alt="Screenshot 2023-01-19 102655" src="https://user-images.githubusercontent.com/99363597/213483393-345ee8b7-037a-4dc5-aee9-8f32ff54b596.png">

<img width="1214" alt="Screenshot 2023-01-19 103852" src="https://user-images.githubusercontent.com/99363597/213489151-c724752a-73d3-454d-8025-6ea45b2b61ff.png">

**Comment by wesleygravess** [comment]
Still getting oops error clicking this button in the fox tab on the fox opportunities page.

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/99363597/213545950-689b4bc4-6a94-482e-ab2c-9cf8b67df0e0.png">

**Comment by wesleygravess** [comment]
do you want me to make a separate ticket for this issue?

**Comment by reallybeard** [comment]
> do you want me to make a separate ticket for this issue?

nah i'll just attach it to this one again
