### ISSUE TITLE
Handle wallet rejections for KeepKey

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3706]
### Overview

As a user, if I reject a transaction on my KeepKey the UI gets stuck. Instead, the transaction I had set up, should revert back to the initial screen. ie, how we handle with Metamask. if the user rejects the trade, then the screen is reset to the trade the input view.

### References and additional details

this can be tested with a KeepKey

### Acceptance Criteria

Rejected transactions with the KeepKey should reset the UI instead of just hanging, which requires the user to disconnect their wallet to reset everything

**Comment by 0xean** [comment]
asking operations to confirm this is still valid

**Comment by 0xean** [comment]
closing per @purelycrickets
