### ISSUE TITLE
Portis Login Looping on Brave Browser

### ISSUE THREAD

**Issue by VladHZC** [shapeshift/web#372]
![](https://i.ibb.co/0VYVQQ8/sasaas.gif)
`https://i.ibb.co/0VYVQQ8/sasaas.gif` 
Any portis login is looping on my brave browser, I am able to login wallet.portis, but not on shapeshift website or opensea. 
Tried several login orders

This is the version of Brave I am using: 

<html>
<body>

Brave | 1.31.91 Chromium: 95.0.4638.69 (Official Build) (64-bit)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Windows 10 Version 21H1 (Build 19043.1348)
JavaScript | V8 9.5.172.25
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

</body>
</html>

**Comment by 0xean** [comment]
closing as wont fix.  Shields on brave must be turned down due to portis. @0xdef1cafe to follow up with portis on it.
