### ISSUE TITLE
Blank screen showing in Eligible Opportunities Slider

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3749]
### Overview

as a user, I see an empty slide on the eligible opportunities slider from the dashboard. We should not have an empty slide.

### References and additional details

To replicate:
1. Before I unlock my wallet, it shows "fox farming" and "usdt' in the slider
2. After I unlock my wallet, the farming one is hidden but the empty slide is still there.
3. I assume this is because I'm already farmed, but the app doesn't pick up on this until AFTER i've unlocked my wallet.

I assume, its an issue related to when we're running the check on eligible opportunuties
<img width="782" alt="Screen Shot 2023-02-02 at 4 00 09 PM" src="https://user-images.githubusercontent.com/90058616/216470490-f7c0a3be-1ec8-400a-b75e-8ea82d883dd2.png">

### Acceptance Criteria

As a user, I should not see any empty screens in "eligible opportunities"

**Comment by gomesalexandre** [comment]
@DiggyDiggy2 looks like this was an issue related to duplicates (https://github.com/shapeshift/web/pull/3825), I can't repro it anymore

**Comment by DiggyDiggy2** [comment]
> @DiggyDiggy2 looks like this was an issue related to duplicates (#3825), I can't repro it anymore

agreed, just attempted to reproduce and it seems to be resolved.
