### ISSUE TITLE
Date Stamp on transactions disappears on certain screen sizes

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3750]
### Overview

@reallybeard to fill in the details - as he can replicate this one

### References and additional details

This was reported by a user in feedback and can be seen on certain mobile screen sizes

### Acceptance Criteria

As a user, I should always see the date and time stamp on my transaction history

**Comment by 0xean** [comment]
@reallybeard - could you take a look at this one?

**Comment by reallybeard** [comment]
@0xean yah i'll take a look.
