### ISSUE TITLE
KeepKey asking to confirm ETH address on log in 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#3773]
### Overview

After inputting your pin during log in with KeepKey, you get a prompt on your device to confirm your ETH address before it loads your ETH address on your wallet. Looks like this was introduced in 1.203 

### References and additional details

1. go to app.shapeshift.com
2. log in with KK
3. input your pin 
4. notice confirm ETH prompt on your device 
5. press button on KK to confirm address
6. wallet load eth address

### Acceptance Criteria

you should not have to confirm ETH address on log in, in order to load your ETH address on your wallet

**Comment by 0xApotheosis** [comment]
Closed by https://github.com/shapeshift/web/pull/3807
