### ISSUE TITLE
UTXO trades borked on KeepKey on initial load

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3775]
### Overview

Only able to complete ETH/ERC-20 trades currently on KK. When selecting BTC or other utxo it will no preview trade or let you type in an amount. Gives an "Invalid Trade Pair" error

### References and additional details

1) Log into app.shapeshift.com and connect to KeepKey
2) Try create a UTXO trade pair in the trade widget.
3) Notice when selecting BTC for example when trying to enter an amount to trade, the swapper will not enter an amount.
4) Navigate to Trade page and try select a non eth chain and note that you cannot select one.
5) Once a UTXO pair is 'loaded' the error "Invalid Trade Pair" will populate

https://user-images.githubusercontent.com/100157997/217407017-d8125e81-7624-4424-84c1-41ce25e6a58f.mp4

![image](https://user-images.githubusercontent.com/100157997/217406942-d529b28e-39a6-4e4b-b42a-9ebe5ff96674.png)

### Acceptance Criteria

Should be able to complete utxo trades

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
@BitHighlander

**Comment by pastaghost** [comment]
@BitHighlander Can you reproduce this?

**Comment by MBMaria** [comment]
![image](https://user-images.githubusercontent.com/100157997/217409401-ef9be9e5-5a48-4216-8736-f7eeca60b27b.png)
getting these errors in console when playing with different trade pairs.

i was able to do a LTC trade after a refresh. then i refreshed again and couldnt do a trade again. seems to be intermittent

**Comment by 0xdef1cafe** [comment]
@MBMaria can you please retest and close?

**Comment by MBMaria** [comment]
Selecting and populating utxo trades on kk now working.
