### ISSUE TITLE
Deposit into Idle Finance Vaults giving 'Something went wrong error'

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3786]
### Overview

When depositing into an Idle Finance vault for the first time it allows you to select an amount to deposit but when you select continue then it gives a 'Something went wrong' error.
Not sure if its happening to vaults that already have a balance but when i select continue for the amount to deposit it goes through to the sign and broadcast screen so going to assume you can deposit

### References and additional details

1) Log into app.shapeshift and connect to walk of choice
2) Navigate to DeFi page and select the 'Earn' Tab
3) Scroll to find an Idle vault that hasn't been deposited into yet (or use the CTA in Eligible Opportunities)
4) Select Deposit and enter an amount
5) Select Continue and notice the error come up and the continue button spins indefinitely.
*happens on approvals too
![image](https://user-images.githubusercontent.com/100157997/217684026-953729aa-f66a-4978-821e-586b108fe799.png)
![image](https://user-images.githubusercontent.com/100157997/217684071-16b8fb0b-7627-4498-bb53-b2ea0a60f455.png)

### Acceptance Criteria

Should be able to deposit into Idle Vaults

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria this is currently being fixed by the Idle team on-chain, will comment here when that's done so you guys can retest it

**Comment by gomesalexandre** [comment]
@MBMaria this should now fixed on-chain as the new CDO contracts have been added into Idle's registry.
I wasn't able to test an actual deposit, but the pre-deposit, which is calling the same contract method, worked for me. Can we retest this one and close it? 🙏🏽

**Comment by MBMaria** [comment]
Tried this the other day and was successful in depositing. Closing this now.
