### ISSUE TITLE
When enabling Passphrase, the message "Waiting for passphrase"on the KK doesnt disappear after entering the passphrase for the first time

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3788]
### Overview

After enabling passphrase on kk and reconnecting to KK, you are prompted to enter a passphrase on the desktop. The physical KK gives the message "Waiting for passphrase" even after you have entered it on desktop. To get the error message to go away you need to disconnect the KK, refresh the page, reconnect then enter the passphrase on desktop. Then it will show you on the passphrase on the physical KK and ask you to confirm.

### References and additional details

1) Log into Keepkey and in the settings menu under advanced settings enable passphrase
2) Switch to a different wallet then switch back to KK
3) It will prompt to enter a passphrase
4) Enter passphrase and note the physical KK has message "Waiting for passphrase". This doesn't go away or register the passphrase has been entered on desktop
5) Disconnect KK, refresh then reconnect KK
6) Enter passphrase
7) Confirm passphrase on KK

### Acceptance Criteria

Entering the passphrase on desktop should prompt to confirm on KK and "waiting for passphrase" message should disappear

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
This is looking like a race condition. When the `Passphrase.tsx` modal renders the `wallet` is still the previous wallet value:

<img width="1118" alt="Screenshot 2024-03-18 at 12 10 46 PM" src="https://github.com/shapeshift/web/assets/97164662/10dd45a4-f1cd-4d8b-a012-bd2c5b81d8a9">

**Comment by 0xApotheosis** [comment]
> This is looking like a race condition. When the `Passphrase.tsx` modal renders the `wallet` is still the previous wallet value:
> 

It was not a race condition - it was a HDWallet `get` method being unintuitive and defaulting to index `0` 😕
