### ISSUE TITLE
Selecting Cosmos account#0 in mobile app causes app to give the "oops something went wrong" error

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3796]
### Overview

When selecting account 0 for Cosmos in the mobile app either from accounts page or asset page it gives the "oops something went wrong" error

### References and additional details

1) Open shapeshift mobile app and connect to shapeshift wallet
2) Navigate to accounts page and select Cosmos. 
3) Select cosmos account 0, select Cosmos and notice the error

### Acceptance Criteria

Selecting Cosmos shouldn't cause page to crash

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by wesleygravess** [comment]
Going to close this issue. Selecting cosmos account 0 from accounts page or assets page working properly and doesn't give oops error.
