### ISSUE TITLE
Trade widget and trade page in Keepkey gives error message until page is fully loaded

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3797]
### Overview

In KeepKey when selecting an asset pair other then ETH-FOX, the trade widget or trade page will say the pair is either "invalid trade pair" or "sell asset not supported by wallet" or "no receive address fo (asset)" for a bit until the page has fully loaded. Can flicker between diff error messages before saying "preview trade"

### References and additional details

1) Log into app.shapeshift.com and connect to Keepkey
2) Notice the trade widget and its initial error message.
3) Look up BTC in assets and select
4) Notice the trade wigdet have error messages
![image](https://user-images.githubusercontent.com/100157997/217948692-b1fbd6be-d362-45b5-867f-96869d550a8d.png)

### Acceptance Criteria

Trade widget or page should say loading until ready to preview trade rather than having different error messages

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by wesleygravess** [comment]
this is the error we're seeing when the dashboard is loading

<img width="416" alt="Screenshot 2023-02-09 170017" src="https://user-images.githubusercontent.com/99363597/217949133-fd34ecc6-34c3-43cf-affe-de9a6f053b53.png">
