### ISSUE TITLE
New users unable to deposit ATOM/Osmosis to staking

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#3866]
### Overview

When users click on either ATOM or Osmosis staking through earn they are given a dimmed screen but no modal pops up if they have nothing staked. No errors in the console screen, just seems to not be step up properly.

Recreation Steps:
1. Login with a new account with no ATOM or Osmosis staked
2. Attempt to click on the earn opportunity
3. Notice the dimmed screen but no modal 

### References and additional details

N/A

### Acceptance Criteria

New users should be able to deposit ATOM and Osmosis. They should be greeted with the deposit screen

**Comment by gomesalexandre** [comment]
@tshifty this has been fixed in https://github.com/shapeshift/web/pull/3840 and will be released in https://github.com/shapeshift/web/pull/3855 - please close after testing release

**Comment by 0xdef1cafe** [comment]
@tshifty can you please retest and close?

**Comment by tshifty** [comment]
Fixed
