### ISSUE TITLE
Claiming FOX staking rewards fails when not enough ETH for Gas

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3872]
### Overview

When a user goes to claim their FOX staking rewards, they might see an error that "transaction failed" — this is due to not having enough ETH in the wallet to cover gas.

 _As a user if I don't have enough ETH to cover gas, I should see the button on the claim screen as a faded red and the message should be "Not enough ETH for gas"_

(this should be handled the same way we do on trades)

### References and additional details

no additional details. Was able to replicate this.

### Acceptance Criteria

Button should change to "Not enough ETH for gas" when the user attempts to claim rewards without enough ETH for gas.

**Comment by 0xdef1cafe** [comment]
closing as stale
