### ISSUE TITLE
BTC Send Modal not progressing to 'Next' screen if it picks up the bitcoin prefix

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3885]
### Overview

When copy and pasting a BTC address into the send modal and it is populates the prefix bitcoin, it wont allow you to select Next to complete the trade

### References and additional details

1) Log into native wallet on mobile
2) Navigate to BTC account and select Send
3) Paste BTC address into send modal
4) Note that if the prefix bitcoin populates it wont allow you to select Next

### Acceptance Criteria

the send modal should be able to deal with bitcoin addresses that are prefixed with bitcoin: without the user having to manually edit them

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/88504456/235541829-080d09e2-1813-4e13-ae90-af425fdb9848.png">

fixed in prod
