### ISSUE TITLE
XDEFI wallet not switching to Optimism

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3914]
### Overview

When attempting to do an optimism trade, it wont complete the trade and gives a console error "Cannot read properties of undefined (reading 'xdefiId')"

### References and additional details

1) Log into app.shapeshift and connect to xdefi wallet
2) Try to complete optimism trade
3) Note it looks like the trade will go through, can confirm and trade but then it just says on "confirm details" with no other action.
4) Console gives error about reading xdefiId
5) When trying to switch to the Optimism Network in the top right, it gives the same error
![image](https://user-images.githubusercontent.com/100157997/221316458-a2e1887a-5038-4e3b-90bc-8b4286a54f1f.png)
![image](https://user-images.githubusercontent.com/100157997/221316536-3653680a-608a-43a1-9fad-8ba7f90528f6.png)

### Acceptance Criteria

Wallet should change to optimism network if it is listed as an available blockchain

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
closing as hdwallet only supports eth mainnet for XDEFI - @twblack88 to prioritize if we support all chains that XDEFI supports via hdwallet
