### ISSUE TITLE
"Learn More" on dApps page linked to Zendesk

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3915]
### Overview

On the dApps page, the "Learn More" link takes you to zendesk which we no longer support

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to dApps page
3) Select "Learn More"
4) Note that it takes you to Zendesk

### Acceptance Criteria

Learn more shouldn't link to zendesk as its no longer our support system

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
doc.shapeshift.com should be the learn more link
