### ISSUE TITLE
BTC to RUNE shows invalid pair

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#3924]
### Overview

Users trying to trade BTC into RUNE using ThorChain are unable to continue due to an "invalid trade pair"

Recreation Steps:
1. Go to the trade page
2. Input BTC to RUNE trade
3. Notice a red "invalid trade pair" button 
![invalidtradepair](https://user-images.githubusercontent.com/94189400/221646257-8ec68b8f-a5f0-4830-a92f-d52501604904.jpg)

### References and additional details

N/A

### Acceptance Criteria

Users should be able to trade BTC into RUNE.

**Comment by gomesalexandre** [comment]
closed by https://github.com/shapeshift/web/pull/3926
