### ISSUE TITLE
MetaMask: 0x trades not working

### ISSUE THREAD

**Issue by notatooyou** [shapeshift/web#393]
Execute a 0x trade with MetaMask connected. After clicking "Confirm and Trade" button, notice a dead click, or possible an error message saying "Insufficient Gas".

Either way, open console, and notice these errors.
<img width="658" alt="Screen Shot 2021-11-16 at 3 22 18 PM" src="https://user-images.githubusercontent.com/89656210/142076183-d6ea4350-c5b3-44f8-b18a-5748306a1036.png">

**Comment by 0xean** [comment]
working.
