### ISSUE TITLE
Defi Positions: Empty State

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3933]
### Overview

When a user doesn't yet have any defi positions
1. The earn balance would show $0
2. if the user navigates to the earn balance section, it will display featured/eligible opportunities that they can start earning yield in.
*** need mock ups****

### References and additional details

will update with additional details from product once we're ready

### Acceptance Criteria

User with no defi positions, will not see any tables, but will instead see some CTAs around opportunities

**Comment by 0xdef1cafe** [comment]
closed by https://github.com/shapeshift/web/pull/4133
