### ISSUE TITLE
Balance chart for eth/fox LP borked

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3946]
### Overview

The balance chart for eth/fox LP is displaying incorrectly

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to assets page and select Eth chain
3) Select ETH/FOX Pool (UNI-V2) asset and view the Balance chart
![image](https://user-images.githubusercontent.com/100157997/222287644-902cd9e7-1908-414a-b5ca-022efe39deee.png)

### Acceptance Criteria

Balance chart should be an accurate display of the asset balance

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
closing as we can't get market price for this asset
