### ISSUE TITLE
Expected amount on 0x trades changes between modal screens

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3948]
### Overview

When completing a 0x trade, the expected amount will change from when you enter an amount to trade and preview trade

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to trade page
3) Populate a 0x trade
4) Note the expected amount
5) Select Preview trade
6) Note that the expected amount has changed

![image](https://user-images.githubusercontent.com/100157997/222292467-96b9e796-c7a7-4c7c-b874-7af4c2a8822e.png)
![image](https://user-images.githubusercontent.com/100157997/222292476-708ead0c-2995-4e5b-a3ae-0bc733356ace.png)

### Acceptance Criteria

Expected amount should be the same through out the preview trade stages

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
This guy should now be resolved from recent swapper work 👌

<img width="481" alt="Screenshot 2023-04-20 at 2 32 56 pm" src="https://user-images.githubusercontent.com/97164662/233258881-df65c297-2c88-484e-8240-e119e641c11f.png">

<img width="484" alt="Screenshot 2023-04-20 at 2 33 07 pm" src="https://user-images.githubusercontent.com/97164662/233258901-8eb5b02b-6717-49b2-90bd-13d2400319cb.png">
