### ISSUE TITLE
Users unable to send BTC from portis wallet

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#3951]
### Overview

Currently users are unable to send BTC from app.shapeshift.com w/ portis. They are given an error that they are rejecting the transaction but really nothing pops up for them to sign. Below are the console logs for the error:
![btcportiserror](https://user-images.githubusercontent.com/94189400/222316255-12996046-f933-4c5b-bfa7-647070807153.jpg)

Recreation Steps:
1. Login with a portis account to app.shapeshift.com
2. Attempt to make a BTC send
3. Notice the error pops up that you have rejected the transaction

### References and additional details

N/A

### Acceptance Criteria

Users should be able to sign a BTC transaction w/ portis

**Comment by 0xdef1cafe** [comment]
@tshifty would recommend we close as wont-fix and sunset portis instead. lowest lift would be link to a gitbook article about portis being sunset and how to migrate to native wallet
