### ISSUE TITLE
Earn dashboard rewards

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#3959]
### Overview

Seems like we are having some issues with the new grouping earn dashboard rewards.

- Cosmos rewards aren't showing up correctly
- Thorchain savers should not have claimable rewards

### References and additional details

Most likely inside the combined selector

### Acceptance Criteria

Shows the correct reward amounts and claimable rewards.

**Comment by gomesalexandre** [comment]
Closed by https://github.com/shapeshift/web/pull/4072
