### ISSUE TITLE
After refresh on KeepKey wallet fails to load: on new firmware 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#3976]
### Overview

Refresh the page while logged in with KeepKey on app.shapeshift.com. Notice the wallet fails to load after 

### References and additional details

1. go to app.shapeshift.com
2. log in with KeepKey wallet
3. Refresh the page
4. noticed the wallet doesn't load 

### Acceptance Criteria

kk wallet should load after refresh 

### Screenshots/Mockups

<img width="1337" alt="Screenshot 2023-03-06 155015" src="https://user-images.githubusercontent.com/99363597/223227844-fe30aaff-972b-4c0f-a43f-879af051e700.png">

**Comment by purelycrickets** [comment]
@MBMaria can we see if this is still an issue?

**Comment by MBMaria** [comment]
Closing this as you can refresh on keepkey and the page will reload
