### ISSUE TITLE
Swapper: Change location of gas fee errors

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3986]
### Overview

Currently in the swapper, we have multiple error types that appear inside the button. Going forward, we'll need to remove any errors related to 'gas' from the button and pull them out into an error state that will display above the button. The reasoning, is due to bridging— with a bridge sometimes the user will need gas on two different chains (ex: eth and avax) and the button does not provide enough room to display a longer error.

### References and additional details

1. The error for gas should appear above the button
2. In the case when the user doesn't have enough gas, the "preview trade" button should mute/fade and the error would display
3. Please use the yellow error styling
4. Message will state " Insufficient gas" you need at least: [asset amount] on [chain name]
5. 
<img width="400" alt="Screen Shot 2023-03-08 at 10 08 21 AM" src="https://user-images.githubusercontent.com/90058616/223781837-1f27af19-c373-4305-bfd3-64fb9bb2508c.png">

### Acceptance Criteria

As a user, I should see any errors related to insufficient gas in a yellow alert box above the "preview trade" button. I should not be able to continue my trade when this error occurs.

**Comment by purelycrickets** [comment]
No longer relevant
