### ISSUE TITLE
UTXO ThorChain Savers TX's Don't Update to Confirmed on Mobile

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4007]
### Overview

After testing UTXO thorchain savers deposits, going to the asset page and clicking on the TXID from that send shows pending forever. Vault balance also won't update until you close out of the app and reopen it. 

Recreation Steps:
1. Deposit into a UTXO ThorChain Savers Vault on mobile
2. Once that TXID confirms, go to the asset page on mobile and click on the TXID of that send.
3. Notice that pending TX is still there and that DeFi modal hasn't updated native or fiat amounts.

### References and additional details

![Screenshot_20230310_154253_ShapeShift](https://user-images.githubusercontent.com/94189400/224442991-d9016bd7-943d-4371-aa00-e8a871747574.jpeg)
![Screenshot_20230310_154240_ShapeShift](https://user-images.githubusercontent.com/94189400/224443005-0664f0b3-d7e9-489d-8524-a4c0bf566f7e.jpeg)

### Acceptance Criteria

Confirmed ThorChain TXID's should update to confirmed on transaction history on mobile and DeFi overview page should update native and fiat amounts on confirmed as well on mobile.

**Comment by gomesalexandre** [comment]
@tshifty can you confirm that this is happening exclusively within the mobile app and not when using the app from a regular browser on mobile / desktop ?

**Comment by tshifty** [comment]
@gomesalexandre It only does this on the mobile app. Not through the browser on the phone. It's a very weird bug

**Comment by MBMaria** [comment]
FYI, a user is reporting this issue with BTC yields 3/17/23

**Comment by 0xdef1cafe** [comment]
closing as sporadic websocket issues rather than specifically related to savers - any fixable bug would occur consistently on all devices
