### ISSUE TITLE
(ALPHA) V2: Wallets disconnect on refresh

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#407]
From previous discussion this is a feature not a bug.  Can discuss further how we want to handle this in the future. 

On web V2 when a user refreshes the page the wallet disconnects and the user is taken back to the initial"Connect Wallet" screen.

A/C:
When a user refreshed any page on web V2 the connected wallet stays connected.

<img width="1219" alt="Screen Shot 2021-11-17 at 12 03 29 PM" src="https://user-images.githubusercontent.com/57505863/142265976-5cd3411b-472b-4f70-b736-baee9db5b941.png">

**Comment by 0xean** [comment]
@SS-FOX-McCloud - can I bounty this one?

**Comment by SS-FOX-McCloud** [comment]
@0xean Yea, this would be a great bounty if we can find a community member comfortable with this!

**Comment by 0xdef1cafe** [comment]
closing in favor of required groundwork in https://github.com/shapeshift/web/issues/904

and awaiting product spec for wallet "demo mode"
