### ISSUE TITLE
Add error handling to 0x Trade

### ISSUE THREAD

**Issue by DaoDev44** [shapeshift/web#408]
We are currently not showing any feedback to the user for basic trade errors, (ie: input value is less than min trade amount). We need to add some basic error handling for these states:

- User tries to trade an amount that is less than the minimum trade amount.
- User tries to trade more than their balance of that asset.
- User tries to trade, but their ETH balance does not cover the txFee.

**Comment by 0xean** [comment]
resolved in #378
