### ISSUE TITLE
ATOM Claim Amount Zeros Out

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4089]
### Overview

Currently after claiming from a cosmos validator the claim amount zeros out after showing the correct amount. I believe it's actually updating to the real amount after the claim but that's just a theory. It should just hold the amount you just claimed.
<img width="466" alt="Claim0" src="https://user-images.githubusercontent.com/94189400/226450299-5c21ac26-a3ac-4a53-97e0-52d6766af703.png">

Recreation Steps:
1. Claim ATOM
2. Notice on the transaction complete page the amount of ATOM zeros out

### References and additional details

N/A

### Acceptance Criteria

The transaction complete page should hold the claimed amount of ATOM instead of updating to zero

**Comment by 0xdef1cafe** [comment]
@tshifty can you retest this please?

**Comment by tshifty** [comment]
Fixed
