### ISSUE TITLE
Add an "import wallet" option to the Connect Wallet screen

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#4091]
### Overview

As a user coming to ShapeShift, I want to easily be able to see where to import my wallet from another provider

Right now, there is only a "Create one" link on the Connect Wallet screen. It is not clear to a user where to go to import a wallet. We'd like to add an "Import a Wallet" next to "Create one" link that will drop the user directly into the shapeshift import flow. There will be UI copy change to accomodate (see mock up)

Please discuss with @reallybeard regarding design. He tried to do this as Beard oil, but was unable to.

### References and additional details

it should appear here on this modal
<img width="558" alt="Screen Shot 2023-03-20 at 2 46 53 PM" src="https://user-images.githubusercontent.com/90058616/226462280-0a01e24e-d0d3-44a0-ae19-52d49cfcd715.png">

### Acceptance Criteria

A user can import a wallet directly by clicking on the "import wallet" link from the "Connect Wallet" screen
We will need to add tracking to mixpanel

**Comment by purelycrickets** [comment]
Couple of issues here, details in Canny tickets. Will update later in q4

**Comment by twblack88** [comment]
#3521 too, we should wrap this into a spec and merge things
