### ISSUE TITLE
Clicking outside keepkey webusb modal crashes app

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#410]
cancel does the same thing

https://user-images.githubusercontent.com/88504456/142270380-13a12ed7-b65c-4d62-8508-58a6a3722309.mov

**Comment by jdambron** [comment]
This issue seems to have been fixed somehow.
When trying to repoduce I get:
![2021-12-07_13-14](https://user-images.githubusercontent.com/5672954/145027209-012496ea-be3d-401c-ae8f-623796110f9c.png)
The error is properly handled.
I think this issue should be closed.

**Comment by 0xean** [comment]
thanks @jdambron - confirmed this is resolved!
