### ISSUE TITLE
FOXy 7-14 day max withdraw wallet connect issue 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#4103]
### Overview

when making a 7-14 day max withdraw from the foxy vault via wallet connect ex: trust wallet, your position disappears and you are unable to see your pending withdraw and interact with it. Also, if you import your trust wallet seed into a shapeshift wallet you are still unable to see the position. 

### References and additional details

1. go to app.shapeshift.com
2. log in via wallet connect, in this case trust wallet
3. do a 7-14 day max withdraw via foxy vault 
4. notice the position disappears and you are unable to see your pending withdraw

### Acceptance Criteria

your position should not disappear and you should be able to see your position so when the 7-14 days are up, you can claim your funds

**Comment by MBMaria** [comment]
A user has experienced, and i can recreate, on KK. might be across all wallets if you dont already have a pending withdraw. ill test with a native wallet that doesnt have any pending tx's.,

**Comment by MBMaria** [comment]
happens on native as well for any withdrawals , even if there is a pending one. any new withdraw does not appear in the overview screen
