### ISSUE TITLE
Selling with Onramper doesn't allow users to pick the amount they want to sell

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4114]
### Overview

When trying to sell any crypto through onramper it does not allow you to pick the amount and has a preset amount already entered (for ETH it's 0.1). Users should be able to pick the amount they want to sell through our window service.

Recreation Steps:
1. Go through the onramper KYC process.
2. When you get to the selling step you are unable to pick the amount you want to sell and it's hardcoded

### References and additional details

N/A

### Acceptance Criteria

Users should be able to pick the amount of crypto they want to sell through our widget.

**Comment by 0xdef1cafe** [comment]
closing as a problem on the vendor side - nothing we can do here
