### ISSUE TITLE
Osmosis -> Atom trade fail

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#4118]
### Overview

Attempting to trade Osmosis to atom in the trade modal causes an error and the trade fails.

### References and additional details

1. go to app.shapeshift.com
2. log in with native wallet 
3. go to trade modal and choose osmosis -> atom
4. put in amount and click preview trade
5. on confirm page, click confirm and trade
6. notice trade fails 

### Acceptance Criteria

trade should not fail 

### Screenshots/Mockups

https://user-images.githubusercontent.com/99363597/227302277-e09fc949-a5ef-4d9c-b559-9fab8935c480.mp4

**Comment by 0xdef1cafe** [comment]
@MBMaria is this still valid?

**Comment by MBMaria** [comment]
Was just able to complete osmo to atom trade.

**Comment by gomesalexandre** [comment]
@MBMaria Can you confirm the output asset was ATOM on the Cosmos blockchain, and not Osmosis IBC channel ATOM? We currently have another issue being worked on by @pastaghost (https://github.com/shapeshift/web/issues/4400), though it should only happen if you're receiving on an account with no OSMO balance

**Comment by MBMaria** [comment]
https://www.mintscan.io/cosmos/txs/0F399C548144B11AD4E842EB2048CAE4624B1D722DEB93B1E99B2479643374CD
![image](https://github.com/shapeshift/web/assets/100157997/42b5b16a-4465-42f3-872e-e81b020ccc91)

**Comment by gomesalexandre** [comment]
> [mintscan.io/cosmos/txs/0F399C548144B11AD4E842EB2048CAE4624B1D722DEB93B1E99B2479643374CD](https://www.mintscan.io/cosmos/txs/0F399C548144B11AD4E842EB2048CAE4624B1D722DEB93B1E99B2479643374CD) ![image](https://user-images.githubusercontent.com/100157997/237349296-42b5b16a-4465-42f3-872e-e81b020ccc91.jpeg)
> 
> Maybe it is IBC 😬

Looks like you eventually received actual ATOM, all good here!
