### ISSUE TITLE
BTC Account 1 with balance not showing up when logging in with uncached app

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#4164]
### Overview

BTC account 1 with balance not showing up when logging in on uncached version of app. You have to add a BTC account to get account 1 information to show up 

### References and additional details

1. go to app.shapeshift.com
2. empty cache and hard reload
3. log in with native wallet with an BTC balance on account 1
4. to go the accounts page
5. notice BTC account 1 info isnt loading 
6. add a BTC account by clicking the add account button on the top of the accounts page 
7. notice your BTC account 1 information loads

### Acceptance Criteria

BTC account 1 with an available balance should load without having to add an account 

### Screenshots/Mockups

https://user-images.githubusercontent.com/99363597/228939530-1ad7a23d-d17b-4930-b515-1e4b116cf317.mp4

**Comment by 0xdef1cafe** [comment]
closing as incorrect, verified this works
