### ISSUE TITLE
Miner Fee trading out of FOX is $0.00 when entering a USD amount

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4168]
### Overview

When doing a trade out of FOX, the miner fee is $0.00 if you select a USD amount to trade. Selecting an amount in the native token gives an amount for the miner fee.

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Use trade modal on dashboard or navigate to trade page
3) Create a trade out of FOX, entering a USD amount
4) Note that the miner fee is $0.00
5) Select an amount to trade in fox token and note that a miner fee calculates
![image](https://user-images.githubusercontent.com/100157997/228975666-3f78cbec-6397-4a9d-8645-d158aeee5b8e.png)

### Acceptance Criteria

Selecting USD amount should calculate miner fee

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
@0xApotheosis FYI

**Comment by gomesalexandre** [comment]
@MBMaria Can you confirm this state happened with a ZRX or CoW swap? As noted by @0xApotheosis in https://discord.com/channels/554694662431178782/1091123238089785405/1091177027828191263, 0 fee for CoW swaps is actually correct, as there is a 0$ native asset fee i.e CoW fees are taken from your sell ERC20 instead
