### ISSUE TITLE
Large transaction accounts keep prompting users "an update is available 

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4233]
### Overview

When using frame I was able to recreate willy's bug of constantly getting the "an update is available" on app.shapeshift.com.
It seems users with large amounts of transactions get this bug.

Recreation Steps:
1. Using frame, connect something like "vitalik.eth" to app.shapeshift.com
2. Notice that you will get the update button and it will keep coming up after you click it

### References and additional details

N/A

### Acceptance Criteria

Fix the issue where large transaction accounts get prompted to update over and over

**Comment by 0xdef1cafe** [comment]
closing as fixed, tested with @willyogo wallet. fixed in https://github.com/shapeshift/web/pull/4426
