### ISSUE TITLE
CowSwap trades showing incorrect minimum amount

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4234]
### Overview

CoWSwap minimum amount received we display can be higher or lower than the minimum amount that actually is set on the trade. "We may be incorrectly setting the minimum amount on the trade too high, resulting in a high chance that the cowswap trade is never executed (because the rate is above market)" - Willy.

Recreation Steps:
1. Do a CoWSwap trade through app.shapeshift.com and check the TXID for expected amount or just check app.shapeshift.com rate against CoWswap

My Trade: https://explorer.cow.fi/orders/0xbca6cbe39f7ad2511ff594e0a9443f827432e61e290740f633b74b2dd677a814e7f92e3d5fde63c90a917e25854826873497ef3d6435d16b
Willy's Trade Info: https://discord.com/channels/554694662431178782/1094293699355234424/1095448957334859886

### References and additional details

![sscow](https://user-images.githubusercontent.com/94189400/231291145-1bed38a0-4336-4b61-9e76-1648419b0eb8.jpg)
![cow](https://user-images.githubusercontent.com/94189400/231291165-89e2f5ff-fc58-4717-a4fd-db4af1464ef5.jpg)

### Acceptance Criteria

The amounts should be what we get quoted by CoWSwap

**Comment by 0xdef1cafe** [comment]
@tshifty plz retest 🙏

**Comment by tshifty** [comment]
Still get a worse rate than from cowswap

**Comment by woodenfurniture** [comment]
@MBMaria can this issue be closed?

**Comment by MBMaria** [comment]
yep, looks good now, can be closed @woodenfurniture
