### ISSUE TITLE
Send NFT Support

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#4236]
In this product spec, the sending NFT functionality would allow users to securely transfer their NFTs to other users within app.shapeshift.com Here's what it would look like:

Accessing NFT Collection: The user navigates to the dashboard and selects the NFT collection or gallery. This displays all the NFTs owned by the user.

Selecting an NFT to Transfer: The user chooses the specific NFT they want to send by clicking on it. This opens the NFT's detailed view, including its metadata, media assets, and ownership history.

Initiating the Transfer: Within the NFT's detailed view, the user clicks on a "Send" button, which opens a transfer Modal

Entering Recipient's Details: The user inputs the recipient's wallet address, Y.at, or unstoppable domain, etc, in the designated field. Do we want the ability to put a note/message with the transfer?

Review and Confirmation: The user reviews the transfer details, ensuring that the recipient's information is correct. Once they confirm the transfer, they are prompted to sign the transaction using their connected wallet (e.g., MetaMask, keepkey, xdefi, coinbase, brave, etc).

Transaction Processing: The web application submits the signed transaction to the blockchain, where it is processed and confirmed. The user should be able to see the transaction ID of the NFT sent and be able to click on it to see the on-chain information. 

Notification and Update: Once the transaction is confirmed on the blockchain, both the sender and the recipient (if receive address's wallet is being used within the app) receive a notification within the web application. The NFT's ownership is updated in both users' profiles accordingly, and the NFT is removed from the sender's collection and added to the recipient's collection.

**Comment by 0xdef1cafe** [comment]
closing as @willyogo is working on a fully fledged spec
