### ISSUE TITLE
WalletConnect support for Polygon, BSC, Optimism, Avax

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#4248]
### Overview

Abstract
This product specification aims to extend the WalletConnect feature in the ShapeShift App to support Polygon, Optimism, Avalanche, and Binance Smart Chain networks. This will provide users with more options for connecting their wallets and interacting with different blockchain ecosystems, enhancing the overall user experience and broadening the ShapeShift App's reach.

Objectives
Enable WalletConnect support for Polygon, Optimism, Avalanche, and Binance Smart Chain networks in the ShapeShift App.

Ensure seamless wallet connection and interaction across different networks.
Provide clear network selection options and guidance for users.

Maintain compatibility with existing supported networks (e.g., Ethereum).

Ensure the ShapeShift App's features and functionalities work as expected on the newly supported networks.

Implementation
Updating WalletConnect Configuration: Update the WalletConnect configuration in the ShapeShift App to include the RPC endpoints and chain IDs for Polygon, Optimism, Avalanche, and Binance Smart Chain networks.

Network Selection Interface: Modify the wallet connection interface in the ShapeShift App to allow users to select their desired network (Ethereum, Polygon, Optimism, Avalanche, or Binance Smart Chain) before connecting their wallets.

Connecting the Wallet: When a user selects a network and initiates the wallet connection in the ShapeShift App, the WalletConnect feature establishes a connection with the wallet using the appropriate RPC endpoint and chain ID for the selected network.

Network-Specific Functionality: Update the ShapeShift App's features and functionalities to support the newly added networks, ensuring compatibility with each network's smart contract standards, token standards, and transaction formats.

Network Switching: Provide users with the ability to switch between supported networks in the ShapeShift App without disconnecting their wallets. This may involve updating the ShapeShift App's state and refreshing relevant data when a network switch occurs.

User Interface and Guidance: Update the UI in the ShapeShift App to display the currently connected network prominently and provide guidance for users about the implications of using different networks (e.g., transaction fees, supported tokens, and available features).

Testing and Validation: Thoroughly test the WalletConnect feature and the ShapeShift App's functionalities on each supported network, ensuring a seamless and secure user experience through WalletConnect to L2 Dapps. 

By implementing this product spec, the ShapeShift App will offer WalletConnect support for Polygon, Optimism, Avalanche, and Binance Smart Chain networks, expanding its compatibility and enhancing the user experience across multiple blockchain ecosystems.

### References and additional details

Resources
[WalletConnect Documentation](https://docs.walletconnect.org/)
[Optimism Developer Documentation](https://community.optimism.io/docs/)
[Avalanche Developer Documentation](https://docs.avax.network/)
[Binance Smart Chain Developer Documentation](https://docs.binance.org/)

### Acceptance Criteria

Testing and Validation: Thoroughly test the WalletConnect feature and the ShapeShift App's functionalities on each supported network, ensuring a seamless and secure user experience through WalletConnect to L2 Dapps.

**Comment by 0xdef1cafe** [comment]
closing this, we are not making changes to v1 and this will work when v2 is ready upstream
