### ISSUE TITLE
CTA Mercle NFT (Foxatar) Minting if user hasn't minted one yet

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#4250]
### Overview

Abstract
This product specification aims to introduce a targeted call to action (CTA) for minting a Mercle soul-bound NFT (Foxatar) within the ShapeShift App, specifically targeting users who have not yet minted the Foxatar in the app. The CTA will be designed to catch the attention of these users, guiding them toward the NFT minting process and encouraging engagement with the app's NFT capabilities highlighting that it is "free" to mint!

Objectives
Design a visually appealing and attention-grabbing call to action for Foxatar minting targeted at those who haven't minted yet. 

Seamlessly integrate the CTA into the ShapeShift App's user interface for users who have not minted a Foxatar yet.

Encourage user engagement with the Foxatar minting, specifically targeting those who haven't minted one yet.

Implementation
CTA Design: Collaborate with the UI/UX Designer to create a visually appealing and attention-grabbing call to action that clearly communicates the ability to mint an NFT within the ShapeShift App for first-time minters. The design should be consistent with the overall look and feel of the app and easily distinguishable from other elements on the page.

### References and additional details

Resources
[Polygon NFT Documentation](https://docs.polygon.technology/docs/develop/nfts)
[IPFS for decentralized storage](https://ipfs.io/)

### Acceptance Criteria

a CTA that brings users with out a Foxatar to a modal to mint their Foxatar once clicked upon!

**Comment by twblack88** [comment]
[full spec is here](https://www.notion.so/shapeshift/Mercle-FOXatar-e2f752faf4964474a928ffb6c1b697a3?pvs=4) pending tech spike for end of this week. We'll likely close this and open corresponding tickets depending on bandwith.

**Comment by twblack88** [comment]
this is live in the carousel now
