### ISSUE TITLE
Osmosis trade issues

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4253]
### Overview

Sends and trades with osmo not working

### References and additional details

1) Log into app.shapeshift and connect to a native or kk 
2) Try to send osmo from one address to another
3) Notice the send does not complete and an error of "your send of osmosis failed" appears
4) Navigate to trade page and attempt an atom to osmo trade
5) Note that that atom will send, but the trade will not complete.
6) Check osmo address on mintscan and note that there will be a balance of atom on osmosis, but it does not convert to osmo
![image](https://user-images.githubusercontent.com/100157997/231621739-59eb5faf-931c-4220-923d-d667f243f547.png)
<img width="235" alt="image" src="https://user-images.githubusercontent.com/100157997/231621754-c46f6bb7-d452-4667-b56c-2cccff75e905.png">
![image](https://user-images.githubusercontent.com/100157997/231624057-f472d4c0-335b-4dd9-ae4a-18b7eb099fe1.png)
![image](https://user-images.githubusercontent.com/100157997/231624097-339dfbcf-978a-4e84-bbe1-9e299b01f448.png)

<img width="766" alt="image" src="https://user-images.githubusercontent.com/100157997/231623057-1d32dbc2-c0e2-4176-a82b-9c5d9bddd303.png">

### Acceptance Criteria

Should be able to complete osmo sends and trades

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
FYI when attempting atom to osmo trade on kk, when confirming steps on the kk itself, the trade modal zero's out before trade completes @BitHighlander @pastaghost 
![image](https://user-images.githubusercontent.com/100157997/231623673-73e8f680-e1a3-42d6-aa04-99303372ea67.png)

**Comment by MBMaria** [comment]
Osmo sends now working.
Trades still a litte funky. The amount of osmo being received after a trade is different to the amount that is listed in the expected amount from the confirm and trade screen. 
![image](https://user-images.githubusercontent.com/100157997/235547399-0d7e6fe2-4ff7-40a5-bd0e-3d74fdc43525.png)
![image](https://user-images.githubusercontent.com/100157997/235547410-12bbf501-026c-40a8-8826-5c0cb9a87964.png)

**Comment by purelycrickets** [comment]
nope
