### ISSUE TITLE
Switching between Eth and Avax causes MM pop up to show fees in previous chain amount

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4257]
### Overview

After completing and ERC-20 to Eth trade then entering an Avax to assset on Avalanche trade, when confirming the trade, it asks to switch networks. Despite switching the network, it still displays the fee in ETH even though it is an Avalanche trade

### References and additional details

1) Log into app.shapeshift and connect to MM
2) Navigate to trade page and complete an ERC-20 to ETH trade
3) Once completed, enter an Avax to Asset on Avalanche trade, i.e avax to weth on avalanche
4) Confirm and trade and wait for MM pop up to ask to switch from ETH to AVAX chain
5) Switch networks and note that the MM pop to confirm the trade displays fees in ETH even though it is an Avalanche trade
![image](https://user-images.githubusercontent.com/100157997/231671386-51209fb8-4214-4a0a-ad7c-1a808f6025f5.png)

**note that the trade modal zero's out the value - but you can still complete the trade and it will charge gas fee in correct crypto

### Acceptance Criteria

Fees should be displayed in the asset of the chain that the trade is being completed on 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Tested on prod, confirmed fixed by https://github.com/shapeshift/web/pull/4255
