### ISSUE TITLE
Realign UX for default asset selection

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#4270]
### Overview

Currently the UX for default asset selection for trading is confusing and does not appear to adhere to any definitive spec. 

We require a holistic solution that will initially set sane defaults and then stay out of the users way for the duration of their session.

### References and additional details

Most of the logic relating to this task is contained in the following files:
- `src/components/Trade/Trade.tsx`
- `src/components/Trade/hooks/useDefaultAssets.tsx`

### Acceptance Criteria

- Opening the app initially defaults to "from ETH" and "to FOX" on the ethereum network (independent of the currently selected network on the wallet)
- Wallet network selection is independent of token selection in trade UI so a users selection is not modified by actions unrelated to trading
- No action from the user will trigger defaulting to initial state except reloading the page
- In the dashboard, clicking an asset under "Wallet Assets" loads the page for that asset and pre-populates the trade assets on that page:
  - the "From" asset will be the base asset for the network (e.g for avalanche network it will be ETH on avalanche)
  - the "To" asset will be the asset for that page, if it is supported by the app
  - if it is NOT supported by the app, fall back to the native asset for the network (e.g for avalanche network it will be AVAX on avalanche)

### Estimated effort

half day

**Comment by woodenfurniture** [comment]
> the "From" asset will be the base asset for the network (e.g for avalanche network it will be ETH on avalanche)

I'm going to not implement this and keep the currently selected asset for the "from" asset to minimise cognitive load to user - the only change will be the amounts clearing and the "to" asset will be updated as per spec above

**Comment by willyogo** [comment]
this sounds lovely ser
