### ISSUE TITLE
Approvals for LIFI trades needs gas amount displayed

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4272]
### Overview

When completing a LIFI trade on Native that has a gas fee other than eth, it should be displayed in the amount and chain that it is charged in. 

### References and additional details

1) Log into develop.shapeshift and connect to native wallet
2) Navigate to trade page and enter LIFI trade that requires an approval (i.e usdc on optimism to avax)
3) Confirm and trade and note the approval step comes up
4) Note that the approval modal does not display a fee, appears as tho it is $0.00 and it costs 0 eth
![image](https://user-images.githubusercontent.com/100157997/231930537-787c91b3-8c34-469a-af67-557356dbebf5.png)

### Acceptance Criteria

Approvals should have gas fee displayed

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by woodenfurniture** [comment]
closing as this appears to have been resolved in #4241
![image](https://github.com/shapeshift/web/assets/125113430/a39b9217-32b2-44d9-867d-53d5a062f689)
