### ISSUE TITLE
MM default trade asset pair switching to match the chain that is selected

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4273]
### Overview

When a chain different to Ethereum is selected on MM, the default trade pair will change to match the chain when you select the output asset

### References and additional details

1) Log into app.shapeshift and connect to MM
2) From the dashboard switch the network from eth to something else like optimism or bnb
3) Click on the trade page
4) Return to dashboard
5) Clicked the output asset
6) Note the assets changed to the chain that's connected

https://user-images.githubusercontent.com/100157997/231930980-d696d650-e721-4ad0-ba28-69853233f95a.mp4

### Acceptance Criteria

Default asset pair should remain eth-fox unless changed, even if connect to a different chain

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
Resolved 👌
