### ISSUE TITLE
Trade modal not refreshing when needed

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4274]
### Overview

When entering details for a trade, the trade modal keeps the amounts even when you switch pages, complete a trade or switch wallets on a completed trade screen

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to trade page and complete a trade
3) Note the trade's completed tick then select dashboard
4) Note the trade modal has the details of the last completed trade
![image](https://user-images.githubusercontent.com/100157997/231931598-fc30c721-8203-47ec-839b-c23cc5fa98c3.png)
![image](https://user-images.githubusercontent.com/100157997/231931607-1d63f0f4-5b65-4fba-921c-48bf4f1784e4.png)

**note the trade modal did not refresh when switching wallets on a completed trade screen
**when refreshing native wallet after completed a trade out of eth on optimism, the trade modal default pair became eth on optimism and optimism
![image](https://user-images.githubusercontent.com/100157997/231931824-e4c6d27e-4273-4582-bbe0-56efb9e08f20.png)

### Acceptance Criteria

Trade modal should refresh after completing a trade or switching paged or wallets

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
@MBMaria this should now be fixed, though I'll need to test ones UTXO swaps are enabled again so I can do a cheap trade to test.

**Comment by MBMaria** [comment]
@0xApotheosis I've just been looking at the trade modal now and its much better than it was. however, if you choose a different asset in the input or output , that will carry across the modal on all pages when selecting a trade. 
For example, on the dashboard, if i switch the asset pair to ETH -> BTC then navigate to the trade page, it will have ETH -> BTC populated. 
If i now go to the arkeo airdrop page and select "trade for FOX" under FOX Token Holders then the ETH -> BTC pair is loaded in the trade modal, when i think it makes sense it would be ETH -> FOX. 
And this modal as well from the FOX opportunities page. 
![image](https://user-images.githubusercontent.com/100157997/234721318-1d91a2a2-ecee-4af9-bfe8-556bf15ac7cd.png)
