### ISSUE TITLE
Enable RUNE onramping via Banxa

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#4283]
### Overview

Just noticed that Banxa added support for RUNE onramping (https://banxa.com/)

Can we enable this? 

### References and additional details

n/a

### Acceptance Criteria

AC:
1. RUNE is added to the list of assets available to Buy, with Banxa as the provider
2. THORChain is added to the list of chains to filter by
3. If a user selects THORChain, they see RUNE
4. If a user selects RUNE, they see Banxa as an available provider
5. If a user clicks Banxa with RUNE selected, the Banxa buy flow is opened in a new window and the users' RUNE address and asset selection are passed through

**Comment by gomesalexandre** [comment]
@willyogo tried building a partner URL using the same parameters as the ones Banxa are using in their landing page (`https://checkout.banxa.com//?fiatAmount=100&fiatType=USD&coinAmount=56.65659463&coinType=RUNE&lockFiat=true&blockchain=THORCHAIN&orderMode=BUY`), unfortunately it is not supported yet.

Added the `blocked` tag until this is supported upstream - when that's done, we can simply apply this patch to support it:

```diff
diff --git a/packages/caip/src/adapters/banxa/index.ts b/packages/caip/src/adapters/banxa/index.ts
index 92301df4d..5eaf02f93 100644
--- a/packages/caip/src/adapters/banxa/index.ts
+++ b/packages/caip/src/adapters/banxa/index.ts
@@ -16,6 +16,8 @@ import {
   ethChainId,
   optimismAssetId,
   optimismChainId,
+  thorchainAssetId,
+  thorchainChainId,
 } from '../../constants'
 
 /**
@@ -28,6 +30,7 @@ const AssetIdToBanxaTickerMap = {
   [ethAssetId]: 'eth',
   [avalancheAssetId]: 'avax',
   [optimismAssetId]: 'eth',
+  [thorchainAssetId]: 'rune',
   'eip155:1/erc20:0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9': 'aave',
   'eip155:1/erc20:0xbb0e17ef65f82ab018d8edd776e8dd940327b28b': 'axs',
   'eip155:1/erc20:0x4d224452801aced8b2f0aebe155379bb5d594381': 'ape',
@@ -83,6 +86,7 @@ const chainIdToBanxaBlockchainCodeMap: Record<ChainId, string> = {
   [cosmosChainId]: 'COSMOS',
   [avalancheChainId]: 'AVAX-C', // note - the AVAX-C chain is not the same as the AVAX "ticker" on the banxa side
   [optimismChainId]: 'OPTIMISM',
+  [thorchainChainId]: 'THORCHAIN',
 } as const
 
 /**
```

**Comment by purelycrickets** [comment]
@willyogo do you want to follow up with Banxa to see if this has been fixed yet?

**Comment by willyogo** [comment]
> 

You bet, just pinged them discord (https://discord.com/channels/554694662431178782/1136046536585908364/1146206257074671616)

**Comment by willyogo** [comment]
Confirmed that RUNE has been enabled for ShapeShift on Banxa's end @gomesalexandre 🎉 

https://shapeshift.banxa.com//?fiatAmount=100&fiatType=USD&coinAmount=56.65659463&coinType=RUNE&lockFiat=true&blockchain=THORCHAIN&orderMode=BUY

They also shared this doc of assets they support so we could spot any others that may be missing: https://docs.google.com/spreadsheets/d/1KU6J1Hl4vxBTIWCwWdrFfSadNltuFheQRoJyPrd0LMQ/edit#gid=366537232

If there are any others @shapeshift/product would like to enable, can ping @maaak in Banxa's Discord partner thread.
