### ISSUE TITLE
Sending BCH on KK fails on app.shapeshift.com

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4321]
### Overview

Currently when a user tries to send BCH w/ KK on app.shapeshift.com, the KK blinks and never prompts the user to send.

Recreation Steps:
1. Connect a KK with a BCH balance to app.shapeshift.com
2. Attempt to send BCH
3. Notice it fails and your KK is never prompted

### References and additional details

<img width="471" alt="BCHunabletosign" src="https://user-images.githubusercontent.com/94189400/233489095-d87f6be1-b970-4e12-93cc-6ec86b008005.png">

### Acceptance Criteria

Users should be able to send BCH w/ KK on app.shapeshift.com

**Comment by BitHighlander** [comment]
This issue was fixed on KK desktop via this commit

https://github.com/keepkey/keepkey-desktop/commit/bf43491ef4acebe58574883fc45e72d0415dc860

Appears it was broke on shapeshift back in Feb. 5

**Comment by BitHighlander** [comment]
@0xdef1cafe looks like we need addresses to contain the "bitcoincash:" prefix to match the tests in HDwallet. I will be working on a PR that adds this into chain adapters with similar logic for non desktop users.
