### ISSUE TITLE
"FOX Opportunities" page blank for 60s on demo wallet

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#4327]
### Overview

The `FOX Opportunities` page will remain blank for around 60s after initial load when connected to the demo wallet. Eventually some network requests time out and the page renders.

https://app.shapeshift.com/#/fox

### References and additional details

![image](https://user-images.githubusercontent.com/125113430/233518876-de372e48-729e-4022-9cda-6f2e18b9b90d.png)

![image](https://user-images.githubusercontent.com/125113430/233519182-0d518a6c-541f-4193-94bb-43acfab79c77.png)

![image](https://user-images.githubusercontent.com/125113430/233519200-bd2c3110-5a08-44c5-853a-831f480ffc4e.png)

### Acceptance Criteria

The `FOX Opportunities` page should render and not be blocked by the network requests that are failing. If these are required to render details on the page, some loading state should be rendered within the page instead of being completely blank.

### Estimated effort

half day

**Comment by 0xdef1cafe** [comment]
#4325 or #4342 or #4292 seem to have fixed this
