### ISSUE TITLE
Add Idle Finance Clearpool USDC Senior Tranche and Clearpool Portofino DAI junior tranche to Earn Section.

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#4331]
### Overview

Per group DM with idle.finance, they have told us that their Clearpool USDC Senior Tranche and the Clearpool Portofino DAI Senior and Junior tranche have reached their minimum required TVL and can now be added to our earn section. 

### References and additional details

Replicate other Idle Finance opportunities for the senior/junior tranches but directed at these new opportunities. 

### Acceptance Criteria

Adding the  Clearpool Portofino USDC Senior Tranche and Clearpool Portofino DAI Senior/Junior tranches to the earn section and being able to deposit into them like the other Tranches.

**Comment by gomesalexandre** [comment]
@tolltalcrypto we already have support for those opportunities
<img width="780" alt="image" src="https://user-images.githubusercontent.com/17035424/234388488-d28afe20-a421-4bc1-b289-68e0da1249be.png">
<img width="775" alt="image" src="https://user-images.githubusercontent.com/17035424/234388575-1d178cc5-d3b9-4bca-992b-b2b546a25c7f.png">

Double checked against Idle's API and those are indeed the correct contract addresses. We could theoretically close this one already, but will author a migration that will close this issue as a paranoia step.
