### ISSUE TITLE
UNI-V2 ETH/FOX Pool Gas Estimation Error

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4349]
### Overview

Right now users are unable to deposit or interact with ETH/FOX UNI-V2 through app.shapeshift.com and get the errors below when they attempt to.
![unigas](https://user-images.githubusercontent.com/94189400/234418885-d4314171-e018-487f-bf98-0233f19696eb.png)

### References and additional details

"{"reason":"execution reverted: UniswapV2Router: INSUFFICIENT_A_AMOUNT","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0x7a85293dfC50432aC88f53A119597B09Eb170232","to":"0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D","value":{"type":"BigNumber","hex":"0xe878daffdaab"},"data":"0xf305d719000000000000000000000000c770eefad204b5180df6a14ee197d99d808ee52d000000000000000000000000000000000000000000000000da3722b02c60d3df000000000000000000000000000000000000000000000000d91fd1dfeeb7622c0000000000000000000000000000000000000000000000000000e74f4a8b5ffa0000000000000000000000007a85293dfc50432ac88f53a119597b09eb17023200000000000000000000000000000000000000000000000000000187ba6d8c64","accessList":null},"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":78596,\"error\":{\"code\":3,\"message\":\"execution reverted: UniswapV2Router: INSUFFICIENT_A_AMOUNT\",\"data\":\"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000026556e69737761705632526f757465723a20494e53554646494349454e545f415f414d4f554e540000000000000000000000000000000000000000000000000000\"}}\n","error":{"code":3,"data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000026556e69737761705632526f757465723a20494e53554646494349454e545f415f414d4f554e540000000000000000000000000000000000000000000000000000"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"value\":\"0xe878daffdaab\",\"from\":\"0x7a85293dfc50432ac88f53a119597b09eb170232\",\"to\":\"0x7a250d5630b4cf539739df2c5dacb4c659f2488d\",\"data\":\"0xf305d719000000000000000000000000c770eefad204b5180df6a14ee197d99d808ee52d000000000000000000000000000000000000000000000000da3722b02c60d3df000000000000000000000000000000000000000000000000d91fd1dfeeb7622c0000000000000000000000000000000000000000000000000000e74f4a8b5ffa0000000000000000000000007a85293dfc50432ac88f53a119597b09eb17023200000000000000000000000000000000000000000000000000000187ba6d8c64\"}],\"id\":78596,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://ethereum-svc.unchained.svc.cluster.local:8332/%22%7D%7D"

### Acceptance Criteria

Users should be able to interact with ETH/FOX UNI-V2 Pool without running into the gas estimation error.

**Comment by kaladinlight** [comment]
We are currently calculating the asset pair rate using fiat values which has no correlation with the underlying values in the univ2 pools. Depending on the fiat rates provided at the time, this can result in invalid trades/estimations. We should update our calculations to query the pool reserves to find the price conversion in order to accurately provide a 50/50 split conversion.
