### ISSUE TITLE
Lifi trades with input of Eth on Optimism not working

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4350]
### Overview

when trying to trade eth on optimism to bnb on bnb the trade is failing on native and on KK the trade modal keeps resetting on confirm and trade and doesn't complete

### References and additional details

1) Log into app.shapeshift and connect to native wallet
2) Navigate to trade page and enter an Eth on Optimism to anything trade
3) Preview trade and Confirm and trade
4) Note that the trade modal continues to spin as pending even tho a tx shows up in recent transactions as a failed send.
(On KK, the trade modal will confirm and trade will disappear for a bit then become available again to select. Prompts on kk itself are slow and don't execute the trade)
![image](https://user-images.githubusercontent.com/100157997/234437472-22cdfb91-2b76-48a7-b717-32407d535ef8.png)
https://optimistic.etherscan.io/tx/0x12c4d770a1b666f4b840ef9c03325697116cba4d8f4c6a2c0f31a27292b07831
https://user-images.githubusercontent.com/100157997/234437329-3fb99d64-4d32-4fcd-b47a-bb8d9b7d1433.mp4

 

### Acceptance Criteria

Should be able to complete a trade from Eth on Optimism 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by woodenfurniture** [comment]
Looks like a gas estimation bug in the lifi swapper. Gas fee is estimated as `$0.00291` for ETH on optimism -> MATIC (clearly wrong).

Backend is protecting us, returns code 400 with `{"message":"invalid transaction: insufficient funds for gas * price + value"}`.

Fixing now.

**Comment by woodenfurniture** [comment]
After a bit of investigation it looks like this is actually caused by us sending a trade when there is insufficient balance to cover fees of the receiving chain. The UI state management currently assumes that protocol fees are always in the sell asset, however with lifi trades there can also be protocol fees in the buy asset.
