### ISSUE TITLE
Add promo for DOGE

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#4365]
### Overview

Add promo card for DOGE

### References and additional details

https://docs.google.com/document/d/1obkZtDRob0auK2X5VvEDH2InEE9JexmsEnLDm9gVu5k/edit

Use the doge icon for the image.

### Acceptance Criteria

A promo card for doge shows up on the site and has a cta to get into a savers vault.

**Comment by 0xdef1cafe** [comment]
closed in https://github.com/shapeshift/web/pull/4388
