### ISSUE TITLE
BCH output for ThorChain trades always comes up "sell amount lower than the fee"

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4382]
### Overview

Currently, when a user tries to trade into BCH they are always given "sell amount lower than the fee" no matter whatever you type in.

Recreation Steps:
1. Attempt to try a trade with BCH the output coin
2. Notice that you always get "sell amount lower than the fee" 

### References and additional details

N/A

### Acceptance Criteria

Users should be able to trade into BCH using ThorChain

**Comment by MBMaria** [comment]
Noticing this is happening when RUNE is the input asset as well
![image](https://user-images.githubusercontent.com/100157997/235561788-c6ae0e48-b2c5-4ec9-a4d5-fe84488581fa.png)
