### ISSUE TITLE
RUNE shows up as "invalid trade pair" when it's an output coin

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4383]
### Overview

Currently, users are unable to trade into RUNE as they are always given "invalid trade pair" when it's the output coin using ThorChain.

Recreation Steps:
1. Attempt to buy rune with ThorChain using app.shapeshift.com
2. Notice you get "invalid trade pair" for every coin supported by ThorChain

### References and additional details

N/A

### Acceptance Criteria

Users should be able to trade into RUNE using ThorChain w/ app.shapeshift.com

**Comment by 0xApotheosis** [comment]
I fixed this guy in https://github.com/shapeshift/web/pull/4338/commits/62d2abdbe0d8b00ba4ebd9eba2b64e330b54c59d as part of the monadic errors release 👌
