### ISSUE TITLE
Swapper - flaky max button behavior

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4384]
### Overview

Currently, users are unable to hit max when trying to trade WETH on Polygon w/ MetaMask. Seems to be the only coin affected for some reason.

Recreation Steps:
1. Have WETH on Polygon on a MetaMask wallet
2. Attempt to hit max when trading WETH on Polygon
3. Notice it dead clicks and never loads anything

### References and additional details

N/A

### Acceptance Criteria

Users should be able to hit max when trading WETH on Polygon w/ MetaMask

**Comment by tshifty** [comment]
On a second look, this happens with native wallet as well

**Comment by woodenfurniture** [comment]
This issue was unlinked to #4567 because polygon was unavailable during testing. Needs retest to close

**Comment by woodenfurniture** [comment]
closing due to removal of max button
