### ISSUE TITLE
ATOM to Osmosis Trades Without a Osmosis Balance Fail

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4400]
### Overview

Currently, users without a balance of Osmosis are unable to swap from ATOM to Osmosis because of the minimum fee on the osmosis protocol.

Recreation Steps:

1. Have a wallet with just ATOM in it
2. Attempt to swap ATOM to Osmosis
3. Notice the error and only having CosmosHub

Options we have to fix this: 
- One option is to disable swaps into Osmosis for users who do not have an existing OSMO balance sufficient to cover fees. 

- Another option is to allow the user to select Osmosis as the buy asset, but to inform the user that the trade cannot be performed in the event that there is an insufficient OSMO balance.

- For a third option, it may actually be possible for the user to pay the transaction fees denominated in ATOM on Osmosis. Notice that in the Swap Fees section at https://osmosis.gitbook.io/o/liquidity-providing/fees, the documentation specifies that the fee is paid by the trader in the form of the input asset. I've got an idea of how to go about this, and can play around to see if this works.

### References and additional details

N/A

### Acceptance Criteria

Users should be able to bridge ATOM to Osmosis seamlessly

**Comment by MBMaria** [comment]
This is still an issue 
![image](https://github.com/shapeshift/web/assets/100157997/a66ea944-4c70-40d0-b845-c48f24551448)
![image](https://github.com/shapeshift/web/assets/100157997/88cf721b-b14f-4094-af8e-ff89250cc991)
![image](https://github.com/shapeshift/web/assets/100157997/d475525d-86a1-4ebd-830b-bda2067f4ea4)

**Comment by purelycrickets** [comment]
nah
