### ISSUE TITLE
osmo tx history not upserted correctly

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4404]
### Overview

@0xApotheosis was unable to create an Account 1 for Osmosis even though there are transactions in Account 0

### References and additional details

1) Log into app.shapeshift and connect to native wallet
2) Navigate to "Wallet" and go to Add Account
3) Add Osmosis Account 1 
4) Note Error:  
![image](https://user-images.githubusercontent.com/100157997/235818107-ae2e7c00-8982-4a7b-b310-26d19d8a6ada.png)

*unable to be recreated if you already have an account 1. i.e It doesn't occur when adding account 2

### Acceptance Criteria

Should be able to add account 1 if meet requirements

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@0xApotheosis do you have exact repro steps on this one? I was able to create an account 1, with a new wallet and an account 0 that was fresh and just used to receive dust

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/17035424/235957998-cd2da6e0-0182-4b59-9472-92ec42eb4726.png">

**Comment by 0xApotheosis** [comment]
@gomesalexandre Ah, so indeed I don't seem to have any transactions showing in the Osmosis history, despite having a balance:

<img width="1028" alt="Screenshot 2023-05-04 at 10 47 41 am" src="https://user-images.githubusercontent.com/97164662/236081569-8549a013-90ab-4299-86db-ca6cf9cb8a55.png">

**Comment by 0xdef1cafe** [comment]
updated PR title as i'm seeing osmo txs come in over the network but not appearing in the UI

the originally reported bug of not being able to add an additional account will be automatically fixed when are correctly handling tx history

**Comment by purelycrickets** [comment]
nomo osmo
