### ISSUE TITLE
Send accurate portfolioBalance data to Mixpanel

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#4408]
### Overview

Mixpanel's ability to display Assets in Orbit data is awesome, but for some reason, a small handful of users have portfolio balances that appear too good to be true.

Please investigate these users in Mixpanel to determine whether or not their portfolio balance is accurate, and if not, update the way that Mixpanel tracks portfolio/asset balances to ensure that no false data is tracked.

### References and additional details

Users with highest portfolio balances in Mixpanel:
$4,804,428,580.48: https://mixpanel.com/project/2933919/view/3436921/app/profile#distinct_id=187e180aacd83-0a5331519ec9ac-26031b51-10e26d-187e180aace1adb
$881,909,944.49: https://mixpanel.com/project/2933919/view/3436921/app/profile#distinct_id=187dfa872272f3-0d68a88c5165e18-1d41661c-4a640-187dfa87229419
$519,721,036.25: https://mixpanel.com/project/2933919/view/3436921/app/profile#distinct_id=187d040693652b-0268e93a9d5f38-26031b51-fa000-187d0406937b2b
$19,7361,288.92: https://mixpanel.com/project/2933919/view/3436921/app/profile#distinct_id=1877d3dbd9a112-0e960ffbfd2197-414d7500-448e0-1877d3dbd9bf5
$88,159,425.47: https://mixpanel.com/project/2933919/view/3436921/app/profile#distinct_id=187a0b27c46520-06d8aff9fde52b-7e57547d-f3000-187a0b27c471376
$21,041,294.09: https://mixpanel.com/project/2933919/view/3436921/app/profile#distinct_id=1873b272ec92d1-0d0fccc1ccfff6-7a545471-144000-1873b272ecae6c
$19,785,073.94: https://mixpanel.com/project/2933919/view/3436921/app/profile#distinct_id=1877cdc6f8d1ca-0293b4ad146903-26031951-1fa400-1877cdc6f8e9f6
$18,201,132.84: https://mixpanel.com/project/2933919/view/3436921/app/profile#distinct_id=18775a477f733a-011b97e44ca4818-39176950-4a640-18775a477f8ae9
$11,004,878.15: https://mixpanel.com/project/2933919/view/3436921/app/profile#distinct_id=186c8c7372376e-05ceef2ed672c2-1f525634-1aeaa0-186c8c73724bc8

### Acceptance Criteria

AC:
1. Portfolio/asset balance data sent to Mixpanel is never greater than the portfolio/asset balance displayed to the user in the app

**Comment by willyogo** [comment]
thanks for taking a look 🙏  once we confirm that the portfolio balance data for these users is incorrect, lmk and I can delete the incorrect data from mixpanel

**Comment by willyogo** [comment]
Investigated the first user with 0xdef1 and confirmed that the portfolio balance was incorrect. the app thought the user had $4.8B of SWP on polygon (https://polygonscan.com/address/0xabede05598760e399ed7eb24900b30c51788f00f), but we're not sure why yet. Deleted the user's property and continuing to investigate.

$4,804,428,580.48: https://mixpanel.com/project/2933919/view/3436921/app/profile#distinct_id=187e180aacd83-0a5331519ec9ac-26031b51-10e26d-187e180aace1adb

**Comment by willyogo** [comment]
Investigated the largest whale and it while it looks like the portfolioBalance could actually be accurate, it's unclear whether the user actually controls the wallet or just connected a whale wallet via walletconnect that they don't actually control. Not sure what the best way to handle this would be.. perhaps a separate view of AIO that is filtered to only include wallets that have executed at least one transaction 🤔 

https://mixpanel.com/project/2933919/view/3436921/app/profile#distinct_id=187e7e04feb105-010d9f32e0b913-1e4f173f-46500-187e7e04fec96

**Comment by 0xdef1cafe** [comment]
closing until this crops up again as we haven't seen it since the last safeguards were implemented

**Comment by willyogo** [comment]
Added a version of the AIO table that's filtered to only include users that have executed at least 1 tx:
https://mixpanel.com/s/1obHre

it almost seems too low now, but at least isn't impossibly large
