### ISSUE TITLE
Trigger event in Mixpanel whenever a user connects to a dapp via WalletConnect

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#4413]
### Overview

As a dao stakeholder, i want to know how frequently users are connecting to dapps via WalletConnect as well as which dapps they're connecting to on which chains.

### References and additional details

n/a

### Acceptance Criteria

AC:
1. When a user connects to a dapp on mixpanel, an event "Dapp Connected" is triggered
2. Properties of the event include Dapp: [ie. Uniswap] and Network: [ie. Arbitrum]

**Comment by 0xdef1cafe** [comment]
this is already implemented https://github.com/shapeshift/web/blob/develop/src/plugins/walletConnectToDapps/components/DappRegistryGrid.tsx#L52

**Comment by willyogo** [comment]
we do trigger an event when users click a dapp on the /dapps page, but we don't currently trigger an event when a user actually uses WalletConnect to connect to a dapp. this issue is to give us insight into if/how users are using the WalletConnect integration.
