### ISSUE TITLE
ThorChain trades never stop spinning even when users have received funds 

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4414]
### Overview

We have never had confirmations green check marks working for ThorChain trades. It's a pain point for users because they think they haven't completed the trade and stay on the screen even though they have received their funds from the trade.

Recreation Steps:
1. Do any ThorChain trade
2. Notice the icon keep spinning like the trade hasn't completed forever

### References and additional details

N/A

### Acceptance Criteria

Users should get a green checkmark once they have received their funds

**Comment by 0xApotheosis** [comment]
Hey @tshifty. I can't replicate this, I'm getting the green tick on trade confirmation for THORTrades:

<img width="678" alt="Screenshot 2023-05-09 at 5 18 40 pm" src="https://user-images.githubusercontent.com/97164662/237023067-44dbd9d4-9179-42be-977d-3325e83d0516.png">

Can you please confirm if this is still an issue, or if there are certain cases in which it doesn't work?
