### ISSUE TITLE
Consolidate individual UTXO transactions into a single row in tx history

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#4422]
### Overview

Currently, the app breaks down a UTXO transaction into multiple rows in the tx history: a send tx for each UTXO consumed by the tx, and a receive transaction for the change. As a user, I want to see each UTXO transaction represented as a single row in tx history, where amount sent is the sum of all consumed inputs minus the change & miner fee.

### References and additional details

More context: https://discord.com/channels/554694662431178782/885616186623148062/1103530164660469840

### Acceptance Criteria

AC:
1. UTXO transactions that share the same txid are represented as a single row
2. The value sent is equivalent to the sum of all inputs minus the change & miner fee

**Comment by kaladinlight** [comment]
@willyogo finally got around to this (wanted it to look nice with the incoming thorchain tx parsing)! should be a big UI improvement for utxos :partying_face:
