### ISSUE TITLE
Updating OnRamper Widget to v2

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#4449]
### Overview

Onramper has added some parameters for filtering by network, so you can supply a wallet address that will be used by all tokens on that network.

### References and additional details

https://docs.onramper.com/
https://docs.onramper.com/docs/coverage-payment
https://docs.onramper.com/docs/widget-theme-config
Can also reach out to Leeroy at OnRamper directly

"Would love to assist getting you live with our widget v2 also, feel free to drop any github URL's to the integration here and I'll put up some PR's for review." Check out the coverage sections of the docs for currently supported fiats / cryptos / payments.

### Acceptance Criteria

TBD

**Comment by twblack88** [comment]
notes from pile: Took a bit of a detour on this one trtying to automate mapping but PR incoming.

**Comment by twblack88** [comment]
#4683
