### ISSUE TITLE
Change HelpDesk on www.shapeshift.com to docs.shapeshift.com

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#4450]
### Overview

as per a comment by GiantKin ( https://discord.com/channels/554694662431178782/885616186623148062/1104140767494156368 ), shapeshift.com still routes users to HelpDesk link here ( https://shapeshift.zendesk.com/hc/en-us ).

We should update this with docs.shapeshift.com where ever possible. 

I do see Hoff as someone to assign to, else I would. 

### References and additional details

![image](https://user-images.githubusercontent.com/94986227/236865256-6f79a133-bdd7-4854-bc77-29e39ad56d7a.png)

### Acceptance Criteria

Links changed at shapeshift.com from zendesk links to docs.shapeshift.com links.

**Comment by twblack88** [comment]
Fixed 
![Screen Shot 2023-05-31 at 10 09 09 AM](https://github.com/shapeshift/web/assets/8991325/593636d9-9181-4f4f-b52d-7a7cdc8049fc)
