### ISSUE TITLE
App crashes and loads black screen when changing default currency in the mobile app

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#4451]
### Overview

In the mobile app, when a user navigates to the settings screen and selects to change their default currency to a different currency, the app crashes and sits on a blank background.  This does not resolve until a user deletes the app and starts fresh. 

### References and additional details

https://discord.com/channels/554694662431178782/1105154998138048552/1105156168839598240

### Acceptance Criteria

Users are able to switch default currencies in the mobile app without the app crashing

### Need By Date

ASAP

### Screenshots/Mockups

![IMG_2042](https://user-images.githubusercontent.com/94998097/236893221-32f16505-eb9f-4153-b937-f8b25dac6c1a.png)

**Comment by 0xdef1cafe** [comment]
fixed in prod
