### ISSUE TITLE
MAX sends of ERC-20 (USDC Maybe all ERC-20's) Fail

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4477]
### Overview

Currently if a user tries to send MAX of USDC (or other ERC-20's) the transaction fails. If the user types in a smaller amount the TX goes through. I believe we are trying to send more than the users balance and this is why it's failing on chain.

Recreation Steps:
1. Try to send MAX of USDC
2. See on chain that it's reverted 

### References and additional details

https://etherscan.io/tx/0x9de51ef15ea8ac9cad9dfa30784e8cee0bd9064702e323098ea1f696aa673d9e

### Acceptance Criteria

User should be able to hit MAX for ERC-20's and have their sends be successful

**Comment by gomesalexandre** [comment]
@tshifty Just retested this one and managed to make a USDC max send https://etherscan.io/tx/0x4252c6684369e03bd45ce7b035f752e6df1674cddbf31354fe919a34a818aa89, I believe this has been fixed since the EIP1559 improvements/fixes went in - can we please retest it and close if unable to reproduce?
