### ISSUE TITLE
Users unable to send whole numbers (1-9) "Insufficient Funds"

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4483]
### Overview

Currently, if a user types in whole numbers (1-9) into the send modal it comes up with "Insufficient Funds" but if they just add another number they can successfully go to the next page.

Recreation Steps:
1. Try to send an ERC-20 Token (1-9)
2. Notice it comes up as "Insufficient Funds"

### References and additional details

N/A

### Acceptance Criteria

Users should be able to send whole numbers (1-9) in the send modal.

**Comment by gomesalexandre** [comment]
@tshifty Is this still happening for you? I wasn't able to repro:

<img width="543" alt="image" src="https://github.com/shapeshift/web/assets/17035424/45aa8302-f4f6-4c54-8192-eaab81c3539b">
<img width="547" alt="image" src="https://github.com/shapeshift/web/assets/17035424/d94ba408-548c-4586-9adb-9ef66f5bde15">

<img width="542" alt="image" src="https://github.com/shapeshift/web/assets/17035424/5ba38a2c-b018-44b0-a1b5-b008a2943f4d">
<img width="535" alt="image" src="https://github.com/shapeshift/web/assets/17035424/600514ab-5740-4b5d-845e-b42b013ffd4b">

**Comment by gomesalexandre** [comment]
Confirmed with @tshifty unable to repro
