### ISSUE TITLE
Max send of BTC borks send modal

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4486]
### Overview

When attempting a max send of BTC, the send modal goes into negative BTC and says "Not enough BTC to cover gas"

### References and additional details

1) Log into app.shapeshift and connect to native wallet
2) Select the QR code and scan a BTC address or select send and enter or scan a BTC address then select Next
3) In the Send amount select Max
4) Note the errors appearing in the send modal
![image](https://github.com/shapeshift/web/assets/100157997/b145425e-dcf7-4d10-a61f-179f850a55ca)

### Acceptance Criteria

Should be able to complete a max send of BTC

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria this is actually correct per current BTC fees (tyvm ordinals), sitting at 81792 sats when I checked (0.00081792 BTC), the negative value you're seeing is the diff between your balance and the send fees.
<img width="361" alt="image" src="https://github.com/shapeshift/web/assets/17035424/ef4a663c-2eb0-48d4-a9dd-be122fba51ae">
<img width="542" alt="image" src="https://github.com/shapeshift/web/assets/17035424/1a50c232-f212-411b-9081-d40ea9579ba6">

**Comment by MBMaria** [comment]
yeah shifty thought it may have been that as well. shall i go ahead and
close the ticket?

**Comment by gomesalexandre** [comment]
FTFY @MBMaria 🙏🏽
