### ISSUE TITLE
Bug: App displays incorrect value for underlying tokens for Idle Vaults

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#4493]
### Overview

Currently the app is underreporting the value of underlying tokens that a user has deposited in Idle's Junior stETH Vault. this issue is likely impacting all Idle vaults.

### References and additional details

1. willywonka.eth deposited 15.05 stETH on 4/9/2023
https://etherscan.io/tx/0xd2f569a6ea3a2bd4cc0ccbd30057aef023ae8076646ce0f76695bd02e049aa52 
2. App displays the value of underlying stETH tokens in willywonka's portfolio as 14.812 stETH (less than was even deposited)
![image](https://github.com/shapeshift/web/assets/26232238/c0980bd2-6590-4c61-9bbc-d4969d8c67e9)
3. When simulating the withdrawal tx, willywonka.eth can see that he would receive 15.148 stETH
![image](https://github.com/shapeshift/web/assets/26232238/730bd5b6-62ce-4375-8d29-cd9641be5523)

### Acceptance Criteria

AC:
1. App displays the correct amount of underlying tokens for all Idle vaults, which matches what a user would receive if they executed a withdrawal tx (in theory we could write a test for this that uses tenderly to simulate a withdrawal, but may not be necessary)

**Comment by zethdubois** [comment]
Hi y'all, no bug takers?

**Comment by gomesalexandre** [comment]
@willyogo just tested this one out and given the data we have, we are indeed displaying the "correct" amount:

See balance (13.272859302865498367 BB_wstETH):

<img width="639" alt="Screenshot 2023-08-23 at 16 10 38" src="https://github.com/shapeshift/web/assets/17035424/8499ba6f-814d-4a81-bf5a-96e0d5d00180">

and `pricePerShare` from Idle API (i.e the underlying asset ratio for a given Idle token):

<img width="493" alt="Screenshot 2023-08-23 at 16 10 57" src="https://github.com/shapeshift/web/assets/17035424/04aeb166-3268-45f4-a27f-28a3ac12cc86">

13.272859302865498367*1.15612845 = 15.3451302529

<img width="1377" alt="image" src="https://github.com/shapeshift/web/assets/17035424/eccba04b-eeca-4f83-9251-ab3e599f57c6">

I'll report this to Idle to ensure we get the correct `pricePerShare` 🙏🏽

**Comment by purelycrickets** [comment]
@MBMaria Can we see if this is still unresolved.  It should be fixed upstream.

**Comment by MBMaria** [comment]
Confirmed this is fixed.
![image](https://github.com/shapeshift/web/assets/100157997/1993dd2e-cf9d-4441-b2f8-1c28f9af3d3b)
![image](https://github.com/shapeshift/web/assets/100157997/390649d4-71c0-45fa-a682-48b1488013f9)
