### ISSUE TITLE
Preview trade for USDC on Avalanche to BCH is a dead click

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4502]
### Overview

When trying to preview a trade from USDC on Avalanche to BCH the Preview Trade button spins then reappears without progressing in the modal 

### References and additional details

1) Log into app.shapeshift and connect to native wallet
2) Enter USDC on avalanche to BCH in trade modal with appropriate amount
3) Select preview trade and not the button spins but does not work

https://github.com/shapeshift/web/assets/100157997/4a4c405c-2b0b-467d-87c0-df8b5af7ad2d

### Acceptance Criteria

Preview trade should progress to next screen

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
Dupe: https://github.com/shapeshift/web/issues/4500

**Comment by woodenfurniture** [comment]
Closed with #4500
