### ISSUE TITLE
Occasional invalid trade pair for ETH -> FOX

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#4546]
### Overview

Rarely the displays "invalid trade pair" for ETH -> FOX default pair.

### References and additional details

![image](https://github.com/shapeshift/web/assets/125113430/bb508be7-1c53-40e1-815c-0a768139d06d)

### Acceptance Criteria

This pair should always have a valid swapper and should be a valid trade pair.

### Estimated effort

2 hours

**Comment by purelycrickets** [comment]
@MBMaria can we check in to see if this is still re-creatable?

**Comment by MBMaria** [comment]
Confirming getting rates for eth - fox trade
![image](https://github.com/shapeshift/web/assets/100157997/1b956fec-e3e0-49a6-8a67-072181970ba1)
