### ISSUE TITLE
Osmosis swapper trades give no spinner

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#4550]
### Overview

Trades made using the osmosis swapper provide no visual feedback during trade execution or completion.

### References and additional details

![image](https://github.com/shapeshift/web/assets/125113430/0dc6bd89-5eab-424f-a0d6-1b5e4df0c50e)

### Acceptance Criteria

When confirming a trade using the osmosis swapper, there should be a spinner until the trade is completed, at such time a green check should appear in the UI.

### Estimated effort

2 hours

**Comment by purelycrickets** [comment]
no osmo
