### ISSUE TITLE
NFT descriptions all the same

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#4566]
### Overview

Looks like NFT descriptions are all duplicated from the first NFT in the list.

### References and additional details

Looks correct for the first in the collection:
![image](https://github.com/shapeshift/web/assets/125113430/031727e4-b1c7-49ff-af8c-4b4b0167aec9)

Pretty sure chungus is not a punk though:
![image](https://github.com/shapeshift/web/assets/125113430/62d88339-aee5-4d85-bbbc-330cc189b95c)

### Acceptance Criteria

Display the correct description for the NFTs

### Estimated effort

1h

**Comment by twblack88** [comment]
behold my 💩  polygon NFT's breaking the NFT modal. To recreate:
- connected to app via walletconnect. using rainbow on my phone.
- sourced this 🐛 

woody and I were guessing @kaladinlight or @reallybeard could look at this for two seconds and see why the data is propogating all funny. Also, im glad to have brought a chungus into the mix.

**Comment by kaladinlight** [comment]
Will take a look in the morning at this.

**Comment by gomesalexandre** [comment]
Will take a look as part of https://github.com/shapeshift/web/pull/4563 - most likely wrong parsing from Covalent/Zapper
