### ISSUE TITLE
Unable to deposit into USDT Vault (Clearpool Junior Tranche)

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4570]
### Overview

When trying to deposit into USDT Vault after selecting Continue it gives an error saying "Something went wrong"

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to Earn page and select USDT Vault
3) Enter an amount to deposit and select continue
4) Note the "Something went wrong" error and the continue buttons spins continuously
![image](https://github.com/shapeshift/web/assets/100157997/ed433701-11a4-4f7d-8311-6b56bcdb8e6c)
![image](https://github.com/shapeshift/web/assets/100157997/e9f60052-d6a6-475d-8348-da8342a6ab1b)

### Acceptance Criteria

Should be able to deposit into USDT Vault

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
@MBMaria another Idle issue that needs recreation

**Comment by purelycrickets** [comment]
Still broken upstream

**Comment by MBMaria** [comment]
Modal didnt update while i was waiting but the tx confirmed on the blockchain. Marking this ticket as resolved. 
![image](https://github.com/shapeshift/web/assets/100157997/9959c864-1dba-4e0d-a2ed-d4a11593e55c)
