### ISSUE TITLE
Failure to scan multiple accounts for legacy BTC accounts with no balance on account 0

### ISSUE THREAD

**Issue by BitHighlander** [shapeshift/web#4571]
### Overview

users With funds on multiple accounts are Failing to be detected. This results in many users having large parts of their life savings omitted when pairing with shapeshift. This has resulted in many unnecessarily stressful support tickets where users are under the assumption they have lost funds. 

### References and additional details

Currently even with tx history on account0 account 1 is not being scanned for funds. 

### Acceptance Criteria

Scan account 1-3 atleast and if funds are found continue to keep scanning. 

### Need By Date

-

### Screenshots/Mockups

![Screen Shot 2023-05-24 at 11 50 02 PM](https://github.com/shapeshift/web/assets/4935895/f9f14dc0-e78f-4d2a-a3f2-fefd71ea5258)

### Estimated effort

1 day

**Comment by 0xApotheosis** [comment]
Additional context: [15:28]highlander: yup, for reference this was legacy btc. account0 had a 0 balance but a massive tx history. account1 had a large amount of funds but the dashboard and send modal did not display the funds

**Comment by 0xApotheosis** [comment]
@twblack88 FYI

**Comment by twblack88** [comment]
Is this pre Segwit addresses? Might that be part of the TX history issues?
