### ISSUE TITLE
User unable to see FOX farming position from staked KK in app

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#4587]
### Overview

User with a staked UNIv2 FOX lp balance is unable to see or interact his position in the app.  It is gone from both the Earn page and the Opportunities page. 

### References and additional details

![Screenshot_2023-05-26_alle_19 53 20](https://github.com/shapeshift/web/assets/94998097/26e3f6e0-5ea5-4dc3-a092-77462637e803)
Missing FOX farming in FOX Opportunities page: 

Missing ETH/FOX staking in Earn page: 
![Screenshot_2023-05-26_alle_19 34 35](https://github.com/shapeshift/web/assets/94998097/a54f8258-ef22-4743-b395-a8c39df1a3b1)

https://etherscan.io/address/0x0b636a058c307add05b2cd0ef1000a4a4785cb2b
Users Address that staked FOX

TXID of staked position: https://etherscan.io/tx/0xc26e96f8b8d3c8b4a9dbd4a9cbfa245cad4354902f086dd19761e6f619ac4174

![Screenshot_2023-05-26_alle_20 00 15-1](https://github.com/shapeshift/web/assets/94998097/14509df0-940e-42a1-b135-8394af3d32d4)
Transaction history says 'Sent' instead of 'Staked'

### Acceptance Criteria

User able to see and interact with their FOX LP position

**Comment by purelycrickets** [comment]
The user who reported this, is now able to see/interact with his position, not sure if this was fixed in a different PR.

**Comment by gomesalexandre** [comment]
@purelycrickets that may have been a temporary Infura/our own JSON-RPC node issue, if we're unable to deterministically repro, we can close this

**Comment by purelycrickets** [comment]
Yes, unable to deterministically repro. closing this now.
