### ISSUE TITLE
TX History leaks between different wallets through Global Search

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4589]
### Overview

If I connect with a ShapeShift wallet, and then disconnect and reconnect with KeepKey for example (or MetaMask) and I open the Global Search, I can see Transaction History entries from the other wallet in addition to the current one. I've tested this using a private session (so not previous sessions should have altered this), happens in both FireFox and Chrome.

### References and additional details

1) Fresh Icognito/Private browser session.
2) Import a ShapeShift wallet which has few recent transactions. Connect to it, check the Global Search menu to see the TXs.
3) Disconnect the ShapeShift wallet through the top right menu.
4) Connect a KeepKey or MetaMask wallet that also has one-two recent transactions (so they don't replace all the potentially less recent ones from the other wallet).
5) Open the Global Search modal and check the transactions, a mix of both wallet's recent transaction is listed. Since they link to simple transaction history details they can be clicked to view more details about them and you can clearly see the addresses are from the other wallet.

Native wallet: 
![image](https://github.com/shapeshift/web/assets/100157997/7a53765f-603c-44fa-8116-a8b12857b31b)
Metamask Wallet:
![image](https://github.com/shapeshift/web/assets/100157997/96d1dad5-19cf-415a-9c02-da99c1c8437b)

### Acceptance Criteria

Global search should have relevant tx history for each wallet listed

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
@MBMaria can we try to recreate this issue as well?

**Comment by MBMaria** [comment]
Still seeing this. also noticing that the transactions listed (same in native and mm ) are quite old, and definitely not the most recent transactions. 
![image](https://github.com/shapeshift/web/assets/100157997/a3242690-f990-42bd-884b-f649477bf4c1)
