### ISSUE TITLE
Swapper estimated execution time

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4611]
### Overview

For some LifFi trades, the trade modal doesn't update once completed. This is related to the chain reflecting a transaction as successful while the exchange is still processing it on their side. 
To the user it looks like our app is broken but underneath there is a status saying "waiting for off chain logic" or similar.

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to trade/bridge page (or modal) and execute in a LiFi trade eg (tether on bnb to usdc on avalanche)
3) Note that transactions appear in the recent transactions as completed but the modal is still spinning on pending

### Acceptance Criteria

We need to do the following to resolve this:
1) display the estimated execution time in the UI so the user doesn't panic when it takes >30m
2) show the current status of the transaction in the UI so the user doesn't panic

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by woodenfurniture** [comment]
![image](https://github.com/shapeshift/web/assets/125113430/2c29fb84-7e13-41e5-9ea3-69bccf8c49ac)
