### ISSUE TITLE
Wallet Connect Modal Disappears for KeepKey users that need a KeepKey update  

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#4648]
### Overview

When Connected to app.shapeshift.com with a KeepKey, Users that need to update their KeepKey will have modal pop up to ask them to update their KeepKey, this modal blocks the loading of Wallet Connect. 

### References and additional details

![Screen_Shot_2023-06-03_at_2 06 50_AM](https://github.com/shapeshift/web/assets/94998097/268bac97-2ded-4439-a491-5fd419d1ae16)

Screenshot of connected KeepKey with missing Wallet Connect button. 

### Acceptance Criteria

KeepKey users are able to interact with Wallet Connect even if they need a firmware update.

**Comment by BitHighlander** [comment]
This is also kept hidden when any network/node is offline

**Comment by purelycrickets** [comment]
Needs to be addressed after WC work
