### ISSUE TITLE
Issues minting the foxatar on mobile

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4657]
### Overview

Users are having struggles minting the foxatar on mobile. It takes a couple attempts to connect Mercle to shapeshift via WalletConnect (and for Mercle to detect that shapeshift has connected), and then the prompt to sign the login message is never displayed in the app

### References and additional details

1. Connect shapeshift mobile to Mercle app via walletconnect
2. It takes a couple of attempts for Mercle to detect that ShapeShift has connected, and the prompt for the user to sign the login message is never displayed in the shapeshift app

### Acceptance Criteria

Mercle detects shapeshift connection on first attempt, and the user is prompted to sign the login message in the shapeshift app

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
Related discussion: https://discord.com/channels/554694662431178782/1113560894786502707
