### ISSUE TITLE
NFT not appearing in wallet until after a refresh

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4674]
### Overview

After purchasing an NFT, the tx will show in Activity, but the NFT wont be displayed until you refresh the wallet

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Purchase an NFT (via Opensea or something similar)
3) Note the tx shows in the Activity but no NFT under the NFT section
4) Refresh wallet - note the NFT appears

### Acceptance Criteria

NFT should appear after its purchased without a refresh

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
Working now
