### ISSUE TITLE
Unable to trade between OP pairs

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#4694]
### Overview

Getting a series of 500 and 429 errors when trying to make trades on the OP chain. User gets the warning, 'Invalid trade pair.'

### References and additional details

![Screenshot_413](https://github.com/shapeshift/web/assets/94998097/f0756cd7-04d3-41ca-9c5e-2e457916b1f0)
![Screenshot 2023-06-08 at 8 51 32 AM](https://github.com/shapeshift/web/assets/94998097/f28505f7-f7f7-431d-9629-240df0e6e691)
![Screenshot 2023-06-08 at 8 53 50 AM](https://github.com/shapeshift/web/assets/94998097/33a45a4e-3f47-4afe-9673-4bc6fa3da996)

### Acceptance Criteria

OP trades between pairs able to be made successfully.

**Comment by gomesalexandre** [comment]
@purelycrickets https://github.com/shapeshift/web/pull/4919 brought support for same chain Li.Fi swaps which will bring one more source for Optimism, and I've confirmed 1inch, ZRX and Li.Fi are all happy. 

Please confirm if you can still repro and close if fixed 🙏🏽 

- LiFi

<img width="629" alt="image" src="https://github.com/shapeshift/web/assets/17035424/b213fc7d-74aa-45b0-bef8-e9a2aceb43dc">
<img width="827" alt="image" src="https://github.com/shapeshift/web/assets/17035424/df53e9a8-f17f-4d5d-af37-598a613365ad">

- ZRX

<img width="629" alt="image" src="https://github.com/shapeshift/web/assets/17035424/ac36e43f-e0ba-4a5c-a99b-55bf7040b68b">
<img width="820" alt="image" src="https://github.com/shapeshift/web/assets/17035424/891c8e59-9312-4eca-bcb3-55dcc7a0f7e8">

- 1inch

<img width="607" alt="image" src="https://github.com/shapeshift/web/assets/17035424/440e0364-0f18-4c84-84ec-263ea9eb2669">
<img width="615" alt="image" src="https://github.com/shapeshift/web/assets/17035424/debb5a5e-360d-46d7-93ff-2ec89a447841">

**Comment by gomesalexandre** [comment]
> Please confirm if you can still repro and close if fixed 🙏🏽

@purelycrickets ^^

**Comment by purelycrickets** [comment]
No longer able to recreate 🙏  Closing the issue Thanks @gomesalexandre!
