### ISSUE TITLE
Scrolling fixes on mobile

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#4695]
### Overview

Surfaced via QA sessions we want to make scrolling on the assets page more intuitive (and also behave). 
-[ ] follow common design pattern for chains (move the selected chain into the truncated listed)
-[ ] spike to deal with the weird flexing issues around the box of chains 

Make scrolling behave. 
follow common design pattern for chains
truncate stuff
deal with the weird flexing isues

After a chain is selected from the additional chains it will need to move into the truncated list. 

Before selection:
![Screenshot 2023-06-08 at 1 32 44 PM](https://github.com/shapeshift/web/assets/89934888/3eaf6d7f-284c-4a6b-9379-cc5882079255)

After selection:
![Screenshot 2023-06-08 at 1 32 48 PM](https://github.com/shapeshift/web/assets/89934888/e5f61e5b-2c19-482b-9842-74c00642248a)

Should probably solve for this issue where the nav on assets comes along for the ride:

![image](https://github.com/shapeshift/web/assets/8991325/fe4964df-cd26-4ad1-8580-5d03c82f42cd)

### References and additional details

QA sessions feedback

### Acceptance Criteria

Scrolling feels more intuitive
navbar stays in place

**Comment by purelycrickets** [comment]
Fixed
