### ISSUE TITLE
Arbitrum base support

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#4704]
### Overview

Base support for Arbitrum EVM network - see AC below.

### References and additional details

**Out of scope for this ticket**

- [ ] Fiat ramps
- [ ] Swapping

### Acceptance Criteria

We have the following support

- [ ] asset data
- [ ] market data
- [ ] receive
- [ ] send
- [ ] tx history
- [ ] websockets

**Comment by kaladinlight** [comment]
https://github.com/shapeshift/web/pull/5337
