### ISSUE TITLE
"Start Earning" button in DeFi page is a deadclick

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4709]
### Overview

When selecting a chain to search by opportunities to earn, if there are no active positions, the "Start Earning" button is a deadclick

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to DeFi page
3) Select a chain that doesnt have any current active positions (ie Polygon or Optimism)
4) Select the Start Earning button and note nothing happens
5) ** also note when selecting a different chain (if you have selected a chain that has no positions) if you scroll when the menu is dropped down then it goes funky
![image](https://github.com/shapeshift/web/assets/100157997/a8e9270e-00ee-4b1a-b4e8-19aa4a62f62c)

https://github.com/shapeshift/web/assets/100157997/b2feec53-a5d4-4e66-a7b8-e514e05925fd

### Acceptance Criteria

"Start Earning" button should take you to other active positions

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria I've managed to repro this locally, confirmed this only happens within the navbar earn, not the dashboard Earn.
I will sync with Beard on this one, I believe there's nothing to "fix" here as far as the button goes, but rather have a different empty state for the navbar Earn.

- Dashboard Earn tab shows your active positions, so this empty state makes sense there when none is found
- Navbar earn on the other hand, shows all, not just active. So "No Active Positions" is wrong, this should really be "No available opportunities" and some empty state search similar to the search results one. IMO, the button should be "See All Positions" (i.e across all chains) or "Reset Filters"

<img width="1322" alt="image" src="https://github.com/shapeshift/web/assets/17035424/636e1782-4196-41a6-8729-0160d527a3d2">
