### ISSUE TITLE
Wallet Connect, Unable to deploy contracts

### ISSUE THREAD

**Issue by BitHighlander** [shapeshift/web#4718]
### Overview

When using a dapp to deploy a contract the msg.to address will be null/undefined

Currently ShapeShift freezes and does not handle this case.

```
Uncaught (in promise) RequiredError: Required parameter requestParameters.to was null or undefined when calling estimateGas.
```

![Screen Shot 2023-06-11 at 3 55 29 PM](https://github.com/shapeshift/web/assets/4935895/e049e6ad-05e0-4516-9cf0-61680d0c0c8a)

Recreate this issue. 
https://app.tokenlauncher.com/

### References and additional details

WalletConnectBridgeProvider.tsx:109

### Acceptance Criteria

A/C accept payload without .to address

**Comment by 0xdef1cafe** [comment]
closing as won't fix - our users simply aren't deploying contracts. PRs welcome if you have some specific use case.
