### ISSUE TITLE
Asset API Spike

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#4740]
### Overview

https://www.notion.so/shapeshift/Exchange-API-20ba8db095374743ac581e11c2c06db4?pvs=4#933726f1582741ac9f57c5f54f54fe70

In order to be able to get a quote, consumers will need to know what asset ids to call the quote endpoint with.

### References and additional details

* LiFi has this concept - where you can ask for a list of all assets and get back a bigly JSON object (several mb)
	* `curl --request GET --url 'https://li.quest/v1/tokens?chains=POL%252CDAI' --header 'accept: application/json'`
* Note that asset ids require escaping in URLs as they contain `:` and `/`, e.g. eth mainnet is `eip155:1/slip44:60` - this ergonomics of this should be taken into consideration
* Consumers will likely want a search endpoint, e.g. a user of a UI will want to search for "USDC" 
* We already have this static generated asset data as part of web. 
	* https://github.com/shapeshift/web/blob/develop/src/lib/asset-service/service/generatedAssetData.json#L17

### Acceptance Criteria

A list of endpoints defined, with request and responses documented, ideally defined with swagger. At a later date we'll likely use `tsoa` to generate these endpoints from code, such that the swagger docs are always current and reflective of reality and current code, but this is an implementation detail, and outside the scope of this spike.

All endpoints should use, and reference original CAIP specs, for `ChainID` (CAIP2) and `AssetID` (CAIP19)

Please use discretion, but loosely, we should spec out the following endpoints

* an `/all` type endpoint, a la LiFI
	* filterable by `ChainID`
* a search endpoint
	* probably by symbol/name
* a detail endpoint
	* "give me all the asset details for `eip155:1/slip44:60`

**Out of scope**

* NFT support

**Comment by 0xean** [comment]
Whoever picks up this spike, please take a look at the following tickets that might need to be updated based on the outcome of this spike.


https://github.com/shapeshift/exchange/labels/Asset%20API

Some of the tickets might also be useful to cross reference that we have all the needed asset endpoints

**Comment by 0xdef1cafe** [comment]
```
https://exchange.shapeshift.com/api/trpc/assets/search?query=pepe
https://exchange.shapeshift.com/api/trpc/assets
https://exchange.shapeshift.com/api/trpc/assets?id=eip155:1/slip44:60
```
