### ISSUE TITLE
Wallet-Connect v2 Non conforming namespaces.

### ISSUE THREAD

**Issue by BitHighlander** [shapeshift/web#4756]
### Overview

Attempting to connect Wallet-Connect v2 with app.shapeshift.com

```format.ts:26 Uncaught (in promise) Error: Non conforming namespaces. approve() namespaces chains don't satisfy required namespaces.
      Required: eip155:1,eip155:42161,eip155:43114,eip155:56,eip155:5,eip155:10,eip155:137
      Approved:
```

![Screen Shot 2023-06-14 at 4 18 13 PM](https://github.com/shapeshift/web/assets/4935895/7aabe9fb-1a3a-4a41-811c-a0ac1d1d9f79)

![Screen Shot 2023-06-14 at 4 17 27 PM](https://github.com/shapeshift/web/assets/4935895/d25f096c-3c35-4fdb-b84c-50c5e118cadf)

### References and additional details

Steps to recreate:

go to https://pay.sablier.finance/

attempt to use v2

https://pay.sablier.finance/

full error.

format.ts:26 Uncaught (in promise) Error: Non conforming namespaces. approve() namespaces chains don't satisfy required namespaces.
      Required: eip155:1,eip155:42161,eip155:43114,eip155:56,eip155:5,eip155:10,eip155:137
      Approved: 
    at Je.isValidApprove (format.ts:26:47)
    at async Je.approve (validators.ts:17:23)
    at async tn.approve (validators.ts:11:85)
    at async bn.approveSession (validators.ts:11:85)
    at async _n.approveSession (validators.ts:11:85)
    at async SessionProposal.tsx:98:11

### Acceptance Criteria

connect

**Comment by 0xean** [comment]
@BitHighlander - any idea if this issue still exists?
