### ISSUE TITLE
Wallet-Connect v1 switch chain bug

### ISSUE THREAD

**Issue by BitHighlander** [shapeshift/web#4758]
### Overview

Broken Dapp https://thatsgnar.ly/ submitted to keepkey support by shapeshift dao member. 

broken chain select flow

### References and additional details

Steps to recreate:

pair to 
https://thatsgnar.ly/edition/box-gap-to-tail-tap941

press "switch network to polygon"
![Screen Shot 2023-06-14 at 5 43 03 PM](https://github.com/shapeshift/web/assets/4935895/b5ea843c-e4d1-4718-a0f7-b003ac268143)

ShapeShift Fails to switch networks

Gnarly shows error:

![Screen Shot 2023-06-14 at 5 46 14 PM](https://github.com/shapeshift/web/assets/4935895/e0b1082b-aff9-41bc-a30e-58c0657c62f9)

(this error does not show on kk desktop) desktop handles network swtich without error

error in ss logs 

![Screen Shot 2023-06-14 at 5 51 00 PM](https://github.com/shapeshift/web/assets/4935895/a4a80b88-195e-43c5-82b6-79b57dc7839f)

```WalletConnectBridgeProvider.tsx:197 Error: Missing or invalid topic field
    at C.send (index.ts:57:19)
    at X._sendRequest (index.ts:564:25)
    at async X.killSession (index.ts:411:23)
    at async WalletConnectBridgeProvider.tsx:194:5```

However, this bug was found debugging matic broadcasting on kkdesktop that is broke and I believe to be dapp side. 


### Acceptance Criteria

n/a

### Need By Date

_No response_

### Screenshots/Mockups

_No response_

### Estimated effort

_No response_

**Comment by woodenfurniture** [comment]
with walletconnect v1 removed from the project, this is now resolved
