### ISSUE TITLE
Keepkey Users Unable To Trade Polygon Assets

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4786]
### Overview

Currently, keepkey users are unable to trade polygon assets on app.shapeshift.com. They get "Oops something went wrong" and the console log spits out https://api.polygon.shapeshift.com/api/v1/send 400 error.

Recreation Steps:
1. Attempt to trade anything on matic to matic on KK.
2. Notice that you get an error every time you send.

### References and additional details

N/A

### Acceptance Criteria

Keepkey users should be able to trade MATIC coins

**Comment by gomesalexandre** [comment]
@tshifty is this isolated to KK and still reproducible? There were some issues with the Polygon node which should now have been fixed.

**Comment by tshifty** [comment]
@gomesalexandre yeah it's re-creatable only with KK

**Comment by kaladinlight** [comment]
assumption is there is a bug in hdwallet for keepkey. not sure about prioritization however...

**Comment by tshifty** [comment]
@BitHighlander Any idea what is causing this?

**Comment by kaladinlight** [comment]
![image](https://github.com/shapeshift/web/assets/35275952/ccbc5b20-8daa-4f46-8a85-ffc0d2b40b23)
first glance would be a one liner addition of `, { common }` to the `FeeMarketEIP1159Transaction.fromTxData` args. Just going to be defaulting to eth mainnet most likely without it. I am just in the middle of things and testing hdwallet can be a pain.

**Comment by kaladinlight** [comment]
> ![image](https://user-images.githubusercontent.com/35275952/246941278-ccbc5b20-8daa-4f46-8a85-ffc0d2b40b23.png) first glance would be a one liner addition of `, { common }` to the `FeeMarketEIP1159Transaction.fromTxData` args. Just going to be defaulting to eth mainnet most likely without it. I am just in the middle of things and testing hdwallet can be a pain.

spent some time looking into this more and not as straight forward as the above suggestion just fyi

**Comment by BitHighlander** [comment]
bug is related to EIP1159, we don't have test cases for non chainId 1 1159 txs in hdwallet and there are inconsistencies in packages the various wallets use. running my test locally I got 4 separate signatures from the different wallets. https://github.com/shapeshift/hdwallet/pull/610

best course of action is disable EIP1159 tx's for non ETH chains as there isn't really and gas savings on those networks anyway. 

We do this automatically on kk-rest api and just convert to standard fee params. <img width="473" alt="Screen Shot 2023-06-20 at 5 55 46 PM" src="https://github.com/shapeshift/web/assets/4935895/62dfcf20-2053-455a-9a57-94ef62725eb0">

**Comment by tshifty** [comment]
No longer an issue
