### ISSUE TITLE
DeFi position doesn't update until after a refresh

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4802]
### Overview

When depositing/withdrawing from Idle positions, the balance doesn't update until you do a refresh

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to DeFi page and find an Idle vault to deposit into or withdraw from
3) Deposit/Withdraw and note the once you view the position after its completed that the balance does not update.
4) Refresh page and note that the balance appears/disappears
![image](https://github.com/shapeshift/web/assets/100157997/e04f0794-b0ae-4bed-93fd-e7768a91019a)
![image](https://github.com/shapeshift/web/assets/100157997/05c28080-a5ea-446a-8631-e5edd72febb6)

### Acceptance Criteria

Balance should update once you "View Position" after transaction has completed

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
Checking to see if this is still active and discovered that the modal didnt update once the transaction completed. Still needing to do a refresh to get balance to show in defi position
![image](https://github.com/shapeshift/web/assets/100157997/b558e5cb-a29e-41e8-b5d1-5b94f3001d4f)
![image](https://github.com/shapeshift/web/assets/100157997/14bfac16-445a-438a-ab20-7aa1e5dc3bdd)

**Comment by 0xean** [comment]
closing, idle has been removed.
