### ISSUE TITLE
WalletConnectV2 Dapp Support

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#4832]
### Overview

According to WalletConnect's docs, all dapps that support WalletConnectV1 need to do to support V2 is update the version of their SDK; no UI changes _should_ be required. As platform admins, we would like to support WalletConnect V2 as a dapp in time for the migration on the 28th if it can be done within a day. If it can't be done within a day, we can revisit prioritization once we have a better idea of the lift as well as whether or not WC will stick to their migration schedule.

Note: Rather than upgrading the current WCV1 dapp integration to v2, we would like to add V2 as an additional wallet option alongside the existing v1 implementation. This will provide a workaround if there are issues with v2 or for users whose wallets have not yet updated.

### References and additional details

Migration overview: https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/overview
Docs for dapps to migrate: https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/dapps
Implement web3modal from scratch: https://docs.walletconnect.com/2.0/web3modal/about

Example of a dapp that supports v1 and v2 alongside eachother: https://app.sablier.finance/

### Acceptance Criteria

1. Up to 1 day is spent attempting to implement walletconnect v2 dapp support as a new option in the 'Connect Wallet' modal alongside v1
2. If v2 support can be added within a day, users of wallets that support WalletConnectV2 (ie. trust, zerion, rainbow wallet) can connect to shapeshift and execute a transaction
3. If v2 support cannot be added within a day, provide product with an estimated # of days that it would take to support it

Note: ops is standing by to test on Yeet 🚀 

### Estimated effort

one day

**Comment by willyogo** [comment]
If we are able to add WalletConnect V2 as an option for users to connect their wallet, we should update the subtitle for the current WalletConnect V1 card to say "V1 - Ethereum Only" and to use this orange version of the WalletConnect icon:
<img width="1180" alt="image" src="https://github.com/shapeshift/web/assets/26232238/4e15e61d-77ea-4cf6-aacf-15c5f8f2d25c">

We should use the current blue version of the WalletConnect icon for v2, and should make the subtitle say "V2"

We should also move the WalletConnect options to the bottom of the list with v1 on the left and v2 on the right.

**Comment by twblack88** [comment]
moving this to new issues now that we spiked on the dapp versus the wallet surface area and spent a day trying to deal with WC migration
