### ISSUE TITLE
"See All" button for the "Transaction History" on asset pages goes to a blank page

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4849]
### Overview

On asset pages like Ethereum, in the "Transaction History" section when enough transaction are present there is a "See All" button that appears next to the title. Clicking on it leads to an empty/blank page. 

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to asset page with multiple transactions
3) Under the transaction history select "See All"
4) Note it takes you to a blank page

### Acceptance Criteria

See All should list all transaction history

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Fixed by https://github.com/shapeshift/web/pull/4955
