### ISSUE TITLE
Trading XDAI on Gnosis to another asset on Gnosis is not possible

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4852]
### Overview

Tested on ShapeShift wallet and MetaMask. If you select XDAI (the base/fee asset of Gnosis) as the sell asset on the Trade page (or widget) the networks available for the buy asset do not include Gnossis. If you try to "trick" it by selecting a Gnosis asset first as sell asset (e.g. USDT on Gnosis), XDAI as buy asset, and then switch the sell/buy asset with the arrow button, the error message "Invalid Trade Pair" appears in the Trade button.

### References and additional details

1) Select XDAI as the sell asset
2) Try to select an asset on Gnosis for the buy asset.
3) To trick it, have a non gnosis asset as the input asset then select USDT on gnosis as the output asset. 
4) Select the input asset and note you can select xdai on gnosis
5) Note this error 
![image](https://github.com/shapeshift/web/assets/100157997/4157620c-5c57-4e8b-952c-9785158d4541)

### Acceptance Criteria

Should not be able to trick the swapper for invalid pairs

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Fixed in https://github.com/shapeshift/web/pull/4919
<img width="628" alt="image" src="https://github.com/shapeshift/web/assets/17035424/5f2fa102-e2f0-4894-bb0d-60a879d16e8a">
