### ISSUE TITLE
app.shapeshift.com broken in metamask mobile browser and app 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#4865]
### Overview

metamask mobile users are unable to to connect to app.shapeshift.com (but are still able to connect to other dapps like zapper successfully) 

Navigating to ShapeShift for metamask mobile users instead directs users to the metamask app in the appstore instead of pairing and connecting.

### References and additional details

![Screenshot_20230629_095534_MetaMask](https://github.com/shapeshift/web/assets/94998097/047db80d-397d-46fc-b20a-96a170654f57)

Wallet 'connected' but not recognized or actually connected. 

![IMG_6628](https://github.com/shapeshift/web/assets/94998097/035339fc-a3ab-49e7-8d4a-86ddc8cc53b9)

Metamask appstore flow when trying to pair from the metamask app browser. 

### Acceptance Criteria

Metamask mobile users are able to connect to app.shapeshift.com successfully.

**Comment by gomesalexandre** [comment]
@purelycrickets I just gave this a try on MM mobile on iOS and was able to connect without any issue. Looking at the first screenshot on android, it looks like the MM version is out-of-date, there has been a major UI revamp recently and this doesn't seem to match it according to the top-right network icon (unless it looks different on Android).
Can you confirm the MM app is up-to-date ?

**Comment by twblack88** [comment]
Can't reproduce, i think we're OK.
