### ISSUE TITLE
Add card to missions page for FOX Rewards (coming soon)

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#4877]
### Overview

As buidlers, we want to add a card for FOX Rewards to the Coming Soon section of the FOX Missions page so all the new users that are stopping by for the OP Rewards will see that FOX Rewards are coming.

Title: Buy, sell, trade, earn, and more
Subtitle: Earn FOX
Start time: January 1, 2025 (we'll update this once start date is known)
End time: N/A (ongoing mission)

URL: N/A (will update once we know what the URL will be)

### References and additional details

Artwork: 
![FOX Rewarditation](https://github.com/shapeshift/web/assets/26232238/3eb38fb2-ac1c-49c9-90ed-e3a6c045f0b1)

### Acceptance Criteria

AC:
1. Users see the FOX Rewards card in the Coming Soon section of FOX Missions

**Comment by gomesalexandre** [comment]
closed by https://github.com/shapeshift/web/pull/4959
