### ISSUE TITLE
Bad Request 400 from 0x when trading FOX to Anything on ETH

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4879]
### Overview

Currently, users are unable to trade FOX to ETH or any ERC-20 token. When you try to fire off the trade, spins and goes back to confirm. 

Console Errors:
{"code":105,"reason":"SenderNotAuthorizedError","values":{"sender":"0xdef1c0ded9bec7f1a1670819833240f027b25eff"}}

https://api.0x.org/swap/v1/quote?buyToken=0x514910771af9ca656af840dff83e8264ecf986ca&sellToken=0xc770eefad204b5180df6a14ee197d99d808ee52d&sellAmount=1154718796212772000000&takerAddress=0xE7F92E3d5FDe63C90A917e25854826873497ef3D&slippagePercentage=0.002&affiliateAddress=0xc770eefad204b5180df6a14ee197d99d808ee52d&skipValidation=false&feeRecipient=0x90a48d5cf7343b08da12e067680b4c6dbfe551be&buyTokenPercentageFee=0
![FOX0xerror](https://github.com/shapeshift/web/assets/94189400/d058bfd1-226b-4e5f-ab5e-abe6fd230125)

Recreation Steps:
1. Attempt to trade FOX to any ETH or ERC-20 token with 0x

### References and additional details

N/A

### Acceptance Criteria

Users should be able to sell FOX through 0x

**Comment by gomesalexandre** [comment]
@tshifty managed to swap USDC -> ETH (https://etherscan.io/tx/0x02712b7c30fc97132dd653cf9206e494e5492ebf0c5124e28f2ec413d84cb91f), ETH -> FOX (https://etherscan.io/tx/0xd150893de984f2d6f8b18a57e8a71a4ad2394f972fda77d5aba5f51a3d65bb10).

I didn't have enough gas for FOX -> ETH, though this seems to happen at quote time, and looks happy to me when testing with your account frame-injected (full payload and preview response hidden for privacy):

<img width="611" alt="image" src="https://github.com/shapeshift/web/assets/17035424/1df5a911-cad8-4501-8aec-a0cbf1aa12be">

Please confirm you're now able to complete the trade and let's close this if so

**Comment by tshifty** [comment]
Hey @gomesalexandre! It needs to be a ERC-20 that's not a USD pegged coin. Try anything but those, LINK and FOX I can get it to do it every single time. Please try with a native wallet on prod. Thanks
