### ISSUE TITLE
Handle multiple network fees per hop in swappers

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#4885]
### Overview

Its possible to have up to 2 network fees per hop. Currently if a hop has fees on the buy chain and insufficient balance for it to complete, the app ignores it and executes the trade anyway, resulting in a partially processed trade.

Upgrade the app to handle this.

### References and additional details

Example of jumper.exchange (lifi) showing a single-hop bridge+swap with network fees payable on both sell chain and buy chain:
https://jumper.exchange/exchange?fromAmount=1&fromChain=43114&fromToken=0x0000000000000000000000000000000000000000&toChain=100&toToken=0x0000000000000000000000000000000000000000
![image](https://github.com/shapeshift/web/assets/125113430/e2722577-a876-425a-aa98-21de2d02c522)

![image](https://github.com/shapeshift/web/assets/125113430/5f2c6c3b-f015-46ad-a614-439e82c8db00)

When there is insufficient balance for the buy chain netowrk fee, it appears (for lifi at least) as a random token being received, often one that isnt supported by the app (e.g QIDAO on gnosis):
![image](https://github.com/shapeshift/web/assets/125113430/38df70c0-79e5-4aba-8ce2-83ccd923c5be)

### Acceptance Criteria

- Trades that have a network fee paid in the fee asset on the sell chain can be completed (most swappers are this case)
- Trades that have a network fee paid in the fee asset on the buy chain can be completed (theoretical, may not be testable although osmo swapper might be a good candidate for this)
- Trades that have a network fee paid in both the fee asset on the sell chain AND the fee asset on the buy chain can be completed (See jumper example above to test with lifi swapper)
- Trades that have no network fee can be completed (cow swapper)

### Estimated effort

2 days

**Comment by gomesalexandre** [comment]
> Trades that have a network fee paid in the fee asset on the buy chain can be completed (theoretical, may not be testable although osmo swapper might be a good candidate for this)

Indeed, with our current implementation, ATOM -> OSMO really has two fees: one in the native asset/asset being sold i.e ATOM on Atom (CosmosHub) while doing the first ATOM on CosmosHub to ATOM on Osmosis swap, and the other on the receiving chain (OSMO on Osmosis) while doing ATOM on Osmosis to OSMO on Osmosis.

OSMO -> ATOM on the other hand is independent of "current implementation" being correct or not - it's always a single fee paid on Osmosis.

**Comment by woodenfurniture** [comment]
Closing as this is now correctly handled.
