### ISSUE TITLE
Wallet Connect V2 Routes

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#4904]
### Overview

Add a new wallet v2 wallet as an option from the connect wallet modal.

When the user clicks on this options, they will see two buttons -- Saved Connections, Connect new wallet

If the user taps on saved connections they see a list of previously connected wallets with a picture, name, expiration date, and a way to delete that connection.

If the connection is expired, we will add a new button to refresh the connection.

If they click on the connect new wallet they will see the wallet connect modal.

### References and additional details

Plug into the existing wallet connect provider stuff

### Acceptance Criteria

A user can connect using wallet connect v2 and they can see there persistent connections.

**Comment by 0xApotheosis** [comment]
From the docs at https://docs.walletconnect.com/2.0/web/web3modal/react/wagmi/options, I'm guessing we'll have data that looks something like:

```ts
{
  id: string,
  name: string,
  links: {
    native: string
    universal: string,
  },
},
```

Where

```
 Native link represents deeplinking URL like ledgerlive:// and Universal link represents webpage link that can redirect to the app or fallback page. Defaults to undefined.
```

**Comment by gomesalexandre** [comment]
https://github.com/shapeshift/web/pull/4952
