### ISSUE TITLE
ShapeShift DAO Router not processing approvals for Clearpool USDC Junior Tranche

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4907]
### Overview

When trying to approve usdc token with shapeshift dao router to deposit into Clearpool USDC Junior Tranche, it just spins on approval and gives a "Transaction Failed" error. you can select approval again and process repeats even though user is being charged for the approval.

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to DeFi page and find Clearpool USDC Junior Tranche
3) Select an amount to deposit
4) Select Approve 
5) Note that the approval spins until a Transaction Failed error appears. see screenshot below for console error.

![image](https://github.com/shapeshift/web/assets/100157997/8b47479b-d2a6-489d-a954-ee324dc901ee)
![image](https://github.com/shapeshift/web/assets/100157997/76936235-22b5-4818-847f-ca5342ab7ea9)
![image](https://github.com/shapeshift/web/assets/100157997/9b71473d-13f0-4864-8d11-0dfa9746b81f)

### Acceptance Criteria

Approval should go through so can deposit into junior tranche

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria do we have a link for the failed Tx ? 🙏🏽

**Comment by MBMaria** [comment]
@gomesalexandre just checked and looks like the transaction does complete. however, each time you go to deposit it asks for approval again. 
https://etherscan.io/tx/0x6822e27168acfe0a195bef609208e47b5d0f5061c2f619bbbac04b41a6c59c51
