### ISSUE TITLE
Language drop down menu on connect page on mobile app too high

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4925]
### Overview

When trying to select a different language on mobile, the drop down menu is too high and you cant access it

### References and additional details

1) open mobile app 
2) notice language selector at the top right hand corner
3) note it is too high and you cannot access the drop down menu
*iphone 14
![image](https://github.com/shapeshift/web/assets/100157997/84b1ec50-24c0-4416-b91b-feee9cfbcddb)

### Acceptance Criteria

should be able to access language drop down menu

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by firebomb1** [comment]
Hmm interesting, the "safe zone" for UI elements gets smaller and smaller these days.

Not sure where else we should place it otherwise, any opinion @reallybeard ?

I can push it down a bit, but it will look odd on smartphones that don't integrate the camera shutter in the UI of the page (what a world we're living in these days 🤣 )

**Comment by firebomb1** [comment]
Looking into this again, Chakra UI [polyfills](https://chakra-ui.com/changelog/v2.3.1#styled-system-231) the `-webkit-fill-available` non-standard property that could solve this. Simply adding "$" before "100vh" and putting the `LanguageSelector` (and its `Flex` wrapper) inside the now `$100vh` sized container could solve this... I unfortunately don't have any Apple device to emulate or test this theory.

**Comment by gomesalexandre** [comment]
@firebomb1 feel free to PR this and I'll get this tested on iPhone 14 🙏🏽

**Comment by firebomb1** [comment]
I've drafted one, but I'm not convinced it will fix anything. We can continue the technical aspect of this in the PR.  Thanks for your help!
