### ISSUE TITLE
Unable to trade Eth on Optimism to USDC on Optimism 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4939]
### Overview

When trying to trade Eth on Op to usdc on OP the transaction with broadcast but then fail and give the error "Something went wrong". 

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to trade pair or trade widget and enter a trade eth on OP to usdc on OP
3) Confirm and Trade and note the error appears. 
![image](https://github.com/shapeshift/web/assets/100157997/7b5a693a-7c06-48e8-9646-364c6c060157)
![image](https://github.com/shapeshift/web/assets/100157997/d72eeefe-3176-451c-b2ad-d6dd84d0607d)
on Metamask wallet: 
![image](https://github.com/shapeshift/web/assets/100157997/fcb59027-80aa-4092-a6f2-66908136a1a8)
https://optimistic.etherscan.io/tx/0xbcbf0a57ff8a00419ef0afacfc32e1569630c211d91bd9f89211d52498e2562e

### Acceptance Criteria

should be able to trace eth on op to usdc on op

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
This was unable to be recreated by @tshifty and can probably be closed.

**Comment by gomesalexandre** [comment]
Retested and confirmed we're 🛍️ @purelycrickets 
<img width="618" alt="image" src="https://github.com/shapeshift/web/assets/17035424/74bba9a2-9dd7-4e4f-a028-4477c054ca02">
<img width="1377" alt="image" src="https://github.com/shapeshift/web/assets/17035424/6f84e42f-044c-483f-9e6e-de406825d5cd">
