### ISSUE TITLE
(ALPHA) V2: Trade screen “pending” status doesn’t update to "Confirmed"

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#494]
When a user submits a trade on V2 using metamask, a pending modal pops up.  Once the trade completes (as verified on Etherscan) the pending status does not update to "complete".  Completed trade shows upon refresh.

**Comment by 0xean** [comment]
@Neverwas-dev will re-test and confirm

**Comment by 0xean** [comment]
resolved.
