### ISSUE TITLE
OP trading gas estimation way lower than on chain

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4946]
### Overview

Right now when a user is trading on the OP network using 0x we're showing a miner fee of (0.000000000034111119 ETH ≃ <$0.000001) when in reality the miner fee is 0.000446456588857052 ETH ($0.85). This causes people with way less ETH on OP to push through failed trades that get dropped from the network. https://optimistic.etherscan.io/tx/0x68b5457bc841daa2eb58a2d11b5393364dffdf39b64cc7386cceec1d2f433db2

Recreation Steps:
1. Attempt to do a trade with our miner fee amount with less than .37 of ETH on OP
2. Notice this transaction fails because it gets dropped from the network

<img width="652" alt="OPSSFee" src="https://github.com/shapeshift/web/assets/94189400/a65c8901-d1e5-4272-ad1d-ca3f0fcc2bca">

### References and additional details

N/A

### Acceptance Criteria

Gas estimations for trading on the OP network should be correct

**Comment by MBMaria** [comment]
Looking more accurate now. is this able to be closed or should it still be looked into by engineering?
![image](https://github.com/shapeshift/web/assets/100157997/d688ae74-ea09-428b-8ef2-16491b3e31cb)

**Comment by purelycrickets** [comment]
Seems to be a much more appropriate miner fee. I'm gonna mark this as closed.
