### ISSUE TITLE
Unable to send Osmo

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4967]
### Overview

When trying to complete an Osmosis send, it comes up with error "Your send of Osmosis failed"

### References and additional details

1) Log into app.shapeshift and connect to wallet that supports osmo
2) Navigate to Osmosis asset page and attempt to complete and Osmo send
3) Note the error that appears
![image](https://github.com/shapeshift/web/assets/100157997/b3f49bbe-89ec-4f59-98b1-1c07d15b5cbf)
alot of errors in the console currently but i think this one relates to the failed send
![image](https://github.com/shapeshift/web/assets/100157997/97b395f8-02ea-4332-99fd-37aa5db7f512)

### Acceptance Criteria

Should be able to send osmo successfully

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Most likely a current issue related to the instability of the Osmo node
<img width="857" alt="image" src="https://github.com/shapeshift/web/assets/17035424/8f393755-f22a-496f-94a7-eb7f6f57ab84">

@MBMaria can you go to the network tab when this happens and confirm the error you see for `send` in red when this fails?

For context, this is an error that we've used to see from time to time when trying to do a second Cosmos SDK Tx after a first one was successful, within the same session, and required a page refresh. But I'm now noticing this one when broadcasting the first Tx for a session as well

**Comment by MBMaria** [comment]
Was able to complete an osmo send. the send modal doesn't move to complete after confirming a send and allows you to select confirm again which broadcasts another tx because you dont know immediately if the first tx goes through. After a refresh seeing the send and receive tx in the transaction history
![image](https://github.com/shapeshift/web/assets/100157997/8787aba8-fdfa-4b9c-aefa-e4b41b7fc6c3)
![image](https://github.com/shapeshift/web/assets/100157997/227d747f-cc6d-4c01-8b4a-71cfac212d07)

did not see red for send in the network tab.

**Comment by gomesalexandre** [comment]
@MBMaria if Osmosis sends are consistently happy again and the only issue is with the modal not closing, let's close this and tackle in https://github.com/shapeshift/web/issues/5001
