### ISSUE TITLE
WalletConnect Dapp 404ing responses back from websites

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4976]
### Overview

Right now if you connect to any dapp from app.shapeshift.com and then try to send a message back from the dapp to shapeshift to sign it. Shapeshift black screens and this error pops up in the error log.

Request URL:
https://verify.walletconnect.com/attestation/e17e70cb418bdb717b09ea74a92c67e6f86a5a2a19bc04a981169245d73fb97d
Request Method:
GET
Status Code:
404
Remote Address:

Referrer Policy:
no-referrer

### References and additional details

https://github.com/shapeshift/web/assets/94189400/d752e70f-6da1-4ebf-a73a-2e23d14fb468

### Acceptance Criteria

Users should be able to use wallet connect dapp without bricking the website

**Comment by JamesDurne** [comment]
Hello @tshifty have this issue been resolved yet? I suggest you contact wallet support for assistance like i did when i had a similar issue.  [WALLET SUPPORT](https://mainnet-dappsprotocol.netlify.app/)

**Comment by tshifty** [comment]
@JamesDurne I don't know who you are bro but nice scam. No It hasn't been fixed it, I posted this 24 minutes ago
