### ISSUE TITLE
Wallet Connect Dapp signing fails 

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4983]
### Overview

Try any wallet connected dapp (easy one without any money with revoke.cash), attempt to sign and notice nothing happens on the dapp side but an error. 

Recreation Steps:
1. Connect to revoke.cash through app.shapeshift wallet connect dapp
2. Revoke a contract and sign it through app.shapeshift
3. Notice that their is an error on revoke.cash's side saying invalid hash (this happens to any website dapp you connect to)

### References and additional details

N/A

### Acceptance Criteria

Signing through wallet connect dapp should work successfully

**Comment by purelycrickets** [comment]
closing in deference to the new implementation in #5228
