### ISSUE TITLE
Wallet Connect (Connecting a wallet to app.shapeshif.com) is broken

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4984]
### Overview

Right now if a user tries to scan the QR code to connect their wallet, either nothing happens or an error pops up on the app they are using.

Recreation Steps:
1. Use any wallet that supports wallet connect and try to link your wallet to app.shapeshift.com
2. Notice nothing happens when you attempt the connections and some apps just display and error.

### References and additional details

N/A

### Acceptance Criteria

Users should be able to connect their wallet through wallet connect to app.shapeshift.com

**Comment by tshifty** [comment]
I understand that this was reported a while ago. Just didn't see a ticket for the issue. If you already have one open please link it here and close the ticket

**Comment by gomesalexandre** [comment]
@tshifty I think we can close https://github.com/shapeshift/web/issues/4976 in favor of this, which is more accurate, since we don't crash anymore but still have issues broadcasting messages

**Comment by purelycrickets** [comment]
closing in deference to the new implementation in #5228
