### ISSUE TITLE
Send Modal doesn't update once TX is broadcast

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5001]
### Overview

When completing a send, it will broadcast the transaction then remain on the Confirm screen. It allows you to select Confirm again and it will complete another send. Easy to think the first one failed and select Confirm again. However the green toast appears and the transaction does complete... twice... if you hit confirm twice :P

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Select an asset to send and enter details for a send
3) Confirm send and note that is says "Send broadcasting". After a second it reverts to "Confirm" and then shortly after the green toast will appear in the top right hand corner.
![image](https://github.com/shapeshift/web/assets/100157997/2e54dd18-6a97-4420-a148-d4df871ddc52)

### Acceptance Criteria

Send modal should move across to complete after the transaction has sent

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Introduced by https://github.com/shapeshift/web/pull/4972 and/or https://github.com/shapeshift/web/pull/4971, diffing send modal things there might help
