### ISSUE TITLE
Swapper balance check is broken 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5011]
### Overview

When trading, you can enter an amount more than is available in your wallet and will allow you to preview trade

### References and additional details

1) Log into app.shapshift and connect to wallet of choice
2) Navigate to the trade page
3) Enter a trade where the input asset is more than the balance in your wallet
4) Note you can select preview trade
![image](https://github.com/shapeshift/web/assets/100157997/cfe0fd3c-85ab-4ea2-ba8b-19bae35fb27b)

### Acceptance Criteria

Should not be able to preview a trade when the balance entered is higher than the amount in the walllet

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
Closed by https://github.com/shapeshift/web/pull/5043
