### ISSUE TITLE
Clear cache on native Shapeshift wallet causes the page to load indefinitely

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5013]
### Overview

When clearing the cache on shapeshift wallet, the page will half reload and then spin continuously. Not seeing this behaviour on MM or KK wallet.

### References and additional details

1) Log into app.shapeshift and connect to shapeshift wallet
2) In the Settings menu select "Clear Cache"
3) Note the page starts to refresh but never loads. 
4) To rectify need to disconnect wallet and reconnect.
 
![image](https://github.com/shapeshift/web/assets/100157997/48b8bc1e-32c0-458b-a2a3-8f4004866cb0)

### Acceptance Criteria

Clearing cache should result in the page refreshing and being functional

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Note this isn't strictly related to cache clear, I have noticed this one on page refresh as well.
Looks like the issue is we're not popping up the wallet connect modal on page refresh
