### ISSUE TITLE
Getting 500 errors on initial lifi trade attempt

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5039]
### Overview

When attempting the first lifi trade (cross-chain) after a refresh, the trade will fail
https://discord.com/channels/554694662431178782/1136907860450750475/1137979586152513548
### References and additional details

1) Log into app.shapeshift.com and connect to native wallet
2) Navigate to trade/bridge page
3) Enter a cross chain lifi trade. i.e usdt on matic to usdc on optimism
4) Preview trade and confirm and trade
5) Note the error "Something went wrong"
![image](https://github.com/shapeshift/web/assets/100157997/67e74cae-d6b8-48a2-9a5e-df9019d5e1ff)
![image](https://github.com/shapeshift/web/assets/100157997/8951eb0a-0da2-4356-a6fe-1a4656e89783)

https://github.com/shapeshift/web/assets/100157997/8bb9c197-6d33-4c95-9d50-ee627915c18a

### Acceptance Criteria

Lifi trade should complete after selecting "confirm and trade"

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
Transferring my comments from Discord:

It might be something to do with a node issue, as `https://api.CHAIN.shapeshift.com/api/v1/send` `500`s with `timeout of 10000ms exceeded`. That said, I _think_ that only happens when we get a `500` first from LiFi's `https://li.quest/v1/advanced/stepTransaction`, which responds with the following:

```json
{
    "message": "An unknown error occurred. Please seek assistance in the LI.FI discord server."
}
```

**Comment by 0xApotheosis** [comment]
This was not fixed by bumping the SDK 😞

**Comment by woodenfurniture** [comment]
currently resolved in production
