### ISSUE TITLE
Unable to perform actions in App when opening a new tab/refreshing app

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#5045]
### Overview

The app gets in a state where you can browse but not perform actions when a user has hit the refresh button or when a new tab is opened. 
 1. connect native wallet on web
2. refresh app/open a new tab 
3 Observe state where you can browse app, but can't initiate transactions. wallet shows as forever 'Connecting...' in the dropdown

### References and additional details

<img width="315" alt="image" src="https://github.com/shapeshift/web/assets/94998097/c918ab56-3fdc-4d6e-ada1-85a07c88e500">
![image-1](https://github.com/shapeshift/web/assets/94998097/bd6958b0-ebb0-41d9-8b0b-d7115b46f499)
Wallets after a refresh

### Acceptance Criteria

The app be able to function properly when a user refreshes or opens a new tab.

**Comment by 0xApotheosis** [comment]
Additional context: we used to show the reconnect modal to enter a password when the connected wallet it locked, but a regression (probably related to performance improvements?) broke this.
