### ISSUE TITLE
Lifi Trade Confirmed page does not update with green tick once trade completed

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5049]
### Overview

After completing a lifi trade, the trade modal doesn't update to the Green tick once its confirmed on the blockchain. Instead it just stops spinning.

### References and additional details

1) log into app.shapeshift and connect to wallet of choice
2) navigate to trade page and enter lifi trade (definitely same chain, maybe cross chain) 
3) Preview trade and confirm and trade
4) Note that once trade is completed, the green tick does not appear and the loading circle just stops spinning
*post release 1.397.0 - https://github.com/shapeshift/web/pull/5048
![image](https://github.com/shapeshift/web/assets/100157997/07266c61-b51e-40dc-93d7-966b6ebde9d9)

### Acceptance Criteria

Green Tick should populate once trade has completed

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by woodenfurniture** [comment]
cannot repo so far, will need to obtain some BUSD to try the pair above
![image](https://github.com/shapeshift/web/assets/125113430/da15efd3-69d0-42ee-a4ed-584b1cc268f4)
![image](https://github.com/shapeshift/web/assets/125113430/497981dd-e03e-4c6d-96c5-d6f3c4ff55aa)

**Comment by woodenfurniture** [comment]
The above is incorrect, their docs are out of date and 0x is actually valid. The issue turned out to be a problem with caching in lifi sdk.
