### ISSUE TITLE
QR Code has more info than just address

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#5068]
### Overview

QR Code is busted on app.shapeshift.com, it gives more info than just the address.
<img width="490" alt="Screen_Shot_2023-08-13_at_6 41 22_PM" src="https://github.com/shapeshift/web/assets/94189400/1e2e9691-99c0-4563-8f09-057a6e248cff">

### References and additional details

N/A

### Acceptance Criteria

QR Code should paste the address, with no extra info.

**Comment by purelycrickets** [comment]
A fix in this should also be mindful of any regressions that might show up related to the way Coinbase displays qr codes with extra data.
