### ISSUE TITLE
FOXy Deposit/Withdraw modal does not update beyond pending

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#5074]
### Overview

When making a deposit or withdraw to the FOXy staking pool, the modal for Performing the transaction does not update to Success even though the TXIDs post to chain. 

### References and additional details

![Screenshot 2023-08-14 at 4 00 54 PM](https://github.com/shapeshift/web/assets/94998097/feee8b09-00ed-438d-b35e-180a99916c20)
![Screenshot 2023-08-14 at 3 31 42 PM](https://github.com/shapeshift/web/assets/94998097/deb9bfc4-677f-4e26-ad7c-3baa2d71d41b)
Forever pending

### Acceptance Criteria

FOXy staking modals update correctly when a user performs a FOXy deposit or withdraw action.

**Comment by 0xean** [comment]
low priority on foxy at the moment.

**Comment by gomesalexandre** [comment]
@purelycrickets Deposits are now disabled, however I wasn't able to test withdraws either, are we still able to repro this?
