### ISSUE TITLE
Alchemy spam NFT blocks 🙈

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#5075]
### Overview

We have a bunch of scam NFT's coming up on the demo wallet and on users accounts. We'd like to remove the dust and make sure our site doesn't get flagged as a phishing zone. 

### References and additional details

https://docs.alchemy.com/reference/isairdrop

### Acceptance Criteria

NFT's that scammy are hidden by default

### Screenshots/Mockups

![IMG_EE077635D824-1](https://github.com/shapeshift/web/assets/8991325/07b8fb1e-c7de-4737-a92a-8589dfdd422b)

### Estimated effort

1/4 day

**Comment by gomesalexandre** [comment]
@twblack88 I'm not sure isAirdrop Alchemy endpoint is the best solution for users, as it would hide legitimate airdrops and accidentally doesn't seem to properly detect spammy airdrops. `isSpamContract` would be a better one, though we already exclude spam NFTs both with Alchemy and Covalent calls currently (Zapper doesn't allow this unfortunately), so we should theoretically only have "legitimate" NFTs currently in the NFT page. Which means we could *theoretically* introspect the NFT slice and an NFT being missing from there means it's a spam and we could hide the row.

Unfortunately, there are two interlinked issues here:

1. Spam detection is only as good as the data from the 3 APIs (Zapper, Alchemy and Covalent), e.g for Alchemy:

<img width="1085" alt="image" src="https://github.com/shapeshift/web/assets/17035424/6ef75b73-b298-41c7-9060-54dccc2c93f7">
<img width="1494" alt="image" src="https://github.com/shapeshift/web/assets/17035424/3daefb7c-f143-40db-a548-eb4ae95e2152">
<img width="1486" alt="Screenshot 2023-08-17 at 19 05 36" src="https://github.com/shapeshift/web/assets/17035424/80acdf2c-ab67-42d0-a64c-28299fd6dd70">

Also see the request we make to get the NFTs, we should theoretically exclude spams:

https://paw.pt/h4VxJOFj

2. Different APIs return us different NFTs, so in addition to spams not being properly detected by these APIs, there are also missing legit NFTs depending on the API, see e.g missing FOXatar in Zapper

<img width="1474" alt="image" src="https://github.com/shapeshift/web/assets/17035424/ead83f52-1d76-40b8-af0c-c05cbe7cdcb2">
<img width="1394" alt="image" src="https://github.com/shapeshift/web/assets/17035424/830c3de7-a8e9-47d8-b99d-dc1db2f1a4ec">

@twblack88 noticed this endpoint https://docs.alchemy.com/reference/reportspam, not sure how reactive Alchemy is on these, but WDYT about implementing a button to call it, then hiding the NFTs client-side? We could have a `isSpam` property set to true after a user clicks the report spam button, which we could would then use to instantly hide NFTs everywhere applicable, for the lifetime of a browser session.

**Comment by twblack88** [comment]
> WDYT about implementing a button to call it, then hiding the NFTs client-side? We could have a isSpam property set to true after a user clicks the report spam button, which we could would then use to instantly hide NFTs everywhere applicable, for the lifetime of a browser session.
Into it. 

When we say "hide NFTs" we mean scoped to the collection id (aka `address`)

**Comment by gomesalexandre** [comment]
Scoped to the collection (not the NFT ID only) be the best indeed @twblack88, that's how it is reported on Alchemy's side

**Comment by twblack88** [comment]
Can we prio this bad boi tomorrow @gomesalexandre at end of day? We got dusted with some more BS and it would be good to not have to deal with it.

**Comment by twblack88** [comment]
<img width="682" alt="Screenshot 2023-08-25 at 10 27 41 AM" src="https://github.com/shapeshift/web/assets/8991325/ec740fab-7e3e-4d76-beeb-a8d9d44ff516">

Spiked on this and set up a draft UI for @reallybeard approval by end of next week no rush. Ideally we'll drop the fontawesome `FaExclamationTriangle` into the report spam button top right above the image and make the boxes behave. 

As a user i want tio click on spam NFT, click on the triangle to report it, and see the  spam vanish so that my NFT dash looks correct.
