### ISSUE TITLE
Transaction history does not have the date showing 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5076]
### Overview

When looking up transactions from the transaction history, the date is not displayed. can see the month and year only

### References and additional details

1) log into app.shapeshift and connect to wallet of choice
2) navigate to 'Activity' tab
3) note that the Month is listed but no date in front of it
![image](https://github.com/shapeshift/web/assets/100157997/bc3b9937-db57-4af3-af35-871aa5fee9e7)

### Acceptance Criteria

Should be able to see the date of the transaction

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by firebomb1** [comment]
Noticing that there's also a Localization issue with the date (they are not translated and always in English format). I'll make a PR to fix these issues.
