### ISSUE TITLE
Unable to bridge or swap FOX on Optimism even though both LiFi and 0x support in their UI

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#5096]
### Overview

LiFi's UI and API supports bridging FOX on mainnet to FOX on optimism via a single hop, and 0x's UI (and I assume API) supports swapping FOX/wstETH on Optimism. However, when you try the same pairs in ShapeShift, the app says no rate available.

Ideally we can fix this for both FOX as well as any other pairs that our partners support but we don't (both in the API and interface). At the very least, we should understand why it works in their UI and API but not on ShapeShift.

This is a blocker for launching FOX/wstETH liquidity mining on Optimism, which we've been granted 20k OP for that we're working to get matched by Lido.

### References and additional details

Steps to reproduce on LiFi:
1. Set up a FOX on mainnet to FOX on Optimism bridge on [LiFi's UI](https://jumper.exchange/?fromAmount=5000&fromChain=1&fromToken=0xc770eefad204b5180df6a14ee197d99d808ee52d&toChain=10) or API and see it returns a single hop bridge route
2. Try setting up the same bridge in ShapeShift's UI or API and see it returns 'no rate available'

<img width="877" alt="image" src="https://github.com/shapeshift/web/assets/26232238/1ff831f6-7049-4218-96e6-d37bde49ab60">

<img width="346" alt="image" src="https://github.com/shapeshift/web/assets/26232238/32810077-0d33-4b0c-b3c1-8e10ba98fa11">

Steps to reproduce on 0x:
1. Set up a FOX on Optimism to wstETH on Optimism swap in [matcha's UI](https://matcha.xyz/tokens/optimism/0xf1a0da3367bc7aa04f8d94ba57b862ff37ced174) and see it returns a rate (although note that it does see FOX's price as $0.00 and so calculates a price impact of 100%)
2. Set up a FOX on Optimism to wstETH on Optimism swap in ShapeShift's UI and see it returns 'no rate available'

<img width="474" alt="image" src="https://github.com/shapeshift/web/assets/26232238/4ba977c9-91f2-46f2-a1c5-3c58d18b4c07">

<img width="333" alt="image" src="https://github.com/shapeshift/web/assets/26232238/d7d57904-da6f-4ad7-8284-f5a0f964ae10">

### Acceptance Criteria

AC:
Ideal: Enable users to swap and single-hop-bridge the same pairs in ShapeShift that they can on 0x and LiFi (at least for tokens that shapeshift supports)
At least: Determine why some pairs such as FOX are supported in 0x and LiFi but not in ShapeShift, and create a separate issue with the details

**Comment by gomesalexandre** [comment]
This is the offender: https://github.com/shapeshift/web/blob/ae6a8807e41c85b2126034b7feafff37bd90d432/src/state/apis/swappers/swappersApi.ts#L31

I think we should be able to safely assume FOX price for all bridged versions here, though it definitely feels hacky, as this may happen with other bridged assets we don't have market data for

**Comment by gomesalexandre** [comment]
> @gomesalexandre So like 1 FOX = 1 FOX? sounds like slippage errors and other issues to me. We can keep digging.

More like we don't have market data for the Optimism flavor of bridged FOX and bail out @twblack88 , instead of using the mainnet market data for it.
This is really just informative anyway, as the rate is only for us to display what the market data is for a given asset, but won't impact the quotes we're getting (we are in fact getting quotes here on that pair, but we bail out early) this is a totally separate concern

**Comment by willyogo** [comment]
> I think we should be able to safely assume FOX price for all bridged versions here, though it definitely feels hacky, as this may happen with other bridged assets we don't have market data for

Makes sense to me as long as we're just using it to display a fiat value and the assets are mapped to eachother.

Does this explain for both LiFi and 0x @gomesalexandre? William mentioned another potential issue in [discord](https://discord.com/channels/554694662431178782/1128753936501854289/1141841169270181899):

"The API will return an error of insufficient liquidity due to the price impact being higher than the defined limit. The threshold is easily customizable by setting PriceImpactProtectionPercentage anywhere from 0-1, so we encourage every Swap API user to customize this parameter based on their needs and tolerance.

https://0x.org/docs/0x-swap-api/advanced-topics/price-impact-protection"

--

If this is also an issue, I think we should be able to set to 1 because we have solid price impact handling in the UI (and may to give ShapeShift API customers their own ability to set this between 0-1)

**Comment by gomesalexandre** [comment]
Correct @willyogo this is the same issue for ZRX, see
<img width="1165" alt="image" src="https://github.com/shapeshift/web/assets/17035424/2973f781-8b52-4e80-b963-ac3eb8668c97">

**Comment by gomesalexandre** [comment]
Thanks for reporting this @sktbrd. Unfortunately, we don't have market data for BRZ, thus are unable to show a quote as we don't have USD rate for it.
Matcha use an internal `/api/get-usd-prices` endpoint to which is how they're able to get a USD rate, unfortunately, their API isn't public so we cannot consume it.

<img width="679" alt="image" src="https://github.com/shapeshift/web/assets/17035424/a04b2d2b-2ac9-404e-a0e3-576fa05eb714">

**Comment by willyogo** [comment]
@gomesalexandre I'm not sure why we don't have a fiat price for BRZ; it's in coingecko's tokenlist and has a [price on coingecko](https://www.coingecko.com/en/coins/brazilian-digital-token).

Regardless, can you help me understand why we need a fiat price in order to show a quote? I'd expect we could display/return quotes for any assets that 0x can. in the past we've been able to support DEX trading for assets with no fiat value as long as we could get a quote from a provider.

**Comment by gomesalexandre** [comment]
> @gomesalexandre I'm not sure why we don't have a fiat price for BRZ; it's in coingecko's tokenlist and has a [price on coingecko](https://www.coingecko.com/en/coins/brazilian-digital-token).

Nice catch @willyogo, this would be the explanation

<img width="1286" alt="image" src="https://github.com/shapeshift/web/assets/17035424/4fb5d27f-bf03-441b-bae6-c4923a9d9e6d">

Authored https://github.com/shapeshift/web/pull/5123 which regenerated asset data, including the updated contract for BRZ.


WRT the second point, we do need a USD rate in order to allow user input in fiat, as we *are* getting quotes as well as to show fiat rates in swapper. Theoretically, we could remove the safeguards against having USD rates for both buy and sell assets, though that's probably more of a product concern here

**Comment by willyogo** [comment]
thanks @gomesalexandre 🙏  good q for @shapeshift/product on whether we can remove the USD rate safe guard for buy and sell assets. my gut says we could just show either no fiat value or $0.00 and disable inputting a fiat amount. it looks like this will be limited to edge cases, so may not be worth the squeeze until we support inputting custom tokens via contract address
