### ISSUE TITLE
Optimise streaming interval

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#5112]
### Overview

Currently our thorchain streaming swap interval is hardcoded to 10 
```
export const DEFAULT_STREAMING_INTERVAL = 10
```

We should optimise this based on the documentation.

### References and additional details

https://dev.thorchain.org/thorchain-dev/concepts/streaming-swaps

### Acceptance Criteria

Streaming swap interval is calculated dynamically using the approach detailed in the documentation rather than using a hardcoded value.

**Comment by woodenfurniture** [comment]
Requesting input on this before starting - this could be a UI feature or we could leave it as-is

**Comment by woodenfurniture** [comment]
Currently thorswap is using a (seemingly hardcoded) 9 block interval for their swaps, so our current default of 10 seems to be sufficient considering it will result in slightly cheaper trades in our app

**Comment by gomesalexandre** [comment]
@woodenfurniture do we want to close this or do we still want to investigate better heuristics for streaming interval?

**Comment by woodenfurniture** [comment]
Closing until we have some sort of direction on this since it's fine as is :)
