### ISSUE TITLE
Add Slippage support to CoW Swap

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#5116]
### Overview

The CoW swap API doesn't explicitly support slippage. The CoW app UI has slippage input, but implements it by submitting an order with a lower `buyAmountAfterFee` param (as a function of the user's selected slippage) if the initial order fails due to price movement.

### References and additional details

For us to implement it (with the current shape of our data), we'll need to update `src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts` such that if a user specifies a slippage amount, we get an initial quote of `kind: "sell"` by specifying the `sellAmountBeforeFee`, then get a second quote specifying `kind: "buy"` with a `buyAmountAfterFee` value specified, which takes the `buyAmount` returned in the first quote (which is before fees), get the after fees amount (using `getValuesFromQuoteResponse`), and then subtracting slippage (using `convertDecimalPercentageToBasisPoints`).

This would also need to be updated in `getUnsignedTx`.

Unfortunately, doing this with the current internal quote shape requires market data. We might want to consider storing the `buyAmountAfterFee` on the `TradeQuote2` shape to make this more ergonomic.

CoW docs: https://api.cow.fi/docs/#/default/post_api_v1_quote

### Acceptance Criteria

We support CoW slippage by using the `buyAmountAfterFee` param of the quote request to allow the user to input a custom slippage value.

**Comment by 0xean** [comment]
closed in #5119
