### ISSUE TITLE
Wrongly insufficient xDAI on Gnosis for Lifi trade

### ISSUE THREAD

**Issue by koeppelmann** [shapeshift/web#5136]
### Overview

Want to trade Gnosis - EURe -> Mainnet - FOX
Connected with Rabby
Have >10 xDAI on my account.
Still, get the error I would have insufficient.

<img width="619" alt="Screenshot 2023-08-22 at 09 38 04" src="https://github.com/shapeshift/web/assets/2594089/0c012af3-f1dd-4bee-856e-a11742895a6e">

### References and additional details

...

### Acceptance Criteria

...

**Comment by gomesalexandre** [comment]
Hi @koeppelmann, I assume this is using Li.Fi given the cross-EVM-chains nature of the swap.

If you look at the protocol fees, by expanding "Expected Amount", you'll see Li.Fi fees for bridging to mainnet (typically with Connect/Hop) are usually quite high, at ~50 xDAI currently, which would explain why ~10 USD is insufficient for the trade (this is with an account that has ~1 xDAI): 

<img width="542" alt="image" src="https://github.com/shapeshift/web/assets/17035424/2bd52d53-31db-4090-9b62-cfed6137e95e">

Can you confirm you have enough xDAI on that account for protocol fees?

**Comment by koeppelmann** [comment]
@gomesalexandre I see. I expected I had to only pay the gas costs for the Gnosis trasnaction and the gas costs for mainnet would be deducted from the trade. However, if the xDAI is used to cover mainnet costs it of course makes sense that $10 is not enough.

Thank you.
