### ISSUE TITLE
No market price for osmo on cosmos

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5158]
### Overview

When looking up Osmo on cosmus hub, the market data is missing so it has a zero value

### References and additional details

1) Log in app.shapeshift.com and connect to wallet of choice
2) naviagate to 'Wallet' and select "Cosmo"
3) Note that an osmo on cosmos has a $0.00 value. 
![image](https://github.com/shapeshift/web/assets/100157997/21059eaf-c221-4561-a6b1-5da5297afbdf)
![image](https://github.com/shapeshift/web/assets/100157997/96c0dddd-e36d-4b7e-b5bf-08eab92d80eb)

### Acceptance Criteria

Market value should be available for osmo on cosmos

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
wontfix
