### ISSUE TITLE
Net Worth balance double counts DeFi and Rewards amounts

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5202]
### Overview

The Net Worth of the wallet has the balance of the wallet plue the defi position which includes the rewards and then is adding the value of the rewards again on top overstating the net worth of the wallet

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) On the Dashboard note that the Net Worth is made up of the Wallet, DeFi and Rewards amount. note that the rewards is double counted. 
![image](https://github.com/shapeshift/web/assets/100157997/7c7dffd8-4898-4d45-b885-0fbcee952605)

### Acceptance Criteria

Net Worth should be wallet plus defi plus rewards but rewards should not be double counted. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Confirmed fixed:

<img width="638" alt="image" src="https://github.com/shapeshift/web/assets/17035424/bf5bf969-91b8-42c5-afc5-03e8c25801ef">

692.42+360.94+5.83 = 1059.19
