### ISSUE TITLE
Unable to send any BNB assets

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5211]
### Overview

When trying to send USDT on BNB, it comes up with an error

### References and additional details

1) Log into app.shapeshift and connect to wallet that supports BNB
2) Navigate to USDT on BNB page and initial Send
3) Enter amount to send and continue.
4) Note once confirming amount to send it comes up with an error.
![image](https://github.com/shapeshift/web/assets/100157997/8802dc7d-accc-44cf-9401-1d3b11b1281d)
![image](https://github.com/shapeshift/web/assets/100157997/620e2940-5c6f-4018-a8d8-e9b883c882b1)

### Acceptance Criteria

Should be able to send USDT on BNB

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
Note sure if its related but unable to complete a USDC on BNB approval for 0x as well . 
![image](https://github.com/shapeshift/web/assets/100157997/f92b19db-03f1-4e74-a9dd-444bbadfea78)
![image](https://github.com/shapeshift/web/assets/100157997/8d0ad602-58b0-4014-bd69-b2181c0148b8)

**Comment by MBMaria** [comment]
Update from the user who found the problem: 
"There is a problem with the section that calculates the fee of transactions in BNB. I tried to send it by paying the minimum and average fees, but it shows the same error we commented on before. However, when you select the priority fee, the withdrawal order is executed successfully."

**Comment by MBMaria** [comment]
another approval on bnb not working (usdc) 
![image](https://github.com/shapeshift/web/assets/100157997/c63afe1a-df72-4a78-85c6-51d92eaf26df)
![image](https://github.com/shapeshift/web/assets/100157997/bb1dc504-c973-433e-a1e1-231a807d7864)

**Comment by MBMaria** [comment]
sending of bnb not isolated to usdt - seems to be all bnb 
![image](https://github.com/shapeshift/web/assets/100157997/eabaa663-ce06-441e-a0db-8ebb14a24c69)

**Comment by MBMaria** [comment]
Okay so got the same error for xDai on gnosis. i tried a second time and it failed, on the 3rd attempt i opted for 'fast' when selecting gas fee. if failed. tried fast fee again and it worked. 
![image](https://github.com/shapeshift/web/assets/100157997/a5f723b0-93dd-4579-95a5-6203a0307ee8)

**Comment by gomesalexandre** [comment]
> Okay so got the same error for xDai on gnosis. i tried a second time and it failed, on the 3rd attempt i opted for 'fast' when selecting gas fee. if failed. tried fast fee again and it worked. ![image](https://user-images.githubusercontent.com/100157997/266194359-a5f723b0-93dd-4579-95a5-6203a0307ee8.png)

@MBMaria tested both self and cross-account sends of xDAI with slow, fast and average fee, both on prod and develop , and on both native and MM, which all went in without hassle. Can you still repro for xDAI? 

I was able to repro for cross-account on BSC however:

<img width="608" alt="image" src="https://github.com/shapeshift/web/assets/17035424/8148d1b4-7976-4cb2-98d8-2859ea203326">

**Comment by MBMaria** [comment]
@gomesalexandre was able to do an xdai send straight away on average fee just now
![image](https://github.com/shapeshift/web/assets/100157997/f2f0fbcc-c1b7-490f-a53a-73cdb2a2111e)

**Comment by gomesalexandre** [comment]
Fixed by https://github.com/shapeshift/web/pull/5234
