### ISSUE TITLE
Coinbase Link for buying/selling Fox not working

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5220]
### Overview

When trying to buy or sell fox the Coinbase link is a dead click

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to Arkeo Airdrop Page
3) Under FOX Token Holders select "Buy FOX"
4) Note that you get an error in the console right away: 
![image](https://github.com/shapeshift/web/assets/100157997/f4f1b492-2498-422c-b80a-0e027c0886d7)
5) If you select Coinbase, it is a dead click. you get this error in the console: 
![image](https://github.com/shapeshift/web/assets/100157997/01417902-4c30-4262-b7e1-e7e46e0d7acd)
Same for the Sell screen as well.

### Acceptance Criteria

Should be able to access Coinbase from this link

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Note this isn't only an issue within the Arkeo page - same deal with the buy button in asset page, and the "TopAssets" i.e this guy:

<img width="1194" alt="image" src="https://github.com/shapeshift/web/assets/17035424/7fe45403-4937-4d27-98cf-1294c199092a">
