### ISSUE TITLE
Support Thorchain Swapping for BSC

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#5233]
### Overview

Per convo in Product stand up Big Kev stopped in for, should be a three liner to support the upcoming support for BSC being a Tradable TC asset. 

### References and additional details

https://x.com/thormaximalist/status/1699649235355046067?s=46 Tweet mentioning BSC going live in a few days. 

### Acceptance Criteria

BSC should be tradable via TC after this change. 

### Need By Date

9/10/2023

### Estimated effort

three liner

**Comment by kaladinlight** [comment]
PR ready to roll for when they deploy the router contract to enable LP and trading for BSC
