### ISSUE TITLE
Unable to stake in Cosmos SDK

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5250]
### Overview

When trying to stake in Cosmos SDK, it says the transaction is complete, but the txid on the blockchain says it was unsuccessful. 

### References and additional details

1) Log into app.shapeshift and connect to wallet that supports Cosmos SDK
2) Navigate to DeFi page and find Cosmos SDK
3) Select Deposit and enter amount, select Continue
4) Sign and Broadcast
5) Note it says Transaction Confirmed
6) Drop down on Details and select the "view on chain" 
7) Note the transaction is unsuccessful 
![image](https://github.com/shapeshift/web/assets/100157997/4b235ed0-2709-419f-a49e-ab70cb7a4325)
![image](https://github.com/shapeshift/web/assets/100157997/883bdc47-686e-44b0-9130-3af57d01b050)
![image](https://github.com/shapeshift/web/assets/100157997/02c068c6-8efb-4b4a-8fdd-9f323b7c06a3)
![image](https://github.com/shapeshift/web/assets/100157997/1817fbf3-f49f-42d5-bba6-4a2f7b327635)
https://www.mintscan.io/cosmos/transactions/57FB6816218DD148D7F129E991955A73C6E7E43A7A4C3C15007AC9F10E53BDC3

### Acceptance Criteria

Should be able to stake into Cosmos SDK

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
GAIA hardfork rugging us here - I was unable to test. Will take a look when the route is available again
