### ISSUE TITLE
Issues with Wallet Connect: 1inch swap tx link broken

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5285]
### Overview

Listing different issues found when connecting Shapeshift to another dApp using Wallet Connect

### References and additional details

Attempting a swap using native wallet connect to 1inch (usdc to eth). Signed tx in app.shapeshift and then 1inch said the transaction was sent but if you check the etherscan it gives the link below. getting console errors on shapeshift.
https://etherscan.io/tx/0xf9012f8202e9847356851083029cde941111111254eeb25477b68fb85ed929f73a96058280b8c80502b1c5000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000000000000000000001312d00000000000000000000000000000000000000000000000000002b0b5291691efa0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000140000000000000003b6d03403aa370aacf4cb08c7e1e7aa8e8ff9418d73c7e0fe26b997726a010231f660de006004a62c17fb87a4636a5337e69f8fc46e8f93cecba50ebbb86a0634f40d4013ccd9437d2831f8bdf0f40bd35564005b30563d7a707df325aa869
![image](https://github.com/shapeshift/web/assets/100157997/7764b850-1bd1-45cb-8467-af51d3c20a0e)
![image](https://github.com/shapeshift/web/assets/100157997/d09eb9e8-7b53-47c4-a39c-e8a3a44aace2)
![image](https://github.com/shapeshift/web/assets/100157997/55ed6d36-c42d-4ff6-9f14-aa93e13868d3)

### Acceptance Criteria

Should be able to sign and complete transaction in connected dApps

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by woodenfurniture** [comment]
RE point 6 - this is 1inch, not us. They generate that buggy url:


![Image](https://github.com/shapeshift/web/assets/125113430/2820620e-5887-4635-bc66-8179204b1a32)

https://etherscan.io/tx/0xf9014d2a8468acc4f183033298941111111254eeb25477b68fb85ed929f73a96058280b8e80502b1c5000000000000000000000000c770eefad204b5180df6a14ee197d99d808ee52d00000000000000000000000000000000000000000000000564ddb92db418a32800000000000000000000000000000000000000000000000000000000001f8c4f0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000280000000000000003b6d0340470e8de2ebaef52014a47cb5e6af86884947f08c00000000000000003b6d034026642be81ffd799b8588a5602758d1f34e9ff7bae26b997725a035d725da1540d4a7d125f05b67cd50a41d6e319d3829c6b55ea0ce78538053c4a014c852a62b133d627a2ecdf1a1c141a3781a1d1f030b94696ff16064a642a109
![Image](https://github.com/shapeshift/web/assets/125113430/f36fc16d-554d-4f4c-83b6-6360a4164e52)

**Comment by woodenfurniture** [comment]
closing as commented, not something on our side

**Comment by woodenfurniture** [comment]
will double check with trust wallet

**Comment by woodenfurniture** [comment]
trust wallet working - this issue is on our side
