### ISSUE TITLE
Wallet Connect Issue: safe wallet - creating new wallet

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5304]
### Overview

creating new account gives an error after signing with the kk, wont allow the account to be created.

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/d10adf10-cbc2-4cd0-bde8-8fe50f35da69)

### Acceptance Criteria

Should be able to create new wallet

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
Attempting to create new safe account with trust wallet and still getting an error. this time says its to do with gas estimates. 
![image](https://github.com/shapeshift/web/assets/100157997/899c25f2-f910-4bf4-8568-26bec9e10f23)

**Comment by woodenfurniture** [comment]
Will try with native

**Comment by woodenfurniture** [comment]
closed with #5372


![Image](https://github.com/shapeshift/web/assets/125113430/5ba5df3f-c5c0-4573-a108-86a7ca9a4eb2)

![Image](https://github.com/shapeshift/web/assets/125113430/ded050f0-7b98-43e3-b590-6176e66c7eb8)
