### ISSUE TITLE
Wallet Connect Issue: uniswap - signing tx doesnt complete

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5305]
### Overview

 Connect to uniswap snf try a swap, eg: usdc to eth. Was able to sign with the wallet to enable spending and then just spun continuously in uniswap. could see the 1 pending tx in the top right hand corner. selecting the approving usdc tx listed in pending gives this link: https://etherscan.io/tx/0xf8ab8202e985015d40793d82ed1c94a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4880b844095ea7b3000000000000000000000000000000000022d473030f116ddee9f6b43ac78ba3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff25a00495dd86679ccb223b053d25469c60c87a0dc476477c901cb9b4de5bff2dad87a00bcce31d44dde837097743082749056f9e02492044f170f3c0e52173778fda57

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/79b69e57-2886-45e1-abf3-2ea01ddc8581)
![image](https://github.com/shapeshift/web/assets/100157997/d7a8b086-f8d3-4481-a081-132107a8e731)

### Acceptance Criteria

Should be able to sign and complete a tx

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
Attempting swap with trust wallet connect to uniswap and getting an error straight away on uniswap saying swap failed
![image](https://github.com/shapeshift/web/assets/100157997/da7b3b27-f1f9-43b0-ba2a-76e916387a2f)

![image](https://github.com/shapeshift/web/assets/100157997/2cb29664-f5b7-4b89-8f3f-e5231a81fc1d)

**Comment by woodenfurniture** [comment]
After some investigation this appears to be an issue on uniswap side. Trust wallet is able to trade however other wallets (gnosis safe) are seeing similar issues, refer to uniswap issue for details:
https://github.com/Uniswap/interface/issues/7086

**Comment by woodenfurniture** [comment]
The issue still appears to be specific to Uniswap's handling of ERC-20 tokens in the context of walletconnect requests sent to us; native assets continue to function as expected. As this issue falls outside the scope of our project's codebase, we are closing this ticket.
