### ISSUE TITLE
Issues with Wallet Connect: zapper - signed tx gives error in dApp

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5307]
### Overview

Trying to swap using Zapper. Selecting confirm caused a transaction to be signed in app.shapeshift. signed it then got the error in zapper. (2x)

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/8cb5d27f-9d40-4ec7-9cc6-35c99967376d)
![image](https://github.com/shapeshift/web/assets/100157997/df0f8af3-e451-4e5c-8c08-dfd01c16c033)

### Acceptance Criteria

Signing the tx in app should sign the tx in the dApp

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
Connected trust wallet to zapper and got the same error. looks like its a zapper issue, not necessarily a shapeshift issue. 
![image](https://github.com/shapeshift/web/assets/100157997/7a9ddc8b-2d74-4330-a8b0-8d3a61b998d4)

**Comment by woodenfurniture** [comment]
closed by 5372


![Image](https://github.com/shapeshift/web/assets/125113430/c28855bf-cb0e-498d-a033-540ff5515ee0)
![Image](https://github.com/shapeshift/web/assets/125113430/fdc4c796-d541-49b2-8609-96603e18bfdc)
![Image](https://github.com/shapeshift/web/assets/125113430/0a794c7a-65c2-4352-92db-727313c6b4b7)
![Image](https://github.com/shapeshift/web/assets/125113430/c653cd33-f777-48f1-8877-79c58a2eb00c)
