### ISSUE TITLE
Issues with Wallet Connect: opensea - switching network causes error

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#5312]
### Overview

Listing different issues found when connecting Shapeshift to another dApp using Wallet Connect

### References and additional details

Connect to Opensea and try purchase any NFT that isnt on ETH and note that the transaction wont complete - gives error about not being able to switch network 
![image](https://github.com/shapeshift/web/assets/100157997/6a1c5940-b760-4f1e-8311-0252c30017de)

### Acceptance Criteria

Should be able to sign and complete transaction in connected dApps

**Comment by MBMaria** [comment]
Trying to purchase an NFT in BNB using Opensea says to check wallet to sign, but nothing appears in trust wallet. No tx comes across to be signed. 
![image](https://github.com/shapeshift/web/assets/100157997/984912ba-4926-4461-949b-66e703ddc0ad)

**Comment by MBMaria** [comment]
When opensea is connected to shapeshift, you cannot change the network. gives an error. When connected to trust wallet you can switch between chains no problem.

**Comment by woodenfurniture** [comment]
Strategy to solve:
* import seed into trustwallet mobile and try to repo with that

**Comment by woodenfurniture** [comment]
Work on trust wallet - need to retry with shapeshift in case issue was fixed on opensea side

**Comment by woodenfurniture** [comment]
This issue is on opensea side, caused by running older version of walletconnect 2
https://github.com/MetaMask/metamask-mobile/issues/6655#issuecomment-1609461290
