### ISSUE TITLE
Replace `axios-cache-adapter` with `axios-cache-interceptor`

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#5333]
### Overview

Replace the deprecated axios-cache-adapter package with axios-cache-interceptor.

### References and additional details

The axios-cache-interceptor package was introduced in PR #5328 and is intended to supersede axios-cache-adapter.

### Acceptance Criteria

* Remove axios-cache-adapter from project.json.
* Ensure that all instances where axios-cache-adapter was used are refactored to utilize axios-cache-interceptor.
* Validate that the transition does not introduce regressions or new bugs.
* Confirm that caching behavior remains consistent with previous implementation.
* Update any relevant documentation to reflect the change.

**Comment by gomesalexandre** [comment]
https://github.com/shapeshift/web/pull/5602 crashing the app may be related to `axios-cache-interceptor`, taking a look
