### ISSUE TITLE
SCP 153 Implementation {FOX Page}

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#5362]
### Overview

We want to ad a page to tell users the benefit to hold fox, where to buy fox, where to send fox, and what you can do. 

At the bottom there needs to be a CTA to governance as well. 

### References and additional details

https://www.notion.so/shapeshift/SCP-153-implementation-FOX-Fees-simulator-page-summary-modal-display-e2f89143fd704f7588862e9518a3b2d4?pvs=4

### Acceptance Criteria

- [ ] Plot.ly behaves so we have an interactive model
- [ ] Sliders work to update said model
- [ ] all the opportunities display correctly
- [ ] people can manage older FOX assets if they need to (e.g., FOXy)
- [ ] Governance link out good

**Comment by 0xean** [comment]
nice to have, lower priority.

**Comment by twblack88** [comment]
closing this for a better spec once rFOX is out.
