### ISSUE TITLE
Fix CoW swap message signing on WC2 wallets

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#5371]
### Overview

When clicking Trade Confirm we an error about an invalid or missing payload:

```
Error: Missing or invalid. Decoded payload on topic 888b5da3e5c91d0c5d877138e61fbe84c5f652c7a553d56e8a7edbc9446db9d2 is not identifiable as a JSON-RPC request or a response.
```

### References and additional details

This likely applies to all `eth_sign` transaction types.

### Acceptance Criteria

CoW swaps should sign correctly when connected to a wallet via WC2.

**Comment by 0xApotheosis** [comment]
This one has me a bit stumped. It seems to be something up with the payload we are sending CoW, but we are just passing the payload through that they send us in the quote response.

<img width="691" alt="Screenshot 2023-09-28 at 12 38 55 pm" src="https://github.com/shapeshift/web/assets/97164662/17e1aa24-e683-4e03-8bb3-e00009843e60">

**Comment by twblack88** [comment]
#5138 maybe signatures need to get an overhaul in general?

**Comment by 0xApotheosis** [comment]
Closed by https://github.com/shapeshift/web/pull/5382 🙏
