### ISSUE TITLE
Users unable to select alternative currencies 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#5380]
### Overview

Currently a user gets an error when trying to select any default currency besides USD.  

### References and additional details

When attempting to change default currency to anything other than USD, there is an error in the console log and display.  The user's currency selection is defaulted back to USD. 
<img width="1078" alt="Screenshot 2023-09-29 at 2 19 08 PM" src="https://github.com/shapeshift/web/assets/94998097/a238ae24-8db6-4e76-9bbf-c07bb00b71ae">
Error when attempting to change currency. 
<img width="588" alt="Screenshot 2023-09-29 at 2 18 59 PM" src="https://github.com/shapeshift/web/assets/94998097/6d4558eb-2b33-4437-a601-cd2c7d439f11">
Error is console. 

### Acceptance Criteria

Users are able to select alternative currencies for default display successfully.

**Comment by twblack88** [comment]
Use this new api with no credit card required for free tier https://www.exchangerate-api.com/#pricing
