### ISSUE TITLE
WalletConnect To DApps: "Invalid order signature" when attempting to list an NFT for auction

### ISSUE THREAD

**Issue by 0xMillz** [shapeshift/web#5384]
### Overview

I've been trying to list a Polygon NFT that I hold on my KeepKey for sale on the OpenSea dApp (auction-type) via the Connect to Dapp feature in web. I am able to approve it and sign all the data messages on my KeepKey but when the final response is sent back to the OpenSea dApp, the dApp briefly displays a toast message that says "Invalid order signature" and the browser dev logs for OpenSea throw a graphql error, somethings about `useHandleBlockchainActionsCreateOrderMutation` (see final screenshot):
<img width="831" alt="Screenshot 2023-10-02 at 09 00 23" src="https://github.com/shapeshift/web/assets/37815163/b52781f3-2220-49b6-8dae-33e1990db5cd">
<img width="831" alt="Screenshot 2023-10-02 at 09 02 28" src="https://github.com/shapeshift/web/assets/37815163/9729c4e1-d9e3-40c3-82ab-953640e292bf">
<img width="831" alt="Screenshot 2023-10-02 at 09 02 41" src="https://github.com/shapeshift/web/assets/37815163/1c1f1559-4c3d-4df8-ba17-bb8915e21b07">
<img width="831" alt="Screenshot 2023-10-02 at 09 05 40" src="https://github.com/shapeshift/web/assets/37815163/3eb9a0d3-ef34-408e-8ab9-e9885560c74e">

### References and additional details

I'm guessing it could be a fix like this [one](https://github.com/shapeshift/web/pull/5372/files) but I really haven't dug into the code yet

### Acceptance Criteria

You can sucessfully list for sale a Polygon NFT on the OpenSea dApp

### Estimated effort

4 - 8 hours, optimistically

**Comment by millsmcilroy** [comment]
Self-assigning this issue to myself. I don't have repo privileges so can't do it officially

**Comment by millsmcilroy** [comment]
Closing this issue as "won't do", as it appears to be related to KeepKey only and out of the domain of web. Using @metamask/eth-sig-util's `recoverTypedSignature_v4`, I was able to verify that the recovered address from the signatures produced from wallets like ShapeShift Native for eth_signTypedData_v4 messages are accurate, while for KeepKey they are not. Ref: https://github.com/MetaMask/eth-sig-util/blob/cf4352793a78727df8b0585190b4d39d5c166ba4/src/sign-typed-data.ts#L853C39-L853C39

**Comment by millsmcilroy** [comment]
Reopened because I came up with a solution. A PR to hdwallet is incoming and then a PR to web will follow with an hdwallet version bump

**Comment by millsmcilroy** [comment]
This is the PR in hdwallet that will fix this issue: https://github.com/shapeshift/hdwallet/pull/649
Once web bumps to the version of hdwallet containing the above change, this issue should be resolved!
