### ISSUE TITLE
Scam NFT Transactions Displaying in Transaction History

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#5394]
### Overview

Nice to Have - Filtering out scam NFT receives from the transaction history so if someone's wallet is getting hit hard with scam nfts, they dont have to sift through a bunch of recieced scam nft transactions. Demo wallet has 4 received at the top of the transaction history currently. 
![image](https://github.com/shapeshift/web/assets/94986227/5311a53e-d5b1-47c0-903c-1abdb2dcfcf2)

### References and additional details

https://app.shapeshift.com/#/demo

### Acceptance Criteria

Nice to Have - Filter Out Scam NFT receives in transaction history like we are preventing them from showing on the NFT Page.

**Comment by gomesalexandre** [comment]
@tolltalcrypto this should see large improvements after the recent Tx history improvements that went in develop, could you confirm? 🙏🏽

**Comment by kaladinlight** [comment]
@tolltalcrypto as per @gomesalexandre comment, there were updates to this a few months back that should have made a large improvement. The filtering is based on url strings as the most dangerous scam assets, but it is difficult to catch everything with a regex. Feel free to compile a list of existing scammy assets if we want to improve coverage, but the app should be in a much better state as it stands. Closing at this time.
