### ISSUE TITLE
Trade To Box Native Rune Not Showing Up

### ISSUE THREAD

**Issue by Neverwas-dev** [shapeshift/web#540]
- Brief description (high level)
Not able to search or select native RUNE as the trade to pair
- Steps to recreate (detail)
1. After insuring that the native RUNE asset is toggled on
2. Choose trade and try searching for native RUNE as the traded to asset.
3. Currently work around is to have the from asset be native RUNE and then choose a to asset and swap the from/to to get it selectable.
- Screenshots/vids (add or add attachments “to the right”)
- Link to Discord
https://discord.com/channels/554694662431178782/915680123800416277/915684352829050920
- AC (acceptance criteria)
Fixing the option to search and have native RUNE selectable for the (to) asset in a trade for all wallets on beta.shapeshift.com
![unknown](https://user-images.githubusercontent.com/95000549/144916473-acda77c1-51df-4147-9f8a-40ef08ff266f.png)
![unknown](https://user-images.githubusercontent.com/95000549/144916539-6392f4ad-283e-4360-8a0d-4fe9e6a2f1c5.png)
![unknown](https://user-images.githubusercontent.com/95000549/144916559-5d2c6c75-6bee-4f9f-9ce2-4b26a496110c.png)

**Comment by 0xean** [comment]
closing.
