### ISSUE TITLE
Switching to WC does not kill dApp connections from previous wallet

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5408]
### Overview

When switching from a native/KK wallet that has a dApp connection to Wallet Connect does not end the session. Can still create a sign tx from the previous wallet address in the dApp even after connecting to WC.

### References and additional details

1) Log into develop.shapeshift and connect to native wallet.
2) Navigate to dApp page and select dApp to connect to, ie zapper/uniswap
3) Switch to WalletConnect WALLET and note that the dApp still says connected to original wallet
4) Attempt a transaction in the dApp and note the modal to sign the tx comes up even though its for the previous wallet
5) Attempt to sign tx but note the trsnsaction does not complete
**sessions disconnect when switching to other non-WC wallets. native to kk and vice versa is fine. 
![image](https://github.com/shapeshift/web/assets/100157997/c3c69dd3-6375-4f0b-81e1-5b6d61d43fb8)
![image](https://github.com/shapeshift/web/assets/100157997/7a630e75-aa97-45c9-8418-f8701ae25e4f)

### Acceptance Criteria

Switching between any wallet should kill dApp connections

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
Re-opening, the change made in https://github.com/shapeshift/web/pull/5417 wasn't aggressive enough - @MBMaria can still reproduce this.

**Comment by 0xApotheosis** [comment]
We can fix this with the following in `WalletProvider.tsx`, but it breaks `WalletProvider.test.tsx`.

```ts
if (currentConnectedType === 'walletconnectv2') {
  state.wallet?.disconnect?.()
  clearLocalWallet()
} else {
  void clearAllWalletConnectToDappsSessions()
}
```

**Comment by gomesalexandre** [comment]
Retesting this as the recent wallet pairing refactor may have fixed this
