### ISSUE TITLE
MetaMask support in Firefox requires `unsafe-inline` CSP directive

### ISSUE THREAD

**Issue by mrnerdhair** [shapeshift/web#541]
#443 for reference, but the appropriate resolution is in `hdwallet-metamask` (as shapeshift/hdwallet#416) or `@metamask/detect-provider` (as https://github.com/MetaMask/detect-provider/issues/31)

**Comment by 0xdef1cafe** [comment]
blocked by hdwallet changes required

**Comment by theoboldfrazier** [comment]
@0xdef1cafe Is this still an issue?

**Comment by 0xean** [comment]
closing as stale.
