### ISSUE TITLE
WalletConnect wallet modal not showing on native mobile

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#5412]
When attempting to connect to a WalletConnect wallet from the ShapeShift native mobile dApp, the walletconnect modal does not render.

I.e., when "WalletConnect" is enabled as a Wallet on this screen:

![IMG_5562](https://github.com/shapeshift/web/assets/97164662/48880071-6bb1-4073-a96e-043783371e05)

**Comment by 0xean** [comment]
@0xApotheosis - this is attempting to connect native wallet out to a wallet connect app?

**Comment by 0xApotheosis** [comment]
@0xean the opposite - attempting to connect to a wallet (as a dApp) via WalletConnect.

I updated the description to improve the clarity of this ticket!

**Comment by 0xean** [comment]
thanks ser.
