### ISSUE TITLE
Spike rearchitect app context for deferred load of data per page

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#5451]
### Overview

.

### References and additional details

https://www.notion.so/shapeshift/Mobile-profiling-0321f42373a14e399db7e5255676a97c

### Acceptance Criteria

.

**Comment by twblack88** [comment]
Some screens that are particularly laggy from willy wallet:
- connecting my native wallet, after enterting password the UI gets frozen for 1-2 minutes.
- after unlocking the wallet .
- return to the app, the page is blank for a while, but eventually the UI loads and gets stuck trying to ask for the native 
wallet password while the balances load in the background.
- occasionally the page becomes unresponsive; for some reason it takes longer to load when returning to the app than when connecting the wallet from the dashboard. 
-->wondering where this comes from in context<--
