### ISSUE TITLE
Persistent Pairing Problems with MetaMask

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#5453]
### Overview

1. was connected to SS with MM displaying fine
2. pressed the "lock MM" button in the MM wallet itself (this happens for lots of users with a time  delay anyways)
3. i also disconnected via the modal in the SS app (we can assume this happens as well due to timing)
4. went back tot he SS app with locked MM and clicked connect MM => then the blue pair MM
5. no pop up and no alert infinite loading spinner

### References and additional details

window.ethereum.request({
      method: "wallet_requestPermissions",
      params: [{ eth_accounts: {} }],
    });

can send this and it prompts unlock successfully

### Acceptance Criteria

Handle MeatMask states gracefully and prompt users to unlock/reconnect when MM is in a locked/disconnected state.

**Comment by gomesalexandre** [comment]
gm @purelycrickets I just did some debugging locally, and it looks like the guts of our MM issues is when unlock (i.e `eth_requestAccounts`) is prompted, MM will sometimes not pop-up and instead show a notification number.
That's a MM thing we have no control of - in most cases, it would actually pop the MM window up, but not always, it can sometimes be a bit stubborn.

Now what happens is when you dismiss the unlock screen (or never saw it pop up in the first place as it did in the background) and try to click Pair again, it will look as if we're spinning indefinitely, but what happens is we actually errored behind the scenes.

Can you confirm this is happening while having a pending request (i.e a visible notification number)?

<img width="31" alt="image" src="https://github.com/shapeshift/web/assets/17035424/95a410ce-e195-42f1-9179-25bf1c5bbcc7">

**Comment by gomesalexandre** [comment]
Update on this @purelycrickets - did a full refactor of the local wallet type / MM pairing logic and things are looking much *consistently* better: https://github.com/shapeshift/web/pull/5817 - to be opened soon after more testing and cleanup

https://github.com/shapeshift/web/assets/17035424/2f4fffa1-2cb7-44b3-bfa7-5a4a26779adc
