### ISSUE TITLE
Re-Envision dApp Page

### ISSUE THREAD

**Issue by hpayne1** [shapeshift/web#5456]
### Overview

This ticket addresses the need to enhance the user experience of the dApp page on app.shapeshift.com. The current implementation of this page is suboptimal, causing confusion and usability issues. The proposed solution involves a complete removal of the existing dApp page and a redesign in collaboration with the product team. The revised page should incorporate deeplinks, a top list of protocols and partners, and a card-based layout resembling the missions page to make the experience more coheasive.

### References and additional details

Spec WIP: https://www.notion.so/shapeshift/Wallet-connect-d312b33f25944e8c867f43da69d98d5f

### Acceptance Criteria

1.   Complete removal of the existing dApp page from app.shapeshift.com.
2.    Commencement of the design and specification process for the new dApp page.

### Need By Date

Ideally, the outlined tasks should be completed by 10/16/23, aligning with our WalletConnect launch to mitigate user confusion and optimize the first-time user experience.

### Estimated effort

N/A

**Comment by twblack88** [comment]
this is out of app so we should have removed. closing
