### ISSUE TITLE
Unable to send txs or complete approvals on Arbitrum when connected to KeepKey

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5461]
### Overview

Connected to KeepKey wallet, cannot do a send of Arbitrum or complete an Approval for a trade

### References and additional details

1) Open release.shapeshift and connect to Keepkey wallet
2) Navigate to Assets page and select Arbitrum one
3) Choose an asset to send 
4) Note the tx for the send of the arbitrum can be signed on the KK, but the app gives an error
5) Navigate to trade page and set up a trade for arbitrum token to arbitrum native
6) Note that if an approval is needed for the swapper, you can sign the tx on the kk but then app gives an error 
![image](https://github.com/shapeshift/web/assets/100157997/347440ec-9c75-4248-8d1f-190515fba081)
![image](https://github.com/shapeshift/web/assets/100157997/a731a5c2-088d-485d-9fae-a3dfb7df38fd)
![image](https://github.com/shapeshift/web/assets/100157997/20cfc84a-5bee-4d96-9241-cee09ef8f914)

### Acceptance Criteria

Should be able to send arbitrum and complete approvals while connected to KK wallet

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
we can potentially re-enable now that eip-1559 is disabled for KK holistically, would need testing to confirm

**Comment by gomesalexandre** [comment]
> we can potentially re-enable now that eip-1559 is disabled for KK holistically, would need testing to confirm

Absolutely @0xean - https://github.com/shapeshift/hdwallet/pull/668 and https://github.com/shapeshift/web/pull/6506. Note the testing done on the web PR, everything is happy again for KK!
