### ISSUE TITLE
Implement wasm-based seed conversion for HD-Wallet native

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#5467]
## Description

Mobile devices spend around 3.5s on app boot converting the mnemonic to a BIP32 seed. Looking into the HDWallet source code we see a TODO to reimplement it:
`packages/hdwallet-native/src/crypto/isolation/engines/default/bip39.ts`

![Image](https://github.com/shapeshift/web/assets/125113430/e18e700b-d915-4b03-8364-d237ef87b95d)

## Additional details

 The existing implementation of `pbkdf2_sha512_singleblock` may be replaceable with `pbkdf2` from `hash-wasm`, for example:
```typescript
import { createSHA512, pbkdf2 } from "hash-wasm";

// ...

const out = await BIP32Engine.Seed.create(
      Buffer.from(
        await pbkdf2({
          password: mnemonic,
          salt,
          iterations: 2048,
          hashLength: 64,
          hashFunction: createSHA512(),
          outputType: "binary",
        })
      )
    );
```

## Acceptance criteria

- Native wallet can connect / disconnect / transact as normal
- Improved app boot time

**Comment by 0xApotheosis** [comment]
HDWallet PR: https://github.com/shapeshift/hdwallet/pull/648
