### ISSUE TITLE
Unable to claim fox after foxy withdraw

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5484]
### Overview

When trying to claim fox after a withdraw from foxy yieldy, the claim button broadcasts a tx, and spends gas, but doesnt actually claim the fox. You can 'claim' multiple times. 

### References and additional details

1) Log into app.shapeshift and connect to wallet that has foxy to be claimed
2) Navigate to defi page and select fox yieldy
3) Select claim (if there is amount to claim) *note at first it says pending but after a few second will come up as available
4) Note the tx broadcasts and you get a txid
5) Go back into claim modal and note that it still says there is an amount to claim. 
6) Select claim again and note it does the same flow. 
![image](https://github.com/shapeshift/web/assets/100157997/017fe6da-8bb8-4f05-a85f-acb7dbb5798e)
![image](https://github.com/shapeshift/web/assets/100157997/e6866ff6-6de2-4c14-9f5c-68da05cbfde0)
![image](https://github.com/shapeshift/web/assets/100157997/607d556e-5e7c-4dee-890e-aabd8a0c05a6)
![image](https://github.com/shapeshift/web/assets/100157997/b6f791c3-b752-46fc-92a3-b18b02132f28)
![image](https://github.com/shapeshift/web/assets/100157997/7e5208e0-a2ca-4dcc-8a0d-eade4d40276d)
![image](https://github.com/shapeshift/web/assets/100157997/b67e590b-3ffe-4e6c-86f8-57cd3527d610)
txid: https://etherscan.io/tx/0x71139e8a538a5553082b800277e9f6d75e26eb40f5179906d5559e273424171c
![image](https://github.com/shapeshift/web/assets/100157997/103ae742-aff6-49ea-b8aa-9777dd537815)

### Acceptance Criteria

Should be able to successfully claim fox from foxy yieldy

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
A user is having an issue where the claim button is stuck on pending and wont allow him to select claim. looks like the tx was done 5 days ago so it may not be ready to be claimed but the modal is saying conflicting things 
![image](https://github.com/shapeshift/web/assets/100157997/144a2388-016a-41f8-8e71-b27ba07533e0)

**Comment by MBMaria** [comment]
gm @gomesalexandre i thought we fixed this one last week but the user is still experiencing not being able to claim the fox. 
Wallet address: 0xF00Fa71B3df3226cbc3cA98985ff76B10c82Ebe6
Recent txid: https://etherscan.io/tx/0xbc71413f82f5838dc5a7f2e8d60f046f7d20e2b783210fb8f52f484f7c3c75d7
Let me if there is anything else you need or something I can do to assist

**Comment by gomesalexandre** [comment]
gm @MBMaria is this one still happening or can we close it?

**Comment by MBMaria** [comment]
i think this has been resolved. was about to check but fees are $30 at the moment. ill see if it comes down over the next couple days and if its resolved i can close it 
![image](https://github.com/shapeshift/web/assets/100157997/fda3c51d-8800-4059-8471-652b1647a863)

**Comment by gomesalexandre** [comment]
Retested by @MBMaria and confirmed fixed, closing
