### ISSUE TITLE
useHasAppUpdated regression

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#549]
https://github.com/shapeshift/web/blob/develop/src/hooks/useHasAppUpdated/useHasAppUpdated.ts

we made some changes to the code splitting for the prod build and now the logic in this hook is wrong

update it and maybe write a unit test to cover so the app updatey thing works again

**Comment by reidrankin** [comment]
Investigation shows this is related to the same hashing issue causing #553. Hopefully CRA goes to webpack 5 soon; we may want to consider proactively moving to their @next version to make our lives suck less in general.
