### ISSUE TITLE
Sort asset list by market cap

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#55]
Currently the asset list is just in alphabetical order which isn't useful.

Make some sort of hook that can join asset data with market data to then sort this by marketcap.

Requires https://github.com/shapeshift/lib/issues/106

**Comment by bootsboogie** [comment]
@0xdef1cafe I think this is blocked by the Asset Service? Right now we are getting the assets from the marketService and it is not apart of the marketService data.

**Comment by 0xdef1cafe** [comment]
market service should return market cap yeah - then we can take that and join with asset data to sort by market cap
