### ISSUE TITLE
Remove custom slippage from THORSwap streaming swaps

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#5536]
### Overview

As the THOR protocol will extract an affiliate fee from a trade in the first block of a streaming swap, this fee will be paid by the user regardless of if the trade completes.

Therefore, we should not let the user specify a tight custom slippage, as it creates the opportunity for a mostly unfulfilled swap where the user still pays the full affiliate fee as if it was 100% fulfilled (something that was meant to help might actually harm).

The comment from leena below gives a potential path forward, whereby we could disable slippage/limit protection for streaming swaps and rely on the protocol to protect the user.

We'll need appropriate UI to explain this.

### References and additional details

```
[09:14]leena:
- currently the affiliate fee is taken out of the start of the swap, so it's the full amount, not filled amount cc @Son of Odin

- did the user actually want 60BPS lock-in to a set price for a full 24hours, or did they "think" they wanted it? Eg, they may have thought they were locking in a max of 60BPS slippage protection for the duration of trade; TC auto-stream guarantees 5BPS fees and generally hits close to 5-50 BPS slippage (from arb performance). It's not possible to guarantee the second part.

Often users don't know what they want; for a long streaming swap, a user generally prefers full execution. TC will guarantee 5BPS fee and in practice, the user will get 5-50 BPS slippage (sometimes up to 100). Our recommendation is

1) Always use `0/1/0` for L1 streamers, (fastest auto 5BPS stream, tightest to starting market price, guaranteed full-execution)
2) If the "health" drops to below 90%, use `0/3/0` (volatile)
3) If dealing with large trades (more than 10% of pool depth), increase up to `0/5/0` (up to 30 secs for arbs to restock synths)
```

See https://viewblock.io/thorchain/tx/EC37EB94BCA188FCB72CECFE7E3A7C7EB6407F7AF5DFC2CF692A341FA3A483AE

and https://discord.com/channels/838986635756044328/1166265575941619742

### Acceptance Criteria

- No ability to set slippage on THORSwap streaming swaps
- UI explaining the potential market movement impacts (TODO)
- Stream params in the memo dynamically calculated as per the suggestions above

**Comment by twblack88** [comment]
adjust params for streaming swaps to adjust for loss prevention
remove limit from streaming swaps in general 
add tooltip to highlight mini receive amount (guarantee) is not there. highlighting different ones etc. @reallybeard

**Comment by 0xean** [comment]
@twblack88 followed up with thorchain team to find out if this has been addressed.

**Comment by gomesalexandre** [comment]
@0xean FYI this has been tackled by @kaladinlight in https://github.com/shapeshift/web/pull/5748, though UI changes will be coming up as as follow-up, it is still possible to *set* a default/custom (both wrong) slippage for THORChain streaming swaps currently, but setting them is a no-op, and the amount we display in the custom slippage component also is.

**Comment by 0xean** [comment]
closing in pref of #5764
