### ISSUE TITLE
Slippage value in Savers from Thorchain seems wrong

### ISSUE THREAD

**Issue by HostFat** [shapeshift/web#5555]
It seems that the slippage value on Savers of Thorchain isn't calculated right.
Screenshot from Shapeshift (wrong value), one from Thorswap (right value).

![shape1](https://github.com/shapeshift/web/assets/644416/536117a5-ad5f-4eb8-80b5-bc4c1bdab282)
![ts](https://github.com/shapeshift/web/assets/644416/9f31e41d-09ad-4fcf-8095-fafc387b9316)

**Comment by gomesalexandre** [comment]
Thanks for reporting this @HostFat ! It looks like THOR deprecated a few types and we're still using them instead of their new variant. Fixed in https://github.com/shapeshift/web/pull/5556 :)
