### ISSUE TITLE
Add Feature Flag to Fox Missions 

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#5570]
### Overview

As title suggests, adding a feature flag to fox missions so we can hide it when there arent any active missions going on.

### References and additional details

Don't see a feature flag option for Fox MIssions to be able to turn off in the flagged feature area. 

### Acceptance Criteria

Being able to turn off fox missions when there arent any.

**Comment by 0xean** [comment]
closing, missions are being removed.
