### ISSUE TITLE
Unable to deposit into ETH ThorChain Saver Vault

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5576]
### Overview

Unable to deposit into ETH thorchain saver vault. gives "Transaction Failed" error.

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to DeFi page and find ETH thorchain saver vault
3) Select deposit and an amount and confimr
4) Note when selecting Sign & Broadcast that it gives the error "Transaction Failed" 
![image](https://github.com/shapeshift/web/assets/100157997/8b5773b8-92a1-4eb8-8335-3261fa91f7cc)
![image](https://github.com/shapeshift/web/assets/100157997/a39412b9-1b9d-4b38-8ee7-ab6b09236df8)

### Acceptance Criteria

Should be able to deposit into ETH thorchain saver vault

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by woodenfurniture** [comment]
Noting error message from api:
![image](https://github.com/shapeshift/web/assets/125113430/458627b7-a8f2-47aa-9a2d-baba265f7d84)
