### ISSUE TITLE
Trade Transaction history UI enhancements

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#559]
@DiggyDiggy2 @SS-FOX-McCloud @reallybeard to coordinate with @0xApotheosis for UI on what tx's we're able to/soon able to parse correctly

* currently, we support trade transactions (erc20 swaps) but the UI is a little bare and minimal. this is simply implementing improved UI from products QA meetings

**Comment by 0xean** [comment]
depends on #560 - @0xdef1cafe to add details here.

**Comment by 0xApotheosis** [comment]
- Pre-factor work for this has been started: https://github.com/shapeshift/web/pull/811
- Related to this issue is: https://github.com/shapeshift/web/issues/786

@kaladinlight and @0xApotheosis to work through next steps for `unchained` to support the desired product functionality.

**Comment by 0xean** [comment]
removing needs bounty until we are ready

**Comment by DiggyDiggy2** [comment]
there is a new design for TX history. i think that makes this an outdated issue.

**Comment by 0xdef1cafe** [comment]
i'm more than happy to close this in favor of https://github.com/shapeshift/web/issues/1006

**Comment by 0xean** [comment]
closing for #1006
