### ISSUE TITLE
Getting Insufficient Matic error when trading Matic to Eth on Eth 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5597]
### Overview

When trying to trade a token on Matic to Eth on Eth, it says there is insufficient matic to cover fees even if the wallet has enough to cover fees. 

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to trade page and enter a trade with input asset being a polygon token
3) Enter the output asset as Eth on Eth
4) Note the error "insufficient MATIC on Polygon for fees" appears
**note it does not happen if the output asset is eth on op or eth on arbitrum
![image](https://github.com/shapeshift/web/assets/100157997/d53abc17-3b03-488a-a529-70370df1c2df)
![image](https://github.com/shapeshift/web/assets/100157997/5c38a4e4-2c6a-4319-8045-f514a458a2c6)

### Acceptance Criteria

Should be able to trade token on polygon to eth on eth 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
will have to wait until polygon is synced but will test once its good again @0xean

**Comment by MBMaria** [comment]
Not getting the insufficient funds error anymore, just "unsupported trade pair" which is probably likely
![image](https://github.com/shapeshift/web/assets/100157997/4a6da13f-84c6-4c40-ae34-a9759e6af6a7)

**Comment by 0xean** [comment]
lifi timeouts might be the cause of unsupported trade pair.
