### ISSUE TITLE
btc address changed

### ISSUE THREAD

**Issue by bitdaric** [shapeshift/web#5606]
### Overview

you change btc address on swap. I know it is good for security but it is not compatible with thorchain keystore wallets like asgardex. so when I use my asgardex keystore in your site, balance become zero in asgardex. it would be great if you add an option to not change addresses on swaps.

### References and additional details

-

### Acceptance Criteria

btc address changed

**Comment by twblack88** [comment]
Thanks for bringing to our attention, feel free to add this to our canny board! https://shapeshift.canny.io/
