### ISSUE TITLE
Lifi routes dondé

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#5642]
### Overview

It seems like we might have an issue with lifi routing or requests. Jumper shows a route for hop and it seems like we don't. Look into swapper and lifi. 

### References and additional details

![Screen Shot 2023-11-20 at 10 24 23 AM](https://github.com/shapeshift/web/assets/8991325/e4068c3d-eea7-4c12-afe5-9ff12f7ff222)
![Screen Shot 2023-11-19 at 1 42 00 PM](https://github.com/shapeshift/web/assets/8991325/16d865ce-b630-4fe6-8c97-51255a699828)

### Acceptance Criteria

We can send USDC from gnosis to 
- arb
- optimism

### Estimated effort

¯\_(ツ)_/¯

**Comment by woodenfurniture** [comment]
Those routes are multi-hop routes, which are currently not yet supported. We'll have support for this rolling out in a few weeks 🍻

![image](https://github.com/shapeshift/web/assets/125113430/764cff63-9d51-4f7d-a916-3ad091a9c65b)
