### ISSUE TITLE
Display completed mulit-hop trade metadata

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#5668]
### Overview

When a trade is completed, a summary needs to be rendered containing all of the metadata that was generated during execution. 

Currently all metadata associated with a multi-hop trade shares the same lifetime as the components that generate it. To achieve this, the metadata should be stored in redux to allow the application to access it after the trade execution UI components unmount.

### References and additional details

Note the current completion summary is missing TX IDs - these are inaccessible after the previous page unmounts, so they will need to be stored.
![image](https://github.com/shapeshift/web/assets/125113430/615c15a1-30d8-4615-9b8c-db979f2021e5)

### Acceptance Criteria

- TX IDs and explorer links appear for **approvals** in the trade completion summary
- TX IDs and explorer links appear for **swaps** in the trade completion summary

**Comment by 0xean** [comment]
completed in #5676
