### ISSUE TITLE
Lending infinite loading state when trading is halted

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#5681]
### Overview

The lending UI enters an infinite loading state when a load quote from thorchain fails due to halted trading.

### References and additional details

The following error is returned from thorchain:

https://dev-daemon.thorchain.shapeshift.com/lcd/thorchain/quote/loan/open?from_asset=ETH.ETH&amount=200000000&to_asset=AVAX.AVAX&destination=0x34B5D5153Fc1a2107A311CE6412fb69a30D78e15

```json
{
    "error": "failed to simulate swap: trading is halted, can't process swap"
}
```

### Acceptance Criteria

Failed quotes due to halted trading are handled in the UI so the user knows to try again later or borrow a different asset

### Screenshots/Mockups

Loading state while trading is halted:
![image](https://github.com/shapeshift/web/assets/125113430/ffa4f67a-1538-46da-9ffe-291c4ab1c1a5)

Note swappers do handle it correctly:
![image](https://github.com/shapeshift/web/assets/125113430/0364c5c5-0f47-4881-95e5-4149c077b115)

**Comment by gomesalexandre** [comment]
Tackled in https://github.com/shapeshift/web/pull/5680 - see https://github.com/shapeshift/web/pull/5680/commits/3c0a49f192bbcb5981f7b024960e5b3873436678
