### ISSUE TITLE
Unable to deposit into Doge on Ledger

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5687]
### Overview

When trying to deposit in Doge on Ledger, it gets to the "Consolidate'' step and gets stuck on Loading

### References and additional details

1) Log into app.shapeshift and connect to Ledger wallet
2) Navigate to Earn page and select Doge saver vault
3) Select Deposit and an amount an Continue
4) On the next screen select "Consolidate" and note it just spins on loading
![image](https://github.com/shapeshift/web/assets/100157997/bbf6f209-a281-4fb8-927d-6492e368e109)
![image](https://github.com/shapeshift/web/assets/100157997/da5ac7c4-ce8f-4a9f-b29a-d5f71b85149d)
Exiting out of the screen i saw this error in console:
![image](https://github.com/shapeshift/web/assets/100157997/50c14d5a-6f84-4ed7-872f-de66ac021a06)

### Acceptance Criteria

Should be able to deposit into Doge vault

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Related to the current DOGGO issues in https://github.com/dogecoin/dogecoin/issues/3385 - will retest and close once fixed upstream

**Comment by gomesalexandre** [comment]
@MBMaria  Closing as we have implemented hardcoded fees for DOGE in https://github.com/shapeshift/web/pull/5853, effectively fixing this:

<img width="570" alt="image" src="https://github.com/shapeshift/web/assets/17035424/49ed1b67-9eb5-4086-a3a7-1e5c301f4947">
<img width="543" alt="image" src="https://github.com/shapeshift/web/assets/17035424/c2400295-a289-4833-9a58-48a5eaef1373">
<img width="591" alt="image" src="https://github.com/shapeshift/web/assets/17035424/499d7686-b6d3-4c52-8d17-e7b060c25a5f">
<img width="538" alt="image" src="https://github.com/shapeshift/web/assets/17035424/86752041-69e2-4df8-98ce-e213c5c18f14">
<img width="417" alt="image" src="https://github.com/shapeshift/web/assets/17035424/29f8e1a1-4479-448c-889e-96c31a6bcf78">
