### ISSUE TITLE
Unable to deposit into BTC vault

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5688]
### Overview

Cannot currently deposit into BTC vault, comes up with error "Transaction Failed"

### References and additional details

1) log into app.shapeshift and connect to wallet of choice
2) navigate to earn page and select BTC vault
3) Enter amount to deposit and follow steps to Sign and Broadcast
4) Note that comes up with error "Transaction Failed" immediately
![image](https://github.com/shapeshift/web/assets/100157997/e5c4b524-3930-402d-998b-eb180721200c)
![image](https://github.com/shapeshift/web/assets/100157997/5820f3c4-c913-4978-978c-16e5cf1fee57)

### Acceptance Criteria

Should be able to deposit into BTC vault 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Tested with the seed this error was encountered with and was able to deposit without any error (though with some shenanigans, see below)
<img width="520" alt="image" src="https://github.com/shapeshift/web/assets/17035424/66ab2dcb-012e-4a51-84a9-984d5ecf0df6">

Note one shenanigan, which may or may not be tangential here: when reconciliating from a xpub (legacy) account, funds were sent to a zpub (SegWit native) account, which means that within the deposit flow, it would then be impossible to continue with the deposit after reconciliating - unless you go to the SegWit native account and continue there, which I did.
