### ISSUE TITLE
Withdraw from AVAX Vault shows $0.00 on the txid regardless of amount selected to withdraw

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5689]
### Overview

When withdrawing from the AVAX vault, the txid shows withdraw as $0.00 even if you select a higher amount. 
I have had 2x users report this and was able to recreate. 1 user said eventually the balance showed in his wallet after a number of hours. 

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to Earn page and select AVAX vault
3) Follow steps to withdraw an amount 
4) Note the withdraw amount listed in shapeshift is different to the amount on the txid 
![image](https://github.com/shapeshift/web/assets/100157997/50ad7162-d756-4d29-b390-25f8acf9ef40)
![image](https://github.com/shapeshift/web/assets/100157997/c68dd0c2-6166-405b-842e-c885c7bf7606)
![image](https://github.com/shapeshift/web/assets/100157997/9c52fd01-3e71-441a-957b-ac8d8200806f)
![image](https://github.com/shapeshift/web/assets/100157997/27254ad1-c622-4f40-a379-841cc1a1b140)
https://snowtrace.io/tx/0xeee5c06caaa0c362481761a79588f8c881a1cd5f3209558651344fa4fc17a18e

### Acceptance Criteria

Withdraw amount shown in shapeshift and the txid should be the same

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria this is correct behavior - here's the Viewblock Tx matching https://snowtrace.io/tx/0xeee5c06caaa0c362481761a79588f8c881a1cd5f3209558651344fa4fc17a18e: https://viewblock.io/thorchain/tx/eee5c06caaa0c362481761a79588f8c881a1cd5f3209558651344fa4fc17a18e

The 0.00005 value of the Tx is the *dust* amount, however, 0.15249865
AVAX.AVAX were withdrawn, here's the internal Tx https://snowtrace.io/tx/0x656c50fc25b1eda8ce64c186c928fb9c6a9b876b2a92bb8e11f0696c95c1855e

**Comment by 0xean** [comment]
closing as expected per @gomesalexandre
