### ISSUE TITLE
FOXy Token Holders widget not loading on Arkeo Page 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5706]
### Overview

On the Arkeo page, the FOXy Token Holder widget does not load.

### References and additional details

1) Log into app.shapeshift on an incognito browser and connect to wallet of choice
2) Navigate to Arkeo page and note the FOXy Token Holder widget just loads indefinitely.
![image](https://github.com/shapeshift/web/assets/100157997/886206d6-094a-4ee4-9939-2c6aa08e1abe)

### Acceptance Criteria

Foxy widget should load like the others.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by twblack88** [comment]
This page needs a clean up in general. We should probably also make it more static until the actual airdrop page is up on Arkeo's end.
