### ISSUE TITLE
Clean up navbar

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#5712]
### Overview

We have a couple icons that need removing to make space for new features coming down the pipe. 
- #5706 clean up arkeo thing, then linkout to arkeo airdrop page when it's built
- Remove yat callout, stays in the send modal
- remove dapp store, connect wallet is all people need for native walletconnect. can revisit dapp connections in q2 2024 when the ecosystem is more robust and WC ships more of their roadmap. 

### References and additional details

`sidenavcontent` 

### Acceptance Criteria

- Icons go away
- functionality doesn't break
- things are cleaner

**Comment by 0xean** [comment]
move arkeo link to above settings smaller
