### ISSUE TITLE
Swapper attempts to swap more than in wallet and fees beyond the input amount

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#5723]
### Overview

Attempting to swap from BNB to ETH on the app with Frame injected as MetaMask

### References and additional details

In the recording you can see me attempting to trade 1.4 BNB, the transaction that is created is for ~1.9 BNB ... way more than my total balance.. 

https://github.com/shapeshift/web/assets/15096737/8898a470-9d8e-47e2-9d32-d355a4988251

This is also hidden if you dont click into the Expected amount tab, but is damn confusing when the Send shows 1.4 BNB 

![Screenshot 2023-11-29 at 1 09 34 PM](https://github.com/shapeshift/web/assets/15096737/12ab1a17-dff1-4dae-861f-a9b5a402c275)

### Acceptance Criteria

- We should never suggest a transaction that is beyond what a user has in their wallet
- we should also fix the UX here so a user isn't blindsided that they think they are sending 1.4 BNB but are ask to sign a tx sending ~2.0 BNB

**Comment by 0xean** [comment]
Issues:
1. Advancing in the trade flow beyond what a user has in their wallet
2. Constructing a tx beyond what a user has in their wallet and beyond what the UI has showed
3. Sorting incorrectly because the input amount is much larger than expected so the output isn't comparable with other providers
4. Displaying in main UI that input is going to be higher for LiFI (or reduce the amount we tell lifi we are sending by their fees, or get them to fix this!)

**Comment by 0xean** [comment]
Next steps:


1. reach out to lifi
2. enforce #1 and #2 above
3. create sanity check that we never suggest a transaction that is larger than what a user input

**Comment by woodenfurniture** [comment]
disabling the following bridges should avoid the issue in the short term
`['stargate', 'amarok', 'arbitrum']`

I'm going to action that and follow up with the other checks

**Comment by 0xean** [comment]
@woodenfurniture - should we close this ticket at this point?
