### ISSUE TITLE
Move swappers into a package that excludes Redux

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#5739]
### Overview

The crux of this ticket is effectively moving the `lib/swapper` directory into it's own package that does not have access to Redux.

This directory should already be decoupled, the intent of doing this is to ensure that developers do not accidentally re-introduce dependencies on Redux in the future.

### References and additional details

This should mainly be a plumbing task, as most of the work to remove dependencies should already be complete.

If there are remaining, uncaught dependencies we'll want to pass the needed data into each function as args instead.

### Acceptance Criteria

A new package exists inside the `web` monorepo, the consumption of which replaces all usages of functions inside `lib/swapper`.

**Comment by twblack88** [comment]
This is leftover from the API abstraction. But we old yeller-ed the API.
