### ISSUE TITLE
ETH saver vault withdraw not working properly

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5743]
### Overview

When doing a withdraw from ETH saver vault, it withdraws a smaller amount than requested. I tried to withdraw $3 but it can back with 0.06c 

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) navigate to earn page and select eth vault
3) select withdraw and enter amount to withdraw
4) Note its says something went wrong and the amount that you get back is less than the amount you put in to claim
![image](https://github.com/shapeshift/web/assets/100157997/254ba2fd-da3c-4ffe-a656-b9fbd9e4a4b5)
![image](https://github.com/shapeshift/web/assets/100157997/c6587923-ec72-4651-9e50-f98f09939678)
![image](https://github.com/shapeshift/web/assets/100157997/d3ec0437-89d4-4146-937c-65e82035e173)
![image](https://github.com/shapeshift/web/assets/100157997/236e9883-c252-44e9-81f5-0d5df87f18f9)
https://etherscan.io/tx/0xf030967f1088494d2832ac66757dd5a5a2c2d265db4280fe6a4599eb343d5a24

### Acceptance Criteria

Should withdraw expected amount 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria this is fixed in https://github.com/shapeshift/web/pull/5735 - tl;dr is protocol fees were wrong, making it seem like none were occurred

**Comment by MBMaria** [comment]
Sweet, so will go in the next release then or something I'm guessing @gomesalexandre ?
