### ISSUE TITLE
Unable to send Doge

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5822]
### Overview

Unable to send doge - getting "insufficient funds error"

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to doge asset page and select send
3) Enter doge wallet address and amount
4) Note the error insufficient funds appears. 
![image](https://github.com/shapeshift/web/assets/100157997/3cf9304e-9a42-4b2a-87cc-c6a5f5b2a89a)

### Acceptance Criteria

Should be able to send doge

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Related to currently borked fees estimation upstream - @kaladinlight given this is still unresolved upstream, do we want to bail on `canCoverFees` for DOGE for the time being?
https://github.com/shapeshift/web/blob/880175dac9f7aa090143f7d16d1288de9702420c/src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx#L142-L151

**Comment by 0xApotheosis** [comment]
Heh, read my mind @gomesalexandre!

Came here to say we are throwing at https://github.com/shapeshift/web/blob/develop/src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx#L148 as the estimate fees response is:

```json
{
    "fast": {
        "txFee": "undefined",
        "chainSpecific": {
            "satoshiPerByte": "-97656"
        }
    },
    "average": {
        "txFee": "undefined",
        "chainSpecific": {
            "satoshiPerByte": "-97656"
        }
    },
    "slow": {
        "txFee": "undefined",
        "chainSpecific": {
            "satoshiPerByte": "-97656"
        }
    }
}
```

**Comment by 0xean** [comment]
https://api.dogecoin.shapeshift.com/api/v1/fees

**Comment by 0xean** [comment]
Per @gomes - this looks to be upstream of us 

https://github.com/dogecoin/dogecoin/issues/3385

perhaps there is a way to deal with this in the meantime.

**Comment by mwbro1** [comment]
I have the same issue unable to send Doge
![doge](https://github.com/shapeshift/web/assets/153525064/20fbcb6b-bc95-4c66-b116-aeb468cc70f8)

**Comment by BitHighlander** [comment]
imho there should just be a fallback, or even just hardcode fee's on doge. Dogecoin fee's used to just be hardcode to 1 for many many years. 1 doge = 1tx. the only time this was questioned in the doge community was when there was a pump to nearly a dollar. The fee market is not competitive on doge, low fee tx's will get confirmed timely. I see little downside in just hard coding fees to 1 until they merge their smart fee's into dogecoin core and it proves to be effective.

**Comment by 0xean** [comment]
add hardcoded fee to chain adapters for the time being, once fixed upstream we can remove and add some sanity checks to unchained to guard against future failures.

**Comment by mwbro1** [comment]
Thank you!!!
