### ISSUE TITLE
Custom recipient / custom to address on swaps

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#5883]
### Overview

Currently we offer the ability to enter a custom address when a user has a wallet connected that doesn't support a specific chain (EVM wallet connected but attempting to swap to BTC, for example). 

We should extend this functionality to always allow for a custom recipient in the swapper.  This isn't always supported by all routes, so we may need to add a bit of help text about this if a user attempts to enter a custom recipient. 

### References and additional details

Some risk here of a user entering an incorrect address. We can validate the format, but not much else 

### Acceptance Criteria

- ability to input custom recipient to swapper
- tooltip / info text alerting the user that not all routes support this functionality 
- validate the address is correctly formatted / valid addy for the specific output chain
- on confirm screen we should link out the custom recipient address to a block explorer so people can easily confirm its validity 
- add flag on event for mixpanel so that we can track the usage of this feature

**Comment by twblack88** [comment]
Spec is a lil out of date https://www.notion.so/shapeshift/Input-custom-recipient-address-on-Trades-b1ccaf4df489421e8e60c63b1f80dce0?pvs=4 need to 
- finish technical due diligence for wallet types (since snap launched)
- spike through tracking and how we'd like to see it
- articulate success/failure metrics.

**Comment by 0xean** [comment]
@twblack88 - did the spec for this get finished off? might be able to slot it in if its ready from a product perspective.

**Comment by twblack88** [comment]
I think it just needs a spike on the technical bit. the product experience is pretty dialed. Hop does this pretty well and a few others we can look to. Will bring up on roadmap.

**Comment by 0xean** [comment]
@reallybeard to design component for a custom address dropdown on the primary swapper input screen.

**Comment by reallybeard** [comment]
![Screenshot 2024-01-16 at 3 28 15 PM](https://github.com/shapeshift/web/assets/89934888/f6938b57-424d-4ad9-8e24-e658985cdd9c)

Flow
1. Recipient address shows the address we get from the wallet.
2. The user can click the edit icon, if the user hovers over the edit button they will see a tooltip with the text "Enter a custom recipient address for this trade"
3. The custom recipient text input box appears.
4. The user pastes their custom address, if the address is invalid we show an error message below the text field in yellow.200
5. Once the user has entered a valid address, they can click either the check mark button to save or the x mark button to cancel.
6. After the user has saved their custom address, the row changes from text to a tag with an x mark button on it. And also note that the label of the row has now changed from Recipient Address, to Custom Recipient Address
7. If the user hovers over the tag they will see a tooltip that says, "This is your custom recipient address"
8. If the user decides they want to remove the custom recipient address, they click the tag and the field then resets back to the original state with the wallet address.

**Comment by 0xean** [comment]
thanks @reallybeard!
