### ISSUE TITLE
Extremely long load time for wallets first session

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#5901]
### Overview

Currently in production, it can take >1 minute and sometimes >5 minutes for a newly paired wallet to load it's initial balances. This is happening to all wallets in first pair sessions and is an extremely unideal user experience. 

### References and additional details

See Discord Thread: https://discord.com/channels/554694662431178782/886041582422356018/1186784348775665684

### Acceptance Criteria

First time connections to wallets have a more acceptable load time before balances are shown, or a message to users about the expected load time for a newly connected wallet to alleviate support requests and have a better user experience

**Comment by 0xean** [comment]
This is currently reproducible for me by loading up the demo wallet in a chrome incognito browser and navigating to the wallet section.

**Comment by 0xean** [comment]
seems intermittent as I am unable to reproduce the same latency at the moment.

**Comment by woodenfurniture** [comment]
Load time appears virtually instant on demo wallet via incognito. Have pinged the discord thread for confirmation whether this issue still exists

**Comment by 0xean** [comment]
will reopen when latency issues arise again as currently not able to repro
