### ISSUE TITLE
Users Unable to withdraw from BNB savers position 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#5903]
### Overview

We currently provide an error for not enough gas for withdrawal on BNB savers vault positions with addresses that should have enough gas to perform the transaction.  Unsure of root cause of issue but bug is currently in Prod and blocking users from interacting with their positions. 

### References and additional details

Discord Thread: https://discord.com/channels/554694662431178782/1184599011349516418/1186804362174005318

Savers EVM issues were initially addressed in #5882 but withdraw issue still exists. 

Issue looks to be affecting thorswap as well but BSC is not down on: https://track.ninerealms.com/ 

![Screenshot 2023-12-19 at 3 56 37 PM](https://github.com/shapeshift/web/assets/94998097/552957f0-2579-4082-9234-e976eba82659)

funding address: https://bscscan.com/address/0x9a56D3d1A6631376cC0c5DC45A1453eA0287a938

(DM Tyler for seed to position) 

### Acceptance Criteria

Users are able to withdraw BNB assets in savers positions, or an appropriate error message is displayed to the user as to why they are unable to withdraw their position.

**Comment by gomesalexandre** [comment]
@purelycrickets this may have been a transient node issue, can we still repro this? Just tried to repro and this is now happy

<img width="555" alt="image" src="https://github.com/shapeshift/web/assets/17035424/b17c2360-404b-4844-ab15-e325a2d0950d">

**Comment by 0xean** [comment]
@purelycrickets to test again to confirm still exists

**Comment by 0xean** [comment]
closing as working
