### ISSUE TITLE
Coinselect UTXO for OFAC address checks

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#5919]
### Overview

Implement the coinselect algorithm in our React app to identify input and output addresses in UTXO chain transactions. This integration will involve modifying the transaction creation process to utilize coinselect for selecting UTXOs, followed by screening the determined addresses against OFAC sanctions lists. The task includes understanding the UTXO model, ensuring accurate address identification, and updating the sanctions screening logic to handle these addresses both before and after selection. Focus on maintaining transaction efficiency while ensuring compliance with OFAC regulations.

### References and additional details

See `packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts` for current chain adapter implementation.

See `packages/chain-adapters/src/utxo/utxoSelect/index.ts` for coin select implementation.

Also see:
https://github.com/shapeshift/web/pull/5454/files#r1358008627
https://github.com/shapeshift/web/pull/5842#discussion_r1425851202

### Acceptance Criteria

1. **Accurate Address Identification:** The system must correctly identify and extract all input and output addresses from UTXO chain transactions using the coinselect algorithm.
2. **Compliance with OFAC Sanctions:** All identified addresses must be thoroughly screened against OFAC sanctions lists, ensuring full compliance with no false negatives.
3. **Transaction Efficiency and Integrity:** The integration of coinselect should not adversely affect the transaction's efficiency or integrity, maintaining optimal transaction size and fee calculations.

**Comment by gomesalexandre** [comment]
Fixed in https://github.com/shapeshift/web/pull/6510
