### ISSUE TITLE
Link to Support/Chatwoot not shown on private.shapeshift

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5935]
### Overview

When connected to private.shapeshift, you do not see the option for support to get to chatwoot, only a link for discord and feature request

### References and additional details

1) Log into private.shapeshift.com and connect to wallet of choice
2) Navigate to the Feedback and Support menu and not that there is no option for "Get Support" 
![image](https://github.com/shapeshift/web/assets/100157997/02c3d11d-dd78-4d8b-9769-8e27d47480c7)

### Acceptance Criteria

Should be able to access support on private.shapeshift.com

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
This might be as expected considering the desire for private to have as little integrations or possibility for exfiltrating user data to a third party. Will see if maybe @twblack88 or @purelycrickets have any historical context on this.

**Comment by twblack88** [comment]
I would assume private should stay as light as possible.

**Comment by 0xean** [comment]
closing as we intend not to add extra features to private to keep it as private as possible
