### ISSUE TITLE
Bitcoin account view missing segwit info

### ISSUE THREAD

**Issue by NukeManDan** [shapeshift/web#5948]
### Overview

Using the https://github.com/keepkey/keepkey-desktop to access accounts, I see in some screens 3 accounts by default for a new seed/wallet. I would think all places should have a note as to the type, if needed, perhaps for the case of a new user default to the most modern/best account/address type and hide the rest? 

Here are examples with corresponding URLs

![1](https://github.com/shapeshift/web/assets/35669742/3ab890c0-4712-435c-99f9-0509bba1207d)
:point_up: looks fine, although unclear to a noob why 3 are here...
![2](https://github.com/shapeshift/web/assets/35669742/a8611cc1-54e4-450a-b1b0-77373afeb530)
:point_up: ...um no idea why there are 3... :sweat_smile: 
![3](https://github.com/shapeshift/web/assets/35669742/6e14bfa3-1379-4fda-9cb5-aa3a289cb6bb)
:point_up: looks fine... but not easy to spot the type!

### References and additional details

N/A

### Acceptance Criteria

IMHO: Some means to identify at a glance the account type for any asset with "sub-accounts" like segwit flavors in bitcoin, IFF there is a need to expose that to the end user, if not, then hide that information & default to some best practice account type.

**Comment by gomesalexandre** [comment]
Thanks for opening this @NukeManDan! I've just opened https://github.com/shapeshift/web/pull/6053 which will now reflect the UTXO account type in the balance rows 🙏🏽
