### ISSUE TITLE
Wire up data for Thorchain LP detailed pool view created 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#5968]
### Overview

#5959 created the UI components for the detailed pool view this ticket is to connect the data for that view 

### References and additional details

see #5940 for docs and info on where to get some of the data / math

### Acceptance Criteria

all data (and math) is available for all thorchain lp pools available in the view created in #5959

**Comment by gomesalexandre** [comment]
closed by https://github.com/shapeshift/web/pull/6009
