### ISSUE TITLE
Mobile app takes a long time to load

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5975]
### Overview

When opening the mobile app, noticing unusually long time for the app to load - very sluggish

### References and additional details

1) Log into mobile app
2) Note that it takes a long time to load
3) Sometimes wants you to re enter the pin to reload app
*wallet address: 0x3D504949Ca5ff1143cacA57d75EAd1179Ba1Dd3A

https://github.com/shapeshift/web/assets/100157997/d966c945-a8ec-40a4-96b4-5cfa2e3e76bd

 

### Acceptance Criteria

App should load relatively quick. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
@MBMaria Can you also share the address associated with this long load so Engineering can recreate?

**Comment by woodenfurniture** [comment]
I've noticed when there is a single slow request in one of the swapper supported asset requests, the whole ui has to wait for it to resolve before the loading state ends. We should be able to load all swapper supported async and add them to an active pool of swappers so users are able to interact with the UI while its loading.

We can probably put loading swappers at the bottom of the quote list with a spinner and loading text so its clear to users why a swapper isnt returning quotes.

**Comment by woodenfurniture** [comment]
Additionally, I've noted that the asset dropdowns have to wait for market data to arrive before any will appear in the dropdown. By sorting based on user balance, then name (instead of market cap) we can display the asset list sooner.

**Comment by 0xean** [comment]
closing in preference of the more holistic spike in #6252
