### ISSUE TITLE
Transactions in app.shapeshift takes a long time to load when first opening the platform 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5976]
### Overview

On an initial load in app.shapeshift, the transactions take ages to load. 

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Note that the transactions take ages to load
*wallet address: 0x3D504949Ca5ff1143cacA57d75EAd1179Ba1Dd3A

https://github.com/shapeshift/web/assets/100157997/c63ceef4-463f-40cf-a519-29a45383756b

### Acceptance Criteria

Shouldn't be waiting a long time for the platform to load

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by woodenfurniture** [comment]
Write up here
https://www.notion.so/shapeshift/Transaction-History-d656eb2ea4e244699fecb4c68eebfa45
