### ISSUE TITLE
Proper error message for thorchain halts 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#5979]
### Overview

Currently when a chain is halted on thorchain, there is not a clear message letting users know this is the reason they are unable to perform the action they were wishing to. 

### References and additional details

We currently display 'not enough gas' error for halted chains: 

![Screenshot 2024-01-10 at 5 03 05 PM](https://github.com/shapeshift/web/assets/94998097/695d9c3a-1ca7-4d49-8fed-c250f5d4cb4d)

ETH is currently halted: https://track.ninerealms.com/

### Acceptance Criteria

Proper error messaging for halted thorchain chains when a user goes to make an action on a halted chain.

**Comment by 0xApotheosis** [comment]
I'm not very clear on this ticket. The screenshot shows a 0x quote, for which there is no such thing as a halted chain.
I can't see how much ETH the account used in the screenshot has, but is it possible it didn't have enough gas?

As far as I can tell we correctly show the correct message when a chain is halted for THORChain:

<img width="485" alt="Screenshot 2024-01-11 at 11 10 08 am" src="https://github.com/shapeshift/web/assets/97164662/4acd6c42-3a91-4eb2-9ff2-5b898c0005ce">

**Comment by MBMaria** [comment]
I feel this is an example where we could have error messaging that states the trade are halted because this should generally have an available rate. 
![image](https://github.com/shapeshift/web/assets/100157997/77ff2934-47f0-4f40-b809-c515be723549)

**Comment by purelycrickets** [comment]
I jumped the gun from an internal report, looks like the error is displaying correctly, it is just not sorted to the top but will be in a future fix. 

![Screenshot 2024-01-10 at 5 11 44 PM](https://github.com/shapeshift/web/assets/94998097/372dfe19-8a5d-42ff-b276-d4c30611bb0e)

Sorry for the false ticket, got excited.
