### ISSUE TITLE
(ALPHA) V2: Saved Native Wallet Age Displaying incorrectly

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#599]
https://discord.com/channels/554694662431178782/873244924026449940/922562336911392778

In Web v2, when you go to the saved wallets, if you have a saved native wallet address, it will show up being very old. 52 years in this case. 

I was able to remove and re-add the native wallet and it's showing up correctly for now. I am keeping an eye on this to see if it speeds up in time vs how long it's actually been added.

**Comment by jdambron** [comment]
I confirm I was able to see this behavior with old saved wallets but not with new ones.
I checked, and the PR that introduced the created date is https://github.com/shapeshift/web/pull/499.
I agree with @reidrankin that every wallet that already existed before the merge of this PR indicates ~52 years old. It should not appear with wallets created after that.

**Comment by 0xdef1cafe** [comment]
this only affects people prior to the fix, won't fix this
