### ISSUE TITLE
Atom to Rune trade failing

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5995]
### Overview

when attempting to trade atom to rune it is coming up with an error in broadcasting

### References and additional details

1) log into app.shapeshift and connect to wallet if choice
2) Enter an atom to rune trade
3) Broadcast tx and note that the trade does not go through 

https://github.com/shapeshift/web/assets/100157997/34da68b9-9865-448f-a3de-45bbc488c6ca

### Acceptance Criteria

Should be able to trade atom to rune

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
@MBMaria just confirming this is happening on prod, too? The video recording is on `wood`.

**Comment by MBMaria** [comment]
> @MBMaria just confirming this is happening on prod, too? The video recording is on `wood`.

yep, happening on prod as well.

**Comment by woodenfurniture** [comment]
@kaladinlight looks like the tx broadcast is failing in unchained. When trading atom -> rune on native wallet:

Request
```json
{"rawTx":"CpkBCk8KDi90eXBlcy5Nc2dTZW5kEj0KFLUYNCDBYTR6tjwjIT0IQk0v4EIrEhRb4LptXs9BLiTXyIABeCtXyrVcURoPCgV1YXRvbRIGNDg0MDI3EkY9OlRIT1IuUlVORTp0aG9yMTd5amV4NjJueXl6anA4ajV4OTdqNjN6MzB3bjN1c3Vrd3l2czlzOjEwMTc2Mzg4MjpzczowEmgKUApGCh8vY29zbW9zLmNyeXB0by5zZWNwMjU2azEuUHViS2V5EiMKIQNn9AkOoJcUdYFmKiP7V9YdBeuI+P/C4wEd2IsRw7bQQBIECgIIARgNEhQKDgoFdWF0b20SBTEwMDAwEMCEPRpACoMRQiLT8pX2N9/ZaOm/VW0AcROsOH3g5lFTEgmXnN8xq+lGNtdIGqXcLvtuX/I6X7JxUMv2utrxRkJzdCQXPA=="}
```

Response
```json
{
    "message": "failed to broadcast transaction: codespace: sdk, code: 2, description: tx parse error"
}
```
