### ISSUE TITLE
Wallet connect out on mobile not working 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6008]
### Overview

When trying to connect to Idle Finance from the mobile app, the camera doesn't read the QR code and cannot connect

### References and additional details

1) Open mobile app
2) Select connect dApp from the menu
3) Try scan the QR code from Idle finance https://app.idle.finance/#/dashboard
4) Note that the camera in the app does not read the qr code
*can connect to uniswap by scanning the QR code

### Acceptance Criteria

Should be able to connect to idle finance via mobile dApp

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
Unable to connect to any dApps now, including uniswap. dApps are working on desktop but not mobile.

**Comment by MBMaria** [comment]
1) open mobile app 
2) select Connect dApp from the top left hand corner menu
3) scan or enter qr code of desired dApp
4) Note that the Connect button is a dead click 
![image](https://github.com/shapeshift/web/assets/100157997/598abb4b-393a-436f-9b0e-d8e977a6ee00)

**Comment by 0xean** [comment]
I can take a look at it

**Comment by 0xean** [comment]
per @woodenfurniture - this never worked and was a known gap when WC shipped.

Therefore we should treat this as a feature request vs a bug ticket and @twblack88 can deliberate on priority. 

If we aren't going to add this support to the mobile app, we should remove it from the UI so its not confusing users however. 

Some notes if we decide to try and get this working:

@gomesalexandre and I tried updating packages and using the native reach shims from WC... none of this helped. When logging state from the mobile app, the following line is never hit

https://github.com/shapeshift/web/commit/972d510b084f860b4d22aa0f58387a60a4c42e53#diff-cc45a3456fb6eeae871d41a5dd230bf278754ee5a2050b4895833461a61ebd70R42

leading to pair being undefined

https://github.com/shapeshift/web/commit/972d510b084f860b4d22aa0f58387a60a4c42e53#diff-066cc2d15263e61b3f2b227a3ac5742a7fb88c52bb1e2ba9d60d014d44d9d7a0R25

and 

https://github.com/shapeshift/web/commit/972d510b084f860b4d22aa0f58387a60a4c42e53#diff-cc45a3456fb6eeae871d41a5dd230bf278754ee5a2050b4895833461a61ebd70R51

always being false.

**Comment by NeOMakinG** [comment]
Reopen if I'm wrong but I think we can close this one as it's a part of the new mobile release we've done
