### ISSUE TITLE
Review and fix all areas that set slippage tolerances

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6017]
Long tail swaps don't correctly enforce slippage leading to sandwich and a loss of user funds. We need to resolve this and additionally take the time to audit anywhere else this might be the case and confirm slippage is set correctly. 

#### AC
1. Long tail swaps correctly enforce a `minAmountOut` for the intermediary asset
2. All other swap protocols / routes are confirmed to enforce sane slippage tolerances

**Comment by 0xApotheosis** [comment]
In addition to the long-tail fixes above, I sanity checked the following at runtime:

**1inch:**

We correctly build the transaction payload with the user's specified slippage (or the default if not set) in the `slippage` parameter:

<img width="492" alt="Screenshot 2024-01-29 at 9 37 19 am" src="https://github.com/shapeshift/web/assets/97164662/8446de56-1492-44e3-a130-abfb3b2711ba">

**0x**

We _only_ use the user's specified slippage if 0x supports [slippage protection](https://0x.org/docs/0x-swap-api/advanced-topics/slippage-protection#what-is-slippage-protection) for that trade pair. If not, we default to 0.2% (and let the user know that custom slippage is not supported).

**THORChain**

- For non-streaming swaps we use a param in the memo to set the minimum amount out before the trade will be reverted (based on the slippage value - custom or default).

- For streaming swaps slippage is handled automatically by the protocol, see: https://discord.com/channels/838986635756044328/1166265575941619742/1166500062101250100

**LiFi**

Defaults to 0.5%, and can be overridden by the user.

**Comment by 0xean** [comment]
thanks @0xApotheosis for the review here.
