### ISSUE TITLE
V7 farming rewards showing APR after rewards expiration

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6071]
Currently v7 farming has expired, while we still need to allow users to interact with this contract to remove assets, it shouldn't show any APY.  

<img width="1158" alt="Screenshot 2024-01-24 at 11 14 03 AM" src="https://github.com/shapeshift/web/assets/15096737/5b932b21-712f-41c9-93f9-001079f78db2">

The [staking contracts](https://etherscan.io/address/0x5939783dbf3e9f453a69bc9ddc1e492efac1fbcb#readContract) have an expiration date that is build into them (periodFinish) which should be respected as the deadline to no longer show a valid APR on the staking contract. 

Not sure how this has been dealt with in the past, but ideally we simply query that timestamp to disable showing any rewards past the date.

#### Acceptance Criteria
- UI correctly stops showing rewards/APR for a staking contract after `periodFinish` has past
- User can still interact with existing staked position in that contract, but we disable new deposits (think this already exists).
- bonus points if we display the expiration date nicely somewhere in the UI so that the user understands the timeline and when they will need to migrate (next to V8 or the APR, maybe @reallybeard has an opinion as to where) 

alternative long-term solution: we find a better staking contract to fork and stop with this nonsense every 4.5 months :)

**Comment by 0xean** [comment]
per conversation with most TMDC members, a new contract would be the desired long term path, so any fixes will just be for v8 and once v8 ends, we will migrate to an evergreen type contract to avoid migrations.

**Comment by gomesalexandre** [comment]
@0xean we already consume `periodFinish` from the contract to detect expired state:

https://github.com/shapeshift/web/blob/f519a098b3341522031b155952bdcfeea4be3c0c/src/state/slices/opportunitiesSlice/resolvers/ethFoxStaking/index.ts#L87-L88

I'll author a PR to ensure we holistically stop showing APR for expired opportunities. While FOX Farming is the obvious one, and the only one having this property, it may not be in the future so might as well!
