### ISSUE TITLE
Streaming swaps completion state errors

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6086]
### summary

When attempting a streaming swap from an EVM to BTC after the initial EVM input transaction was confirmed, the UI showed as Trade Completed / BTC is now in your wallet and the progress bar was still spinning. Even after the BTC was confirmed the progress bar still didn't update.

This was not correct and was much too fast for the outgoing BTC tx to have already been executed. 

Will ask operations to recreate and record screen. 

### Recreation steps

1. swap BNB or other evm asset to BTC via streaming swap
2. when BNB tx confirms UI will update to a trade complete state incorreclty

### Acceptance Criteria

- Trade complete only shown when outgoing tx is confirmed
- progress bar is updated appropriately

**Comment by purelycrickets** [comment]
Ops was able to recreate and screen record this issue as described above.  

See the successful "Trade complete Successfully received BTC on Bitcoin" message while the outbound BTC has been sent on chain: 

https://github.com/shapeshift/web/assets/94998097/232c2efb-1906-4d17-97e7-8f34e84910f0

**Comment by woodenfurniture** [comment]
> Ops was able to recreate and screen record this issue as described above.
> 
> See the successful "Trade complete Successfully received BTC on Bitcoin" message while the outbound BTC has been sent on chain:
> 
>  Screen.Recording.2024-01-26.at.11.19.16.AM.mov

@purelycrickets is this the correct screen recording? it seems to be cut off

**Comment by purelycrickets** [comment]
Whoops, that was my failed first attempt at recording it.  Here is the actual error recorded: 
Uploading Screen Recording 2024-01-26 at 11.19.52 AM.mov…

**Comment by purelycrickets** [comment]
lol here it is:

https://github.com/shapeshift/web/assets/94998097/70407c2e-385b-4261-8405-03305e1d5093

**Comment by woodenfurniture** [comment]
@purelycrickets that one's a regular thorchain swap. Judging by the  BTC showing as received in dropdown at the top of our app (which is totally disjoint to the swapper and runs off blockbook), it the looks the funds were in fact received and it seems the mismatch between us and viewblock is indexing on their viewblock's side - i.e they can take several minutes longer than us to index and display a completed trade. I dont think there is an issue with regular swaps at least.

Do we have a recording of the streaming swap issue regarding progress bar not updating?
