### ISSUE TITLE
Logic for identifying partially completed symmetric LP position based

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6094]
### Overview

TS handles a state where a user is able to see that they have completed part of the 2 needed transactions for a symmetrical LP position, we don't have this consideration in our implementation.  

We need the logic to identify this state exists (this ticket) and UI to display this state to a user (seperate ticket).

### References and additional details

NA

### Acceptance Criteria

- Spike into and identify conditions that lead to a user being in the partially completed state 
-

**Comment by 0xApotheosis** [comment]
Closed by https://github.com/shapeshift/web/pull/6481

@kaladinlight let me know if you feel this is incorrect.
