### ISSUE TITLE
Design and implement TX row for incomplete TC LP deposit 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6095]
### Overview

re: https://github.com/shapeshift/web/issues/6094

### References and additional details

See TS screenshot 

### Acceptance Criteria

- tx row mock and implementation create to show incomplete state

**Comment by 0xApotheosis** [comment]
Thorswap UI for an incomplete symmetrical position:

<img width="519" alt="Screenshot 2024-01-30 at 7 56 39 am" src="https://github.com/shapeshift/web/assets/97164662/5d2797de-0e86-4034-ba8c-26c3ed97daa5">

**Comment by gomesalexandre** [comment]
We will also want to ensure that this gives the option to withdraw if a user changed their mind and wishes to withdraw instead of completing their deposit

**Comment by 0xApotheosis** [comment]
We now have an "Incomplete" tag on pool positions (https://github.com/shapeshift/web/pull/6481) - this ticket feels complete.

@kaladinlight @gomesalexandre let me know/re-open if there is still more work to be done here.

**Comment by kaladinlight** [comment]
> We now have an "Incomplete" tag on pool positions (#6481) - this ticket feels complete.
> 
> @kaladinlight @gomesalexandre let me know/re-open if there is still more work to be done here.

Feels like this issue has been completed. Another ticket can be written up if we wish to update/change the UI/UX for this flow at all with product mocks included. :+1:
