### ISSUE TITLE
Review slippage on thorchain LP transactions and confirm all working as expected

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6096]
### Overview

triple check that all slippage parameters are correctly set prior to release 

### References and additional details

NA

### Acceptance Criteria

- @0xApotheosis and @gomesalexandre sign off on slippage is enforced.

**Comment by gomesalexandre** [comment]
Assigning to @kaladinlight as this is related to the LP calc improvements being worked on

**Comment by kaladinlight** [comment]
Estimated slippage calcs are being displayed correctly. There is no explicit limit support for lp transactions. Closing as complete
