### ISSUE TITLE
V2 (Alpha): Unable to send USDC

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#611]
As a user, i want to be able to send USDC via V2 of the web app.  Currently, when trying to send USDC a user will continuously  run into an "Insufficient funds" error regardless if the user has enough funds and/or gas.

- Visit https://app.shapeshift.com/
- Connect a wallet with a USDC balance
- Attempt to send some/all of the USDC
- Notice the error messaging

A/C:
Users are able to send USDC if they have a balance and enough gas without an error. 
 
<img width="611" alt="Screen_Shot_2021-12-22_at_5 50 53_PM" src="https://user-images.githubusercontent.com/57505863/147271147-9b1cd731-6ba2-4041-81db-3ca02c7c1d9f.png">

**Comment by 0xean** [comment]
![Screen Shot 2022-01-07 at 9 14 57 AM](https://user-images.githubusercontent.com/15096737/148572800-94890bd4-8b3b-42a0-8987-e9c854387432.png)


@SS-FOX-McCloud - can you please confirm this still is an open issue? I attempted just now and was able to get past to the metamask screen

**Comment by SS-FOX-McCloud** [comment]
Can confirm this is no longer an issue.
