### ISSUE TITLE
1inch quotes failing

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#6140]
### Overview

currently in Prod, we are unable to fetch 1inch quotes for swapper. 

This error reads in the console: Failed to load resource: net::ERR_NAME_NOT_RESOLVED
and the error message "An error occurred getting a quote" is displayed to the user. 

### References and additional details

https://github.com/shapeshift/web/assets/94998097/e938d473-5723-499a-9691-18d018f2ccfb

### Acceptance Criteria

1Inch quotes working again.

**Comment by twblack88** [comment]
we moved to their low tier b/c they want us to pay 10x 0x.

**Comment by 0xean** [comment]
We probably also need to migrate our API key as well. 

Its worth considering if we should remove the error message and just not display 1inch if no quote is available since we expect intermittent errors that really shouldnt be user facing.  @twblack88 thoughts?

**Comment by 0xean** [comment]
@twblack88 - discussed with eng team today, and the consensus is that since lifi include 1inch and there is significant overlap with 0x that it would be best to just disable 1inch in production.  I want to make sure you are good with this before we move forward.

**Comment by twblack88** [comment]
yeah is fine.
