### ISSUE TITLE
Spike on Displaying: NFTs, defi, Tx history

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#6154]
### Overview

We need to offload the data ingestion for things like NFTs  etc.  Data is greedy for full Tx history when it might be better to background that on a different menu. 

If we know user balance we theoretically can populate the rest of the long tail display of txs or obscure older actions on a lazy load. @kaladinlight had a beautiful plan for this but not sure if we got blocked by unchained. 

Putting this spike in here so we remember to hit it at next roadmap call. 

### References and additional details

![image](https://github.com/shapeshift/web/assets/8991325/7d93b71a-c937-4090-80af-61043b93e267)

### Acceptance Criteria

we meet
we create an artifact of decisions

**Comment by woodenfurniture** [comment]
zerion
