### ISSUE TITLE
Make FOXy withdrawl only

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6178]
### Overview

Tokemak's going away and we don't have a plan for FOXy at the moment, continuing to allow deposits doesn't make sense if we know FOXY v1 has to go away and soon.

### References and additional details

NA

### Acceptance Criteria

- FOXY adds are no longer supported in the UI, not shown as an option for users who aren't already involved 
- withdrawl's still allowed for users with existing positions

**Comment by twblack88** [comment]
related to #5074
