### ISSUE TITLE
Add fee curve to Thorchain LP

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6179]
### Overview

TDMC has voted on the below params for the fee's on TC LP

### Acceptance Criteria
- fee model implemented for TC LP depoosit

**Comment by twblack88** [comment]
https://discord.com/channels/554694662431178782/920449863408287855/1207415430025580627

**Comment by 0xean** [comment]
AC:

- UI display 
- Separate out params for LP vs Swapper and allow them to be defined in the env file
