### ISSUE TITLE
Ledger Live Integration

### ISSUE THREAD

**Issue by hpayne1** [shapeshift/web#6181]
### Overview

ShapeShift BD team has been in contact with the Ledger Partner success and integration team. They are keen to have more decentralized partners inside their app and are willing to help guide us with this integration and onboarding process.

### References and additional details

Link to their docs:
https://developers.ledger.com/docs/discover

Needed: (can find this on the docs via link above)

he app supports:

    0-click connect to the wallet
    Clear Signing on hardware
    Analytics so we can monitor product performance

In case of DApps on EVM chains, you have created a Dune Dashboard to monitor the performance of your DApp when used in Ledger Live, as it is a requirement to be listed in the search bar
The app leverages the [Wallet API](https://developers.ledger.com/APIs/wallet-api/introduction)
All the app information and metadata is complete and accurate
You test your app for crashes and bugs
The app forbids logging through other wallets
You update your contact information in case our Live App Review and Editorial teams need to reach you
You accept our [General T&Cs](https://docs.google.com/document/d/1kFUVIyHuSUJSA4HBAub1qvrIdfyYlXTL/edit?usp=sharing&ouid=116459622350591585491&rtpof=true&sd=true)
, and Specific T&Cs when applicable

I was told the whole KYB thing is not needed but can double check that.

### Acceptance Criteria

Ledger Live users can connect to app.shapeshift.com inside Ledger Live

### Need By Date

none :)

### Estimated effort

?

**Comment by twblack88** [comment]
From what we hear working with ledger will not work for the DAO (KYB amongst other things)

gonna close until they reach out for integration.
