### ISSUE TITLE
Successful Tx flagged as failed?

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#6183]
### Overview

This one is a bit strange. I had some ETH and went to send a test amount of like $100 or so. Went through the send flow and signed the Tx in my MM connected to the app. 

Tx succeeded on chain, but 
- on the activity tab it showed as failed
- it triggered the success toast but didn't sit as pending on the drawer

Ideally we make small amount sending more seamless and safe. 

### References and additional details

Tx from etherscan was fine

![But the TX link was success? made me nervous](https://github.com/shapeshift/web/assets/8991325/ab99d81e-8be4-4358-aa45-3a4613c6daad)

But on the activity tab it got flagged as failed.
![After i traded FOX i sent a test amount and it failed](https://github.com/shapeshift/web/assets/8991325/28d89b3a-a5f1-47ab-992b-f28794db13be)

### Acceptance Criteria

- [ ] We tighten up the pipeline from send -> drawer -> activity. making sure we have tx's properly flag
- [ ] investigate why this guy got flagged as failed on our transactions. `0x9f589048633134cb89753a72e92ed8a5d53f26aea9be27e8e3d68d6e86fc451f`

**Comment by 0xean** [comment]
networking request failing creates incorrect state for the transaction itself.

**Comment by 0xean** [comment]
@shapeshift/operations can you help us to determine if you are able to replicate this? If its able to replicated, engineers can pick it up, but otherwise might close it without more information / reports of this.

**Comment by purelycrickets** [comment]
Ops is currently unable to recreate the 'failed' error message state of this issue: 
![Screenshot 2024-04-09 at 8 07 54 AM](https://github.com/shapeshift/web/assets/94998097/eb0736a9-bf1d-4755-9c7a-e876f52e0a22)

@twblack88 were you ever able to reproduce this issue consistently, or was this a one off?  I am in support of closing this issue if we cannot reproduce the error.

**Comment by twblack88** [comment]
One off. @purelycrickets  closing 🤝
