### ISSUE TITLE
Error when connecting to Ledger on initial load

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6188]
### Overview

When trying to connect to Ledger on an initial load, it will say there is an error. Trying to connect straight afterwards allows you to connect

### References and additional details

1) Open app.shapeshift.com
2) Select Ledger
3) Note the modal pops up with "Error"
4) 'X' out of modal and select Ledger again and note you can connect

https://github.com/shapeshift/web/assets/100157997/c9e94fb7-f6d4-4dd1-bcb7-fa187577634c

### Acceptance Criteria

Should be able to connect to Ledger on first attempt

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria I haven't been able to repro and never seen this one before, or at least not in this context, this effectively means that you're not clicking on a button to pair the Ledger, which you definitely are.

Do you have anything that could rug your connection to the Ledger or intercept the button click? Think browser extensions, Ledger live, perhaps as a stretch some USB hub that could intercept actions.

https://github.com/shapeshift/web/assets/17035424/e932867f-5648-44af-a5bf-01f5ceca3af4

Please try with a fresh chrome session (no MM, xDEFI, adblock or anything) and let me know if that helps 🙏🏽

**Comment by purelycrickets** [comment]
I am able to reproduce a lesser version of this issue where whenever I try to add my ETH account, the first time the connection seems like it does not work and requires a second connection to work.  I recreated this 3 times incognito before recording it: 

https://github.com/shapeshift/web/assets/94998097/1f3a35cc-60c5-477c-8cad-55439d3d0a9c
