### ISSUE TITLE
Resolver for ETH/FOX Staking: staking not implemented error

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#6195]
### Overview

Currently in Prod, users are unable to deposit into the FOX farming contract.  attempting to do so results in a dead click and an error in the logs: opportunitiesApiSlice.ts:130 resolver for ETH/FOX Staking::staking not implemented

### References and additional details

This screen recording was captured with a native wallet connected in an incognito session and was recreated twice before recording: 

https://github.com/shapeshift/web/assets/94998097/3a82f335-4405-41d0-82e0-91ba05170c23

### Acceptance Criteria

Users are able to deposit into the FOX farming contract through the app flow successfully.

**Comment by gomesalexandre** [comment]
@purelycrickets the warning you see is unrelated to the approval hanging. Is the issue here unable to approve or being unable to deposit? Is there any network tab errors?

**Comment by gomesalexandre** [comment]
@purelycrickets there were some intermittent issues with the Ethereum send endpoint yesterday, could you try this again and confirm this isn't happening anymore? I was able to successfully approve and sign a FOX Farming deposit Tx from native.


https://github.com/shapeshift/web/assets/17035424/43b05210-c45b-4fa4-b220-f1f485d7e07e

**Comment by 0xean** [comment]
@purelycrickets - low priority, but can your team re-test when able.

**Comment by purelycrickets** [comment]
Issue was unable to be recreated.  Closing this ticket. Thanks fam.
