### ISSUE TITLE
[Feature] Limit Order 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6198]
https://github.com/shapeshift/web/labels/limit%20orders

- [spec](https://www.notion.so/shapeshift/Limit-orders-fa0d8cd178e9483db6f989668561ce3f?pvs=4)
- [figma](https://www.figma.com/proto/IBz3Fn75GGjXfm89FsymAL/Limit-Orders?page-id=680:7&type=design&node-id=680-2004&viewport=246,770,0.23&t=8kMDwXWQdNVvLHrg-1&scaling=min-zoom&starting-point-node-id=680:2004&mode=design)
- https://docs.cow.fi/cow-protocol/reference/apis/orderbook

**Comment by 0xean** [comment]
- keep open orders tray on the same side as the quotes 
- open orders are synced to the account that is selected in the trade modal (for now)
- enable partial fillable by default for now (no advanced options)

**Comment by woodenfurniture** [comment]
Closing as stale
