### ISSUE TITLE
[Spike] Approval flow for cow limits 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6204]
- spike into permit2 for cowswap (create payload and attach payload to order?)
- output from spike is ticket to be groomed

**Comment by woodenfurniture** [comment]
Permit2 is not available for cowswap, but they do provide `EIP-2612` Permit, which requires a token that has EIP-2612 permit support (such as COW, USDC, and DAI - many tokens do not support this.

To avoid the complexity of multiple allowance flows for cow limit orders, I recommend we stick to vanilla ERC20 `approve()`.

**Comment by woodenfurniture** [comment]
Closing, outcomes in ticket https://github.com/shapeshift/web/issues/8154
