### ISSUE TITLE
Requests failing when attempting to approve a transaction

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6215]
### Overview

When trying to do approvals, requests are failing. (noted on avax and polygon). Sometimes the approval tx will go through, sometimes it will fail

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/e2eb07dc-d99e-4bce-ab2b-d86d74616fba)
Status error:
{jsonrpc: "2.0", id: 639, method: "eth_blockNumber"}
id
: 
639
jsonrpc
: 
"2.0"
method
: 
"eth_blockNumber"
https://github.com/shapeshift/web/assets/100157997/77b19b33-721d-4434-a8ba-7bfd059b9754

console error: Access to fetch at 'https://daemon.avalanche.shapeshift.com/ext/bc/C/rpc' from origin 'https://app.shapeshift.com/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Acceptance Criteria

Approvals should go through 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Approvals are fine on my side, this may have been an intermittent issue with the Polygon and Avalanche JSON-RPC nodes - from looking at the error messages, the approval Tx was succesfully sent, but the Tx receipt was unable to be fetched.

<img width="741" alt="image" src="https://github.com/shapeshift/web/assets/17035424/340447bf-f860-4692-b53c-bcfd3bc3b0da">
<img width="752" alt="image" src="https://github.com/shapeshift/web/assets/17035424/c6b0bede-2cda-49c4-a3e0-f37d8d88b240">

@MBMaria given the intermittent nature of this, could you give this another try and confirmed this is fixed? 🙏🏽

**Comment by woodenfurniture** [comment]
Seeing issues with approvals for polygon
![image](https://github.com/shapeshift/web/assets/125113430/cc598b97-1cba-4089-b60f-f4f277677697)
![image](https://github.com/shapeshift/web/assets/125113430/6e5e5998-9633-4398-996d-f819db540957)
