### ISSUE TITLE
Create UI components for Limit order tab and confirmation flow in swapper interface

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6218]
- See https://github.com/shapeshift/web/issues/7905#issuecomment-2398441892 for architecture spike. Basically use the same architecture as claims
- Ensure https://github.com/shapeshift/web/issues/7908 is done first
- excludes the order history and order status panels
- needs feature flag

https://www.figma.com/design/IBz3Fn75GGjXfm89FsymAL/Limit-Orders?node-id=691-4267&node-type=frame&t=10V63HAsj795allM-0

**Comment by woodenfurniture** [comment]
Blocked by https://github.com/shapeshift/web/issues/7908

**Comment by woodenfurniture** [comment]
Need to create a feature flagged placeholder UI so @0xApotheosis can begin work on #6206
