### ISSUE TITLE
Demo Wallet doesn't have any balance on the Asset Page

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6240]
### Overview

When viewing the asset page on the demo wallet, there are not balances along side the assets

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/47d49cb8-e02a-48df-8702-2e9909e9c765)

### Acceptance Criteria

Assets should have a balance next to them 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
is this affecting native wallet or just the demo wallet?

**Comment by MBMaria** [comment]
Just the demo wallet @0xean
