### ISSUE TITLE
Trades being reported as halted for non-thorchain chains

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#6242]
### Overview

When trading from a thorchain-swapper-compatible chain to a non-thorchain-swapper-compatible chain, the swapper reports that trades are temporarily halted for the unsupported chain.

### References and additional details

![image](https://github.com/shapeshift/web/assets/125113430/dadbb70e-2eb0-43e6-a7e0-2840ce7a30a6)
![image](https://github.com/shapeshift/web/assets/125113430/6c72ca13-6fb7-4475-834f-d8697743b736)

### Acceptance Criteria

Swapper should only report a chain as halted when it is actually halted.

**Comment by gomesalexandre** [comment]
closed by https://github.com/shapeshift/web/pull/6236
