### ISSUE TITLE
intermittent out of gas reverts with swapper

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6247]
@woodenfurniture had some failures when testing swaps related to OOG errors, it was intermittent and the specific swaps did use significantly more gas than other's he completed (potentially different routes/paths). 

https://polygonscan.com/tx/0xb4932512bedbcd006a628a3211c2dd2c76a267639f31d31edd6847fee7483c00
https://polygonscan.com/tx/0xdd2a01b1f48988e1934b127abfd55cf3598d02294d6337600ad13df5f8035638

Either way seems we need to consider how we are estimating gas and resolve the issue here.

These were executed using native wallet

**Comment by 0xean** [comment]
- should we consider using the 0x based gasLimit vs estimating against our own node?

**Comment by gomesalexandre** [comment]
Closed by https://github.com/shapeshift/web/pull/6516
