### ISSUE TITLE
review release script and hot fix process to ensure its smooth for next production bug that needs a hotfix against main

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6249]
During a recent production issue their was not confidence in the ability and process to make a hot fix against main to avoid pushing the differences between develop and main.

We should add this functionality in the script and everyone's comfortability with it to ensure during the next prod issue we can make use of it.

we should also document this process a bit better so any engineer feels comfortable in the midst of a prod issue

**Comment by gomesalexandre** [comment]
Will take a look at this since I'm precisely in this context with the robots work currently
