### ISSUE TITLE
[Spike] Document load times for large wallet 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6252]
#### background
several users with large wallets have complained about slow app experiences and initial load times. Some of them are on mobile devices, but the experience isn't unique to mobile only.

we should determine was an acceptable load time to target for a large wallet (how to define this?) and then work towards what we can fit into that time budget. 

To start, we can get a document of the current time spent on each group of actions we take on load (wallet balances, tx history, defi positions, etc) and then work with product to reason about what can be deferred or removed. 

#### AC 
1. determine a wallet we can use as a performance benchmark
2. document loads time with profiler using this wallet
3. consider optimizations that could be made 
4. once complete schedule time with product / eng to discuss options to improve performance

**Comment by woodenfurniture** [comment]
Document with findings here
https://www.notion.so/shapeshift/Perf-2024-02-27-9c145074b2e9423486b4876f913704ce?pvs=4
