### ISSUE TITLE
Cow Swap Order Changes Need By March 19 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6261]
### Overview

Cow is changing how their solver fees are taken:

> I wanted to give you an update about a change we are pushing for (which will also very soon, probably by tomorrow, will be formalized in a CIP that will be moved to voting). We want to deprecate the fixed-signed fee orders that are currently the standard swap "in-market" orders that most users place, and instead have all orders as zero-signed fee orders. Such a change would give the flexibility to solvers to charge an appropriate fee, based on the true gas cost of the execution, and also push benefits that come from CoWs/batching etc to users (while the fixed fee model doesn't allow that as the fee is computed based on a "single-order" execution).

> The target date for officially deprecating the fixed-fee order class is March 19, 2024 (assuming the CIP i mentioned above passes), but ideally we would like to have all integrators implement the change before that. I am attaching an informal doc that describes the change. Let me know whether you need any support on this.

### References and additional details

```
 Convert CoW Protocol swap orders to zero-signed fee orders
Suppose you are about to post a swap (market) order on CoW Protocol with the following specifications:
     Sell token:    A
     Sell amount:   x
     Fee:           f
     Buy token:     B
     Buy amount:    y
Note that this is the well-known fixed fee swap order that we have been used to.
The proposed change now asks to instead propose to sign a zero-fee order; in such a case, solvers are responsible for dynamically computing a fee for the order, thus allowing them to pass any gas savings due to batching etc to users.
To do so, one has to replace the above specification with the following, meaning that instead of proposing to the user to sign the order above, we should instead ask them to sign the following order:
     Sell token: A
     Sell amount: x + f
     Fee:           0
     Buy token:     B
     Buy amount:    y
```

### Acceptance Criteria

Updated signed order for cow userse

### Need By Date

March 19 2024

**Comment by 0xean** [comment]
Waiting for the COW CIP to pass before we pick this up.

**Comment by 0xean** [comment]
this has been unblocked

**Comment by 0xean** [comment]
adding to bug board so this gets completed the week of 3/11

**Comment by gomesalexandre** [comment]
Note, we'll probably want to ensure we use the latest AppData spec: https://github.com/cowprotocol/app-data
