### ISSUE TITLE
Auto account selection issues with swapper

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6264]
#### context

recently this hotfix was introduced:

https://github.com/shapeshift/web/pull/6263#pullrequestreview-1891137438

which caused this regression (but fixed other larger issues with quote retrieval and account selections)

https://github.com/shapeshift/web/commit/0cfb0dbf21d6b52f68617ebdbf8569db27142070

#### AC
- When a sell account is selected using EVM chains, by default the buy account matches it regardless of account balance

**Comment by gomesalexandre** [comment]
Cannot repro this one anymore, may have had some cached shenanigans when testing. The *initial* buy account now properly matches the sell account account number https://github.com/shapeshift/web/pull/6263

<img width="602" alt="image" src="https://github.com/shapeshift/web/assets/17035424/214e48e5-9e1e-4e3e-84c9-b322b56cb209">
<img width="676" alt="image" src="https://github.com/shapeshift/web/assets/17035424/35d59dbb-1dae-479e-b38c-b2d2a22e89f5">

<img width="680" alt="image" src="https://github.com/shapeshift/web/assets/17035424/a0b346b0-d6c5-41af-925b-cd67483edae0">
<img width="681" alt="image" src="https://github.com/shapeshift/web/assets/17035424/5d721a9d-88c3-465e-8522-b4afd543aa4d">
<img width="565" alt="image" src="https://github.com/shapeshift/web/assets/17035424/5bf20eca-ddd3-4f57-8a29-8bada2addef6">
