### ISSUE TITLE
Approval txid missing from Trade Complete Modal

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6270]
### Overview

On the Trade Complete modal, if you drop down the 'Show Details' area, the txid for the approval (if applicable to the trade) no longer appears

### References and additional details

Complete a trade that requires an approval. Note the tx/txid disappears once the approval has completed 
Release: 
![image](https://github.com/shapeshift/web/assets/100157997/571908b4-0679-46b7-ad67-0529c8a7ca99)
![image](https://github.com/shapeshift/web/assets/100157997/dbc93872-919e-487f-989e-40432ae2b977)
![image](https://github.com/shapeshift/web/assets/100157997/e96dbaaa-f0d3-4c5d-a533-8503570c096c)

### Acceptance Criteria

Should be able to see txid of the approval in the trade complete modal 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria are we still able to repro this in develop?
Managed to successfully perform a few trades and the Tx explorer link is present:

<img width="630" alt="image" src="https://github.com/shapeshift/web/assets/17035424/0071bd7e-5230-4127-b0b0-9f64f13296ac">
<img width="562" alt="image" src="https://github.com/shapeshift/web/assets/17035424/740523f0-47ca-44c6-acd5-fc5dd85647a9">

**Comment by 0xean** [comment]
Closing.
