### ISSUE TITLE
Swapper error - "A problem occurred executing the swap"

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6280]
When attempting to swap from USDC to imgnAI, after approval, when I attempt to sign the transaction an error occurs.

```
A problem occurred executing the swap
makeSwapperAxiosServiceMonadic
```

https://github.com/shapeshift/web/assets/15096737/61deb97e-0d2e-4491-a3c1-2003baaa7181

Looks like 0x returns the following error
```
{
    "code": 105,
    "reason": "IncompleteTransformERC20Error",
    "values": {
        "outputToken": "0xa735a3af76cc30791c61c10d585833829d36cbe0",
        "outputTokenAmount": "80764087136406",
        "minOutputTokenAmount": "83102157180477"
    }
}
```

Probably an edge case with the token, but we should see if we can determine this before the users wastes gas on a approvals

**Comment by gomesalexandre** [comment]
Closing as this is a non-actionable, chicken and egg scenario here:

- 0x needs allowance to be granted before giving us a quote
- We would like to block firing approvals in case Tx may fail, but 0x does Tx simulation in their quote endpoint, which will only succeed (or fail at `IncompleteTransformERC20Error` time) so long as you have granted allowance, else you'd get a very different allowance error
