### ISSUE TITLE
Users reporting missing assets in balance 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6291]
#### User feedback
> my wallet balance displayed in shapeshift is 1/7th the balance displayed in Rabby :sadpepefox:  hard to use a wallet/dapp when so many of your assets/portfolio aren't displayed. did we stop crawling coingecko's tokenlist daily to add new tokens?? none of the eigenlayer LRT tokens (rsETH, swETH, etc) are supported in the app but they're all on CG's tokenlist. 

#### Background
- user has a very large wallet 
- user doesn't see some assets that they see in other portfolio viewers.
- assets do appear to be in our assets list for example 

```
 {
      address: '0xa1290d69c65a6fe4df752f95823fae25cb99e5a7',
      chain: 'ETH',
      identifier: 'ETH.RSETH-0XA1290D69C65A6FE4DF752F95823FAE25CB99E5A7',
      decimals: 18,
    }
```

ping @0xean to get user's address to attempt to recreate. Throttling or other network errors could potentially explain this?

**Comment by kaladinlight** [comment]
Some additional info, we have the balance and the asset, but we have no market data, so it doesn't show up against any filters by balance

![image](https://github.com/shapeshift/web/assets/35275952/b970beed-7af4-4cb6-8f93-bf664fac67eb)

**Comment by 0xean** [comment]
would be good for us to either determine a manual process by which we are going to update these periodically or automate it into out build pipeline to ensure we don't get too stale again.  That work can certainly be done as a follow up vs a bug fix.

**Comment by gomesalexandre** [comment]
@0xean that's definitely something we should *automate* in some fashion.
I'm not sure running something "something hosted" that would e.g regenerate at interval (like a cron bot opening PRs regenerating asset and caip asset data) would make sense, but I believe the path of least effort would simply be to have a timestamp on both and have CI fail when the timestamp on any of these gets too old
