### ISSUE TITLE
Native Wallet: Add validation logic to rename modal

### ISSUE THREAD

**Issue by cjthompson** [shapeshift/web#630]
AC:
* In NativeRename, if the length of the name input is "0"
  * Show a form error that using an empty name will remove the nickname
  * delete the "name" meta property from the Vault rather than setting it to an empty string
* Set a maximum length of 64 (or some other justifiable number) characters for the name
* Show an error if the user inputs more than 64 characters and disable the Rename button

The developer MUST verify that any content put in the name is escaped and rendered as Text (avoids HTML injection).

**Comment by jdambron** [comment]
@cjthompson I think the same logic should also be implemented at wallet creation, not just renaming (except for the first rule).
For now, there is no length control at creation. It would make sense to have something coherent here.

**Comment by jdambron** [comment]
@cjthompson or @0xdef1cafe I didn't put the `closes` keyword keyword in my PR, sorry. But this issue can be closed as the PR was merged.
