### ISSUE TITLE
Max send Eth on Optimism not working

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6312]
### Overview

When trying to do a max send of Eth on Op, it is not taking into account the value of the gas fee and is causing the transaction to be rejected

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to send modal and select eth on Op
3) Select max send
4) Confirm send and note the total amount to send is higher than the max balance and causes tx to fail 
![image](https://github.com/shapeshift/web/assets/100157997/2c682dd0-c8cc-4782-85ac-743063d061dc)

https://github.com/shapeshift/web/assets/100157997/5ec98685-3836-4fae-8c85-80d63f490a1b

### Acceptance Criteria

Should be able to complete max send eth on Op 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by Vayras** [comment]
hey! @MBMaria I'm really interested in contributing towards this project, what are the issues available to work on? and do you accept public contributions or do I have to join a development community? either way kindly let me know.
