### ISSUE TITLE
Earn page mobile borked

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#6336]
The by asset view on mobile is currently displaying a sidebar of colors.

![image](https://github.com/shapeshift/web/assets/8991325/fb7fb6a7-f8f3-48bc-9d43-3221a8984727)

@gomesalexandre @reallybeard

**Comment by gomesalexandre** [comment]
@reallybeard FYI I couldn't repro in web under any viewport but can repro on the mobile app exclusively - also seems isolated to the "By Asset" view
