### ISSUE TITLE
Incorrect icon for degraded chain

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#6337]
### Overview

The popover notifying users of degraded state shows an incorrect icon for Arbitrum Nova.

### References and additional details

![image](https://github.com/shapeshift/web/assets/125113430/4643f06f-30c5-4fc8-9ce5-c970188c9b02)

### Acceptance Criteria

All icons in the degraded chain popover are correct.

**Comment by 0xean** [comment]
@reallybeard - can you also grab this little guy?
