### ISSUE TITLE
Automate or create manual process to ensure generation scripts are regularly executed. 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6383]
### Overview

https://github.com/shapeshift/web/pull/6295 for context.

We have no current process to ensure we don't end up in this very stale state again. 

### References and additional details

NA

### Acceptance Criteria
- Automate process to update assets in web and caip packages
https://github.com/shapeshift/web/blob/83955732fac904f46e60af8c0b85a8f591f5cfbc/package.json#L28-L32
https://github.com/shapeshift/web/blob/develop/packages/caip/package.json#L20-L22
- bare minimum have comments on PRs when updates are out of date 
- stretch goal: automated PRs open periodically (dependa-bot style)
- use judgement re: time spent here.

**Comment by gomesalexandre** [comment]
Will most likely want to use a cheap and *informative* way vs. blocking. Perhaps finally bringing Danger as a low-eng-cost solution? Which will allow us to warn about many many other things (e.g dangerously touched files, you forgot to xyz etc)
