### ISSUE TITLE
USD values displayed with user's currency symbol in FOX Power/Fee Discount simulation

### ISSUE THREAD

**Issue by firebomb1** [shapeshift/web#6390]
### Overview

When simulating FOX Power/Fee Discounts there are couple of issues for users who use a non-USD currency, they are numbered in this screenshot:

![image](https://github.com/shapeshift/web/assets/88804546/9567c6d8-2422-4e56-9a52-5138407e20a0)

1. The "Trade Size" slider is labelled in the user's currency, but behave according to the USD thresholds/parameters: e.g. any trade over 1000 Indian ruppees (INR) triggers fees in the chart.
2. The value of the threshold for free trades ($1000 currently) is displayed with the user's currency (which is incorrect if they selected anything different from USD).
3. The "based on a fee of" is labelled in USD, regardless of the user's currency.
4. Depending on how this is solved, the chart's abscissa labeling might need to be updated to use the user's currency instead of USD.

As far as I can see this does not affect effective fees thankfully, it's just the way fees are explained/simulated in this modal.

The total fees are valued and labelled in the user's currency, which is good in my opinion as it's what they will pay, but then the rest of the values should also follow this logic.

### References and additional details

1. Select a different currency than USD in the app's settings.
2. Get a quote for any trade.
3. Click on the "ShapeShift Fee" info icon in the quote details.
4. Click on the "Simulate Discount" tab.
5. Witness the inconsistencies caused by the different user currency.

### Acceptance Criteria

Either display USD currency symbols for these values/thresholds (and ignore the user's preference for this specific UI) or convert these to the local user currency where appropriate.

The first solution seem like the easiest and match our public strategy which is communicated in USD in various places (Discord, SnapShot, X, etc.), the second makes it more user-friendly for international users who might not always have the local USD rate in mind when trading and just want to figure out how much they could pay in their local currency.

**Comment by gomesalexandre** [comment]
Ty for the acceptance criteria @firebomb1, I was going to ask what you would expect as a user here but you answered that. USD everything indeed seems like the best case since everything in the fee curve is denominated in USD!
