### ISSUE TITLE
Not getting rates trading into avax on Keepkey

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6393]
### Overview

When trying to trade into avax on Keepkey there are no rates. Swappers dont even load

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/c1f86802-4ea6-47bd-871b-e7d6bc7951c7)

https://github.com/shapeshift/web/assets/100157997/a822d73e-1273-495b-a722-8a054a389b80

### Acceptance Criteria

Should be able to trade into avax

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
KeepKey does not support Avalanche, this is the same ticket as https://github.com/shapeshift/web/issues/6245.

It should, however, work (get quotes) when a manual receive address is entered.

**Comment by 0xApotheosis** [comment]
Actually @MBMaria in your video the trade _from_ ATOM looks like it never even asks for a receive address?

**Comment by MBMaria** [comment]
@0xApotheosis im noticing similar behaviour on mm if you dont have mm installed, when you go to the trade modal and enter a trade from evm to utxo that there are no rates and the swappers dont load. Not getting the opportunity to enter a manual address.
If you select evm to evm, the address pops up, then switch back to utxo, you get the manual address box . Do want want a separate ticket or in here is fine?
![image](https://github.com/shapeshift/web/assets/100157997/72653d6d-f590-4466-b397-137b249215a2)

**Comment by 0xApotheosis** [comment]
All good @MBMaria, it probably has the same root cause. I'll take a look at them both.
