### ISSUE TITLE
LP Withdraw Polish

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#6405]
### Overview

- [x] massage the confirm and broadcast with a "tx sent" state so that users don't do what i did this morning and send multiple Tx's to withdraw position. Sending multiple withdraws is silly. 
- [x] @gomesalexandre - we already skip outbounds for withdraws - so long as inbound is seen and swap is completed, we detect the withdraw Tx as complete and invalidateQueries ~~update the balance on the LP position if we have sent a close Tx (waiting for outbound state can take 15 ish minutes). 1. if the Tx is seen. 2. if we can rely on the pending state from midgard.~~
- [x] remove the back button from the complete screen (https://github.com/shapeshift/web/pull/6408)

### References and additional details

we can see that multiple Tx(es) are `pending: liquidity`
![Screenshot 2024-03-11 at 12 33 55 PM](https://github.com/shapeshift/web/assets/8991325/c2b32377-5c98-4d1b-be8c-ab8e18a898dc)

### Acceptance Criteria

UX is smoother and intuitive. 

### Screenshots/Mockups

![Screenshot 2024-03-11 at 12 32 13 PM](https://github.com/shapeshift/web/assets/8991325/aeb6a449-14e1-4d4e-9241-b50ed912a771)
As a user I'm dumb and moved through the confirmation screen. so i initiated another tx to withdraw. or two. oops. ☝️

**Comment by gomesalexandre** [comment]
@twblack88 effectively closed by #6556 - re: second point, we already do this, see withdraw with position updated as soon as inbound + swap completes (without waiting for outbound)

 

https://github.com/shapeshift/web/assets/17035424/c085ebe2-a0d3-4485-960b-1df496ccf3d9
