### ISSUE TITLE
Lp nice to have ( fast follow)

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#6410]
### Overview

Tagging all the fast follow features that aren't launch blockers

- [x] on the Available pools table sort by column headers. eg., APY,. volume, etc 
- [x] add the chain so the base pool asset is more clear(e.g., there are two USDC rune pools. one is AVAX the other ETH)
- [x] add the fee simulator to LP. E.g., change "trades always free " to "LP under 2k is free." from #6325 
- [ ] add the sanity BPS on the fee breakdown modal 
- [x] ~~Command K searchable LP pairs~~ gomes - @twblack88 we can't do this, we've actually removed opportunities from the search and this follows the same idea because of the complexity and performance issues
- [x] #6456
- [x] not related to LP and not a spike we're going to do in the short term ~~#6446~~

### References and additional details

For fees in summary modal let's just add the BPS so they are set up for success: 
Trade Fee: $3,940.22 (10 bps)
FOX Discount: $200 (2 bps)
Total Trade Fee: $3,740.22 (8 bps)

For fees in simulator quoted from 6325 (im not sure why i copied but here we are): 
> We want to abstract fees to be feature specific. i know this is a PITA. Mainly because LP below $2k and trade below $1k right now. But will change with votes in future.

> In general we should stop using the word "always" like "trades under 1k are ~~always~~ free." 

> If a discount is not applicable we should strikethrough the FOX power discount, or grey it out with an on.hover that says: below fee threshold for `{feature}`. This way it still reflects the 100% discount code but makes it clear in the UX that it doesn't matter.

### Acceptance Criteria

Fixes go in 
Test discounts math and it's sane
We can cross check math against spec in Github or somewhere ( will ask @purelycrickets about docs)

**Comment by twblack88** [comment]
- [x] ~~Add wiki page for fee params and when the PR went in so DFC can start to use github.~~ Gonna make this a DFC tracking thing and refer to a forum post that gets uploaded. All engineering will have to do is comment with the PR.

**Comment by gomesalexandre** [comment]
Closing as the bps stuff is unrelated to this issue as discussed with @twblack88 yesterday - see https://github.com/shapeshift/web/issues/6325 for the actual fee modal rework issue
