### ISSUE TITLE
Polygon fee weirdness

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6411]
### Overview

When doing a polygon trade, it says there is not enough Matic for fees but when you check the amount for fees and the balance of matic, there is enough to cover it .

### References and additional details

User screenshot:
![image](https://github.com/shapeshift/web/assets/100157997/6702301a-f855-4edb-9cc3-b97180f7b89f)
My testing wallet screen recording"
https://github.com/shapeshift/web/assets/100157997/a5168043-1d00-4501-be2f-8f3546a4dbd4

### Acceptance Criteria

Should be able to trade with polygon when enough matic for fees is in the wallet

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria There are two issues here:

1. The one on the user screenshot i.e Hop Li.Fi bridges showing a not enough MATIC for gas error despite no fees being payable in MATIC
2. The one on the screen recording i.e Polygon chain <-> Polygon chain swaps showing a not enough MATIC for gas despite having enough native fee for gas 

I wasn't able to repro the former - FYI, hop doesn't charge *payable* fees on the destination chain but only on the source chain (gas fees + some deduction on the received amount on the destination chain, but no payable fees there).
Tested with a frame-injected account with no MATIC on it at all:

<img width="495" alt="image" src="https://github.com/shapeshift/web/assets/17035424/ca698edf-c2e1-407b-a2dc-9cf7f5992013">
<img width="442" alt="image" src="https://github.com/shapeshift/web/assets/17035424/97632857-92f5-46ca-afd9-e52c5cdd77e8">

Note we've had some recent changes recently re: payable fees (https://github.com/shapeshift/web/pull/6455). I've went back in time to the commit right before those changes, however I still can't repro:

<img width="485" alt="image" src="https://github.com/shapeshift/web/assets/17035424/620b95bc-6330-434b-ba70-4fe0fcfb1069">

Tested with USDC specifically as a sanity check as there could be something off with those quotes but couldn't repro either:

 
<img width="489" alt="image" src="https://github.com/shapeshift/web/assets/17035424/be112d46-8622-477c-903c-1302c4904159">


As for the L1 <-> L1 issue in your screen recording, I wasn't able to try and repro as the fees endpoint is currently down on all envs:

<img width="377" alt="image" src="https://github.com/shapeshift/web/assets/17035424/a2ea4f89-4697-4ae7-b085-732452a5a9db">

**Comment by gomesalexandre** [comment]
Moved to block as Polygon fees endpoint is currently down - to be reopened when happy again

**Comment by gomesalexandre** [comment]
@MBMaria closing this as fixed, I was able to retest both flows here as the Polygon node is currently happy with fees estimation this morning:

1. Hop bridge

<img width="555" alt="image" src="https://github.com/shapeshift/web/assets/17035424/f5bae472-f641-4dc5-939d-2b5213530234">
<img width="589" alt="image" src="https://github.com/shapeshift/web/assets/17035424/3f8d72fa-c929-433d-9c0d-8244be4233dc">

2. Polygon <-> Polygon swaps

Note enough MATIC for gas

<img width="499" alt="image" src="https://github.com/shapeshift/web/assets/17035424/0ab15b99-3cac-4e6c-846f-1a3d9c2dc4c8">
<img width="577" alt="image" src="https://github.com/shapeshift/web/assets/17035424/8e93044a-6a50-430e-9518-cabf75913e6c">
<img width="544" alt="image" src="https://github.com/shapeshift/web/assets/17035424/ea33f0e5-963d-4626-a55f-69336ba6f0ad">

<img width="540" alt="image" src="https://github.com/shapeshift/web/assets/17035424/13be2a51-d0f9-4971-8646-c642bf2dc2e8">
<img width="545" alt="image" src="https://github.com/shapeshift/web/assets/17035424/21f88535-5c05-43e3-941e-54621744ff7c">
<img width="529" alt="image" src="https://github.com/shapeshift/web/assets/17035424/198e7d37-ce0f-410e-a9f4-adeb4a118d80">
