### ISSUE TITLE
[ALPHA] V2 Native Wallet BTC Balance History 1Y and ALL charts incorrect

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#642]
Triage Ticket Discord Link -https://discord.com/channels/554694662431178782/873244924026449940/928753439515746324

Explanation: When going to dashboard and BTC asset balance pages, it displaces balances over time incorrectly. The wallet was created in early November and there are balances being displayed from previous to that time. 

Recreation Steps: 
1) go to app.shapeshift.com
2) Connect a ShapeShift Native Wallet with BTC Balance
3 )go to the BTC asset balance page and click the  Balance button and navigate to the 1y/ALL tabs. Observe that the balances are off.

![btc native balance alltime 01062022](https://user-images.githubusercontent.com/94986227/148452779-bcb7c890-2a01-4e8a-afc1-8539e16061bb.png)
![btc native balance 1y 01062022](https://user-images.githubusercontent.com/94986227/148452783-370405aa-9ac1-4156-9675-ffa18bec4efd.png)

Attached screen shots show balances prior to November 2021, when the wallet was created.

**Comment by notatooyou** [comment]
Are the 1H, 1D, 1W, and 1M charts correct? Just 1Y and All that is off?

**Comment by SS-FOX-McCloud** [comment]
For any wallet with a BTC balance, the balance charts will all be incorrect before the time the wallet initially received the BTC regardless of timeframe selected.  Will bring this up in Standup tomorrow.

**Comment by 0xean** [comment]
Closing as resolved.
