### ISSUE TITLE
Mobile UX Rework

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#6432]
### Overview

Going to spend some time giving mobile some UX love.

- [x] #6433 
- [x] #6434 
- [x] #6437 
- [x] #6496 
- [ ] #6435 
- [x] #6436 
- [x] #6438 
- [x] #6439 
- [ ] #6440 
- [x] #6555

**Comment by twblack88** [comment]
Also need to capture filtering the assets on the markets page. 

As a user i don't need to see USDC on multiple chains etc.
