### ISSUE TITLE
Turn asset search modal into a stand alone page.

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#6435]
### Overview

On mobile we will want the asset search modal to also be its own main nav item. This will allows users to search for specific assets they want from anywhere in the app.

### References and additional details

Use the revamped asset search modal that is going to be introduced and put it on its own page.

### Acceptance Criteria

A new page is created for searching for assets.

### Screenshots/Mockups

![Screenshot 2024-03-13 at 10 47 59 AM](https://github.com/shapeshift/web/assets/89934888/93442dc6-c18a-4217-8f96-362264c4f824)

**Comment by gomesalexandre** [comment]
@reallybeard now that the assets page is a markets page, do we still want this?

**Comment by reallybeard** [comment]
> @reallybeard now that the assets page is a markets page, do we still want this?

Its going to be handled a little differently on mobile. 

https://www.figma.com/proto/Ikx1qWAFxlL4TqRmhzkgqI/Mobile-UX?type=design&node-id=733-2505&t=WTALDIxAR8wMqaXn-0&scaling=scale-down&page-id=1%3A250&starting-point-node-id=733%3A2505&show-proto-sidebar=1

From home if you click see more, thats basically the markets page.

Search is either going to be the global search, or just the asset search.
