### ISSUE TITLE
SPIKE: Cosmos Staking Module

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#644]
Staking abstraction module? (similar enough to support both cosmos chains and yearn?, separate implementations?). Provides logic to build a delegate/undelegate/etc transaction in the same way buildSendTransaction works in ChainAdapters. These payloads are then passed to signTx in ChainAdapters.

Single sided staking abstraction?
Look at Yearn and other single sided use cases and see if it is worthwhile. Could Single sided handle Yearn, Fox Farming, and Cosmos? Less web code and complexity.

https://twitter.com/joey__santoro/status/1478489634300588032

Acceptance Criteria:
Create the API specification for how the web front end would call this module. The spec should be able to handle single-sided staking for cosmos, yearn, and FOXy. Something similar to this for unchained. But it shouldn't be a .ts file, can just be markdown: https://github.com/shapeshift/lib/blob/main/packages/chain-adapters/src/api.ts

Consider this only at the lib layer, unchained will handle a lot of the abstraction. Work with Adam on what belongs where exactly.

**Comment by cjthompson** [comment]
Vault/Validator
1. Does an asset support staking / vaults?
2. Find out if they are staked and what their staked balance / unstaking in progress balance/time
3. - Per ASSET, not per account
4. Get APR for each staking opportunity
5. Get transaction / gas fee 
6. Does the staking opportunity have an unbonding period (typically in days)
7. Stake / Unstake
8. Available balance in terms of the crypto asset (plus fiat value)
9. Destination / Address (validator / vault) - display name / address
10. Get Available Destinations
11. Sign / Broadcast / get TXID
12. Typed Errors
13. Rewards - 
      - claimable Pending Rewards - show claim button
      - auto-compounding rewards / rebasing - don't show rewards at all?
14. Unstaking
      - sometimes unstaking will claim your rewards
15. Does the opportunity require approval / is it already approved?

Lending
1. Supply / Borrow
2. Various protocols (compound, rari, etc)
3. Supply - enable as collateral (not all protocols support this)
4. Rewards in "n" assets (1 or 2 usually) - not necessarily the same asset
     - APR (per asset, blended?)

Affiliate revenue ?

**Comment by cjthompson** [comment]
```ts
import BigNumber from 'bignumber.js'

export interface SingleSidedStakingOpportunity {
  id: string
  displayName: string
  displayIcon?: string // URL?
  assetId: string // CAIP19
  address: string
  apr: BigNumber // where 1 = 100%
  commission: BigNumber // 0-1 where 1 = 100%
  tvl: BigNumber // current balance of the vault/validator
  deposit: (amount: BigNumber) => Promise<unknown>
}

export interface SingleSidedStakingPosition {
  id: string
  opportunityId: string
  apr: BigNumber // where 1 = 100%
  assetId: string // CAIP19
  balance: {
    crypto: BigNumber
    fiat: BigNumber // USD?
  }
  createdAt: Date
  costBasis: BigNumber // crypto amount
  findPendingRewards: () => Promise<SingleSidedStakingReward[]>
  deposit: (amount: BigNumber) => Promise<unknown>
  withdraw: (amount: BigNumber) => Promise<unknown>
}

export interface SingleSidedStakingReward {
  positionId: string
  balance: {
    claimable?: BigNumber
    unclaimable?: BigNumber
    lifetime?: BigNumber
  }
  assetId: string // CAIP10
  claim: () => Promise<unknown>
}

export interface SingleSidedStaking {
  findActivePositions: () => Promise<SingleSidedStakingPosition[]>
  findOpportunities: () => Promise<SingleSidedStakingOpportunity[]>
}
```

**Comment by 0xean** [comment]
closing per @asamere based on web architecture conversations from ~2/18
