### ISSUE TITLE
SPIKE: Data Hub figment for production solution?

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#645]
We are currently using datahub.figment.io Cosmos cloud nodes.  Will this solution work going forwards?

Connect with Conscience- he has best insight

Also, chat with Marley about custom dedicated node.  Could he host for Osmosis specifically?

Do we want to use GRPC if possible?

Currently GRPC is not supported for Osmosis

A/C:
Create issues necessary to enable app to connect to cosmos/osmosis nodes

**Comment by asamere** [comment]
Reached out to figment on Discord:
```
Yash - Figment — 01/09/2022
@wegfox @adamfox I've to check with our team for the availability of gRPC endpoint on these networks. I'll keep you posted
```

https://discord.com/channels/741351331222126663/741354053736333333/929940610255847454

**Comment by asamere** [comment]
Reached out to Yash again:

https://discord.com/channels/741351331222126663/741354053736333333/936670858238373888

**Comment by asamere** [comment]
Response from Yash:
https://discord.com/channels/741351331222126663/741354053736333333/936672562153398392

"hey @adamfox sorry for the delay in getting back, I missed it. currently there're no such plans of having gRPC on Osmosis & Secret very soon"

**Comment by 0xean** [comment]
figment doesn't support gRPC so will leverage unchained nodes.
