### ISSUE TITLE
Halfway Sym deposit UX and tx update.

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#6456]
Users could get bored or stop halfway through a symmetric deposit. We need to track that state and push to the Tx history. It gets hairy with Thorchain states and the way we look.

UI with @reallybeard 

- [ ] state for showing an incomplete LP deposit on table. E.g., A user deposits the first asset into  a pool (symmetrically) but they don't finish the second asset. We need to detect the incomplete deposit (info below) and then show it as incomplete to the user. The "your pools" table is one place, a row or tag for incomplete . We could also display info for incomplete on the route (button in top corner, trigger a toast etc. etc.) 
- [ ] warning to see incomplete LP position. A little fuzzier but like another way to route to completing.
- [ ] option to continue or withdraw. E.g., a user clicks on the warning or "incomplete deposit"  button. They come back to the UI and see the first part of their deposit complete and then the button to click finish the rest of their position.
- [ ] incompatible. E.g.,  they deposited into a pool asymmetrically with Rune and come back to symmetrically deposit. If we don't already check for this, more info text is probably best. The add liquidity modal on thei position should just not work but we should grey it out and explain "if you want to add liquidity here with two assets you will need to symettrcially deposit. Naviaget back to the pools page, choose your pool, and select add liquidity." 

![Screenshot 2024-03-14 at 12 15 40 PM](https://github.com/shapeshift/web/assets/8991325/0a354cee-3b72-4470-9c34-52c6ae0d079b)

States notes
- [ ] on Thorchain `member` indexer Detect `assetAddress` and `runePending` so we can detect the differences. if we don't have one of the sides deposited we can push that to the slice.
- [ ] pending tx in the drawer (needs it's own parsing so likely another ticket)

**Comment by purelycrickets** [comment]
![Vqi0wC-1dEnTGS410rXaiKpaGW5KUrzEBZPtD_jPyWOKsooVQtWZ5hZlJWuAvmuA4c22V4WGjjlDGKKhE6p4JWKXzHKt5CS4tvnKDGdNuTsEpkQr7Ual0LpMWkEH1yFIzCqzC_Do](https://github.com/shapeshift/web/assets/94998097/7f78972f-661b-4ed7-92b7-f0be67da5add)
