### ISSUE TITLE
Cosmos: KeepKey Firmware

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#646]
As a user, I want to be able to use Cosmos and Osmosis on  KeepKey. As platform admins, we want to limit Wallet functionality for Cosmos and Osmosis to wallets that support [Asset].

Make corresponding HD wallet KK changes

A/C:
Users can send, receive, stake (delegate), unstake (undelegate), and get reward on KeepKey

**Comment by 0xdef1cafe** [comment]
@SS-FOX-McCloud can you please close and reopen under https://github.com/shapeshift/hdwallet/issues

**Comment by 0xdef1cafe** [comment]
captured under hdwallet https://github.com/shapeshift/hdwallet/issues/414
