### ISSUE TITLE
LiFi trades failing, seemingly after new approvals

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#6485]
### Overview

Currently in production when a user attempts a trade requiring a new approval of a token trade through LiFi, the trade after the approval action errors and the user gets a 'Something went wrong' error message. 

### References and additional details

USDC.BNB>BNB.BNB on native wallet: 
https://github.com/shapeshift/web/assets/94998097/eac3b80f-9c5c-412b-8290-f3c749d08ffc

USDC.OP>USDT.OP on native wallet: 

https://github.com/shapeshift/web/assets/94998097/8acb9368-151c-493e-85c8-8e8f13882a0d

Error from network tab: https://api.optimism.shapeshift.com/api/v1/gas/estimate?data=0x4630a0d8b2d3bf74627583b8a3bc308e8e66cec1e4519816befc8668b8b314daac654b7300000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000009a56d3d1a6631376cc0c5dc45a1453ea0287a9380000000000000000000000000000000000000000000000000000000002f51bf30000000000000000000000000000000000000000000000000000000000000160000000000000000000000000000000000000000000000000000000000000000a7368617065736869667400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002a307830303030303030303030303030303030303030303030303030303030303030303030303030303030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000bd6c7b0d2f68c2b7805d88388319cfb6ecb50ea9000000000000000000000000bd6c7b0d2f68c2b7805d88388319cfb6ecb50ea90000000000000000000000000b2c639c533813f4aa9d7837caf62653d097ff850000000000000000000000000b2c639c533813f4aa9d7837caf62653d097ff850000000000000000000000000000000000000000000000000000000002f8b7ef00000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000084eedd56e10000000000000000000000000b2c639c533813f4aa9d7837caf62653d097ff850000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000090a48d5cf7343b08da12e067680b4c6dbfe551be00000000000000000000000000000000000000000000000000000000000000000000000000000000ca423977156bb05b13a2ba3b76bc5419e2fe9680000000000000000000000000ca423977156bb05b13a2ba3b76bc5419e2fe96800000000000000000000000000b2c639c533813f4aa9d7837caf62653d097ff8500000000000000000000000094b008aa00579c1307b0ef2c499ad98a8ce58e580000000000000000000000000000000000000000000000000000000002f8b7ef00000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000bc83bd37f900010b2c639c533813f4aa9d7837caf62653d097ff8500070402f8b7ef0402f8e9eb0147ae0001926faafce6148884cd5cf98cd1878f865e8911bf000000011231deb6f5749ef6ce6943a275a1d3e7486f4eae59725ade03010204001f0101010203ff00000000000000000000000000000000000000000050a39b94b1dc8472faa08c36a3ef5b0a01c5bd100b2c639c533813f4aa9d7837caf62653d097ff8594b008aa00579c1307b0ef2c499ad98a8ce58e580000000000000000&from=0x9a56D3d1A6631376cC0c5DC45A1453eA0287a938&to=0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE&value=0

USDT.OP>USDC.OP on KeepKey: 

https://github.com/shapeshift/web/assets/94998097/c00962a5-064a-4b9f-927a-21555bee50d2

### Acceptance Criteria

Users are able to perform LiFi trades successfully regardless of wallet or asset pair.

**Comment by purelycrickets** [comment]
This also may be intermittent/non-deterministic as @MBMaria and I have both had transactions fail where we don'r need approvals either.

**Comment by purelycrickets** [comment]
This was also confirmed in Prod (videos say release) to assure it was not a release blocker. More recreations can be uploaded if requested.

**Comment by woodenfurniture** [comment]
This is actually unrelated to approvals and affects ERC20 trades due to an error estimating gas. Trades from native assets seem unaffected.

Looks to be unrelated to any changes on our side. I've contacted lifi for assistance:
https://discord.com/channels/554694662431178782/1080826012784414720/1220228291235938336
