### ISSUE TITLE
KK unable to sign transactions through specific wallet connect dapps

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#6488]
### Overview

Currently there are a few dapps when connected via wallet connect to a KeepKey connected to app.shapeshift.com.  I have a user currently affected in support unable to KeepKey wallet connect to eigenlayer or ether.fi. 

Support was able to make successful Wallet Connected dapp transaction's with a KeepKey so this appears to only affect certain dapps. 

### References and additional details

User captured video of the issue here: https://www.youtube.com/watch?v=6_b_qM1kNpY

inject.js:1 Port connected
errors.ts:117 Uncaught (in promise) TypeError: unknown ProviderEvent (argument="event", value="accountsChanged", code=INVALID_ARGUMENT, version=6.11.1)
    at f (errors.ts:117:21)
    at i (errors.ts:143:15)
    at b (errors.ts:154:5)
    at Bc (abstract-provider.ts:151:5)
    at qr.fr (abstract-provider.ts:1035:36)
    at qr.removeAllListeners (abstract-provider.ts:1146:50)
    at Connect.tsx:64:24
    at Connect.tsx:60:26
    at Object.Le (react-dom.production.min.js:54:317)
    at Ue (react-dom.production.min.js:54:471)
f @ errors.ts:117
i @ errors.ts:143
b @ errors.ts:154
Bc @ abstract-provider.ts:151
fr @ abstract-provider.ts:1035
removeAllListeners @ abstract-provider.ts:1146
(anonymous) @ Connect.tsx:64
(anonymous) @ Connect.tsx:60
Le @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Dr @ react-dom.production.min.js:105
zr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
ss @ react-dom.production.min.js:274
Re @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Kt @ react-dom.production.min.js:74
Qt @ react-dom.production.min.js:73
await in Qt (async)
(anonymous) @ Connect.tsx:64
(anonymous) @ Connect.tsx:60
Le @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Dr @ react-dom.production.min.js:105
zr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
ss @ react-dom.production.min.js:274
Re @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Kt @ react-dom.production.min.js:74
Qt @ react-dom.production.min.js:73
Show 28 more frames
Show less
errors.ts:117 Uncaught (in promise) TypeError: unknown ProviderEvent (argument="event", value="chainChanged", code=INVALID_ARGUMENT, version=6.11.1)
    at f (errors.ts:117:21)
    at i (errors.ts:143:15)
    at b (errors.ts:154:5)
    at Bc (abstract-provider.ts:151:5)
    at qr.fr (abstract-provider.ts:1035:36)
    at qr.removeAllListeners (abstract-provider.ts:1146:50)
    at Connect.tsx:65:24
    at Connect.tsx:60:26
    at Object.Le (react-dom.production.min.js:54:317)
    at Ue (react-dom.production.min.js:54:471)
f @ errors.ts:117
i @ errors.ts:143
b @ errors.ts:154
Bc @ abstract-provider.ts:151
fr @ abstract-provider.ts:1035
removeAllListeners @ abstract-provider.ts:1146
(anonymous) @ Connect.tsx:65
(anonymous) @ Connect.tsx:60
Le @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Dr @ react-dom.production.min.js:105
zr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
ss @ react-dom.production.min.js:274
Re @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Kt @ react-dom.production.min.js:74
Qt @ react-dom.production.min.js:73
await in Qt (async)
(anonymous) @ Connect.tsx:65
(anonymous) @ Connect.tsx:60
Le @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Dr @ react-dom.production.min.js:105
zr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
ss @ react-dom.production.min.js:274
Re @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Kt @ react-dom.production.min.js:74
Qt @ react-dom.production.min.js:73
Show 28 more frames
Show less
setupKeepKeySdk.ts:27 
 
 
       GET http://localhost:1646/auth/pair net::ERR_CONNECTION_REFUSED
fetchApi @ runtime.js:84
request @ runtime.js:136
await in request (async)
verifyRaw @ AuthApi.js:85
verify @ AuthApi.js:97
create @ index.js:68
s @ setupKeepKeySdk.ts:27
(anonymous) @ Connect.tsx:67
(anonymous) @ Connect.tsx:60
Le @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Dr @ react-dom.production.min.js:105
zr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
ss @ react-dom.production.min.js:274
Re @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Kt @ react-dom.production.min.js:74
Qt @ react-dom.production.min.js:73
Show 16 more frames
Show less
setupKeepKeySdk.ts:27 verify failed FetchError: The request failed and the interceptors did not return an alternative response
    at s.fetchApi (runtime.js:100:31)
    at async s.request (runtime.js:136:15)
    at async s.verifyRaw (AuthApi.js:85:15)
    at async s.verify (AuthApi.js:97:15)
    at async c.create (index.js:80:9)
    at async s (setupKeepKeySdk.ts:27:11)
    at async Connect.tsx:67:15
    at async Connect.tsx:60:11
(anonymous) @ index.js:77
Promise.then (async)
create @ index.js:68
s @ setupKeepKeySdk.ts:27
(anonymous) @ Connect.tsx:67
(anonymous) @ Connect.tsx:60
Le @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Dr @ react-dom.production.min.js:105
zr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
ss @ react-dom.production.min.js:274
Re @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Kt @ react-dom.production.min.js:74
Qt @ react-dom.production.min.js:73
Show 13 more frames
Show less
setupKeepKeySdk.ts:27 
 
 
       POST http://localhost:1646/auth/pair net::ERR_CONNECTION_REFUSED
fetchApi @ runtime.js:84
request @ runtime.js:136
await in request (async)
pairRaw @ AuthApi.js:56
pair @ AuthApi.js:69
create @ index.js:85
await in create (async)
s @ setupKeepKeySdk.ts:27
(anonymous) @ Connect.tsx:67
(anonymous) @ Connect.tsx:60
Le @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Dr @ react-dom.production.min.js:105
zr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
ss @ react-dom.production.min.js:274
Re @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Kt @ react-dom.production.min.js:74
Qt @ react-dom.production.min.js:73
Show 16 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
foxy.ts:53 FoxyMarketService(findByAssetId): Failed to find by AssetId
findByAssetId @ foxy.ts:53
(anonymous) @ market-service-manager.ts:89
await in (anonymous) (async)
findByAssetId @ market-service-manager.ts:85
(anonymous) @ marketDataSlice.tsx:174
queryFn @ marketDataSlice.tsx:172
(anonymous) @ apiState.ts:804
(anonymous) @ apiState.ts:23
(anonymous) @ apiState.ts:4
(anonymous) @ apiState.ts:85
k @ apiState.ts:67
f @ apiState.ts:768
(anonymous) @ index.ts:1237
(anonymous) @ index.ts:38
(anonymous) @ index.ts:19
(anonymous) @ index.ts:87
S @ index.ts:69
(anonymous) @ index.ts:1210
Object.assign.pending @ index.ts:1209
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ apiState.ts:592
(anonymous) @ index.js:16
queryFn @ AppContext.tsx:204
fetchFn @ query.ts:175
g @ retryer.ts:83
l @ retryer.ts:116
fetch @ query.ts:218
U @ queryObserver.ts:168
setOptions @ queryObserver.ts:105
(anonymous) @ useBaseQuery.ts:44
rl @ react-dom.production.min.js:244
ks @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 29 more frames
Show less
index.ts:13 
 
 
       GET https://verify.walletconnect.com/attestation/7f5b56ac48241760dac26331fccef67211d3d493e126b7cdc0c4563fe00ac7ea 404 (Not Found)
fetchAttestation @ index.ts:13
resolve @ index.ts:13
At.getVerifyContext @ tslib.es6.js:217
At.onSessionProposeRequest @ tslib.es6.js:217
await in At.onSessionProposeRequest (async)
At.processRequest @ tslib.es6.js:217
At.processRequestsQueue @ tslib.es6.js:217
At.onRelayEventRequest @ tslib.es6.js:217
(anonymous) @ tslib.es6.js:217
await in (anonymous) (async)
d.emit @ events.js:158
onMessageEvent @ index.ts:13
await in onMessageEvent (async)
onProviderPayload @ index.ts:13
await in onProviderPayload (async)
onPayloadHandler @ index.ts:13
d.emit @ events.js:153
onPayload @ provider.ts:64
(anonymous) @ provider.ts:101
d.emit @ events.js:153
onPayload @ index.ts:13
e.onmessage @ index.ts:13
Show 9 more frames
Show less
index.ts:13 
 
 
       GET https://verify.walletconnect.com/attestation/2c84a97d3d7bc0d99afe8d0b9df4b51815e9adba328d4b949892f369314404cb 404 (Not Found)
fetchAttestation @ index.ts:13
resolve @ index.ts:13
At.getVerifyContext @ tslib.es6.js:217
At.onSessionRequest @ tslib.es6.js:217
At.processRequest @ tslib.es6.js:217
At.processRequestsQueue @ tslib.es6.js:217
At.onRelayEventRequest @ tslib.es6.js:217
(anonymous) @ tslib.es6.js:217
await in (anonymous) (async)
d.emit @ events.js:158
onMessageEvent @ index.ts:13
await in onMessageEvent (async)
onProviderPayload @ index.ts:13
await in onProviderPayload (async)
onPayloadHandler @ index.ts:13
d.emit @ events.js:153
onPayload @ provider.ts:64
(anonymous) @ provider.ts:101
d.emit @ events.js:153
onPayload @ index.ts:13
e.onmessage @ index.ts:13
Show 9 more frames
Show less

### Acceptance Criteria

KeepKey users connected to ShapeShift are able to use the Wallet Connect connect to dapp function successfully.  Currently Eigenlayer and ether.fi seem to be having the same errors captured by the user.

**Comment by gomesalexandre** [comment]
Note this isn't exclusive to KK, native is also affected
