### ISSUE TITLE
Cosmos: Send

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#651]
Use same backend as Send for other assets beside memo field (https://github.com/shapeshift/web/issues/652)

Below is the Send flow expanded but additional work (besides memo) should not be necessary.

A/C: User can send Cosmos/Osmosis same as other assets

3. **Send ([Mockup](https://projects.invisionapp.com/share/TX127TESW3GS#/screens/462779458))**
    
    *As a user I want to send Cosmos and Osmosis [Cosmos SDK assets].*  
    
    1. On the Cosmos and Osmosis asset pages, users can click 'Send' to open the send modal
    2. Users can paste a Cosmos or Osmosis address as the recipient or scan a QR code ([Mockup](https://projects.invisionapp.com/share/TX127TESW3GS#/screens/462779457))
        1. If address is invalid, user experiences the error state where the Next button turns red, disables, and displays “Invalid Address”
    
    2. Users can input an amount to send in crypto or fiat ([Mockup](https://projects.invisionapp.com/share/TX127TESW3GS#/screens/462779456))
    
    1. If amount exceeds user's balance, they see an error message and continue button is disabled
    2. if user inputs in fiat, the crypto amount is populated
    3. if user inputs in crypto, the fiat amount is populated
    
    1. Users can click ‘Max’ to input their full balance minus tx fee
        1. If a user clicks Max, their full balance minus the estimated tx fee is input
    2. Users can optionally include a "Memo" field. 
        1. If user inputs an invalid memo due to special characters the field turns red, the user experiences an error state where the Next button turns red, disables, and displays "Invalid Memo.”
        2. A character counter is displayed. If a user exceeds the character count, the field turns red, the Next button is disabled, and user sees error message "Character Limit Exceeded.”
        3. Tooltip: Some ATOM recipients may require a memo in order for the transaction to be processed correctly
        4. Web Ticket
        5. Edit Gas Fee
            1. note: be better than Keplr in estimating/over-estimating (@Beard ShapeShift @Diggy mockup plz)
        
        Implementation notes: ([Mockup](https://projects.invisionapp.com/share/TX127TESW3GS#/screens/462779459))
        
        1. [https://github.com/shapeshift/web/issues/](https://github.com/shapeshift/web/issues/561)[relevant-issue] Ask engineers who break this down to link to each relevant github issue in the spec doc link this Link to github issues #1
        2. Add abstraction to send flow to handle whether or not a chain supports Memos
    
    5. User can click ‘Next’ to select their transaction speed and confirm the details of their transaction before executing. ([Mockup](https://projects.invisionapp.com/share/TX127TESW3GS#/screens/462779459))
    
    1. Confirm screen displays the following:
        1. amount in crypto and fiat the user is sending
        2. address the user is sending to
        3. Memo ([Mockup](https://projects.invisionapp.com/share/TX127TESW3GS#/screens/462779472))
            1. If no memo attached, field is left blank
        4. Slow, Average, and Fast fees based on network conditions
        5. Value of the fees in both crypto and fiat
        6. Total value of the tx including the selected fee in both crypto and fiat
    2. If a user has enough funds to cover the selected fee, the ‘Confirm’ button is activated
    3. If a user does not have enough funds to cover the selected fee, the ‘Confirm’ button turns red, disables, and displays “Insufficient Balance.”
    1. When a user clicks confirm, they are prompted to sign the tx on their connected wallet
        1. “Confirm” button goes into a “Confirm on Wallet” pending state (right now it says “Broadcasting Transaction” but we should fix this) until tx is signed and broadcasted
    2. After a user confirms a tx on their wallet, the transaction is broadcasted
        1. If tx is broadcasted successfully, user sees a success screen with a link to view on the Cosmos or Osmosis block explorer
        2. If tx is not broadcast successfully, user sees a toast message, “Error sending. Try again.”, and the button goes back to the active “Confirm” state
        3. If user rejects tx on their wallet, the ‘Confirm’ button goes back to the active “Confirm” state and user sees a toast message, “Transaction Rejected”
    
    Miscellaneous:
    
    1. If at any point during the Send flow a user’s wallet is disconnected, the CTA turns into a “Connect Wallet” button - Is this relevant yet? Or if you disconnect keepkey does it take you back to dashboard?
        1. 0xdef1cafe and majorhayes have context on this

**Comment by gomesalexandre** [comment]
@SS-FOX-McCloud Can we reword the acceptation criteria to state this is only for Cosmos and not Osmosis? It will make it clear to anyone reviewing that there is no Osmosis functionality expected from the PRs linked to this issue.
