### ISSUE TITLE
Show mobile menu button on all tabs

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#6519]
### Overview

On mobile, we currently only show the menu button (which is the only way to access THORChain Lending and LP) when the Trade tab is active.

It's hidden/not visible otherwise, which is confusing for users.

### References and additional details

![image](https://github.com/shapeshift/web/assets/97164662/9bbcde2b-d953-4f9f-8258-5ebe3f754384)

### Acceptance Criteria

Users should be able to access the menu from any tab on mobile.

**Comment by 0xean** [comment]
@reallybeard - can you tackle this?

**Comment by reallybeard** [comment]
> @reallybeard - can you tackle this?

this will be fixed in the new mobile UX improvements

**Comment by 0xean** [comment]
closing in pref of #6438 

thank you @reallybeard !
