### ISSUE TITLE
Add more granular feature flags

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#6520]
### Overview

Sometimes we want to disable certain features for user safety.
However, our current feature flags are rather course. For example, setting `REACT_APP_FEATURE_THORCHAIN_LP` to `false` will disable the entire LP route, which prevents users from seeing their current positions/balances.

We should improve the granularity with which we can disable features such that we only disable the critical, exposed part of the feature set (usually executing transactions).

### References and additional details

<img width="1198" alt="Screenshot 2024-03-21 at 11 21 36 AM" src="https://github.com/shapeshift/web/assets/97164662/49a1a8b6-bde4-4f56-94ed-4901292fe5fc">

### Acceptance Criteria

- Determine the places it makes sense to add more granular flags
- Implement them

**Comment by gomesalexandre** [comment]
Closed by https://github.com/shapeshift/web/pull/6535
