### ISSUE TITLE
X (close) on wallet connect modal a dead click when switching wallet providers

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#6530]
### Overview

Currently in production, when a user goes to switch wallet providers to Wallet Connect from having another wallet connected, the Close X is a dead click.  The user must click outside of the modal if they would like to close the screen. 

This is not the case when trying to close the modal if Wallet Connect is the first wallet to connect. 

### References and additional details

Recreation steps: 
1. Connect a non-wallet connect wallet to app.shapeshift.com
2. Select 'switch wallet providers'
3. Select Wallet Connect as the wallet option
4. try to close the window by clicking the X
5. Witness dead click

Video of dead click:
https://github.com/shapeshift/web/assets/94998097/073f5e75-553e-4a81-a890-ff91ed8a657b

### Acceptance Criteria

Wallet connect close button is functional when clicked.

**Comment by gomesalexandre** [comment]
@purelycrickets is this still happening for you? Can't repro on upstream nor local develop


https://github.com/shapeshift/web/assets/17035424/5e78f857-b7fd-4a86-99a1-4959f5af9e27

**Comment by purelycrickets** [comment]
unable to reproduce this issue any longer. good to close. thanks @gomesalexandre
