### ISSUE TITLE
0x trade giving "makeSwapperAxiosServiceMonadic" error

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6539]
### Overview

When attempting a trade of STBU to USDT on Ethereum using 0x, it gives the error message: makeSwapperAxiosServiceMonadic

### References and additional details

https://github.com/shapeshift/web/assets/100157997/fe282558-ee6c-4c5c-9402-4e2952e1516e

### Acceptance Criteria

Should be able to trade STBU to USDT

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria I've cut a monkey patched build skipping 0x validation on gome for this guy, unfortunately this is an issue for this specific pool and while this will make the validation work, the Tx will still revert on-chain for the exact same reason.

https://www.tdly.co/shared/simulation/a521f4eb-d230-467d-9ede-674303815981

See https://docs.0xprotocol.org/en/latest/basics/functions.html#registerallowedrfqorigins

> The RFQ order includes a txOrigin field, which a maker can use to restrict which EOA’s can submit the Ethereum transaction that fills their order. There are two ways a maker can use this field.

In order words, this pool is restricted in 0x and STBU cannot be traded so closing this at wontfix.
