### ISSUE TITLE
Lending Pool Health

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#6577]
### Overview

logic for pool health needs sanity check on TC lending . borrow assets will display as healthy even if the liquidity will cause massive slippage. 

So the concept of health is determinate on your behavior. We need to calculate the math of your entry and display health from your actions, alongside slippage. 

### References and additional details

Beard wants to investigate relative depth
see whatever you're borrowing to understand you're getting the amount you want. 

### Acceptance Criteria

- As a user i can see when my borrow isn't going to get close enough to my collateral ratio after slippage.

**Comment by 0xean** [comment]
![Screenshot 2024-04-01 at 6 16 41 PM](https://github.com/shapeshift/web/assets/15096737/149cae7f-b7d0-43f6-b86d-e1da79562f19)

- Currently lending pool health is hardcoded to be always green
- Pool Status vs Pool Health should be separated concepts
- @shapeshift/product - to determine naming convention and mock
- engineering will implement 3 tiers regardless of naming 
- consult TC / TS to see if existing reference implementation or terminology exists

**Comment by 0xean** [comment]
closing this ticket, we will create a separate ticket to remove the tag since we have user guards in the modal
