### ISSUE TITLE
Remove the slippage from LP

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#6579]
### Overview

If #6578 has a 5% warning value harcoded, we need to remove the ability to manage slippage. Other interfaces leave this but it....doesn't do anything. 

### References and additional details

We should turn this option on after significant user requests only and keep them safer with sane values. 

### Acceptance Criteria

- tooltip of what the slippage is set as
- get rid of the gearbox in the upper right on LP

### Screenshots/Mockups

![Screenshot 2024-03-26 at 2 07 09 PM](https://github.com/shapeshift/web/assets/8991325/7c642475-a50e-4628-82db-a733d709de7f)

**Comment by gomesalexandre** [comment]
Very nice catch @twblack88! Fun fact: this was a bug and didn't set any slippage for LP but rather for swapper:

<img width="1144" alt="image" src="https://github.com/shapeshift/web/assets/17035424/537d498c-0c74-414c-be69-85f4d52382df">

**Comment by gomesalexandre** [comment]
Very nice catch @twblack88! Fun fact: this was a bug and didn't set any slippage for LP but rather for swapper:

<img width="1301" alt="image" src="https://github.com/shapeshift/web/assets/17035424/84d5d02d-4300-4d9f-ae43-0b5f3fdc9d83">
