### ISSUE TITLE
Osmosis: Staking

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#66]
This project includes Osmosis staking user flows/designs

• Web
• Mobile

**Comment by DiggyDiggy2** [comment]
Osmosis Staking Mobile
Mobile prototype:  [(https://invis.io/R811O2E1TU4K)]
Sketch file:

**Comment by DiggyDiggy2** [comment]
User Flows
[Osmo_Staking_Mobile.pdf](https://github.com/shapeshift/web/files/7124208/Osmo_Staking_Mobile.pdf)

**Comment by 0xean** [comment]
@DiggyDiggy2 - can we move this over to the correct repo (looks like its the legacy app not v2)
