### ISSUE TITLE
Unable to view backup phrase on some android phones (operating system 11 or less, i think) 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6617]
### Overview

When trying to back up the pass phrase on older versions of android, the screen will not scroll down to enable you to reveal the words. 

### References and additional details

Try to back up passphrase on old android - note that you cannot scroll down. 
tested samsung s7 - android version 8
also user reported using realme 3 pro mobile - android version 11 
![image](https://github.com/shapeshift/web/assets/100157997/e9ec4f29-e69f-4b4d-a952-936aedc3e08c)

### Acceptance Criteria

Should be able to scroll and view passphrase 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Assigning to @reallybeard and his wizardry to find the one CSS rule for this in no time

**Comment by gomesalexandre** [comment]
@shapeshift/operations can we retest this on an actual Android device? It may or may not have been fixed, and as we're fixing wc dApps on mobile app, we've noticed the same issue there

**Comment by gomesalexandre** [comment]
Reopening for it to be retested - and closed if indeed fixed.

**Comment by 0xean** [comment]
on pixel 7 it works fine, checking a pixel 3

**Comment by 0xean** [comment]
pixel 3 also looks good.

**Comment by purelycrickets** [comment]
tested and not an issue with a Samsung galaxy.

**Comment by gomesalexandre** [comment]
Tested with Android Studio emulator:
- Pixel 3A / Android 14.0 and couldn't repro (obviously since that's a large enough screen)
- "Small phone" with v. small resolution / Android 11, same here, couldn't repro and was able to scroll just fine


https://github.com/shapeshift/web/assets/17035424/1adeafa7-8ac0-45e5-b002-9fffac7250b5

**Comment by gomesalexandre** [comment]
Reopening as this is still happening on desktop

**Comment by gomesalexandre** [comment]
Re-closing, you have to enable this guy while testing responsive on desktop, derp 
<img width="613" alt="image" src="https://github.com/shapeshift/web/assets/17035424/8917350d-d139-457e-b5ad-b0d040d5ad4c">
