### ISSUE TITLE
Cosmos: Stake Confirm

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#663]
Stake - Confirm (Mockup)

*As a user, I want to be able to confirm the details of my staking transaction before executing*

1. *Progress Column*
    
    *As a user, I want to know what steps are required to stake and which step I’m on*
    
    1. Step 1: Confirm Details with animated spinner
    2. Step 2: Broadcast TX
2. *Confirm Details*
    
    *As a user, I want to be able to confirm the details of my staking transaction before executing*
    
    1. The following details are displayed on the confirmation screen
        1. Stake: Amount being staked in both crypto and fiat
        2. Validator: Validator being delegated to (Default is ShapeShift; users will not be able to select in MVP; just support a default validator for each chain for now)
        3. Average APR: Current staking APR for the selected validator
            1. Validator commission is accounted for when calculating APR
        4. Gas Fee: Gas cost in both crypto and fiat
            1. User can select Low, Med, or High gas fee based on network conditions
        5. Estimated Yearly Rewards: Estimated rewards in crypto and fiat calculated by multiplying input amount by average APR
        6. Copy: While your tokens are staked you will not be able to transfer or spend them. It will take X days to unlock them after you unstake them.
            1. x = the number of days for the respective Cosmos SDK chain’s unbonding period
    2. Confirm & Broadcast
        1. If a user clicks “Confirm & Broadcast,” they are prompted to confirm the transaction on their wallet and the button displays a pending state with, “Confirm on Wallet”
        2. If tx is not broadcast successfully, the ‘Confirm & Broadcast’ button turns red and displays “Error staking. Try again.”
        3. If user rejects tx on their wallet, the ‘Confirm & Broadcast’ button goes back to the active “Confirm & Broadcast” state and user can try again
        4. If a user confirms the tx on their wallet their tx is broadcasted successfully and they are routed to the **Stake - Pending** step
            1. The Confirm Details icon turns into a Check icon
            2. The ‘Broadcast Tx’ step turns into an animate spinner
        
        f. Copy: While your tokens are staked you will not be able to transfer or spend them. It will take X days to unlock them after you unstake them.
        
        1. x = the number of days for the respective Cosmos SDK chain’s unbonding period

**Comment by gomesalexandre** [comment]
Reopening since broadcast should be done in the same issue.
