### ISSUE TITLE
Unresponsiveness during loads of large wallets

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6630]
### Overview

Some power users have reported unresponsive app states while loading their wallets. 

https://github.com/shapeshift/web/assets/15096737/13c26ea2-0973-48fc-a0d6-14a0a5443f9d

### References and additional details

1.  inject willywonka.eth
2. after pairing hard refresh while on the wallet route (command + shift + r)
3. attempt to click around during this process, can lead to unresponive state and sometime even the `Page Unresponsive` modal 

![image](https://github.com/shapeshift/web/assets/15096737/6776cb07-cab5-41a3-8d5d-f8c332f2e46e)

### Acceptance Criteria

- background loading doesn't make interface unresponsive when loading large wallets

**Comment by gomesalexandre** [comment]
Tackled in https://github.com/shapeshift/web/pull/6631 which seems to fix the bleed for now - keeping this open as this is very likely to happen again after a few days or weeks when the cache gets older and huge/r
