### ISSUE TITLE
Repayment Lock shows negative days for new borrow

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6641]
### Overview

When doing a new borrow, the repayment lock has a negative amount of days listed in the borrow modal

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/25e74ae1-318b-47f6-81c3-ea9a461d0340)

### Acceptance Criteria

Should say 0 days, or the current amount of days until repayment is unlocked

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by Vayras** [comment]
@MBMaria I'm looking to contribute towards this, can you tell me how do I do that?
