### ISSUE TITLE
Cosmos: Unstake Input

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#665]
**d. Unstake - Input ([Mockup](https://projects.invisionapp.com/share/WF1262ZUU2Q6#/screens/462326311))**

*As a user, I want to be able to input the amount of Cosmos or Osmos that I want to unstake.*

1. Unstake [Asset]
    1. Copy: It will take x days to unlock your [Asset] after you unstake. Staking rewards will need to withdrawn separately.
        1. x = the number of days for the respective Cosmos SDK chain’s unbonding period
    2. [Asset] Staking Balance: Amount in crypto of asset staked
    3. *Amount to Unstake:*
        1. Users can click the [Asset]/[Fiat] toggle to toggle input mode between crypto and fiat
        2. if user inputs in fiat, the crypto amount is populated
        3. if user inputs in crypto, the fiat amount is populated
    4. 25%/50%/75%/Max Toggle
        1. If a user selects a %, that % of their staked balance is input
        2. Default selection is Max
    5. Continue
        1. If no amount is input, the Continue button is disabled
        2. If the user has a valid amount input, the “Continue" button is active
        3. If the amount a user has input is greater than a user’s staked balance, the Continue button disables, turns red, and displays “Insufficient Funds”
        4. If the amount the user has input is less than their balance and the estimated fee & buffer, the Continue button is active 
        5. If a user clicks “Continue,” they are routed to the **Unstake - Confirm** step

**Comment by gomesalexandre** [comment]
Closed by #1070
