### ISSUE TITLE
[Spike] Ledger multi-account functionality 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6653]
1. why do we block user from adding additional accounts without TX history? Is this to help dumb dumbs from losing assets? if so, can we allow them to override?
![Screenshot 2024-04-09 at 3 07 52 PM](https://github.com/shapeshift/web/assets/15096737/9dfd41d8-7a41-4c26-b33b-bd5fea1c802c)

2. Can we offer an account selection screen similiar to Rabby for ledger uses (would be nice to allow this for all chains / UTXOs)
![Screenshot 2024-04-09 at 3 08 21 PM](https://github.com/shapeshift/web/assets/15096737/440fb8b3-9bb4-4871-8341-455e4257d514)

3. Currently when we add a new account on a ledger, it adds it for that specific EVM.... can we instead add it for all EVMs.  Said differently If an address is connected, we connect it for everything. 
![Screenshot 2024-04-09 at 3 11 47 PM](https://github.com/shapeshift/web/assets/15096737/f5d17507-669b-4987-9098-408fff086e39)

Product is working on mocks to allow the rabby like selector flow, engineering should do a little research so we are aware of any limitations ahead of this implementation. So this ticket is mainly just prep to be able to help inform product decisions before we move forward with implementation.

**Comment by 0xean** [comment]
existing product spec for reference

https://www.notion.so/shapeshift/Ledger-Improvements-d72c7d4c53564d26b4f45917cc65ff05

**Comment by gomesalexandre** [comment]
> 1. why do we block user from adding additional accounts without TX history? Is this to help dumb dumbs from losing assets? if so, can we allow them to override?

That one is an historical decision - we use this as heuristics to know when to stop fetching account, see https://github.com/shapeshift/web/pull/2702/files#diff-68fa73b2eac2fc2d43c7e89f845090ff6f7e55830383e855b59502c227702d9bR82

And matching selector:
https://github.com/shapeshift/web/blob/d3f42415bbc6cfb41fe8fb0425b741e04709bac6/src/state/slices/txHistorySlice/selectors.ts#L201-L208

The main reason for this was auto-discovery, so we had a way to short-circuit fetching the next account number. Though we can probably do a lot better here heuristics-wise.

> 2\. Can we offer an account selection screen similiar to Rabby for ledger uses (would be nice to allow this for all chains / UTXOs)

We absolutely could - not only for Ledger - and that's definitely interlinked to the above. *If* we have sane heuristics on the number of accounts we "discover", then we could do something similar. If we're only going to display the addresses without any e.g balance, then that would be straightforward and wouldn't be a performance bottleneck.
As soon as we want to display (hence fetch) balances in this screen, then we'll have to keep perf in mind and probably come up with heuristics (e.g pagination, fetch and display 0-5 first then allow users to load next).

> 3. Currently when we add a new account on a ledger, it adds it for that specific EVM.... can we instead add it for all EVMs.  Said differently If an address is connected, we connect it for everything.

Also not Ledger-specific, and the same current heuristics of only fetching accounts with activity (meaning stopping fetching accounts as soon as one has no Tx history). Accounts on diff. chains are entirely diff. entities and we have no notion of fetching the *same* account numbers for all EVM, this is decoupled.

I believe this would be a nice addition as well - it could be implemented relatively easily currently, though we probably want to wait and see whether or not we rip the current "Add Account" / automagical discovery of account numbers before doing so.

**Comment by 0xean** [comment]
thanks @gomesalexandre 

cc @twblack88 do you have enough info here to spec out the desired UX with mocks further and then we can take it back to engineer for implementation. Seems like there really isnt any technical blockers here, just old ways of doing things that we can invest the time into fixing

**Comment by twblack88** [comment]
Yeah we got the working draft [here](https://www.figma.com/file/VEKmwSuhnZVghkUl0VSvN2?node-id=1:250&locale=en&type=design) @reallybeard wanted to make into prototype quickly to communicate idea.
