### ISSUE TITLE
THORChain Lending - Approval step

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#6677]
### Overview

See https://github.com/shapeshift/web/pull/6676 - token repayments weren't implemented and have been wired up in that PR, but we need to check for allowance/add an approval step

 > Note this is an immediate "fix the bug and make this work" fix, and is to be directly follow-up on top of this stack with approvals handling - this will not work in and by itself without calling approve() first

### References and additional details

N/A

### Acceptance Criteria

- Approvals needed are handled for lending borrows (even though THOR doesn't support token borrows yet) i.e check allowance and approve first before continuing if needed
- Approvals needed are handled for lending repayments i.e check allowance and approve first before continuing if needed

**Comment by 0xean** [comment]
closing as stale.

**Comment by gomesalexandre** [comment]
Still standing for borrows - to be added as a PR stacked on top of https://github.com/shapeshift/web/pull/6753

**Comment by 0xean** [comment]
closing - lending goes bye.
