### ISSUE TITLE
THORChain Lending - Token collaterals

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#6678]
### Overview

See https://github.com/shapeshift/web/pull/6676:

> Note this is an immediate "fix the bug and make this work" fix, and is to be directly follow-up on top of this stack with handling tokens at borrow time too - which is currently unsupported, but we should be prepared for it as things will similarly fail there

### References and additional details

https://github.com/shapeshift/web/pull/6676

### Acceptance Criteria

- Using tokens as collateral is implemented using `depositWithExpiry()`

**Comment by twblack88** [comment]
looks fixed but not closed. and lending going bye bye
