### ISSUE TITLE
Add memos to all the things TC

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6679]
#### AC
- ensure that all thorchain related tx's have memos with our affiliate code (even if free) 
- all evm transactions that aren't depositWithExpiry
- goal is to be able to track all transactions and know they originated from our app 
- Monkey-patch lending memo to have an affiliate name (*without* an affiliate fee) until affiliate fees are supported upstream (i.e https://github.com/shapeshift/web/pull/5813)
- validate tc tx parsing doesn't break with all chains / tx types

**Comment by 0xean** [comment]
- be careful here, high risk prs...

**Comment by gomesalexandre** [comment]
Closing as lending was the last bit and it's hasta la vista
