### ISSUE TITLE
Thorchain LP : Assymetric withdraw from symmetric position

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6680]
#### AC
- ability to take a symmetric LP position and only receive a single asset back
- @shapeshift/product need for mock here

**Comment by reallybeard** [comment]
https://www.figma.com/design/hq8z2S8QwL2DciuGR8b0GR/Thorchain-LPs?node-id=812-8783&t=viWRGTlk18i5OgDn-0

**Comment by 0xean** [comment]
<img width="475" alt="Screenshot 2024-07-03 at 4 16 15 PM" src="https://github.com/shapeshift/web/assets/15096737/d35c2fdc-78cd-4152-b00d-2c18587bd66e">

Adding the ability to distinguish which asset is being withdrawn and the three buttons to select the asset out
