### ISSUE TITLE
Multi-account support - phase 1

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6688]
#### Prototype

https://www.figma.com/proto/VEKmwSuhnZVghkUl0VSvN2/Ledger-UX?type=design&node-id=612-980&t=mLIhzZt3E2mnJFXh-0&scaling=min-zoom&page-id=75%3A3202&starting-point-node-id=612%3A980

#### details
- balances are just native asset displayed in native asset values (not fiat and not portfolio balance)
- UTXOs just show account #0 ... no script types, total balance is the sum of all script types tho
- Implement for main wallet pairing flow and the add account flow in the wallet page
- for metamask wallet that expose only one wallet, no need to show the import account selection tray
- filter selection by supported chains for the wallet
- WalletConnect is a bit of an unknown here, so for now consider it out of scope to support multiple accounts in wallet connect. 
- ticket assumes all components exist (separate ticket to be created for that work)

**Comment by woodenfurniture** [comment]
User flow.

![Image](https://github.com/shapeshift/web/assets/125113430/75495294-a9d3-4650-ac43-477b1219f0d7)
