### ISSUE TITLE
Multi account support - manage wallets 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6689]
![Screenshot 2024-04-15 at 4 57 21 PM](https://github.com/shapeshift/web/assets/15096737/058cc036-9c33-47ba-ab29-e62382e84e57)

- add "manage accounts" to dropdown that takes you to the wallet page 
- add ability to add / remove account on wallet page

**Comment by 0xean** [comment]
![Screenshot 2024-04-15 at 5 18 36 PM](https://github.com/shapeshift/web/assets/15096737/6178a26e-b8d8-4c9e-a3a2-9852730fed00)

- add manage accounts to chain row
- fix broken arrows

**Comment by woodenfurniture** [comment]
User flow.

![Image](https://github.com/shapeshift/web/assets/125113430/75495294-a9d3-4650-ac43-477b1219f0d7)
