### ISSUE TITLE
Cosmos: Get Reward Modal

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#669]
Reward Modal (Mockup)
As a user, I want to be able to claim my staking rewards
1. *Progress Column*
    
    *As a user, I want to know what steps are required to Claim rewards and which step I’m on*
    
    1. Step 1: Confirm Details with animated spinner
    2. Step 2: Broadcast TX
2. *Confirm Details*

*As a user, I want to be able to confirm the details of my staking transaction before executing*

1. The following details are displayed on the confirmation screen
    1. Copy: Confirm Claim Staking Rewards
    2. [Amount to Claim in fiat and crypto]
    3. Gas Fee: Gas cost in both crypto and fiat
        1. User can select Low, Med, High
    4. Copy: Your rewards will be deposited into your primary wallet.

**Comment by 0xApotheosis** [comment]
Adding mocks to improve clarity on requirements:

<img width="1045" alt="Screen Shot 2022-03-03 at 3 37 27 pm" src="https://user-images.githubusercontent.com/97164662/156497123-ddaa2479-87d9-4014-a8f7-c2ff75260128.png">

<img width="1043" alt="Screen Shot 2022-03-03 at 3 37 57 pm" src="https://user-images.githubusercontent.com/97164662/156497173-d5f1cc14-b5d5-45ac-b7d2-3e9252fa5a02.png">

<img width="1043" alt="Screen Shot 2022-03-03 at 3 38 21 pm" src="https://user-images.githubusercontent.com/97164662/156497208-8de8065c-31af-422c-af5c-f26134741a68.png">
