### ISSUE TITLE
Muti Account UI components

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6690]
https://www.figma.com/proto/VEKmwSuhnZVghkUl0VSvN2/Ledger-UX?type=design&node-id=612-980&t=mLIhzZt3E2mnJFXh-0&scaling=min-zoom&page-id=75%3A3202&starting-point-node-id=612%3A980

- create ui components for above user flows to be implemented / wired up in #6688

**Comment by woodenfurniture** [comment]
User flow.

![Image](https://github.com/shapeshift/web/assets/125113430/75495294-a9d3-4650-ac43-477b1219f0d7)
