### ISSUE TITLE
[spike] Multi account for wallet connect

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6691]
- does wallet connect support multiple accounts
- what is the lift to implement support for this
- do this after all other multi account stuff is wrapped up

**Comment by woodenfurniture** [comment]
@0xean or @twblack88 do you know of any wallets or dApps that support this? So far it appears to be theoretically possible but without anything to connect to it would be fairly moot.

On the plus side, we do currently support use of multiple accounts when connected as a wallet ✅

When connected as a dApp we only see the first account. This is something we should fix and would actually be useful. The example I see currently is ledger live connected to ShapeShift via WalletConnect, where 2 accounts are connected but we're only displaying the first one.

**Comment by 0xApotheosis** [comment]
It's probably important here to confirm which side of the WalletConnect ecosystem we are talking about.

I believe this would be us, as a _wallet_, using WalletConnect to connect to other _dApps_.
It would be theoretically possibly to use our new account management UI to add new chains to the WalletConnect session via the [`session_update`](https://specs.walletconnect.com/2.0/specs/clients/sign/session-events#session_update) event.

As noted about @woodenfurniture, we are probably not handling the `accounts` a _wallet_ gives us in the session payload when we are connected as a _dApp_, as we just use the existing logic to derive accounts, and so I assume if a _wallet_ gives us an account with 0 balance in the session request we don't actually show it in ShapeShift without manually adding it.

**Comment by woodenfurniture** [comment]
> It would be theoretically possibly to use our new account management UI to add new chains to the WalletConnect session via the [session_update](https://specs.walletconnect.com/2.0/specs/clients/sign/session-events#session_update) event.

Agree, we absolutely should be emitting that event when accounts change, even if the dApp on the other end isn't handling this event

**Comment by woodenfurniture** [comment]
Will turn this into tix

**Comment by woodenfurniture** [comment]
Ticket for "Make ShapeShift as a WalletConnect dApp connect to all accounts in the request":
https://github.com/shapeshift/web/issues/7118

Ticket for "Make ShapeShift as a WalletConnect wallet/dApp emit/respond to session_update event when accounts change":
https://github.com/shapeshift/web/issues/7119
