### ISSUE TITLE
Trigger the no actionable quotes event!

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6692]
- when a user selects a trade route / pair that has no actionable quotes trigger the no actionable quotes event
- INCLUDE the buyAsset and sellAsset 
- do everything so we can track the buyAsset and sellAsset in mixpanel and understand product gaps in our offering.

**Comment by woodenfurniture** [comment]
We're currently able to report on actionable quotes with buy/sell assets and other metadata in mixpanel:
https://mixpanel.com/s/1BEHHb

Non-actionable quotes, breakdown by `sellAssetId`:
![Image](https://github.com/shapeshift/web/assets/125113430/e740f11a-2b52-4caf-9bcc-c49520c589b6)

Non-actionable quotes, breakdown by `buyAssetId`:
![Image](https://github.com/shapeshift/web/assets/125113430/70381379-465a-4c07-bd64-18d4539ba84d)

Is there more work required?

**Comment by woodenfurniture** [comment]
If we're happy with the existing reporting, I can remove the redundant event in the source code as it's likely a cause of confusion.

**Comment by woodenfurniture** [comment]
Marking as blocked so we can discuss in next sync

**Comment by 0xean** [comment]
Sure, please remove the redundant event.

@shapeshift/product - can you please start tracking this information and use it to inform next steps regarding asset pair expansion?

**Comment by woodenfurniture** [comment]
PR to remove unused mixpanel events from the enum:
https://github.com/shapeshift/web/pull/6744
