### ISSUE TITLE
Longtail out of TC swaps

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6693]
#### Background
Currently, we allow users to transact an ERC20 into a natively supported thorchain asset via uniswap which then forwards the underlying intermediate asset to thorchain.  

shitcoin -> ETH (via uniswap) -> BTC (via thorchain)

We want to extend this functionality to go from BTC -> ETH (via thorchain) -> Shitcoin (via uniswap)

We have been calling these swaps "long tail" swaps. 

#### AC
- feature flag specifically just for this segment of longtail (vs long tail in)
- Native TC supported asset to long tail erc20
- custom memo to send into uniswap pool
- lots of testing
- make sure we have slippage controls going into thorchain and uniswap 
- confirm mixpanel tracking working for these trades

**Comment by 0xApotheosis** [comment]
**Notes for the implementor**

In `src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts` we have a `switch` on `tradeType`.
We have logic to determine the trade type of the requested quote (`LongTailToLongTail` etc), though have so far only implemented logic for the `L1ToL1` (basic THORChain to THORChain assets) and `LongTailToL1` (non THORChain L1 to THORChain L1).

```ts
switch (tradeType) {
  case TradeType.L1ToL1:
    return getL1quote(input, streamingInterval, tradeType)
  case TradeType.LongTailToL1:
    return getLongtailToL1Quote(input, streamingInterval, assetsById)
  case TradeType.LongTailToLongTail:
  case TradeType.L1ToLongTail:
    return Err(makeSwapErrorRight({ message: 'Not implemented yet' }))
  default:
    assertUnreachable(tradeType)
}
```

We've implemented the the logic for the `swapIn` side, next we want to do the `swapOut` call to allow trades from an L1 to a longtail asset: https://dev.thorchain.org/aggregators/aggregator-overview.html#swapout

To do this we'll want to add a new `getL1ToLongtailQuote` function that is called in the switch statement above.

**Useful reading**

- Marketing: https://docs.thorswap.finance/thorswap/thorswap/cross-chain-dex-aggregation
- Dev docs: https://dev.thorchain.org/aggregators/aggregator-overview.html
- Memo logic: https://gitlab.com/thorchain/thornode/-/merge_requests/2218
