### ISSUE TITLE
Cosmos: Confirm and Claim reward

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#670]
1. When a user clicks confirm, they are prompted to sign the tx on their connected wallet
    1. “Confirm” button goes into a “Confirm on Wallet” pending state (right now it says “Broadcasting Transaction” but we should fix this) until tx is signed and broadcasted
    2. If user rejects tx on their wallet, the ‘Confirm’ button goes back to the active “Confirm” state and user sees a toast message, “Transaction Rejected”
2. After a user confirms a tx on their wallet, the transaction is broadcasted
    1. If tx is broadcasted successfully, user is routed to the **Pending Claim** step with their TXID linked to a block explorer in the new tab
        1. Confirm Details icon becomes a Check icon
        2. Broadcast TX icon becomes an animated spinner
    2. If tx is not broadcast successfully, user sees a toast message, “Error sending. Try again.”, and the button goes back to the active “Confirm” state
3. If tx is not broadcast successfully, user sees a toast message, “Error sending. Try again.”, and the button goes back to the active “Confirm” state

**Comment by chxash** [comment]
will work on this one
