### ISSUE TITLE
Cosmos: Claim Reward Pending

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#671]
d. **Pending Claim ([Mockup](https://projects.invisionapp.com/share/WF1262ZUU2Q6#/screens/462326246))**

1. Pending claim step displays the same information as the Confirm step as well as the TXID linked to a block explorer in a new tab
2. Users can click “Close” at any time to exit the modal

e. **Claim Complete ([Mockup](https://projects.invisionapp.com/share/WF1262ZUU2Q6#/screens/462326247))**

1. When the claim transaction is confirmed, the header displays “Claim Complete” and the Broadcast TX icon turns into a Check icon

**f. Claim Failed**

1. If the tx fails before making it on chain, user can click Try Again and the tx is attempted to be broadcasted again
2. If the tx fails on chain, show a human readable error message with context for why it failed, or if this isn’t feasible, display “Transaction failed. Contact Support” Contact Support links to [https://shapeshift.zendesk.com/hc/en-us](https://shapeshift.zendesk.com/hc/en-us)

## Screenshots
![image](https://user-images.githubusercontent.com/1958266/157279830-e0255fcb-8355-4583-8a27-800ef8efb277.png)

![image](https://user-images.githubusercontent.com/1958266/157279885-68573f81-d0cd-49e3-ac3a-06b111f8acc6.png)

**Comment by chxash** [comment]
will work on this one
