### ISSUE TITLE
Ledger prompting add ETH in the console log when only adding single non ETH accounts

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#6713]
### Overview

Currently in production Ledger users that import accounts that are not ETH accounts get an error in the console log.  

This issue does not currently block users from any actions from Operations understanding. 

### References and additional details

Error in the console logs: 
<img width="521" alt="Screenshot 2024-04-18 at 12 27 26 PM" src="https://github.com/shapeshift/web/assets/94998097/6f1042f0-40cc-4d76-b8b4-0c45e80c0005">

### Acceptance Criteria

If there is any errors that are being caused by Ledger importing of non-ETH accounts, those should be considered across the app feature suite. 

This may be a quality of life improvement as this issue appears to only fire in the logs.

**Comment by 0xean** [comment]
should be resolved in #6727
