### ISSUE TITLE
Create Ledger "open the app" drawer

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#6720]
### Overview

Connecting a ledger requires users to manually add accounts. This popover will guide users to open the appropriate app on their device as part of that flow.

### References and additional details

https://www.figma.com/file/VEKmwSuhnZVghkUl0VSvN2/Ledger-UX?type=design&node-id=75-3202&mode=design&t=D8Ric66rqcXwSSqP-0

### Acceptance Criteria

Needs to:
- Try and detect the ledger app for the chain being open
- If it does detect, automatically proceed
- Else, wait for user to confirm
- Cancel will go back to start of flow
- Failure to connect to app will show an error toast.

### Screenshots/Mockups

<img width="1821" alt="Screenshot 2024-04-29 at 2 38 11 PM" src="https://github.com/shapeshift/web/assets/97164662/4d141048-d5dd-4f41-ac20-0ec6627bc88a">

**Comment by 0xApotheosis** [comment]
Updated spec with the new drawer flow.
