### ISSUE TITLE
In-app multi-account management final wiring

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#6721]
### Overview

Wire up all of the components and functionality so users can manage their accounts in the app after they have connect their wallet to the app.

### References and additional details

https://www.figma.com/proto/VEKmwSuhnZVghkUl0VSvN2/Ledger-UX?type=design&node-id=612-980&t=rnvOVFBzSPwg5Pjq-1&scaling=scale-down&page-id=75%3A3202&starting-point-node-id=612%3A980&mode=design

### Acceptance Criteria

Only multi-account wallets can enter this flow (i.e not metamask).
Needs to work on all multi-account wallets - test on all of them.
Excludes walletconnect.

**Comment by woodenfurniture** [comment]
Additional observations regarding MM snaps
https://github.com/shapeshift/web/pull/6733#pullrequestreview-2019893668

**Comment by gomesalexandre** [comment]
@woodenfurniture authored as a separate issue in https://github.com/shapeshift/web/issues/6991 so we don't forget this guy: [#6733 (review)](https://github.com/shapeshift/web/pull/6733#pullrequestreview-2019893668)

> Same issue as above for EVM chains, although in this case it's an actual bug, since MM with snaps should have accounts management - we're using MM native functions vs. the snaps entropy derivation, meaning we also don't have access to accounts > 0. We should probably disable EVM chains for MM with snaps (in addition to disabling the whole Manage Accounts flow altogether for MM without snaps)

Looks like this issue can now be closed as it's done in the board?
