### ISSUE TITLE
Ledger connect account selection final wiring

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#6722]
### Overview

Wire up all of the components and functionality so users can connect their ledger accounts when initially connecting.

### References and additional details

https://www.figma.com/proto/VEKmwSuhnZVghkUl0VSvN2/Ledger-UX?type=design&node-id=612-980&t=rnvOVFBzSPwg5Pjq-1&scaling=scale-down&page-id=75%3A3202&starting-point-node-id=612%3A980&mode=design

### Acceptance Criteria

Only ledgeer wallets can enter this flow.

**Comment by 0xean** [comment]
remaining: enable FF

**Comment by 0xApotheosis** [comment]
Gave this a final sanity check against requirements, happy to close now ready for release in https://github.com/shapeshift/web/pull/6961.
