### ISSUE TITLE
Unable to send BTC to taproot addresses 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#6761]
### Overview

Currently being reported by users in both MetaMask and Mobile and able to be recreated by Ops with native. In production, users are unable to send to BTC taproot addresses, however the app allows users to go through the transaction building flow resulting in an error and not a successful transaction 

### References and additional details

https://github.com/shapeshift/web/assets/94998097/e97d0e9b-5f0d-476b-920f-a7bd729b4b4e

Screen recording of the error in action^ 

Recreation steps: 
1. Find taproot style BTC address to test a send to (I used Coolwallet) 
2. Attempt a BTC send to that taproot address for any amount of funds.
3. Witness the errors in the console log when the address is entered. 
4. Continue to attempt to broadcast the transaction and witness the 'User rejected the transaction' error.

<details>
  <summary>Error from logs</summary>
    unstoppable-domains.ts:79 Error: invalid address (argument="address", value="bc1pxk2u9kjszfzxqmsrcctvst32dn2pqrlptsw0e7wqumhlq9cl35ks9v5kh2", code=INVALID_ARGUMENT, version=address/5.7.0) (argument="addr", value="bc1pxk2u9kjszfzxqmsrcctvst32dn2pqrlptsw0e7wqumhlq9cl35ks9v5kh2", code=INVALID_ARGUMENT, version=abi/5.7.0)
        at u.makeError (index.ts:224:23)
        at u.throwError (index.ts:233:20)
        at u.throwArgumentError (index.ts:236:21)
        at i._throwError (abstract-coder.ts:38:16)
        at i.encode (address.ts:17:18)
        at array.ts:57:19
        at Array.forEach (<anonymous>)
        at u (array.ts:43:12)
        at k.encode (tuple.ts:51:16)
        at R.encode (abi-coder.ts:86:15)
    f @ unstoppable-domains.ts:79
    await in f (async)
    k @ address.ts:239
    I @ address.ts:324
    await in I (async)
    validateAddress @ Address.tsx:73
    Re @ isCheckBoxInput.ts:1306
    U @ isCheckBoxInput.ts:1558
    T @ isCheckBoxInput.ts:1399
    R @ isCheckBoxInput.ts:1458
    Te @ isCheckBoxInput.ts:1872
    B @ isCheckBoxInput.ts:364
    H @ isCheckBoxInput.ts:479
    _o @ react-dom.production.min.js:167
    El @ react-dom.production.min.js:290
    bs @ react-dom.production.min.js:280
    ms @ react-dom.production.min.js:280
    ys @ react-dom.production.min.js:280
    is @ react-dom.production.min.js:268
    k @ scheduler.production.min.js:13
    P @ scheduler.production.min.js:14
    Show 15 more frames
    Show less
    useFormSend.tsx:58 Error: failed to add output: Error: bc1pxk2u9kjszfzxqmsrcctvst32dn2pqrlptsw0e7wqumhlq9cl35ks9v5kh2 has no matching Script
        at B.<anonymous> (bitcoin.ts:312:39)
        at Generator.next (<anonymous>)
        at bitcoin.ts:31:71
        at new Promise (<anonymous>)
        at a (bitcoin.ts:27:12)
        at bitcoin.ts:287:67
        at Array.map (<anonymous>)
        at B.<anonymous> (bitcoin.ts:287:51)
        at Generator.next (<anonymous>)
        at s (bitcoin.ts:28:58)
</details>

### Acceptance Criteria

- Users are able to send to taproot BTC addresses
- Not full taproot support (wallet support / address generation)

**Comment by purelycrickets** [comment]
From @gomesalexandre in discord: "Yeah pretty sure we don't support sending to P2TR, should be super easy to detect and we could add some error messaging and disabled state early on!"

**Comment by 0xean** [comment]
holding on a fix since we are contemplating taproot at the product level for the moment.

**Comment by twblack88** [comment]
It's time. For chainflip and to be more modern.

**Comment by Emmaward090** [comment]
> Currently being reported by users in both MetaMask and Mobile and able to be recreated by Ops with native. In production, users are unable to send to BTC taproot addresses, however the app allows users to go through the transaction building flow resulting in an error and not a successful transaction



It sounds like you're dealing with a significant issue regarding transaction failures with BTC taproot addresses in your app. This could be frustrating for users, especially if they can initiate the transaction building process but then encounter errors. It might be helpful to investigate the specific error messages that users are receiving and check if there are updates or patches available for the app that address this issue. Additionally, collaborating with the Ops team to identify any underlying problems in the transaction flow could lead to a solution. Have you already started troubleshooting this with the development team?
@purelycrickets
