### ISSUE TITLE
Unable to deposit into USDT on Eth Thorchain Savers

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6762]
### Overview

When trying to deposit into USDT on Eth saver vault you get an error once selecting Continue on an amount to deposit 

### References and additional details

https://github.com/shapeshift/web/assets/100157997/09d3a3a1-65eb-4583-a669-c945561e58da

### Acceptance Criteria

Should be able to deposit into USDT on Eth Vault

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
To be tackled as part of https://github.com/shapeshift/web/pull/6700

**Comment by gomesalexandre** [comment]
@MBMaria is this on prod or gome? On gome, I cannot repro:


https://github.com/shapeshift/web/assets/17035424/0df9ddde-2586-4430-a887-76d3d20dd323

**Comment by kaladinlight** [comment]
I wasn't able to repro full fail on gome either, but did see a bunch of failed estimations that we can handle better. pushed: https://github.com/shapeshift/web/pull/6700/commits/39dad476a279c343d370f69346d847823b5ef6f2 to gome if you can retest and validate again @MBMaria :pray:

**Comment by MBMaria** [comment]
happening on both prod and gome
![image](https://github.com/shapeshift/web/assets/100157997/adfe4572-d5c1-4362-946b-9c7dac181641)
![image](https://github.com/shapeshift/web/assets/100157997/d2976547-7d39-409a-917a-cad3e3ad4868)

**Comment by MBMaria** [comment]
i also have a user who has a persistent issue with approving usdt for a trade.... not sure if its related but this is his video of what he is experiencing. 
[Screencast from 04-25-2024 12-30-17 PM.webm](https://github.com/shapeshift/web/assets/100157997/2c332542-81ae-4d00-b37c-b819417ef754)
