### ISSUE TITLE
Unable to approve deposit for USDT/Rune symmetric LP 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6763]
### Overview

Getting a dead click when trying to approve USDT for a deposit into USDT/Rune sym LP 

### References and additional details

https://github.com/shapeshift/web/assets/100157997/cf875803-de46-481a-839e-541c2888b823

### Acceptance Criteria

Should be able to approve USDT for usdt/rune LP

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
To be tackled as part of https://github.com/shapeshift/web/pull/6700

**Comment by gomesalexandre** [comment]
@MBMaria is this on prod or gome? On gome, I cannot repro:


https://github.com/shapeshift/web/assets/17035424/b1a8679f-9184-4d61-b050-47e68105d0a7

**Comment by kaladinlight** [comment]
I was unable to repro this as well. Will wait to see if it can be reproduced, and if so, can you paste the estimate gas request payload from the network tab here please @MBMaria. That should provide enough insight to hopefully fix. Thanks!
