### ISSUE TITLE
Wallet Connect (out) broken in android mobile

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#6766]
### Overview

Currently in Prod, the connection flow for wallet connecting out to another service via Android devices is broken and does not allow uses to Wallet Connect (out). 

### References and additional details

![Screenshot_20240426_121513_ShapeShift](https://github.com/shapeshift/web/assets/94998097/21a99d61-8117-4e13-b464-c72a772237ae)

Using either the QR camera or copy and pasting the link both result in dead clicks when attempting to connect.  

There is also one support ticket of a user using Graphene OS on their android device saying the WC flow is completely crashing the app. 

This issue has not been able to be recreated by Operations with the web or iOS versions of the app which leads us to believe it is currently only affecting android users. 

### Acceptance Criteria

WC flow for android devices is happy again.

**Comment by gomesalexandre** [comment]
@purelycrickets I was able to repro in the app and can confirm this is isolated to the app:


https://github.com/shapeshift/web/assets/17035424/b15970c9-f1a7-420a-8389-4bac7dd8d39f

We just added Sentry to the app (in develop currently, staged for next release) so I will add some error reporting for this so we have visibility 🙏🏽
