### ISSUE TITLE
Infinite spinning on LP sym deposit

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#6787]
### Overview

During a sym LP deposit the app never progressed past the first stage. Looking at viewblock, the transaction failed but the app is displaying the TX as pending.

### References and additional details

TX link:
https://viewblock.io/thorchain/tx/9283E5816B31A73A37D1009B456EFD8A76D869ED446B6790711FDFC53326E739

App stuck:
![image](https://github.com/shapeshift/web/assets/125113430/2d1b5300-21e6-416a-a6bb-a75601b3a155)

There may be an issue where we arent able to prevent conflicting deposit types across tabs. The following message appeared after sym rune deposit - but there was already a sym deposit in flight in a different tab... The seems to warrant some discussion.

![image](https://github.com/shapeshift/web/assets/125113430/6fe360d2-7ca1-42da-9b01-e4ca9db50410)

### Acceptance Criteria

* Sym deposits can complete.
* Failed deposits appear as failed in the UI.
* We handle conflicting tx types to prevent stuck deposits and lost funds.

**Comment by kaladinlight** [comment]
Regression from: https://github.com/shapeshift/web/pull/6700/commits/062cf1755e5112cb40667333e6c8f9db20030258
Fixed with: https://github.com/shapeshift/web/pull/6700/commits/d8ae87fc2c724ec2155bd09ca6ee6ebb2f8a216c
