### ISSUE TITLE
Thorchain lending slippage levels

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6836]
ticket replacing this one https://github.com/shapeshift/web/issues/6577

- Implement slippage color / warning scheme in thorchain lending. Follow the same pattern used in the swapper and same heuristics. 
- double check on LP to see if we can extend there as well 

- [x] pull health tag should reflect Active or Halted state rather than Healthy (completed)

**Comment by NeOMakinG** [comment]
What I did on LP:

![image](https://github.com/shapeshift/web/assets/14963751/ee450099-3023-4ee4-8e10-6668450b8e05)
![image](https://github.com/shapeshift/web/assets/14963751/69b47b90-fe86-4dfe-b74e-e313d14df05d)

If it's something else than `Available`, it will display `Halted` with a red tag

I also added the fact that we display every pools we support even if the status is halted, here is a monkey patched example:

![image](https://github.com/shapeshift/web/assets/14963751/d2d63174-05be-4034-858d-cb8588d515f0)

It actually doesn't change anything and will almost never be shown as `loan_collateral` will mostly be 0, we actually end up with BTC and ETH pool for now but it works!

Pools:
We already handle the status:
![image](https://github.com/shapeshift/web/assets/14963751/6c1929cf-27a1-4192-99ad-9a85c851ec44)

BorrowInput: we already handle the slippage Acknowledge warning
RepayInput: Missing the slippage acknowledge warning, I'll add it in the same PR

Do I miss anything regarding heuristics? Is that enough?

**Comment by twblack88** [comment]
Sounds right. It's that tag, e.g., if a lending pool is at capacity it shouldn't show as healthy. 

It should say active probably.

![Screenshot 2024-06-19 at 3 42 00 PM](https://github.com/shapeshift/web/assets/8991325/3f052432-c790-47dd-be33-9ea0404575ad)

**Comment by NeOMakinG** [comment]
- We have acknowledgement almost everywhere except in `RepayInput`
- Status are reflecting the real status of Lendings

If someone has a loan to repay or can deposit in the LP at one time because it's a bit emptier, feel free to finish this but it's pretty hard to test on my side for now

**Comment by 0xean** [comment]
potentially closing based on upcoming TC vote
