### ISSUE TITLE
Thorchain streaming swaps should be labelled as such in the quote

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#6848]
### Overview

It's been reported by @twblack88 that thorchain streaming swaps are not being correctly labelled as streaming swaps in the quote, lead users to action them and be stuck with a very slowly executing trade.

### References and additional details

.

### Acceptance Criteria

Thorchain streaming swaps are labelled as such.

**Comment by woodenfurniture** [comment]
Non-compact view labels steaming swaps but compact view does not

**Comment by woodenfurniture** [comment]
Possible low-lift "solushun" (ignore the janky screenshot paste):

![Image](https://github.com/shapeshift/web/assets/125113430/4099215a-f740-4a13-a87b-5d79f5b1f425)

**Comment by 0xean** [comment]
product to create mock for warning model.

@shapeshift/product

**Comment by reallybeard** [comment]
Here is what we have mocked up for the ACK for streaming swaps.

https://www.figma.com/design/ZK7L1l38Kzc4SlKekbPnm0/Modals?node-id=1044-1079&t=HygmuLAAnC3XfJIz-0

**Comment by 0xean** [comment]
![image](https://github.com/shapeshift/web/assets/15096737/a96b742a-df23-489a-8857-ac0381d6a36c)
