### ISSUE TITLE
V9 fox farming contract states 0.00% APY

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6881]
### Overview

The new fox farming contract still states 0 rewards even though it went out on the 11th. Not sure if there should be rewards accruing yet.

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/9f57c380-b52d-403a-b8f1-058de83b7e37)

### Acceptance Criteria

APY should be accurate representation of rewards being received, 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria is this still happening for you? 
<img width="1431" alt="image" src="https://github.com/shapeshift/web/assets/17035424/fe0f84b8-a759-4834-b6ef-9a27d8f69b23">

**Comment by MBMaria** [comment]
Nope :) looks like rewards are accruing now! 
![image](https://github.com/shapeshift/web/assets/100157997/b5cd766d-a332-481e-bd93-263c0cd055ee)

**Comment by gomesalexandre** [comment]
Closing as rewards have started and APY is now reflected in the app
