### ISSUE TITLE
Intermittent failure to import accounts in account import drawer

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#6928]
### Overview

There's a intermittent issue importing accounts. See details below.

### References and additional details

See comments at 0:45 and 0:50 in the jam:
https://jam.dev/c/28e42ad1-da47-4164-b593-64219561203a

Originally raised in:
https://github.com/shapeshift/web/pull/6908#pullrequestreview-2054586834

### Acceptance Criteria

Accounts reliably load without failure.

**Comment by woodenfurniture** [comment]
@gomesalexandre does this relate to your fix in https://github.com/shapeshift/web/pull/6827 ?

**Comment by gomesalexandre** [comment]
> @gomesalexandre does this relate to your fix in #6827 ?

Probably isn't, IIRC those failures weren't exclusive to UTXOs - either way, we should be on a sane base WRT UTXOs scriptTypes to fix this so let's wait before #6827 gets in and test this again.

**Comment by woodenfurniture** [comment]
Non-blocking for initial release
