### ISSUE TITLE
KeepKey extreme slow pubkey derivation

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#6929]
### Overview

It's around 30 seconds to derive pubkey for a UTXO account.

Per comment from @gomesalexandre :

Things are suuuper slow here, which I believe is caused by device being slow to derive pubkeys (and obviously accounts fetching). 
I believe we want to use `pubKey` vs. on-device derivation for existing AccountIds as we've discussed yesterday. All `deriveAccountIdsAndMetadataForChainNamespace` methods should be able to accept an alternative input containing `pubKey` which would call
  - `getAddress` with the newly passed `pubkey` for EVM chains (we're already calling it, but never with `pubKey`
  - for UTXOs, things are slightly more complex. Ideally we'd call `getAddress()` instead of `wallet.getPublicKeys()` when `pubKey` is passed, but that's not so simple. We support passing a `pubKey` in `UTXOBaseAdapter`'s `getAddress()` to support account derivation, but the `pubKey` is really an address, see https://github.com/shapeshift/web/blob/b2839c8823efe08383618770c823048e2b45ed14/packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts#L246
  
 
We have two solutions for the latter, either don't call `getAddress` nor `getPublicKeys()`at all in `deriveUtxoAccountIdsAndMetadata` when `pubKey` is passed, or refactor `UTXOBaseAdapter`'s `getPublicKey()`to support bypassing derivation with `pubKey` too, i.e:

```diff
diff --git a/packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts b/packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
index ef6bf320ce..98ebb25738 100644
--- a/packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
+++ b/packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
@@ -540,9 +540,14 @@ export abstract class UtxoBaseAdapter<T extends UtxoChainId> implements IChainAd
     wallet: HDWallet,
     accountNumber: number,
     accountType: UtxoAccountType,
+    pubKey?: string,
   ): Promise<PublicKey> {
     this.assertIsAccountTypeSupported(accountType)
 
+    if (pubKey) {
+      return { xpub: convertXpubVersion(pubKey, accountType) }
+    }
+
     const bip44Params = this.getBIP44Params({ accountNumber, accountType })
     const path = toRootDerivationPath(bip44Params)
     const publicKeys = await wallet.getPublicKeys([
```

### References and additional details

See jam for example:
https://jam.dev/c/14bf5e04-bc9a-4354-9b2b-2619708065c9

Originally raised in:
https://github.com/shapeshift/web/pull/6908#pullrequestreview-2054586834

### Acceptance Criteria

KeepKey slow pubkey derivation should not slow down the import of accounts.

**Comment by gomesalexandre** [comment]
Note @woodenfurniture I'm not 100% confident the derivation is the issue here so we may *first* want to focus on using RTK `getAccount` query here, so the accounts already existing in store don't make network requests. Only then, and if things are still slow we should bypass device derivation.

**Comment by woodenfurniture** [comment]
Not blocking for initial release

**Comment by woodenfurniture** [comment]
When debugging I was not able to see a loading state longer than 2s on keepkey. May have to pile on this to determine next steps.

**Comment by woodenfurniture** [comment]
Closing as this appears to be a transient issue related to network.
