### ISSUE TITLE
Unable to deposit into BTC loan position

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#6945]
### Overview

I have had a number of support tickets come in over the weekend related to being unable to deposit into a BTC loan position.  The cap is not yet met and users are able to enter the amount they would like, but the borrow button goes red and greys out once a number has been entered regardless of the wallet. 

### References and additional details

Native wallet attempt: https://jam.dev/c/5929c525-26bb-4b5b-9535-2e9d50e9fe27

Ledger attempt (same seed): https://jam.dev/c/4374da2f-88be-4430-8c90-6a97575e1caa

I additionally have users of KeepKey, Native, and Ledger that have reported the same issue in support tickets. 

### Acceptance Criteria

If there is a reason users are unable to deposit into a new borrow position, we should display to the user the reason they are unable to make the transaction. 

If there is a a big blocking the functionality, we should resolve it so users can make deposits when the Caps have enough room for a user to be able to do so.

**Comment by gomesalexandre** [comment]
GitHub is drunk, #6946 fixed it
