### ISSUE TITLE
Wire up Change Rune Address flow for rFOX

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6947]
https://www.figma.com/design/REOouo0sAuOhoD597yZEGE/rFOX?node-id=1-250&t=rKiPIPofUI4duT4G-0

- check string entered is valid rune address, show error state if invalid
- validate new address is not the same as the old address
- all functionality in flow works, tested against live arb contracts

**Comment by gomesalexandre** [comment]
Note, this issue encapsulates both the visual bits *and* the wire-up bits. Initial visual bits have been started in https://github.com/shapeshift/web/pull/6959, to be continued either in https://github.com/shapeshift/web/pull/6963 or in a separate @reallybeard PR.
