### ISSUE TITLE
Abstract and refactor rfox claim component

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6965]

**Comment by gomesalexandre** [comment]
@0xApotheosis to confirm but IMO, feels like claim is straightforward enough not to require the same hooks logic extraction we've done for stake/unstake/bridge?

**Comment by 0xApotheosis** [comment]
@gomesalexandre I might just pull out `getUnstakingRequest` to match all of the other contact calls that have been extracted as standalone hooks.
