### ISSUE TITLE
[spike] integrate portals zaps into swapper 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6981]
- portals offers "one click defi" which looks like a swap into a defi position 
- https://build.portals.fi/docs/guides/using-portals
- spike into integrating this into our swapper 
<img width="698" alt="Screenshot 2024-05-23 at 3 22 30 PM" src="https://github.com/shapeshift/web/assets/15096737/58f6f9bb-b317-49cb-9fdc-b1c70eef3c94">

Some Qs
- how do we find these assets?
- can we charge fees?
- how do we display these tokens / positions after a user has them?

Output from this spike would be 

1. tickets for the full implementation work with some general estimate on level of effort
2. documentation of above questions and any other's that arise from that
3. communicate any concerns with product on UX that might need to be considered that would be different than the existing swapper

**Comment by 0xean** [comment]
https://shapeshift.notion.site/Two-Smol-Swappers-646613460477490497f91287e4966fbc

**Comment by gomesalexandre** [comment]
> can we charge fees?

Absolutely:

<img width="806" alt="image" src="https://github.com/shapeshift/web/assets/17035424/e34fc034-d44c-4ee8-be95-dd64b2b56ef0">
https://api.portals.fi/docs#/Portal/PortalController_portalV2

**Comment by gomesalexandre** [comment]
> how do we find these assets? / how do we display these tokens / positions after a user has them?

1. How do we find them?

`https://api.portals.fi/v2/tokens` is the goer, and we should update the asset generation script to parse and use these as assets. We could start as a low lift with one chain only, and only one page, to validate this! 

2. How do we display them

Once added to generated asset data, these will live as ERC20 tokens in the app, business as usual

3. How do we display the DeFi positions?

ideally: we don't and let Zapper do it
effectively: Zapper isn't so good with all chains and *will* miss many opportunities. IMO, having them as tokens is a good MVP, but eventually, we could use the DeFi opportunities abstraction to parse and upsert `https://api.portals.fi/v2/tokens` list as DeFi opportunities. For all intents and purposes, the shape is very similar to Zapper's, which will make things **relatively** easy to work with  (note **relatively** in bold, there is definitely quite the lift here)

4. What about market-data?

Historical market data isn't going to be available, but that's nothing different than e.g how we used to do UNI-V2 opportunities - we absolutely can and should upsert the current price of all `https://api.portals.fi/v2/tokens` tokens in the market-data slice

**Comment by gomesalexandre** [comment]
Actual issues to be created from this, and spike to be closed on Monday if we agree we're there spike-wise

**Comment by gomesalexandre** [comment]
https://github.com/shapeshift/web/issues/7305
https://github.com/shapeshift/web/issues/7304
https://github.com/shapeshift/web/issues/7303
https://github.com/shapeshift/web/issues/7306
