### ISSUE TITLE
[Spike] BTC <> DEGEN frame 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6982]
https://shapeshift.notion.site/F-Multichain-trade-Frame-8cf92831c8024680863dd6f19e2aa68b

**Comment by twblack88** [comment]
Updated the spec to reflect a more possible GTM: 
- Blocked on router upgrades from TC. 
- Go to market with just L1 swaps upgrading gomes first app into an MVP with better styling.

Closing this spike for now as complete.
