### ISSUE TITLE
ETH.BASE to ETH.ETH failure 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7036]
### Overview

Getting failures when trading ETH on Base to ETH on ETH. 

### References and additional details

https://jam.dev/c/fd29fc7e-1f2b-4a27-b1bd-ddd33a6cdd1f

### Acceptance Criteria

BASE trades work for ETH <> ETH on ETH

**Comment by kaladinlight** [comment]
Jam super helpful. Shows a 429 from lifi when trying to broadcast the transaction. This PR: https://github.com/shapeshift/web/pull/7027 should fix this scenario and then we can retest and validate things are working as intended

**Comment by kaladinlight** [comment]
Going to close as this was specifically related to 429 error on send attempt. If we get other errors that we have control over (failed `/send` endpoint, or failed `/estimate` endpoint), we can create a new ticket as such.
