### ISSUE TITLE
User unable to claim foxy 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7040]
### Overview

A user has tried multiple times to claim his unstaked foxy - it says transaction complete and he is charged ETH for the tx but the claim is for zero fox. 

### References and additional details

Wallet address: https://etherscan.io/address/0xe8fa51ca0f738e3f902538a2b85fe1c97f8dbd45
![image](https://github.com/shapeshift/web/assets/100157997/afec27ca-82cb-4143-a108-fcad77696cea)
![image](https://github.com/shapeshift/web/assets/100157997/65b062ca-ee44-4961-b443-393280101a61)
![image](https://github.com/shapeshift/web/assets/100157997/cf233e82-e0c0-4df6-8b82-1e7cb5034ed4)

### Acceptance Criteria

Should be able to claim fox in single tx

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
@MBMaria can you please go through the troubleshooting steps that we have taken time to outline for operations?

https://github.com/shapeshift/web/issues/6279#issuecomment-2004705069

cc @purelycrickets

**Comment by 0xean** [comment]
closing per @purelycrickets
