### ISSUE TITLE
Multi accounts behavior seems wrong using the demo wallet

### ISSUE THREAD

**Issue by NeOMakinG** [shapeshift/web#7047]
### Overview

The Demo Wallet uses the Manage Accounts button in the menu: 

![image](https://github.com/shapeshift/web/assets/14963751/8953ad4b-66aa-4928-935c-051daa77658a)

When you click on it, it open the Wallet modal

But, if you go to the a wallet view, the `Manage Accounts` button opens the multiple accounts management modal

![image](https://github.com/shapeshift/web/assets/14963751/bff98e53-79cd-47e1-a6d2-b8c35abb7638)

### References and additional details

https://github.com/shapeshift/web/pull/7023

### Acceptance Criteria

Depending on product decision:

- Remove Manage Accounts item in from the menu and remove the same button from the wallet page
or
- Activate multiple accounts management in the demo wallet, but disable the `Load More` button as for MM snap

**Comment by NeOMakinG** [comment]
I'll fix this tomorrow in the morning, will be quick

**Comment by gomesalexandre** [comment]
More context here: https://github.com/shapeshift/web/pull/7032#discussion_r1625753255

**Comment by NeOMakinG** [comment]
@shapeshift/product can we get a hint on what should be the default behavior? We have a mix between 2 different behaviors

**Comment by reallybeard** [comment]
> @shapeshift/product can we get a hint on what should be the default behavior? We currently have a mix between 2 different behaviors

Yah I think we should disable or hide for demo wallet mode. @twblack88

**Comment by twblack88** [comment]
I think we should just hide it.

**Comment by NeOMakinG** [comment]
> ~I think we should just hide it.~ make it work on the menu NVM. @NeOMakinG already on there. We can
> 
> * add the functionality to the menu for connect account (top right
> * CTA to connect when they connect a chain to connect wallet instead of done.

@twblack88 when they connect a chain? I'm not sure to get it, as the demo wallet has every chains by default, this button is disabled

Here is what I actually did: https://jam.dev/c/65a00786-75ea-4a26-9001-952792a36ad5

Are you happy with this?

**Comment by twblack88** [comment]
For the record Neo was praoctive and DM-ed i replied: 

– leave the Manage accounts in the demo Wallet​ as discussed.
– when they click on manage accounts, the add another chain button should be disabled. ✅ 
– where it says done in the chain menu - on demo wallet - it should say “connect wallet” instead. 
– if they click on any of the chains load more should be disabled, already done ✅
