### ISSUE TITLE
Unable to trade USDT on Eth to OPSEC on Eth 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7059]
### Overview

User is unable to trade usdt to opsec on eth. I was able to recreate the issue as well.

### References and additional details

https://jam.dev/c/1334c253-511d-40fd-96fd-15ee0ae162db

### Acceptance Criteria

Should be able to complete trade or not give a rate if trade is not valid

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
gm @gomesalexandre thanks for looking into this. 
I have another user unable to trade out of usdt on eth ....could this be due to a similar issue and upping the slippage would help?
![image](https://github.com/shapeshift/web/assets/100157997/bef14445-2867-4a02-a8a1-585c0f507c7b)

**Comment by gomesalexandre** [comment]
> gm @gomesalexandre thanks for looking into this. I have another user unable to trade out of usdt on eth ....could this be due to a similar issue and upping the slippage would help? ![image](https://private-user-images.githubusercontent.com/100157997/337094100-bef14445-2867-4a02-a8a1-585c0f507c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjM0MjksIm5iZiI6MTcxNzY2MzEyOSwicGF0aCI6Ii8xMDAxNTc5OTcvMzM3MDk0MTAwLWJlZjE0NDQ1LTI4NjctNGEwMi1hOGExLTU4NWMwZjUwN2M3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwODM4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTZiYjQyZjgzODcyYmIxMjY1NTAyOTY2MDc3MmQ4YjMyNTJmZDFhMTlmN2U5ZTE1YWRlZDllN2MwOWU5YjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ikz2lNwae39ZMc3GG38JSREFnZ8ZoNfeLyTMgOEBag)

That doesn't sound very likely - the USDT approval situation should be handled by the various DEXes, I only mentioned it for reference so we don't get confused with the various network failures, it's usually expected  (or may not) as part of the USDT approval flow depending on how said swapper implements that, but should eventually automagically work on a second try (automagically handled by the DEX).

Can we have a Jam of this guy if we're able to repro? That would be quite helpful 🙏🏽

**Comment by 0xean** [comment]
closing as stale and no response from operations.
