### ISSUE TITLE
When a user executes any form of a transaction doesn't update wallet balance or TX history

### ISSUE THREAD

**Issue by Neverwas-dev** [shapeshift/web#706]
# Brief description
Following release v1.0.4 during testing it was discovered that when executing a wallet transaction it doesn't update the current session once completed and verified on the blockchain. This includes Sends, Receives, and Trades
This has been recreated on each available wallet on the app.shapeshift.com platform.

# Steps to recreate 
1. Connect a wallet
2. Execute a trade, send or receive
3. Verify that the transaction is complete on the blockchain
4. Change pages try to see if Dashboard or assets pages update to reflect new tx
5. A hard refresh of the wallet (browser window) the wallet will update and display correct balances and transaction history

# Acceptance Criteria
- Once the transaction has been successfully mined / confirmed, the transaction populates in the connect wallets Recent Transactions. 

# Bounty Hunters
- Join our discord [here](https://discord.gg/shapeshift).  Feel free to ask for help in #engineering-public channel
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info

Link to Discord triage
https://discord.com/channels/554694662431178782/873244924026449940/929136355630518312

**Comment by 0xdef1cafe** [comment]
there are two possible ways to approach this, both are in the `txHistorySlice` reducer

https://github.com/shapeshift/web/blob/develop/src/state/slices/txHistorySlice/txHistorySlice.ts#L70

firstly, verify that a new tx is coming in over the websocket; this may be a problem with unchained. i'd recommend testing with btc sends as they're cheapest in terms of fees - sending to your own address is also possible.

1. when a new tx comes in, update the underlying asset/account balances in the `portfolioSlice` of the store. this is not my preferred approach as the `txHistory` slice shouldn't be meddling with the `portfolioSlice` if possible, and there are a lot of complicated edge cases to consider here (adjusting fee asset balances, adding new assets).
2. when a new tx comes in, call the `getAccount` endpoint in `portfolioSlice` to refetch the whole account. this is my preferred approach. it's much cleaner and will catch edge cases such as someone doing a swap into a new asset that they previously didn't have. the difficulty here, is that we don't have a way of determining if tx's have finished loading over the websocket, i.e. we absolutely can't refetch the entire account from unchained for each tx that comes in over the websocket on initial page load, but we do want to refetch the account for a send/trade. for example, in the balance charts we currently debounce a selector of tx ids in the store "know" when they're finished loading. we might have to put something in the `PortfolioContext` https://github.com/shapeshift/web/blob/develop/src/context/PortfolioProvider/PortfolioContext.tsx to manage this "loading" state. speak to @kaladinlight if there's a better way to unchained to notify us if the tx's have finished loading. alternatively, we could use some kind of callback on send/trade, but i'd prefer a centralized approach to manage this. this might all change with tx history moving to restful with upcoming cosmos integration too.

**Comment by 0xean** [comment]
Gonna leave this one for a workstream dev to look at given some of the complexities.

**Comment by 0xdef1cafe** [comment]
after conversation with @kaladinlight - these will be the pending tx history changes that affect this work

- on initial app load, we'll fetch the tx history RESTfully, this will show all current confirmed and pending txs (getAccount call will soon including pending txs as part of it)
- this will mean that once we're finished paginating confirmed txs, we can confidently say when the tx's are finished loading. this is useful for balance charts/loading state of the app.
- we'll still open the websocket, and this will catch new pending txs. upon a new pending tx, the transaction provider is then able to confidently refetch the corresponding account. this will be useful in the case of a user trading into a new asset they they didn't previously have in their portfolio.

**Comment by 0xdef1cafe** [comment]
given this continues to manifest in multiple issues we should prioritize this before the cosmos epic is done, as there's no guarantee that the btc and eth unchained implementations will be updated to match the new cosmos paginated and tx websocket implementation at the same time.

@0xdef1cafe to spike on approach and fetch portfolio on trade & new incoming tx and bounty.

note - solve the issue of a "loaded tx state" before the fetching.

**Comment by 0xean** [comment]
waiting on cosmos tx pagination and web sockets

**Comment by 0xdef1cafe** [comment]
@stackedq is going to take over this and finish my linked draft PR
