### ISSUE TITLE
lang selector is over the title on responsive splash screen

### ISSUE THREAD

**Issue by NeOMakinG** [shapeshift/web#7062]
### Overview

If you use ShapeShift with the Metamask mobile app, the lang selector is over the title and so it makes it difficult to read/notify that it exists

![image](https://github.com/shapeshift/web/assets/14963751/7091303f-aed1-46ee-a4e7-24c2cf508605)

### References and additional details

- Use MetaMask browser on mobile
- Navigate to https://app.shapeshift.com

### Acceptance Criteria

TBD by @shapeshift/product

**Comment by twblack88** [comment]
I guess `safe-area-inset-top` won't render because it fights with the MM top bar? 

ideally the thing just has the 6 px padding like mobile connector
