### ISSUE TITLE
ModalProvider not showing unmount animation

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#71]
when we set isOpen to false it unmounts the component before the animation has a chance to run

add a thunk to set `isOpen` to false, and another state variable `shouldRender` to false on the next render after `isOpen`is set to false

**Comment by 0xean** [comment]
need someone with strong TS experience to handle this one. Better for core team to pick up. @0xdef1cafe to add comments

**Comment by 0xdef1cafe** [comment]
closing in favor of new template https://github.com/shapeshift/web/issues/1095
