### ISSUE TITLE
Deposit into BTC saver has Continue button greyed out when should say "Minimum amount XYZ" or "Insufficient Funds"

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7105]
### Overview

When trying to deposit into BTC saver vault , currently it doesnt matter what value you select it will have the continue button greyed out if it is not enough to proceed with the deposit - does not tell you it needs a minimum amount or that you have insufficient funds

### References and additional details

https://jam.dev/c/efc95387-aad6-4c36-9ee1-6405b301a1a1
![image](https://github.com/shapeshift/web/assets/100157997/ea9b034b-4fd4-4c76-be7f-0531c618d37c)

### Acceptance Criteria

Modal should give correct error messaging 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria looks like this may have been caused by intermittent BTC node issues? Currently able to get a minimum, as well as a valid quote (though not enough funds to confirm this works to preview) 

<img width="448" alt="image" src="https://github.com/shapeshift/web/assets/17035424/9e3d0025-2e14-48ea-814b-4246213556c7">

**Comment by MBMaria** [comment]
If i type in an amount to deposit the errors will show, but if i select and of the percent amounts it will just have continue greyed out
![image](https://github.com/shapeshift/web/assets/100157997/c0669d74-6c16-4ed3-a14b-70712be16bb7)
