### ISSUE TITLE
Short-term unblock for RUNE revenue per epoch

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#7117]
### Overview

This is a short-term solve to unblock rFOX dashboard progression, with long-term solve in #7116.

Create a react query which can determine the total affiliate earnings in RUNE for a given block/timestamp range, using the approach detailed in https://github.com/shapeshift/web/issues/6951#issuecomment-2159563532

Yes, this isn't very scalable but this is only intended to unblock work in the short term.

### References and additional details

For the given time range, page through actions using the `/actions` midgard endpoint, e.g
https://midgard.ninerealms.com/v2/actions?affiliate=ss,fromTimestamp=1718006345,timestamp=1718066345

Docs here
https://midgard.ninerealms.com/v2/doc#operation/GetActions

### Acceptance Criteria

Returns the total affiliate earnings in RUNE for the given timestamp range

**Comment by kaladinlight** [comment]
Just to note on this approach, using midgard `/actions` endpoint will only give us revs on swaps. Midgard does not index LP, savers, or loans by affiliate at this time.

**Comment by woodenfurniture** [comment]
No longer required
