### ISSUE TITLE
Parsing for rFOX change address transactions

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7120]
### Overview

When changing address for rune claims for rFOX, the transaction in the activity tab lacks details

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/a10012a8-4cd0-4480-896d-ef8a33ae12b0)

### Acceptance Criteria

Transactions should say what they are for

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
Unstake of rfox on mm says transaction in activity tab as well
![image](https://github.com/shapeshift/web/assets/100157997/8420c883-2c75-4cc1-be35-53d5f076eddc)
https://arbiscan.io/tx/0x6330c78d07a8eaac871b17f1d30918e54dba1238ab3c679ec0a70a7c10bd8894

**Comment by gomesalexandre** [comment]
@MBMaria ty for raising this! For context, unchained-client parsing of RFOX Txs is next up in the plate, though EVM Txs parsing is probably lower prio - incoming RUNE rewards Txs parsing would be higher prio (to be displayed in the dashboard) but we're currently blocked by the rewards address being yet unknown 🙏🏽
