### ISSUE TITLE
Web Workers for Native Vaults

### ISSUE THREAD

**Issue by mrnerdhair** [shapeshift/web#713]

**Comment by 0xdef1cafe** [comment]
as of writing, this is blocked by hdwallet bits required for async goodness.

probably not ready any earlier than 2/21

**Comment by theoboldfrazier** [comment]
@mrnerdhair Is this still an issue? Can you close if not.

**Comment by mrnerdhair** [comment]
Still an issue, but backlogged to oblivion RN.

**Comment by 0xean** [comment]
closing as stale.
