### ISSUE TITLE
Doge receive address changes between pending and confirmed trade screens

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7172]
### Overview

When trading into Doge, the doge address listed on the preview screen changes after the transaction says complete. 

### References and additional details

Preview trade: 
![image](https://github.com/shapeshift/web/assets/100157997/078b0881-72fd-4fef-b575-95d3bc1aab96)
Confirm and trade: 
![image](https://github.com/shapeshift/web/assets/100157997/c6edcfc0-a806-4ac9-9a87-a4cc99c17d5d)
Trade complete: 
![image](https://github.com/shapeshift/web/assets/100157997/35e8afa1-a741-424b-9dbf-02490e15d1ee)
TXID: 
![image](https://github.com/shapeshift/web/assets/100157997/9e4c4b8d-3352-42ce-8924-1c145ff926f1)

### Acceptance Criteria

Should say same address on all screens

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Goint to pile tackle this with @NeOMakinG as an UTXO deep-dive 🏊🏽
