### ISSUE TITLE
Selecting "Go to my dashboard" button when setting up a new wallet takes you to trade page

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7173]
### Overview

When importing/creating a new wallet, the initial pop up with details of the wallet has a option "Go to my dashboard" on the third screen. However this takes you to the trade page, not the dashboard. 

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/1e9e0f88-7319-4606-8918-4091d326713d)

### Acceptance Criteria

Should take you to Dashboard

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by twblack88** [comment]
oh! that's a good callout @MBMaria thank you. We should change the copy to start swapping.
