### ISSUE TITLE
Approvals for LP deposits greyed out

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7189]
### Overview

Trying to deposit into fox/rune or dai/rune LP's and the approve button is greyed outt

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/adca3bf7-0c03-436c-a7ba-2848b58aa3e2)
![image](https://github.com/shapeshift/web/assets/100157997/a5b205a5-55f2-403c-8c2f-824e5d9a9d1f)

https://jam.dev/c/daa30016-7b8a-43c2-85a6-4b3ef729dd1c

### Acceptance Criteria

Should be able to approve

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
@MBMaria can you repro this consistently?

I tried with both your and my wallet, but couldn't get it to happen.

**Comment by MBMaria** [comment]
@0xApotheosis yep. ive been recreating on keepkey if that makes a difference

**Comment by 0xApotheosis** [comment]
Oh, that does make a difference, yes.

Can you please DM me your KK seed?

**Comment by 0xApotheosis** [comment]
Ok, I can replicate - this looks like a KK-specific bug.

I'll investigate a fix.

**Comment by 0xApotheosis** [comment]
Found the root cause, it was not just KK. Fix incoming.
