### ISSUE TITLE
Add XDeFi wallet to SelectWallet Modal

### ISSUE THREAD

**Issue by loxator** [shapeshift/web#720]
Hi,

I would like to open a PR for adding [XDeFi](https://xdefi.io) wallet as an option in the SelectWallet Modal. I have done most of the work and the wallet connects successfully, but it uses MetaMask Adapter to connect since our wallet relies on Ethereum Provider as well.

However, in case the Ethereum Provider is not found, the MetaMask Adapter's implementation in your `hdwallet` repo, then redirects the user to the MM chrome store page. Of course, in case of XDeFi this is not what should be done. 

Do I also need to create an appropriate adapter for XDeFi wallet and use that for the XDeFi wallet connect option? Or is there an alternative way? 

Thank you for your help!

**Comment by 0xean** [comment]
@loxator -  

First off, this is wonderful and thank you for looking into how to integrate with ShapeShift.  I cannot speak for the engineering workstream, but at the moment they are very heads down to try and get to a public launch of app.shapeshift.com

It is looking like that will occur in the coming week or two and would expect then that there will be some additional bandwidth to help guide your question on integration. 

We are still working on getting better documentation in place to allow people to self-serve on these types of requests and this will probably be a great one for us to use as an example for that documentation.

Thanks again for the willingness to push this through!

**Comment by loxator** [comment]
@0xean ,

Thanks for getting back to me! I have had some discussion with my team and decided to add our own XDeFi Adapter, which is a replica of your MM Adapter. Only difference being that if `window.xfi` is not found, and the user clicks on the XDeFi option, it will redirect them to `https://xdefi.io`. 

I will open 2 PRs soon, one for this repository and one for your `hdwallet` repo. I hope everything is in order, but if there's any changes please don't hesitate to react out!

Thanks again for all your help :heart:

**Comment by 0xdef1cafe** [comment]
still in progress with @loxator as of 2/11

**Comment by 0xean** [comment]
xdefi team is affected by macro events and we are waiting for updates on their side.

**Comment by loxator** [comment]
@0xdef1cafe @0xean , I have just updated the [PR](https://github.com/shapeshift/web/pull/734) on the web-app, and the bug on our end has also been fixed in our new release. You should be able to proceed with testing it now and as always, thank you for your work!

**Comment by 0xean** [comment]
Currently blocked until ~4/8 pending gas api discussions.

**Comment by 0xean** [comment]
blocked by xdefi release upstream.
