### ISSUE TITLE
USDT pools have disappeared from pools list

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7205]
### Overview

USDT on ETH and USDT on BSC pools are no longer showing up in the available TC LP pools list.  There are currently users with active positions in these pools and they are unable to engage with them from the 'active pools' section either.  

### References and additional details

Jam of current list with no USDT pools available besides USDT on AVAX. 
https://jam.dev/c/422ff3aa-47f7-42cc-a229-17db17bfee82

### Acceptance Criteria

Our TC pools list reflects all available pools of chains/assets supported in ShapeShift.  Users are able to see and interact with current/new pool positions.

**Comment by 0xean** [comment]
midgard syncing which should resolve this

**Comment by kaladinlight** [comment]
Dev is synced, cut over all web environments to dev until snapshots finish and prod is back in order. Will cut back app and private at that time.
