### ISSUE TITLE
Getting 503s for basic Thorchain routes (ETH<>FOX) in Gome

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7209]
### Overview

Currently in Gome, while testing rFOX, I was able to recreate swapper errors related to Thorchain that do not exist and are unable to be recreated in prod

### References and additional details

Jam of the issue: https://jam.dev/c/1815a467-fe05-407c-b9bc-9d388ef892ae

Unable to be recreated in production currently. 

### Acceptance Criteria

Users are able to use TC trade routes through swapper and we do not have errors when fetching TC quotes.

**Comment by gomesalexandre** [comment]
Related to current midgard bork in develop, see pools calls in prod vs. develop endpoints:

<img width="264" alt="image" src="https://github.com/shapeshift/web/assets/17035424/e0e8db62-b275-42d4-bcee-4e377ff5b377">
<img width="322" alt="image" src="https://github.com/shapeshift/web/assets/17035424/e4cfb15a-cc8c-4c92-9bef-8038dc6ef2b5">
