### ISSUE TITLE
Mocks for importing custom token, showing them in the UI, and warning to users 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7212]
https://github.com/shapeshift/web/issues/6980

 figma mocks for import flows:
 - asset search / trade flow
 - warning of risks
 -  small flag / icon on imported assets 
 - importing is scoped per chain so we need a flow that allows the user to select the chain(s) that they would like to import from the custom address that they have entered.

**Comment by reallybeard** [comment]
https://www.figma.com/design/2UaOq5q4lb5EKMexrULYPd/Import-Token?node-id=1611-16323&m=dev
