### ISSUE TITLE
custom import token

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7213]
https://www.figma.com/design/2UaOq5q4lb5EKMexrULYPd/Import-Token?node-id=1611-16323&m=dev
https://github.com/shapeshift/web/issues/6980

1. implement ability to enter custom address into asset search
2. add import button in place of balance (add asset to the store and fetch market data) 
  2.1. if we cannot find market data from Cow or Lifi - then user wont be able to swap 
  2.2 add flag to manually added assets so they aren't ever going to see these assets in their portfolio 
4. warning modal 
5. group by "import token" in asset search 
6. mixpanel event fired for import so we can track usage frequency (include token addy so we can determine if we should figure out how to source that token in the future) 
7. all behind feature flag until clean up / audit is done in follow up ticket

**Comment by 0xean** [comment]
placeholder for once mocks are done

**Comment by NeOMakinG** [comment]
![image](https://github.com/shapeshift/web/assets/14963751/4a2c7edb-06a7-4d06-b9b8-b588ad722711)

I confirm we can use the `Acknowledgement` component inside a modal, it works as expected
