### ISSUE TITLE
rFOX - Remove the Tx history placeholder code

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#7215]
Tx histoyr on rFOX is just all tx history. i would imagein this is just a placeholder for now. Making this ticket so we don't forget to make it scoped to the rFOX stuff. 
![Screenshot 2024-06-24 at 1 17 08 PM](https://github.com/shapeshift/web/assets/8991325/0334b821-6271-4d2f-8a91-62e7b2445afa)

**Comment by NeOMakinG** [comment]
FYI: it's already behind a special feature flag with the dashboard, currently not displayed even if the rfox feature flag is turned on

**Comment by twblack88** [comment]
Ayyy nice!

**Comment by 0xean** [comment]
closing in favor of https://github.com/shapeshift/web/issues/7281
