### ISSUE TITLE
Add infotext modal for bridging on ARB

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#7216]
The bridge takes 15 mins and we don't have a global polling state to check on TX's finishing. So, to alert folks, we just need to hit them with the acknowledgment flow explaining the bridge timing. 

"Bridging to Arbitrum takes approximately 15 mins for the canonical bridge. If the transaction is successful to bridge, please return to the app and refresh to make sure your balance reflects the bridge transfer."

**Comment by gomesalexandre** [comment]
@twblack88 not sure what's the issue with the current flow re: 
> The bridge takes 15 mins and we don't have a global polling state to check on TX's finishing.

We already poll on Tx complete in the Arb side when depositing into Arb - and we have granular statuses in the swapper already informing of updates as they go, without needing to refresh anything? See the jams here https://github.com/shapeshift/web/pull/6977

**Comment by twblack88** [comment]
> granular statuses in the swapper

To clarify, i meant for the special cases like me who leave the swapper to go have ADHD elsewhere. 

with #7207 we have enough info that another warning is a bit much. gonna close this for now unless we hear from people that it's not clear. 

If is still confuse, we'll add it to the info text bubble
