### ISSUE TITLE
Use correct RFOX epoch start timestamp

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#7224]
### Overview

Currently, we have monkey patched the start timestamp of the first RFOX epoch in

https://github.com/shapeshift/web/blob/40d6a7cb2824b89eaab19d3839f4a75e060e5d6c/src/pages/RFOX/hooks/useEpochHistoryQuery.ts#L15-L17

However, as soon as we hit 30 days after the first rewards epoch (**WARNING**: this is 30 days later, not 1 month, which can be very very different. We want to test and merge this on Wednesday, 31 July 2024 00:00:00 GMT), we should revert this line back to its original implementation to make rewards happy.

### References and additional details

https://github.com/shapeshift/web/blob/40d6a7cb2824b89eaab19d3839f4a75e060e5d6c/src/pages/RFOX/hooks/useEpochHistoryQuery.ts#L15-L17

### Acceptance Criteria

- Rewards are happy after 30 days

**Comment by gomesalexandre** [comment]
Fine to author anytime, but can't be tested, and should not be merged before Wednesday, 31 July 2024 00:00:00 GMT.

**Comment by woodenfurniture** [comment]
Pushed #7234 to reduce the impact and risk associated with this task, so if we're late for any reason there is zero impact to produciton.

**Comment by woodenfurniture** [comment]
Marking as low priority now there is no impact in being late.
