### ISSUE TITLE
[bug] certain BTC send addresses failing 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7226]
BTC sends to 3EjBrZtPiYV5iighYA5PWd56TJ2pGo1ksS failing on app 

https://jam.dev/c/12901c3a-b6d2-4d35-86ef-b524f09eb282

not a recent regression per @0xApotheosis 

but we should route cause and understand whats wrong here, effects dont seem to be widespread. 

some notes:

- Issue is related to that address somehow, I can replicate the issue with that address, but can send to other BTC addresses just fine
- I can also send to other UTXOs just fine (e.g. DOGE)
- That address is a valid BTC address

**Comment by kaladinlight** [comment]
Closing this ticket as described. See discord thread here: https://discord.com/channels/554694662431178782/1255200582902481138

If there is still an issue, it would seem to be wallet specific and related to `utxoSelect`. Can re-open a new issue if able to recreate with more pertinant details
