### ISSUE TITLE
arb bridge in swapper

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7255]
https://www.figma.com/design/IAtOWIGhClYAj7dxC4CzhJ/ARB-Bridge?node-id=601-6732&t=dTAisubxTDEYGfNT-0

- implement claim logic as shown in mocks
- allow user to claim arb bridge assets coming back to mainnet
- use arb sdk to determine if claim is available for the user (all connected EVM accounts)
- polling at some sane interval (5+ minutes?)
- block estimation to get number of days until available 
- logic to ensure we don't show already claimed to users.

**Comment by kaladinlight** [comment]
https://github.com/shapeshift/web/issues/6979 dupe issue here so we can consolidate fyi

**Comment by gomesalexandre** [comment]
Ping @0xApotheosis is the assignment on this one for spike/ownership purposes, meaning can someone else take it? 🙏🏽

**Comment by 0xApotheosis** [comment]
@gomesalexandre someone else can absolutely take it 🙏

**Comment by 0xean** [comment]
moving this back to up next / groomed for someone to pick up. The plan per discord discussion is to release with full claim flow implemented per the AC of this ticket

**Comment by 0xean** [comment]
most of the other work has already been completed by woody prior to his leave.
