### ISSUE TITLE
token icons from coingecko 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7258]
goal: remove coincap as single point of failure 

- remove coincap
- update asset generation to use large icons from coingecko
- if needed suggest viable alternative to coingecko if we find edge cases.

**Comment by NeOMakinG** [comment]
Asked my previous mates, for reference they are using a mix of:

- [Binance Icons](https://github.com/VadimMalykhin/binance-icons)
- [Cryptofont](https://cryptofonts.com/icons.html)

To compose a CDN for the tokens icons

And they use [coinmarketcap](https://api.coinmarketcap.com/data-api/v3/uniswap/all.json) as a fallback

For the chains icons, they use https://github.com/DefiLlama/icons/tree/v2
