### ISSUE TITLE
remove restrictions on contracts interacting with TC 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7272]
The white list has been removed - 

https://discord.com/channels/838986635756044328/839001804812451873/1255927290785697833

So this means that a Safe wallet connected via WC should be able to transact with TC now. 

We should remove the restriction and test the functionality to ensure it works before rolling it out 

EDITED AS OF 7/29/24 -

Enable smart contract interactions just for swapper and not the TC defi products

**Comment by gomesalexandre** [comment]
Testing https://github.com/shapeshift/web/pull/7277 and there may be some ramifications to this - even though TC did lift the smart contract limitations, THOR Txs being happy (i.e seen by the network) is really assuming `msg.sender` is the smart contract signer, i.e connecting to a safe through WC will show the safe address as a connected address, but the `msg.sender` of the actual Tx will be whichever address executed it, i.e the last signer.

This means that while the Tx *will* be succesful (no lost funds), the THOR Tx will be seen as initiating from the signer's address, which isn't the desired behavior. This was not visible previously as we disabled smart contract wallets interaction, but may become an issue if we land that PR in.

**Comment by 0xean** [comment]
closing https://github.com/shapeshift/web/pull/7277 for now since we are going to just enable this for swapper.
