### ISSUE TITLE
Identifiers for Connect Wallet (placeholder)

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#728]
Adding ENS name or shortened address or other identifiers for the connected wallet..... 

needs detail, mocks, expected behavior per wallet type...etc.

**Comment by DiggyDiggy2** [comment]
For the wallet label: 
- Display vendor icon 
- If there is a name for the wallet display that, if there is no name display the wallet vendor
- Truncate the string using middle ellipse to prevent wrapping

* ShapeShift Native: Label or ID 
* KeepKey: Label (when we support it) 
* MetaMask: address or label (if we can get it) 
* Portis: email address

Examples: https://invis.io/XC128TD4W3EM#/462931953_Artboard_Copy_4

(you might need to use an email to view, or view as guest)

**Comment by 0xean** [comment]
![Screen Shot 2022-01-14 at 5 34 24 AM](https://user-images.githubusercontent.com/15096737/149516248-0951a042-ee39-4265-ac20-46b39797ed29.png)

Adding mock.

**Comment by amitojsingh366** [comment]
I can attempt this

**Comment by 0xean** [comment]
@amitojsingh366 to pick this one up, I will get a bounty posted for @amitojsingh366 early next week.
