### ISSUE TITLE
Filter rfox dashboard for rewards transactions only 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7281]
currently we hide all transactions in the rFOX dashboard but it really shows all tx's. Filter these for the transactions that are specific to the user. 

- display all transactions related to rewards if the user has a connected rune wallet that has received rewards
- if the user doesn't have that rune addy connected, query the most recent rune rewards address associated in the smart contract for rewards transactions.  Keep this simple for now, but be cautious if we are loading large amounts of TXs for this rune address to be parsed.  

this doesn't support users changing rune addies, multiple addies.

**Comment by woodenfurniture** [comment]
Reopening, we need this to consume IPFS data and then release with feature flag on
