### ISSUE TITLE
Add warning to swapper when bridging / swapping non-native assets 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7282]
if a user is bridging or swapping a non native asset, add warning that they will need native asset on that chain to interact with it. 

https://www.figma.com/design/IAtOWIGhClYAj7dxC4CzhJ/ARB-Bridge?node-id=601-6414&t=r2iciAw2ZiHrZMfs-0

This mock is for the arb bridge but this can be generic for the swapper any time we are going cross chain

**Comment by gomesalexandre** [comment]
We already have this for Arbitrum bridge, so it's just a matter of generalizing the checks 🎉
