### ISSUE TITLE
Cosmos SDK giving out of gas error when trying to unstake

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7294]
### Overview

Unstaking from Xosmos SDK is saying transaction successful but its failing on chain with error : out of gas

### References and additional details

![image](https://github.com/shapeshift/web/assets/100157997/7fe45e56-1337-4a15-ad60-109ff849eca8)
https://www.mintscan.io/cosmos/tx/8D20AFB5E34AB199519EBD0259BA5EFA315D87B2C4EFC09A17EC7D212438E8EC
https://jam.dev/c/97213b8f-7546-4e00-a292-7ff5dd07ca9e

### Acceptance Criteria

Should be able to unstake from Cosmos SDK

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
I have one user who is still struggling to interact with ATOM balances they have attempted to withdraw from staking positions.  

User has performed unstaking actions with 2 different wallets, both are showing no balances available to be unstaked any longer and the staked positions seem to have disappeared. 

Wallet 1: 
Unstake TXID: https://www.mintscan.io/cosmos/tx/04A158D98E7A1582264ACB171BCDC99CBB421D67A6CD90A23CEB254F836F8ED1

Users staked balance shows up as a calculation in the DeFi balance yet the position is not detected: 
![image-9](https://github.com/user-attachments/assets/eced68ea-71d3-4250-97f2-29f6c90e89df)

Users TX history identifies the transaction as an undelegate: 
![image-10](https://github.com/user-attachments/assets/405e2795-6b44-4adb-9cdb-d3e9045c1f8e)

No balance of ATOM in current position identified in Defi page: 
![image-11](https://github.com/user-attachments/assets/4e7020e4-60ab-4f90-bd5d-a1699020726c)

Balance and underlying assets identified in staking modal: 
![image-13](https://github.com/user-attachments/assets/d2d0fc28-7ac9-4bf4-a73b-67fe1162f63a)

Balance no longer identified when attempting withdraw modal: 
![image-15](https://github.com/user-attachments/assets/adbbb468-11bb-4c09-a87b-df4ec70aa290)

Balance displayed as both 0 and ~2 Atom: 
![image-16](https://github.com/user-attachments/assets/8688885c-2876-4d9f-aae3-eee9dbded422)

Undelegate transaction shown in TX history, not balance: 
![image-18](https://github.com/user-attachments/assets/8c4164b1-3ed5-4aef-a246-d6f07ebb8903)


Wallet #2: 
Unstake TXID: https://www.mintscan.io/cosmos/tx/BE285FF6BB4595D727C34C4AAE58F0DE7D9E1314BFD2CA485A2CF6959800A9CB

Users staked balance shows up as a calculation in the DeFi balance yet the position is not detected:
![image-19](https://github.com/user-attachments/assets/5317a578-d117-49eb-b4dd-d95113359c74)

TX history shows undelegate, ATOM balance does not recognize balance change: 
![image-21](https://github.com/user-attachments/assets/5602d18c-a0e3-4dc5-93c4-c98f24de32ff)

Position appears no longer active in Defi page, balance still shows in Defi total balance: 
![image-22](https://github.com/user-attachments/assets/a51dbb6a-9068-4d48-9fab-64e66154253a)

Balance and underlying assets identified in staking modal: 
![image-23](https://github.com/user-attachments/assets/9a2949fe-466f-4eb8-b039-662d1d181abd)

Balance discrepancies in withdraw modal: 
![image-25](https://github.com/user-attachments/assets/e48a0df9-8c19-4cf6-b739-1fe7e5fb393f)

Undelegated transaction shows up in TX history, not in asset balance: 
![image-27](https://github.com/user-attachments/assets/7bb368e7-17dc-4c06-80c4-3c8616832e3e)

User has performed many clear caches with no change in balance display or ability to engage with their staked (or are they unstaked now?) positions. 

If there is more information that would be helpful to be gathered from the user, please let me know and I can request more information.

**Comment by 0xean** [comment]
Adding notes from conversation with Tyler - 

from what I can tell the user has undelegated but has not waited the needed 21 days to claim back their balances.  So this might be a case of needing better UX to show a user this state and how much longer they will need to wait to claim back their delegated balances.

**Comment by 0xean** [comment]
<img width="218" alt="Screenshot 2024-08-22 at 2 53 59 PM" src="https://github.com/user-attachments/assets/bf48bbbf-3a92-47b0-a8bf-975241e7d83f">
It looks like we have a section for this, but isn't showing up, so this may be the actual bug

**Comment by 0xean** [comment]
since this is unrelated to the original ticket, I am gonna open a new one to address the missing pending undelegations.

**Comment by 0xean** [comment]
https://github.com/shapeshift/web/issues/7608 <- closing in favor of this guy
