### ISSUE TITLE
Use tsx instead of ts-node

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/web#7300]
### Overview

ts-node sux, tsx rox

### References and additional details

https://github.com/privatenumber/tsx

### Acceptance Criteria

- install `tsx` as dev dependency
- remove `ts-node` dependency
- replace all instances of `ts-node` with `tsx`
- validate everything still works

**Comment by NeOMakinG** [comment]
Another argument in favor of TSX:

`--inspect-brk` works with `tsx` while `ts-node` requires to use `node --inspect-brk -r ts-node/register myFile.ts`
