### ISSUE TITLE
rune pool implementation in savers 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7302]
https://www.figma.com/design/8SLOPbPAjOWILIgvDv39jB/RUNEPool?node-id=1603-773&t=dE7c6hhx54pniLle-0

- feature flag
- ~~fees~~
- implement rune pool into savers
- support for multi account
- source data / maths for APY since rune pool isn't actually a saver 
- https://gitlab.com/thorchain/thornode/-/issues/1841
- https://gitlab.com/thorchain/thornode/-/merge_requests/3612

**Comment by 0xean** [comment]
ETA is ~ next week for prod launch according to 9r

**Comment by reallybeard** [comment]
We already had an introduction screen for RUNEPool, so here we will add a checkbox that they agree that they understand RUNEPool has impertinent loss, with a link out to a relevant article. 

User cannot continue to the next screen until they have agreed. 

https://www.figma.com/design/8SLOPbPAjOWILIgvDv39jB/RUNEPool?node-id=1603-681&t=NL4qVDS7qB8TfKKr-0
