### ISSUE TITLE
Trade modal via accounts page does not reflect selected asset

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7316]
### Overview

Currently in Production, the trade modal is always ETH to FOX no matter what coin is selected when visiting from the trade page. From the asset page, the trade modal is ETH into the asset you are viewing. The Accounts page has the same logic as the trade page currently and displays ETH > FOX, this does not change like it does in the assets page to mirror the selected asset by the user

### References and additional details

![image-8](https://github.com/shapeshift/web/assets/94998097/085d6669-50ce-47e3-a457-1713654a074a)
Image of ETH> FOX in the trade modal while navigating the Cosmos account page^

### Acceptance Criteria

If desired, the accounts page trade modal logic should match the same logic as the asset page.

**Comment by reallybeard** [comment]
This seems pretty straight forward, the asset should reflect the current page you are one either account or asset page.

**Comment by 0xean** [comment]
@purelycrickets - can you repro and help with steps to do it / jam it? 

seems like works correctly on happy path

**Comment by 0xean** [comment]
https://app.shapeshift.com/#/wallet/accounts/cosmos:cosmoshub-4:cosmos1k0q3reyg3q5as0uu4xy0ptfnynjrspw70vwyd7/cosmos:cosmoshub-4%2Fslip44:118

repro'd using the wallet page as linked above
