### ISSUE TITLE
Help adding rFOX voting power to SnapShot voting strategy

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7332]
### Overview

GK needs some help with getting the rFOX voting strategies added to Snapshot.  

We are unsure of the strategy and strategy parameters necessary to add rFOX balances to the Snapshot strategy successfully. 

Attempts at adding the rFOX contract as 'erc20-balance-of' failed. 

### References and additional details

Here are the current strategies allowed: 
Multichain
[multistrategy snapshot.txt](https://github.com/user-attachments/files/16132373/multistrategy.snapshot.txt)
Contract call: 
[ContractCall Strategy.txt](https://github.com/user-attachments/files/16132383/ContractCall.Strategy.txt)

Here is the list of possible strategies able to be used at Snapshot: https://snapshot.org/#/?filter=strategies

### Acceptance Criteria

GK is able to make the adjustments in SnapShot, We need help identifying the proper strategy style to add the contract successfully.  

If this strategy can be identified/provided, GK can make the changes in SnapShot.

**Comment by 0xean** [comment]
I just attempted the balanceOf in the playground and it works correctly. 

<img width="456" alt="Screenshot 2024-07-08 at 12 44 23 PM" src="https://github.com/shapeshift/web/assets/15096737/d01f9a1f-e258-4d65-b6e3-c22bf61ad39f">
<img width="224" alt="Screenshot 2024-07-08 at 12 44 36 PM" src="https://github.com/shapeshift/web/assets/15096737/c7d25223-aedf-4480-9e24-e0300c08821b">


Link here -https://snapshot.org/#/playground/erc20-balance-of?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4YWMyYTRmZDcwYmNkOGJhYjA2NjI5NjA0NTVjMzYzNzM1ZjBlMmI1NiIsInN5bWJvbCI6IiIsImRlY2ltYWxzIjoxOH0sIm5ldHdvcmsiOiI0MjE2MSIsInNuYXBzaG90IjoiMjMwMTM4MDUzIiwiYWRkcmVzc2VzIjpbIjB4ZTkzM0JkNDNBQWUwNjQ0RkRBZDIzNDJENTYyNDZjMjk5ZmJFZTcyQiJdfQ..
