### ISSUE TITLE
rfox dashboard support for multi-account

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7336]
- support for multiple accounts in the rFOX dashboard
- allow user to toggle between accounts to view them in a segregated fashion
- @shapeshift/product to provide some mocks

**Comment by reallybeard** [comment]
Here is a link to how we could handle the account toggle, similar to how we handle this for earn opportunities.
https://www.figma.com/design/REOouo0sAuOhoD597yZEGE/rFOX?node-id=635-4708&t=Nm0oGVZzPjr6vTTq-0

User can toggle between their accounts for the dashboard view. 

TBD: Should we sync the right widget with this selected account? So whatever account you have selected in this dropdown, will also change the selected account on deposit/withdraw/etc.

**Comment by 0xean** [comment]
> TBD: Should we sync the right widget with this selected account? So whatever account you have selected in this dropdown, will also change the selected account on deposit/withdraw/etc.

We will synchronize. Changing dashboard will affect the other transaction flows
