### ISSUE TITLE
Ledger trades stuck at signing when app not opened prior

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#7339]
### Overview

If the user does not have the relevant ledger app open on the device at the time of tx signing, the app spins infinitely until the user goes back.

The app should disable the "sign transaction" button until the ledger app is open. Additionally there should be some sort of prompt to let the user know to open the relevant app on the device, like account management does.

### References and additional details

Infinite spinner when opening bitcoin app after clicking "sign transaction"

![image](https://github.com/shapeshift/web/assets/125113430/2910a910-d865-4333-9664-bd8a543874ba)

### Acceptance Criteria

Should be impossible to get into a state where a transaction is stuck due to ledger app not being open at the time of signing.

**Comment by woodenfurniture** [comment]
@shapeshift/product tagged at needs product for UX details on flow

**Comment by twblack88** [comment]
Acknowledgement trigger probably is best here.

**Comment by reallybeard** [comment]
@woodenfurniture what do you think about this:

If we detect the ledger app is not open, we should disable the sign transaction button. And pop open the ACK for connecting to the app on ledger.

Here is an example of this would look, very similar to the account management flow.

![Screenshot 2024-07-11 at 4 57 41 PM](https://github.com/user-attachments/assets/fdebaf56-d5b7-49c9-b6bc-88a68dbbfb38)

**Comment by 0xean** [comment]
related to #7374

**Comment by reallybeard** [comment]
@shapeshift/product talked it over with @woodenfurniture and we decided the easiest way to get this done was to pop this open in a modal instead of the ack. Which I think totally works in the case.
