### ISSUE TITLE
App boots user out when amount acknowledgment appears

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#7340]
### Overview

When trading a small amount, sometimes the app will boot a user out of the app when the acknowledgement appears.

### References and additional details

https://github.com/shapeshift/web/assets/125113430/5a5f3030-4934-4644-9532-238bd08c1f88

### Acceptance Criteria

User should not get booted out of the app when acknowledging minimum amounts.

**Comment by 0xean** [comment]
probably related to #7384

**Comment by NeOMakinG** [comment]
> probably related to #7384

Confirmed it's the same bug
