### ISSUE TITLE
Verify addresses UX flow improvements

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#7342]
### Overview

The current ledger swapper verify addresses flow is not clear for a user who has not successfully gone through this flow in the past.

All that's displayed is "verify BTC" with no other information. The user is able to click the button without the ledger app open on the device, which does nothing. Until the user figures out they need to open the correct app on the device for that asset, they are stuck.

![image](https://github.com/shapeshift/web/assets/125113430/967ba2d3-69c0-4d99-b845-e51fb9fd32e3)

### References and additional details

Current flow

https://github.com/shapeshift/web/assets/125113430/839a2c96-8d42-4d67-b204-4c81b1789459

### Acceptance Criteria

1. App steps the user through verify each address via some sort of stepper
2. App will disable the button until the correct app is open on the device (we do this for account management so its doable)
3. App will actually tell the user what they need to do

**Comment by reallybeard** [comment]
@woodenfurniture thinking we could leverage the same ACK we would use on trade here.

If user clicks verify [asset], we will pop up the ACK and once we've detected the app is connected, close the ACK and verify the address.

Here is the reference again:
![Screenshot 2024-07-11 at 4 59 08 PM](https://github.com/user-attachments/assets/4c03ecf8-0a3c-46ab-9c6c-8b3f9c798c88)

**Comment by twblack88** [comment]
We need to double check that we can verify the app is open on the device and make sure the toasts fire; that seems to be part of the issue too.

**Comment by reallybeard** [comment]
Same solution here - https://github.com/shapeshift/web/issues/7339#issuecomment-2237699632

**Comment by 0xean** [comment]
@0xApotheosis to shepherd through
