### ISSUE TITLE
Swapper UI breaks during trade execution

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#7347]
### Overview

The UI breaks from signing onwards. See screenshots

### References and additional details

![image](https://github.com/shapeshift/web/assets/125113430/68a79ae0-0faa-41b6-9635-3b3eeff1c1d5)
![image](https://github.com/shapeshift/web/assets/125113430/fed5a7b2-743a-4b74-8f3a-5c0bac89ccea)
![image](https://github.com/shapeshift/web/assets/125113430/2b0ed8d2-b472-4799-9e88-83d36ec1aa3e)

### Acceptance Criteria

Fix regression in display of trade execution

**Comment by woodenfurniture** [comment]
jam
https://jam.dev/c/4d0b7cc0-d999-4234-8271-776196dd7384

**Comment by 0xApotheosis** [comment]
Also getting this:

<img width="350" alt="Screenshot 2024-07-10 at 10 41 21 AM" src="https://github.com/shapeshift/web/assets/97164662/2a76e194-f00e-42cd-b4ed-cf8f460edb1c">
