### ISSUE TITLE
Send To Bitcoin modal address box whitespace can be trimmed

### ISSUE THREAD

**Issue by Neverwas-dev** [shapeshift/web#735]
- Brief description
When placing an BTC address in any of the different formats it leaves a trailing whitespace. This can be truncated to reflect the shorter BTC addresses.

- Steps to recreate
Choose to send BTC and paste or enter a address in the send modal.
Note the trailing whitespace in the address bar

- Screenshots/vids
![unknown](https://user-images.githubusercontent.com/95000549/149373542-c1e8f4c0-fdd5-4e7a-aa69-114f4560cfdf.png)

- AC (acceptance criteria)
Remove un-needed trailing whitespace on the send address bar

**Comment by 0xApotheosis** [comment]
I'll get this done shortly.

**Comment by 0xApotheosis** [comment]
Resolved by https://github.com/shapeshift/web/pull/803
