### ISSUE TITLE
Add Cosmos Nodes to nownodes monitoring

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7354]
### Overview

The current list of nodes monitored that are being provided by NowNodes at: https://nownodes-1712072512758.site24x7statusiq.com/ is not a complete list of nodes we currently consume. 

### References and additional details

https://nownodes-1712072512758.site24x7statusiq.com/

No Cosmos (also no BASE or RUNE) 

### Acceptance Criteria

Have https://nownodes-1712072512758.site24x7statusiq.com/ monitoring match the nodes we currently consume from Now Nodes.

**Comment by 0xean** [comment]
closing 

https://nownodes-cosmos-1720629913743.site24x7statusiq.com

single status page is at limit
