### ISSUE TITLE
Unable to trade into/out of RUNE 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7355]
### Overview

Currently in production, users are unable to make trades.  to/from RUNE through ShapeShift.  

This issue is not directly related to a specific wallet and has been recreated on Ledger and ShapeShift native. 

### References and additional details

Users are able to enter trade details, but the 'Preview Trade' button is never clickable once the trade details have been selected. 

Ledger jam: 
https://jam.dev/c/6e2595b1-3b68-4092-b05e-b3b65e014def

Native jam: 
https://jam.dev/c/8124907b-a91b-4032-bee2-211d5e6aedd9

### Acceptance Criteria

Users should be able to trade to and from RUNE successfully with all wallet types.

**Comment by purelycrickets** [comment]
Looks like we might not be the only ones experiencing the issue, Trust wallet also having issues: https://x.com/0xSaigon/status/1809258817974354340

**Comment by woodenfurniture** [comment]
issue seems isolated to certain pairs, can trade ETH <> RUNE

![image](https://github.com/shapeshift/web/assets/125113430/b3c29ecb-1ef4-4b6c-8439-52235fc597e4)
