### ISSUE TITLE
Update the PR template file to reflect the new release process.

### ISSUE THREAD

**Issue by Neverwas-dev** [shapeshift/web#737]
- Brief description
PR template can be updated to reflect the updated release process with the questions and steps needed for pushing a PR in Github

- Steps to recreate

- Screenshots/vids

- AC (acceptance criteria)

**Comment by 0xean** [comment]
Remove " Do all new and existing tests pass? Does the linter pass?"

**Comment by 0xdef1cafe** [comment]
done in https://github.com/shapeshift/web/pull/865/files
