### ISSUE TITLE
rFOX tx history of position related transactions in the rFOX page

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7375]
### Overview

Currently there is no log/tx history of all rFOX related transactions to users that have made multiple deposits.  

This feels like a feature request, but with the dashboard still being built out a github ticket felt appropriate. 

### References and additional details

Please add a tx history for the rFOX page that tracks all related transactions :pray

### Acceptance Criteria

a functional TX history log in the rFOX page

**Comment by NeOMakinG** [comment]
Do we really want to display every TXs related with rFOX? I think we initially wanted to display rune rewards TXs

If you are right, we might want to update https://github.com/shapeshift/web/issues/7281 and close this one as a duplicate, or mark this one as a follow up

**Comment by 0xean** [comment]
https://www.figma.com/design/REOouo0sAuOhoD597yZEGE/rFOX?node-id=635-4708&t=B4RRhz15w0iwambE-0

Add a new tab to the rFOX dashboard called "Actiivity" that shows tx history (on arb only) including:

- stake
- unstake
- change address
- NOT claim ( as this is shown already)
- NOT bridge
- NOT rewards
