### ISSUE TITLE
rFOX deposits from a ledger device wipe the USD value of rewards balance

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7377]
### Overview

This issue has only been able to be recreated with ledger devices.  New deposits from a ledger device wipe the USD value of the rewards in RUNE to 0.  

### References and additional details

[ttps://jam.dev/c/9ee11875-37a5-4391-ad60-9f60829d3d74](https://jam.dev/c/9ee11875-37a5-4391-ad60-9f60829d3d74)

Jam of the issue in production via chrome opposite a firefox browser of the same wallet connected via Metamask that is not experiencing the issue.  The firefox balance is more an anomaly than part of the issue. 

### Acceptance Criteria

Staking deposits from Ledger devices to rFOX do not wipe out the USD value of rewards earned.

**Comment by purelycrickets** [comment]
@MBMaria to jam a recreation of the issue in action. 🙏

**Comment by 0xean** [comment]
#7366 may resolve this. @woodenfurniture to confirm and close if so.
