### ISSUE TITLE
Refresh not bringing in balance, need to clear cache 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7378]
### Overview

Normally if a balance doesnt update you can refresh to get the new balance but we are experiencing a lot of cases when the user needs to clear the cache before the balance comes in

### References and additional details

Send of fox on eth from kk to mm. 
Initial load did not show the increase in balance. Refresh did not update balance but did bring tx into recent transactions. 
Clear cache updated balance
https://jam.dev/c/4e5ba505-da65-4f96-b66f-7b26db5bf001

### Acceptance Criteria

Refresh should update wallet balance

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
closing for #7214
