### ISSUE TITLE
Handle send errors

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#738]
Currently, as a user when trying to send some asset then changing my mind, I can see a toast with copy:

![image](https://user-images.githubusercontent.com/17035424/149370756-a61d0d7c-235a-4382-96ea-44c320a1f279.png)

- `%{asset} sent` as a header
- Something went wrong as a message

What I would like to see is what went wrong.

Metamask throws this on transaction declined by user:

```javascript
{
    "code": 4001,
    "message": "MetaMask Tx Signature: User denied transaction signature."
}
```

Questions:

1. Is it possible to handle them in `chain-adapters` similar to swap errors? **Yes, it is ✅** 
2. If the answer to 1. is yes, should the errors be chain-agnostic or do we want to handle metamask ones specifically? Either way, we should investigate all the possible error codes.

**Comment by gomesalexandre** [comment]
Errors are originally thrown in https://github.com/shapeshift/hdwallet/blob/master/packages/hdwallet-metamask/src/ethereum.ts#L86 in the following shape:

```javascript
{
    "code": 4001,
    "message": "MetaMask Tx Signature: User denied transaction signature.",
    "stack": "{\n  \"code\": 4001,\n  \"message\": \"MetaMask Tx Signature: User denied transaction signature.\",\n  \"stack\": 
}
```
    
 
https://docs.metamask.io/guide/ethereum-provider.html#errors

Since we build the requests ourselves and they should be valid, I don't think it makes sense to handle the "Internal error" and "Invalid params" errors, we can throw in https://github.com/shapeshift/lib/blob/main/packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts#L214 (as we already do) and handle this specific error `Error signing & broadcasting tx'` in the `useFormSend` error toast (https://github.com/shapeshift/web/blob/develop/src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx#L100) for now.

**Comment by 0xean** [comment]
resolved.
