### ISSUE TITLE
Unable to withdraw or claim Cosmos SDK

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7389]
### Overview

When trying to withdraw from Cosmos SDK, selecting continue gives error "Something went wrong". 
Whent trying to claim rewards, it just spins continuously and doesnt progress. 

### References and additional details

Withdraw: https://jam.dev/c/798b488a-d709-4983-b090-1b1e18700621

Claim: https://jam.dev/c/cc48235b-e65b-4658-9ef0-458baf42cf50

### Acceptance Criteria

Should be able to interact with cosmos SDK 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by kaladinlight** [comment]
https://github.com/cosmos/gaia/pull/3028

looks like a breaking change last update. no longer self hosting so haven't been paying as close of attention, but looks like I will need to start...

**Comment by kaladinlight** [comment]
https://github.com/shapeshift/unchained/pull/1010

**Comment by kaladinlight** [comment]
@MBMaria pushed the backend fix to prod if you can verify on your end when available. I tested in develop and was able to successfully withdraw/claim
