### ISSUE TITLE
Yearn Overview Page doesn't update unless you refresh the page

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#740]
Please write a short description of the issue:
The earn page overview won't update unless you refresh the page, still shows the withdrawn amount

Reproduction Steps:
1. Visit https://app.shapeshift.com/earn/
2. Add into the yearn vault of your choosing
3. Withdraw from yearn vault
4. Look at the overview page and notice it still shows that yearn vault that you withdrew from

Acceptance Criteria: 
-  Earn overview page should update without having to refresh the entire page.
- Once the fix is in place have Ops test before moving to prod

Join our discord [here](https://discord.gg/shapeshift). Once you join you can see more about this issue [here](https://discord.com/channels/554694662431178782/873244924026449940/925799058537336853)
 Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
 Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info

**Comment by tshifty** [comment]
![ShapeShiftYearnShowingthewrongvault](https://user-images.githubusercontent.com/94189400/149401438-7fc21233-4f9b-4c3e-bfb5-350d921919db.jpg)
![ShapeShiftYearnCorrectamount](https://user-images.githubusercontent.com/94189400/149401467-2c729f28-5a77-46f0-8f43-e92d89fd8991.jpg)

**Comment by 0xdef1cafe** [comment]
root cause #706
