### ISSUE TITLE
rFOX actions dead clicks

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7400]
https://jam.dev/c/9fca0710-8e99-4455-b53a-f8152b5430a3

attempting to interact with rFOX stake, unstake, etc are all dead clicks

reproduced on both rabby and native wallet using chrome

**Comment by 0xean** [comment]
uninstalling Jam seems to resolve this issue, attempting to confirm now

**Comment by MBMaria** [comment]
Unable to recreate - was able to stake and unstake on native wallet just now
Are you still experiencing this @0xean ?
![image](https://github.com/user-attachments/assets/f62c0ff9-bc4f-490a-ae3b-58205dfd7df1)
![image](https://github.com/user-attachments/assets/ae63912f-32d0-44e1-b3fd-d781929c597d)

**Comment by 0xean** [comment]
Yes, its reproducible. Steps

1. reload page one https://app.shapeshift.com/#/rfox or start from there with a native wallet already selected so it just prompts for pw
2. unlock native
3. dead clicks moments later.

**Comment by 0xean** [comment]
It doesn't occur if you load from main route (https://app.shapeshift.com/) with wallet not connected.

**Comment by 0xean** [comment]
https://jam.dev/c/d9a1071d-ef42-4143-a83d-72a2d26dcd9c another Jam with a happy path and a broken path

**Comment by 0xean** [comment]
@MBMaria

**Comment by MBMaria** [comment]
Doing the same steps I can still interact with the rFOX modal from a fresh import and after a refresh on the rfox page. :woman_shrugging:  perhaps as i have a longer to pass word, having the additional seconds to load makes a difference?
https://jam.dev/c/dc216047-a4a4-4595-b744-058d81f31601

**Comment by NeOMakinG** [comment]
I couldn't reproduce on my side too

https://jam.dev/c/d57c6852-3a71-4535-8503-b4a39cc61ece

We might be able to close this one except if @0xean reproduces it

**Comment by gomesalexandre** [comment]
> Yes, its reproducible. Steps
> 
> 1. reload page one [app.shapeshift.com/#/rfox](https://app.shapeshift.com/#/rfox) or start from there with a native wallet already selected so it just prompts for pw
> 2. unlock native
> 3. dead clicks moments later.

Was unable to repro either @0xean https://jam.dev/c/088d153f-ba1b-4ac1-b8b0-c5fe8f98d384

Note the slowness in caused by lazy module imports and slow tethered connection, which as @MBMaria stated could be the same reason why she was unable to repro (i.e if we load very very fast then this may happen as a race condition, but in slower scenarios may not be obvious)

**Comment by 0xean** [comment]
still reproducible for me...

**Comment by 0xean** [comment]
> https://jam.dev/c/d57c6852-3a71-4535-8503-b4a39cc61ece

the native wallet needs to be already selected, and then refresh, enter password, and voila... dead clicks (atleast for me)

**Comment by 0xean** [comment]
https://jam.dev/c/fe0bf0c9-dce0-4955-bb2a-b4dc7979c08b another repro

**Comment by gomesalexandre** [comment]
@0xean looking at your last two Jams, is this an account active in RFOX? Or are the zero'd out values across the widget and dashboard incorrect? https://jam.dev/c/d3001f2a-1dcc-4da1-b577-ba1209f8dc9b FYI this is native after a refresh and unlock

**Comment by 0xean** [comment]
cannot reproduce on local dev environment unfortunately.

**Comment by 0xean** [comment]
Gonna close this as its seems its some sort of rare edge case (extension or something) and not worth troubleshooting further.
