### ISSUE TITLE
rFOX on Earn page needs refresh to update balance

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7417]
### Overview

When staking fox on rFOX page, the balance updates automatically. However, the balance shown on the earn page only updates after a refresh 

### References and additional details

https://jam.dev/c/80be1c51-cf65-47e6-8934-9885d387e3f2

### Acceptance Criteria

Balance on earn page should update automatically

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by Emmanueltech** [comment]
Hi I would like to work on this

**Comment by gomesalexandre** [comment]
@NeOMakinG if you want to take on that one, this should be a few-liner to `getOpportunitiesUserData.initiate()` RFOX user data
