### ISSUE TITLE
Trader Joe assets push network name out of box on trade modal on asset page

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7418]
### Overview

When selecting a trade joe asset on the asset page, the network name is too long for the box 

### References and additional details

![image](https://github.com/user-attachments/assets/100e6154-d4e2-48f6-a441-6b6cd8fac34c)

### Acceptance Criteria

Network name should fit in box

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
@shapeshift/product could you please help us with this? I don't want to take a decision on my own as we have multiple solutions

**Comment by reallybeard** [comment]
> @shapeshift/product could you please help us with this? I don't want to take a decision on my own as we have multiple solutions

@NeOMakinG We can either truncate the text inside the network selector, or wrap the network selector below the asset. I'd have to see how either of those look though.

**Comment by 0xean** [comment]
Set max length to truncate and provide tooltip to show full name for both asset name and chain
