### ISSUE TITLE
Fees estimation for quotes failing EVM simulation

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#7434]
### Overview

Currently upstream, *some* swappers do have some magic to do fees estimation for Txs with:

- allowance not yet granted for that amount 
- not enough token to transfer for a Tx with token transfer
- not enough native asset for a native asset Tx
- not enough native asset for gas fees

They usually expose this as an optional `validate` option, see e.g ZRX enforcing validation at trade execution with the `priceOrQuote` option

https://github.com/shapeshift/web/blob/c3bac3d447f8aff54f9257002aca62aaab9a2153/packages/swapper/src/swappers/ZrxSwapper/endpoints.ts#L45-L47

but ditching validation and letting ZRX do its magic at `quote` time:

https://github.com/shapeshift/web/blob/c3bac3d447f8aff54f9257002aca62aaab9a2153/packages/swapper/src/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts#L74-L75

Arbitrum Bridge is an example of a swapper which does *not* support such magic, and the WIP Portals swapper will be another one.

We should implement the samg magic as upstream to allow fees estimates in this case.

 

### References and additional details

This could be implemented with something like this (pseudo-ish code):

```typescript
const getDummyQuoteParams = (assetId: AssetId) => {
  const chainId = fromAccountId(assetId).chainId
  const dummyAccountId = `toAccountId(vitalikAddyToAccountIdParams)
  const isNativeAsset = !isToken(fromAssetId(assetId).assetReference)

  const dummyAssetId = isNativeAsset ? assetId : wethAssetId

  return {accountId: dummyAccountId, assetId: dummyAssetId}
}
```

i.e the naive implementation is:

- take `vitalik.eth`'s addy
- if swapping a native EVM asset, no problem, this address is more than well funded
- if swapping an EVM token, replace the token being swapped with ETH

Once you get those dummy params, make a second, dummy request upstream in case the first one fails simulation with those params, and voila 🎉  you get a new quote/Tx data can succesfully be simulated!

Obviously, we may want to have an address per chain if `vitalik.eth`. doesn't work for all of our EVM chains, as well as possibly changing the dummy token per chain, but the high-level idea is here

### Acceptance Criteria

- We can get dummy params to be used for swappers to get a dummy quote in case the quote's Tx cannot be simulated for the user's address

**Comment by suhailgme** [comment]
@gomesalexandre just came across this. We are implementing improved simulations which will return accurate estimates/gas even if the sender doesn't have the tokens or approvals in place. Should be about 2-3 weeks and will use the same /estimate endpoint with no changes needed.

**Comment by gomesalexandre** [comment]
That sound sperfect @suhailgme! Let us know when that's implemented, we may even revert this guy to leverage *only* upstream estimates again.

**Comment by gomesalexandre** [comment]
Also: closed by https://github.com/shapeshift/web/pull/7439
