### ISSUE TITLE
Persist dynamic assets

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#7437]
### Overview

We have a few places dynamic assets are created, but the state is not preserved on refresh.

- Custom asset creation

https://github.com/shapeshift/web/blob/30a96d6179f7f393ad7b51b89d49ba7a78a22774/src/components/TradeAssetSearch/components/SearchTermAssetList.tsx#L87

- Asset creation on initial TX history load:

https://github.com/shapeshift/web/blob/c3bac3d447f8aff54f9257002aca62aaab9a2153/src/state/slices/portfolioSlice/portfolioSlice.ts#L208

### References and additional details

For each of the cases above, the assets that are made are lost when refreshing the app.

In the case of the assets made from the portfolio slice, the only way to get these assets generated again is to clear the cache and reload the transactions.

For the custom assets, they need to be re-imported

### Acceptance Criteria

These "dynamic" asset creations should persist until the cache is cleared.

**Comment by 0xean** [comment]
closing as related to #7214
