### ISSUE TITLE
Improve displaying of Portals LP assets

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#7452]
### Overview

Currently in develop, Portals assets look like this:

<img width="448" alt="image" src="https://github.com/user-attachments/assets/2ace8c3b-f597-4d0d-8d49-be0216cde894">
<img width="1425" alt="image" src="https://github.com/user-attachments/assets/2b360588-b75b-46ac-be59-6b339c6112c0">

That's an extreme example of a many many assets LP, but a regular 2 assets LP would look like this:

<img width="695" alt="image" src="https://github.com/user-attachments/assets/875ab924-3f3a-4bb1-8e38-df147abaa81a">

In comparison, ETH/FOX and other UNI-V2 pools look like this

<img width="967" alt="image" src="https://github.com/user-attachments/assets/1d0c8c41-cc5a-4a2f-bb8e-136d6927063c">

We should use similar logic as the previous UNI-V2 asset-service logic (and remove it while at it) to get consistent pretty names and while at it, improve how we do icons

### References and additional details

https://github.com/shapeshift/web/blob/a0bd379079edf91750dfad9c911c9b2e57982a92/scripts/generateAssetData/ethereum/uniswapV2Pools.ts#L91-L93

### Acceptance Criteria

- We use a consistent naming for LP assets (see references above)
- Agree with a better way to display many icons with @reallybeard and implement it
- Remove the previous `getUniswapV2Pools` implementation in favor of portals

**Comment by gomesalexandre** [comment]
Adding to the list of visual issues:

https://discord.com/channels/554694662431178782/1268691088185491538/1268734472396865639

> asset icon kinda bunched up - not sure if there is a better way to display?
![image](https://github.com/user-attachments/assets/13cf8c1e-3961-4cd2-989f-b53b06a2f548)
![image](https://github.com/user-attachments/assets/812c5814-b390-4d6d-8a88-8c1e23ee1caf)
![image](https://github.com/user-attachments/assets/03a8dc3f-aa2c-4e4e-ae4a-a010c025ee07)

https://discord.com/channels/554694662431178782/1268691088185491538/1268737713402806336

> placement of icon is to the left, opposed to being in the centre
![image](https://github.com/user-attachments/assets/8db177cd-31ed-490d-bcc4-b279d56ce8e7)

**Comment by NeOMakinG** [comment]
Also 
![image](https://github.com/user-attachments/assets/aefa439b-eb2b-44c2-a381-93eeac09ba98)
is not super sexy

Even worse with multiple assets
![image](https://github.com/user-attachments/assets/1517e285-6472-4211-860b-9bc4a9895a6f)
