### ISSUE TITLE
Asset in trade modal only showing first 1 or 2 letters

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7499]
### Overview

The trade modal only shows the first 1 or 2 letters of assets . Also happening in rFOX and loans, when selecting the asset to repay

### References and additional details

![image](https://github.com/user-attachments/assets/fb613ebd-4d00-4a8f-89b4-9588e99d12d1)
![image](https://github.com/user-attachments/assets/71f52218-787c-4429-b613-c244173bb743)
![image](https://github.com/user-attachments/assets/d2f10903-f0c3-4331-a796-bdd2a5aead46)

### Acceptance Criteria

Should have at like 3? letters ?

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
Worth mentioning that this can be only reproduced by browser zooming to some levels (67%, 110%...)
