### ISSUE TITLE
data - account to portfolio, exclude asset ids we don't have asset data for

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#750]
note - this isn't required for v2 launch, should be done anyway, can easily be bountied.

users often have a bunch of shit tokens in eth accounts that we don't have asset data for

in here https://github.com/shapeshift/web/blob/develop/src/state/slices/portfolioSlice/portfolioSlice.ts#L201

we shouldn't add these to their portfolio if `if (!state.assets.ids.includes(assetId))` - as this may have flow on breaking changes throughout the app if there are assets we don't support

**Comment by chxash** [comment]
I can work on this one

**Comment by 0xean** [comment]
@chxash - I would like to get you a tip for your work here. Can you help me to know roughly how many hours you spent on this?

**Comment by chxash** [comment]
@0xean I think I spent something like 10 hours on this between the original code and the merge, but I was pretty slow and learnt a lot, so do as you wish ! Thank you !
