### ISSUE TITLE
Warning for MAX deposit into THORCHain savers

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7529]
### Overview

When depositing into THORChain Savers, it gives you an option to deposit the max balance. If you do this, you need additional funds to pay for the withdraw fee. Can we add a warning if you deposit max amount that you might get stitched up down the line?

### References and additional details

![image](https://github.com/user-attachments/assets/c0011f0c-5f93-4d64-8074-6acf780a01fc)

### Acceptance Criteria

Potentially add a warning about consequences of max deposit

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
will discuss with team today, may be easiest just to remove the max option for RUNE pool

**Comment by 0xean** [comment]
closing as expected behavior... blockchains...
