### ISSUE TITLE
test - update useSendDetails test (currently skipped with account changes)

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#755]
talk to engineering before doing this, we may want to clean up the useSendDetails implementation before making the tests work

**Comment by 0xean** [comment]
- unskip tests, make changes to allow them to pass. 

"JUST UN-JANK IT" - @0xdef1cafe

**Comment by 0xean** [comment]
haha - @chxash - thanks for saving me a bounty to post! Tip incoming!!

**Comment by chxash** [comment]
@0xean thank you !
