### ISSUE TITLE
rune distribution show -- for date

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7558]
<img width="806" alt="Screenshot 2024-08-16 at 5 41 56 PM" src="https://github.com/user-attachments/assets/727c2e40-42d3-4111-8a0b-e0054a16374b">

Clicking on the tx detail for a rune distribution shows `--` instead of a date

**Comment by NeOMakinG** [comment]
![image](https://github.com/user-attachments/assets/5777cb59-d1bb-400e-9be5-12929813139f)

Might be a cache issue?

**Comment by 0xean** [comment]
closing for now.  Also wasn't able to repro quickyl
