### ISSUE TITLE
Portals Mixpanel Tracking tags

### ISSUE THREAD

**Issue by hpayne1** [shapeshift/web#7562]
- confirm mix panel tracking is working with portals
- if not, implmenet basic tracking that we have in other swappers for portals

**Comment by 0xean** [comment]
cc @shapeshift/product - we should make sure mixpanel tracking (if desired) is part of the spec up front.  I believe the intention was on-chain tracking for this feature.

**Comment by 0xean** [comment]
@hpayne1 - can you please be more specific and list out " all key interaction points " that you would like instrumented?

**Comment by 0xApotheosis** [comment]
@hpayne1 can you please confirm what you'd like to see here?

I've confirmed that we are correctly sending Mixpanel events for Portals swaps, see example below (the `swapperName` key:

<img width="1870" alt="Screenshot 2024-08-23 at 11 11 18 AM" src="https://github.com/user-attachments/assets/d8caf396-1ffb-40b9-a737-b38667992739">

**Comment by 0xApotheosis** [comment]
Closing as has been stale for 2 weeks, and should be resolved.
