### ISSUE TITLE
Portals pricing Vaults inconsistenly

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#7564]
The portals team pointed out that vaults can be tricky to price. Primarily b/c coingecko doesn't get it right. things like yearn v2, v3, pooltogether, beefy, harvest, morpho are good examples to test against. 

![image](https://github.com/user-attachments/assets/f31891ba-e8c8-49ba-902f-34821a82f41e)

"usually  `pricePerShare` * `the underlying token price` works" however we don't know what we don't know. since upstream there is a need for a solution. This ticket is here to track and discuss, as there might not be a solution ATM. cc @gomesalexandre for the extra context im missing.

**Comment by 0xean** [comment]
Questions:

- what is the expected solution here? to find another market data source prices? to hand roll our own solution? 
- Have we reached out to portals to ask them how they handle this?

**Comment by twblack88** [comment]
I think there two possible outcomes:
* we do nothing because we expect there to be an upstream fix from CG. not sure if we've contacted and asked. 
* 🤝 we did ask Portals team and they got back.  Portals calculates this themselves so we could do that: it's under the `v2/tokens endpoint`

**Comment by gomesalexandre** [comment]
@twblack88 can we close this, since market-data issues are an upstream "issue" (read: not an actual issue, but work needed on a per-token basis), and there is nothing actionable on our side here, as we already hit Portals with highest priority for for LP market data? See https://github.com/shapeshift/web/issues/7450 where this work was done and prioritization was introduced.

**Comment by twblack88** [comment]
Yeah no problem. QQ, is there a happy path for the `balance.Of` not equalling usd. like....hide it?  

![portals](https://github.com/user-attachments/assets/dcea2b34-cf65-41a8-ad4b-45757ee53804)

**Comment by 0xean** [comment]
@gomesalexandre to double check that our implementation is working as expected, if so, probably no action here otherwise will comment here on next steps.
