### ISSUE TITLE
Mixpanel event for runepool

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#7566]
Just in case we forgot to ticket (or didn't add), add mixpanel tags on 
- runepool deposits & withdraws

Until we have the onchain reference.

**Comment by gomesalexandre** [comment]
@twblack88 RUNEPool is leveraging the DeFi deposit events meaning we already have these, however we'll need to use the `assetId` vs. underlyingAssetIds



![Image](https://github.com/user-attachments/assets/bb91e031-7e3b-4c93-a97a-50f60d3ce21b)
![Image](https://github.com/user-attachments/assets/5617aa17-61d0-4c07-9000-738a9a063360)
