### ISSUE TITLE
Unable to complete rFOX Bridge

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#7590]
### Overview

When attempting to stake FOX on Ethereum via the rFOX page the bridge step never completes.

### References and additional details

Se Jam for a reproduction: https://jam.dev/c/87551814-3dec-4425-a25e-a3cb6038d158

Error thrown, which is possibly related: `No retryable data found in error at L1ToL2MessageGasEstimator.populateFunctionParams`

<img width="1086" alt="Screenshot 2024-08-22 at 10 31 37 AM" src="https://github.com/user-attachments/assets/9e569e3f-d309-4fae-b0a2-5e77502c5b58">

### Acceptance Criteria

Can successfully bridge FOX from Ethereum to Arbitrum via the rFOX stake workflow.

**Comment by 0xApotheosis** [comment]
This is not actually an issue - I suspect the ops testing just didn't wait long enough for the Arb-side TX to complete.

It works just fine in production:

<img width="433" alt="Screenshot 2024-08-26 at 3 49 37 PM" src="https://github.com/user-attachments/assets/c6989fb6-2e12-44a3-91be-72719fe34f3d">

**Comment by gomesalexandre** [comment]
> This is not actually an issue - I suspect the ops testing just didn't wait long enough for the Arb-side TX to complete.
> 
> 
> 
> It works just fine in production:
> 
> 
> 
> <img width="433" alt="Screenshot 2024-08-26 at 3 49 37 PM" src="https://github.com/user-attachments/assets/c6989fb6-2e12-44a3-91be-72719fe34f3d">
> 
> 

@0xApotheosis indeed, that error is expected! Though we could probably swallow it.
re: bridge taking 5-15mn, those kind of spotted bugs that actually aren't are usually the symptom of a confusing behavior: if ops are confused, users would definitely be.
@twblack88 how about we add some lil explainer there that things may take some time to complete? (Usually 7 minutes from all my testing but can be up to 15 technically)
