### ISSUE TITLE
Infinite loop on buy-crypto route

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#7599]
### Overview

When loading the `buy-crypto` route we end up in an infinite loop, causing the icons to never load and tens of thousands of console logs.

### References and additional details

<img width="281" alt="Screenshot 2024-08-22 at 1 00 29 PM" src="https://github.com/user-attachments/assets/9cbe1319-e600-4caa-bf89-4ec416eba4dd">

<img width="1410" alt="Screenshot 2024-08-22 at 12 59 49 PM" src="https://github.com/user-attachments/assets/547db169-822c-4e2f-940e-786544ceba51">

### Acceptance Criteria

Find and fix the cause of this loop.

**Comment by NeOMakinG** [comment]
Started investigating:

It's not an infinite loop, but we reload market data for around 1500 assets when visiting the page, making things super slow
