### ISSUE TITLE
Addresses in app should be kopiable

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7624]
![Screenshot 2024-08-26 at 7 06 09 PM](https://github.com/user-attachments/assets/2e55aaaf-c357-4cf2-b70c-a1a4db656503)
![Screenshot 2024-08-26 at 7 08 20 PM](https://github.com/user-attachments/assets/e51a9f3c-d750-4e9b-aa57-5c3ad8a607b9)

Currently we show truncated addresses in several places on the app, these display a no-click cursor icon when you hover over them but we offer copy buttons seperately in places.  We should fix this so clicking on an address allows it to be copied to the clipboard. 

another example:

- For addresses that do not link out, make them clickable to copy the address
- For addresses that link out, add a small copy icon next to the address
![Screenshot 2024-08-26 at 7 09 41 PM](https://github.com/user-attachments/assets/7930728a-f9a0-4f64-ade0-28de047eeb62)

**Comment by twblack88** [comment]
Spiked in, there is a component for this named `inlinecopybutton.tsx` so we should just make sure that we popped this one in there.
