### ISSUE TITLE
0x Permit2 send it

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#7648]
0x launched their new API. They sent us all this documentation about saving people gas and making the UX better. This ticket covers picking up a more secure pattern for token allowances on the 0x swapper. 

It's basically: replace approval with permit2 for the 0x swapper.

Consider it low priority but worth picking up. Should only use the pattern for permit2 since we already have token-approval signature transaction flows (sign to approve) and then send the transaction. In our current app permit2 upgrades a current onchain siganture to an "offchain signature for limited approval and an onchain signature for the trade." Already better.

>  "If your integration doesn't support collecting offchain signatures, such as with smart contracts, we recommend using AllowanceHolder."

☝️ this is what we have to verify and account for. 

from smart contract lore, a good overview: https://github.com/dragonfly-xyz/useful-solidity-patterns/tree/main/patterns/permit2

0x docs: https://0x.org/docs/upgrading/upgrading_to_swap_v2#step-1-get-indicative-price

Headless example: https://github.com/0xProject/0x-examples/blob/main/swap-v2-headless-example/index.ts#L62-L83

**Comment by twblack88** [comment]
@reallybeard it's simple and we already have this,  but a mock or two here would be super helpful. 

0x is nagging us about upgrading to v2 so we might as well see where we're going. Just to round it out.

**Comment by woodenfurniture** [comment]
Questions to answer:

- [ ] Can we wrap all of the swappers in Permit2 or does the protocol need to support Permit2 for it to work?

**Comment by twblack88** [comment]
@woodenfurniture going for extra credit. 

vomited thoughts for now https://excalidraw.com/#room=57937cdcd3d70f535ad4,MgzvO8mKR_lRaC18ncX2-g

![image](https://github.com/user-attachments/assets/1750c7db-4136-485e-814b-d463e431ac6f)

**Comment by 0xean** [comment]
waiting for UI help from @reallybeard

**Comment by reallybeard** [comment]
Was having trouble getting this to run correctly on my local env. But I went through the different jams. Everything looks great, only small feedback is to move the instructions below the label. @woodenfurniture 

Crappy screenshot attached. 
![Screenshot_2024-10-14_at_4 23 57_PM copy](https://github.com/user-attachments/assets/f3758e8a-c1a0-49fb-bd7c-566eb83cdc02)
