### ISSUE TITLE
Evergreen Fox Farm - Web

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7666]
Blocked by https://github.com/shapeshift/web/issues/7667

--------

Since the ABIs of the functions we care about may be identical (or atleast very close), this is probably just a matter of confirming that and making sure everything works with a new contract.

**Comment by woodenfurniture** [comment]
I've compared the ABIs and there are some difference.

Functions with the same ABI:

1. `balanceOf`
2. `earned`
3. `getReward`
4. `lastUpdateTime`
5. `owner`
6. `paused`
7. `rewardPerToken`
8. `rewardPerTokenStored`
9. `stake`
10. `stakingToken`
11. `totalSupply`
12. `withdraw`

Different ABI:
1. `FOX_STAKING_V1_ABI` has `pause`, `pauseStaking`, `pauseUnstaking`, and `pauseWithdrawals`, which are different from `STAKING_REWARDS_ABI`'s `setPaused`.
2. `FOX_STAKING_V1_ABI` has `transferOwnership`, which is different from `STAKING_REWARDS_ABI`'s `nominateNewOwner` and `acceptOwnership`.

Missing in FOX_STAKING_V1_ABI:
1. `exit`
2. `getRewardForDuration`
3. `lastPauseTime`
4. `lastTimeRewardApplicable`
5. `nominatedOwner`
6. `notifyRewardAmount`
7. `periodFinish`
8. `recoverERC20`
9. `rewardRate`
10. `rewards`
11. `rewardsDistribution`
12. `rewardsDuration`
13. `rewardsToken`
14. `setRewardsDistribution`
15. `setRewardsDuration`
16. `userRewardPerTokenPaid`

Missing in STAKING_REWARDS_ABI:
1. `REWARD_RATE`
2. `UPGRADE_INTERFACE_VERSION`
3. `WAD`
4. `cooldownPeriod`
5. `getUnstakingRequest`
6. `getUnstakingRequestCount`
7. `initialize`
8. `proxiableUUID`
9. `renounceOwnership`
10. `setRuneAddress`
11. `stakingInfo`
12. `stakingPaused`
13. `unstakingPaused`
14. `withdrawalsPaused`
15. `totalCoolingDown`
16. `unpause`
17. `unpauseStaking`
18. `unpauseUnstaking`
19. `unpauseWithdrawals`
20. `upgradeToAndCall`
21. `version`

**Comment by woodenfurniture** [comment]
Functions with the same ABI:
1. `balanceOf`
2. `earned`
3. `getReward`
4. `lastUpdateTime`
5. `notifyRewardAmount`
6. `owner` (named `rewardsDistribution` in `FARMING_ABI`)
7. `periodFinish`
8. `rewardPerToken`
9. `rewardPerTokenStored`
10. `rewardRate`
11. `rewards`
12. `rewardsToken`
13. `stake`
14. `stakingToken`
15. `totalSupply`
16. `userRewardPerTokenPaid`
17. `withdraw`

Different ABI:
1. `STAKING_REWARDS_ABI` has `setPaused`, while `FARMING_ABI` doesn't have a pausing function.

Missing in STAKING_REWARDS_ABI:
1. `lastTimeRewardApplicable`
2. `getRewardForDuration`
3. `stakeWithPermit`
4. `exit`

Missing in FARMING_ABI:
1. `acceptOwnership`
2. `getRewardForDuration`
3. `lastPauseTime`
4. `nominateNewOwner`
5. `nominatedOwner`
6. `paused`
7. `recoverERC20`
8. `rewardsDistribution` (as a separate function, it's used as `owner` in `FARMING_ABI`)
9. `rewardsDuration`
10. `setPaused`
11. `setRewardsDistribution`
12. `setRewardsDuration`

**Comment by woodenfurniture** [comment]
Entries with the same ABI:
- RewardAdded
- RewardPaid
- Staked
- Withdrawn
- balanceOf
- earned
- exit
- getReward
- getRewardForDuration
- lastTimeRewardApplicable
- lastUpdateTime
- notifyRewardAmount
- periodFinish
- rewardPerToken
- rewardPerTokenStored
- rewardRate
- rewards
- rewardsDistribution
- rewardsDuration
- rewardsToken
- stake
- stakingToken
- totalSupply
- userRewardPerTokenPaid
- withdraw

Missing in STAKING_REWARDS_ABI:
- stakeWithPermit

Missing in FARMING_ABI:
- RewardsDurationUpdated
- acceptOwnership
- lastPauseTime
- nominateNewOwner
- nominatedOwner
- owner
- paused
- recoverERC20
- setPaused
- setRewardsDistribution
- setRewardsDuration
