### ISSUE TITLE
Unable to deposit into USDT on Eth ThorChain savers

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7677]
### Overview

getting an error when trying to depost into usdt on eth savers vault

### References and additional details

![image](https://github.com/user-attachments/assets/cfefd416-c6ad-491a-896f-194403e47499)
https://jam.dev/c/56116463-ff29-4279-a73c-6f079bd86a5b

### Acceptance Criteria

Should be able to deposit into USDT on eth savers vault

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria this should be fixed next release assuming this guy gets merged! https://github.com/shapeshift/web/pull/7670
