### ISSUE TITLE
Markets Page : Watchlist 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7685]
[notion](https://www.notion.so/shapeshift/Markets-Page-Desktop-efad92c67eee47298d2e65a133e0ace8)
[figma](https://www.figma.com/design/cuSW3HCchxWeKC8CEvn029/Markets-Page-%26-Watchlist?node-id=814-2039&t=0BpTRBv2et0FfCHi-0)

- create Watchlist view 
- reuse functionality from mobile as much as possible (storing on user preferences object)
- sort on marketcap for now (later we can add fancy sorting)

**Comment by gomesalexandre** [comment]
GitHub is drunk - closed by https://github.com/shapeshift/web/pull/7795
