### ISSUE TITLE
Setup Market Data Websocket

### ISSUE THREAD

**Issue by bootsboogie** [shapeshift/web#77]
With the talk of websockets I think that we should follow the same principles we have laid out in the state management docs, if it is a websocket that is used in one place it lives in that one place if the state is needed in multiple places across the app we should have it in redux. You will see in the redux tool kit documentation they state that when working with websockets we should create our on middleware that handles the websocket. The middleware exists for the lifetime of the application and we can store a single instance in there and dispatch actions when we receive an update from the websocket. If we are using selectors appropriately this should only update the parts of the app that are grabbing that state from the redux store. 

I think this would be a good use case for something like balances. We create a middleware probably for Asset data, that middle ware creates the websocket connection and handles updating state and the reducers can handle combining that state into one uniform piece that has asset and market data in it. 

Here is the documentation describing websocket use in redux https://redux.js.org/faq/code-structure#where-should-websockets-and-other-persistent-connections-live and here is there example of how to implement it with a custom middleware https://gist.github.com/markerikson/3df1cf5abbac57820a20059287b4be58. Another thing that we have talked about is that if a user has a bad internet connection we dont want the app to be completely unusable. 

If we go with this approach and we are saving our asset data into redux we can use something like redux-persist to update whatever state we would like in local storage automatically and if a user does not clear their local storage and comes back to the site we can rehydrate our state with where they left off.

**Comment by bootsboogie** [comment]
https://dev.to/aduranil/how-to-use-websockets-with-redux-a-step-by-step-guide-to-writing-understanding-connecting-socket-middleware-to-your-project-km3

**Comment by 0xean** [comment]
leaving this open to revisist once [#281](https://github.com/shapeshift/lib/issues/281)  is completed
