### ISSUE TITLE
THORChain LP - Guard against amount too low for withdraw

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#7710]
### Overview

Precisely what the title says - users withdrawing too small of amounts will end up in Txs not even being observed, only hitting the mempool (which runescan/viewblock is able to leverage and provide useful error messages for e.g https://viewblock.io/thorchain/tx/FE3BE7549136777827D46F46049C7E26FA047128BB4E60D7D5D082EB1617B84B).

### References and additional details

N/A

### Acceptance Criteria

- A minimum is introduced for withdraws, that will ensure Txs go through and block users from continuing, with some messaging alongside it

**Comment by 0xean** [comment]
disable when failure is for sure, otherwise leave as is

**Comment by 0xean** [comment]
use 4x buffer to avoid failed transactions and potential for failed tx's
