### ISSUE TITLE
RFOX rewards address account selection borked

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#7721]
### Overview

Currently in develop, account selection is borked for RFOX:

https://jam.dev/c/3aa80f37-6ae7-4239-ac8f-ef1b8f5a79ef

No matter how many times you select another account, it always reverts to the active account

### References and additional details

N/A

### Acceptance Criteria

- RFOX rewards address account selection is happy

### Screenshots/Mockups

https://jam.dev/c/3aa80f37-6ae7-4239-ac8f-ef1b8f5a79ef

**Comment by NeOMakinG** [comment]
I'm unable to reproduce for now: https://jam.dev/c/5b8d0ea4-8cc6-4316-b077-0e6a1a65e338

Any ideas on a way to reproduce it in a deterministic way?
