### ISSUE TITLE
Deposit and withdraw from ATOM saver vault does not list txid in recent transactions or activity tab

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7743]
### Overview

After depositing into Atom vault or doing a withdraw (even though it fails currently), the txid does not show in the transaction history, even after a clear cache
*side note: wallet takes a while to load (about 2mins to get transactions in) 

### References and additional details

https://jam.dev/c/985e08cd-96cb-48ec-abd6-f504d3113b38

### Acceptance Criteria

Should show deposit/withdraw tx's in recent transactions

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by kaladinlight** [comment]
After backend fix:
![image](https://github.com/user-attachments/assets/90b1a5ce-dbf4-4dbf-8ed0-36382a443cd7)
![image](https://github.com/user-attachments/assets/92b75cc3-490a-4828-9e73-0aa411892d21)
