### ISSUE TITLE
Web bundle size too big spike

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#7768]
### Overview

Our app bundle size is right on the cloudflare limit. We should investigate way to reduce it before it's too big to deploy.

### References and additional details

.

### Acceptance Criteria

Options to reduce bundle size.

**Comment by 0xean** [comment]
- do we need to serve asset data externally to app 
- what other solutions exist?

**Comment by 0xApotheosis** [comment]
**Initial bundle size for reference**

Parsed: 45.9 MB

<img width="2056" alt="Screenshot 2024-09-26 at 18 31 50" src="https://github.com/user-attachments/assets/2a63e99f-c87a-4a11-80da-d85015abfab4">

Gziped: 12.96 MB

<img width="2056" alt="Screenshot 2024-09-26 at 18 32 03" src="https://github.com/user-attachments/assets/17903918-5e94-4e96-a1c1-6752030512b0">

**Comment by gomesalexandre** [comment]
> **Initial bundle size for reference**
> 
> Parsed: 45.9 MB
> 
> <img alt="Screenshot 2024-09-26 at 18 31 50" width="2000" src="https://private-user-images.githubusercontent.com/97164662/371341623-2a63e99f-c87a-4a11-80da-d85015abfab4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjEyNzYsIm5iZiI6MTcyNzQyMDk3NiwicGF0aCI6Ii85NzE2NDY2Mi8zNzEzNDE2MjMtMmE2M2U5OWYtYzg3YS00YTExLTgwZGEtZDg1MDE1YWJmYWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA3MDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkOTgwMjE2ODc5Y2UwZDI0ODZjM2NhNGU1YjY5NTQzNDZlNmIzYWMwN2ZkMGU4YmQ1YmY5NWFjMzI2YjRmYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4bOS_IPaz_HG0iYltjdzuKUcTlxEMqAV69serY6t9ZM">
> Gziped: 12.96 MB
> 
> <img alt="Screenshot 2024-09-26 at 18 32 03" width="2000" src="https://private-user-images.githubusercontent.com/97164662/371341729-17903918-5e94-4e96-a1c1-6752030512b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjEyNzYsIm5iZiI6MTcyNzQyMDk3NiwicGF0aCI6Ii85NzE2NDY2Mi8zNzEzNDE3MjktMTc5MDM5MTgtNWU5NC00ZTk2LWExYzEtNjc1MjAzMDUxMmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA3MDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MWZiMjNiZTM2MmQ4YTQxOWMzYjJmYjI5N2JmY2FmYTk5ZjY3NDliYjBkOGM5MDk4MjQ4ODdiYjQzMzk4NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Iqh4Lyd7d0JZT2Pp0CaSK71Klc7VuRJg9V5bNZeVD5o">

@0xApotheosis would minifying the base (non-gzipped) `generatedAssetData.json` save a *lot* here or wouldn't it be significant?

**Comment by 0xApotheosis** [comment]
### Opportunities (2 promising ones that are Pareto-optimized)

**Lazy load `@ledgerhq`:**

38% of the the total Gzipped bundle size is from a single part of a single package: `@ledgerhq/cryptoassets/lib-es/data/evm`.

**Minifying `generatedAssetData.json`**

A quick sanity check on this approach (thanks @gomesalexandre) showed that we'd reduce this file size somewhere in the order of 15% (10.8mb down to 9.4mb on a quick test).

Other good candidates for minification are `relatedAssetIndex.json` (1.46mb) and `color-map.json` (872kb).

However, the alternative and likely better solution is probably to remove these files from the build entirely by...

**Using GitHack to externalize generated files from the build**

We could keep these generated files in the existing repo (`web`), but exclude them from the build and serve them via GitHack.

This alone would reduce the gzipped bundle size by 85%, and the parsed size by 25%.

**Comment by 0xApotheosis** [comment]
Closing this spike as tickets have been spawned which, once completed, should alleviate the issue.
