### ISSUE TITLE
Spike data storage mechanisms for client side performance

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#7769]
### Overview

App performance is bad and often the app requires a cache clear to bring performance back to acceptable level. Its likely our use of redux to store large amounts of data is the issue here, and use of a different approach could keep the app buttery smooth even in the present of relatively large volumes of data in the client.

### References and additional details

.

### Acceptance Criteria

Investigate possible solutions to avoiding use of redux for persistent data storage and access.

**Comment by 0xean** [comment]
- benchmark and identify the source of performance issues (initial hydration vs read/write at runtime)
- document options in GH for conversation with team
- report back to team after 1 days of research

**Comment by gomesalexandre** [comment]
As discussed with @woodenfurniture, https://github.com/shapeshift/web/pull/7799 was the effective fix for the time being, but this spike still remains opened as a lower prio.

**Comment by 0xean** [comment]
closing for now ... will reopen in ~4 weeks
