### ISSUE TITLE
Trade rates calculating before finished typing in amount to trade 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7775]
### Overview

When typing in an amount to trade in the trade modal that is more than 1 or 2 digits, you need to type the number super fast otherwise the modal will start to calculate a rate before you have had time to finish typing in the amount. 

### References and additional details

https://jam.dev/c/6645a6e0-7a1a-439e-99a0-6201776c2342

### Acceptance Criteria

the modal should have enough buffer time for you to finish typing in the amount to trade before calculating a rate.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
Ugh. I suspect that's a regression from https://github.com/shapeshift/web/pull/7741.
