### ISSUE TITLE
Swapper infinite load state

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/web#7789]
### Overview

The swapper UI stays in an infinite load state if a thorchain (maybe others?) quote fails.

### References and additional details

![image](https://github.com/user-attachments/assets/05c1a458-c665-41a7-8f34-fe231016261c)

### Acceptance Criteria

- Swapper should load and show available quotes even if some quotes failed under the hood

**Comment by 0xean** [comment]
Need state to show no quotes available
