### ISSUE TITLE
Swapper price impact calculation inaccurate

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/web#7790]
### Overview

The displayed price impact is way off on the swapper display

### References and additional details

![image](https://github.com/user-attachments/assets/486be4e4-3071-4789-bae3-a36668c0a8c6)

### Acceptance Criteria

- Accurate price impact percentage

**Comment by 0xean** [comment]
![Screenshot 2024-09-23 at 6 52 30 PM](https://github.com/user-attachments/assets/ee405eb9-a778-40c8-8aec-0da336497ec4)

- fix the value here to show the diff between input fiat amount vs output fiat amount and keep the copy as is

**Comment by woodenfurniture** [comment]
Left one will be NET send/receive diff percentage
Right one will be unchanged.
