### ISSUE TITLE
Arbitrum network down

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7803]
### Overview

Arbitrum network showing as $0.00 in ShapeShift and there is no degraded state warning.

### References and additional details

![image](https://github.com/user-attachments/assets/2769cf1b-bc4a-4ca6-b637-f2c6fc323907)

![image](https://github.com/user-attachments/assets/c1f0157c-db6b-4a4c-9686-4b959e86d0cc)

### Acceptance Criteria

Balance should show in ShapeShift

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by kaladinlight** [comment]
Nownodes arbitrum blockbook was resynced for unknown reasons and will be out of service until it is synced back up. Currently 175m/250m blocks synced.
