### ISSUE TITLE
Drop down arrow on trade confirmation screen is pointing in the wrong direction 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7804]
### Overview

The drop down arrow on trade confirmation screen points up when it should point down and vice versa

### References and additional details

![image](https://github.com/user-attachments/assets/4c056462-b93d-49da-99da-fe22a204b4ca)

https://jam.dev/c/9212cdd2-cd9e-41a6-bc54-0a6c91738780

### Acceptance Criteria

Arrow should point in direction the drop down goes

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by woodenfurniture** [comment]
Should be pointing down when its closed, should point up when open.
