### ISSUE TITLE
New splash for connect wallet does not translate all text to new language selection

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7816]
### Overview

When selecting a language different from English on the new connect wallet splash, not all the text is translated

### References and additional details

![image](https://github.com/user-attachments/assets/7a0df3fc-4004-4f7f-9424-a7f8fe782c52)

https://jam.dev/c/91cb88fa-2841-4839-8a89-3086c0c4e922

### Acceptance Criteria

Changing language should translate all text 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by firebomb1** [comment]
Thanks for the ticket @MBMaria, these all seem to be translatable and will be translated during the next MKBD Translation sync which occur biweekly. The next one starts next Monday, September 30th, once translators will have translated the strings in the 9 languages supported by the app the changes will be merged in the app and released eventually.

**Comment by 0xean** [comment]
closing as temporary

**Comment by firebomb1** [comment]
I would have tagged the issue in the upcoming merge later this week, but thx for preemptively closing it, it's currently in the works 👍
