### ISSUE TITLE
Unable to trade LINK to M87 on Eth 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7827]
### Overview

When trying to trade LINK on eth to M87 on Eth getting an error of Something went wrong. Happens both Portals and 0x swapper

### References and additional details

![image](https://github.com/user-attachments/assets/fd42dcea-f8be-4e39-9cb7-2a86f10f0e3b)

https://jam.dev/c/4314206f-2168-494f-8fc1-2808feb23327

### Acceptance Criteria

Should be able to swap to M87? 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
@MBMaria this is one of those unfortunate upstream issues: the error is coming from 0x with code `IncompleteTransformERC20Error`.
Researching that, I can see that:
 > At this time 0xAPI only works with standard ERC20/BEP20 tokens which does not include tokens (like SHIBIC) that take a fee on transfer.
 
Can close at wontfix, though since this is not the first time this happens, could be worth it curating a list of untradeable assets and disabling them in swapper. If you believe there is value in that, happy to create an issue for that and raise it next sync!

**Comment by MBMaria** [comment]
hi @gomesalexandre thanks for looking into this. Yes I'd say go ahead and close then. If we could disable the pair in the swappers that would be great. I think there has been 2 or 3 assets we have come across like this? (cant remember what they are lol) Is there a way to find all the assets that are blocked upstream?

**Comment by gomesalexandre** [comment]
> hi @gomesalexandre thanks for looking into this. Yes I'd say go ahead and close then. If we could disable the pair in the swappers that would be great. I think there has been 2 or 3 assets we have come across like this? (cant remember what they are lol) Is there a way to find all the assets that are blocked upstream?

Unfortunately this is more of a "try it out and find out" kind of issue, AFAIK there really isn't a definite list anywhere.

Let's keeep those PRs handy somewhere, and if this happens again and for enough assets to become a problem, happy for ops to curate a list which we could use as a blocklist!

**Comment by MBMaria** [comment]
@gomesalexandre - is this the same error with KNDX? 
https://jam.dev/c/cfbe6dee-b5ec-43a1-ba93-28024cdebd0b
![image](https://github.com/user-attachments/assets/d4ce2cf8-1889-473f-a952-d9ab5dbec650)
