### ISSUE TITLE
Arbitrum bridge notifications when claim is ready

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7835]
Add notification when claim is ready

original mock:

https://www.figma.com/design/REOouo0sAuOhoD597yZEGE/rFOX?node-id=1018-2107&node-type=section&t=Bs5U4OZV6wyIsm5s-0

UX preferred by product would be to add a toast (@reallybeard to mock)

**Comment by 0xean** [comment]
https://www.figma.com/design/REOouo0sAuOhoD597yZEGE/rFOX?node-id=1018-2107&node-type=section&t=Bs5U4OZV6wyIsm5s-0

above mock that was probably missed during implementation

**Comment by reallybeard** [comment]
![Screenshot 2024-10-03 at 4 30 07 PM](https://github.com/user-attachments/assets/ded294f0-9b1e-467f-b3cd-3b6a6947900a)
Thinking something similar to our update app toast. 

Need to align on copy from @twblack88
