### ISSUE TITLE
expose markets page route externally without need to connect a wallet.

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7837]
pave the path for shareable links to specific categories and potentially on boarding users

for example a tweet about TC opps with a link to 

https://develop.shapeshift.com/#/markets/category/thorchainDefi

**Comment by gomesalexandre** [comment]
Reference: https://github.com/shapeshift/web/blob/9b47fbdecefce840f4c9d3683fdc789bf2f0d737/src/Routes/Routes.tsx#L110-L123

- Exposing externally hould just be about *not* redirecting for the specific case of certain routes (e.g markets)
- /category/<category> routing is already implemented so nothing to do here 🎉

**Comment by 0xean** [comment]
![Screenshot 2024-09-30 at 7 03 00 PM](https://github.com/user-attachments/assets/a7ac5a49-e472-48ed-9d38-04b70f8a3f54)

If a use attempts to navigate to outside the markets page, we throw this modal in the same way we do for the demo wallet
