### ISSUE TITLE
Unable to deposit into ThorChain saver vaults

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7842]
### Overview

When trying to deposit into savers, the slippage and time to break even do not populate. For evm savers you can select continue but it loops back, for utxos, continue does not come up as an option to select. 

### References and additional details
![image](https://github.com/user-attachments/assets/3f00f2d7-dad2-496d-803f-3d0e24186200)

![image](https://github.com/user-attachments/assets/e60e82d1-2ded-4696-9732-4807a4c31260)
https://jam.dev/c/33cda4b5-f9a5-49f6-a9c2-58bec3263f27
https://jam.dev/c/37c42083-f091-4988-b3a8-165e1422968b

### Acceptance Criteria

Should be able to deposit into savers

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by kaladinlight** [comment]
Confirmed savers quotes appear to be broken. This is not just us, ninerealms and thorswap nodes are showing the same behavior. It would seem there is a bug in the thorchain daemon logic. Raised in discord and will update here as I know more.

**Comment by kaladinlight** [comment]
https://discord.com/channels/838986635756044328/839002619481554955/1290719412672004146

**Comment by kaladinlight** [comment]
Thornode update just went out and savers are back in action:
![image](https://github.com/user-attachments/assets/58c79e52-6e36-421b-bec9-b6815f30ff99)
![image](https://github.com/user-attachments/assets/217f4190-4182-4fcd-9313-facee8ecf5f8)
