### ISSUE TITLE
Exclude `@ledgerhq` from bundle

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#7855]
### Overview

The `@ledgerhq` package, specifically the `@ledgerhq/cryptoassets/lib-es/data/evm` directory, takes up a significant proportion of `web`'s bundle size.

We should lazy load this package so that it's only loaded by the client when a user is attempting to connect a Ledger (or even when the "Connect wallet" modal is loaded if the former is not possible.

### References and additional details

Spawned from the spike into web's bundle size: https://github.com/shapeshift/web/issues/7768

Run `yarn analyze` to generate a visual representation of the bundle.

![image](https://github.com/user-attachments/assets/ffdcf632-a35a-459a-a68d-ab2e513e6b92)

### Acceptance Criteria

The `@ledgerhq` package is not included in the `web` bundle.

**Comment by 0xean** [comment]
- can we remove the package entirely since its only used for filtering device id
