### ISSUE TITLE
Exclude generated asset data from bundle

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#7856]
### Overview

A large portion of `web`'s bundle size comes from the generated asset data, namely:

- `generatedAssetData`
- `relatedAssetIndex.json`
- `color-map.json`

We can instead load these on app boot using a tool such as GitHack.

### References and additional details

Spawned from https://github.com/shapeshift/web/issues/7768

See https://raw.githack.com/

### Acceptance Criteria

The generated asset data is still included in the `web` repo, but is not included in the app bundle.

**Comment by 0xean** [comment]
- consider using compression to assist with network transfer

**Comment by 0xApotheosis** [comment]
Color map excluded in https://github.com/shapeshift/web/pull/7897
