### ISSUE TITLE
Yearn transactions are not being displayed in Recent Transaction in Dashboard.

### ISSUE THREAD

**Issue by Neverwas-dev** [shapeshift/web#786]
- Brief description
After a Yearn vault interaction the wallet dashboard screen doesn't reflect any Recent Transaction history for Yearn tx

- Steps to recreate
1. Connect a wallet
2. Preform a Yearn transaction (Approve interaction, Stake, Un-stake of an vault asset)
3. Confirm transaction is complete
4. Look for the tx in the dashboards Recent Transactions

- Screenshots/vids

- Link to Discord
https://discord.com/channels/554694662431178782/873244924026449940/930564356461191199

- AC (acceptance criteria)
The connected wallet Recent Transactions should display all Yearn vault transactions. This includes:
1. Approvals of asset vault interactions
2. Staking of asset to a Yearn vault
3. Un-Staking of asset from a Yearn vault

**Comment by 0xean** [comment]
waiting on comsos tx pagination and websockets
