### ISSUE TITLE
FOX page: fox farming

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7870]
https://www.figma.com/design/lqcttmmnGtRtbjb8evL6Le/FOX-page?node-id=814-675&node-type=frame&t=g7p4aoeHaEYvZV2s-0
- add fox farming section 
- add feature flag for this section
- release

**Comment by twblack88** [comment]
cc @NeOMakinG The chakra UI math for APY on fox farming: 
![Screenshot 2024-10-03 at 10 44 09 AM](https://github.com/user-attachments/assets/8ee8e92f-5e54-476b-8b09-88964268d474)

" do trailing three epochs using FOX price and Rune price on day of distribution. Call it "estimated trailing 90 day APY" " @shapeshift/product is aligned with good math.

**Comment by 0xean** [comment]
@twblack88 - #7867 is the rfox guy
