### ISSUE TITLE
Invisible chain in Chain selector dropdown in Markets page

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7885]
### Overview

Currently in Release, the Market page chain selector dropdown has a blank, selectable option that is not a chain. 

### References and additional details

![Screenshot 2024-10-03 at 2 23 37 PM](https://github.com/user-attachments/assets/93e4c64b-cb7c-43ac-b003-131100e7c001)

https://jam.dev/c/3ef8de38-fe10-40fa-84d2-7204ce4810c9

This should not be present/selectable. 

### Acceptance Criteria

Chain selector drop downdoes not have ghost selectable chain.

**Comment by purelycrickets** [comment]
![Screenshot 2024-10-03 at 2 26 18 PM](https://github.com/user-attachments/assets/42042cfc-a6ae-4a9f-b445-7124008d0da6)
Additionally, 'One-click-DeFi' has 2 listings of ARB.

**Comment by 0xApotheosis** [comment]
Closed by https://github.com/shapeshift/web/pull/7887
