### ISSUE TITLE
Arbitrum Bridge withdraws displayed as success

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#7894]
### Overview

Currently in all envs, Arbitrum *withdraws* (ARB -> ETH) are detected as success as soon as the inbound Tx is complete:

![image](https://github.com/user-attachments/assets/f7731f73-7699-4bb9-b411-1a7a341122ba)

However these take ~6-7 days to complete, and eventually require a claim.

That's as opposed to Arbitrum deposits (ETH -> ARB) which take ~5-15mn, and we have proper polling for success, meaning when we show success, the bridge *is* actually a success.

In an effort to make the experience feel more streamlined and less broken in the app, we should improve this from a product perspective so that this success step looks different from the regular one, and users are clearly informed that their swap is *not* complete but only their inbound is, as well as getting a gentle reminder (they have already been warned with an ack before bridging) that they will require a claim Tx in ~x days.

### References and additional details

Spotted while testing https://github.com/shapeshift/web/pull/7876

### Acceptance Criteria

- Success step for Arb withdraws doesn't look broken

**Comment by gomesalexandre** [comment]
@twblack88 needs product

**Comment by twblack88** [comment]
We probably need an inbound step and something to indicate that the claim is pending.
