### ISSUE TITLE
Add simple-import-sort to the linter

### ISSUE THREAD

**Issue by bootsboogie** [shapeshift/web#79]
There has been some back and forth on removing and adding `simple-import-sort` to the linter and this is the place to have a discussion and sort this out so we can get on the same page.

@technojak has a pr adding it back in https://github.com/shapeshift/web/pull/78/files

**Comment by bootsboogie** [comment]
I personally like the import sorting. I think that having organized consistent imports makes it easier to find what I am looking for there are a lot of import statements. And with anyone being able to work in the code base it is nice to have some more organization so its not messy(maybe that is just me being ocd). For me my code editor fixes prettier problems on save so if I don't put it in the right place when I save the file it is fixed automatically so I don't even notice it is there. But thats just my two cents.

**Comment by reidrankin** [comment]
Yay! Import re-orgs are my least favorite part of a manual merge.
