### ISSUE TITLE
Markets Filters [follow ons]

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#7919]
We have mocks for a few extra pieces that should smooth the rougher edges on markets. 

https://www.figma.com/design/cuSW3HCchxWeKC8CEvn029/Markets-Page-%26-Watchlist?node-id=1118-1578&node-type=frame&t=lOadxXVRus99U0ce-11

and mobile: https://www.figma.com/design/cuSW3HCchxWeKC8CEvn029/Markets-Page-%26-Watchlist?node-id=1118-3104&node-type=frame&t=lOadxXVRus99U0ce-11

Sorting by market cap, volume, price change. 

<img width="300" alt="Screenshot 2024-10-10 at 9 19 52 AM" src="https://github.com/user-attachments/assets/cd67541b-3592-4fc0-9548-df72d1907083">

Ascending and descending too.

<img width="735" alt="Screenshot 2024-10-10 at 9 23 05 AM" src="https://github.com/user-attachments/assets/8d6174b8-3025-45b2-823f-16433a76a0c5">

-  Implement all sorting / filtering options that are available natively from coingecko APIs  / portals API

**Comment by hpayne1** [comment]
Something I wanted to add here was my experience inside the markets page. It is a hit or miss of loading 1-click defi opportunities on BNB as well as Arbitrum. Sometimes opportunities load, sometimes not. Shared more here: https://ptb.discord.com/channels/554694662431178782/1293593369800605716/1293593374674386988

**Comment by twblack88** [comment]
yeah @hpayne1 heard. noticing the same. 

<img width="1189" alt="Screenshot 2024-10-14 at 11 56 50 AM" src="https://github.com/user-attachments/assets/7d4315d4-7382-4de9-a8ca-a982fd715aae">

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
