### ISSUE TITLE
bug - keepkey btc legacy send fail

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#792]
@tshifty tried to send legacy to segwit and it failed with this console error

![image](https://user-images.githubusercontent.com/88504456/149835308-d29d65dc-e3c2-44f1-9435-3307d77202cb.png)

this has been narrowed down to specifically keepkey btc legacy sends with a new version of hdwallet, this doesn't appear in beta, and must have been this way for some months.

**Comment by 0xean** [comment]
@0xdef1cafe - to try and move this forward next week

**Comment by 0xean** [comment]
@pastaghost / @bithighlander - can you take a look at this one at some point.

**Comment by asamere** [comment]
ended up being this 1 line change to prevent converting already sats amount to sats for utxo referenced prevTx output value causing hash mismatch in firmware.

https://github.com/shapeshift/hdwallet/pull/554/commits/2eecaefe67166e532e52f31b363f5e514896e2f2

**Comment by 0xdef1cafe** [comment]
closed by https://github.com/shapeshift/web/pull/2238

💩
