### ISSUE TITLE
Cancel order flow 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7921]
Just UI implementation 
RTK queries already exist

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by reallybeard** [comment]
Here is the cancel limit order screen: https://www.figma.com/design/IBz3Fn75GGjXfm89FsymAL/Limit-Orders?node-id=1470-18819&node-type=section&t=3zTZ08tEPw1MruS1-0

user would click cancel from the orders list, and this would show as a modal to keep it simple.

Once they confirm the cancel, show a loading state, and then a success.

If there is anything else to consider, we can mock that out. @0xean
