### ISSUE TITLE
Cosmos SDK rewards tx listing all assets claimed and says pending even though tx has been successful

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7926]
### Overview

When claiming atom from cosmos sdk, all the assets that get claimed are listed and run off the screen and the transaction still says ending even though it completed straight away on the blockchain .

### References and additional details

![image](https://github.com/user-attachments/assets/ac0b91db-b87e-4133-82da-e4bcea306e68)
![image](https://github.com/user-attachments/assets/b5f5937f-6c02-4c5f-abf2-6ac9b713189c)
![image](https://github.com/user-attachments/assets/534b3715-b973-4619-8b85-7c8e928f985c)

https://www.mintscan.io/cosmos/tx/34DA201CED4322A4EC0B6A85CC04D9D5BE80124E19B7DD1177C10AC6FCF8B42E

### Acceptance Criteria

Should just have atom listed? And update to completed once tx is successful.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
- Potentially related to cosmos WS issues being experienced with NNs

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by kaladinlight** [comment]
Validated the cosmos transactions are being detected and showing confirm correctly with the websocket updates. I am calling in @reallybeard for the symbol trunctation :pray:
