### ISSUE TITLE
Attention Warning in trade modal spans across whole page instead of just the modal

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7946]
### Overview

When there is a warning on trades, the attention banner spans across the whole page instead of just the modal like it used to 

### References and additional details

![image](https://github.com/user-attachments/assets/fd2aab06-6499-4549-9a83-3419cc428c26)

https://jam.dev/c/ff267f2d-3ce6-40ee-ab0e-fe1a5f670a0f

### Acceptance Criteria

Warning should be width of modal 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
Closed by https://github.com/shapeshift/web/pull/7953
