### ISSUE TITLE
Swapper pair resetting when attempting chain switch for trade into WETH  

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7960]
### Overview

Currently in production, when attempting to switch the the chain of the output asset of a WETH trade, the asset pairs switch the output and input assets.  See Jams for recreations.  Attempts to trigger the bug with assets that are not WETH were not successful. 

### References and additional details

Hpayne discovery: https://jam.dev/c/73a354a3-e041-42c5-9ff0-4f430ef72674

Tyler recreation: https://jam.dev/c/18c1e2ce-c011-4541-ad83-b4f30226705a

### Acceptance Criteria

Changing the chain of the outgoing asset in a x>WETH trade does not reset or switch the pair.  Users are able to use the chain selector successfully when attempting to change the chain of an outout WETH trade.

**Comment by NeOMakinG** [comment]
I don't see any bugs there:

sellAsset => ETH on Base, buyAsset => WETH on Ethereum, if you change the buyAsset chain to `Base (ETH)`, it will select `ETH on Base` and as you can't swap one same asset to the same asset, we simply switch the assets

You are clicking on `Base (ETH), Arbitrum (ETH)` which is here to cleary distinguish ETH and WETH which are 2 different assets, if you want to switch ETH to WETH on the same chain, then click on the chain without `(ETH)`

![Image](https://github.com/user-attachments/assets/8f633dec-2adc-4bb8-922a-65478a8074e8)

Closing as it seems logical so far but if @shapeshift/product want to confirm feel free!
