### ISSUE TITLE
Unable to trade into Custom Token

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7962]
### Overview

When trying to import a custom token , entering the address comes up with no results found

### References and additional details

![image](https://github.com/user-attachments/assets/60da8762-2ead-4577-bf8a-64c29cd13589)
https://jam.dev/c/0d8bc27c-c0ed-4e01-8718-a789f7e5e251

### Acceptance Criteria

Should be able to import custom tokens

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Fixed by https://github.com/shapeshift/web/pull/7956
