### ISSUE TITLE
Missing Solana related AssetIds

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#7967]
### Overview

Currently in all envs, we solely rely on Zerion for related AssetIds fetching:

https://github.com/shapeshift/web/blob/b226bd2db3e1bd2c69d0bd0447f9e761f0516f22/scripts/generateAssetData/generateRelatedAssetIndex/generateRelatedAssetIndex.ts#L101-L122

This works great for EVM assets, however doesn't play well with Solana assets missing there, e.g USDC:

<img width="649" alt="image" src="https://github.com/user-attachments/assets/e0b60165-4e4a-4433-876f-ccddafbcd93a">

vs. Coingecko:

<img width="389" alt="image" src="https://github.com/user-attachments/assets/583cda01-304f-4e42-9678-ba9500e142cb">

This actually makes sense, as Zerion doesn't support Solana as a chain.

This PR is for us to support a new source (cg) in `generateRelatedAssetIndex.ts`, to support Solana related AssetIds.

Data can be gotten using the request below:

https://paw.pt/i90PfDIu

### References and additional details

- `getRelatedAssetIds`:

https://github.com/shapeshift/web/blob/b226bd2db3e1bd2c69d0bd0447f9e761f0516f22/scripts/generateAssetData/generateRelatedAssetIndex/generateRelatedAssetIndex.ts#L101-L122

- coingecko network can be gotten with `chainIdToCoingeckoAssetPlatform`:

https://github.com/shapeshift/web/blob/9a15257c92dba6beaafd8867a473274e7971ef0b/packages/caip/src/adapters/coingecko/index.ts#L62-L63

### Acceptance Criteria

- As a user, I can now see Solana related AssetIds for e.g USDC
- Rate-limiting is in-place not to spew cg
- When fetching related assets, an additional request is made to cg alongside Zerion, following the `/api/v1/markets/coins/<coingeckoNetwork>/contract/<contractAddress>` request shape: https://paw.pt/i90PfDIu
- Duplicates between Zerion and cg are handled properly
- Related assets not present in Zerion are parsed and upserted properly

### Estimated effort

1

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
