### ISSUE TITLE
Phantom support for imported HW wallet accounts

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7973]
Currently in prod (with solana flag enabled) if you attempt to connect phantom wallet for an imported ledger account the app enters an error state and phantom throws the following:

<img width="342" alt="Screenshot 2024-10-21 at 12 04 16 PM" src="https://github.com/user-attachments/assets/17becdc9-389b-4ef7-9682-6024bc2bdc3c">

We should allow phantom to be used even when an EVM based account is not present

**Comment by 0xean** [comment]
https://jam.dev/c/0eeab9c6-1578-4f10-80fa-d7be593683b7

**Comment by gomesalexandre** [comment]
Going to try and repro @0xean - assuming Solana support, we should definitely be able to connect to *at least* Solana and handle failures gracefully. @NeOMakinG could confirm but iirc pairing is only done on EVM accounts, and so is the deviceId for Phantom, which would explain why this happens.

**Comment by gomesalexandre** [comment]
@0xean looks like a chicken and egg scenario here - we need to request ETH permissions (or Solana permissions, same idea) in Phantom to try and get accounts and check for support, but we would like to know support *before* doing said request, so this looks like a feature with no technical inherently possible with our multichain nature, unless we did the same thing for Phantom that we do for Ledger (remove autodiscovery and make users add chains one by one).

Can you confirm you're eventually able to connect? i.e I do see the one error popup from the eth_request, though can eventually see Solana accounts here

https://jam.dev/c/445eb069-e9f0-45e2-835e-8094147571f8

**Comment by gomesalexandre** [comment]
<img width="556" alt="image" src="https://github.com/user-attachments/assets/fe4a8d15-6e81-4427-bb66-d67eaf8ef7a3">

Not sure if we want to spent such UX effort on that feature but this could be a relatively quick win @twblack88

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by 0xean** [comment]
Hmm....

I think it might be a quick and dirty option to reverse the order of this, so instead we connect Solana first on phantom and then later check for ETH / BTC... which may ofc fail.  At that point, alteast the user has connected their wallet succesfully.

I was NOT able to get connected at all when I first opened this ticket, but can try again to confirm

**Comment by 0xean** [comment]
And also agree that perhaps the Ledger like flow is ideal for Phantom. Always connect Solana and then ask about other chains.  @twblack88 ?

**Comment by twblack88** [comment]
Yeah that would be smart. 

 and would capture the ledger with a phantom wrapper use case right?

**Comment by gomesalexandre** [comment]
Going to give a try to "assume Solana support" for deviceId and initial connection @0xean @twblack88

**Comment by gomesalexandre** [comment]
@0xean can you confirm this is still happening for you after #8075? The only reason this is still open was because of possible product improvements here, but as far as this being a high-priority issue, this should be solved

https://jam.dev/c/0cc2fdaf-fa39-4024-8b04-00c1f77bde97

**Comment by 0xean** [comment]
confirmed this is much better. closing
