### ISSUE TITLE
Trading into Safe on Xdai looks like might have decimal in wrong place for 'you get' amount

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7983]
### Overview

When trading into safe on xdai the receive amount is way overstated - looks like decimal is in the wrong spot. Havent been able to recreate with safe on eth or bnb 

### References and additional details

![image](https://github.com/user-attachments/assets/ee521a4d-c5de-4560-8aa3-6195d650c256)
https://jam.dev/c/05eb33a0-08f8-48d6-ae4c-644ce09e340c

### Acceptance Criteria

Should state actual amount going to receive

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
I think this is an error from CoW:

https://api.cow.fi/xdai/api/v1/quote/ is returning `"buyAmount": "2038101678190893936",` while the precision is `15` in the coingecko API:

`{"chainId":100,"address":"0x4d18815d14fe5c3304e87b3fa18318baa5c23820","name":"Safe","symbol":"SAFE","decimals":15,"logoURI":"https://assets.coingecko.com/coins/images/27032/thumb/Artboard_1_copy_8circle-1.png?1696526084"},`

Nothing we can do on our side for now, do we have a contact at coingecko?

**Comment by NeOMakinG** [comment]
Submitted a request to coingecko, we can close this issue as it's not under our hands
