### ISSUE TITLE
Protocol fee for Lifi and Portals trades seems to be the same as the shapeshift fee

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7987]
### Overview

When previewing a lifi or portals trade that has a shapeshift fee - the protocol fee looks the same as the shapeshift fee

### References and additional details

![image](https://github.com/user-attachments/assets/893d681f-86b0-4393-aa01-0899bc1f959b)
![image](https://github.com/user-attachments/assets/e0d2109c-ad16-4103-9a2a-4512d6d93f30)
![image](https://github.com/user-attachments/assets/ee18feae-ea28-4a0a-8ce7-74444d38eb49)
https://jam.dev/c/6ac0773f-27f9-4697-853a-44524dba3192

### Acceptance Criteria

Protocol and shapeshift fee should be listed correctly

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
