### ISSUE TITLE
Lifi stargate v2 swapper gives an error while the trade is completing to contact lifi discord due to an unexpected error

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7988]
### Overview

Using stargate v2 swapper for lifi trade gives an error after broadcasting the transaction to contact the lifi discord . Trade still completes as expected but could be disconcerting for users to receive what seems like an unnecessary error.

### References and additional details

![Uploading image.png…]()
https://jam.dev/c/ed275e47-2200-48d5-8166-0e3704594bb1

### Acceptance Criteria

Should not show error message if there is no error

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by woodenfurniture** [comment]
Stargate is meant to be blacklisted from the swapper, so this looks to be more of an issue with not blocking `Stargate V2 (Economy Mode)`.

![image](https://github.com/user-attachments/assets/0958b659-d1bb-4afe-b8dd-652d8a377d1d)
