### ISSUE TITLE
Unavailable quotes drawer

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#7998]
### Overview

Currently in all envs, swapper displays some non-actionable quotes:

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/6264afd2-cf74-471e-b93c-245b3476abc9">

While some of these errors are something you can "fix" as a user (e.g not enough native asset, not enough fee asset, minimum not met etc), some others aren't really errors, and only mean the current selection is incompatible for a given swapper (cross-chain not supported, chain not supported, pair not supported) aren't really errors per se in the sense nothing failed upstream as a result of.

This PR is to add a drawer that will group all "unavailable quotes" (cross-chain not supported, chain not supported, pair not supported) into a drawer.

### References and additional details

N/A

### Acceptance Criteria

- A drawer is added that groups all unavailable quotes in their own collapsable drawer, collapsed by default
- Quotes that errored because of "wrong user state" (not enough balance, not enough fees, minimum not met...) are still displayed outside of the drawer

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by 0xean** [comment]
![image](https://github.com/user-attachments/assets/a06a2ffe-c9ce-463e-9528-3743281a52ac)

**Comment by reallybeard** [comment]
Here is a mock for this:
https://www.figma.com/design/ZkRqq0Bk1glXqIW776IAtr/Portals?node-id=636-3893&node-type=frame&t=ftzpLksOo2ZyCmx0-0

The empty state icon is from tabler `<TbRoute />`
