### ISSUE TITLE
Add Translations

### ISSUE THREAD

**Issue by bootsboogie** [shapeshift/web#8]
We are using RawText where we should be using Text components and there are a lot of other places we are just passing untranslated text into buttons and more

Here are a few places that need updating from the wallet merge
- PinModal
- NativeImport
- NativePassword
- NativePasswordRequired
- NativeSeed
- NativeStart
- NativeSuccess
- NativeTestPhrase
- SelectModal

**Comment by 420coupe** [comment]
take 2 cleaned up PR.
