### ISSUE TITLE
TX history not updating after trades are performed 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#8008]
### Overview

Currently in production, when a user attempts a trade in the app, the TX history does not update until a refresh/clear cache is performed 

### References and additional details

EVM trade that did not update: https://jam.dev/c/01df4776-6ba9-4b86-bc96-db4ad2a01ac5
TC trade that did not update: https://jam.dev/c/3396cf07-8ba1-4ebb-a62f-e74604bb265d https://jam.dev/c/1fe2eed3-ae8e-409c-9d1e-aafc1deb1d10

TX history resetting after a clear cache: https://jam.dev/c/68eb8c06-d58b-42a4-9d88-352be4908a23

### Acceptance Criteria

TX history updates after trades are performed within the app.

**Comment by Olowojaye** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by 0xean** [comment]
related to current WS instability.

**Comment by kaladinlight** [comment]
Most recent websocket durability improvements have looked to fix the websocket issues we have been seeing. APIs have been up all night and I am seeing detection and updates of tx history. I am _not_ seeing the balances update as expected however, so going to look into that next.
