### ISSUE TITLE
SOL asset available as an option in Swapper with no path

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#8016]
### Overview

Currently in release, SOL is available as an asset to be traded into even though there are no paths available to users.   

### References and additional details

SOL as an asset to be traded via swapper: ![image-2](https://github.com/user-attachments/assets/7816cf09-65f0-4d6f-8a98-8ac3f2b00962)

### Acceptance Criteria

Is it possible to have SOL omitted from swapper as an asset that can be traded until a route is available for it to be traded?

**Comment by MBMaria** [comment]
@kaladinlight  - not sure if the asset page of sol can have the trade widget greyed out? Even if you enter a custom address it just looks like its fetching a rate the whole time
https://jam.dev/c/458838db-bd6f-480a-958b-cfeb85b9da5d

**Comment by kaladinlight** [comment]
> @kaladinlight - not sure if the asset page of sol can have the trade widget greyed out? Even if you enter a custom address it just looks like its fetching a rate the whole time https://jam.dev/c/458838db-bd6f-480a-958b-cfeb85b9da5d

Good catch. I updated to use FOX as the default buy asset on solana asset pages
