### ISSUE TITLE
Free trades for thor holders.

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8019]
# AC
- utilize snapshot API to get thor voting power as of any time before the proposal is posted (today / tonight)
- Feature flag for launch
- any voting power greater than 1 human unit gets free trades on shapeshift while that wallet is connected 
- expires end of UTC year programatically 
- mix panel event fired for a user that completes a discounted swap based on THOR holdings

https://discord.com/channels/554694662431178782/920449863408287855/1300581700916740177

**Comment by reallybeard** [comment]
We need to consider the modal when a user clicks on Free for ShapeShift Fee. 

The easiest lift would be to turn it off for now, until we figure out a solution that handles more than just FOX.
