### ISSUE TITLE
Finish chainflip swapper implementation 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8026]
take over PR https://github.com/shapeshift/web/pull/7991 and bring through to production

- standard mix panel events for swappers
- clean up 
- shepherd through operations testing and into prod
- modify https://github.com/shapeshift/web/pull/8039 to allow solana (native asset and USDC) for chainflip as a valid

**Comment by CumpsD** [comment]
Thanks! I am around when you got questions! :)
