### ISSUE TITLE
Update trade complete screen

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#8027]
A little polish on this screen will go a long way to more volume and a better experience. 

- [ ] render a checkmark, draw the check animation by beard
- [ ] change to trade summary (instead of show details)

[new modal here](https://www.figma.com/design/lqcttmmnGtRtbjb8evL6Le/FOX-page?node-id=893-979&node-type=frame&t=Psp4D7HPd0PYMGKP-11)

Follow on ticket 
- [ ] #8028

**Comment by 0xean** [comment]
@reallybeard will make the animated check

**Comment by NeOMakinG** [comment]
We need to get it back, it's been removed with the new trade flow, make it great again with it!
