### ISSUE TITLE
Add on.Hover to the fiat amount of you pay

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#8038]
Inside trade modal,  the fiat amount can get confusing if users are thinking in those terms. especially as they come to the trade summary and forget that they have to participate in the market to finish "you get." 

We already make price difference in you get very clear, let's do the same for " pay with "

try to add a nice get hover effect on the whole section for explaining: "This is the approximate fiat value of your assets. Derived from coingecko and the amount of tokens you hold." 

![Screenshot 2024-10-29 at 5 03 49 PM](https://github.com/user-attachments/assets/80a1db5d-3e9b-4d4a-affe-4c148ef21b77)

**Comment by 0xean** [comment]
<img width="344" alt="Screenshot 2024-11-04 at 6 40 49 PM" src="https://github.com/user-attachments/assets/65c1dee4-97d7-4c7f-895e-4999425f521a">

add a simliar on hover to the fiat amount only when typying in crypto amounts into the trade input 

<img width="116" alt="Screenshot 2024-11-04 at 6 41 09 PM" src="https://github.com/user-attachments/assets/1864a5c6-5301-44d6-9251-6c5242ac4c38">

"This is the approximate fiat value of your assets. Derived from coingecko and the amount of tokens you hold." 

Product to discuss more on the solution here... no engineering action for the moment

**Comment by 0xean** [comment]
Closing because they went nuclear.
