### ISSUE TITLE
Selecting SOL to purchase through Banxa is a dead click

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8053]
### Overview

Trying to purchase SOL through Banxa is a dead click 

### References and additional details

![image](https://github.com/user-attachments/assets/3f5ec07b-c973-4593-914d-b13dcaccbaea)
https://jam.dev/c/3109d64e-bdbb-42b7-8ec4-9070c5f2f4ab

### Acceptance Criteria

Should be able to purchase SOL on banxa if listed as a provider

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by kaladinlight** [comment]
Thanks for the catch and fix of this bug!
