### ISSUE TITLE
Switching wallet doesn't recompute snapshot voting powers

### ISSUE THREAD

**Issue by NeOMakinG** [shapeshift/web#8058]
### Overview

If you first load a wallet like a native wallet, wait for snapshot vote power to load

Then switch to another wallet, it doesn't recompute the voting power

### References and additional details

Spotted in https://github.com/shapeshift/web/pull/8044#issuecomment-2450416103

### Acceptance Criteria

Switching to another wallet recompute all the snapshot voting power

**Comment by twblack88** [comment]
Fast follow b/c yeah we've been meaning to fix this. Thank you @NeOMakinG !!

#6128

**Comment by NeOMakinG** [comment]
Directly fixed by https://github.com/shapeshift/web/pull/8044, closing this 

https://github.com/shapeshift/web/issues/6128 is unrelated, we compute all previously connected wallet, this is a old feature, we might want to get rid of it to avoid abuses
