### ISSUE TITLE
Phantom w/ Ledger Multi Account Issues 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8062]
Currently the app can get confused with what wallet is connected via ledger and phantom.  

Repro steps from a cache clear:

1. Connect phantom w/ ledger account
2. Change to a diff ledger account
3. disconnect in app
4. reconnect in app
5. observe old account is still connected

User could end up mixing funds from the wrong wallet if not careful. 

Screen share without Jam so more windows are visible. 

https://github.com/user-attachments/assets/dfc27233-c641-438c-ad54-d7cb2f6f71a4

**Comment by 0xean** [comment]
retest after https://github.com/shapeshift/web/pull/8075 goes in

**Comment by NeOMakinG** [comment]
Seems like it works now: https://jam.dev/c/bfc630e8-7692-4e07-9895-bed1fc64b20c

https://jam.dev/c/cb71bae0-d041-4e60-9e94-d4cd39213f55

Reopen if reproduced 🙏
