### ISSUE TITLE
rFOX dashboard intermittently 0's when pointing at production endpoints

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#8070]
### Overview

The rFOX dashboard intermittently (about 30% of the time) displays 0's when refreshed. This only occurs when pointed at production endpoints via `yarn env app`. Pointing the app to dev endpoints via `yarn env develop` results in consistent correct display of rFOX dashboard data.

### References and additional details

Release branch running locally pointing at dev endpoints:

https://github.com/user-attachments/assets/7b38700f-7d79-485a-914a-f87eaab763c7

Release branch running locally pointing at prod endpoints:

https://github.com/user-attachments/assets/63918e55-80d7-4df5-ae56-19c7186f2fa2

### Acceptance Criteria

rFOX dashboard should not display 0's when refreshed.

**Comment by gomesalexandre** [comment]
@woodenfurniture looks like this has been automagically fixed? Trying out on prod atm, can't repro this behaviour with CMD + Shift + R hard refreshes
https://jam.dev/c/117fa67c-01c3-4385-874d-23a6156c12f0

**Comment by woodenfurniture** [comment]
Confirmed, just smashed refresh for a few mins, no issues found. Closing for now.
