### ISSUE TITLE
Account Management drawer could use a scrollbar

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#8077]
### Overview

True degens cannot add enough accounts because the account management drawer REFUSES to show a scrollbar.

Workaround is to zoom out on the app - not doable on mobile.

### References and additional details

https://github.com/user-attachments/assets/e55eead2-786d-4e43-b71f-5dcdea851898

<img src="https://github.com/user-attachments/assets/c2f6eee5-ef50-41cb-a70e-963b426c2de9" width="200">

### Acceptance Criteria

Ability to scroll when many accounts added.

**Comment by NeOMakinG** [comment]
it REFUSES

**Comment by NeOMakinG** [comment]
I did try to reproduce, no way, but I have a buggy scrollbar that I can only drag, leaving this open if someone see the no-scrollbar bug it might be better to let him fix it

**Comment by woodenfurniture** [comment]
Unable to repro after switching between branches 
<img src="https://github.com/user-attachments/assets/7e9f89b8-4d6a-4867-8c5f-4b3eb009da3f" width="200">
