### ISSUE TITLE
Drop down arrow for sorting functions on market page overlaps if screen is less than 100% 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8085]
### Overview

If you open devs tool, or scroll zoom out on the markets page, the sorting sections have the drop down arrow overlap the working slightly

### References and additional details

![image](https://github.com/user-attachments/assets/23ec2f83-bf68-4344-ae0b-ce1a59d60479)
https://jam.dev/c/95789b69-4209-41db-9118-fd4906027470

### Acceptance Criteria

Should be small space between word and arrow even is screen is shrunk

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
I think I've fixed it while fixing some other issues, reopen if I'm wrong but couldn't reproduce anymore!
