### ISSUE TITLE
Swapper flow improvements

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8100]
This has been this way for a while, but permit2 makes it a bit worse of a UX in my opinion.

We ask the user to do 2 clicks on the bottom of the screen (preview trade) 

![Screenshot 2024-11-07 at 5 47 09 AM](https://github.com/user-attachments/assets/ec5a65ee-16c3-4c64-a9c0-86d5ba1be18b)
 
and then confirm and trade 

![Screenshot 2024-11-07 at 5 47 31 AM](https://github.com/user-attachments/assets/aeee2da0-d8f6-4f11-a048-e0bdc930cfa6)

and then all of a sudden bury the user action mid page when we want them to sign. 

![Screenshot 2024-11-07 at 5 47 44 AM](https://github.com/user-attachments/assets/8be9bb98-47b3-4890-8750-95b9c1f110e1)

With permit2, we prompt the user and if they are using an external wallet, they are taken away from the context of the page and the changes to UI are very subtle 

![Screenshot 2024-11-07 at 5 48 27 AM](https://github.com/user-attachments/assets/407402b8-9f56-49f2-b070-742824584688)

Now the user is wondering what action to take since the UI change is minor and they never had to wait for a TX to confirm.

I would suggest:

1. Move all user actions to the bottom, so a user gets used to just clicking through the flow and not having to figure out wat do that is buried in our UI

**Comment by gomesalexandre** [comment]
re: > `was asked to execute a legacy approval transaction`  /  If a legacy approval is in place, we should not need a permit 2 signature also

Note, this isn't granting allowance to ZRX legacy router but rather this grants allowance to `0x000000000022d473030f116ddee9f6b43ac78ba3` i.e the Permit2 contract, which is required before signing the Permit2 message

re: `finally was able to execute the transaction after a refresh`

If I understand correctly, does it mean it's impossible to execute the trade without a refresh of the app?

**Comment by 0xean** [comment]
@twblack88 @reallybeard - think we might want to fix this ASAP. It feels a bit broken currently with permit2

**Comment by twblack88** [comment]
Onboard with moving all actions to the bottom button. @reallybeard and I started exploring something very similar this week so we can churn some mocks/flows pretty quickly.

**Comment by 0xApotheosis** [comment]
@twblack88 @reallybeard do we have finalized mocks for this yet?

**Comment by twblack88** [comment]
https://www.figma.com/design/VSXdqFlFkBhdcPs2WqJqMo/SWAP-UX?node-id=2644-8097&node-type=section&t=SPp8hvzHw1871zKG-11

looks like we didn't link from today.

**Comment by reallybeard** [comment]
This issue should prob be closed in favor of #8118

**Comment by 0xApotheosis** [comment]
Yeah isn't https://github.com/shapeshift/web/issues/8118 what we groomed today and called a `5`?

**Comment by 0xApotheosis** [comment]
Closing in favour of https://github.com/shapeshift/web/issues/8100
