### ISSUE TITLE
Swapper doesn't catch max (or close to) native sells as errors

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#8103]
### Overview

Spotted in https://github.com/shapeshift/web/pull/8087#pullrequestreview-2422488573

Currently in develop, it is possible to input a max, or close to, as a sell amount, which won't trigger an error

![image](https://github.com/user-attachments/assets/37f60f9d-a550-4ae7-a340-1a9a762566f5)

Math obviously doesn't check out here as (value + gas > balance) = revert:

![image](https://github.com/user-attachments/assets/c594a061-1306-4439-ad6b-bc3c01cf091a)
<img width="786" alt="image" src="https://github.com/user-attachments/assets/574fec1e-3453-4c79-a417-0f97aad01f3b">

### References and additional details

N/A

### Acceptance Criteria

- Those close-to-max sells are captured as "Not enough fee asset to cover gas" or best error and displayed in the available quotes list as errored

**Comment by NeOMakinG** [comment]
This has been introduced by the rate/quote split work: https://github.com/shapeshift/web/commit/d8c2efeb5d3248e133cb70abd6c1df9d78de2e52#diff-11cff69592f70893ba71b1f145ba4691cf7452b1c8188088b9769e13fd055ed9R257-R282

By commenting the condition on fees checks, it works again:

```ts
      !firstHopHasSufficientBalanceForGas && {
        // quoteOrRate === 'rate' && {
        error: TradeQuoteValidationError.InsufficientFirstHopFeeAssetBalance,
        meta: {
          assetSymbol: firstHopSellFeeAsset?.symbol,
          chainSymbol: firstHopSellFeeAsset
            ? getChainShortName(firstHopSellFeeAsset.chainId as KnownChainIds)
            : '',
        },
      },
      !secondHopHasSufficientBalanceForGas && {
        // quoteOrRate === 'rate' && {
        error: TradeQuoteValidationError.InsufficientSecondHopFeeAssetBalance,
        meta: {
          assetSymbol: secondHopSellFeeAsset?.symbol,
          chainSymbol: secondHopSellFeeAsset
            ? getChainShortName(secondHopSellFeeAsset.chainId as KnownChainIds)
            : '',
        },
```

![image](https://github.com/user-attachments/assets/abd5f8cc-abc2-480d-ae37-fb545eb7aef2)

Any reasons why these rates are considered quote at this point? As it's a WIP, before taking more time on trying to fix it, I prefer gathering your input 🙏
