### ISSUE TITLE
If a network is disabled in account management on MM but then used in a trade, address populates and re-adds the network

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8105]
### Overview

If you disable say BTC in MM then go to the trade modal and enter an eth to btc trade, to start with, the wallet address will say not connected, but shortly afterwards will populate and re-add BTC as an available network. Same as with eth as shown in jam below

### References and additional details

https://jam.dev/c/45e9cfa9-ba99-40fa-aca3-91230ce74c8f

### Acceptance Criteria

Should not automatically add a network without being prompted 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
Slightly different but same behavior: https://jam.dev/c/19fe7ceb-897c-4911-a33a-060e6a78749d
