### ISSUE TITLE
Surface "Address not supported" vs "User has rejected transaction" catch

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8117]
If an invalid address is used we currently catch the error and show the user "User has rejected the transaction" which leads to all sort of confusion. 

We should instead catch this specific error and alert the user with "Address 0x123 not supported" on the toast. This will help us and operations to better triage issues of this sort.

**Comment by 0xean** [comment]
bumping prio on this one due to more users coming in the door and more chaos with this issue.

**Comment by purelycrickets** [comment]
Is there a possibility that a copy button could be added next to the address in the error message?

**Comment by 0xean** [comment]
@purelycrickets - yep, Kev the UI wizard will do this for us
