### ISSUE TITLE
User rejected the transaction firing incorrectly 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#8128]
### Overview

Jam from an affected user that is getting the 'User rejected the transaction' error as something not related to the address validation endpoint. 

### References and additional details

Native wallet user, DOGE chain: 
https://jam.dev/c/5d4c64b5-5085-486e-b94e-a5329c9e5730

Error that fires: Error: failed to add input: Error: RangeError: value out of range

### Acceptance Criteria

User is able to interact with their DOGE without the 'user rejected the transaction' error blocking them from interacting with their funds.

**Comment by gomesalexandre** [comment]
For reference: 
- User's xpub looks absolutely fine (shared in DM) 
- From a quick googling, error is *not* originating from utxoSelect/coinselect, but rather bitcoinjs-lib `psbt.addInput` in native hdwallet i.e https://github.com/shapeshift/hdwallet/blob/c9f36aa0c96215bb5aa81dee164f0fbc01df9a88/packages/hdwallet-native/src/bitcoin.ts#L238

**Comment by purelycrickets** [comment]
User reached out again with a new Jam. Still blocked but with a new error message this time: 

{"error":{"date":1731951725910,"message_type":"FAILURE","message_enum":3,"message":{"code":9,"message":"Encountered invalid prevhash 2"},"from_wallet":true}}

https://jam.dev/c/43d60d6f-f4c9-4978-a3b8-83391db87e76

**Comment by 0xean** [comment]
1. attempt to bring us up to date with rc 7.0.0
2. if that fails use reference implementation above to get support for big int
