### ISSUE TITLE
Chain selector issues and clean up 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8135]
![image](https://github.com/user-attachments/assets/8b3dd5c6-27a7-4956-b0d8-9bb971bfef86)

Currently we show a duplicated ETH in the trade chain selection dropdown.  Additionally we show wrapped assets here for some reason.  I think these are both bugs (cc @shapeshift/product ). wrapped assets should be treated like all other ERC20 assets and shouldn't be mixed in with the chain selection process.  I can see an argument for potentially allowing this for chain that don't have a native representation of ETH, but for chains like arbitrum that do, this just seems overly 
confusing.

**Comment by reallybeard** [comment]
I think @woodenfurniture was working on a fix for this.
