### ISSUE TITLE
Bad UX with asset search in swapper. 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8139]
In the swapper we currently don't show USDC as a pinned asset on the top, when a user attempts to search for it we suggest really bad first options for USDC, and the actual USDC is buried in the search. 

![Screenshot 2024-11-18 at 6 36 58 AM](https://github.com/user-attachments/assets/7f499d2e-2b68-4b96-a1f2-88b81e5d7c6a)

A user has to 

1. know that the first USDC we suggest isn't the correct one, because they wont get any rates back with whatever spam token that actually is.
2. scroll down three full pages to find USDC on ethereum 
![Screenshot 2024-11-18 at 6 38 01 AM](https://github.com/user-attachments/assets/0326d4a0-4e32-464b-b1f1-ba5495f21cb8)

4. scroll past several other chain suggestions for USDC even tho the chain selector has ETH selected AND the wallet has ETH selected. 

We should solve this.  My suggestions would be 

1. pin USDC to the top just like USDT
2. determine a better sorting algo for assets ( can we use market cap / trade volume or some other metric to better sort assets that match search criteria)
3. Show assets on the currently connected chain and selected chain in the swapper first.  (USDC on ETH shows up ahead of USDC on polygon for example)

**Comment by 0xean** [comment]
cc @shapeshift/product

**Comment by twblack88** [comment]
wondering how much overlap with  #7900

**Comment by 0xean** [comment]
This is gonna be high prio - we can discuss during grooming, but the USDC assets we are suggesting PAGES ahead of the real assets are scam / spam tokens.

**Comment by 0xean** [comment]
### for this ticket:

Sort order in search:
- Assets with fiat balance 
- Assets sorted by market cap (from asset generation)
- Asset with non zero balance but zero fiat value (sort alphabetically)

Remove 0 mcap tokens from asset metadata 

### longer term: 
- add hide list for assets 
- pair down search within swapper to remove more esoteric items w no MC that still may be desireable from portals
  - filter that allows for low caps in search (default to not include low or no mc tokens)
- add warning to confirm user wants to interact with a low mcap token

**Comment by 0xApotheosis** [comment]
For posterity, the reason we don't necessarily show USDC as a pinned asset is because this list is dynamic.

We have `useGetPopularAssetsQuery` which calls `getMarketServiceManager().findAllSortedByVolumeDesc()` - we then dynamically pin the top 5 (either by chain, or overall is "All" is selected).

**Comment by 0xean** [comment]
@0xApotheosis - thanks for that, forgot to add that to the scope of this during grooming, but will add a separate ticket for this.
