### ISSUE TITLE
Less invasive rate changed UX 

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#8144]
### Overview

Placeholder for @shapeshift/product, raised by @0xApotheosis in https://github.com/shapeshift/web/pull/8079#pullrequestreview-2444202042

![image](https://github.com/user-attachments/assets/5cbe9c6f-4da5-4d93-b9eb-4c8d692df296)

> We should probably show the difference in the rate, maybe as a percentage here. This popped up every time for me when using Portals (maybe because we go from not knowing gas to knowing gas? This itself feels like a bug/undesirable behavior), and every time I had to try work out if the rate got better or worse, but I didn't know because I had no reference point.

Indeed, this does look like a broken flow to have that show up *consistently*, as rates changing isn't an exception but the regular flow here. 

### References and additional details

https://github.com/shapeshift/web/pull/8079

### Acceptance Criteria

- A less invasive UX is used to display rate changed (maybe a popover/tooltip of sorts that's well-visible, but less "in your face'?)
- The change in rate is displayed either as a percentage or as a fiat/crypto diff, or a mix of both

**Comment by 0xean** [comment]
https://docs.google.com/spreadsheets/d/1-gjh29Ns8q_IyQuJoUE4xP4e6XEV_n7ks__1_maSMMk/edit?gid=0#gid=0

**Comment by 0xean** [comment]
Per conversation today with team, we are gonna move forward fixing portals and then looking at a threshold based approach. Portals does not allow us to set an absolute number for min out, just a percentage.

**Comment by 0xean** [comment]
@shapeshift/product will circle back on the threshold based ideas as we get more feedback with the release going out and splash page being removed but for now we should get the modal updated.
