### ISSUE TITLE
KeepKey BTC accounts not detected and automatically for BTC segwit balances

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#8156]
### Overview

Currently in production, with a clear cache, when connecting a KeepKey with a Segwit balance only in Account 0, we do not detect the balance and require the user to manually add their BTC address.  

### References and additional details

I was able to get balances to load initially for a personal KeepKey with a higher BTC balance (Segwit Native) on initial load with a clear cache, but could not get the same results for my test KK that only has BTC in a segwit address.

Jam of no BTC account detection even though there is a BTC balance: https://jam.dev/c/f034e8b5-3ea1-48e9-b8d0-0e8baf1eec78

A user in this situation could think they have lost their BTC, panic, and not know how to toggle their accounts in manage account to reveal them.

### Acceptance Criteria

KeepKey accounts with balances are detected for all supported chains without the need to manually add them.

**Comment by purelycrickets** [comment]
Getting more reports from users about this issue blocking them from seeing their balances.

**Comment by purelycrickets** [comment]
This is now appearing to also affect other UTXO chains like DOGE and LTC.

**Comment by NeOMakinG** [comment]
I did try to reproduce multiple times using:

- An already existing wallet
- A fresh new wallet
- With Segwit
- With Segwit native
- With wallet with another tx history already existing

I'm struggling to reproduce... If you have any other interesting informations to share, I feel stuck now :/

**Comment by 0xean** [comment]
@kaladinlight to also attempt to recreate

**Comment by purelycrickets** [comment]
The jam shared in the ticket is a recreation, I can consistently reproduce and jam with my test KeepKey but do not currently have access to the seed.  I can take another Jam if there is any information that helps in the logs but will need another day to deep dive for a seed phrase if that is the only way to diagnose further.

**Comment by kaladinlight** [comment]
Firmware update fixed the problem for @purelycrickets. Awaiting to hear from affected users if they are out of date and updating to the latest firmware version fixes the issue for them as well

**Comment by 0xean** [comment]
closing for now - users have been told to update and seems to have solved the problem
