### ISSUE TITLE
Unable to broadcast transactions through Kyberswap via LiFi

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#8158]
### Overview

Currently in production, A user is able to select Kyberswap as a route via LiFi in certain trades, but the trade will fail if Kyber is selected.  The same pairs are successful with other routes selected. 

### References and additional details

See jam of issue: https://jam.dev/c/bcd2716a-2746-4f22-a15b-475abb4cd73d

### Acceptance Criteria

Issue blocking Kyberswap functionality via lifi should be fixed, or Kyberswap should be turned off as a route option.

**Comment by gomesalexandre** [comment]
@purelycrickets can't repro on MM https://jam.dev/c/9fc80b90-2a5c-4270-8036-78223a8475ab nor native https://jam.dev/c/652ae2a2-e3ed-46fc-8d87-5f16fb1f0ff9 is still still happening for you? 

Looking at the Jam's network requests however, this seems to be a transient node issue (here re: fees estimation), which would be related to https://github.com/shapeshift/web/issues/8190 and would explain why trying at a diff time yields diff. results.
