### ISSUE TITLE
NFT related spew on initial load

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#8167]
### Overview

This issue only affects the console log, so this may be a non-action ticket, but currently in Production, upon initial wallet connection, the console spews dozens of Zerion 404s and Alchemy 429 rate limit errors filling the console log.

### References and additional details

Jam of issue: https://jam.dev/c/8431010c-aa3c-4f82-84cb-4f165f156c36 

### Acceptance Criteria

Clean console logs? Operations is not sure if these errors are intentional or erroneous.

**Comment by 0xean** [comment]
potential for client side rate limiting to better conform to api endpoints from providers

**Comment by gomesalexandre** [comment]
Tested with willywonka.eth (it doesn't get spammier on XHRs than this!) and confirmed
- those Zerion 404s are actually expected, this is a result of market-data not being found for a given asset upstream
- Alchemy XHRs can be rate-limited on the client-side as proposed by @0xean. With that being said, I think a first step to stop the bleed with Alchemy would be to not fetch NFTs app-wide, but only from the dashboard, and *then* follow-up with sane rate-limiting.

**Comment by gomesalexandre** [comment]
re: Alchemy throughput https://docs.alchemy.com/reference/throughput

https://docs.alchemy.com/reference/throughput#option-1-alchemy-sdk

> [Alchemy SDK](https://docs.alchemy.com/reference/alchemy-sdk-quickstart) is an Ethers.js wrapper that automatically handles retry logic for you. It's the easiest way to build retry logic into all of your requests.

We actually do use the SDKs, so retries *are* implemented as recommended by docs without any lift required.
