### ISSUE TITLE
Add warnings to open orders when order cannot be filled

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#8217]
### Overview

We want 2 warnings when an order is "unable to be filled"

- Insufficient balance
- Insufficient allowance

Add code comments explaining the difference between "unfillable" (a notion with spot orders which related to "out of market") vs "cannot be filled" (due to balance + allowance reqs).

### References and additional details

https://github.com/shapeshift/web/pull/8173#pullrequestreview-2466740965

<img src="https://github.com/user-attachments/assets/cf0241a9-964b-40a1-ab9e-b4e876b6dd13" width="200">
<img src="https://github.com/user-attachments/assets/5d960216-7c93-4b00-82bb-9ad0b4dbce1e" width="200">

### Acceptance Criteria

Code comments documenting "unfillable" (a notion with spot orders which related to "out of market") vs "unable to be filled".

UI on open order card with 2 warnings when an order is unable to be filled:

- Insufficient balance
- Insufficient allowance

**Comment by gomesalexandre** [comment]
@woodenfurniture when we tackle this guy, wondering if we'll want to also revert balance input validation changes? e.g:

<img width="501" alt="image" src="https://github.com/user-attachments/assets/5de735c9-b225-4586-a88c-4855756d1009">

I may want to place a limit order for this guy, knowing I don't currently have enough balance but I may by the time this gets filled. 

As it currently stands, skipping validation may or may not look odd as users do not have any info that their order is un/fillable, but as we implement this lil' Unfillable tag, then it will make perfect sense to let users place limit orders for balances higher than their current ones, or even for assets they currently don't hold any balance of at all currently

**Comment by woodenfurniture** [comment]
Just updating the spec here:
We want 2 warnings rather than "unfillable"
1. Insufficient balance
2. Insufficient allowance

Looking at the cowswap source code, it appears the notion of "unfillable" refers to a limit price (i.e slippage) outside a hardcoded percentage of the market price, for spot trades. If a spot trade goes outside that hardcoded threshold, it is marked as "unfillable" in their order list.

https://github.dev/cowprotocol/cowswap

![Image](https://github.com/user-attachments/assets/72aa72e9-f840-4616-a5c9-8b6bcb4511f9)
![Image](https://github.com/user-attachments/assets/f136ef72-7782-4050-a5d0-677569294e5e)
![Image](https://github.com/user-attachments/assets/926550cf-4cd0-4210-8b81-32a8712667b8)

**Comment by woodenfurniture** [comment]
As this seems to be nice-to-have, I'm going to lower the priority.
