### ISSUE TITLE
Intermittently getting black screen when navigating through app

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8237]
### Overview

Don't know exact recreation steps but has happened a few times, no time has been the same. when selecting something in the app, the screen goes black and get an error in the console. Unable to catch on jam yet as i cannot seem to do the same thing twice to recreate it. A refresh unrugs it.

### References and additional details

![image](https://github.com/user-attachments/assets/de200128-2fa1-470f-aeb6-bdd3b45ef9f6)

### Acceptance Criteria

Should not get black screen while navigating the app

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
First attempt at fixing: https://github.com/shapeshift/web/pull/8255

I think this is the issue but let's say we reopen the issue if we face it again after the merge
