### ISSUE TITLE
Update copy for Ctrl wallet(FKA xdefi)

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#8244]
### Overview

Xdefi has rebranded to Ctrl wallet https://ctrl.xyz/ 

We should update the copy and images appropriately where needed, such as the wallet connect modal. 

### References and additional details

https://ctrl.xyz/
https://discord.com/channels/554694662431178782/1275196805163782154/1275200957231140955

### Acceptance Criteria

xdefi wallet and assets are updated to Ctrl wallet and assets

**Comment by tolltalcrypto** [comment]
@twblack88

**Comment by gomesalexandre** [comment]
Tackled by https://github.com/shapeshift/web/pull/8252 but one reference still exists re: xdefi download page
