### ISSUE TITLE
Research and implement token account creation for Solana affiliate fees

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8247]
Proposed solution:

if the affiliate address doesn't have a token account and a user attempts to swap with a new token include in the tx the instruction to create the token account. Only do this if fees are included in the transaction. 

before implementing ask / research alternative options 
- jupiter discord
- jupiter docs

**Comment by 0xean** [comment]
Non blocking for the upcoming production release

**Comment by NeOMakinG** [comment]
So I did try to talk with Jupiter:

## First solution (the one I think is the most effortless and viable)
- Pre-creating SOL, USDC, USDT accounts should cover a lot of the swaps (I would also suggest creating like the top 10 assets like JUP, BONK, etc, Jupiter list should be ordered by mCAP I think)
- Make our big swaps users pay for the referral account opening if both assets doesn't have a referral account linked

## Second solution
- Host a server with a private key, that will open referral account just before the swap lends (Bigger effort => managing another webservice, could lead to bugs if the funding wallet remains empty, could be drained by a spammer)

I couldn't find any more solutions

Opened a PR supporting the automatic account creation:

- If the account exist, don't create it
- If it doesn't exist, the user pays for it, but it probably means this is an "exotic" swap with 1000$ amount

It's included as platform fee in our interface and taken account in balance validations at rate time

**Comment by 0xean** [comment]
Thanks @NeOMakinG to confirm 

> Make our big swaps users pay for the referral account opening if both assets doesn't have a referral account linked

this is only when a fee is already being added, correct?

In the future if we did find this to be problematic, we could always lower our affiliate fee to take it into account, although for now I think its negligible and am glad we are going forward with this solution

**Comment by NeOMakinG** [comment]
> Thanks @NeOMakinG to confirm
> 
> > Make our big swaps users pay for the referral account opening if both assets doesn't have a referral account linked
> 
> this is only when a fee is already being added, correct?
> 
> In the future if we did find this to be problematic, we could always lower our affiliate fee to take it into account, although for now I think its negligible and am glad we are going forward with this solution

Exactly, it's only if the fees are applied

Also I think I think we can create 10-20 accounts that should cover the biggest assets at start

And yes if users complains or we find it very hard, let's lower the fees for this particular case!
