### ISSUE TITLE
Overlay of tooltips on Portals trade

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8250]
### Overview

When moving from the gas icon to the amount, the tooltips overlay and you cant read the one underneath 

### References and additional details

![image](https://github.com/user-attachments/assets/62b5e227-7de0-45dd-8078-68157ffdaa88)

### Acceptance Criteria

Should be able to see both tooltips clearly

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
We should simply disable one of both tooltips in this view as it's already contained inside another tooltip, which one should we keep @shapeshift/product ? I guess we could remove the "Continue swapping for final details" from this view

**Comment by gomesalexandre** [comment]
@NeOMakinG "Continue swapping for final details" was precisely added for this specific context, makes sense to me we would rather keep this one? See https://github.com/shapeshift/web/pull/8288

**Comment by 0xApotheosis** [comment]
> @NeOMakinG "Continue swapping for final details" was precisely added for this specific context, makes sense to me we would rather keep this one? See #8288

100%, this feels like the original intent of the tooltip.
