### ISSUE TITLE
protocol fee on portals is way overstated

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8266]
![Screenshot 2024-12-04 at 5 12 40 PM](https://github.com/user-attachments/assets/a8ffb821-f2bd-4162-aae1-d9d76fd1265f)

repro steps:

1. get a portals quote
2. click into the trade confirm page
3. notice the large protocol fee

**Comment by gomesalexandre** [comment]
We may either have to rethink that assumption, or are dealing with wrong precision here

https://github.com/shapeshift/web/blob/2f7cfc1318f29fa140aca1b97f7ef4f983b54d24/packages/swapper/src/swappers/PortalsSwapper/getPortalsTradeQuote/getPortalsTradeQuote.ts#L180-L188
