### ISSUE TITLE
Unable to interact with AVAX

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8273]
### Overview

Currently getting errors when trying to interact with AVAX - sends are failing as well as trades 

### References and additional details

Error for send: Error getting fees 
![image](https://github.com/user-attachments/assets/b940b929-4a19-4116-b230-a26c35f3ab84)
https://jam.dev/c/b091cafb-2d3e-472d-b346-9218d04afdb1
Error for trades: Failed to estimate network fees
![image](https://github.com/user-attachments/assets/de74d18d-751f-423f-8b35-2a4935eb55df)
 https://jam.dev/c/80ecedeb-d173-4767-8a9d-8893627de37a

### Acceptance Criteria

Should be able to interact with AVAX

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by kaladinlight** [comment]
I am seeing timeouts on nownodes avalanche nodes. Pinged them for resolution.

**Comment by kaladinlight** [comment]
Issue has been resolved:

![image](https://github.com/user-attachments/assets/fde6984d-5908-460b-93b7-e540466c8e12)
![image](https://github.com/user-attachments/assets/18c4909e-8d13-4089-91ab-c4c7f8c65efa)
