### ISSUE TITLE
Receive address not showing on confirm and trade screen in trade modal for thorchain, 0x and portal trades

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8289]
### Overview

When moving to the confirm and trade screen in the trade modal, the address the funds are going to does not populate straight away if its a thorchain, 0x or portals trade. you have to confirm and trade before the address appears. Lifi trade show the address straight away.

### References and additional details

![image](https://github.com/user-attachments/assets/421379a3-362f-456e-89e8-b6d79042497e)
![image](https://github.com/user-attachments/assets/f64d35f5-f208-483c-909a-8974a89608ba)
https://jam.dev/c/3e7128fe-cc75-4d32-a050-bbc058342624 

### Acceptance Criteria

Should show receive address when move to preview trade

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
This is because we don't have a `receiveAddress` on most _rate_ quotes (except LiFi).

We might want to re-think this.

https://github.com/shapeshift/web/blob/76353dbaa5c2cf6c9791676f9bf7118262fa44a2/src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StepperStep.tsx#L37-L50

**Comment by gomesalexandre** [comment]
That's correct @0xApotheosis!

Seems like a catch-22 of sorts here. We want no `receiveAddress` to discriminate rates, but at the same time, we want the `receiveAddress` to flow if available.

Looks like it can be easily solved by using another discriminator i.e `'quote' | 'rate'`, which would allow us to have our cake and eat it:

- discriminate between rates and quotes with this simple string discriminator
- actually return `receiveAddress` back whenever possible

**Comment by 0xApotheosis** [comment]
> - discriminate between rates and quotes with this simple string discriminator

Sounds like the perfect path forward 🤝
