### ISSUE TITLE
Blank screen attempting to execute bridges on Li.Fi

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#8344]
### Overview

When attempting to execute a bridge on lifi, the screen goes blank when attempting to sign the transaction:

<img src="https://github.com/user-attachments/assets/811cc548-ee16-4aa4-af4b-9ddef791c15e" width="200">

### References and additional details

HTTP 400 from their api:
<img src="https://github.com/user-attachments/assets/73657475-7cd4-4cc0-b23a-595fe8dbd01d" width="200">
![image](https://github.com/user-attachments/assets/6cbb24c6-f151-4147-b08d-96206ec208ac)

### Acceptance Criteria

Able to trade on lifi swapper.

**Comment by gomesalexandre** [comment]
This has been introduced by https://github.com/shapeshift/web/pull/8326.

Just to be disambiguate things here, there are two bugs at play, and this one refers to `oneOf` (pun intended) them

### Us wrongly passing bridges 

This one is an easy one and a blatant mistake on my part:

https://github.com/shapeshift/web/blob/687a26583564acbd1e37482778a0aaf277c1b050/packages/swapper/src/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts#L100-L103

We pass the tool previously gotten at rate time as `options.tools.exchanges`, however, this shoudn't live in `exchanges[]`, this is a `bridges[]`. The insertion should be programmatic on the type of tool it is.


### Li.Fi quote is gone from one call to the other (**not** this bug)

This only happens in rare cases when the tool selected is not available anymore, i.e see happy quotes:
https://jam.dev/c/95b9c602-c742-4891-82b0-816a1189b7e3 (with one sad empty state occurence of blank screen at the end, but for an entirely different rate-limit reason)
vs. sad quotes: https://jam.dev/c/9241dff2-4c51-47d8-93be-5a62c84379a7

See in the latter, Enso, if you manage to get a rate for it, is the perfect contender for this bug - it looks like Li.Fi are hitting their own rate limits internally (the response is a 200 however):

```typescript
{
  "routes": [],
  "unavailableRoutes": {
    "filteredOut": [],
    "failed": [
      {
        "overallPath": "42161:FOX~42161:USDC",
        "subpaths": {
          "42161:FOX~42161:USDC": [
            {
              "errorType": "NO_QUOTE",
              "code": "RATE_LIMIT_EXCEEDED",
              "action": {
                "fromChainId": 42161,
                "fromAmount": "1210000000000000000",
                "fromToken": {
                  "address": "0xf929de51D91C77E42f5090069E0AD7A09e513c73",
                  "chainId": 42161,
                  "symbol": "FOX",
                  "decimals": 18,
                  "name": "FOX",
                  "coinKey": "FOX",
                  "logoURI": "https://static.debank.com/image/eth_token/logo_url/0xc770eefad204b5180df6a14ee197d99d808ee52d/a3ba70c14f1dfe0cd7bff6c759686b33.png",
                  "priceUSD": "0.08580374324695125"
                },
                "toChainId": 42161,
                "toToken": {
                  "address": "0xaf88d065e77c8cC2239327C5EDb3A432268e5831",
                  "chainId": 42161,
                  "symbol": "USDC",
                  "decimals": 6,
                  "name": "USD Coin",
                  "coinKey": "USDC",
                  "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png",
                  "priceUSD": "0.99930048965724"
                },
                "slippage": 0.005,
                "fromAddress": "0x5daf465a9ccf64deb146eeae9e7bd40d6761c986"
              },
              "tool": "enso",
              "message": "The tool has exceeded its rate limit."
            }
          ]
        }
      }
    ]
  }
}
```

Gut feel is the best way to handle this is to catch those specific failures (tool not available anymore a

**Comment by gomesalexandre** [comment]
Bad bot GitHub, closed by https://github.com/shapeshift/web/pull/8348
