### ISSUE TITLE
ShapeShift fee always in USD even if app is in different currency

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8360]
### Overview

When viewing the ShapeShift fee on a trade, it is in USD amount even if the app is in different currency 

### References and additional details

![image](https://github.com/user-attachments/assets/8500d3d8-7350-4b87-bbbd-3845d46bce51)
![image](https://github.com/user-attachments/assets/dd50cf83-02e3-45b0-980d-124bdd96f674)

### Acceptance Criteria

ShapeShift fee should show in the same currency the app is set to

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by DanErbo23** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SHAPESHIFT SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
