### ISSUE TITLE
Unable to trade custom import token - Emperor Trump 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8370]
### Overview

A user is unable to trade an asset called Emperor Trump on base network. 
Looks like it was a manual import token.... Is this a bug or would it be due to the nature of the token itself?
contract: 0xCfbDAA56F1945e377fFdF38a5612c37f48819927 
https://basescan.org/address/0xCfbDAA56F1945e377fFdF38a5612c37f48819927 

### References and additional details

![image](https://github.com/user-attachments/assets/b990f5b7-e1fb-4a72-bbd7-cee4a9c3c7d6)

### Acceptance Criteria

Not sure if we should be able to trade..? 
there is this bad boy to sign before trading into import i guess 
![image](https://github.com/user-attachments/assets/49ab4ddd-a9ab-465c-9eb0-f828eea25ae9)

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by DanErbo23** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SHAPESHIFT SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by gomesalexandre** [comment]
@MBMaria closing as this is a gas estimation call for this specific token, erroring with `execution reverted: SafeERC20: low-level call failed` : https://jam.dev/c/c34e22e4-82b4-43d4-93d5-0c1cb5100b96

This means that even gas estimations aside, the actual Tx would error for the same reason and would never make it on-chain

Confirmed that bumping the slippage is a no-go either: https://jam.dev/c/b8ca189f-c9ca-4432-a358-8a517f7259ba
