### ISSUE TITLE
Chainflip - Cannot get BTC sell quote without wallet connected

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#8377]
### Overview

See Jam below:

https://jam.dev/c/113d544d-3ab3-482c-85b9-c7c316336a98

When attempting to get a BTC sell quote, quotes are not surfaced without a wallet connected. They are however fetched just fine, as can be see with the flip API calls

### References and additional details

N/A

### Acceptance Criteria

- BTC sell quotes are surfaced without a wallet connected

**Comment by Davodavelication** [comment]
@gomesalexandre For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by gomesalexandre** [comment]
Closing as duplicate of https://github.com/shapeshift/web/issues/8178, already fixed
