### ISSUE TITLE
native wallet evm networks not detected

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#8404]
### Overview

Currently in production without clearing my cache, I am able to connect different native wallets, but I get prompted that no ETH wallet is connected.

### References and additional details

https://jam.dev/c/abaae115-80b5-424a-8524-46f1966c90f5

### Acceptance Criteria

native wallets evm accounts are detected on initial load.

**Comment by Musk1045** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SHAPESHIFT SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by purelycrickets** [comment]
I started a new browser session for testing elsewhere and can no longer reproduce the issue.  I will keep an eye out for any reports of similar symptoms in support and escalate.  Seems like it must have been a weird local issue. 

Closing for now, Thanks @gomesalexandre for looking into repro'ing.
