### ISSUE TITLE
Dynamic Text Sizing

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#850]
# Background
We have had community contributors make a few passes (see #709 ) at dynamic text sizing and while the issue has been resolved, we think there may be a better css based solution (potentially using clamp) to solve this.

This issue can be picked up by anyone and we will happily tip anyone that has a clean solution to the problem and opens a PR that implements that and removes the old code paths from #836 

# Acceptance Criteria
- CSS based solution to dynamic text sizing in fields that expand as the number of digits grown
- Tested and working in all localizations
- bonus points and tip for a re-usable component that we can implement anywhere this type of text would be needed.

# Screenshots 
Current Solution Example:
![image](https://user-images.githubusercontent.com/15096737/151044775-9f2a91e6-1969-4ce3-aa06-4b1e7b4718ee.png)
Old issue that prompted the fix (see the clipping):
![image](https://user-images.githubusercontent.com/15096737/151044778-d5f55cf4-2bcd-4a7c-9988-82efb4112033.png)

**Comment by bronco-eth** [comment]
Hi! Just to let everyone know, I'm taking a stab at this and will post a PR soon.

**Comment by 0xean** [comment]
Awesome!
