### ISSUE TITLE
Add Language selection setting

### ISSUE THREAD

**Issue by cjthompson** [shapeshift/web#854]
AC:
* Add UX to allow a user to change the language of the website. Note: _Product Team to provide wireframes_
* The language selection should list all available translations (e.g., `messages-en.json`)
  1. on selection of a different language, the selection should be saved to LocalStorage (see `preferencesSlice.tsx`). Note - refer to this PR that removed `preferencesSlice`. Feel free to revert this PR to bring back `preferencesSlice` implementation https://github.com/shapeshift/web/pull/822
* On launch, the app should 
  1. check LocalStorage for a language preference (see `preferencesSlice.tsx`) and set the translation accordingly
  2. check if there is an available translation for the browser's default locale and set the translation if one matches (but do not write a persistent Preference in LocalStorage)
  3. default to English (but do not write a persistent Preference in LocalStorage)

There is no requirement to add additional language translations for this ticket but once an additional language is added, it should "just work". During development, the developer may want to make a fake alternate translation to verify functionality.

**Comment by amitojsingh366** [comment]
I would like to work on this!

**Comment by LPX55** [comment]
@amitojsingh366 there's a draft PR that has the front-end ready, just need to implement state store -- unfortunately I've been caught up with other things to finish but feel free to finish the job :) https://github.com/shapeshift/web/pull/828

**Comment by 0xean** [comment]
waiting for product input on UX

**Comment by SS-FOX-McCloud** [comment]
Issue is resolved in https://github.com/shapeshift/web/issues/1163
