### ISSUE TITLE
V2 (Alpha): copy change on wallet connect screen (Portis and Metamask only)

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#856]
After connecting a Metamask or Portis wallet the successful wallet connected modal comes up.  The modal has duplicate copy.  

- visit app.shapeshift.com
- connect a metamask or Portis wallet
- see the incorrect copy in the success modal

The bold title copy should stay the same:
"Your Wallet has been connected"

The body should have this new copy:
"You can now close this window or it will auto-close shortly"

![Screen_Shot_2022-01-27_at_12](https://user-images.githubusercontent.com/57505863/151445900-b2b79c36-d426-4b92-ae85-ee06b1a7e217.png)

**Comment by SS-FOX-McCloud** [comment]
@0xean this might be a good bounty!  Not a priority.

**Comment by amitojsingh366** [comment]
I would love to work on this bounty!

**Comment by 0xean** [comment]
thanks @amitojsingh366 !
