### ISSUE TITLE
Handle long digits in amount inputs

### ISSUE THREAD

**Issue by bronco-eth** [shapeshift/web#868]
**Problem**

When entering long digit counts into the amount input fields, the displayed numbers are getting clipped to the size of the input.

**Possible solution**

Based on flexible input component from https://github.com/shapeshift/web/pull/863 make amount inputs scalable with the number of digits, so the whole number is always visible.

Just a side note: I couldn't assign myself to this issue, because of permissions, but I'm working on it.

**Comment by reallybeard** [comment]
I appreciate the thought into this, but I think for these type of inputs we just go with the default behavior. The user can scroll the input left or right if they would like to see the full number. Scaling these numbers based on their input length will end up with some really weird visuals.

**Comment by 0xdef1cafe** [comment]
@bronco-eth appreciate the issue and the PR, but i'm going to defer to @reallybeard here from product as he's the design man. at this stage we're going to close this PR.

**Comment by 0xean** [comment]
@bronco-eth - apologies as I told you to move forward with this work.  I am getting a tip sent over either way!

I hope you will pick up another issue with us!

**Comment by bronco-eth** [comment]
Hi @0xean, ah i see, no worries, text scaling might not be the standard way of handling long numbers, anyhow it was fun working on it and thanks for a tip! I'll keep looking for other things.
