### ISSUE TITLE
v2: User can send ERC20/ETH without gas to cover it

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#872]
Steps to reproduce:

- Have a wallet with some ETH/ERC20 on it, but not enough gas to cover a transaction
- Try to send an asset and input some amount greater than that asset balance for your wallet
- The send button goes to error state with "Insufficient Funds"

- Reload app and reproduce the steps above, this time with an amount within your balance
- The app will let you complete the flow all the way to the broadcast of the transaction, however your wallet will not let you broadcast it, since there isn't enough gas to cover it. The only way is to close the window, which means being prompted with a declined transaction UX feedback, which is true, but wrong as you are effectively forced to reject it

- If trying to send ETH (at USD OR ETH value) without enough gas to cover it, the app will take long enough to estimate gas , so it is possible to click next and complete a similar flow to broadcast if fast enough to click, which will also result in a Metamask modal user is forced to decline because of lack of gas to cover
- If trying to send ETH (at USD or ETH value) that is out of user balance range, the app will take long enough to estimate gas, so it is possible to click click next and complete a similar flow to broadcast if fast enough to click, which will result in the fees estimation modal to infinite load

- If trying to send max ETH (at USD or ETH value) with barely enough gas to cover it, the app will calculate a wrong, negative value. It is however possible to complete the flow without problem if using the slow fee (that's why the 0x API returns us a valid estimation). But we use the fast fee as the amount to reduce from the value, so we effectively get a negative number. 

**- The lack of gas to cover for the transaction should be caught at the same moment as the send amount vs . wallet balance check** 

For reference, this is how 1inch handles it, at this exact step:
![image](https://user-images.githubusercontent.com/17035424/151696494-8268ca49-3f0f-4dbe-974d-28c539ee9eaf.png)

**Comment by gomesalexandre** [comment]
@0xApotheosis I'm aware that there is work done on gas estimations being done in https://github.com/shapeshift/web/issues/526 - still, I suppose it's probably expected for estimations to always have some discrepancies since different wallets / front-ends always calculate it slightly differently, right? If so, and independently on the gas estimation improvals, what about erroring on negative number?

**Comment by 0xApotheosis** [comment]
Solid suggestions.

I left a comment on https://github.com/shapeshift/web/pull/875, though out of those two options above, the first is the most informative - it lets the user know by how much they are short to facilitate a transaction.

A `title` on the send button with a description of what's going on might also improve UX.

**Comment by gomesalexandre** [comment]
Closed in #873
