### ISSUE TITLE
add Fox Farming V3 to mobile

### ISSUE THREAD

**Issue by notatooyou** [shapeshift/web#878]
Not actually in web repo, it is in the private centralized axiom repo, but we want it on this board to track the work.

Create a new Fox Farming opportunity - call it V3, instead of V2.

For testing, have it point to the current V2 smart contract. Make sure it is hidden from production. The new V3 contract will be deployed the week of 1/31 by @0xean  . He can update the ticket with that new contract address when it's ready.

Once it is tested and confirmed working with the V2 contract, we can then update to the V3 contract address, and then hide from Prod and be ready for launch end of Feb.

**Comment by SS-FOX-McCloud** [comment]
For mobile we need to ensure that once a user adds liquidity/received LP tokens that the staking CTA on the EARN page routes to staking/unstaking using the V3 contract.  If a user chooses to unstake their LP they should be shown any contracts (V1-V3) where they have tokens staked. 

 ![IMG_5331](https://user-images.githubusercontent.com/57505863/152214440-bc87d4b9-d968-45f1-8f28-6aa14d649def.PNG)
