### ISSUE TITLE
Autofocus AssetSearch input field (on desktop)

### ISSUE THREAD

**Issue by rbeer** [shapeshift/web#882]
It would be convenient, if the input in the AssetSearch component was auto focused.

### Considerations
- Makes sense in all places, except the AssetSidebar
- Should not auto focus on mobile devices; opens the screen keyboard automatically

### Implementation
- Add prop on AssetSearch, allowing parent components to control auto focus behavior; defaulting to `false`
- Use already present `react-device-detect` to never auto focus on mobile devices

rbeer/shapeshift-web@2036840

### Current behavior

https://user-images.githubusercontent.com/3411649/151930637-b27ab853-b737-44a3-bd33-03f6b87cad2e.mp4

**Comment by 0xdef1cafe** [comment]
@rbeer would you like to go ahead and PR your implementation of this?

**Comment by 0xean** [comment]
does product want to proceed with this change? @SS-FOX-McCloud  / @DiggyDiggy2

**Comment by DiggyDiggy2** [comment]
We don't want to proceed with this change. I don't like forcing the user into search, as not everyone wants to do that

**Comment by 0xean** [comment]
closing per product
