### ISSUE TITLE
SPIKE: How to decompose existing Yearn components

### ISSUE THREAD

**Issue by cjthompson** [shapeshift/web#892]
AC: write down a break down yearn components into smaller shareable components

 * Identify what can be used for Yearn/Cosmos (shared)
 * What parts of the existing yearn UI components would be Atoms, Molecules, Organisms, etc.
 * optional: create a few examples 

```
src/features
  components
    Atoms
      ...small individual components
    Molecules
      ...composed atoms (like a Fee row, or 1 steps in sidebar)
    Organisms
       ..composed molecules (Sidebar with steps 1/2/3)
```

**Comment by gomesalexandre** [comment]
WIP, living in this gist for now: https://gist.github.com/gomesalexandre/cfa9fa943bcdbbde36ca6e82a7889d01

**Comment by gomesalexandre** [comment]
@cjthompson You can take the CR state as a “let’s call and iterate from there”, it’s quite difficult to make a write up of this but I’ll be happy to go a bit more in depth during a call

**Comment by cjthompson** [comment]
I'm sorry but I don't understand what you're trying to say. What is "CR state"?

**Comment by gomesalexandre** [comment]
> I'm sorry but I don't understand what you're trying to say. What is "CR state"?

I meant moving the issue to Code Review state in the EPIC board. GitHub is quite bad at integrating the board into the rest of the flow, so I'll create a dummy PR for all future discussions.
