### ISSUE TITLE
DeFi - Balance isn't available for staking after swapping

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#907]
It looks like wallet balance isn't updated in DeFi after swapping.

Steps to reproduce:

1. Swap for an asset that's available in yearn and wait for your wallet's confirmation (for testing, I used some asset I currently don't have any amount of in wallet)
2. Wait for tx confirmed by Metamask
3. Go to DeFi and "Get started" into that asset's vault

Expected:

- No full page reload is necessary to see balance for that newly received asset
- Amount for asset should show as balance available to stake

Actual:

- 0 balance is shown
- Reload page, and go to that vault again, asset is now shown in balance

![image](https://user-images.githubusercontent.com/17035424/152310288-8058700d-5404-4e10-83d5-eeeb88b264c8.png)
![image](https://user-images.githubusercontent.com/17035424/152310221-b86a95b9-24d2-4497-ab95-d97d45e024d4.png)

**Comment by 0xdef1cafe** [comment]
also related to #706

**Comment by 0xean** [comment]
@gomesalexandre to prep for bounty.

**Comment by gomesalexandre** [comment]
- Tested on prod with an asset I didn't have in my wallet before swapping and this is still happening
- Tested on prod with an asset I had in my wallet already (and now have more of) and this seems fixed

**Comment by 0xean** [comment]
May have different behavior depending on if user already has asset balance.

**Comment by 0xean** [comment]
confirmed only on new assets.

**Comment by theoboldfrazier** [comment]
@gomesalexandre I'll take a look at bountying this one out, I think I have a good idea of what needs to be done.

**Comment by 0xean** [comment]
resolved with portfolio refetch.
