### ISSUE TITLE
Enable HSTS (HTTP Strict Transport Security) for *.shapeshift.com

### ISSUE THREAD

**Issue by mrnerdhair** [shapeshift/web#923]

**Comment by 0xdef1cafe** [comment]
@mrnerdhair to deploy this change when all of engineering and ops are on vacation together. gl. hf.

**Comment by 0xean** [comment]
We need information on sendgrid domains via axiom to move forward with this. 

@con5cience - can you review the PR from reid in croixdrinkers
@mrnerdhair - to dig into axiom / sendgrid domains.

**Comment by mrnerdhair** [comment]
Ref: https://github.com/shapeshift/security/issues/31

**Comment by theoboldfrazier** [comment]
@mrnerdhair Is there any update on this issue?

**Comment by 0xean** [comment]
closing as stale.
