### ISSUE TITLE
Chainlink Asset Balance Page not displaying properly on ALL time frame

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#930]
in App.shapeshift.com, the Chainlink asset page is not displaying properly. on the ALL Balance Graph on asset page showing a flat-lined graph, even with a balance showing above.

1. log into app.shapeshift.com with a wallet containing the chainlink token
2. go to the asset page for chainlink
3. click on balances and go to the ALL time tab
4. See flat-lined graph
![unknown (3)](https://user-images.githubusercontent.com/94986227/152566666-c2053c80-7643-4899-ac91-8f3a5a849e9c.png)

Triage Ticket Link: https://discord.com/channels/554694662431178782/873244924026449940/938556301896736778

**Comment by visitskyworld** [comment]
Similar to #939  - 429 error.

![image](https://user-images.githubusercontent.com/96882365/152855049-590d9010-fac1-4df5-9ade-3b12fb3c41f5.png)

**Comment by 0xean** [comment]
closing as resolved with rate limiting
