### ISSUE TITLE
Send Tx Modal QR code Bug

### ISSUE THREAD

**Issue by Neverwas-dev** [shapeshift/web#935]
- Brief description
When sending a tx and selecting QR reader button for first time if you exit the allow camera or not allow it will create a flow where it doesn't ask for an address and just moves to the continue screen where the amount is selected.

- Steps to recreate
1. Select an asset to send
2. Choose QR code
3. If first time using QR code for the device will as for permission to use the camera if you exit out or cancel it just goes to the continue screen and asks for a send amount with out a send address
4. If you out in an amount and select the next button (should be disabled if no send address)

- Screenshots/vids (add or add attachments
![image](https://user-images.githubusercontent.com/95000549/152573496-428f5725-04e8-4858-9d88-2728374fa105.png)

![image](https://user-images.githubusercontent.com/95000549/152573571-82be337f-5628-42f0-aae4-2191cb35eff0.png)

- Link to Discord
https://discord.com/channels/554694662431178782/873244924026449940/938556778734567424

- AC (acceptance criteria)
Create a graceful fail if a user doesn't approve the camera access to the device.

**Comment by 0xean** [comment]
Product to provide error messaging (@DiggyDiggy2 / @SS-FOX-McCloud )

**Comment by NeOMakinG** [comment]
@DiggyDiggy2 

![image](https://user-images.githubusercontent.com/14963751/156623793-735c7642-3b29-4f91-9da7-06c384c36142.png)

Here is a quick look at what I did in case the camera access has been declined, and if you click on "Cancel", it redirect you back to the address form

**Comment by SS-FOX-McCloud** [comment]
@NeOMakinG that error message is perfect. Once the user closes out of that error message they should be routed back to the first screen of the modal where they will enter in their address.  If they chose the QR button again they should be prompted to give camera permission again. (Or they can type in or copy/paste an address) Let us know if you have further questions.

**Comment by NeOMakinG** [comment]
> @NeOMakinG that error message is perfect. Once the user closes out of that error message they should be routed back to the first screen of the modal where they will enter in their address. If they chose the QR button again they should be prompted to give camera permission again. (Or they can type in or copy/paste an address) Let us know if you have further questions.

I've another question:

When they close the message, why do we want them to be redirected to the previous step? It looks not like a norma UX behavior to me, as an user, I would think that clicking on the close button, the modal would just disappear, but clicking on cancel, it would redirect me to the previous step

For example: When you click on the close button, you are not redirected to the asset list modal, it just close the modal. but if you click on cancel, it redirects you to do Asset List modal (Maybe the cancel wording is wrong too, because it should be called "Back"

wdyt?

**Comment by NeOMakinG** [comment]
Also, sorry but forgot something

We need to handle the fact that the user gives permission access while being in front of this error message

There is no way to listen to the permission event, which means that we need to ask the user to click on a button in case they gave the permissions

Here is my proposal

![image](https://user-images.githubusercontent.com/14963751/156628390-a593aa23-84d2-44f9-a1d3-a9afff2b9a17.png)

**Comment by SS-FOX-McCloud** [comment]
@NeOMakinG Good point! Lets go with that flow.  Change the button to "Back" and if the user clicks that they are taken back to the first modal screen where they can enter in the address or click the QR code icon (in which case they are prompted to allow camera access again) or if they "x" out of the modal, the modal will close completely.  We can also add your additional "I gave access permissions" button as well.  Thank you!

**Comment by DiggyDiggy2** [comment]
Can we please just use a blue button to be consistent with our UI? :)

**Comment by NeOMakinG** [comment]
We were talking about the wording with @gomesalexandre and we found out that it wasn't really clear for users, it should be understandable by everyone.

What do you think about this @DiggyDiggy2 ?

![image](https://user-images.githubusercontent.com/14963751/156658013-4d37dec9-62db-42b8-9a88-69387eac131d.png)

**Comment by DiggyDiggy2** [comment]
yeah, I think this works! I don't think we need a comma after "Please"
Is that the correct button style? it feels a little small.

**Comment by NeOMakinG** [comment]
> yeah, I think this works! I don't think we need a comma after "Please" Is that the correct button style? it feels a little small.

Alright, updated:
![image](https://user-images.githubusercontent.com/14963751/156817065-36e4703d-5262-4805-8aec-9d0db5ae1001.png)


Thanks for the feedback!
