### ISSUE TITLE
Custom Asset About sections

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#936]
Enable contributors to easily update about sections on the asset page.

Background Context: For assets that can only be acquired by depositing asset(s) into a DeFi strategy not yet supported natively in ShapeShift, we can make bounties for community members to research and write copy for each about section that provides some background on the asset along with instructions to the user on how to acquire this asset.

# Reference

This will need to be implemented under the asset service, as a hardcoded fallback file.

Please implement a `descriptions.json` file, which is a key/value map between the asset id (caip19) with a string containing the description, e.g.

```json
{
  "eip155:1/erc20:0x6c3f90f043a72fa612cbac8115ee7e52bde6e490": "3CRV is a Curve Finance pool token containing a mix of DAI, USDC, and USDT stablecoins."
}
```

The asset service will need to be modified here, to check for community contributed descriptions, before `finally` giving up and returning an error

https://github.com/shapeshift/lib/blob/main/packages/asset-service/src/service/AssetService.ts#L133

# Acceptance criteria
1. Contributors can make a pull request to a public repo to add custom about copy for each asset.
2. If an asset has custom about copy, this overrides any about copy that comes from external APIs (ie. Coingecko)

Example about section:
https://app.shapeshift.com/assets/ethereum/0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9
![image](https://user-images.githubusercontent.com/26232238/152573501-d6be667a-f8cf-45e8-913e-17ca6e2de35e.png)

Example of an asset with no about section:
https://app.shapeshift.com/assets/ethereum/0x6c3f90f043a72fa612cbac8115ee7e52bde6e490

**Comment by 0xdef1cafe** [comment]
closing and reopening under lib repo here https://github.com/shapeshift/lib/issues/345
