### ISSUE TITLE
Market data information not prefetched correctly

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#939]
Asset price information, value, and balance don’t initially load on the dashboard after logging in. It takes about 2-3 minutes for everything to load unless you click on each asset individually. 

Reproduce Steps
1. open https://app.shapeshift.com/ 
2. connect your wallet and arrive at the dashboard
3. certain assets won't load pricing information, value, and balance for 2-3 minutes unless you click on them individually

Link to the Triage Ticket https://discord.com/channels/554694662431178782/873244924026449940/938886580465184818
<img width="901" alt="Screen_Shot_2022-02-03_at_1 41 29_PM" src="https://user-images.githubusercontent.com/94986227/152578596-8e6f75e1-998e-4117-ac0d-9f42596e226d.png">

**Comment by visitskyworld** [comment]
That's because 429 error(Too many requests). When you click assets several times, coingekco api returns 429 error.

**Comment by 0xdef1cafe** [comment]
this requires a wallet with a large number of assets and is better suited to shapeshift engineering using an ops test wallet
