### ISSUE TITLE
Importing seedphrase into firefox incognito mode yields stuck after entering password and wallet name.

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#941]
When importing a seed phrase into app.shapeshift.com on firefox incognito mode, it gets stuck after trying to save the password and spins forever.

1. open a private browser in firefox and go to app.shapeshift.com
2. input seed phrase for the native wallet.
3. go to the password step and put in a password and wallet name and hit next
4. get the spinning loading circle forever.

Triage thread
https://discord.com/channels/554694662431178782/873244924026449940/938852190213259348

![stalling firefox incgonito](https://user-images.githubusercontent.com/94986227/152610403-858deb2b-2b8a-479a-9bea-997373193927.png)
f

**Comment by 0xdef1cafe** [comment]
console error message is `WalletProvider:NativeWallet:Start - Cannnot enumerate Vault DOMException: A mutation operation was attempted on a database that did not allow mutations.`

[this is a fundamental limitation of firefox in incognito](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API#private_browsing_incognito_modes)

this would be a big lift in comparison to the number of people using it and a lot of bike shedding around security/how to do this with respect to this corner case limitation.

happy to revisit in the future if this becomes a serious source of complaints.
