### ISSUE TITLE
Auto-generate icons for assets with no icon file

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#959]
As a user, I want to see a placeholder icon for tokens with no icon that includes up to 5 characters of the token's symbol

AC:
1. If an asset doesn’t have an icon, an icon is auto-generated using up to 5 characters of the token's symbol from the contract.
2. The Icon looks good with 3-5 characters and the characters are always centered within the icon (make font smaller for tokens with 4 or 5+ characters in the symbol)

**Comment by amitojsingh366** [comment]
I can take this up, I have done this before for user avatars in a project of my own before

**Comment by willyogo** [comment]
> I can take this up, I have done this before for user avatars in a project of my own before

@amitojsingh366 I just changed the AC for this from using jdenticon to auto-generating an icon using the token's symbol (ie. FOX). Do you still want to take this on?

**Comment by amitojsingh366** [comment]
> > I can take this up, I have done this before for user avatars in a project of my own before
> 
> @amitojsingh366 I just changed the AC for this from using jdenticon to auto-generating an icon using the token's symbol (ie. FOX). Do you still want to take this on?

wait I thought that's how you wanted it in the first place 🤣
so yeah sure, I can still take this

**Comment by willyogo** [comment]
awesome :D cc @0xdef1cafe to bountify this

**Comment by amitojsingh366** [comment]
@willyogo could you put a few assets that have no icons in the issue description, it'd be a big help for when I start working on this

**Comment by theoboldfrazier** [comment]
@willyogo @amitojsingh366 Moving conversation for this over to here because it appears to be more of a lib bounty.

https://github.com/shapeshift/lib/issues/354

**Comment by amitojsingh366** [comment]
@theoboldfrazier @willyogo the way I was thinking of doing this was just making a circular div an positioning the symbol as text in it accordingly, not sure how that is suited for lib 😕. Unless you had a different implementation in mind?

**Comment by theoboldfrazier** [comment]
@amitojsingh366 Yes. That makes sense to me. You will need some code in web. The idea behind moving it as a lib issue is that we want to make sure the icon generation is happening there.
