### ISSUE TITLE
ERC20 Asset blacklist

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#961]
Currently the app will display any ERC20 asset with a balance in your portfolio if it is on the asset list, and soon even assets not on the asset will be displayed too. There are a handful of known scam tokens that have been airdropped to many users' wallets and display misleading fiat values (ie. KICK and Minereum). As app maintainers, we want to be able to prevent known scam tokens from appearing in users' wallets and portfolios. Contributors should be able to make pull requests to an open source repo to add new known scam tokens to the blacklist.

AC:
1. The following assets no longer display in v2, even if users have a balance in their wallet:
KICK (0x426CA1eA2406c07d75Db9585F22781c096e3d0E0)
Minereum (0x426CA1eA2406c07d75Db9585F22781c096e3d0E0)
UNIH (0x4bf5dc91e2555449293d7824028eb8fe5879b689) 
0x7761c09EA2DE3F7205Dba784Fd87Fd196E019D2A
0x6f0371247d21d7afad6e624f6e8dbb3bff0455c2
0xF9d25EB4C75ed744596392cf89074aFaA43614a8
0x0f8b6440a1f7be3354fe072638a5c0f500b044be
0x1412ECa9dc7daEf60451e3155bB8Dbf9DA349933
0x34278F6f40079eae344cbaC61a764Bcf85AfC949
2. Contributors can make a pull request to add a token to the blacklist, and there are some instructions in the repo on how to do this
3. Any erc20s that are marked as Spam or Unsafe by Etherscan are added to the blacklist (https://info.etherscan.com/etherscan-token-reputation/)

**Comment by 0xdef1cafe** [comment]
closing and reopened in lib https://github.com/shapeshift/lib/issues/353
