### ISSUE TITLE
Cosmos: Create CosmosSendModal

### ISSUE THREAD

**Issue by cjthompson** [shapeshift/web#962]
AC:
 * create folder structure:
    ```
       src/features/cosmos/components/Modals
    ```
 * copy `src/components/Modals/Send` to `src/features/cosmos/components/Modals`
 * Remove all chain specific code from all files (as necessary, leave comment blocks to add Cosmos specific code later)
 * As possible, break up large components into small re-usable chunks
 * As possible, move components into `src/features/components`.

**Comment by gomesalexandre** [comment]
This is superseeded by https://github.com/shapeshift/web/issues/651 - working on #651 will close this.
