### ISSUE TITLE
Cosmos: Create CosmosReceiveModal

### ISSUE THREAD

**Issue by cjthompson** [shapeshift/web#967]
AC:
 * create folder structure (if it doesn't exist):
    ```
       src/features/cosmos/components/Modals
    ```
 * copy `src/components/Modals/Receive` to `src/features/cosmos/components/Modals`
 * Remove all chain specific code from all files (as necessary, leave comment blocks to add Cosmos specific code later)
 * As possible, break up large components into small re-usable chunks
 * As possible, move reusable components into `src/features/components`.

**Comment by theoboldfrazier** [comment]
see: https://github.com/shapeshift/web/pull/984/files
