### ISSUE TITLE
Asset icons are blurred on the asset page

### ISSUE THREAD

**Issue by NeOMakinG** [shapeshift/web#969]
![image](https://user-images.githubusercontent.com/14963751/153058383-6c9ced5f-47a9-48cd-a8d6-7b8aa2207db2.png)

While checking something, noticed that most of icons are blurred in the asset page, because they are smaller than the actual size it's displayed

# Solution

Use bigger icons, or reduce the display size of every icons in the card header

**Comment by 0xdef1cafe** [comment]
fixed in https://github.com/shapeshift/web/pull/966/commits/ef3864acee7032b436b30fd47c9bda36e5a511aa
