### ISSUE TITLE
Add toggle to show/hide assets with current zero balance and previous tx history

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#973]
# **DO NOT START WORK ON THIS ISSUE UNTIL PRODUCT HAS PROVIDED INPUT**

# Overview

On the dashboard page of the app, assets with previous non zero balance, but currently with zero value/amounts show up still under Your Assets on the dashboard page

# Reproduction steps

1. [Log in to the app](https://app.shapeshift.com/) with any wallet that had a previous balance of a token
2. wait for the dashboard to finish loading and scroll through assets to an asset with the previous balance
3. see that 0 balance assets are showing up

# Reference

* [See previous Discord discussion](https://discord.com/channels/554694662431178782/873244924026449940/940698327723413544)
* [Implementation detail is here](https://github.com/shapeshift/web/blob/develop/src/pages/Dashboard/components/AccountList/AccountList.tsx#L94-L102)

# Screenshots

![Screen_Shot_2022-02-09_at_2](https://user-images.githubusercontent.com/94986227/153066862-caf11be1-ea41-4b7d-9d67-68029ca71678.png)

# Acceptance criteria

* Toggle to hide/show asset with current zero and previous tx history implemented as per product spec @SS-FOX-McCloud @DiggyDiggy2 @reallybeard 

# Bounty Documentation 
- Please check out [our docs](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties) for how to get in touch with us or ask questions.

**Comment by reallybeard** [comment]
IDEA:
Add toggle above table, "Show small balances" with a tooltip that says "Show assets with balances below $1.00"

Mockup:
TBD

**Comment by SS-FOX-McCloud** [comment]
Issue is resolved in #1163
