### ISSUE TITLE
Back button on /defi route doesn't work

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#990]
# **IMPORTANT: NO BOUNTIES WILL BE PAID FROM 2/5 - 2/14 - IF YOU COMPLETE THIS BOUNTY DURING THIS TIMEFRAME WE WILL REMIT PAYMENT ON 2/14**

# Overview

The back button on the top left hand side of the `/defi` route links to nothing but works on the `/defi/earn` route. 

Recreation Steps:
1. [Go to ShapeShift and connect a wallet](https://app.shapeshift.com/)
2. Click on the defi button at the top of the page
3. Click on the earn button on the defi page
4. Click the back button twice and notice the button on `/defi/earn` works but not on `/defi`

# Acceptance Criteria
-Works in accordance with criteria specified by @SS-FOX-McCloud @DiggyDiggy2 @reallybeard 

# Bounty Documentation 
- Please check out [our docs](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties) for how to get in touch with us or ask questions.

**Comment by lohba** [comment]
@tshifty I would like to work on this
